const fs = require('fs');
const path = require('path');

// MÓDULO 1
const p1_m1 = "El Área 51 es, sin duda alguna, una de las instalaciones militares más famosas y misteriosas del mundo, pero su verdadera historia está muy alejada de las historias de extraterrestres y platillos voladores que solemos escuchar en la cultura popular. Ubicada en el sur de Nevada, a unos 130 kilómetros al noroeste de la ciudad de Las Vegas, se encuentra asentada junto al lecho seco de un lago conocido como Groom Lake. Esta vasta planicie de sal ha demostrado ser perfecta para construir pistas de aterrizaje extremadamente largas y seguras. Al estar rodeada de montañas y un inmenso desierto árido, ofrece una barrera natural inmejorable que protege la zona de miradas curiosas y de espías internacionales. Desde el principio, la Fuerza Aérea de los Estados Unidos y la Agencia Central de Inteligencia (CIA) comprendieron que para mantener el secreto absoluto sobre sus tecnologías en desarrollo, necesitaban un lugar aislado y hostil. Así nació esta base, no para ocultar marcianos, sino como el laboratorio aeroespacial más seguro del planeta.";
const p2_m1 = "El término 'Área 51' no tiene ningún origen místico ni alienígena; es simplemente la designación que este terreno recibió en los viejos mapas topográficos elaborados por la Comisión de Energía Atómica de los Estados Unidos (AEC). Durante los años 50, el Polígono de Pruebas de Nevada estaba dividido en varias cuadrículas numeradas para facilitar la organización y las detonaciones atómicas. A este pedazo de desierto le tocó el número 51. Para hacer el lugar más atractivo para los científicos e ingenieros que tenían que dejar a sus familias para mudarse a trabajar en medio de la nada, los líderes del proyecto, como Kelly Johnson de la compañía aeronáutica Lockheed, decidieron apodarlo cariñosamente 'Paradise Ranch' (El Rancho Paraíso). Este contraste entre la rudeza extrema del desierto y un apodo vacacional fue la primera de muchas medidas diseñadas para mantener la moral alta en condiciones de trabajo muy duras y aisladas.";
const p3_m1 = "Para entender por qué se construyó el Área 51, debemos retroceder a la época de la Guerra Fría, un periodo histórico de máxima tensión política y militar entre Estados Unidos y la Unión Soviética. En este contexto, ambas superpotencias vivían en el constante temor de un ataque nuclear sorpresivo y la información se convirtió en el recurso más valioso. Estados Unidos necesitaba desesperadamente saber qué tipo de aviones, misiles y bases estaban construyendo los soviéticos, pero no podían simplemente enviar tropas a averiguarlo. La solución fue la tecnología de vigilancia aérea: aviones espía capaces de volar tan alto que ningún misil o radar enemigo pudiera alcanzarlos. Para desarrollar y probar estos revolucionarios aviones en completo secreto, sin que los espías soviéticos (KGB) se enteraran, se necesitaba una pista de pruebas aislada de cualquier población civil o ruta comercial. Groom Lake era el lugar ideal.";
const p4_m1 = "La clasificación de la información es un concepto clave para entender por qué la base estuvo oculta durante décadas. Cuando un gobierno clasifica un proyecto como 'Top Secret' (Alto Secreto), no lo hace por malicia, sino por seguridad nacional. Imagina que inventas un candado irrompible para tu casa; si publicas en internet exactamente cómo lo fabricaste y cuáles son sus puntos débiles, los ladrones sabrán cómo abrirlo. Lo mismo ocurre con la tecnología militar: si se desarrollan radares invisibles o aviones furtivos, publicar los planos o la existencia del proyecto permitiría a los países adversarios crear armas para derribarlos o copiar la tecnología. Por esta sencilla pero crucial razón de protección táctica y estratégica, el gobierno de los Estados Unidos ocultó todas las actividades del Área 51. Los trabajadores debían firmar juramentos de silencio y ni siquiera podían revelar a sus propias esposas en qué estaban trabajando.";
const p5_m1 = "El nivel de secretismo en el Área 51 llegó a extremos verdaderamente fascinantes. Los ingenieros y pilotos que trabajaban en Groom Lake vivían una doble vida de película de espías. De lunes a viernes, volaban en aviones sin marcas (conocidos como los vuelos JANET) desde el aeropuerto de Las Vegas hasta la base secreta. Durante la semana, trabajaban largas jornadas bajo el implacable sol del desierto de Nevada. Si un satélite soviético estaba programado para pasar por encima de la órbita de Nevada, las alarmas de la base sonaban y todos los prototipos de aviones debían ser escondidos inmediatamente en hangares cerrados o bajo grandes toldos diseñados para engañar a las cámaras del espacio. El polvo del desierto jugaba a su favor, creando un camuflaje natural perfecto. Este meticuloso juego del gato y el ratón duró décadas y fue fundamental para el avance aeronáutico de occidente, demostrando que el verdadero misterio era humano, no alienígena.";
const p6_m1 = "La geografía de Nevada desempeñó un rol tan crucial como la tecnología misma. El desierto de Mojave es inhóspito, con temperaturas que superan fácilmente los 40 grados Celsius en verano y caen bajo cero en las noches de invierno. La falta de agua, las tormentas de polvo y la ausencia total de carreteras civiles hacían que un acercamiento terrestre no autorizado fuera prácticamente imposible o muy fácil de detectar. Además, el gobierno federal fue adquiriendo y expropiando kilómetros de tierras alrededor de la base a lo largo de los años, creando un perímetro de seguridad colosal vigilado por contratistas privados armados, apodados por los curiosos como los 'Camo Dudes' (Chicos camuflados) por su vestimenta de grado militar. A estos guardias de seguridad reales se sumaban sensores de movimiento en la tierra, detectores infrarrojos y patrullajes en helicóptero, asegurando que ninguna mirada indiscreta interrumpiera las pruebas de vuelo experimentales.";
const p7_m1 = "Con el tiempo, el secretismo absoluto, combinado con las luces extrañas en el cielo nocturno producto de las pruebas aéreas, creó el caldo de cultivo perfecto para las teorías de conspiración. A finales de la década de 1980, un hombre llamado Bob Lazar apareció en la televisión estadounidense afirmando haber trabajado en una instalación subterránea cerca del Área 51 conocida como 'S-4', donde supuestamente ayudó a aplicar ingeniería inversa a naves espaciales de origen extraterrestre. Aunque las afirmaciones de Lazar nunca pudieron ser probadas y su historial académico resultó ser dudoso e imposible de rastrear, su historia capturó la imaginación del público a nivel mundial. De la noche a la mañana, la verdadera base militar de pruebas aeronáuticas se convirtió en el epicentro global del fenómeno OVNI, oscureciendo los verdaderos e impresionantes logros científicos y de ingeniería que se llevaron a cabo allí por hombres de carne y hueso.";
const p8_m1 = "Fue apenas en el año 2013, más de medio siglo después de su fundación, que el gobierno de los Estados Unidos y la CIA reconocieron oficialmente la existencia del Área 51. Esto no se debió a una filtración extraterrestre, sino a una solicitud formal bajo la Ley de Libertad de Información (FOIA) realizada por el Archivo de Seguridad Nacional de la Universidad George Washington. La CIA desclasificó un informe de cientos de páginas sobre la historia del avión espía U-2 y el proyecto OXCART, en el cual finalmente se mencionaba de forma explícita el nombre 'Área 51' y se mostraba un mapa con su ubicación exacta en Groom Lake. El documento confirmó lo que los historiadores de aviación ya sabían: la base existió y existe con el único propósito de desarrollar aviones experimentales y realizar pruebas de sistemas de armas avanzadas en un entorno de seguridad controlada, desmintiendo de manera tácita cualquier involucramiento alienígena.";
const p9_m1 = "Hoy en día, el legado del Área 51 es uno de inmensa dualidad. Por un lado, la zona sigue siendo un imán inagotable para turistas de todo el mundo que viajan por la llamada 'Extraterrestrial Highway' (Autopista Extraterrestre) en busca de misterios, souvenirs en forma de alienígenas verdes y restaurantes temáticos. Por otro lado, sigue siendo el centro de investigación aeronáutica clasificada más importante del ejército estadounidense. La tecnología Stealth (que permite a los aviones evadir los radares), desarrollada y probada en el Área 51 en las décadas de los 70 y 80, revolucionó por completo la manera en que se entienden la física de ondas y la guerra moderna. Estos desarrollos tecnológicos tuvieron un impacto profundo no solo en la milicia, sino en la ciencia de los materiales y la aerodinámica que hoy en día beneficia a múltiples ramas de la ciencia y la tecnología comercial en nuestra sociedad.";
const p10_m1 = "Para concluir este módulo, es vital que los estudiantes comprendan la diferencia entre el secretismo militar real y la ciencia ficción. Es normal y prudente que las naciones mantengan secretos sobre su tecnología de defensa para salvaguardar a sus ciudadanos. Las bases secretas existen, las aeronaves experimentales existen, y las maniobras militares encubiertas son un hecho histórico documentado y comprobable. Al separar los hechos demostrables (la geografía aislada, los programas como el U-2, la necesidad de confidencialidad en la Guerra Fría) de la ficción especulativa (platillos voladores subterráneos, autopsias a extraterrestres grises), podemos apreciar el verdadero valor científico del Área 51. Fue y sigue siendo un monumento al ingenio humano, a la superación de los límites de la física aerodinámica y al esfuerzo de miles de ingenieros que trabajaron en el anonimato total para alcanzar las estrellas con tecnología creada aquí mismo, en nuestro planeta Tierra. Fuentes: Documentos Desclasificados de la CIA (2013), The National Security Archive George Washington University.";

// MÓDULO 2
const p1_m2 = "La historia de la aviación secreta en Groom Lake comienza en 1955 con el avión U-2, uno de los proyectos de ingeniería más asombrosos del siglo XX. Diseñado por el genio Kelly Johnson y su equipo de 'Skunk Works' de la corporación Lockheed, el U-2 fue encargado por la CIA con un propósito muy específico: volar sobre la Unión Soviética a una altitud que ningún avión de caza ni misil de la época pudiera alcanzar. El diseño del U-2 era extraordinario; parecía más un planeador gigante que un avión de guerra tradicional. Estaba construido con materiales extremadamente ligeros y poseía unas alas inusualmente largas y delgadas que le permitían planear en la delgada atmósfera de la estratosfera, superando los 70,000 pies de altitud (más de 21 kilómetros de altura). A esta altitud espectacular, el aire es tan fino que los pilotos debían utilizar trajes presurizados muy similares a los que usarían más tarde los astronautas de las misiones espaciales.";
const p2_m2 = "El desarrollo del U-2 fue tan secreto que ni siquiera la mayoría del gobierno estadounidense sabía de su existencia. Fue este mismo secretismo, sumado a la tecnología radical del avión, lo que desató la primera gran ola de avistamientos de OVNIs en Estados Unidos en los años 50. Para poner esto en contexto, a mediados de la década de 1950, los aviones comerciales volaban a altitudes que oscilaban entre los 10,000 y 20,000 pies, y los aviones militares más modernos de la época alcanzaban a lo sumo los 40,000 pies de altura. Cuando un U-2, pintado de un color metálico plateado en sus primeras versiones, sobrevolaba el cielo a 60,000 o 70,000 pies, estaba tan alto que cualquier persona en tierra, o incluso los pilotos de aviones comerciales que volaban más abajo, eran incapaces de identificar la forma del fuselaje o las alas, viendo únicamente un destello brillante y misterioso cruzando la bóveda celeste.";
const p3_m2 = "El efecto óptico que causaban los vuelos de prueba del U-2 al atardecer era impresionante y explica gran parte del misterio. A una altitud de 21 kilómetros, cuando el sol comenzaba a ocultarse en el horizonte terrestre y el cielo a nivel del suelo ya estaba oscuro, el U-2 seguía iluminado por los rayos directos del sol. Las largas y delgadas alas de plata del avión actuaban como enormes espejos reflectantes en la estratosfera. Desde el suelo, un observador vería una luz brillante y silenciosa flotando o moviéndose a gran velocidad en un cielo por lo demás nocturno. Al no haber ningún avión comercial capaz de volar a esa altura y al estar la forma de la aeronave oculta por la inmensa distancia, la mente humana buscaba la explicación más a mano impulsada por la naciente cultura pop: 'Debe ser una nave de otro planeta'. Esta ilusión óptica masiva fue el combustible principal del fenómeno OVNI.";
const p4_m2 = "La propia CIA, de hecho, se dio cuenta rápidamente de que el U-2 estaba provocando un aumento dramático en los reportes del Proyecto Libro Azul, la investigación oficial de la Fuerza Aérea sobre los OVNIs. Cuando recibían un reporte de un piloto comercial que afirmaba haber visto una 'luz cegadora' o un 'platillo' a miles de metros por encima de él, la CIA y la Fuerza Aérea cruzaban las coordenadas y los horarios del avistamiento con los registros de vuelo clasificados de las pruebas del U-2 en el Área 51. Resultó que más de la mitad de todos los avistamientos de OVNIs reportados en Estados Unidos a finales de la década de 1950 y durante los años 60 coincidían exactamente con los vuelos de los aviones de reconocimiento U-2 y, posteriormente, de los A-12 OXCART. Sin embargo, debido al juramento de secreto, los militares no podían explicar a la prensa ni a la población que los 'extraterrestres' eran en realidad pilotos estadounidenses.";
const p5_m2 = "Después del U-2, los ingenieros aeronáuticos se enfrentaron a un reto aún mayor: crear un avión que no solo volara extremadamente alto, sino que también fuera el más rápido jamás construido, capaz de superar la velocidad del sonido por varios múltiplos (Mach 3). Esto dio lugar al proyecto OXCART, que más adelante evolucionaría en el famoso SR-71 Blackbird. Para lograr volar a más de 3,500 kilómetros por hora, las leyes de la aerodinámica exigían que el avión tuviera formas completamente nuevas y extrañas, nunca antes vistas en la historia de la aviación. En lugar de tener una nariz redonda y alas rectas como los aviones de pasajeros, el SR-71 fue diseñado con un perfil hiper afilado, alas delta integradas en el fuselaje, curvas suaves y motores masivos que lo hacían parecer una verdadera nave espacial de ciencia ficción. Fue fabricado principalmente de titanio, un material resistente a las temperaturas extremas de la fricción del aire supersónico.";
const p6_m2 = "El A-12 y el SR-71 no solo eran rápidos, sino que fueron pioneros en lo que hoy conocemos como tecnología furtiva o 'Stealth' (invisibilidad al radar). Para reducir la huella del avión en las pantallas de radar enemigas, los ingenieros de Lockheed utilizaron formas geométricas inusuales y recubrimientos especiales de pintura negra que absorbían las ondas de radio. Cuando estos imponentes aviones negros en forma de cuña o 'raya voladora' realizaban pruebas sobre los cielos del Área 51 y sus alrededores, su apariencia era tan alienígena para el espectador promedio de los años 60 que de inmediato se consolidaba la idea de que el ejército estadounidense estaba probando naves de origen no terrestre. La verdadera magia no era marciana, era termodinámica, aerodinámica y pura ingeniería estadounidense revolucionando el siglo XX bajo el más estricto secreto de la historia moderna.";
const p7_m2 = "Para probar estas bestias de la velocidad en el Área 51, la CIA se enfrentó a un problema logístico colosal: los satélites espías soviéticos. Rusia, sabiendo de la existencia de Groom Lake, ajustaba periódicamente las órbitas de sus satélites fotográficos para tomar imágenes de la base secreta y descubrir en qué estaban trabajando los estadounidenses. En respuesta, la seguridad del Área 51 utilizaba horarios precisos basados en las órbitas satelitales rusas. A los trabajadores se les entregaba un calendario y se les indicaba en qué minutos exactos el satélite ruso pasaría por encima. Antes de ese momento, los aviones como el SR-71 debían ser escondidos a toda velocidad en hangares especiales. A veces, para engañar a los satélites soviéticos, se construían siluetas de cartón o madera pintadas para simular aviones falsos y despistar a la inteligencia rusa, provocando una guerra de engaños digna del mejor thriller de espionaje.";
const p8_m2 = "Con el tiempo, la evolución de los aviones secretos en el Área 51 continuó con el desarrollo de aeronaves como el F-117 Nighthawk en la década de 1970 y 1980. El F-117 fue el primer avión puramente 'stealth' diseñado operativamente. Debido a la necesidad imperiosa de reflejar las ondas de radar lejos de los receptores enemigos, este avión estaba compuesto por un fuselaje completamente angular, lleno de facetas planas como si fuera un diamante oscuro. Carecía por completo de curvas aerodinámicas convencionales, lo que lo hacía tan poco aerodinámico que solo podía volar gracias a un complejo sistema informático de control de vuelo 'fly-by-wire'. Esta bestia angular negra y silenciada, volando bajo y a oscuras sobre los cielos nocturnos del desierto de Nevada, fue responsable de una nueva ola de avistamientos de OVNIs, particularmente de los llamados 'triángulos negros voladores'.";
const p9_m2 = "La historia de estos aviones nos enseña que el desarrollo de la tecnología de vanguardia muchas veces se confunde con magia o con lo sobrenatural cuando el público no tiene la formación técnica para entenderla. Los materiales exóticos como el titanio, las pinturas absorbentes de radar, las altitudes estratosféricas extremas y las formas aerodinámicas rompedoras crearon visualmente la apariencia exacta que Hollywood y las revistas de ciencia ficción nos decían que debían tener los platillos voladores. La ironía es que el gobierno de EE.UU. prefería que la gente creyera en extraterrestres antes que en su tecnología militar avanzada, ya que los rumores sobre naves alienígenas servían como una excelente cortina de humo mediática. Mientras los periódicos hablaban de 'hombres verdes', la CIA y la Fuerza Aérea podían seguir probando sus innovaciones furtivas en la tranquilidad de la ignorancia pública.";
const p10_m2 = "En resumen, la gran mayoría de los mitos que vinculan al Área 51 con tecnología de otros mundos nacieron de la observación parcial e incomprensible de los mayores logros de la aeronáutica humana. Desde los planeadores estratosféricos plateados como el U-2, pasando por los monstruos de titanio supersónicos Mach 3 como el SR-71 Blackbird, hasta los diamantes negros invisibles como el F-117, todos ellos nacieron, fueron probados y volaron desde la inmensa pista salada de Groom Lake. Al comprender la física de la luz reflejada a gran altitud, la necesidad del vuelo supersónico y los imperativos de la tecnología de sigilo, podemos desmitificar completamente las luces en el cielo nocturno. El verdadero secreto del Área 51 nunca estuvo oculto en las estrellas, sino en el genio y la dedicación incansable de los ingenieros humanos que empujaron las fronteras de la aviación. Fuentes: CIA FOIA Reading Room, Lockheed Martin Skunk Works History.";

// MÓDULO 3
const p1_m3 = "El Origen de los Rumores extraterrestres comenzó paradójicamente antes de que el Área 51 se convirtiera en la meca aeronáutica que es hoy, y su epicentro se ubicó en un polvoriento pueblo de Nuevo México llamado Roswell en el año 1947. Para entender cómo nace un mito urbano tan colosal, debemos estudiar el comportamiento humano y la sociología de la información. Cuando el cerebro humano observa un fenómeno en el cielo que no logra clasificar ni entender de inmediato, intenta buscar la explicación más cercana en su base de datos cultural. Tras el final de la Segunda Guerra Mundial y el inicio de la era atómica y los cómics de ciencia ficción, la idea de vida en otros planetas estaba muy presente en el imaginario colectivo estadounidense. Fue en este clima social tenso e imaginativo donde un evento militar altamente secreto chocó de frente con un granjero local y una base aérea asustada, provocando el mayor mito del siglo XX.";
const p2_m3 = "A mediados del verano de 1947, un ranchero llamado W.W. 'Mac' Brazel descubrió esparcidos por sus tierras en el desierto unos misteriosos restos metálicos y pedazos de materiales extremadamente extraños. Recogió algunas láminas que parecían de papel aluminio pero que no se rompían al arrugarlas, varillas de una madera muy ligera similar a la balsa, cintas adhesivas con símbolos extraños que parecían jeroglíficos y pedazos de goma y látex oscuro. Brazel, desconcertado por el hallazgo, llevó el material a la oficina del sheriff local, quien a su vez notificó a la base aérea militar de Roswell. Inicialmente, los militares que acudieron al lugar, sin tener el panorama completo debido a la estricta departamentalización del secreto militar de la Guerra Fría, emitieron un comunicado de prensa precipitado y sorprendente: anunciaron que habían recuperado los restos de un 'disco volador' o 'platillo volador' estrellado.";
const p3_m3 = "El anuncio oficial del ejército causó un revuelo mediático instantáneo en todos los periódicos del país. Sin embargo, en cuestión de pocas horas, las autoridades militares de mayor rango en Washington intervinieron drásticamente, obligando a los oficiales de Roswell a retractarse de inmediato. Emitieron un segundo comunicado oficial afirmando que todo había sido una gran confusión y que los extraños restos metálicos encontrados en el rancho no pertenecían a ninguna nave espacial alienígena, sino simplemente a un globo meteorológico convencional que se había estrellado a causa del mal tiempo. El ejército incluso publicó fotos de un oficial mostrando restos de un globo de papel aluminio en la oficina para calmar las aguas. Aunque la prensa aceptó la rectificación en ese momento y la historia se enfrió, las enormes contradicciones iniciales dejaron sembrada una semilla de duda permanente en la cultura popular que no haría más que crecer con el tiempo.";
const p4_m3 = "Esa pequeña semilla de duda floreció gigantesca tres décadas después, durante los años 70 y 80, cuando investigadores civiles de fenómenos aéreos anómalos desenterraron las viejas noticias y comenzaron a entrevistar a testigos del evento de 1947. Los testigos, ya en edad avanzada, hablaban de gran secretismo militar, de acoso por parte del gobierno, e incluso comenzaron a añadir, con el paso de los años, testimonios sobre recuperación de 'cuerpos pequeños de grandes cabezas'. El vacío de información, creado deliberadamente por el gobierno para proteger sus intereses de defensa, fue rellenado creativamente por escritores y teóricos de la conspiración. Se escribieron docenas de libros bestsellers afirmando que Estados Unidos ocultaba naves alienígenas estrelladas, no solo en Roswell, sino que los restos habían sido llevados para su investigación secreta en el desierto de Nevada, específicamente a Groom Lake, el Área 51.";
const p5_m3 = "Pero ¿cuál fue la verdadera ciencia y la historia clasificada detrás del incidente de Roswell? La respuesta fue desclasificada en la década de 1990 por las Fuerzas Aéreas de Estados Unidos, que finalmente admitieron que la historia del 'globo meteorológico' había sido efectivamente una mentira piadosa, una tapadera oficial, pero no para ocultar marcianos. Los misteriosos restos que el señor Brazel encontró en su rancho correspondían a un proyecto hiper-secreto estadounidense conocido como el 'Proyecto Mogul'. Durante los primeros años de la Guerra Fría, antes de la existencia de satélites espías y de aviones supersónicos de reconocimiento, el gobierno de los Estados Unidos necesitaba desesperadamente un método de vigilancia para saber si los soviéticos estaban detonando bombas atómicas al otro lado del planeta. El Proyecto Mogul fue su primera solución tecnológica brillante y rústica a la vez.";
const p6_m3 = "El concepto científico detrás del Proyecto Mogul se basaba en la propagación acústica en la atmósfera. Los científicos militares, dirigidos en parte por investigadores civiles de universidades prestigiosas, sabían que existía un 'canal de sonido' en la alta atmósfera o tropopausa. En este canal de presión y temperatura específicas, las ondas sonoras de baja frecuencia (los estruendos producidos por explosiones masivas como las detonaciones nucleares) podían viajar miles y miles de kilómetros rebotando alrededor de la curvatura terrestre sin disiparse por completo. La idea era colgar micrófonos extremadamente sensibles y transmisores de radio en trenes gigantes de globos de gran altitud. Estos enormes conjuntos de globos ascenderían hasta el canal de sonido y simplemente se quedarían 'escuchando' cualquier eco sordo provocado por una prueba nuclear rusa al otro lado del océano, permitiendo a EE.UU. rastrear el avance nuclear enemigo.";
const p7_m3 = "Los equipos que se colgaban de estos globos gigantes del Proyecto Mogul eran pesados y debían ser fácilmente rastreables por los radares de las bases terrestres militares para no perderlos de vista. Por este motivo, el equipo de ingeniería diseñó reflectores de radar de apariencia muy extraña construidos con materiales cotidianos de la época pero ensamblados de forma inusual: largas varillas cruzadas de madera balsa ultraligera y recubiertas con una lona recubierta de aluminio. Curiosamente, gran parte de esta cinta adhesiva y tela reforzada utilizada en la fabricación de los reflectores había sido comprada a una fábrica de juguetes neoyorquina que, para decorar sus productos, utilizaba cintas moradas con motivos florales abstractos que a simple vista parecían letras extrañas. Esto explica a la perfección las varillas, los metales que no se rompían y los supuestos 'jeroglíficos extraterrestres' reportados por los testigos civiles en Roswell en 1947.";
const p8_m3 = "Lo que sucedió en junio de 1947 fue que el Vuelo Número 4 del Proyecto Mogul, lanzado desde la Base de la Fuerza Aérea de Alamogordo, sufrió problemas técnicos y fue derribado por los fuertes vientos del desierto de Nuevo México, esparciendo cientos de metros de reflectores de radar recubiertos de papel aluminio, balsa y polímeros directamente sobre las tierras de Mac Brazel. Cuando el granjero llevó los restos a la policía local y el ejército fue a recuperar el material, se enfrentaron a un problema de seguridad nacional crítico: si explicaban abiertamente que se trataba de tecnología diseñada para escuchar bombas nucleares rusas, los soviéticos descubrirían de inmediato las capacidades de espionaje estadounidenses y desarrollarían contramedidas. Fue infinitamente preferible para la seguridad nacional inventar una mentira inocua (el famoso globo meteorológico convencional), aunque ello significara avivar los rumores platillistas iniciales del público.";
const p9_m3 = "El mito de Roswell y su posterior vinculación umbilical con el Área 51 nos enseña una valiosa y poderosa lección sobre la psicología social humana y el comportamiento de las instituciones. Cuando se junta la información incompleta, el secretismo gubernamental extremo y la imaginación activa de una población estimulada por la ciencia ficción cinematográfica, el resultado es inevitablemente un mito moderno resistente al paso de los años. Incluso después de que la Fuerza Aérea de EE.UU. desclasificó los planos completos, los manuales y los registros de vuelo exactos del Proyecto Mogul en la década de los 90 (un reporte masivo de cientos de páginas llamado 'El Informe Roswell: Caso Cerrado'), gran parte del público se negó a creer la explicación, afirmando que el nuevo documento era otra mentira oficial más y prefiriendo quedarse con la historia del complot extraterrestre que resultaba mucho más atractiva para el entretenimiento.";
const p10_m3 = "Para cerrar este módulo analítico, debemos reflexionar sobre la importancia de leer documentos históricos reales y aplicar el rigor de la historia antes de saltar a conclusiones fantásticas. El Proyecto Mogul fue un verdadero triunfo de la ciencia acústica y atmosférica de posguerra, implementado con una astucia táctica notable. Ocultar su propósito y los restos de sus materiales bajo una montaña de desinformación fue una maniobra defensiva propia del ajedrez de la Guerra Fría. Los restos metálicos en el desierto no fueron un fallo de ingeniería galáctica ni mensajeros de Zeta Reticuli; fueron sencillos reflectores de madera y aluminio de un país intentando 'escuchar' secretamente la creación de la bomba atómica en el hemisferio oriental. La ciencia militar documentada, desprovista del aura de la ciencia ficción, es una historia mucho más compleja, humana y fascinante que cualquier relato de ciencia ficción especulativa que podamos inventar. Fuentes: United States Air Force Roswell Report (1995), The New York Times Archives.";

// MÓDULO 4
const p1_m4 = "Ciencia Real vs. Ciencia Ficción es uno de los temas más fundamentales al discutir sobre tecnología aeroespacial y, particularmente, sobre los rumores que rodean a bases militares secretas. Desde los años 50, el cine, la televisión y los cómics nos han bombardeado con imágenes de platillos voladores perfectos, capaces de acelerar instantáneamente, cambiar de dirección en ángulos rectos y viajar entre sistemas solares sin hacer ruido. Sin embargo, en el mundo real, regido por las leyes de la física newtoniana y la termodinámica, los viajes espaciales humanos son ruidosos, inmensamente costosos, sucios, caóticos y requieren cantidades astronómicas de combustible líquido. La tecnología humana, por más avanzada que sea y por muy escondida que esté en hangares secretos en el desierto de Nevada, no puede violar los principios básicos de acción y reacción y la conservación de la energía, lo cual la hace muy distinta a la fantasía cinematográfica.";
const p2_m4 = "Empecemos por comprender cómo se mueve realmente un cohete humano, como los que estudian en Space Camp Academy, y cómo difiere esto de los supuestos OVNIs de las películas. Los cohetes reales (desde el Saturno V que fue a la luna hasta los modernos Falcon 9 de SpaceX) funcionan expulsando masa hacia atrás a gran velocidad para ganar impulso hacia adelante, siguiendo la Tercera Ley de Isaac Newton. Esto requiere llevar a bordo miles de toneladas de combustible y oxígeno líquido (oxidador) sumamente inestables y explosivos. Más del 80% del peso total de un cohete espacial en la plataforma de lanzamiento es puro combustible que se consumirá en cuestión de unos pocos minutos para poder escapar de la feroz atracción de la gravedad de la Tierra. Este es un proceso dominado por explosiones controladas masivas, fuego rugiente, ruido ensordecedor y vibraciones capaces de destruir estructuras cercanas.";
const p3_m4 = "En total contraste, las naves extraterrestres descritas por las teóricas populares de la conspiración de los años 50 y que, según afirman los mitos urbanos, el gobierno escondería para estudiarlas en el Área 51, no parecen depender de la expulsión de gases para la propulsión química tradicional. Testigos de avistamientos afirman ver platillos moviéndose en un absoluto y mortal silencio, deteniéndose en seco a miles de kilómetros por hora y luego salir disparados verticalmente hacia las estrellas. Si un objeto con la masa de un avión comercial o un automóvil sufriera una aceleración instantánea de esa magnitud, las fuerzas G (gravedad) aplastarían cualquier materia biológica (humana o extraterrestre) en su interior, convirtiéndolos en pasta en el fondo de los asientos. Y, si el objeto cortara el aire terrestre a esa velocidad sin una forma aerodinámica afilada (como el SR-71), la fricción atmosférica fundiría el metal instantáneamente, convirtiendo la nave en un meteoro ardiente.";
const p4_m4 = "El fenómeno cinematográfico y cultural del platillo volador tiene un origen que también merece la pena analizarse desde la psicología mediática de masas. El término 'platillo volador' ni siquiera surgió de un supuesto avistamiento real de una nave en forma de disco. El término nació en el verano de 1947, poco antes de Roswell, cuando un piloto civil llamado Kenneth Arnold, volando cerca del Monte Rainier en Washington, informó haber visto objetos brillantes volando en formación. Cuando los periódicos lo entrevistaron, Arnold describió el movimiento de los aparatos diciendo que saltaban por el aire 'como si lanzaras un platillo a través del agua' (haciendo un símil de salto de rocas en un lago). El periodista de la agencia Associated Press malinterpretó la frase y escribió un titular explosivo alegando que el piloto había visto 'objetos en forma de platillo' (Flying Saucers). Así, por un error de traducción periodística, nació la forma estética dominante de los alienígenas en Hollywood por todo un siglo.";
const p5_m4 = "Mientras los teóricos de la conspiración invierten su tiempo y dinero acampando fuera de la verja electrificada del Área 51 esperando presenciar una anomalía galáctica en un cielo controlado por radares militares, la verdadera búsqueda científica del espacio exterior es liderada abiertamente y a la vista de todo el público mundial por agencias espaciales como la NASA, la Agencia Espacial Europea (ESA) y grandes corporativos aeroespaciales privados de la última década. La búsqueda científica moderna y real de vida más allá de la Tierra (la disciplina académica seria conocida como Astrobiología) no se basa en autopsias borrosas de maniquíes grises ni en el estudio secreto de platillos en hangares blindados subterráneos; se fundamenta en un meticuloso, lento, fascinante y complejo análisis matemático de luz proveniente del espacio profundo, buscando anomalías químicas en la composición atmosférica de otros sistemas solares.";
const p6_m4 = "Para encontrar vida hoy en día, los científicos reales emplean la fuerza titánica de la astronomía computacional a través del telescopio espacial James Webb y otros gigantes astronómicos en tierra y espacio. Cuando observamos una estrella lejana y notamos que un planeta gigante (un exoplaneta) pasa por delante de ella oscureciendo su luz en el llamado tránsito planetario, el James Webb utiliza espectrometría de altísima precisión para analizar cómo los gases de la atmósfera de ese planeta lejano absorben los rayos de luz de la estrella anfitriona. Al desglosar esa luz absorbida y analizar las longitudes de onda faltantes como un código de barras lumínico, los astrofísicos pueden deducir exactamente si la atmósfera contiene metano, vapor de agua, oxígeno libre o dióxido de carbono. Si llegasen a encontrar altos niveles de ciertos biomarcadores o biofirmas de manera desproporcionada (por ejemplo, oxígeno masivo que no debería existir a largo plazo), sería un sólido indicio de vida orgánica.";
const p7_m4 = "Además del estudio de atmósferas exoplanetarias por espectroscopía, otra área vital y realista en la búsqueda de contacto interestelar es el proyecto SETI (Search for Extraterrestrial Intelligence o Búsqueda de Inteligencia Extraterrestre). SETI es una iniciativa científica civil y pacífica global que utiliza inmensas redes de radiotelescopios parabólicos gigantes que barren el cosmos las 24 horas del día. En lugar de estar mirando físicamente el cielo nocturno buscando luces brillantes visuales o esferas danzantes, los científicos de SETI apuntan inmensas antenas al corazón de nuestra galaxia y más allá, escuchando matemáticamente frecuencias de radio del espectro electromagnético intentando detectar cualquier patrón estructurado, ordenado y matemáticamente repetitivo, como números primos o señales binarias. Si existe una civilización súper avanzada allá afuera enviando sondas a través de los años luz o simplemente comunicándose entre sí, lo primero que deberíamos detectar matemáticamente no sería una nave rompiendo la barrera del sonido, sino la emisión de su tráfico electromagnético regular cruzando el vasto éter espacial.";
const p8_m4 = "Parte de la educación espacial en un campamento de ciencias moderno y avanzado requiere la desmitificación contundente de la cultura popular pseudo-científica, porque la pseudociencia de las conspiraciones empobrece nuestra percepción y comprensión de lo que los humanos realmente podemos lograr cuando trabajamos juntos de forma metódica y rigurosa. Aceptar que el gobierno simplemente recogió un platillo estrellado mágicamente avanzado para realizarle ingeniería inversa y copiar ciegamente los motores de gravedad e inventar así la fibra óptica y los microchips transistores en la Tierra (como alegan teorías clásicas sobre Roswell) es, honestamente, un enorme insulto intelectual al trabajo de miles de mentes pioneras brillantes de posguerra de carne y hueso (como los laboratorios Bell, inventores reales del transistor en Nueva Jersey tras la guerra). El progreso tecnológico es acumulativo, arduo, iterativo, costoso y cien por ciento humano, no un robo tecnológico a exploradores intergalácticos caídos.";
const p9_m4 = "La idea de que una civilización alienígena capaz de cruzar la monstruosa y gélida distancia del espacio interestelar dominando los viajes a la velocidad de la luz y manipulando el espacio-tiempo termine estrellándose accidentalmente en un desierto mexicano debido a una simple tormenta eléctrica (como argumenta el mito de Roswell) desafía absolutamente la lógica analítica de cualquier ingeniero serio. Una civilización interestelar capaz de superar las leyes de Newton de la forma en la que vemos en las películas, con campos de energía invisibles o portales cósmicos, probablemente dominaría su destino de forma absoluta y no caería derribada por un rayo de atmósfera como un globo civil. Los cohetes humanos actuales (nuestra tecnología más primitiva en comparación interestelar) vuelan en condiciones atmosféricas mucho peores con sofisticados protocolos computarizados e instrumentos redundantes y escudos electromagnéticos integrados sin caer todos los días de manera estrepitosa.";
const p10_m4 = "En resumen de este módulo, al comparar la ciencia real, tangible y desafiante de las misiones espaciales y la astrofísica observacional contra los relatos ficticios de invasores de cabeza grande y bases subterráneas del Área 51, es importante reconocer el inmenso valor del entretenimiento de la ciencia ficción de Hollywood, pero mantenerlo estrictamente separado del rigor histórico y científico. La verdad objetiva nos enseña que el Área 51 es, en efecto, real e importante, pero su historia real trata sobre ingeniería metalúrgica, sobre superar la resistencia del viento, crear cámaras presurizadas habitables y aviones de sigilo de titanio en el corazón de un desierto asoleado. Por lo tanto, el trabajo de exploración del cosmos continúa afuera en los laboratorios de astrofísica y en el constante desarrollo del pensamiento riguroso. Fuentes: Scientific American Astrobiology (2020), NASA Exoplanet Exploration Program, The SETI Institute.";

// MÓDULO 5
const p1_m5 = "El Equipo de Detección de Camelos (o Baloney Detection Kit en inglés) es una de las herramientas intelectuales más poderosas de la educación moderna en pensamiento crítico. Fue conceptualizado y popularizado por el gran astrónomo, cosmólogo y educador científico Carl Sagan en su maravilloso libro 'El mundo y sus demonios: la ciencia como una luz en la oscuridad' publicado a mediados de la década de los años 90. Sagan, preocupado por el auge incesante de las noticias falsas, las pseudociencias, la credulidad mediática irracional ante los ovnis, los fantasmas y la charlatanería en televisión, se dio cuenta de que la educación científica tradicional estaba fallando. No era suficiente con enseñarle a las personas datos de biología celular, física newtoniana o tablas astronómicas; lo fundamental y urgente era enseñarles el riguroso método de pensar de un científico racional. Enseñarles a cuestionar críticamente las historias fantásticas que consumían a diario en los periódicos y programas matutinos sin el más mínimo filtro de comprobación veraz.";
const p2_m5 = "La primera gran regla del Equipo de Detección de Camelos de Carl Sagan se resume en una sola frase legendaria que todo estudiante de ciencias o astronomía debe tatuarse en la memoria: 'Las afirmaciones extraordinarias requieren evidencias extraordinarias'. Esta máxima lógica establece que, si alguien te dice algo común y corriente (por ejemplo: 'tengo un perro negro labrador en el patio trasero de mi casa'), no necesitas exigirle fotos, pruebas genéticas o testigos presenciales, basta con creer en su palabra porque no es inusual que alguien tenga un perro en el mundo moderno. Pero, si esa misma persona afirma: 'tengo un platillo volador con motores cuánticos escondido y estacionado bajo tierra en mi patio', esa es una afirmación tan monstruosa y revolucionaria para la historia de la humanidad, que creerle a ciegas solo porque 'parece confiable o juró decir la verdad' sería sumamente irresponsable e irracional desde el rigor probatorio. Esa afirmación demanda la máxima carga de evidencia tangible del mundo real para ser creída como un hecho.";
const p3_m5 = "El segundo concepto crucial que enseñó Sagan en su manual es la idea de la 'falsabilidad', que es el principio central de la filosofía de la ciencia propuesta por Karl Popper. Para explicarlo de forma lúdica a las personas de cualquier edad, Carl Sagan inventó la famosa analogía filosófica conocida como 'El Dragón en mi garaje'. Imagina que yo te digo que en mi garaje vive un enorme y poderoso dragón que escupe fuego ardiente. Tú, asombrado por la noticia, me pides ir de inmediato a verlo con tus propios ojos. Entramos al oscuro garaje juntos, pero no ves nada y me dices 'no veo al dragón'. Yo te respondo inmediatamente: 'Ah, lo que pasa es que olvidé decirte que es un dragón invisible a la vista de las personas normales'. Entonces, te proponen ideas lógicas de comprobación. Tú ofreces esparcir harina suave por todo el piso para ver de este modo las huellas grandes que deje al caminar. Yo respondo nuevamente con una excusa prefabricada: 'Esa es muy buena idea, pero mi dragón invisible resulta que siempre flota en el aire a un metro del piso, así que no dejará pisadas'.";
const p4_m5 = "La historia del Dragón no termina ahí. Decidido a comprobarlo por ti mismo utilizando el método científico riguroso, sacas una cámara infrarroja sofisticada para detectar la alta firma de calor del fuego que lanza y la pones apuntando hacia mi oscuro garaje, pero una vez más no se detecta absolutamente nada en la pantalla. Y yo sigo sumando mis excusas convenientes: 'Ah, resulta que su fuego mágico es un fuego que no emite absolutamente ningún calor radiante detectable para la ciencia humana moderna'. Por último, tú propones pintar todo el recinto del garaje entero con un bote de aerosol morado de golpe para que la figura del gran dragón flotante de repente quede delineada. Pero yo, sin dudarlo y esquivando el argumento, te digo: 'Es un dragón inmaterial e incorpóreo, la pintura simplemente lo atravesaría de lado a lado sin mancharlo ni tocarlo en lo absoluto'. La parábola continúa así, excusa tras excusa en cada intento racional de demostración científica tangible y observable que tú intentas de forma sincera y analítica estructurada metódicamente.";
const p5_m5 = "Sagan plantea la pregunta analítica final y definitiva en su historia educativa del garaje: ¿Cuál es exactamente la gran diferencia matemática, científica o lógica entre un dragón inmaterial, inodoro, que flota invisiblemente emitiendo fuego sin calor, incapaz de dejar rastro o ser rociado por ningún tipo de pintura de prueba física en todo el mundo, y la posibilidad simple y llana de que absolutamente NO HAY NINGÚN DRAGÓN en lo absoluto en la habitación real? La respuesta metodológica rigurosa es clara: ninguna diferencia tangible objetiva ni empíricamente demostrable. Si una teoría sobre el mundo natural está estructurada de tal manera enrevesada e infalsable que siempre esconde excusas inmateriales o irrefutables pre-preparadas frente a cualquier evidencia analítica contraria, imposibilitando cualquier diseño de experimento neutral empírico y metódico que pueda demostrar empíricamente que la idea fundamental es errónea si lo fuese, entonces esa loca teoría simplemente no puede considerarse parte integral del dominio válido analítico de la ciencia rigurosa o real del método universal.";
const p6_m5 = "Esta asombrosa lección sobre el Dragón Falso aplica directamente al gran mito del Área 51 y de los secretos alienígenas gubernamentales clásicos divulgados en todos los periódicos desde finales del siglo. A menudo, los promotores o líderes más mediáticos de las viejas teorías de ovnis y extraterrestres utilizan argumentos irrefutables idénticos (el Dragón sin calor ni rastros demostrables): 'Los videos borrosos no son pruebas porque el gobierno malvado ya borró sistemáticamente de internet o incautó a los civiles todas las cintas claras con evidencias contundentes físicas tangibles fotográficas', 'Nadie vivo puede dar la cara porque si los investigadores hablaran serían automáticamente silenciados eternamente o encarcelados', 'No tenemos ninguna pieza física material o artefacto alienígena medible o sujeto al microscopio químico riguroso de carbono porque todo el material es resguardado secretamente bajo tierra de Nevada en hangares del S-4 de acceso negado herméticamente'. Esta construcción conceptual paranoica previene ciegamente que la narrativa conspiranoica fantástica sea derribada lógicamente, anulando activamente el método científico de análisis básico estructural analítico deductivo.";
const p7_m5 = "La tercera herramienta fundamental indispensable dentro de tu nuevo maletín intelectual o kit mental de pensamiento crítico es un antiquísimo pero contundente principio filosófico y lógico conocido universalmente por todos los pensadores científicos de la historia europea como La Navaja de Ockham. El postulado original nos dice, básicamente, que cuando estás intentando desesperadamente de explicar un misterio, un fenómeno anómalo de observación repentina nocturna en los cielos profundos, y tienes en mente dos hipótesis que explican teóricamente a la perfección las partes observadas por tu ojo, la explicación lógica más sencilla (la que requiere inventar desesperadamente muchas menos entidades, componentes imposibles o supuestos irracionales fantasiosos increíbles de antemano) suele ser, casi en su totalidad de las ocasiones de estudios astronómicos o psicológicos, la gran ganadora metodológica universal correcta del caso en particular. Y es un argumento verdaderamente afilado al extremo, de ahí su brillante e inteligente denominación de Navaja aguda o cuchilla destructora de mitologías humanas complejas.";
const p8_m5 = "Aplica firmemente esta filosa y aguda Navaja mental analítica de Ockham de manera implacable a un escenario clásico imaginario del curso general básico: Imagina vívidamente por un momento oscuro que a media noche clara, mirando fijamente la fría llanura desértica estrellada sobre las enormes dunas de arena en Nevada, tú de repente logras ver pasar a gran velocidad rasante silenciosa un brillante y alargado tubo oscuro cruzando audazmente la luz estelar a kilómetros y kilómetros inmensos por encima de la nube principal. Tienes, pues, en mente las siguientes dos explicaciones teóricas viables y antagónicas que explicarían tus impresiones de retina. Explicación 1: Una vasta civilización alienígena de seres no biológicos construyó un vehículo curvador de tiempo y se las arregló exitosamente contra todo pronóstico termodinámico de colisiones galácticas durante tres millones enteros de años luz espaciales de distancia para llegar puntualmente a ver el oscuro y aislado desierto seco norteamericano específicamente una noche de frío enero en particular para pasar rozando discretamente sin contacto o diálogo humano alguno.";
const p9_m5 = "Ahora analicemos la otra cara de la filosa hoja, la opción científica real empíricamente probable con hechos terrenales comprobables históricamente documentados sobre nuestra mesa analítica. Explicación Ockham u Opción 2: El enorme gobierno central de los Estados Unidos de América invirtió activamente y aprobó secretamente en plena ebullición del pánico de la Guerra Fría comunista la escalofriante y monstruosa suma contable del billón y medio de dólares americanos reales de los impuestos de guerra para contratar secretamente a los ingenieros brillantes civiles más destacados que se graduaban anualmente de la prestigiosa universidad tecnológica californiana (Caltech), para de este modo construir desde el suelo terrestre en su desierto seguro más inhóspito un avión aerodinámicamente afilado triangular espía negro azabache no tripulado, de control autónomo y vuelo de gran y altísima altitud sigiloso indetectable para espionaje del bloque enemigo nocturno y pruebas extremas clandestinas militares humanas. Aplicando honestamente La Navaja contundente al argumento binario analítico completo en cuestión...";
const p10_m5 = "Es astronómica y lógicamente evidente para la razón científica deductiva moderna que la segunda opción terrenal de ingeniería secreta nacional humana documentada (los jets espías A-12 furtivos) resulta abrumadoramente ganadora, infinitamente más probable, sumamente sencilla metodológicamente, con base material humana, infinitamente más barata biológicamente y, sobre todas las cosas metodológicas de Sagan: no requiere postular arbitrariamente como cimiento fundamental inventado la milagrosa existencia rompedora termodinámicamente increíble de razas e imperios interestelares con propulsores milagrosos. Aprender fuertemente que en la ciencia universal y la física observacional 'no hay verdades absolutas sostenidas puramente por el principio falaz de la autoridad de quien lo dice' es sumamente liberador. El pensamiento crítico exige tener mente abierta en equilibrio perfecto: ni tan dogmática conservadora aburrida que ignoremos hallazgos, pero tampoco tan irresponsablemente abierta de mente descuidada para que el cerebro lógico funcional termine resbalando trágicamente fuera del cráneo por dejarse engañar sin pruebas duras medibles en el maravilloso mundo moderno espacial nuestro de la desinformación constante online de los mitos. Fuentes: The Demon-Haunted World (Carl Sagan, 1995), Committee for Skeptical Inquiry (CSI).";

const newModules = [
  {
    "id": "area51_m1",
    "order": 9001,
    "titleEn": "What is Area 51?",
    "titleEs": "¿Qué es el Área 51?",
    "badge": "Base Explorer",
    "badgeEs": "Explorador de la Base",
    "badgeIcon": "/assets/area51/area51_m1.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m1.png",
    "contentEs": {
      "sections": [
        {
          "id": "area51_m1_merged",
          "title": "La base militar real",
          "text": [p1_m1, p2_m1, p3_m1, p4_m1, p5_m1, p6_m1, p7_m1, p8_m1, p9_m1, p10_m1],
          "image": "/assets/area51/area51_m1.png",
          "style": "highlight"
        }
      ]
    },
    "quizEs": [
      {
        "q": "¿Para qué se construyó originalmente el Área 51?",
        "options": ["Para esconder extraterrestres", "Como laboratorio aeroespacial ultra secreto", "Para pruebas nucleares públicas", "Como aeropuerto comercial"],
        "a": 1
      }
    ]
  },
  {
    "id": "area51_m2",
    "order": 9002,
    "titleEn": "Secret Aircraft",
    "titleEs": "Los Aviones Secretos",
    "badge": "Aero Engineer",
    "badgeEs": "Ingeniero Aeroespacial",
    "badgeIcon": "/assets/area51/area51_m2.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m2.png",
    "contentEs": {
      "sections": [
        {
          "id": "area51_m2_merged",
          "title": "Tecnología aeroespacial clasificada",
          "text": [p1_m2, p2_m2, p3_m2, p4_m2, p5_m2, p6_m2, p7_m2, p8_m2, p9_m2, p10_m2],
          "image": "/assets/area51/area51_m2.png",
          "style": "highlight"
        }
      ]
    },
    "quizEs": [
      {
        "q": "¿Qué efecto óptico causaban los aviones U-2 en la estratosfera?",
        "options": ["Se volvían invisibles por el color", "Sus alas reflejaban el sol brillando en la noche baja", "Emitían luces láser verdes", "Dejaban estelas de arcoíris"],
        "a": 1
      }
    ]
  },
  {
    "id": "area51_m3",
    "order": 9003,
    "titleEn": "Origin of Rumors",
    "titleEs": "El Origen de los Rumores",
    "badge": "Project Mogul",
    "badgeEs": "Proyecto Mogul",
    "badgeIcon": "/assets/area51/area51_m3.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m3.png",
    "contentEs": {
      "sections": [
        {
          "id": "area51_m3_merged",
          "title": "El globo que se estrelló en 1947",
          "text": [p1_m3, p2_m3, p3_m3, p4_m3, p5_m3, p6_m3, p7_m3, p8_m3, p9_m3, p10_m3],
          "image": "/assets/area51/area51_m3.png",
          "style": "highlight"
        }
      ]
    },
    "quizEs": [
      {
        "q": "¿Qué era realmente el objeto estrellado en Roswell?",
        "options": ["Una nave marciana", "Un globo del Proyecto Mogul para detectar pruebas nucleares", "Un avión de pasajeros", "Un misil fallido"],
        "a": 1
      }
    ]
  },
  {
    "id": "area51_m4",
    "order": 9004,
    "titleEn": "Real Science vs. Fiction",
    "titleEs": "Ciencia Real vs. Ficción",
    "badge": "Truth Seeker",
    "badgeEs": "Buscador de la Verdad",
    "badgeIcon": "/assets/area51/area51_m4.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m4.png",
    "contentEs": {
      "sections": [
        {
          "id": "area51_m4_merged",
          "title": "Física y Aerodinámica",
          "text": [p1_m4, p2_m4, p3_m4, p4_m4, p5_m4, p6_m4, p7_m4, p8_m4, p9_m4, p10_m4],
          "image": "/assets/area51/area51_m4.png",
          "style": "highlight"
        }
      ]
    },
    "quizEs": [
      {
        "q": "¿Por qué es tan difícil viajar en el espacio real?",
        "options": ["Porque los aliens nos detienen", "Por las leyes de Newton y la necesidad de gran cantidad de combustible", "Porque el espacio es muy pequeño", "Por la falta de carreteras"],
        "a": 1
      }
    ]
  },
  {
    "id": "area51_m5",
    "order": 9005,
    "titleEn": "Baloney Detection Kit",
    "titleEs": "El Equipo de Detección de Camelos",
    "badge": "Sagan's Student",
    "badgeEs": "Estudiante de Sagan",
    "badgeIcon": "/assets/area51/area51_m5.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m5.png",
    "contentEs": {
      "sections": [
        {
          "id": "area51_m5_merged",
          "title": "El baloney detection kit",
          "text": [p1_m5, p2_m5, p3_m5, p4_m5, p5_m5, p6_m5, p7_m5, p8_m5, p9_m5, p10_m5],
          "image": "/assets/area51/area51_m5.png",
          "style": "highlight"
        }
      ]
    },
    "quizEs": [
      {
        "q": "Las afirmaciones extraordinarias requieren...",
        "options": ["Evidencias extraordinarias", "Mucha fe", "Fotos borrosas", "Secretismo"],
        "a": 0
      }
    ]
  }
];

const filePath = path.join(__dirname, 'lib', 'courseData.js');
let data = fs.readFileSync(filePath, 'utf8');

// The file exports courses as an array. We'll append our objects before the last bracket.
let newFields = newModules.map(m => JSON.stringify(m, null, 4)).join(',\n');

// Find the last closing bracket and replace it
data = data.replace(/\];\s*$/, `,\n${newFields}\n];\n`);

fs.writeFileSync(filePath, data);
console.log('Successfully injected comprehensive Area 51 data into courseData.js');
