const fs = require('fs');
const raw = fs.readFileSync('lib/courseData.js', 'utf8');
const prefix = raw.split('export const COURSE_DATA = ')[0];
const dataStr = raw.split('export const COURSE_DATA = ')[1].replace(/;\s*$/, '');
const COURSE_DATA = eval('(' + dataStr + ')');

const ADD = {
  venus: [
    { title:"El Interior de Venus: Un Mundo de Roca", text:"Venus tiene un interior similar al de la Tierra: un núcleo de hierro, un manto rocoso y una corteza. Sin embargo, a diferencia de la Tierra, Venus no tiene placas tectónicas activas que reciclen la corteza. Esto significa que el calor interno se acumula hasta provocar erupciones volcánicas masivas que renuevan la superficie cada 500 millones de años aproximadamente.", image:"/assets/venus_volcanoes.png", imgCaption:"Volcanes activos en Venus detectados por la sonda Magellan y confirmados por la misión Venus Express. Fuente: NASA/ESA" },
    { title:"Sin Campo Magnético: Venus Desprotegido", text:"Venus no tiene un campo magnético significativo, lo que lo deja expuesto al bombardeo del viento solar. Los científicos creen que esto ocurre porque Venus rota muy lentamente (un día venusiano dura 243 días terrestres), lo que impide generar el efecto dinamo en su núcleo. Sin escudo magnético, el viento solar erosiona la atmósfera superior de Venus continuamente.", image:"/assets/venus_sulfuric_clouds_thick.png", imgCaption:"Sin campo magnético, Venus pierde continuamente su atmósfera superior por efecto del viento solar. Fuente: ESA/Venus Express" },
    { title:"La Rotación Retrógrada: El Sol Nace por el Oeste", text:"Venus hace algo extraordinario: ¡gira al revés! Si pudieras pararte en Venus y ver el Sol (imposible por las nubes), saldría por el oeste y se pondría por el este. Esto se llama rotación retrógrada. Además rota extremadamente despacio: un día en Venus dura más que un año venusiano. Las razones exactas de esta peculiaridad aún son debatidas por los astrónomos.", image:"/assets/planet_venus.png", imgCaption:"Venus rota en sentido contrario a la mayoría de planetas, haciendo que el Sol salga por el oeste en su superficie. Fuente: NASA" },
    { title:"El Efecto Invernadero Extremo", text:"La atmósfera de Venus es 96% dióxido de carbono, creando el efecto invernadero más extremo del Sistema Solar. La superficie alcanza 465°C, suficiente para derretir plomo. Esta temperatura es más alta que la de Mercurio, pese a estar más lejos del Sol. Venus es el planeta más caliente del Sistema Solar. La ESA señala que Venus es un ejemplo extremo de lo que el cambio climático podría hacer a la Tierra.", image:"/assets/venus_sulfuric_clouds_thick.png", imgCaption:"Las espesas nubes de ácido sulfúrico de Venus atrapan el calor creando el efecto invernadero más severo del Sistema Solar. Fuente: ESA" },
    { title:"Las Sondas Venera: Sobrevivir el Infierno", text:"La Unión Soviética logró la hazaña de aterrizar en Venus con las sondas Venera entre 1970 y 1984. Las naves sobrevivían solo entre 23 minutos y 2 horas antes de ser aplastadas y fundidas por la presión de 90 atmósferas y 465°C. La Venera 13 envió las primeras fotografías en color de la superficie. Es el ambiente más hostil que una nave humana ha sobrevivido.", image:"/assets/venus_volcanoes.png", imgCaption:"Las sondas soviéticas Venera sobrevivieron poco tiempo pero enviaron imágenes invaluables de la superficie venusiana. Fuente: NASA/NSSDC" },
    { title:"Los Volcanes de Venus: Un Mundo Volcánico Activo", text:"Venus tiene más volcanes que cualquier otro planeta del Sistema Solar: más de 1,600 volcanes mayores y miles de menores. En 2023, científicos analizando imágenes antiguas de la sonda Magellan de NASA confirmaron erupciones volcánicas activas. El volcán Maat Mons, de 8 km de altura, mostró cambios en su forma entre 1991 y 1992, evidencia de actividad reciente.", image:"/assets/venus_volcanoes.png", imgCaption:"El volcán Maat Mons de 8 km de altura, uno de los cientos de volcanes activos de Venus. Fuente: NASA/JPL/Magellan" },
    { title:"Las Nubes de Ácido Sulfúrico", text:"Las nubes que cubren completamente Venus no son de agua como en la Tierra: son de ácido sulfúrico concentrado. Se extienden entre 45 y 70 km de altura, reflejan el 70% de la luz solar (por eso Venus brilla tanto en el cielo) y son tan densas que desde la superficie reina una luz anaranjada tenue similar a un día nublado. En las nubes la temperatura es de apenas -40°C.", image:"/assets/venus_sulfuric_clouds_thick.png", imgCaption:"Las densas nubes de ácido sulfúrico de Venus, fotografiadas en ultravioleta por la sonda Venus Express de ESA. Fuente: ESA" },
    { title:"La Misión DAVINCI y EnVision: Regreso a Venus", text:"La NASA y la ESA tienen misiones gemelas planeadas para Venus en la década de 2030. DAVINCI+ de NASA descenderá a través de la atmósfera midiendo su composición exacta y fotografiando el terreno. EnVision de ESA orbitará Venus durante años mapeando su geología con radar. Juntas, estas misiones resolverán preguntas clave: ¿alguna vez Venus tuvo océanos? ¿Podría haber vida en sus nubes?", image:"/assets/planet_venus.png", imgCaption:"Representación artística de la futura misión DAVINCI+ de NASA descendiendo a través de la atmósfera de Venus. Fuente: NASA" },
    { title:"Venus y la Tierra: Gemelos Diferentes", text:"Venus y la Tierra son llamados 'gemelos planetarios' porque tienen tamaño, masa y composición similares. Sin embargo, son mundos completamente opuestos: la Tierra tiene agua líquida, temperatura media de 15°C y vida abundante. Venus tiene 465°C, ácido sulfúrico y presión aplastante. Estudiar por qué evolucionaron tan diferente ayuda a los científicos a entender qué hace habitable a nuestro planeta.", image:"/assets/planet_venus.png", imgCaption:"Venus y la Tierra son casi del mismo tamaño pero con condiciones completamente opuestas. Fuente: NASA" }
  ],
  earth: [
    { title:"El Núcleo Terrestre: El Corazón de Hierro", text:"En el centro exacto de la Tierra hay una bola sólida de hierro y níquel de 1,220 km de radio llamada núcleo interno. A su alrededor hay una capa de hierro líquido llamada núcleo externo. La temperatura en el núcleo supera los 5,000°C, similar a la superficie del Sol. Este hierro líquido en movimiento es el responsable de generar el campo magnético que protege toda la vida en la Tierra.", image:"/assets/planet_earth.png", imgCaption:"Estructura interna de la Tierra: corteza, manto, núcleo externo líquido y núcleo interno sólido. Fuente: NASA/USGS" },
    { title:"El Campo Magnético: El Escudo Protector de la Vida", text:"El campo magnético terrestre, generado por el hierro líquido del núcleo externo, es un escudo invisible que deflecta el viento solar. Sin él, las partículas energéticas del Sol barrería la atmósfera y el agua de la superficie, como ocurrió en Marte. El campo magnético crea también las espectaculares auroras boreales y australes cuando partículas solares chocan con la atmósfera en los polos.", image:"/assets/planet_earth.png", imgCaption:"Las auroras boreales, visibles desde la Estación Espacial Internacional, son causadas por el campo magnético terrestre. Fuente: NASA/ISS" },
    { title:"La Luna: Nuestra Compañera Eterna", text:"La Luna se formó hace 4,500 millones de años cuando un objeto del tamaño de Marte chocó con la Tierra primordial. Los escombros de ese impacto se agruparon formando nuestra Luna. La Luna estabiliza el eje de inclinación de la Tierra (lo que nos da estaciones estables), genera las mareas oceánicas y se aleja de nosotros 3.8 cm cada año. Sin la Luna, la vida en la Tierra sería muy diferente.", image:"/assets/planet_earth.png", imgCaption:"La Luna y la Tierra fotografiadas desde la nave Galileo de NASA durante su sobrevuelo en 1992. Fuente: NASA/JPL" },
    { title:"La Atmósfera: El Manto que Nos Protege", text:"La atmósfera de la Tierra es una delgada capa de gases (78% nitrógeno, 21% oxígeno, 1% argón y otros) que hace posible la vida. La capa de ozono en la estratosfera filtra el 97-99% de la dañina radiación ultravioleta del Sol. Sin atmósfera, las temperaturas oscilarían entre -160°C por la noche y 120°C de día, y los rayos cósmicos esterilizarían la superficie.", image:"/assets/planet_earth.png", imgCaption:"La delgada capa de atmósfera terrestre, visible desde el espacio como una franja azul sobre el horizonte. Fuente: NASA/ISS" },
    { title:"Los Océanos: El Gran Tesoro Azul", text:"Los océanos cubren el 71% de la superficie terrestre y contienen el 97% del agua del planeta. Son fundamentales para la vida: regulan el clima global, absorben el 30% del CO₂ emitido por humanos y producen más del 50% del oxígeno del planeta a través del fitoplancton. La fosa de las Marianas, en el Pacífico, es el punto más profundo de la Tierra: 11,034 metros.", image:"/assets/planet_earth.png", imgCaption:"La Tierra vista desde el espacio muestra por qué es llamada el 'Planeta Azul': los océanos dominan su superficie. Fuente: NASA/NOAA" },
    { title:"Las Placas Tectónicas: La Tierra se Mueve", text:"La corteza terrestre está dividida en grandes placas que flotan sobre el manto y se mueven entre 2 y 15 cm por año. Cuando chocan forman montañas como el Himalaya; cuando se separan crean océanos como el Atlántico; cuando una se hunde bajo otra generan volcanes y terremotos. La tectónica de placas recicla constantemente la corteza, manteniendo el ciclo del carbono que regula el clima.", image:"/assets/planet_earth.png", imgCaption:"Mapa global de las placas tectónicas terrestres. Sus movimientos moldean la geografía del planeta. Fuente: NASA/USGS" },
    { title:"La ISS: Nuestra Casa Orbital", text:"La Estación Espacial Internacional (ISS) orbita la Tierra a 400 km de altitud y 27,600 km/h. Da la vuelta al planeta cada 90 minutos. Es un laboratorio científico donde astronautas de múltiples países conviven y realizan experimentos en microgravedad. Se ha habitado de forma continua desde noviembre de 2000. Desde la ISS se ve una salida de sol cada 45 minutos.", image:"/assets/planet_earth.png", imgCaption:"La Estación Espacial Internacional fotografiada desde el transbordador Discovery de NASA. Fuente: NASA" },
    { title:"Los Satélites Artificiales: Guardianes Orbitales", text:"Hay más de 8,000 satélites activos orbitando la Tierra hoy. Estos artefactos hacen posibles los GPS, las llamadas telefónicas globales, la televisión por satélite, la predicción del tiempo y el monitoreo del cambio climático. El primer satélite artificial fue el Sputnik 1 soviético en 1957. Los satélites Landsat de NASA llevan más de 50 años fotografiando los cambios en la superficie terrestre.", image:"/assets/planet_earth.png", imgCaption:"Red global de satélites orbitando la Tierra. Fuente: ESA/Aerospace" },
    { title:"El Cambio Climático: Una Emergencia Real", text:"La temperatura media global de la Tierra ha subido 1.1°C desde la era preindustrial por las emisiones de gases de efecto invernadero producidas por los humanos. La NASA monitorea el clima terrestre con más de 25 satélites. Las consecuencias incluyen derretimiento de glaciares, subida del nivel del mar y eventos climáticos extremos más frecuentes. Reducir emisiones es la prioridad científica más urgente del siglo XXI.", image:"/assets/planet_earth.png", imgCaption:"Imágenes comparativas de un glaciar en 1980 vs 2020, documentando el retroceso glaciar causado por el calentamiento global. Fuente: NASA/USGS" }
  ],
  mars: [
    { title:"El Interior de Marte: Un Núcleo Frío", text:"La sonda InSight de NASA aterrizó en Marte en 2018 para estudiar su interior con sismómetros. Descubrió que el núcleo marciano es líquido, rico en hierro y azufre, y mide entre 1,800 y 2,000 km de radio. A diferencia de la Tierra, el núcleo de Marte no genera un campo magnético global activo, lo que dejó al planeta sin protección frente al viento solar hace unos 4,000 millones de años.", image:"/assets/mars_ancient_oceans.png", imgCaption:"La sonda InSight de NASA registró temblores marcianos que revelaron la estructura interna del Planeta Rojo. Fuente: NASA/JPL" },
    { title:"Fobos y Deimos: Las Lunas de Marte", text:"Marte tiene dos pequeñas lunas: Fobos (27 km de diámetro) y Deimos (15 km). Parecen asteroides capturados por la gravedad marciana. Fobos es tan cercano a Marte que orbita más rápido de lo que el planeta rota: sale por el oeste y se pone por el este. Además, Fobos se acerca a Marte 2 cm por año y en unos 50 millones de años será destruido por la gravedad del planeta.", image:"/assets/planet_mars.png", imgCaption:"Fobos, la luna mayor de Marte, fotografiada por el Mars Reconnaissance Orbiter de NASA. Fuente: NASA/University of Arizona" },
    { title:"El Monte Olimpo: El Volcán Más Grande del Sistema Solar", text:"El Monte Olimpo es el volcán más grande y alto conocido en el Sistema Solar: 21.9 km de altura (casi 3 veces el Everest) y 600 km de diámetro (tan grande como Francia). Lleva miles de millones de años sin placas tectónicas que muevan la corteza, por lo que el magma siguió acumulándose en el mismo punto creando esta monstruosa estructura. Probablemente no ha entrado en erupción desde hace millones de años.", image:"/assets/planet_mars.png", imgCaption:"El Monte Olimpo en Marte: el volcán más grande del Sistema Solar, fotografiado por el satélite Mars Express de ESA. Fuente: ESA/NASA" },
    { title:"Valles Marineris: La Gran Cicatriz Marciana", text:"Valles Marineris es un sistema de cañones que se extiende 4,000 km a lo largo del ecuador de Marte (tan largo como los EE.UU. de costa a costa) y alcanza 7 km de profundidad. Por comparación, el Gran Cañón del Colorado tiene 446 km de largo y 1.8 km de profundidad. Valles Marineris se formó principalmente por fracturamiento tectónico y no por erosión de agua, aunque el agua pudo haberlo agrandado.", image:"/assets/mars_dust_storm.png", imgCaption:"Valles Marineris visto desde órbita: un sistema de cañones que haría al Gran Cañón parecer diminuto. Fuente: NASA/USGS" },
    { title:"Las Tormentas de Polvo de Marte", text:"Marte sufre tormentas de polvo únicas en el Sistema Solar: pueden durar meses y cubrir el planeta entero. La tormenta global de 2018 cubrió todo Marte durante 3 meses y dejó sin energía solar al rover Opportunity de NASA, que no volvió a despertar. El polvo marciano es muy fino, del tamaño de partículas de humo. Las tormentas globales ocurren aproximadamente cada 3 años marcianos.", image:"/assets/mars_dust_storm.png", imgCaption:"Tormenta de polvo global en Marte fotografiada por el Mars Reconnaissance Orbiter de NASA en 2018. Fuente: NASA/JPL" },
    { title:"Perseverance y Curiosity: Los Exploradores del Suelo", text:"Marte ha sido explorado por varios rovers (vehículos robóticos). Curiosity lleva operando desde 2012 y ha analizado miles de muestras de roca confirmando que Marte tuvo un lago de agua dulce habitable. Perseverance aterrizó en 2021 y busca signos de vida antigua recolectando muestras para traerlas a la Tierra en la futura Misión de Retorno de Muestras de Marte (NASA/ESA).", image:"/assets/mars_ancient_oceans.png", imgCaption:"El rover Perseverance de NASA en el cráter Jezero, antiguo lago marciano, en 2021. Fuente: NASA/JPL-Caltech" },
    { title:"El Agua en Marte: Pasado Húmedo", text:"Marte tuvo océanos hace unos 3,500 millones de años. Hoy el agua líquida no puede existir en la superficie por la baja presión atmosférica, pero hay evidencia de agua líquida salada bajo el casquete polar sur. También hay hielo de agua en los polos y en el suelo. Entender qué le pasó al agua de Marte es fundamental para saber si la vida pudo existir allí.", image:"/assets/mars_ancient_oceans.png", imgCaption:"Recreación artística de cómo pudo verse Marte hace 3,500 millones de años, cubierto parcialmente por océanos. Fuente: NASA/GSFC" },
    { title:"¿Hubo Vida en Marte?", text:"Esta es una de las preguntas más importantes de la ciencia actual. Los científicos buscan microfósiles en rocas sedimentarias del cráter Jezero (un antiguo lago). En 2022, el rover Perseverance encontró rocas con estructuras orgánicas complejas que podrían ser signos de vida antigua. Las muestras recolectadas serán analizadas en laboratorios terrestres alrededor de 2033.", image:"/assets/mars_ancient_oceans.png", imgCaption:"Roca sedimentaria del cráter Jezero analizada por Perseverance, que podría preservar signos de vida microbiana antigua. Fuente: NASA/JPL" },
    { title:"La Colonización de Marte: El Sueño del Futuro", text:"Agencias espaciales y empresas privadas planean enviar humanos a Marte en la década de 2030-2040. Los desafíos son enormes: el viaje dura 7 meses, la radiación es intensa sin campo magnético, la temperatura promedio es -60°C y no hay oxígeno respirable. El experimento MOXIE del rover Perseverance ya demostró que es posible producir oxígeno de la atmósfera marciana, un paso crucial para futuras misiones.", image:"/assets/mars_human_colony_dome.png", imgCaption:"Representación artística de una futura base humana en Marte con domos de vida. Fuente: NASA/SpaceX" }
  ],
  jupiter: [
    { title:"El Interior de Júpiter: El Gas que se Convierte en Metal", text:"Júpiter no tiene superficie sólida. Bajo sus nubes, el hidrógeno se comprime tanto que se vuelve líquido, y luego, a mayor profundidad, se convierte en hidrógeno metálico líquido: una sustancia que conduce la electricidad como un metal. Este hidrógeno metálico es el responsable del gigantesco campo magnético de Júpiter. En el centro podría haber un núcleo rocoso del tamaño de la Tierra.", image:"/assets/planet_jupiter.png", imgCaption:"Diagrama del interior de Júpiter: capas de gas, hidrógeno líquido, hidrógeno metálico y posible núcleo rocoso. Fuente: NASA" },
    { title:"El Campo Magnético de Júpiter: El Más Poderoso del Sistema Solar", text:"El campo magnético de Júpiter es 20,000 veces más fuerte que el de la Tierra, el más intenso de todos los planetas. Crea una magnetosfera tan grande que si pudiéramos verla desde la Tierra, ocuparía en el cielo un área 5 veces mayor que la Luna llena. Atrapa partículas de alta energía que crean cinturones de radiación letales para las naves espaciales. Los astronautas no podrían sobrevivir cerca de Júpiter.", image:"/assets/jupiter_auroras_radiation.png", imgCaption:"Las auroras de Júpiter fotografiadas por el Telescopio Espacial Hubble, causadas por su poderoso campo magnético. Fuente: NASA/ESA/Hubble" },
    { title:"Las Lunas de Júpiter: Un Sistema Solar en Miniatura", text:"Júpiter tiene 95 lunas confirmadas, más que cualquier otro planeta. Las cuatro más grandes (Io, Europa, Ganímedes y Calisto) fueron descubiertas por Galileo Galilei en 1610 con un telescopio primitivo y se llaman lunas galileanas. Ganímedes es la luna más grande del Sistema Solar: es más grande que el planeta Mercurio. Estas lunas tienen geología activa, océanos subterráneos y posible vida.", image:"/assets/planet_jupiter.png", imgCaption:"Las cuatro lunas galileanas de Júpiter: Io, Europa, Ganímedes y Calisto, descubiertas por Galileo en 1610. Fuente: NASA/JPL" },
    { title:"La Gran Mancha Roja: La Tormenta Eterna", text:"La Gran Mancha Roja es una tormenta anticiclónica que lleva girando al menos 350 años (fue observada por primera vez en 1665). Es tan grande que podría contener a la Tierra entera. Los vientos en su interior alcanzan 640 km/h. Curiosamente, la mancha se ha estado encogiendo: en el siglo XIX medía 40,000 km; hoy mide apenas 16,000 km. Los científicos no saben si desaparecerá.", image:"/assets/jupiter_cyclones.png", imgCaption:"La Gran Mancha Roja de Júpiter fotografiada por el Telescopio Espacial Hubble en 2019. Fuente: NASA/ESA/Hubble" },
    { title:"Los Anillos de Júpiter: Tenues y Desconocidos", text:"Pocos saben que Júpiter también tiene anillos, aunque son mucho más tenues que los de Saturno. Fueron descubiertos en 1979 por la sonda Voyager 1. Están compuestos principalmente de polvo oscuro eyectado por pequeñas lunas interiores cuando meteoritos las impactan. Son invisibles desde la Tierra con telescopios normales pero la sonda Galileo los estudió detalladamente.", image:"/assets/planet_jupiter.png", imgCaption:"Los tenues anillos de Júpiter fotografiados por la sonda New Horizons de NASA en 2007. Fuente: NASA/JHU/APL" },
    { title:"Io: La Luna Más Volcánica del Sistema Solar", text:"Io es el cuerpo con mayor actividad volcánica de todo el Sistema Solar. Tiene más de 400 volcanes activos que emiten dióxido de azufre. Su superficie constantemente renovada no muestra ningún cráter de impacto. La causa de tanta actividad es el 'tirón de mareas' que ejercen Júpiter, Europa y Ganímedes sobre Io, calentando su interior como una pelota de goma apretada repetidamente.", image:"/assets/jupiter_auroras_radiation.png", imgCaption:"Io, la luna volcánica de Júpiter, con sus volcanes activos visibles como manchas brillantes. Fuente: NASA/JPL/University of Arizona" },
    { title:"Europa: ¿Tiene un Océano con Vida?", text:"Europa, luna de Júpiter, tiene una capa de hielo de 10-30 km que cubre un océano de agua líquida salada de hasta 100 km de profundidad. Este océano contiene dos veces más agua que todos los océanos de la Tierra juntos. El calor de marea de Júpiter mantiene el agua líquida. La misión Europa Clipper de NASA (lanzada en 2024) investigará si este océano podría albergar vida microbiana.", image:"/assets/jupiter_auroras_radiation.png", imgCaption:"Europa, luna de Júpiter, con su superficie de hielo agrietado que cubre un vasto océano subterráneo. Fuente: NASA/JPL-Caltech" },
    { title:"La Sonda Juno: Dentro de Júpiter", text:"La sonda Juno de NASA orbita Júpiter desde 2016. Vuela tan cerca como 4,200 km sobre las nubes y tarda 53 días en completar una órbita. Ha revelado que las tormentas de Júpiter tienen raíces que se extienden cientos de kilómetros hacia el interior, y que los polos están cubiertos de ciclones gigantescos organizados en patrones geométricos perfectos. Juno también encontró agua en la atmósfera joviana.", image:"/assets/jupiter_cyclones.png", imgCaption:"Los ciclones polares de Júpiter fotografiados por la sonda Juno de NASA: una estructura jamás vista antes. Fuente: NASA/JPL-Caltech/SwRI/MSSS" },
    { title:"Júpiter como Escudo Protector de la Tierra", text:"Júpiter actúa como un 'aspirador cósmico' para la Tierra. Su enorme gravedad captura cometas y asteroides que de otro modo podrían impactar nuestro planeta. En 1994, el mundo observó cómo el cometa Shoemaker-Levy 9 fue capturado y destruido por Júpiter en 21 impactos espectaculares. Sin embargo, Júpiter también puede lanzar objetos hacia la Tierra, así que su papel es ambiguo.", image:"/assets/shoemaker_levy_jupiter.png", imgCaption:"Impacto del cometa Shoemaker-Levy 9 contra Júpiter en 1994, fotografiado por el Telescopio Espacial Hubble. Fuente: NASA/HST" }
  ]
};

let changed = 0;
COURSE_DATA.forEach(mod => {
  if (ADD[mod.id]) {
    const existing = mod.contentEs.sections || [];
    mod.contentEs.sections = [...existing, ...ADD[mod.id]];
    console.log(mod.id, ': ahora tiene', mod.contentEs.sections.length, 'secciones');
    changed++;
  }
});

const out = prefix + 'export const COURSE_DATA = ' + JSON.stringify(COURSE_DATA, null, 2) + ';';
fs.writeFileSync('lib/courseData.js', out);
console.log('Fase 2 completa:', changed, 'módulos actualizados');
