const fs = require('fs');
const raw = fs.readFileSync('lib/courseData.js', 'utf8');
const prefix = raw.split('export const COURSE_DATA = ')[0];
const dataStr = raw.split('export const COURSE_DATA = ')[1].replace(/;\s*$/, '');
const COURSE_DATA = eval('(' + dataStr + ')');

const ADD = {
  sun: [
    { title:"Las Capas del Sol", text:"El Sol tiene capas como una cebolla gigante. En el centro está el núcleo, a 15 millones de grados, donde el hidrógeno se convierte en helio liberando energía. Luego viene la zona radiativa, donde la luz tarda ¡100,000 años en escapar! Después la zona de convección, donde el plasma caliente sube y baja como agua hirviendo. Finalmente la fotosfera, la capa visible, a 5,500°C.", image:"/assets/sun_layers_core.png", imgCaption:"Diagrama de las capas internas del Sol: núcleo, zonas radiativa y de convección, fotosfera. Fuente: NASA" },
    { title:"La Corona Solar y la Cromosfera", text:"Sobre la fotosfera hay dos capas invisibles a simple vista. La cromosfera es una franja rojiza de 2,000 km de grosor visible solo durante eclipses totales. Encima está la corona, la atmósfera exterior del Sol, que alcanza temperaturas de hasta 2 millones de grados — mucho más caliente que la superficie. Los científicos de la NASA aún investigan por qué la corona es tan caliente.", image:"/assets/sun_coronal_ejection.png", imgCaption:"Eyección de masa coronal del Sol captada por el Observatorio Solar SOHO de la NASA/ESA." },
    { title:"Las Manchas Solares: Cicatrices Magnéticas", text:"Las manchas solares son áreas oscuras en la fotosfera donde el campo magnético es tan intenso que impide que el calor suba desde abajo. Parecen oscuras porque están 'solo' a 3,700°C, más frías que el entorno de 5,500°C. Aparecen en ciclos de 11 años. En los períodos de máximo solar hay cientos de manchas; en el mínimo, casi ninguna.", image:"/assets/sun_layers_core.png", imgCaption:"Imagen del Sol mostrando manchas solares activas sobre su fotosfera. Fuente: NASA/SDO" },
    { title:"Las Eyecciones de Masa Coronal: Tormentas Solares", text:"El Sol lanza enormes nubes de plasma y energía al espacio llamadas eyecciones de masa coronal (CME). Cuando una CME golpea la Tierra, puede causar apagones de energía eléctrica, interferencias en satélites y auroras boreales espectaculares en los polos. La CME más poderosa registrada fue el 'Evento Carrington' de 1859, que habría destruido nuestra red eléctrica actual.", image:"/assets/sun_coronal_ejection.png", imgCaption:"Eyección de masa coronal capturada por el satélite SOHO. Las CMEs pueden alcanzar la Tierra en 1-3 días. Fuente: NASA" },
    { title:"La Sonda Parker: Tocando el Sol", text:"La Sonda Solar Parker de la NASA, lanzada en 2018, es la nave espacial más rápida jamás construida: alcanza 690,000 km/h. Su misión es volar a través de la corona solar para estudiarla desde adentro. Está protegida por un escudo térmico especial que resiste 1,377°C. En 2021 se convirtió en la primera nave en 'tocar' el Sol al atravesar la corona.", image:"/assets/parker_probe_sun.png", imgCaption:"Representación artística de la Sonda Solar Parker acercándose al Sol. Fuente: NASA/Johns Hopkins APL" },
    { title:"La Fusión Nuclear: La Receta Energética del Sol", text:"Cada segundo, el Sol convierte 600 millones de toneladas de hidrógeno en helio mediante fusión nuclear. En este proceso, una pequeña cantidad de masa se convierte en energía colosal (siguiendo E=mc² de Einstein). Esta energía viaja desde el núcleo hasta la superficie en forma de luz y calor. El Sol lleva 4,600 millones de años haciendo esto y tiene combustible para 5,000 millones de años más.", image:"/assets/sun_layers_core.png", imgCaption:"El proceso de fusión nuclear en el núcleo solar transforma 4 millones de toneladas de masa en energía pura cada segundo. Fuente: NASA" },
    { title:"Los Vientos Solares: El Aliento del Astro Rey", text:"El Sol emite constantemente un flujo de partículas cargadas llamado viento solar. Viaja a entre 400 y 800 km/s y llena todo el Sistema Solar creando la heliosfera, una burbuja gigante de influencia solar. El viento solar es el responsable de que las colas de los cometas siempre apunten alejándose del Sol, sin importar la dirección en que viajan.", image:"/assets/parker_probe_sun.png", imgCaption:"El viento solar fluye desde el Sol hacia los confines del Sistema Solar, creando la heliosfera. Fuente: NASA" },
    { title:"El Futuro del Sol: La Gigante Roja", text:"Dentro de unos 5,000 millones de años, el Sol agotará su hidrógeno y se expandirá hasta convertirse en una Gigante Roja. Su diámetro podría superar la órbita de Venus y posiblemente la de la Tierra. Luego expulsará sus capas externas formando una nebulosa planetaria y su núcleo quedará como una enana blanca. ¡No te preocupes: la humanidad tiene tiempo de sobra para planear!", image:"/assets/red_dwarf_1.png", imgCaption:"En su fase final, el Sol se convertirá en una gigante roja antes de colapsar en una enana blanca. Fuente: NASA" },
    { title:"Récords Solares: El Astro de los Extremos", text:"El Sol guarda impresionantes récords: es 109 veces más ancho que la Tierra y contiene el 99.8% de toda la masa del Sistema Solar. Su núcleo alcanza 15 millones °C y su superficie 'solo' 5,500°C. La luz solar tarda 8 minutos y 20 segundos en llegar a la Tierra. El Sol también tiene su propio campo magnético, ¡que es 5,000 veces más fuerte que el de la Tierra en las manchas solares!", image:"/assets/sun_coronal_ejection.png", imgCaption:"Comparativa de tamaños: la Tierra cabe 109 veces a lo largo del diámetro del Sol. Fuente: NASA" }
  ],
  mercury: [
    { title:"El Interior Metálico de Mercurio", text:"Mercurio tiene un núcleo de hierro sólido y líquido enormemente grande para su tamaño, abarcando el 85% de su radio total. Esto lo hace el planeta con el mayor porcentaje de metal en el Sistema Solar. Los científicos creen que Mercurio sufrió un impacto colosal en su historia temprana que le arrancó la mayor parte de su manto rocoso, dejando expuesto ese enorme núcleo metálico.", image:"/assets/mercury_extremes.png", imgCaption:"La estructura interna de Mercurio muestra un núcleo de hierro desproporcionadamente grande. Fuente: NASA/MESSENGER" },
    { title:"El Campo Magnético de Mercurio", text:"A pesar de su pequeño tamaño, Mercurio tiene un campo magnético activo, aunque 100 veces más débil que el de la Tierra. Este campo protege al planeta parcialmente de los vientos solares, pero al ser tan débil, el plasma solar llega constantemente a la superficie. La sonda MESSENGER descubrió que este campo magnético está desplazado hacia el norte, lo que intriga a los científicos.", image:"/assets/mercury_orbital_resonance.png", imgCaption:"El campo magnético de Mercurio, débil pero real, fue detectado por primera vez por la sonda Mariner 10. Fuente: NASA" },
    { title:"Mercurio Viaja Solo: Sin Lunas", text:"A diferencia de la Tierra con la Luna, Marte con dos lunas o Júpiter con 95, Mercurio no tiene ningún satélite natural. La gravedad del Sol es tan dominante en esa región del Sistema Solar que cualquier luna que Mercurio pudiera haber tenido habría sido atraída por el Sol o expulsada al espacio. También carece de anillos.", image:"/assets/planet_mercury.png", imgCaption:"Mercurio, el planeta más cercano al Sol, orbita solo sin ninguna luna ni anillos. Fuente: NASA/MESSENGER" },
    { title:"La Sonda MESSENGER: Revelando Mercurio", text:"La nave MESSENGER de la NASA orbitó Mercurio durante 4 años (2011-2015). Tomó más de 270,000 fotos y mapeó el 100% de su superficie. Sus descubrimientos fueron asombrosos: encontró agua helada en cráteres permanentemente a la sombra en los polos norte y sur, y confirmó el enorme núcleo metálico. Al agotar su combustible, MESSENGER impactó Mercurio creando un cráter de 16 metros.", image:"/assets/mercury_extremes.png", imgCaption:"La sonda MESSENGER de NASA orbitó Mercurio durante 4 años y transmitió más de 270,000 fotografías. Fuente: NASA" },
    { title:"Los Cráteres: Cicatrices del Sistema Solar", text:"La superficie de Mercurio está cubierta de cráteres de impacto, similar a la Luna. El más grande es la Cuenca Caloris, con 1,550 km de diámetro, formada por un impacto colosal hace unos 3,900 millones de años. Como Mercurio no tiene atmósfera ni clima que erosione los cráteres, estas cicatrices permanecen perfectamente conservadas por miles de millones de años.", image:"/assets/mercury_orbital_resonance.png", imgCaption:"La superficie de Mercurio está densamente cubierta de cráteres, preservados por la ausencia de atmósfera. Fuente: NASA/MESSENGER" },
    { title:"Hielo en el Planeta de Fuego", text:"Aunque Mercurio alcanza 430°C en su lado iluminado, sus polos esconden un secreto sorprendente: ¡hay agua helada! Los cráteres polares están permanentemente a la sombra del Sol y sus temperaturas bajan a -180°C. La sonda MESSENGER confirmó depósitos de hielo mezclados con compuestos orgánicos oscuros. Este hielo pudo llegar por cometas y asteroides que impactaron el planeta.", image:"/assets/mercury_extremes.png", imgCaption:"Imagen de radar del polo norte de Mercurio mostrando zonas brillantes de hielo agua en cráteres sombreados. Fuente: NASA/MESSENGER" },
    { title:"La Resonancia Orbital: El Día Más Largo", text:"Mercurio tiene una peculiaridad asombrosa: un día en Mercurio (176 días terrestres) es más largo que su año (88 días terrestres). Esto ocurre porque Mercurio está en resonancia orbital 3:2 con el Sol: da 3 vueltas sobre sí mismo por cada 2 órbitas alrededor del Sol. Desde la superficie de Mercurio, el Sol aparece detenerse, moverse al revés y luego continuar.", image:"/assets/mercury_orbital_resonance.png", imgCaption:"Mercurio completa dos órbitas alrededor del Sol por cada tres rotaciones sobre su propio eje. Fuente: NASA" },
    { title:"BepiColombo: La Misión Europea a Mercurio", text:"La Agencia Espacial Europea (ESA) y la Agencia Espacial Japonesa (JAXA) lanzaron juntas la misión BepiColombo en 2018. La nave llegará a Mercurio en 2025 y estudiará su campo magnético, su núcleo y su superficie con instrumentos mucho más avanzados que MESSENGER. BepiColombo tiene dos orbitadores: el MPO europeo y el Mio japonés, que trabajarán juntos.", image:"/assets/planet_mercury.png", imgCaption:"Representación artística de la misión BepiColombo de ESA/JAXA aproximándose a Mercurio en 2025. Fuente: ESA" },
    { title:"Mercurio en la Historia: El Planeta Veloz", text:"Mercurio fue conocido por las civilizaciones antiguas que lo observaban a simple vista al amanecer y al atardecer. Los griegos lo llamaban Hermes (el mensajero de los dioses) y los romanos lo nombraron Mercurio por su velocidad orbital: ¡viaja a 47 km/s, el más rápido del Sistema Solar! No fue explorado por una nave espacial hasta 1974, cuando el Mariner 10 hizo el primer sobrevuelo.", image:"/assets/mercury_extremes.png", imgCaption:"Mercurio visto desde la Tierra en tránsito frente al Sol, un evento visible solo unas pocas veces por siglo. Fuente: NASA" }
  ]
};

let changed = 0;
COURSE_DATA.forEach(mod => {
  if (ADD[mod.id]) {
    const existing = mod.contentEs.sections || [];
    mod.contentEs.sections = [...existing, ...ADD[mod.id]];
    console.log(mod.id, ': ahora tiene', mod.contentEs.sections.length, 'secciones');
    changed++;
  }
});

const out = prefix + 'export const COURSE_DATA = ' + JSON.stringify(COURSE_DATA, null, 2) + ';';
fs.writeFileSync('lib/courseData.js', out);
console.log('Fase 1 completa:', changed, 'módulos actualizados');
