import fs from 'fs';
import { COURSE_DATA } from './lib/courseData.js';

const TOPIC_DETAILS = {
  "egypt_m1": [
    "¡Saludos, joven explorador del cosmos! Prepárate para realizar un viaje extraordinario que nos llevará muchísimo más atrás en el tiempo que las mismísimas Pirámides de Giza. Nos adentraremos en el corazón implacable del desierto del Sahara, donde el sol quema y la arena se extiende hasta el infinito.",
    "Hace más de 7,000 años, antes de que existieran los faraones o los grandes imperios, este lugar no era un desierto árido, sino una sabana vibrante. Allí habitaban tribus nómadas que dependían completamente de los ciclos de la naturaleza para sobrevivir. Estos antiguos pobladores observaban el cielo con una devoción y un nivel de detalle que hoy en día nos parece casi increíble.",
    "En medio de esta vasta llanura, descubrieron y construyeron algo asombroso: Nabta Playa. Imagina encontrarte con un círculo perfecto de gigantescas piedras megalíticas, erigidas con un propósito misterioso. A primera vista, podrían parecer rocas puestas al azar, pero la ciencia moderna ha revelado que este es, de hecho, el observatorio astronómico más antiguo conocido por la humanidad.",
    "Superando en antigüedad al famoso Stonehenge por más de mil años, Nabta Playa es una maravilla de la ingeniería prehistórica. Las piedras principales del círculo no fueron colocadas como un adorno; fueron meticulosamente alineadas para predecir con exactitud geométrica la llegada del solsticio de verano.",
    "Para estas tribus, el solsticio de verano no era solo una fecha en el calendario; era una cuestión de vida o muerte. Anunciaba la llegada inminente de los monzones de verano, lluvias torrenciales que llenarían los lagos temporales y permitirían que el ganado bebiera y los pastos crecieran. El cielo era su reloj y su mapa de supervivencia.",
    "Aún más fascinante, investigaciones recientes utilizando mediciones satelitales y software arqueoastronómico han demostrado que algunas de estas enormes piedras apuntan directamente a constelaciones específicas, como Orión y la Osa Mayor. Creían que las estrellas eran los espíritus de sus ancestros guiándolos a través de las áridas tierras.",
    "Este nivel de observación cósmica y comprensión matemática sentó los cimientos fundacionales de todo lo que la civilización egipcia lograría miles de años más tarde. En Nabta Playa, la humanidad aprendió por primera vez a anclar su existencia terrenal a los movimientos perpetuos de los astros.",
    "A partir de estas piedras en la arena, nació la astronomía antigua, demostrando que incluso en las condiciones más primitivas, la mente humana siempre ha buscado respuestas mirando hacia el resplandor de las estrellas."
  ],
  "egypt_m2": [
    "Imagínate en medio de la oscuridad absoluta de la noche egipcia, miles de años antes de que se inventaran los relojes mecánicos, los teléfonos celulares o cualquier instrumento moderno de medición. ¿Cómo podrías saber exactamente cuánto tiempo falta para el amanecer?",
    "Los sacerdotes y sabios astrónomos del antiguo Egipto, conocidos por su brillante intelecto y su aguda capacidad de observación, encontraron la respuesta mirando hacia la bóveda celeste. Descubrieron que el cielo nocturno no era un caos de luces, sino un gigantesco y preciso reloj cósmico en constante movimiento.",
    "Para medir las horas nocturnas, dividieron la banda del cielo por la que parecen viajar las estrellas en 36 secciones iguales. En cada una de estas secciones, identificaron grupos de estrellas o constelaciones muy brillantes y reconocibles. A estos 36 grupos estelares los llamaron 'Los Decanos'.",
    "La mecánica de este reloj estelar era sorprendentemente simple pero matemáticamente brillante. A medida que la Tierra rotaba durante la noche, un nuevo Decano aparecía en el horizonte este. El tiempo exacto que transcurría entre la aparición de un Decano y el siguiente fue considerado como una unidad de tiempo.",
    "Durante una noche típica de verano en Egipto, los sacerdotes podían observar la salida de 12 de estos Decanos. Debido a esto, tomaron la revolucionaria decisión de dividir la noche completa en exactamente 12 partes iguales. Así es, el concepto universal de que la noche (y por extensión, el día) tiene 12 horas, fue un invento directo de la astronomía egipcia.",
    "Pero para los egipcios, la ciencia siempre estaba entrelazada con la magia y la religión. Los Decanos no eran simples marcadores de tiempo; eran considerados deidades menores o espíritus poderosos que gobernaban el destino del universo y protegían a las personas según la hora de la noche.",
    "Tanta era su importancia, que los faraones y nobles egipcios ordenaban pintar complejos y hermosos 'relojes estelares diagonales' en los techos de sus tumbas y ataúdes. Querían asegurarse de que, incluso en la muerte, su alma siempre supiera qué hora era mientras navegaba por los peligros del inframundo.",
    "Esta fusión entre la observación científica empírica y la mitología espiritual hace que el estudio de los Decanos sea uno de los capítulos más fascinantes de la historia de la ciencia y la medición del tiempo."
  ],
  "egypt_m3": [
    "De todas las luces que titilan en la cúpula nocturna, hay una estrella que reina suprema sobre las demás: Sirio. Vista desde nuestro planeta, es la estrella más brillante de todo el cielo nocturno. Pero para los antiguos habitantes del Valle del Nilo, Sirio era mucho más que una simple estrella brillante; era la entidad más sagrada del cosmos.",
    "Los egipcios la llamaban 'Sopdet', y la personificaban como una diosa de deslumbrante belleza y poder protector. Imagina vivir en una sociedad donde el destino de millones de personas dependía por completo de los movimientos de un solo punto de luz en el cielo. Así de crucial era Sopdet para Egipto.",
    "El comportamiento astronómico de Sirio/Sopdet era visto como un evento verdaderamente mágico y predecible. Cada año, la estrella desaparecía completamente del cielo nocturno durante un período de exactamente 70 días, oculta por el brillo cegador del sol.",
    "Para la teología egipcia, estos 70 días representaban el tiempo en el que la diosa viajaba a través de la Duat, el oscuro y misterioso inframundo. Era un período de espera, purificación y anticipación para todo el imperio.",
    "Y entonces, sucedía el milagro cósmico: el Orto Helíaco de Sirio. Era la sagrada madrugada en que Sopdet resurgía de la oscuridad, haciéndose visible por primera vez en meses, parpadeando intensamente justo sobre el horizonte oriental unos minutos antes de que saliera el sol.",
    "Este espectacular renacimiento estelar era el evento más importante del año egipcio, marcando oficialmente el Día de Año Nuevo. ¿La razón? Su reaparición en el cielo coincidía matemáticamente con el evento natural más vital del país: el inicio de la inundación anual del poderoso río Nilo.",
    "La inundación del Nilo no era un desastre, sino una bendición. Las aguas desbordadas depositaban una capa de lodo negro rico en nutrientes (llamado Kemet) sobre las arenas áridas, permitiendo el crecimiento de abundantes cosechas. Sin la crecida del río, anunciada fielmente por Sopdet, Egipto habría perecido de hambre.",
    "Por lo tanto, la astronomía y la observación meticulosa de Sirio eran literalmente la clave de la vida, la agricultura, la economía y la supervivencia de la civilización más grandiosa de la antigüedad."
  ],
  "egypt_m4": [
    "Si levantas la vista hacia el cielo del hemisferio norte en una noche despejada, probablemente buscarás la famosa formación de estrellas que conocemos como la Osa Mayor o 'El Cazo'. Sin embargo, si hubieras sido un niño en el antiguo Egipto hace 4,000 años, te habrían enseñado a ver algo completamente distinto.",
    "En lugar de un oso, los egipcios veían una gigantesca y poderosa pata delantera de un toro cósmico, a la cual llamaban la constelación de 'Mesjetiu'. Esta constelación tenía una característica astronómica muy especial: debido a su posición cerca del polo norte celeste, nunca se ponía por debajo del horizonte.",
    "Mientras otras estrellas nacían en el este y 'morían' en el oeste cada noche, Mesjetiu y sus estrellas vecinas giraban en círculos eternos alrededor del norte. Por esta razón, los egipcios llamaban a estas estrellas circumpolares 'Las Imperecederas' o 'Las Inmortales'.",
    "Creían fervientemente que estas estrellas que nunca desaparecían eran los destinos finales y eternos de las almas de los faraones y los dioses, viviendo por siempre en el firmamento sin ser tocados por la muerte.",
    "Pero Mesjetiu no solo vivía en la mitología; era la herramienta tecnológica y de ingeniería más crítica del imperio. Los sacerdotes la usaban como un inmenso y preciso compás divino para orientar todas sus construcciones sagradas en la Tierra.",
    "Antes de construir cualquier templo o pirámide, se llevaba a cabo un misterioso ritual nocturno llamado 'El Estiramiento de la Cuerda'. El Faraón, asistido por sacerdotes que representaban a Seshat (la diosa de la arquitectura y las matemáticas), salía al desierto bajo las estrellas.",
    "Usando un instrumento especial de observación llamado 'merkhet', se alineaban visualmente con las estrellas de Mesjetiu para encontrar el Norte Verdadero geográfico con una precisión que hoy en día requeriría equipos láser y GPS.",
    "Gracias a esta constelación inquebrantable, lograron alinear construcciones como la Gran Pirámide con márgenes de error casi nulos, demostrando que la astronomía antigua egipcia era una ciencia sumamente sofisticada y exacta."
  ],
  "egypt_m5": [
    "Las majestuosas Pirámides de Giza se alzan sobre la meseta como montañas artificiales desafiando el paso del tiempo. No son solo las tumbas más grandes jamás construidas, sino que representan la cúspide de la ingeniería, las matemáticas y, sobre todo, la astronomía del mundo antiguo.",
    "Lo que más asombra a científicos, arquitectos y astrónomos modernos no es solo el peso de los millones de bloques de piedra, sino la alineación casi alienígena de las pirámides. Sus cuatro lados están alineados perfectamente con los cuatro puntos cardinales geográficos (Norte, Sur, Este y Oeste).",
    "El nivel de precisión es escalofriante: el margen de error es de apenas unas fracciones minúsculas de un solo grado. Alcanzar esta perfección hoy en día requiere brújulas magnéticas avanzadas, satélites topográficos y sistemas de posicionamiento global (GPS). ¿Cómo lo lograron los egipcios hace 4,500 años?",
    "La respuesta es que no utilizaron el magnetismo de la Tierra, porque el norte magnético se desplaza constantemente con el tiempo. Ellos apuntaron al Norte Verdadero, el eje de rotación real del planeta, y la única forma de encontrarlo era utilizando la bóveda estrellada como guía.",
    "Para lograrlo, los ingenieros construían inmensos muros circulares perfectamente nivelados en el sitio de construcción. Estos muros actuaban como un horizonte artificial limpio, bloqueando la visión de dunas irregulares u otros obstáculos terrestres.",
    "Durante la noche, un maestro astrónomo se situaba en el centro exacto del círculo. Observaba minuciosamente el punto exacto por donde una estrella específica emergía en el este (su nacimiento) y el punto exacto por donde se ocultaba en el oeste (su muerte), marcando ambos puntos en el muro circular.",
    "Trazando líneas desde el centro hacia ambas marcas, se formaba un ángulo. Al dividir geométricamente ese ángulo justo por la mitad (una bisectriz), la línea central resultante apuntaba de manera inmutable e inquebrantable hacia el Norte Verdadero geográfico.",
    "Esta técnica de bisección estelar permitió que las Pirámides de Giza quedaran ancladas a la Tierra utilizando las matemáticas del cielo, fusionando el mundo mortal con el orden cósmico perfecto."
  ],
  "egypt_m6": [
    "Profundamente enterrada bajo las abrasadoras arenas cerca de los acantilados de Deir el-Bahari, existe una cámara subterránea que permaneció oculta en la oscuridad durante milenios. Es la tumba catalogada como TT353, que perteneció a un hombre extraordinario llamado Senenmut.",
    "Senenmut no era un faraón, sino un genio plebeyo que ascendió hasta convertirse en el Arquitecto Real y el asesor más íntimo de Hatshepsut, una de las faraonas más poderosas y exitosas que jamás haya gobernado Egipto.",
    "A diferencia de las tumbas reales llenas de tesoros de oro y estatuas colosales, el verdadero tesoro de Senenmut estaba pintado en el techo de su cámara funeraria. Al iluminarlo, se revela el mapa astronómico del universo más antiguo que la humanidad haya descubierto hasta ahora.",
    "Este asombroso techo astronómico no es solo arte decorativo; es un catálogo enciclopédico y científico del cosmos, dividido magistralmente en dos mitades perfectas: el hemisferio celeste norte y el hemisferio celeste sur.",
    "En la sección del cielo norte, los astrónomos modernos pueden identificar claramente las representaciones de los doce meses del calendario lunar, así como enormes figuras de deidades egipcias que custodian las constelaciones circumpolares.",
    "En el hemisferio sur, la pintura documenta meticulosamente la lista de los Decanos (las estrellas que miden las horas), alineaciones planetarias clave como las de Júpiter y Saturno, e incluso a la diosa Isis navegando a través de la banda de la Vía Láctea en su barca solar.",
    "Para Senenmut, este complejo panel astronómico tenía un propósito trascendental. No era para enseñar ciencia a los vivos, sino un GPS espiritual, un intrincado mapa de navegación para que su propia alma pudiera encontrar el camino a través del laberinto estrellado después de la muerte.",
    "El descubrimiento de este techo cambió para siempre nuestra comprensión del conocimiento astronómico egipcio, demostrando que su comprensión del universo era mucho más profunda, documentada y sofisticada de lo que los historiadores creían posible."
  ],
  "egypt_m7": [
    "En el corazón oscuro y silencioso de la Gran Pirámide del Faraón Keops, rodeadas por millones de toneladas de roca sólida, se encuentran dos misteriosas habitaciones conocidas como la Cámara del Rey y la Cámara de la Reina. Durante siglos, estas cámaras guardaron un secreto arquitectónico que desconcertaba a todos.",
    "Desde los muros de estas cámaras, se abren unos pequeños y estrechos túneles, de apenas 20 centímetros cuadrados de ancho. Estos conductos se extienden en diagonales ascendentes a través de la masa de la pirámide hasta salir al exterior. Al principio, los primeros exploradores asumieron que eran simples 'canales de ventilación' para dar aire fresco a los obreros.",
    "Sin embargo, la ciencia moderna intervino para revelar la verdad. A partir de los años 90, equipos de ingenieros utilizaron pequeños robots equipados con cámaras de fibra óptica (como el proyecto Upuaut) para arrastrarse por el interior de estos misteriosos túneles milenarios.",
    "Las mediciones robóticas y láser revelaron algo fascinante: estos canales no eran para ventilación, sino que eran 'telescopios de piedra' fijos, huecos arquitectónicos alineados con ángulos matemáticos perfectos para apuntar a regiones muy específicas del cielo nocturno.",
    "Los cálculos arqueoastronómicos confirmaron que el canal que apuntaba hacia el sur desde la Cámara del Rey estaba alineado con precisión milimétrica hacia el cinturón de la constelación de Orión, la cual los egipcios asociaban directamente con el poderoso dios Osiris, señor de la resurrección.",
    "El canal que apuntaba hacia el norte, por su parte, estaba dirigido exactamente hacia Thuban (la estrella polar de aquella época) y las constelaciones circumpolares inmortales, conocidas como las estrellas 'Imperecederas'.",
    "Estos conductos no estaban hechos para que los vivos respiraran, sino que eran autopistas espirituales, cañones cósmicos diseñados para que el alma inmaterial del Faraón muerto pudiera ser disparada a la velocidad de la luz hacia las constelaciones sagradas, donde se transformaría en una estrella por toda la eternidad."
  ],
  "egypt_m8": [
    "En el extremo sur del imperio egipcio, justo en la frontera con Nubia, el río Nilo fluye junto a inmensas montañas de roca arenisca. Fue en este dramático paisaje donde el Faraón Ramsés II, conocido como 'Ramsés el Grande', decidió construir uno de los monumentos más imponentes de la historia: el Templo de Abu Simbel.",
    "En lugar de construir el templo bloque por bloque, ordenó a miles de canteros que tallaran el templo entero directamente dentro de la cara sólida de la montaña. La entrada está fuertemente custodiada por cuatro estatuas colosales del faraón, cada una de 20 metros de altura, dominando el paisaje como titanes.",
    "Pero la verdadera magia de Abu Simbel no está en su inmensa fachada exterior, sino en un secreto astronómico meticulosamente oculto en sus profundidades. Para descubrirlo, hay que adentrarse 60 metros dentro de la montaña oscura, atravesando grandes pasillos y estatuas de dioses.",
    "Al fondo de este abismo artificial, se encuentra el santuario más recóndito, un cuarto sumido en la oscuridad perpetua los 365 días del año. Allí, talladas en la roca del fondo, están sentadas las estatuas de cuatro dioses principales: Ra-Horajti, Ramsés deificado, Amón-Ra y Ptah.",
    "El milagro astronómico ocurre únicamente dos amaneceres al año: el 22 de octubre (el día tradicional del cumpleaños de Ramsés) y el 22 de febrero (el aniversario de su coronación como faraón). En estas dos fechas exactas, y solo en estas, ocurre un fenómeno que desafía la lógica arquitectónica.",
    "Cuando el primer rayo del sol de la mañana se asoma por el horizonte oriental, penetra por la puerta del templo, cruza a la velocidad de la luz los 60 metros del oscuro pasillo como un rayo láser, e ilumina brillante y mágicamente los rostros de Ra, Ramsés y Amón-Ra.",
    "Increíblemente, gracias a los cálculos astronómicos precisos de los ingenieros, el rayo de luz se detiene justo antes de iluminar a Ptah, el cuarto dios, manteniéndolo en las sombras. Esto se debe a que Ptah es el dios del inframundo y la creación oscura, y su rostro mitológicamente nunca debe ser tocado por la luz del sol.",
    "Este fenómeno solar es un testimonio deslumbrante del dominio egipcio sobre la arquitectura, las matemáticas y el movimiento celestial, un milagro de precisión que ha funcionado de manera ininterrumpida durante más de 3,200 años."
  ],
  "egypt_m9": [
    "Imagina caminar por las majestuosas salas del Templo de Dendera, dedicado a la diosa Hathor, la deidad del amor, la música y el cielo estrellado. Si subes por una pequeña y oscura escalera secreta hasta llegar a una capilla en el techo, y levantas la mirada, te encontrarás con uno de los artefactos más misteriosos e importantes de la antigüedad.",
    "Tallado en relieve sobre un gigantesco bloque cuadrado de arenisca que pesaba varias toneladas, los arqueólogos descubrieron el famoso 'Zodiaco de Dendera'. Es un inmenso planisferio astronómico, un mapa circular del universo esculpido en piedra dura.",
    "Este gigantesco disco representa la bóveda celeste completa, pero proyectada en un plano bidimensional, como si el ojo de un dios estuviera mirando hacia abajo sobre el sistema solar. Pero lo que hace único a este zodiaco es la increíble mezcla de culturas que contiene.",
    "Fue esculpido durante la era Ptolemaica (los últimos días de la civilización egipcia, cuando los faraones tenían origen griego). Por ello, el disco es un asombroso crisol cósmico donde convergen la magia egipcia milenaria, la astrología mística de Babilonia y las estrictas matemáticas de los eruditos griegos.",
    "Al observarlo detenidamente, se pueden identificar por primera vez las representaciones clásicas de los 12 signos zodiacales que usamos hoy en la cultura occidental (Aries el carnero, Tauro el toro, Escorpio el escorpión), pero están mezclados y escoltados por inmensos dioses egipcios que sostienen el cielo.",
    "Además de ser un mapa estelar simbólico, el Zodiaco de Dendera funcionaba como un registro histórico inalterable. Los astrónomos modernos han descubierto que los relieves señalan eventos astronómicos reales y específicos que ocurrieron en el año 51 a.C.",
    "El mapa documenta matemáticamente la posición exacta en que se alinearon cinco planetas conocidos (Mercurio, Venus, Marte, Júpiter y Saturno) e incluso registra la fecha de ocurrencia de eclipses solares y lunares históricos, usando símbolos de dioses siendo devorados por sombras.",
    "El Zodiaco de Dendera es verdaderamente una supercomputadora celeste prehistórica petrificada, un testamento de cómo la humanidad siempre ha buscado su lugar en el universo mapeando el movimiento de las esferas celestiales."
  ],
  "egypt_m10": [
    "En el año 1922, el mundo contuvo la respiración cuando el obstinado arqueólogo británico Howard Carter descubrió la tumba intacta del joven Faraón Tutankamón en el Valle de los Reyes. Durante meses, se maravillaron con carros dorados, tronos y máscaras de oro macizo.",
    "Pero tres años después, en 1925, al examinar la momia misma del faraón bajo gruesas capas de lino, Carter encontró algo oculto junto al muslo derecho del rey: una daga finamente elaborada. Su mango estaba hecho de oro ricamente decorado con cristal de roca, pero lo que desconcertó a la ciencia fue la hoja de la daga.",
    "La hoja, increíblemente afilada, estaba hecha de hierro impecable. Esto presentaba un problema científico monumental: la época de Tutankamón pertenecía de lleno a la Edad del Bronce. Los egipcios de hace 3,300 años no tenían los hornos necesarios para alcanzar las temperaturas extremas que requiere la fundición de minerales de hierro terrestres.",
    "Además, si alguna vez has dejado una herramienta de hierro afuera bajo la lluvia, sabes que rápidamente se convierte en polvo rojo oxidado. Sin embargo, la daga de Tutankamón había permanecido enterrada durante milenios y su hoja de hierro estaba prístina, brillante y completamente libre de óxido. ¿Cómo era esto posible?",
    "El misterio se mantuvo hasta el año 2016, cuando investigadores modernos utilizaron espectrometría de fluorescencia de rayos X portátiles (una tecnología que no daña los artefactos) para bombardear la hoja y analizar su composición química exacta a nivel molecular.",
    "Los resultados fueron de otro mundo, literalmente. El hierro de la hoja contenía un porcentaje muy alto de níquel (alrededor del 11%) y rastros muy específicos de cobalto. Esta huella química es idéntica a la composición de los meteoritos férricos que cruzan el espacio profundo.",
    "El Faraón no portaba un arma hecha de piedras terrestres; su daga estaba forjada del núcleo sólido de un asteroide que había viajado millones de kilómetros por el vacío del espacio antes de estrellarse contra el desierto egipcio como una estrella fugaz.",
    "Sorprendentemente, los egipcios eran conscientes del origen extraterrestre de este material. En sus jeroglíficos, la palabra que utilizaban para referirse a este raro hierro era 'Bia-en-pet', que se traduce literalmente como 'El metal que vino del cielo'. ¡Tutankamón empuñaba verdadera magia estelar en sus manos!"
  ],
  "egypt_m11": [
    "Para los antiguos egipcios, el universo no era el vasto, oscuro y frío vacío lleno de radiación que conocemos hoy. Para ellos, el cosmos era un ser gigantesco, vivo, cálido y profundamente mágico. Todo lo que ocurría en la Tierra tenía un reflejo directo en los cielos.",
    "Si te acostaras en las dunas del desierto en una noche oscura y clara, verías la Vía Láctea, la galaxia espiral en la que vivimos. Nosotros la entendemos como una franja lechosa formada por cientos de miles de millones de estrellas lejanas, pero ellos veían algo mucho más poético.",
    "Ellos veían a 'Nut', la inmensa, poderosa y protectora diosa del cielo nocturno. En la mitología, Nut era representada como una enorme mujer arqueada sobre la Tierra. Sus dedos de las manos tocaban el horizonte lejano en el occidente, mientras que los dedos de sus pies se anclaban firmemente en el horizonte oriente.",
    "Su cuerpo azul oscuro estaba decorado por todas las estrellas del universo. Creían fervientemente que, cada tarde, Nut se tragaba al dios del sol (Ra) y que este viajaba como una chispa dorada por el interior de su cuerpo durante toda la noche.",
    "A la mañana siguiente, en medio de los vibrantes colores rosados del amanecer, Nut daba a luz al Sol nuevamente, garantizando así que la luz, el calor y la vida continuaran existiendo en la Tierra por un día más en un ciclo de eterno renacimiento.",
    "El principio filosófico más grande de Kemet era 'Maat', el orden universal. Una de sus reglas era que el mundo celestial debía ser un reflejo espejo perfecto del mundo terrenal. Así como Egipto dependía absolutamente de las aguas del río Nilo para vivir, el cielo también debía tener su propio río.",
    "Los sacerdotes interpretaron que la brillante cinta de polvo estelar de la Vía Láctea era en realidad el Nilo Celestial, un río de luz etérea. Pensaban que era sobre este gran cuerpo de agua estelar donde las almas purificadas y los dioses navegaban eternamente a bordo de brillantes barcas solares.",
    "Fascinados por esta idea del espejo cósmico, los egipcios alinearon y construyeron a propósito muchas de sus ciudades y templos sagrados a lo largo del Nilo terrestre, para reflejar y hacer eco de la geografía del inmenso río espacial que fluía sobre sus cabezas."
  ],
  "egypt_m12": [
    "Entre todas las grandes e imponentes maravillas que proyectan profundas sombras en los inmensos templos de Egipto, pocas estructuras son tan hipnóticas y dominantes como los Obeliscos. Estas estructuras son un testimonio innegable de la megalomanía y la brillantez técnica de los constructores antiguos.",
    "Imagina gigantescas agujas de roca sólida de hasta 30 metros de altura, que pesan cientos de toneladas. Lo más alucinante es que no están formadas por bloques apilados; cada obelisco era tallado de un solo, masivo e ininterrumpido bloque de granito extraído de canteras lejanas.",
    "Estos colosos de piedra culminaban en la parte superior en una pequeña pirámide en miniatura llamada 'piramidión'. En la antigüedad, esta punta estaba recubierta con capas de oro puro o 'electrum' (una mezcla natural de oro y plata), diseñada para destellar de forma cegadora al atrapar los rayos del sol.",
    "Pero sería un gran error pensar que los obeliscos eran simples decoraciones estéticas para adornar las entradas de templos formidables como los de Karnak y Luxor. En realidad, eran instrumentos científicos monumentales, gigantescas herramientas astronómicas ancladas permanentemente al suelo.",
    "Un obelisco funcionaba como un colosal 'gnomon'. En astronomía y relojería antigua, un gnomon es la barra central o aguja vertical de un reloj de sol, cuyo único propósito es interceptar la luz y proyectar una sombra clara y definida sobre una superficie calibrada.",
    "A lo largo del día, el deslumbrante sol egipcio proyectaba la inmensa y afilada sombra del obelisco sobre el suelo empedrado del templo. Sacerdotes altamente entrenados medían meticulosamente la longitud y la dirección exacta en que la sombra se arrastraba sobre marcas geométricas talladas en el piso.",
    "A través del estudio de estas sombras, podían saber con asombrosa precisión no solo qué hora del día era, sino algo mucho más importante para un imperio agrario: la fecha exacta en el año solar.",
    "Rastreando los días en que la sombra del mediodía alcanzaba su punto más largo y su punto más corto, los astrónomos identificaban con certeza matemática las fechas de los solsticios de invierno y verano, permitiendo a todo el país sincronizar sus cosechas con los ciclos estelares."
  ],
  "egypt_m13": [
    "Hoy en día, das por sentado que un año tiene exactamente 365 días, que se divide en 12 meses, y puedes revisar la fecha en tu celular en cualquier momento. Pero retrocedamos 5,000 años atrás; vivir en la antigüedad significaba vivir en un absoluto caos calendárico.",
    "La mayoría de las grandes civilizaciones primitivas basaban sus calendarios en la observación de las fases de la luna. Aunque esto era fácil de observar, los ciclos lunares son matemáticamente caóticos comparados con el ciclo del sol. Rápidamente, los meses lunares se desfasaban de las estaciones reales (invierno, verano, lluvias).",
    "Para corregir este desastre, los líderes antiguos tenían que inventar e insertar arbitrariamente 'meses sorpresa' o días extraídos de la nada para que las estaciones volvieran a coincidir, lo cual generaba una enorme confusión económica y agrícola.",
    "Pero Egipto era una superpotencia construida en el desierto, cuya existencia entera pendía del fino hilo de las inundaciones anuales del río Nilo. No podían permitirse márgenes de error ni calendarios caóticos; necesitaban orden y una precisión astronómica absoluta.",
    "Gracias a siglos de observación cuidadosa del sol y del orto helíaco de la estrella Sirio, los brillantes astrónomos de Kemet hicieron un avance científico sin precedentes: crearon el primer calendario civil estandarizado basado directamente en el ciclo de traslación del planeta alrededor del Sol.",
    "Con asombrosa matemática, decidieron que el año ideal tendría 365 días. Estructuraron este calendario en 12 meses idénticos, a los que asignaron exactamente 30 días a cada uno. El resultado era un año base perfecto y calculable de 360 días.",
    "Por supuesto, sabían que faltaban 5 días para completar la órbita terrestre. Para mantener la perfección de sus 12 meses, tomaron esos 5 días sobrantes y los agregaron al final del año, como una semana especial de vacaciones festivas. Los llamaron 'Los Días Epagómenos'.",
    "La mitología egipcia explicaba hermosamente estos 5 días extras argumentando que eran los misteriosos días en los que la diosa del cielo, Nut, dio a luz a sus cinco hijos divinos: Osiris, Horus, Seth, Isis y Neftis. Así, el orden astronómico moderno nació junto a las aguas del Nilo."
  ],
  "egypt_m14": [
    "Los cielos sobre el antiguo Egipto eran famosos por estar casi permanentemente despejados, con un sol dorado brillando con una intensidad predecible e inquebrantable día tras día. Pero, muy de vez en cuando, el universo decidía aterrorizar a la población con un evento verdaderamente catastrófico.",
    "Sin que la gente común supiera lo que estaba por ocurrir, en medio del día, una sombra antinatural comenzaba a devorar lentamente al sol. El aire del desierto se volvía frío de golpe, las aves dejaban de cantar, los animales se escondían presa del pánico y una oscuridad sobrenatural y tétrica cubría el mundo entero al mediodía.",
    "Hoy sabemos gracias a la ciencia que esto es un Eclipse Solar Total, provocado por una simple coincidencia orbital donde la luna pasa exactamente entre la Tierra y el Sol, proyectando su sombra sobre nosotros. Pero para los egipcios, esto no era un juego orbital; era el fin de la existencia misma.",
    "El sol era la encarnación visible de su deidad suprema, Ra. Si el sol desaparecía, significaba que las fuerzas del mal estaban ganando. Veían el eclipse como el momento espantoso en que Apofis, una inmensa y malévola serpiente gigante del inframundo hecha de caos y oscuridad, había logrado emboscar a Ra.",
    "Creían que la serpiente monstruosa estaba literalmente tragándose el barco solar del dios en pleno cielo. Para el ciudadano promedio de Egipto, el pánico era absoluto; creían que la luz nunca regresaría y que el universo se derrumbaría en la fría oscuridad.",
    "Sin embargo, los sacerdotes astrónomos de más alto rango habían llevado registros minuciosos durante siglos. Ellos habían descubierto los oscuros patrones matemáticos (similares a los ciclos de Saros babilónicos) y podían predecir empíricamente cuándo ocurriría el próximo eclipse.",
    "Cuando la oscuridad caía, los sacerdotes lideraban enormes rituales masivos de 'rescate'. La multitud gritaba, golpeaba estatuas de serpientes con varas, tocaba tambores frenéticamente y lanzaba hechizos mágicos al cielo para obligar al demonio Apofis a vomitar a Ra.",
    "Y como la matemática orbital dictaba que el eclipse duraría solo unos minutos, el sol inevitablemente regresaba a brillar, convenciendo a todos de que la magia y la astronomía del Faraón habían triunfado una vez más sobre el caos absoluto, salvando al mundo de la destrucción."
  ],
  "egypt_m15": [
    "Durante más de cuatro mil años, los asombrosos sabios y astrónomos del antiguo Egipto mantuvieron sus ojos fijos firmemente en los cielos nocturnos. Mapearon las estrellas, rastrearon los planetas y escribieron los movimientos del cosmos en papiro y roca dura.",
    "Hoy en día, milenios después de que el último faraón cerrara sus ojos, la humanidad ha cerrado un poético ciclo cósmico. Nosotros ahora somos los que estamos flotando allá arriba, en medio del polvo de estrellas negro que ellos tanto estudiaron.",
    "Y desde el frío e inmenso abismo del espacio orbital, hemos dirigido nuestras miradas y nuestras cámaras más poderosas hacia abajo, apuntando de vuelta a los áridos desiertos de Egipto. Esta es la emocionante y revolucionaria era de la Arqueoastronomía Satelital Espacial.",
    "Satélites hiper-tecnológicos, operados por instituciones como la NASA (Agencia Espacial Estadounidense) y la ESA (Agencia Espacial Europea), orbitan nuestro planeta a miles de kilómetros de altura, bombardeando el desierto del Sahara con escáneres infrarrojos penetrantes y radares de apertura sintética.",
    "Estos escáneres están cazando algo invisible para el ojo humano: firmas de temperatura sutiles. Bajo metros y metros de dunas de arena en constante movimiento, se encuentran escondidas ciudades perdidas, inmensos muros y pirámides olvidadas hechas de pesados ladrillos de adobe y roca.",
    "La magia científica detrás de esto es que la arena y la piedra absorben y liberan la radiación solar y la humedad a ritmos y temperaturas diferentes. Desde el espacio térmico, las cámaras captan estas diferencias milimétricas de calor.",
    "Supercomputadoras en la Tierra procesan estas señales satelitales y logran dibujar, casi como por arte de magia espectral, mapas perfectos que muestran grandes plazas, avenidas y enormes pirámides enterradas que parecen flotar sobre una pantalla negra de computadora.",
    "En las últimas dos décadas, estos poderosos 'Telescopios Espaciales que miran a la Tierra' han desenterrado digitalmente más de 17 pirámides desconocidas y más de 3,000 antiguos asentamientos, confirmando que la tecnología espacial moderna es la herramienta arqueológica definitiva. ¡Literalmente, las estrellas nos están revelando los secretos del pasado!"
  ]
};

const updatedData = COURSE_DATA.map(mod => {
  if (mod.id && mod.id.startsWith('egypt_m') && mod.contentEs && mod.contentEs.sections) {
    if(TOPIC_DETAILS[mod.id]) {
      // Reemplazamos la sección única con un nuevo texto masivo
      mod.contentEs.sections[0].text = TOPIC_DETAILS[mod.id];
    }
  }
  return mod;
});

const fileContent = `export const COURSE_DATA = ${JSON.stringify(updatedData, null, 2)};\n`;
fs.writeFileSync('lib/courseData.js', fileContent, 'utf8');
console.log('Successfully expanded all 15 modules with massive content.');
