import fs from 'fs';
import { COURSE_DATA } from './lib/courseData.js';

const EXPANDED_TEXTS = {
  "egypt_m1": [
    "¡Saludos, joven astrónomo! Hoy viajamos muy atrás en el tiempo, mucho antes de que las famosas pirámides de Giza fueran siquiera imaginadas. Nos adentramos en lo profundo del ardiente desierto del Sahara, donde hace más de 7,000 años, existió un misterio fascinante: Nabta Playa. Imagina estar rodeado de arena dorada y encontrar un círculo perfecto de enormes piedras megalíticas erigidas por tribus nómadas. Estas tribus no tenían tecnología moderna, pero poseían algo más poderoso: la capacidad de observar las estrellas con una precisión asombrosa.",
    "Estas piedras no estaban puestas al azar. Fueron cuidadosamente alineadas para rastrear el solsticio de verano. Para las tribus del desierto, saber exactamente cuándo ocurriría el solsticio era una cuestión de supervivencia, pues anunciaba la llegada de las preciosas lluvias de verano. Este círculo de piedras gigantes funcionaba como un gigantesco y silencioso reloj estelar. De hecho, los científicos han confirmado que Nabta Playa es el observatorio astronómico más antiguo del mundo, superando en antigüedad al mismísimo Stonehenge en Inglaterra.",
    "Pero la magia no termina ahí. Investigaciones modernas han revelado que las piedras centrales de Nabta Playa apuntan directamente hacia el cinturón de la constelación de Orión. Los antiguos pobladores consideraban que las estrellas eran guías celestiales, mapas luminosos que dictaban cuándo mover a sus rebaños hacia fuentes de agua vitales. El profundo conocimiento astronómico de esta antigua civilización sentó las bases de todo lo que los poderosos faraones de Egipto aprenderían miles de años después. Nabta Playa es la semilla de la ciencia astronómica."
  ],
  "egypt_m2": [
    "Imagina que estás en medio del desierto durante la noche, en plena oscuridad, y necesitas saber qué hora es. No tienes un reloj de pulsera ni un teléfono celular. ¿Qué harías? Los sabios y sacerdotes astrónomos de Egipto encontraron la solución mirando hacia el cielo. Dividieron la cúpula estrellada en 36 grupos de constelaciones o estrellas muy brillantes que aparecían en el horizonte a lo largo del año. A estos grupos los llamaron 'Los Decanos'.",
    "A medida que la noche avanzaba, la aparición de un nuevo decano en el horizonte marcaba con precisión el paso de lo que hoy conocemos como una hora. En total, durante una noche normal, observaban la salida de 12 de estos decanos, lo que llevó a los egipcios a dividir la noche en 12 partes iguales. Así es, si alguna vez te preguntaste de dónde sacamos la idea de que la noche y el día tienen 12 horas, ¡la respuesta está en la antigua astronomía del río Nilo!",
    "Sin embargo, los decanos no eran solo herramientas científicas para medir el tiempo. Para los egipcios, cada grupo de estrellas representaba a espíritus poderosos, guardianes o deidades menores que gobernaban el destino de las personas según el momento en que nacían, una forma temprana de astrología. Es por esto que los faraones mandaban a pintar hermosos y detallados 'relojes estelares' en los techos de sus tumbas, para que sus almas siempre supieran la hora exacta durante su viaje por el inframundo."
  ],
  "egypt_m3": [
    "Entre todas las estrellas que parpadean en el manto de la noche, hay una que reina sobre todas: Sirio. Para nosotros, es la estrella más brillante de la constelación del Can Mayor, pero para los antiguos egipcios, era 'Sopdet', la estrella más sagrada y vital de todas. Imagina una estrella tan importante que el destino de un imperio entero dependía de ella. Sopdet representaba a una diosa celestial hermosa y protectora, cuyo poder garantizaba que Egipto floreciera cada año.",
    "El comportamiento de esta estrella en el cielo era mágico. Cada año, Sopdet desaparecía del cielo nocturno durante exactamente 70 días, ocultándose detrás de la luz del sol. Para los egipcios, este era el tiempo en que la diosa viajaba por el misterioso inframundo (la Duat). Y entonces, ocurría el gran evento: el Orto Helíaco. Era la madrugada en que Sopdet volvía a ser visible por primera vez, parpadeando intensamente justo sobre el horizonte oriental antes de que saliera el sol.",
    "Este espectacular renacimiento cósmico marcaba el comienzo del Año Nuevo egipcio. ¿Pero por qué tanta emoción por una estrella? Porque la aparición de Sopdet coincidía exactamente con el inicio de la inundación anual del poderoso río Nilo. Las aguas del río crecían y depositaban un barro negro y súper fértil (el Kemet) sobre las arenas secas, permitiendo que crecieran las cosechas. Sin la inundación del Nilo anunciada por Sopdet, Egipto se habría muerto de hambre. ¡Ellos debían su vida a una estrella!"
  ],
  "egypt_m4": [
    "Levanta la vista hacia el cielo del norte en una noche despejada y buscarás lo que hoy llamamos la Osa Mayor o 'El Gran Cazo'. Sin embargo, si hubieras nacido hace miles de años en Egipto, habrías visto algo completamente diferente: una gigantesca pata delantera de un toro cósmico a la que llamaban 'Mesjetiu'. A diferencia de otras constelaciones, Mesjetiu era especial porque nunca se ocultaba bajo el horizonte; giraba eternamente en círculos alrededor del Polo Norte celeste.",
    "Los egipcios llamaban a estas estrellas circumpolares las 'Imperecederas', porque a sus ojos, eran almas de dioses y faraones inmortales que nunca morían (nunca se ponían). Mesjetiu no solo era una constelación importante para los mitos; era la herramienta de ingeniería y arquitectura más importante de la antigüedad. Literalmente utilizaban esta constelación en el cielo como un compás divino para construir sus colosales maravillas en la Tierra.",
    "A través de un elaborado ritual místico llamado 'El Estiramiento de la Cuerda', la diosa Seshat (diosa de la arquitectura y la astronomía) y el Faraón salían a la intemperie en la oscuridad. Observaban la posición exacta de Mesjetiu usando un instrumento bífido llamado merkhet, y trazaban líneas en el suelo con cuerdas. Gracias a esta alineación estelar, lograron construir la Gran Pirámide de Giza alineándola con el norte geográfico verdadero con una precisión casi imposible, que hoy en día asombra a los científicos modernos."
  ],
  "egypt_m5": [
    "Las Grandes Pirámides de Giza no son solo tumbas masivas de piedra; son instrumentos astronómicos y matemáticos construidos a una escala que el mundo nunca ha vuelto a ver. Es la última maravilla del mundo antiguo que aún sigue en pie. Sus lados están alineados de manera tan milimétrica a los cuatro puntos cardinales (Norte, Sur, Este y Oeste) que el margen de error es menor a una fracción minúscula de un grado. La gran pregunta es: ¿Cómo lograron semejante nivel tecnológico sin brújulas magnéticas, satélites o GPS?",
    "El asombroso secreto yace en las estrellas y en la brillantez geométrica de los astrónomos egipcios. Como el norte magnético cambia con los años, ellos no usaban el campo magnético de la Tierra; usaban el Norte Verdadero apuntado por el eje de rotación del planeta. Para encontrarlo, los ingenieros construían muros circulares perfectamente nivelados que simulaban un horizonte artificial, bloqueando las dunas y distracciones del desierto.",
    "Luego, un sacerdote astrónomo observaba desde el centro exactamente por dónde nacía una estrella en el horizonte este, y por dónde se ponía en el oeste. Marcaba ambos puntos en el muro y trazaba un ángulo. Al dividir ese ángulo exactamente a la mitad utilizando cuerdas y geometría básica, la línea central apuntaba como un láser inquebrantable hacia el Norte Verdadero y eterno. ¡Así, las pirámides se anclaron a la Tierra utilizando las estrellas de los cielos!"
  ],
  "egypt_m6": [
    "Nos adentramos en los oscuros y misteriosos túneles bajo las arenas cerca de Deir el-Bahari, hasta encontrar la tumba secreta designada como TT353. Esta tumba perteneció a Senenmut, un brillante arquitecto y el consejero más importante de una de las faraonas más poderosas de la historia: Hatshepsut. Lo que Senenmut dejó en el techo de la cámara funeraria no fue oro ni joyas, sino un tesoro infinitamente más valioso para la ciencia moderna.",
    "Al alumbrar el techo con antorchas, lo que aparece es el mapa del universo más antiguo que jamás se haya pintado. Es el primer catálogo estelar astronómico documentado de la humanidad. El techo está mágicamente dividido en dos partes: el hemisferio del cielo norte y el hemisferio del cielo sur. Este panel es una representación enciclopédica del conocimiento de los sacerdotes de Kemet sobre cómo funcionaban los engranajes cósmicos.",
    "En el hemisferio norte se pueden identificar a los doce grupos de meses lunares y a dioses protegiendo las constelaciones, mientras que en el sur, figuran los Decanos, los planetas Júpiter y Saturno alineados majestuosamente, e incluso Isis cruzando la bóveda celeste a bordo de un bote estelar brillante. Para Senenmut, este no era solo un mapa para científicos; era un GPS espiritual, una guía cartográfica meticulosa para que su alma pudiera navegar por el laberinto oscuro del espacio profundo en su viaje hacia la eternidad."
  ],
  "egypt_m7": [
    "Dentro del vientre de la Gran Pirámide del Faraón Keops se esconde uno de los enigmas más grandes de la arquitectura humana. Existen estrechos canales de ventilación, de unos 20 centímetros cuadrados, que suben en diagonales ascendentes desde las Cámaras del Rey y de la Reina a través de miles de toneladas de roca sólida. Al principio, los arqueólogos creían que eran simples ductos para proveer aire a los obreros esclavizados durante la construcción de la cámara funeraria profunda.",
    "Pero la ciencia moderna demostró algo mucho más asombroso. Al introducir robots miniaturizados con cámaras en la década de los 90, los científicos confirmaron que estos canales eran cañones huecos, telescopios de piedra apuntando hacia la bóveda celeste. Su inclinación es precisa, calculada para mirar directamente a partes vitales del cielo negro. Era un sofisticado observatorio integrado en una montaña artificial.",
    "Los egiptólogos concluyeron que el canal sur apuntaba en línea recta hacia la constelación de Orión (asociada al gran dios Osiris) y a la brillante estrella Sirio (la diosa Isis). El canal norte apuntaba directo a las estrellas polares, las 'Imperecederas'. Estos túneles estelares no eran para que los vivos respiraran, sino los conductos físicos por donde se creía que el alma inmaterial del Faraón se dispararía a velocidades cósmicas, directo al corazón de los dioses, para transformarse en una estrella por toda la eternidad."
  ],
  "egypt_m8": [
    "Viajemos al extremo sur de Egipto, donde las montañas de roca sólida se levantan junto al Nilo. Allí, el faraón Ramsés II, conocido por ser el constructor más ambicioso y megalómano de la historia antigua, ordenó tallar un templo completo directamente en la cara de un acantilado montañoso: Abu Simbel. Por fuera, cuatro colosales estatuas sentadas de Ramsés, de 20 metros de alto, custodian la entrada como titanes petrificados. Pero el verdadero secreto astronómico yace oculto en las profundidades oscuras de la montaña.",
    "A 60 metros de profundidad dentro de la roca, al final de un pasillo rodeado de enormes pilares, se encuentra un santuario sumido en oscuridad perpetua. Allí, sentadas juntas, están talladas en la piedra las estatuas de cuatro deidades de gran poder: Ra-Horajti (dios del sol naciente), Ramsés II deificado, Amón-Ra (el rey de los dioses), y Ptah (el antiguo dios del inframundo y la oscuridad).",
    "Lo increíble sucede únicamente dos días al año, el 22 de octubre (cumpleaños de Ramsés) y el 22 de febrero (el aniversario de su coronación). Gracias a los alucinantes cálculos astronómicos y matemáticos de los arquitectos, al amanecer de esos días, un único, potente y delgado rayo de sol penetra la pequeña entrada del templo, cruza a la velocidad de la luz los 60 metros del pasillo oscuro e ilumina mágicamente los rostros de Ra, Ramsés y Amón. De manera espectacular, el rayo se detiene justo antes de Ptah, dejándolo en las sombras porque, según la mitología, es un dios del inframundo que nunca debe ser tocado por la luz. ¡Es un milagro de precisión astronómica que ha funcionado ininterrumpidamente por más de 3,200 años!"
  ],
  "egypt_m9": [
    "Suspendido en el tiempo, en el impresionante Templo de la diosa Hathor en Dendera, un grupo de arqueólogos europeos quedó paralizado de asombro al alumbrar el techo de una capilla elevada. Tallado en un inmenso bloque de arenisca con forma circular, de más de 2 metros y medio de diámetro y pesando toneladas, descubrieron uno de los mapas astronómicos más complejos e icónicos de la civilización: el Zodiaco de Dendera.",
    "Este mapa celestial es un gigantesco planisferio, un disco redondo que proyecta cómo se veía la bóveda estrellada, como si un ojo gigante la estuviera observando desde la Tierra. Sin embargo, no era un mapa astronómico cualquiera. El disco plasma la perfecta fusión de conocimientos milenarios; es el choque y abrazo cósmico entre la astrología babilónica, el orden griego y la profunda mitología mágica egipcia, pues fue creado durante la última dinastía ptolemaica.",
    "En él podemos identificar claramente la banda circular de los doce signos del zodiaco que usamos hoy (Aries, Tauro, Géminis...), pero están encriptados y re-imaginados a través del estilo de Kemet. Además de las constelaciones, los talladores registraron en la roca eventos reales e históricos: calcularon y tallaron un eclipse solar histórico, un eclipse lunar, e indicaron las posiciones planetarias de Marte, Venus y Mercurio alineados en los signos correctos. Es una computadora celeste prehistórica convertida en arte inquebrantable."
  ],
  "egypt_m10": [
    "Corría el año 1925, en el sofocante y polvoriento Valle de los Reyes, cuando el arqueólogo Howard Carter desenvolvía cuidadosamente los vendajes de la momia del famoso faraón niño, Tutankamón. Enterrado junto a su muslo derecho, escondido entre las capas de lino y oro, descubrió un objeto que no tenía ningún sentido: una hermosa y afilada daga. Su mango era de oro repujado adornado con cristales, pero el misterio científico estaba en su hoja brillante y limpia.",
    "La hoja estaba hecha de hierro impecable. Sin embargo, la Edad de Hierro no había llegado a Egipto en la época de Tutankamón; ellos solo trabajaban el bronce, el oro y el cobre, y no tenían los hornos calientes necesarios para fundir rocas de hierro terrestre. Además, el hierro normal de hace 3,000 años hoy sería polvo rojo oxidado, ¡pero esta daga estaba libre de óxido y reluciente como un espejo! ¿De dónde sacó Egipto el metal imposible?",
    "En el año 2016, usando tecnologías modernas como espectrometría de fluorescencia de rayos X portátiles, la ciencia reveló la alucinante verdad: el hierro poseía altos niveles de níquel y un rastro distintivo de cobalto. La hoja no se fundió de minerales terrícolas. El faraón empuñaba un arma forjada directamente de un meteorito férrico que impactó el desierto milenios atrás. Los egipcios ya sabían esto, pues llamaban al hierro 'Bia-en-pet', que significa 'El Hierro o Metal que vino del Cielo'. Era una daga espacial literal, caída de las estrellas y convertida en el arma del rey."
  ],
  "egypt_m11": [
    "Para los habitantes antiguos del Nilo, el universo no era un vacío oscuro e insensible; era una inmensa entidad viviente y mágica. Si mirabas el cielo nocturno y veías esa cinta lechosa y brillante que llamamos la Vía Láctea, no estabas viendo gases o cientos de miles de millones de soles lejanos. Estabas viendo a Nut, la inmensa diosa del cielo arqueada protegiendo nuestro mundo, con la punta de sus dedos tocando el oeste y sus pies anclados en el este.",
    "Su cuerpo azul oscuro estaba decorado por miríadas de estrellas. Cada noche, los egipcios explicaban el atardecer diciendo que Nut se tragaba al dios sol Ra, y este viajaba como una luz dorada a lo largo del sistema digestivo de su inmenso cuerpo durante las horas oscuras. Y cada mañana, en el horizonte oriente pintado de nubes rosadas y naranjas, Nut daba a luz al Sol nuevamente, en el milagro eterno del amanecer, asegurando que el mundo continuara girando.",
    "Bajo la ley universal de Kemet, conocida como 'Maat', existía una regla suprema: 'Como es arriba, es abajo'. Debía existir un equilibrio espejo entre el Cielo y la Tierra. Por lo tanto, interpretaron que la Vía Láctea, la cinta estelar brillante llena de nubes de polvo cósmico, era el verdadero Nilo del cielo (El Nilo Celestial). Era el inmenso río etéreo sobre cuyas aguas plateadas navegaban los dioses celestiales en sus mágicas barcas solares. Fascinantemente, orientaron muchos de sus templos en la orilla oeste y este de nuestro Nilo terrestre para imitar exactamente y reflejar ese inmenso río espacial."
  ],
  "egypt_m12": [
    "Entre todas las grandes maravillas que proyectan enormes sombras bajo el ardiente sol egipcio, los Obeliscos son las más elegantes e intimidantes. Imagina columnas esbeltas que miden hasta 30 metros de altura, monolitos tallados de una sola pieza en las canteras de granito rojo, sin cemento ni uniones. Estas 'agujas' masivas se coronaban con una punta piramidal bañada en electrum (una aleación de oro y plata) llamada piramidión, diseñada para destellar cegadoramente atrapando los primeros y últimos rayos solares del día.",
    "Pero no te equivoques, los obeliscos no eran simplemente gigantescas estacas de decoración para adornar la entrada a templos como Karnak o Luxor. Eran herramientas, instrumentos de astronomía gigantescos clavados en el suelo. Funcionaban como enormes gnomones. Un gnomon es la barra o aguja central en los relojes de sol, la parte que genera la sombra sobre un disco horario circular.",
    "A lo largo del día, el brillante sol proyectaba la inmensa y afilada sombra del obelisco sobre el suelo del patio del templo. Observando con precisión la dirección y la longitud de esa sombra arrastrándose sobre marcas en la arena o la piedra pulida, los sacerdotes sabían con exactitud meridiana qué hora era del día. Y eso no era todo; marcando qué día la sombra del mediodía era la más larga o la más corta del año, calculaban las fechas exactas de los solsticios de invierno y verano, manteniendo la sociedad agrícola fluyendo en perfecta sincronía."
  ],
  "egypt_m13": [
    "¿Alguna vez te has quejado de que un año entero es demasiado largo? ¡Imagina vivir en una época en que nadie sabía realmente cuántos días duraba un año! En el resto de las civilizaciones primitivas, usaban calendarios lunares basados en las fases de la luna. Eran confusos, asimétricos, y requerían que sacerdotes agregaran días falsos y semanas caóticas para que los meses de nieve o cosecha no terminaran desfasándose a largo plazo. Pero Egipto necesitaba orden matemático absoluto para que el río Nilo no los sorprendiera.",
    "Gracias a sus brillantes astrónomos, los egipcios inventaron algo revolucionario: el primer calendario civil basado directamente en el ciclo real del Sol de la historia humana. Decidieron con valentía que el año civil duraría 365 días en total. Lo diseñaron dividiéndolo en exactamente 12 meses perfectos, y a cada mes le asignaron exactamente 30 días, resultando en 360 días base. Un sistema matemáticamente perfecto y sencillo de calcular.",
    "Pero claro, los matemáticos sabían que el viaje anual de la Tierra alrededor del Sol tomaba cerca de 365.25 días. Así que... ¿qué hacer con esos 5 días faltantes para ajustar la mecánica celeste a su geometría? Inventaron los legendarios 'Días Epagómenos'. Agregaron 5 misteriosos días extras justo al final del año, creando una especie de mes vacacional corto. Mitológicamente explicaban que eran los días en los que el dios de la Tierra (Geb) y la diosa del Cielo (Nut) habían dado a luz a sus cinco hijos divinos: Osiris, Horus el Mayor, Seth, Isis y Neftis. El calendario de tu celular moderno existe únicamente porque hace miles de años, a un lado del río Nilo, calcularon por primera vez nuestro viaje alrededor de una estrella."
  ],
  "egypt_m14": [
    "Aunque los cielos en Egipto casi siempre estaban despejados y el sol brillaba incesante, en raras y aterradoras ocasiones, algo catastrófico sacudía al imperio en pleno día. Sin previo aviso (al menos para el pueblo común), a la mitad del mediodía, el viento se volvía helado, el disco dorado del sol empezaba a ser comido por una mordida de sombra negra, y en pocos minutos, una noche antinatural cubría la Tierra mientras los animales enloquecían.",
    "Nosotros entendemos que esto es un Eclipse Solar, provocado simplemente por la luna bloqueando temporalmente la luz del sol. Pero para los sacerdotes egipcios, este evento astronómico inusual no era solo un fenómeno orbital. Era el terror personificado, la máxima amenaza existencial del universo. Creían que Apofis, la inmensa y malévola serpiente del caos del inframundo, finalmente había emboscado y devorado al dios sol Ra y a su barca estelar en medio del cielo diurno.",
    "En los templos, cundía el pánico organizado. Para 'salvar' al universo, los astrónomos -que en realidad usaban cálculos matemáticos empíricos para predecir cuándo vendría la mordida oscura- convocaban ritos sagrados masivos. La multitud cantaba, gritaba, y golpeaba imágenes y estatuas de serpientes con bastones y magia para atacar al demonio invisible y obligarlo a vomitar la luz del sol. Tras unos minutos de batalla cósmica aparente, la luz del sol regresaba, coronando a la astronomía sacerdotal como la salvadora del mundo. Como guiño poético a este mito, en el año 2004, la agencia espacial de la NASA descubrió un asteroide gigante cruzando muy cerca de la Tierra... ¡y lo bautizaron con el nombre de 'Apophis'!"
  ],
  "egypt_m15": [
    "Por milenios, los brillantes astrónomos de Kemet alzaron sus cuellos hacia arriba para estudiar los misterios brillantes entre el polvo de las estrellas oscuras. Hoy en día, miles de años después, nosotros somos quienes estamos orbitando entre esas mismas estrellas, pero mirando hacia abajo, estudiando a Egipto desde el abismo silencioso del espacio. Hemos pasado de la astronomía en el desierto, a la Arqueología Satelital, creando una alianza cósmica para desenterrar a los faraones.",
    "Nuestros satélites modernos orbitando la Tierra, equipados con súper cámaras infrarrojas potentes patrocinadas por la NASA o la ESA (Agencia Espacial Europea), bombardean el desierto del Sahara y captan firmas de energía calórica. ¿El secreto? Debajo de metros y metros de dunas y arena, hay ruinas, bloques gigantescos de piedra tallada y ladrillos de lodo secos. La arena absorbe calor y humedad a una velocidad y temperatura diferente que los muros densos de piedra sumergidos bajo ella.",
    "Gracias a estas diferencias térmicas invisibles para los ojos humanos, pero que los satélites en órbita interpretan, las supercomputadoras dibujan mapas perfectos mostrando formas geométricas (cuadrados, túneles, grandes avenidas y ciudadelas enteras) flotando como fantasmas sobre una pantalla negra. En los últimos veinte años, los 'Telescopios Espaciales de Piedra' han encontrado más de 17 pirámides desconocidas y más de 3,000 asentamientos humanos enterrados en las dunas de Egipto. ¡Los satélites de hoy son los verdaderos ojos de Horus cruzando el espacio infinito!"
  ]
};

const updatedData = COURSE_DATA.map(mod => {
  if (mod.id && mod.id.startsWith('egypt_m') && mod.contentEs && mod.contentEs.sections) {
    
    // Replace text with EXPANDED_TEXTS
    if(EXPANDED_TEXTS[mod.id]) {
        mod.contentEs.sections[0].text = EXPANDED_TEXTS[mod.id];
    }
  }
  return mod;
});

const newFileContent = `export const COURSE_DATA = ${JSON.stringify(updatedData, null, 2)};\n`;
fs.writeFileSync('lib/courseData.js', newFileContent, 'utf8');
console.log('Fixed courseData.js content expansion');
