const fs = require('fs');
const raw = fs.readFileSync('lib/courseData.js', 'utf8');
const prefix = raw.split('export const COURSE_DATA = ')[0];
const dataStr = raw.split('export const COURSE_DATA = ')[1].replace(/;\s*$/, '');
const COURSE_DATA = eval('(' + dataStr + ')');

const ADD = {
  saturn: [
    { title:"El Interior de Saturno: El Planeta Flotante", text:"Saturno es el único planeta del Sistema Solar menos denso que el agua: si existiera un océano suficientemente grande, ¡flotaría! Esto ocurre porque Saturno es principalmente hidrógeno y helio, los elementos más ligeros del universo. Como Júpiter, tiene capas de hidrógeno gaseoso, líquido y metálico. En su centro hay un núcleo rocoso y helado de unas 10-15 veces la masa de la Tierra.", image:"/assets/planet_saturn.png", imgCaption:"Saturno fotografiado por la sonda Cassini de NASA/ESA. Sería el único planeta del Sistema Solar capaz de flotar en el agua. Fuente: NASA/JPL" },
    { title:"El Campo Magnético de Saturno: El Alineado Perfecto", text:"Saturno tiene un campo magnético 578 veces más fuerte que el de la Tierra. Lo que hace único a Saturno es que su campo magnético está casi perfectamente alineado con su eje de rotación, a diferencia de los campos magnéticos de todos los demás planetas que están inclinados. Esto confunde a los científicos, pues los modelos físicos predicen que un campo magnético así no debería poder mantenerse estable.", image:"/assets/planet_saturn.png", imgCaption:"El campo magnético de Saturno, medido por la sonda Cassini, es casi perfectamente simétrico respecto a su eje. Fuente: NASA/JPL" },
    { title:"Los Anillos de Saturno: La Joya del Sistema Solar", text:"Los anillos de Saturno se extienden hasta 282,000 km desde el centro del planeta pero tienen solo 10 a 100 metros de grosor. Están formados principalmente por agua helada y algo de polvo y roca. La sonda Cassini descubrió que los anillos son relativamente jóvenes (100-400 millones de años) y que lentamente están cayendo hacia el planeta. En unos 100 millones de años, los anillos habrán desaparecido.", image:"/assets/planet_saturn.png", imgCaption:"Los anillos de Saturno, compuestos principalmente de hielo de agua, fotografiados por la sonda Cassini de NASA. Fuente: NASA/JPL-Caltech" },
    { title:"Titán: La Luna con Océanos de Metano", text:"Titán, la luna más grande de Saturno, es el único cuerpo del Sistema Solar (aparte de la Tierra) con líquidos estables en su superficie. Pero no es agua: son lagos y ríos de metano y etano líquidos a -179°C. Tiene una atmósfera densa de nitrógeno con nubes anaranjadas. La misión Dragonfly de NASA enviará un helicóptero nuclear a Titán en 2028 para estudiar su química.", image:"/assets/saturn_titan_landscape.png", imgCaption:"Recreación artística del paisaje de Titán con sus lagos de metano y la atmósfera naranja. Fuente: NASA/JPL" },
    { title:"Encélado: Géiseres de Agua en el Espacio", text:"Encélado es una pequeña luna de Saturno que esconde un océano bajo su cáscara de hielo. En su polo sur hay géiseres que expulsan agua al espacio a 1,400 km/h. Esta agua forma el anillo E de Saturno. Lo más emocionante: en el agua eyectada la sonda Cassini detectó hidrógeno molecular (señal de actividad hidrotermal) y moléculas orgánicas complejas, ingredientes posibles para la vida.", image:"/assets/planet_saturn.png", imgCaption:"Géiseres de vapor de agua en el polo sur de Encélado, fotografiados por la sonda Cassini. Fuente: NASA/JPL-Caltech/SSI" },
    { title:"La Sonda Cassini: 13 Años en Saturno", text:"La misión Cassini-Huygens (NASA/ESA/ASI) orbitó Saturno de 2004 a 2017: 13 años de descubrimientos revolucionarios. Lanzó la sonda Huygens que aterrizó en Titán en 2005, la primera vez que una nave aterrizó en el Sistema Solar externo. Cassini completó 293 órbitas a Saturno, hizo 162 sobrevuelos de lunas y al final se hundió en la atmósfera del planeta para no contaminar sus lunas.", image:"/assets/planet_saturn.png", imgCaption:"La sonda Cassini de NASA/ESA realizó 293 órbitas alrededor de Saturno en 13 años de misión. Fuente: NASA/JPL" },
    { title:"Las Lunas de Saturno: Un Museo Lunar", text:"Saturno tiene 146 lunas confirmadas, el mayor número del Sistema Solar. Incluyen desde Titán (más grande que Mercurio) hasta lunas menores de apenas un kilómetro. Mimas tiene un cráter gigante que lo hace parecer la Estrella de la Muerte de Star Wars. Hyperion tiene la forma de una esponja y Janus comparte su órbita con otra luna llamada Epimeteo, intercambiando órbitas cada 4 años.", image:"/assets/saturn_titan_landscape.png", imgCaption:"Mosaico de lunas de Saturno, incluyendo Titán, Encélado, Mimas, Dione y Tetis. Fuente: NASA/JPL-Caltech/SSI" },
    { title:"Las Tormentas de Saturno: El Gran Punto Blanco", text:"Saturno tiene tormentas periódicas llamadas 'Grandes Manchas Blancas' que ocurren aproximadamente cada 30 años. La tormenta de 2010 fue capturada por Cassini: comenzó pequeña pero creció hasta rodear todo el planeta en cuestión de meses, con vientos de 480 km/h. También se descubrió una tormenta hexagonal permanente en el polo norte, una estructura geométrica única en el Sistema Solar.", image:"/assets/planet_saturn.png", imgCaption:"La tormenta hexagonal del polo norte de Saturno, una estructura única en el Sistema Solar. Fuente: NASA/JPL-Caltech/SSI" },
    { title:"El Futuro de los Anillos y la Misión Dragonfly", text:"Los anillos de Saturno están desapareciendo: la gravedad y el viento solar los erosionan a razón de 10,000 kg de material por segundo. En unos 100 millones de años habrán desaparecido. Mientras tanto, NASA prepara la misión Dragonfly (lanzamiento 2028) que enviará un helicóptero de propulsión nuclear a Titán. Volará cientos de kilómetros explorando sitios de interés astrobiológico.", image:"/assets/saturn_titan_landscape.png", imgCaption:"Representación artística del helicóptero Dragonfly de NASA explorando la superficie de Titán. Fuente: NASA/Johns Hopkins APL" }
  ],
  uranus: [
    { title:"El Interior de Urano: El Planeta de Hielo", text:"Urano es un 'gigante de hielo', diferente a Júpiter y Saturno que son 'gigantes de gas'. Su interior está compuesto principalmente de una mezcla densa y caliente de agua, metano y amoníaco en estado de hielo a alta presión. Sobre este manto helado hay una pequeña envoltura de hidrógeno y helio. En el centro podría haber un núcleo rocoso. Urano emite poco calor interno, a diferencia de los otros gigantes.", image:"/assets/planet_uranus.png", imgCaption:"Estructura interna de Urano: manto de hielo de agua, metano y amoníaco sobre un núcleo rocoso. Fuente: NASA" },
    { title:"El Campo Magnético Peculiar de Urano", text:"El campo magnético de Urano es extrañísimo: está inclinado 59° respecto a su eje de rotación y desplazado del centro del planeta. Esto hace que el campo sea altamente irregular y que las auroras en Urano aparezcan en lugares inesperados. Los científicos creen que la estructura del manto helado de Urano genera el campo de manera diferente a la de otros planetas.", image:"/assets/uranus_rings.png", imgCaption:"La magnetosfera de Urano es asimétrica e irregular debido a la inclinación y desplazamiento de su campo magnético. Fuente: NASA/JPL" },
    { title:"Las Lunas de Urano: Nombradas por Shakespeare", text:"Urano tiene 27 lunas conocidas, todas nombradas con personajes de las obras de Shakespeare y de Alexander Pope (Ariel, Umbriel, Titania, Oberón, Miranda, Puck, etc.). Miranda es la más interesante: tiene un acantilado llamado Verona Rupes de 20 km de altura, el más alto conocido del Sistema Solar. Desde su cima, una caída libre tomaría 12 minutos.", image:"/assets/planet_uranus.png", imgCaption:"Las principales lunas de Urano, fotografiadas durante el sobrevuelo de la sonda Voyager 2 en 1986. Fuente: NASA/JPL" },
    { title:"Los Anillos de Urano: Tenues y Oscuros", text:"Urano tiene 13 anillos conocidos, descubiertos en 1977 cuando el planeta pasó frente a una estrella. Los anillos son oscuros y delgados, muy diferentes a los brillantes anillos de hielo de Saturno. Están compuestos de partículas oscuras, posiblemente hielo recubierto de materia orgánica. Los dos anillos exteriores fueron descubiertos por el Telescopio Hubble en 2005.", image:"/assets/uranus_rings.png", imgCaption:"Los anillos de Urano fotografiados por el Telescopio Espacial Hubble. Son mucho más oscuros que los de Saturno. Fuente: NASA/ESA/Hubble" },
    { title:"La Inclinación Extrema: El Planeta Tumbado", text:"Urano tiene su eje de rotación inclinado 97.77°, lo que significa que rota prácticamente 'de lado'. Se cree que un objeto del tamaño de la Tierra chocó con Urano en la era temprana del Sistema Solar y lo 'tumbó'. Esto tiene consecuencias extraordinarias: cada polo recibe 42 años continuos de luz solar seguidos de 42 años de oscuridad total.", image:"/assets/planet_uranus.png", imgCaption:"El eje de Urano está inclinado 98°, haciendo que el planeta ruede sobre su costado alrededor del Sol. Fuente: NASA/JPL" },
    { title:"Las Estaciones Extremas de Urano", text:"Debido a su inclinación de 98°, las estaciones de Urano son las más extremas del Sistema Solar. Cada estación dura 21 años terrestres. Un polo experimenta verano continuo (sol 24 horas) durante 21 años, seguido de 21 años de invierno total en oscuridad. Durante los equinoccios, Urano tiene un patrón de día/noche similar al de la Tierra, con los polos experimentando condiciones más moderadas.", image:"/assets/uranus_rings.png", imgCaption:"Comparación de Urano en diferentes épocas mostrando cambios atmosféricos relacionados con sus extremas estaciones. Fuente: NASA/ESA/Hubble" },
    { title:"La Sonda Voyager 2: El Único Visitante", text:"Solo una nave espacial ha visitado Urano: la Voyager 2, que hizo un sobrevuelo en enero de 1986. La nave pasó a 81,500 km de las nubes. Descubrió 10 lunas previamente desconocidas, 2 nuevos anillos y estudió la extraña magnetosfera. Después de Urano, Voyager 2 continuó hacia Neptuno. Hoy, Voyager 2 está más allá del Sistema Solar, en el espacio interestelar.", image:"/assets/planet_uranus.png", imgCaption:"La única fotografía cercana de Urano fue tomada por la sonda Voyager 2 de NASA en enero de 1986. Fuente: NASA/JPL" },
    { title:"El Color de Urano: ¿Por qué es Cyan?", text:"El color azul-verdoso de Urano se debe al metano en su atmósfera. El metano absorbe la luz roja y refleja la azul y verde. Aunque Neptuno tiene más metano, Urano parece más verde y Neptuno más azul, algo que los científicos aún no entienden completamente. Hay una capa de gas desconocido que hace a Urano más opaco que Neptuno, modificando cómo percibimos su color.", image:"/assets/uranus_rings.png", imgCaption:"El distintivo color cyan de Urano, causado por el metano en su atmósfera que absorbe la luz roja. Fuente: NASA/ESA" },
    { title:"Futuras Misiones a Urano: Una Prioridad", text:"En 2022, el reporte Decadal Survey de la NASA declaró una misión orbital a Urano como la máxima prioridad de planetología para la próxima década. Una futura misión 'Uranus Orbiter and Probe' enviaría una nave que orbitaría el planeta y soltaría una sonda en su atmósfera. Las lunas de Urano, especialmente Miranda y Ariel, también serán estudiadas en busca de océanos subterráneos.", image:"/assets/planet_uranus.png", imgCaption:"Representación artística de la propuesta misión Uranus Orbiter and Probe, la prioridad máxima de NASA para la próxima década. Fuente: NASA" }
  ],
  neptune: [
    { title:"El Interior de Neptuno: Gemelo Helado de Urano", text:"Neptuno es también un gigante de hielo como Urano. Su interior tiene un núcleo rocoso, un extenso manto de agua, metano y amoníaco en estado de 'hielo caliente' (sólido por la presión pero a 7,000°C) y una envoltura de gas. A diferencia de Urano, Neptuno emite 2.6 veces más calor del que recibe del Sol, lo que sugiere una fuente de calor interna aún no comprendida.", image:"/assets/planet_neptune.png", imgCaption:"Estructura interna de Neptuno similar a Urano pero con mayor generación de calor interno. Fuente: NASA" },
    { title:"El Campo Magnético de Neptuno: Similar al de Urano", text:"El campo magnético de Neptuno, como el de Urano, está muy inclinado respecto a su eje de rotación (47°) y desplazado del centro del planeta. Esto crea auroras en posiciones inesperadas. La Voyager 2 detectó también cuatro cinturones de radiación distintos alrededor de Neptuno. El origen de estos extraños campos magnéticos en los gigantes de hielo sigue siendo un misterio activo.", image:"/assets/neptune_diamond_rain.png", imgCaption:"La magnetosfera de Neptuno, inclinada y desplazada, crea auroras en posiciones inusuales del planeta. Fuente: NASA/JPL" },
    { title:"Tritón: La Luna que Gira al Revés", text:"Tritón, la luna más grande de Neptuno, es única en el Sistema Solar: orbita a Neptuno en sentido contrario a la rotación del planeta (órbita retrógrada). Esto indica que Tritón fue capturado del Cinturón de Kuiper y no se formó junto a Neptuno. Tiene géiseres de nitrógeno activos y una temperatura de -235°C, la más fría registrada en el Sistema Solar. En unos 3,600 millones de años, será destruido por la gravedad de Neptuno.", image:"/assets/neptune_triton.png", imgCaption:"Tritón, la gran luna de Neptuno, con sus géiseres de nitrógeno y superficie de hielo de nitrógeno. Fuente: NASA/JPL/Voyager 2" },
    { title:"Los Vientos Más Veloces del Sistema Solar", text:"Neptuno tiene los vientos más rápidos de todos los planetas: pueden alcanzar 2,100 km/h, más rápidos que el sonido en la Tierra. Esto es sorprendente dado que Neptuno recibe muy poca energía solar (900 veces menos que la Tierra). La fuente de energía que impulsa estos vientos es el calor interno del planeta. Las tormentas de Neptuno pueden ser tan grandes como la Tierra.", image:"/assets/planet_neptune.png", imgCaption:"Las bandas de nubes de Neptuno y la Gran Mancha Oscura, generadas por los vientos más veloces del Sistema Solar. Fuente: NASA/Voyager 2" },
    { title:"La Gran Mancha Oscura: La Tormenta de Neptuno", text:"Cuando la Voyager 2 visitó Neptuno en 1989, descubrió una tormenta enorme llamada la Gran Mancha Oscura, del tamaño de la Tierra, con vientos de 2,100 km/h. Para cuando el Telescopio Hubble la buscó en 1994, había desaparecido. Pero en 1995 apareció una nueva en el hemisferio norte. Las tormentas de Neptuno son pasajeras, a diferencia de la Gran Mancha Roja de Júpiter que lleva siglos.", image:"/assets/neptune_diamond_rain.png", imgCaption:"La Gran Mancha Oscura de Neptuno, una tormenta del tamaño de la Tierra, fotografiada por Voyager 2 en 1989. Fuente: NASA/JPL" },
    { title:"La Lluvia de Diamantes en Neptuno", text:"El interior de Neptuno genera uno de los fenómenos más increíbles del Sistema Solar: lluvia de diamantes. El metano en el interior se somete a temperaturas y presiones extremas que rompen las moléculas de carbono y las comprimen en cristales de diamante, que literalmente caen como lluvia hacia el núcleo. En el laboratorio, científicos han recreado estas condiciones y confirmado que los diamantes se forman.", image:"/assets/neptune_diamond_rain.png", imgCaption:"Representación artística de la lluvia de diamantes en el interior de Neptuno, recreada experimentalmente en laboratorio. Fuente: NASA/SLAC" },
    { title:"El Descubrimiento Matemático de Neptuno", text:"Neptuno fue el primer planeta descubierto mediante predicción matemática, no por observación casual. En 1845, los matemáticos Urbain Le Verrier (Francia) y John Adams (Reino Unido) calcularon independientemente dónde debía estar un planeta desconocido que perturbaba la órbita de Urano. El astrónomo Johann Galle apuntó su telescopio al lugar predicho el 23 de septiembre de 1846, ¡y ahí estaba Neptuno!", image:"/assets/planet_neptune.png", imgCaption:"Neptuno fotografiado por el Telescopio Espacial Hubble. Fue encontrado exactamente donde las matemáticas predicijeron. Fuente: NASA/ESA/Hubble" },
    { title:"La Sonda Voyager 2 en Neptuno: El Viaje Final", text:"Voyager 2 llegó a Neptuno el 25 de agosto de 1989, doce años después de su lanzamiento. Fue la última visita de una nave espacial a Neptuno y la única hasta hoy. En solo 6 horas de sobrevuelo, Voyager 2 descubrió 6 nuevas lunas, 4 anillos y la Gran Mancha Oscura. Después de Neptuno, Voyager 2 salió del Sistema Solar y hoy, a más de 19,000 millones de km, sigue enviando señales débiles a la Tierra.", image:"/assets/planet_neptune.png", imgCaption:"Trayectoria de la sonda Voyager 2 desde su lanzamiento en 1977 hasta su salida del Sistema Solar tras visitar Neptuno. Fuente: NASA/JPL" },
    { title:"Los Anillos de Neptuno: Arcas y Guirnaldas", text:"Neptuno tiene 5 anillos tenues nombrados: Galle, Le Verrier, Lassell, Arago y Adams. El anillo Adams es peculiar porque tiene regiones más densas llamadas 'arcos': Libertad, Igualdad y Fraternidad. Estos arcos se mantienen en su lugar gracias a la gravedad de la luna Galatea. Con el tiempo, los arcos se dispersarán y el anillo se igualará.", image:"/assets/neptune_triton.png", imgCaption:"Los anillos de Neptuno fotografiados por Voyager 2, mostrando los arcos brillantes en el anillo Adams. Fuente: NASA/JPL/Voyager 2" }
  ],
  pluto: [
    { title:"El Interior de Plutón: Un Corazón de Hielo", text:"Plutón tiene un interior más complejo de lo esperado. Su núcleo es probablemente de roca, rodeado de un manto de agua helada. La sonda New Horizons descubrió indicios de un océano subterráneo de agua líquida bajo la famosa región Tombaugh (el corazón). Este océano podría existir porque el calor de la desintegración de elementos radiactivos mantiene el agua sin congelar.", image:"/assets/pluto_tombaugh_regio_2.png", imgCaption:"La región Tombaugh de Plutón, su característica 'corazón', podría estar sobre un océano de agua líquida subterráneo. Fuente: NASA/Johns Hopkins APL/SwRI" },
    { title:"Caronte: La Luna Gigante de Plutón", text:"Caronte, la luna principal de Plutón, es tan grande en relación a Plutón (la mitad de su diámetro) que en realidad forman un sistema doble: ambos orbitan alrededor de un punto en el espacio entre los dos. Caronte tiene 1,212 km de diámetro. Su polo norte tiene una mancha roja oscura llamada 'Mordor Macula', formada por gases de Plutón que migran hacia Caronte y se congelan allí.", image:"/assets/planet_pluto.png", imgCaption:"Caronte, la gran luna de Plutón, fotografiada por New Horizons mostrando la oscura región polar llamada Mordor Macula. Fuente: NASA/Johns Hopkins APL" },
    { title:"El Cinturón de Kuiper: El Hogar de Plutón", text:"Plutón no es un planeta solitario sino el miembro más famoso del Cinturón de Kuiper: una región del Sistema Solar más allá de Neptuno que contiene miles de objetos helados. Hay otros objetos similares o más grandes que Plutón en esta zona: Eris, Makemake, Haumea. Por eso en 2006 la Unión Astronómica Internacional reclasificó a Plutón como 'planeta enano'.", image:"/assets/planet_pluto.png", imgCaption:"El Cinturón de Kuiper, hogar de Plutón y miles de objetos helados más allá de la órbita de Neptuno. Fuente: NASA/ESA" },
    { title:"La Misión New Horizons: El Gran Revelador", text:"New Horizons de NASA fue lanzada en 2006 y llegó a Plutón el 14 de julio de 2015, tras un viaje de 9.5 años y 4,800 millones de km. En solo unas horas de máximo acercamiento reveló que Plutón es geológicamente activo, tiene montañas de hielo de agua de 3,500 m de altura, atmósfera azul y el famoso corazón. Después continuó hacia el Cinturón de Kuiper.", image:"/assets/pluto_tombaugh_regio_2.png", imgCaption:"La nave New Horizons de NASA llegó a Plutón en 2015 revelando un mundo sorprendentemente activo y complejo. Fuente: NASA/Johns Hopkins APL" },
    { title:"La Región Tombaugh: El Corazón de Plutón", text:"La característica más icónica de Plutón es la región Tombaugh, una llanura en forma de corazón de 1,600 km de longitud. La mitad izquierda (Sputnik Planitia) es una llanura de nitrógeno helado sin cráteres, lo que indica que su superficie tiene menos de 10 millones de años: geológicamente joven. El nitrógeno se mueve como un glaciar lentamente.", image:"/assets/pluto_tombaugh_regio_2.png", imgCaption:"La región Tombaugh de Plutón, en forma de corazón, con la llanura de nitrógeno Sputnik Planitia a la izquierda. Fuente: NASA/Johns Hopkins APL/SwRI" },
    { title:"La Atmósfera Fugaz de Plutón", text:"Plutón tiene una atmósfera tenue de nitrógeno, metano y monóxido de carbono. Cuando Plutón se acerca al Sol en su órbita elíptica, el hielo superficial se sublima (pasa de sólido a gas) creando esta atmósfera. Cuando se aleja, la atmósfera colapsa y se congela de nuevo. New Horizons fotografió la atmósfera de Plutón como un halo azul brillante iluminado por el Sol.", image:"/assets/planet_pluto.png", imgCaption:"La atmósfera de Plutón vista en contraluz por New Horizons: capas de neblina azulada de metano y nitrógeno. Fuente: NASA/Johns Hopkins APL/SwRI" },
    { title:"¿Planeta o Planeta Enano? El Gran Debate", text:"Durante 76 años (1930-2006), Plutón fue el noveno planeta del Sistema Solar. En 2006, la Unión Astronómica Internacional creó la categoría 'planeta enano' y reclasificó a Plutón porque no ha limpiado su órbita de otros objetos. Muchos científicos y el público general siguen considerando a Plutón un planeta. El debate es real: algunos investigadores proponen nuevas definiciones que devolverían a Plutón su estatus planetario.", image:"/assets/planet_pluto.png", imgCaption:"Plutón, fotografiado por New Horizons, sigue siendo el objeto más amado del Sistema Solar a pesar de su reclasificación en 2006. Fuente: NASA" },
    { title:"Los Colores de Plutón: Rojo, Azul y Blanco", text:"Plutón tiene una superficie sorprendentemente colorida para un mundo tan frío y lejano. La región Tombaugh es blanca brillante (nitrógeno helado puro). Las regiones más antiguas son marrones y rojizas, coloreadas por tholinas (moléculas orgánicas formadas por la radiación solar sobre metano y nitrógeno). Tiene también montañas azuladas. Esta diversidad de colores indica procesos geológicos activos.", image:"/assets/pluto_tombaugh_regio_2.png", imgCaption:"Plutón en color verdadero mostrando la diversidad de su superficie: blanco, rojo y azul. Fuente: NASA/Johns Hopkins APL/SwRI" },
    { title:"Plutón y sus Cinco Lunas", text:"Además de Caronte, Plutón tiene cuatro lunas pequeñas: Estigia, Nix, Hidra y Cerbero, todas descubiertas entre 2005 y 2012 mediante el Telescopio Espacial Hubble. Nix e Hidra tumban caóticamente mientras orbitan: giran de forma impredecible. Todas fueron probablemente formadas en un gigantesco impacto similar al que creó la Luna de la Tierra, hace unos 4,000 millones de años.", image:"/assets/planet_pluto.png", imgCaption:"El sistema de Plutón con sus cinco lunas: Caronte, Estigia, Nix, Hidra y Cerbero. Fuente: NASA/ESA/Hubble" }
  ]
};

let changed = 0;
COURSE_DATA.forEach(mod => {
  if (ADD[mod.id]) {
    const existing = mod.contentEs.sections || [];
    mod.contentEs.sections = [...existing, ...ADD[mod.id]];
    console.log(mod.id, ': ahora tiene', mod.contentEs.sections.length, 'secciones');
    changed++;
  }
});

const out = prefix + 'export const COURSE_DATA = ' + JSON.stringify(COURSE_DATA, null, 2) + ';';
fs.writeFileSync('lib/courseData.js', out);
console.log('Fase 3 completa:', changed, 'módulos actualizados');
