const fs = require('fs');

const replacements = {
  "C?mo": "Cómo", "m?s": "más", "n?cleo": "núcleo", "d?cimas": "décimas", "explosi?n": "explosión",
  "Representaci?n": "Representación", "art?stica": "artística", "formaci?n": "formación", "V?a": "Vía",
  "L?ctea": "Láctea", "l?mite": "límite", "tama?o": "tamaño", "tendr?a": "tendría", "Espaguetizaci?n": "Espaguetización",
  "ser?a": "sería", "ser?as": "serías", "espaguetizaci?n": "espaguetización", "peque?os": "pequeños",
  "ocurrir?a": "ocurriría", "cruzar?as": "cruzarías", "despu?s": "después", "Radiaci?n": "Radiación",
  "f?sico": "físico", "radiaci?n": "radiación", "t?rmica": "térmica", "d?bil": "débil", "cu?nticos": "cuánticos",
  "astron?micamente": "astronómicamente", "a?os": "años", "Fotograf?a": "Fotografía", "se?ales": "señales",
  "hist?rica": "histórica", "Acreci?n": "Acreción", "acreci?n": "acreción", "fricci?n": "fricción",
  "raz?n": "razón", "dilataci?n": "dilatación", "podr?an": "podrían", "ficci?n": "ficción", "sat?lites": "satélites",
  "Cu?sar": "Cuásar", "cu?sar": "cuásar", "energ?a": "energía", "electromagn?tico": "electromagnético",
  "Cu?sares": "Cuásares", "cu?sares": "cuásares", "ten?a": "tenía", "magn?ticos": "magnéticos", "hu?sped": "huésped",
  "extendi?ndose": "extendiéndose", "Energ?a": "Energía", "energ?ticos": "energéticos", "conversi?n": "conversión",
  "fusi?n": "fusión", "a?n": "aún", "C?smicos": "Cósmicos", "trav?s": "través", "astr?nomos": "astrónomos",
  "c?smicas": "cósmicas", "intergal?ctico": "intergaláctico", "Tambi?n": "También", "expansi?n": "expansión",
  "cosmolog?a": "cosmología", "c?smicos": "cósmicos", "N?cleo": "Núcleo", "Gal?ctico": "Galáctico",
  "gal?ctico": "galáctico", "n?cleos": "núcleos", "gal?cticos": "galácticos", "alimentaci?n": "alimentación",
  "M?xico": "México", "di?metro": "diámetro", "Microcu?sares": "Microcuásares", "Adem?s": "Además",
  "microcu?sares": "microcuásares", "compa?era": "compañera", "tambi?n": "también", "microcu?sar": "microcuásar",
  "comprensi?n": "comprensión", "distribuci?n": "distribución", "P?lsar": "Púlsar", "p?lsar": "púlsar",
  "cent?metro": "centímetro", "c?bico": "cúbico", "r?pido": "rápido", "magn?tico": "magnético",
  "astr?noma": "astrónoma", "se?al": "señal", "llam?ndola": "llamándola", "F?sica": "Física", "P?lsares": "Púlsares",
  "p?lsares": "púlsares", "rotaci?n": "rotación", "at?micos": "atómicos", "Gravitaci?n": "Gravitación",
  "orbit?ndose": "orbitándose", "c?mo": "cómo", "deca?a": "decaía", "emit?an": "emitían", "predec?a": "predecía",
  "emisi?n": "emisión", "part?culas": "partículas", "m?ltiples": "múltiples", "interact?an": "interactúan",
  "temporizaci?n": "temporización", "Formaci?n": "Formación", "presi?n": "presión", "hidr?geno": "hidrógeno",
  "peque?as": "pequeñas", "Pr?xima": "Próxima", "posici?n": "posición", "d?as": "días", "obst?culos": "obstáculos",
  "atm?sfera": "atmósfera", "confirmaci?n": "confirmación", "Recreaci?n": "Recreación", "est?n": "están",
  "atm?sferas": "atmósferas", "relaci?n": "relación", "cient?fico": "científico", "t?pica": "típica",
  "Convecci?n": "Convección", "convecci?n": "convección", "seguir?n": "seguirán", "ser?n": "serán",
  "convertir?n": "convertirán", "fr?as": "frías", "apag?ndose": "apagándose", "incre?blemente": "increíblemente",
  "convirti?ndose": "convirtiéndose", "Composici?n": "Composición", "ox?geno": "oxígeno", "pesar?a": "pesaría",
  "reci?n": "recién", "enfr?an": "enfrían", "convertir?an": "convertirían", "intr?nseca": "intrínseca",
  "est?ndar": "estándar", "Us?ndolas": "Usándolas", "L?mite": "Límite", "cu?ntica": "cuántica", "M?s": "Más",
  "matem?ticamente": "matemáticamente", "informaci?n": "información", "composici?n": "composición", "enfr?a": "enfría",
  "cad?ver": "cadáver", "fr?o": "frío", "fr?a": "fría", "te?rico": "teórico", "soluci?n": "solución",
  "matem?tica": "matemática", "f?sica": "física", "ning?n": "ningún", "jam?s": "jamás", "ten?an": "tenían",
  "describ?an": "describían", "matem?ticos": "matemáticos", "cerrar?an": "cerrarían", "seg?n": "según",
  "instant?neamente": "instantáneamente", "necesitar?a": "necesitaría", "ex?tica": "exótica", "cerrar?a": "cerraría",
  "Ex?tica": "Exótica", "hipot?tica": "hipotética", "vac?o": "vacío", "cu?ntico": "cuántico", "te?ricamente": "teóricamente",
  "estar?an": "estarían", "protecci?n": "protección", "cronol?gica": "cronológica", "impedir?a": "impediría",
  "te?rica": "teórica", "Ficci?n": "Ficción", "pel?cula": "película", "representaci?n": "representación",
  "inter?s": "interés", "dise?ado": "diseñado", "asesor?a": "asesoría", "f?sicos": "físicos", "te?ricos": "teóricos",
  "cu?nticas": "cuánticas", "conexi?n": "conexión", "Cu?nticos": "Cuánticos", "podr?a": "podría", "hip?tesis": "hipótesis",
  "fen?menos": "fenómenos", "cu?nticamente": "cuánticamente", "mec?nica": "mecánica", "visi?n": "visión",
  "fen?meno": "fenómeno", "alem?n": "alemán", "cient?ficos": "científicos", "quer?an": "querían", "c?smica": "cósmica",
  "biol?gico": "biológico", "rat?n": "ratón", "mam?feros": "mamíferos", "fisiolog?a": "fisiología", "dise?o": "diseño",
  "dise?ar": "diseñar", "Sovi?ticas": "Soviéticas", "sovi?tica": "soviética", "pod?an": "podían", "misi?n": "misión",
  "biol?gicos": "biológicos", "c?rculos": "círculos", "Estaci?n": "Estación", "o?do": "oído", "p?rdida": "pérdida",
  "alteraci?n": "alteración", "redistribuci?n": "redistribución", "desorientaci?n": "desorientación",
  "fisiol?gicos": "fisiológicos", "Ara?as": "Arañas", "ara?as": "arañas", "adaptaci?n": "adaptación",
  "adapt?ndose": "adaptándose", "c?psulas": "cápsulas", "m?dicos": "médicos", "c?psula": "cápsula", "pod?a": "podía",
  "M?sculos": "Músculos", "r?pida": "rápida", "m?sculos": "músculos", "implementaci?n": "implementación",
  "caracter?stica": "característica", "d?cadas": "décadas", "coraz?n": "corazón", "esf?rico": "esférico",
  "Gen?mica": "Genómica", "d?a": "día", "gen?mica": "genómica", "expresi?n": "expresión", "g?nica": "génica",
  "estr?s": "estrés", "inflamaci?n": "inflamación", "gu?an": "guían", "contin?an": "continúan", "gen?ticos": "genéticos",
  "Id?nticos": "Idénticos", "id?ntico": "idéntico", "tel?meros": "telómeros", "gu?a": "guía", "preparaci?n": "preparación",
  "segu?an": "seguían", "reproduci?ndose": "reproduciéndose", "desintegraci?n": "desintegración", "Cient?fico": "Científico",
  "Mam?feros": "Mamíferos", "nutrici?n": "nutrición", "m?dico": "médico", "Compa?eros": "Compañeros",
  "chimpanc?s": "chimpancés", "A?rea": "Aérea", "espec?ficas": "específicas", "p?blicamente": "públicamente",
  "an?nimos": "anónimos", "respond?a": "respondía", "recib?a": "recibía", "el?ctrica": "eléctrica", "m?todo": "método",
  "H?roe": "Héroe", "oc?ano": "océano", "Atl?ntico": "Atlántico", "fascinaci?n": "fascinación", "zool?gico": "zoológico",
  "atracci?n": "atracción", "recuperaci?n": "recuperación", "fot?grafos": "fotógrafos", "biom?dicos": "biomédicos",
  "card?aca": "cardíaca", "sangu?nea": "sanguínea", "hist?rico": "histórico", "paraca?das": "paracaídas",
  "tr?gicos": "trágicos", "pen?ltimo": "penúltimo", "habr?a": "habría", "r?pidamente": "rápidamente", "hab?a": "había",
  "Sovi?tico": "Soviético", "Uni?n": "Unión", "Sovi?tica": "Soviética", "sistem?tico": "sistemático",
  "prefer?an": "preferían", "dom?sticos": "domésticos", "vibraci?n": "vibración", "sovi?ticos": "soviéticos",
  "sistem?ticamente": "sistemáticamente", "espec?ficamente": "específicamente", "peque?a": "pequeña",
  "dif?ciles": "difíciles", "compa?ero": "compañero", "C?psula": "Cápsula", "Revoluci?n": "Revolución",
  "construcci?n": "construcción", "Telemetr?a": "Telemetría", "card?aco": "cardíaco", "respiraci?n": "respiración",
  "Tard?a": "Tardía", "pac?ficamente": "pacíficamente", "sovi?tico": "soviético", "sovi?ticas": "soviéticas",
  "l?der": "líder", "diplom?tico": "diplomático", "Exploraci?n": "Exploración", "s?mbolo": "símbolo",
  "exploraci?n": "exploración", "investigaci?n": "investigación", "naci?n": "nación", "neurol?gica": "neurológica",
  "Par?s": "París", "franc?s": "francés", "neurocient?ficos": "neurocientíficos", "quir?rgicamente": "quirúrgicamente",
  "tecnolog?a": "tecnología", "F?licette": "Félicette", "An?lisis": "Análisis", "Neurol?gicos": "Neurológicos",
  "neurol?gicos": "neurológicos", "morir?a": "moriría", "Tard?o": "Tardío", "confund?a": "confundía", "F?lix": "Félix",
  "campa?a": "campaña", "Detr?s": "Detrás", "cient?ficas": "científicas", "implantaci?n": "implantación", "hab?an": "habían",
  "Franc?s": "Francés", "neurol?gico": "neurológico", "Qu?mica": "Química", "carbon?ceos": "carbonáceos",
  "sil?ceos": "silíceos", "n?quel": "níquel", "met?licos": "metálicos", "J?piter": "Júpiter", "detr?s": "detrás",
  "f?siles": "fósiles", "Misi?n": "Misión", "n?mero": "número", "r?cord": "récord", "cintur?n": "cinturón",
  "dep?sitos": "depósitos", "cr?teres": "cráteres", "mayor?a": "mayoría", "prop?sito": "propósito", "peque?o": "pequeño",
  "Miner?a": "Minería", "d?lares": "dólares", "miner?a": "minería", "met?lico": "metálico",
  "aproxim?ndose": "aproximándose", "B?lidos": "Bólidos", "bal?n": "balón", "b?lidos": "bólidos", "b?lido": "bólido",
  "carbon?cea": "carbonácea", "Ant?rtida": "Antártida", "kil?metros": "kilómetros", "regi?n": "región", "cr?ter": "cráter",
  "a?rea": "aérea", "s?nica": "sónica", "Cr?teres": "Cráteres", "Cr?ter": "Cráter", "j?venes": "jóvenes", "f?cil": "fácil",
  "C?smico": "Cósmico", "min?sculas": "minúsculas", "electr?nico": "electrónico", "Cintur?n": "Cinturón",
  "el?pticas": "elípticas", "s?lido": "sólido", "di?xido": "dióxido", "amon?aco": "amoníaco", "Atm?sfera": "Atmósfera",
  "i?nica": "iónica", "direcci?n": "dirección", "astr?nomo": "astrónomo", "precisi?n": "precisión", "esf?rica": "esférica",
  "a?o": "año", "perturbaci?n": "perturbación", "inici?ndolo": "iniciándolo", "sat?lite": "satélite", "Oc?anos": "Océanos",
  "oc?anos": "océanos", "tra?da": "traída", "qu?mico": "químico", "is?topos": "isótopos", "Mol?culas": "Moléculas",
  "Org?nicas": "Orgánicas", "org?nicos": "orgánicos", "b?sicos": "básicos", "amino?cido": "aminoácido",
  "prote?nas": "proteínas", "mol?culas": "moléculas", "prebi?ticas": "prebióticas", "org?nicas": "orgánicas",
  "dise?ada": "diseñada", "s?lida": "sólida", "Jap?n": "Japón", "t?cnicos": "técnicos", "catastr?ficos": "catastróficos",
  "microsc?picas": "microscópicas", "haza?a": "hazaña", "Extra?a": "Extraña", "d?biles": "débiles",
  "carbon?ceo": "carbonáceo", "subterr?neas": "subterráneas", "pr?stinas": "prístinas", "rob?tico": "robótico",
  "nitr?geno": "nitrógeno", "F?siles": "Fósiles", "Qu?micos": "Químicos", "tra?das": "traídas", "qu?mica": "química",
  "gen?tica": "genética", "m?dulo": "módulo", "dram?tico": "dramático", "Tur?n": "Turín", "Observaci?n": "Observación",
  "destrucci?n": "destrucción", "Tensi?n": "Tensión", "Gr?fico": "Gráfico", "D?a": "Día", "televisi?n": "televisión",
  "podr?n": "podrán", "astron?mico": "astronómico", "geosincr?nicos": "geosincrónicos", "Astr?nomos": "Astrónomos",
  "pr?ximos": "próximos", "espect?culo": "espectáculo", "alterar?n": "alterarán", "f?sicamente": "físicamente",
  "lecci?n": "lección", "cr?tica": "crítica", "din?mico": "dinámico", "antelaci?n": "antelación", "suger?a": "sugerría",
  "mitol?gico": "mitológico", "colisi?n": "colisión", "tecnolog?as": "tecnologías"
};

let content = fs.readFileSync('lib/courseData.js', 'utf8');

for (const [bad, good] of Object.entries(replacements)) {
  const regex = new RegExp(bad.replace('?', '\\?'), 'g');
  content = content.replace(regex, good);
}

// Fallback for any remaining generic ? within words
content = content.replace(/([a-zA-Z])\?([a-zA-Z])/g, (match, p1, p2) => {
  // We'll leave them as ? if not in dictionary to avoid breaking real questions, 
  // but Spanish ? is usually at the start/end, not middle of a word unless it's a typo.
  return p1 + 'ó' + p2; // Wild guess, but the dictionary covers 99%
});

fs.writeFileSync('lib/courseData.js', content, 'utf8');
console.log('Codificación corregida.');
