// Auto-generated lightweight course catalog — DO NOT EDIT
// Generated from courseData.js, contains only metadata for navigation
// Generated at: 2026-07-11T17:01:50.012Z
// Total modules: 153
export const COURSE_CATALOG = [
  {
    "id": "egypt_m1",
    "order": 1001,
    "titleEn": "Nabta Playa",
    "titleEs": "Nabta Playa: El Primer Observatorio",
    "badge": "Keeper of the Stones",
    "badgeEs": "Guardián de las Piedras",
    "badgeIcon": "/assets/egypt/m1_nabta_playa.png",
    "color": "#D4A843",
    "icon": "/assets/egypt/m1_nabta_playa.png"
  },
  {
    "id": "egypt_m5",
    "order": 1005,
    "titleEn": "The Laser of Giza",
    "titleEs": "El Láser de Giza",
    "badge": "Builder of Alignment",
    "badgeEs": "Constructor Estelar",
    "badgeIcon": "/assets/egypt/m5_giza.png",
    "color": "#F0A500",
    "icon": "/assets/egypt/m5_giza.png"
  },
  {
    "id": "egypt_m6",
    "order": 1006,
    "titleEn": "Map of the Universe",
    "titleEs": "Mapa del Universo: La Tumba de Senenmut",
    "badge": "Stellar Cartographer",
    "badgeEs": "Cartógrafo Estelar",
    "badgeIcon": "/assets/egypt/m6_senenmut.png",
    "color": "#9B6BFF",
    "icon": "/assets/egypt/m6_senenmut.png"
  },
  {
    "id": "egypt_m8",
    "order": 1008,
    "titleEn": "Abu Simbel",
    "titleEs": "Abu Simbel y la Luz del Solsticio",
    "badge": "Ray of Ramses",
    "badgeEs": "Rayo de Ramsés",
    "badgeIcon": "/assets/egypt/m8_abu_simbel.png",
    "color": "#FF9A3C",
    "icon": "/assets/egypt/m8_abu_simbel.png"
  },
  {
    "id": "egypt_m9",
    "order": 1009,
    "titleEn": "Dendera Zodiac",
    "titleEs": "Zodiaco de Dendera",
    "badge": "Master Astrologer",
    "badgeEs": "Astrólogo Maestro",
    "badgeIcon": "/assets/egypt/m9_dendera.png",
    "color": "#D46A6A",
    "icon": "/assets/egypt/m9_dendera.png"
  },
  {
    "id": "egypt_m10",
    "order": 1010,
    "titleEn": "Space Dagger",
    "titleEs": "Daga Espacial de Tutankamón",
    "badge": "Meteor Blacksmith",
    "badgeEs": "Herrero de Meteoritos",
    "badgeIcon": "/assets/egypt/m10_daga.png",
    "color": "#B0C4DE",
    "icon": "/assets/egypt/m10_daga.png"
  },
  {
    "id": "egypt_m11",
    "order": 1011,
    "titleEn": "Nut's Nile",
    "titleEs": "El Nilo de Nut: La Vía Láctea",
    "badge": "Galactic Navigator",
    "badgeEs": "Navegante Galáctico",
    "badgeIcon": "/assets/egypt/m11_via_lactea.png",
    "color": "#9DD4F0",
    "icon": "/assets/egypt/m11_via_lactea.png"
  },
  {
    "id": "egypt_m12",
    "order": 1012,
    "titleEn": "Obelisks",
    "titleEs": "Obeliscos: Relojes del Sol",
    "badge": "Sun Catcher",
    "badgeEs": "Atrapasol",
    "badgeIcon": "/assets/egypt/m12_obelisco.png",
    "color": "#E8C96A",
    "icon": "/assets/egypt/m12_obelisco.png"
  },
  {
    "id": "egypt_m13",
    "order": 1013,
    "titleEn": "365 Days",
    "titleEs": "365 Días: El Calendario Civil",
    "badge": "Time Keeper",
    "badgeEs": "El Guardián de los Ciclos",
    "badgeIcon": "/assets/egypt/m13_calendario.png",
    "color": "#80D080",
    "icon": "/assets/egypt/m13_calendario.png"
  },
  {
    "id": "egypt_m14",
    "order": 1014,
    "titleEn": "Apophis",
    "titleEs": "Apofis y el Devorador de Soles",
    "badge": "Eclipse Survivor",
    "badgeEs": "Vencedor de las Sombras",
    "badgeIcon": "/assets/egypt/m14_apofis.png",
    "color": "#FF5252",
    "icon": "/assets/egypt/m14_apofis.png"
  },
  {
    "id": "sun",
    "order": 0,
    "titleEn": "The Sun",
    "titleEs": "El Sol",
    "badge": "Solar Pioneer",
    "badgeEs": "Pionero Estelar",
    "color": "#FFD700"
  },
  {
    "id": "mercury",
    "order": 1,
    "titleEn": "Mercury",
    "titleEs": "Mercurio",
    "badge": "Speed Demon",
    "badgeEs": "Demonio Veloz",
    "color": "#8C8C8C"
  },
  {
    "id": "venus",
    "order": 2,
    "titleEn": "Venus",
    "titleEs": "Venus",
    "badge": "Volcano Voyager",
    "badgeEs": "Viajero Volcánico",
    "color": "#E1A95F"
  },
  {
    "id": "earth",
    "order": 3,
    "titleEn": "Earth",
    "titleEs": "Tierra",
    "badge": "Home Hero",
    "badgeEs": "Héroe del Hogar",
    "color": "#2A82D7"
  },
  {
    "id": "mars",
    "order": 4,
    "titleEn": "Mars",
    "titleEs": "Marte",
    "badge": "Red Ranger",
    "badgeEs": "Ranger Rojo",
    "color": "#E25A3D"
  },
  {
    "id": "jupiter",
    "order": 5,
    "titleEn": "Jupiter",
    "titleEs": "Júpiter",
    "badge": "Giant Guardian",
    "badgeEs": "Guardián Gigante",
    "color": "#D29A6A"
  },
  {
    "id": "saturn",
    "order": 6,
    "titleEn": "Saturn",
    "titleEs": "Saturno",
    "badge": "Ring Master",
    "badgeEs": "Maestro de los Anillos",
    "color": "#E8D08D"
  },
  {
    "id": "uranus",
    "order": 7,
    "titleEn": "Uranus",
    "titleEs": "Urano",
    "badge": "Ice Rebel",
    "badgeEs": "Rebelde Helado",
    "color": "#66C6DF"
  },
  {
    "id": "neptune",
    "order": 8,
    "titleEn": "Neptune",
    "titleEs": "Neptuno",
    "badge": "Storm Chaser",
    "badgeEs": "Cazador de Tormentas",
    "color": "#3258A6"
  },
  {
    "id": "pluto",
    "order": 9,
    "titleEn": "Pluto",
    "titleEs": "Plutón",
    "badge": "Dwarf Star",
    "badgeEs": "Estrella Enana",
    "color": "#D1A3B4"
  },
  {
    "id": "black_hole",
    "order": 10,
    "titleEn": "Black Hole",
    "titleEs": "Agujero Negro",
    "badge": "Singularity",
    "badgeEs": "Singularidad",
    "color": "#FF6B00"
  },
  {
    "id": "quasar",
    "order": 11,
    "titleEn": "Quasar",
    "titleEs": "Cuásar",
    "badge": "Hyperactive Core",
    "badgeEs": "Faro Cósmico",
    "color": "#00E4FF"
  },
  {
    "id": "pulsar",
    "order": 12,
    "titleEn": "Pulsar",
    "titleEs": "Púlsar",
    "badge": "Neutron Star",
    "badgeEs": "Estrella de Neutrones",
    "color": "#B000FF"
  },
  {
    "id": "red_dwarf",
    "order": 13,
    "titleEn": "Red Dwarf",
    "titleEs": "Enana Roja",
    "badge": "Stellar Ember",
    "badgeEs": "Ascua Estelar",
    "color": "#FF3B30"
  },
  {
    "id": "white_dwarf",
    "order": 14,
    "titleEn": "White Dwarf",
    "titleEs": "Enana Blanca",
    "badge": "Stellar Ghost",
    "badgeEs": "Fantasma Estelar",
    "color": "#E0F7FA"
  },
  {
    "id": "animales_intro",
    "order": 16,
    "titleEn": "Animals in Space Intro",
    "titleEs": "Animales en el Espacio",
    "badge": "Space Pioneer",
    "badgeEs": "Pionero Espacial",
    "color": "#FFB800"
  },
  {
    "id": "animales_albert_ham",
    "order": 18,
    "titleEn": "Albert and Ham",
    "titleEs": "Simio Albert y Simio Ham",
    "badge": "AstroChimp",
    "badgeEs": "AstroChimp",
    "color": "#FF6B00"
  },
  {
    "id": "animales_laika",
    "order": 19,
    "titleEn": "Laika the Dog",
    "titleEs": "Laika",
    "badge": "Soviet Star",
    "badgeEs": "Heroína Soviética",
    "color": "#D1A3B4"
  },
  {
    "id": "animales_gatos",
    "order": 20,
    "titleEn": "Cats in Space",
    "titleEs": "Gatos en el espacio",
    "badge": "AstroCat",
    "badgeEs": "AstroCat",
    "color": "#3258A6"
  },
  {
    "id": "asteroides_intro",
    "order": 21,
    "titleEn": "Asteroids",
    "titleEs": "Asteroides",
    "badge": "Rock Hopper",
    "badgeEs": "Saltador de Rocas",
    "color": "#9CA3AF"
  },
  {
    "id": "asteroides_meteoros",
    "order": 22,
    "titleEn": "Meteors",
    "titleEs": "Meteoros",
    "badge": "Shooting Star",
    "badgeEs": "Estrella Fugaz",
    "color": "#EF4444"
  },
  {
    "id": "asteroides_cometas",
    "order": 23,
    "titleEn": "Comets",
    "titleEs": "Cometas",
    "badge": "Ice Voyager",
    "badgeEs": "Viajero de Hielo",
    "color": "#60A5FA"
  },
  {
    "id": "asteroides_sondas",
    "order": 24,
    "titleEn": "Space Probes",
    "titleEs": "Sondas",
    "badge": "Deep Explorer",
    "badgeEs": "Explorador Profundo",
    "color": "#34D399"
  },
  {
    "id": "asteroides_apophis",
    "order": 25,
    "titleEn": "Asteroid Apophis",
    "titleEs": "Asteroide Apophis",
    "badge": "Doomsday Watcher",
    "badgeEs": "Vigía del Juicio",
    "color": "#F59E0B"
  },
  {
    "id": "pioneros_yuri",
    "order": 0,
    "titleEn": "Yuri Gagarin",
    "titleEs": "Yuri Gagarin",
    "badge": "Vostok Pioneer",
    "badgeEs": "Pionero Vostok",
    "color": "#ff4d4d"
  },
  {
    "id": "pioneros_alan",
    "order": 1,
    "titleEn": "Alan Shepard",
    "titleEs": "Alan Shepard",
    "badge": "Freedom Pilot",
    "badgeEs": "Piloto Freedom",
    "color": "#3399ff"
  },
  {
    "id": "pioneros_john",
    "order": 2,
    "titleEn": "John Glenn",
    "titleEs": "John Glenn",
    "badge": "Friendship Orbit",
    "badgeEs": "Órbita de la Amistad",
    "color": "#00b300"
  },
  {
    "id": "pioneros_valentina",
    "order": 3,
    "titleEn": "Valentina Tereshkova",
    "titleEs": "Valentina Tereshkova",
    "badge": "Seagull Star",
    "badgeEs": "Estrella Gaviota",
    "color": "#cc00cc"
  },
  {
    "id": "pioneros_leonov",
    "order": 4,
    "titleEn": "Aleksei Leonov",
    "titleEs": "Aleksei Leonov",
    "badge": "Spacewalker",
    "badgeEs": "Caminante Espacial",
    "color": "#ff9900"
  },
  {
    "id": "pioneros_svetlana",
    "order": 5,
    "titleEn": "Svetlana Savitskaya",
    "titleEs": "Svetlana Savitskaya",
    "badge": "Pioneer EVA",
    "badgeEs": "Pionera EVA",
    "color": "#ff3399"
  },
  {
    "id": "pioneros_sally",
    "order": 6,
    "titleEn": "Sally Ride",
    "titleEs": "Sally Ride",
    "badge": "Shuttle Star",
    "badgeEs": "Estrella Transbordador",
    "color": "#00ced1"
  },
  {
    "id": "colisiones_estelares",
    "order": 10,
    "titleEn": "Stellar Collisions",
    "titleEs": "Colisiones Estelares",
    "badge": "Galaxy Crusher",
    "badgeEs": "Colisionador Cósmico",
    "color": "#9933ff"
  },
  {
    "id": "viaje_planetas_rocosos",
    "order": 42,
    "titleEn": "Rocky Planets Journey",
    "titleEs": "Viaje a Planetas Rocosos",
    "badge": "Rocky Pioneer",
    "badgeEs": "Pionero Rocoso",
    "color": "#D2691E"
  },
  {
    "id": "exoplanetas",
    "order": 43,
    "titleEn": "The Exoplanets",
    "titleEs": "Los Exoplanetas",
    "badge": "Exo Hunter",
    "badgeEs": "Cazador Exo",
    "color": "#9370DB"
  },
  {
    "id": "maya_m1",
    "order": 2001,
    "titleEn": "El Caracol",
    "titleEs": "El Caracol: El Observatorio de Venus",
    "badge": "Venus Watcher",
    "badgeEs": "Vigía de Venus",
    "badgeIcon": "/assets/maya/maya_m1.png",
    "color": "#1A5F7A",
    "icon": "/assets/maya/maya_m1.png"
  },
  {
    "id": "maya_m2",
    "order": 2002,
    "titleEn": "El Castillo",
    "titleEs": "Kukulcán: La Serpiente de Luz",
    "badge": "Serpent Master",
    "badgeEs": "Amo de la Serpiente",
    "badgeIcon": "/assets/maya/maya_m2.png",
    "color": "#8E2B2B",
    "icon": "/assets/maya/maya_m2.png"
  },
  {
    "id": "maya_m3",
    "order": 2003,
    "titleEn": "Haab Calendar",
    "titleEs": "El Calendario Haab",
    "badge": "Time Keeper",
    "badgeEs": "Cronometrador",
    "badgeIcon": "/assets/maya/maya_m3.png",
    "color": "#D3882C",
    "icon": "/assets/maya/maya_m3.png"
  },
  {
    "id": "maya_m4",
    "order": 2004,
    "titleEn": "Tzolk'in",
    "titleEs": "El Tzolk'in: Ciclo Sagrado",
    "badge": "Soul Reader",
    "badgeEs": "Lector del Alma",
    "badgeIcon": "/assets/maya/maya_m4.png",
    "color": "#4A90E2",
    "icon": "/assets/maya/maya_m4.png"
  },
  {
    "id": "maya_m5",
    "order": 2005,
    "titleEn": "Calendar Round",
    "titleEs": "La Rueda Calendárica",
    "badge": "Century Wheel",
    "badgeEs": "Rueda de Siglos",
    "badgeIcon": "/assets/maya/maya_m5.png",
    "color": "#E65100",
    "icon": "/assets/maya/maya_m5.png"
  },
  {
    "id": "maya_m6",
    "order": 2006,
    "titleEn": "Temple of Seven Dolls",
    "titleEs": "Templo 7 Muñecas",
    "badge": "Solstice Catcher",
    "badgeEs": "Atrapasolsticios",
    "badgeIcon": "/assets/maya/maya_m6.png",
    "color": "#F1C40F",
    "icon": "/assets/maya/maya_m6.png"
  },
  {
    "id": "maya_m7",
    "order": 2007,
    "titleEn": "Venus (Noh Ek)",
    "titleEs": "Venus: El Planeta Guerrero",
    "badge": "Warrior of Light",
    "badgeEs": "Guerrero de Luz",
    "badgeIcon": "/assets/maya/maya_m7.png",
    "color": "#8E44AD",
    "icon": "/assets/maya/maya_m7.png"
  },
  {
    "id": "maya_m8",
    "order": 2008,
    "titleEn": "Eclipses (Chi'ibal K'iin)",
    "titleEs": "Eclipses: El Sol Devorado",
    "badge": "Eclipse Surviver",
    "badgeEs": "Sobreviviente de Eclipses",
    "badgeIcon": "/assets/maya/maya_m8.png",
    "color": "#111111",
    "icon": "/assets/maya/maya_m8.png"
  },
  {
    "id": "maya_m9",
    "order": 2009,
    "titleEn": "Milky Way (Wakah Chan)",
    "titleEs": "Wakah Chan: El Árbol Cósmico",
    "badge": "Galactic Tree",
    "badgeEs": "Árbol Galáctico",
    "badgeIcon": "/assets/maya/maya_m9.png",
    "color": "#2980B9",
    "icon": "/assets/maya/maya_m9.png"
  },
  {
    "id": "maya_m10",
    "order": 2010,
    "titleEn": "Pleiades (Tzab-ek)",
    "titleEs": "Tzab-ek: La Cola de Serpiente",
    "badge": "Star Snake",
    "badgeEs": "Serpiente Estelar",
    "badgeIcon": "/assets/maya/maya_m10.png",
    "color": "#8E44AD",
    "icon": "/assets/maya/maya_m10.png"
  },
  {
    "id": "maya_m11",
    "order": 2011,
    "titleEn": "Palenque Temple",
    "titleEs": "Palenque y las Inscripciones",
    "badge": "Jungle King",
    "badgeEs": "Rey de la Jungla",
    "badgeIcon": "/assets/maya/maya_m11.png",
    "color": "#27AE60",
    "icon": "/assets/maya/maya_m11.png"
  },
  {
    "id": "maya_m12",
    "order": 2012,
    "titleEn": "Copan Stelae",
    "titleEs": "Copán: Las Estelas Solares",
    "badge": "Stone Carver",
    "badgeEs": "Tallador de Piedra",
    "badgeIcon": "/assets/maya/maya_m12.png",
    "color": "#E74C3C",
    "icon": "/assets/maya/maya_m12.png"
  },
  {
    "id": "maya_m13",
    "order": 2013,
    "titleEn": "Uaxactun Group E",
    "titleEs": "Uaxactún: Grupo E",
    "badge": "Dawn Watcher",
    "badgeEs": "Vigía del Alba",
    "badgeIcon": "/assets/maya/maya_m13.png",
    "color": "#F39C12",
    "icon": "/assets/maya/maya_m13.png"
  },
  {
    "id": "maya_m14",
    "order": 2014,
    "titleEn": "Edzna Cenit",
    "titleEs": "Edzná: Sol en el Cenit",
    "badge": "Zenith Master",
    "badgeEs": "Maestro del Cenit",
    "badgeIcon": "/assets/maya/maya_m14.png",
    "color": "#F39C12",
    "icon": "/assets/maya/maya_m14.png"
  },
  {
    "id": "maya_m15",
    "order": 2015,
    "titleEn": "Dresden Codex",
    "titleEs": "El Códice de Dresde",
    "badge": "Codex Keeper",
    "badgeEs": "Guardián del Códice",
    "badgeIcon": "/assets/maya/maya_m15.png",
    "color": "#1A5F7A",
    "icon": "/assets/maya/maya_m15.png"
  },
  {
    "id": "apollo11_m1",
    "order": 5001,
    "titleEn": "The Saturn V Rocket",
    "titleEs": "El Cohete Saturn V",
    "badge": "Ignition Engineer",
    "badgeEs": "Ingeniero de Ignición",
    "badgeIcon": "/assets/apollo11/badge_ignicion.png",
    "color": "#FF6B35",
    "icon": "/assets/apollo11/m1_launch.png"
  },
  {
    "id": "apollo11_m2",
    "order": 5002,
    "titleEn": "Journey to the Moon",
    "titleEs": "Rumbo a la Luna: 3 Días en el Espacio Profundo",
    "badge": "Deep Space Navigator",
    "badgeEs": "Navegante del Espacio Profundo",
    "badgeIcon": "/assets/apollo11/badge_ignicion.png",
    "color": "#00C2FF",
    "icon": "/assets/apollo11/m2_trajectory.png"
  },
  {
    "id": "apollo11_m3",
    "order": 5003,
    "titleEn": "The Eagle Descends",
    "titleEs": "El Águila Desciende: La Computadora que Salvó la Misión",
    "badge": "Master Pilot",
    "badgeEs": "Piloto Maestro",
    "badgeIcon": "/assets/apollo11/badge_primer_paso.png",
    "color": "#C0E8FF",
    "icon": "/assets/apollo11/m3_eagle.png"
  },
  {
    "id": "apollo11_m4",
    "order": 5004,
    "titleEn": "The First Step",
    "titleEs": "El Primer Paso: Un Momento para la Eternidad",
    "badge": "Moonwalker",
    "badgeEs": "Caminante Lunar",
    "badgeIcon": "/assets/apollo11/badge_primer_paso.png",
    "color": "#F5D020",
    "icon": "/assets/apollo11/m4_moonwalk.png"
  },
  {
    "id": "apollo11_m5",
    "order": 5005,
    "titleEn": "Ascent from the Moon",
    "titleEs": "Ascenso Lunar: El Regreso más Difícil",
    "badge": "Rendezvous Expert",
    "badgeEs": "Experto en Acoplamiento",
    "badgeIcon": "/assets/apollo11/badge_ignicion.png",
    "color": "#A8FF78",
    "icon": "/assets/apollo11/m5_ascent.png"
  },
  {
    "id": "apollo11_m6",
    "order": 5006,
    "titleEn": "Splashdown and Triumph",
    "titleEs": "Amerizaje y Triunfo: El Regreso de los Héroes",
    "badge": "Mission Complete",
    "badgeEs": "Misión Cumplida",
    "badgeIcon": "/assets/apollo11/badge_primer_paso.png",
    "color": "#38B6FF",
    "icon": "/assets/apollo11/m6_splashdown.png"
  },
  {
    "id": "wormhole_m1",
    "order": 4001,
    "titleEn": "Wormhole Section 1",
    "titleEs": "¿Qué es un Puente Einstein-Rosen? (I)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m2",
    "order": 4002,
    "titleEn": "Wormhole Section 2",
    "titleEs": "¿Qué es un Puente Einstein-Rosen? (II)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m3",
    "order": 4003,
    "titleEn": "Wormhole Section 3",
    "titleEs": "La Historia de su Teoría (I)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m4",
    "order": 4004,
    "titleEn": "Wormhole Section 4",
    "titleEs": "La Historia de su Teoría (II)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m5",
    "order": 4005,
    "titleEn": "Wormhole Section 5",
    "titleEs": "Propiedades de los Agujeros de Gusano (I)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m6",
    "order": 4006,
    "titleEn": "Wormhole Section 6",
    "titleEs": "Propiedades de los Agujeros de Gusano (II)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m7",
    "order": 4007,
    "titleEn": "Wormhole Section 7",
    "titleEs": "¿Cómo Funciona un Agujero de Gusano? (I)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m8",
    "order": 4008,
    "titleEn": "Wormhole Section 8",
    "titleEs": "¿Cómo Funciona un Agujero de Gusano? (II)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m9",
    "order": 4009,
    "titleEn": "Wormhole Section 9",
    "titleEs": "¿Qué Pasa si Caigo en un Agujero de Gusano? (I)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m10",
    "order": 4010,
    "titleEn": "Wormhole Section 10",
    "titleEs": "¿Qué Pasa si Caigo en un Agujero de Gusano? (II)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m11",
    "order": 4011,
    "titleEn": "Wormhole Section 11",
    "titleEs": "Últimas Teorías y Experimentos (I)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m12",
    "order": 4012,
    "titleEn": "Wormhole Section 12",
    "titleEs": "Últimas Teorías y Experimentos (II)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m13",
    "order": 4013,
    "titleEn": "Wormhole Section 13",
    "titleEs": "La Paradoja Temporal",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m14",
    "order": 4014,
    "titleEn": "Wormhole Section 14",
    "titleEs": "La Visión de Carl Sagan y 'Contacto' (I)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "wormhole_m15",
    "order": 4015,
    "titleEn": "Wormhole Section 15",
    "titleEs": "La Visión de Carl Sagan y 'Contacto' (II)",
    "badge": "Spacetime Traveler",
    "badgeEs": "Viajero Cuántico",
    "badgeIcon": "/assets/badges/gusano_badge.png",
    "color": "#00FFCC",
    "icon": "/assets/badges/gusano_badge.png"
  },
  {
    "id": "interstellar_m1",
    "order": 5001,
    "titleEn": "Einstein and the Invisible Web",
    "titleEs": "Einstein y la Red Invisible",
    "badge": "Space-Time Navigator",
    "badgeEs": "Navegante del Espaciotiempo",
    "badgeIcon": "/assets/interstellar/m1.png",
    "color": "#00E4FF",
    "icon": "/assets/interstellar/m1.png"
  },
  {
    "id": "interstellar_m2",
    "order": 5002,
    "titleEn": "Gargantua",
    "titleEs": "Gargantúa – Anatomía de un Monstruo Gravitacional",
    "badge": "Black Hole Explorer",
    "badgeEs": "Explorador de Gargantúa",
    "badgeIcon": "/assets/interstellar/m2.png",
    "color": "#FF3366",
    "icon": "/assets/interstellar/m2.png"
  },
  {
    "id": "interstellar_m3",
    "order": 5003,
    "titleEn": "Elastic Time",
    "titleEs": "El Tiempo es Elástico (Dilatación Temporal)",
    "badge": "Time Traveler",
    "badgeEs": "Viajero del Tiempo",
    "badgeIcon": "/assets/interstellar/m3.png",
    "color": "#33FF66",
    "icon": "/assets/interstellar/m3.png"
  },
  {
    "id": "interstellar_m4",
    "order": 5004,
    "titleEn": "Wormholes",
    "titleEs": "Agujeros de Gusano – Atajos Cósmicos",
    "badge": "Wormhole Surfer",
    "badgeEs": "Surfista de Gusanos",
    "badgeIcon": "/assets/interstellar/m4.png",
    "color": "#9933FF",
    "icon": "/assets/interstellar/m4.png"
  },
  {
    "id": "interstellar_m5",
    "order": 5005,
    "titleEn": "The Tesseract",
    "titleEs": "El Teseracto y la Quinta Dimensión",
    "badge": "5D Master",
    "badgeEs": "Maestro de 5D",
    "badgeIcon": "/assets/interstellar/m5.png",
    "color": "#FFD700",
    "icon": "/assets/interstellar/m5.png"
  },
  {
    "id": "apollo8_m1",
    "order": 101,
    "titleEn": "Genesis of the Mission",
    "titleEs": "Génesis de la Misión",
    "badge": "Lunar Pioneer",
    "badgeEs": "Pionero Lunar",
    "badgeIcon": "/assets/badges/moon_badge.png",
    "color": "#4169E1",
    "icon": "/assets/badges/moon_badge.png"
  },
  {
    "id": "apollo8_m2",
    "order": 102,
    "titleEn": "Earthrise",
    "titleEs": "El Amanecer Terrestre",
    "badge": "Earth Observer",
    "badgeEs": "Observador Terrestre",
    "badgeIcon": "/assets/badges/earth_badge.png",
    "color": "#4169E1",
    "icon": "/assets/badges/earth_badge.png"
  },
  {
    "id": "apollo10_m1",
    "order": 201,
    "titleEn": "The Dress Rehearsal",
    "titleEs": "El Ensayo General",
    "badge": "Snoopy Pilot",
    "badgeEs": "Piloto Snoopy",
    "badgeIcon": "/assets/badges/snoopy_badge.png",
    "color": "#32CD32",
    "icon": "/assets/badges/snoopy_badge.png"
  },
  {
    "id": "exoplanetas_m1",
    "order": 110,
    "titleEn": "Fundamentals and Transit",
    "titleEs": "Fundamentos y Tránsito",
    "badge": "Exo Hunter I",
    "badgeEs": "Cazador Exo I",
    "color": "#9370DB"
  },
  {
    "id": "exoplanetas_m2",
    "order": 111,
    "titleEn": "Types of Worlds",
    "titleEs": "Tipos de Mundos",
    "badge": "Exo Hunter II",
    "badgeEs": "Cazador Exo II",
    "color": "#9370DB"
  },
  {
    "id": "exoplanetas_m3",
    "order": 112,
    "titleEn": "Telescopes and Search",
    "titleEs": "Búsqueda y Telescopios",
    "badge": "Exo Hunter III",
    "badgeEs": "Cazador Exo III",
    "color": "#9370DB"
  },
  {
    "id": "exoplanetas_m4",
    "order": 113,
    "titleEn": "Atmospheres and Biosignatures",
    "titleEs": "Atmósferas y Biofirmas",
    "badge": "Exo Hunter IV",
    "badgeEs": "Cazador Exo IV",
    "color": "#9370DB"
  },
  {
    "id": "area51_m1",
    "order": 9001,
    "titleEn": "What is Area 51?",
    "titleEs": "¿Qué es el Área 51?",
    "badge": "Base Explorer",
    "badgeEs": "Explorador de la Base",
    "badgeIcon": "/assets/area51/area51_m1.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m1.png"
  },
  {
    "id": "area51_m2",
    "order": 9002,
    "titleEn": "The Secret Planes",
    "titleEs": "Los Aviones Secretos",
    "badge": "Stealth Engineer",
    "badgeEs": "Ingeniero Stealth",
    "badgeIcon": "/assets/area51/area51_m2.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m2.png"
  },
  {
    "id": "area51_m3",
    "order": 9003,
    "titleEn": "The Origin of the Rumors",
    "titleEs": "El Origen de los Rumores",
    "badge": "Myth Buster",
    "badgeEs": "Cazador de Mitos",
    "badgeIcon": "/assets/area51/area51_m3.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m3.png"
  },
  {
    "id": "area51_m4",
    "order": 9004,
    "titleEn": "Real Science vs Fiction",
    "titleEs": "Ciencia Real vs. Ficción",
    "badge": "Science Defender",
    "badgeEs": "Defensor de la Ciencia",
    "badgeIcon": "/assets/area51/area51_m4.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m4.png"
  },
  {
    "id": "area51_m5",
    "order": 9005,
    "titleEn": "The Camel Detection Team",
    "titleEs": "El Equipo de Detección de Camelos",
    "badge": "Innovator",
    "badgeEs": "Innovador",
    "badgeIcon": "/assets/area51/area51_m5.png",
    "color": "#1F8A70",
    "icon": "/assets/area51/area51_m5.png"
  },
  {
    "id": "galileo_m1",
    "order": 9001,
    "titleEn": "The Telescope Revolution",
    "titleEs": "La Revolución del Telescopio",
    "badge": "Sky Watcher",
    "badgeEs": "Observador del Cielo",
    "badgeIcon": "/assets/galileo/galileo_m1.png",
    "color": "#7B9ED9",
    "icon": "/assets/galileo/galileo_m1.png"
  },
  {
    "id": "galileo_m2",
    "order": 9002,
    "titleEn": "Galileo and the Moons of Jupiter",
    "titleEs": "Galileo y las Lunas de Júpiter",
    "badge": "Moon Hunter",
    "badgeEs": "Cazador de Lunas",
    "badgeIcon": "/assets/galileo/galileo_m2.png",
    "color": "#C87941",
    "icon": "/assets/galileo/galileo_m2.png"
  },
  {
    "id": "galileo_m3",
    "order": 9003,
    "titleEn": "Galileo vs. The Church",
    "titleEs": "Galileo contra la Inquisición",
    "badge": "Brave Scientist",
    "badgeEs": "Científico Valiente",
    "badgeIcon": "/assets/galileo/galileo_m3.png",
    "color": "#9B59B6",
    "icon": "/assets/galileo/galileo_m3.png"
  },
  {
    "id": "galileo_m4",
    "order": 9004,
    "titleEn": "The Laws of Motion",
    "titleEs": "Las Leyes del Movimiento",
    "badge": "Physics Pioneer",
    "badgeEs": "Pionero de la Física",
    "badgeIcon": "/assets/galileo/galileo_m4.png",
    "color": "#2ECC71",
    "icon": "/assets/galileo/galileo_m4.png"
  },
  {
    "id": "galileo_m5",
    "order": 9005,
    "titleEn": "Galileo's Legacy in Space",
    "titleEs": "El Legado de Galileo en el Espacio",
    "badge": "Legacy Star",
    "badgeEs": "Estrella de Legado",
    "badgeIcon": "/assets/galileo/galileo_m5.png",
    "color": "#E67E22",
    "icon": "/assets/galileo/galileo_m5.png"
  },
  {
    "id": "faraday_m1",
    "order": 9101,
    "titleEn": "The Boy Who Became a Scientist",
    "titleEs": "El Niño que se Convirtió en Científico",
    "badge": "Self-Made Scholar",
    "badgeEs": "Sabio por Méritos Propios",
    "badgeIcon": "/assets/faraday/faraday_m1.png",
    "color": "#3498DB",
    "icon": "/assets/faraday/faraday_m1.png"
  },
  {
    "id": "faraday_m2",
    "order": 9102,
    "titleEn": "Electromagnetic Induction",
    "titleEs": "La Inducción Electromagnética",
    "badge": "Electric Pioneer",
    "badgeEs": "Pionero Eléctrico",
    "badgeIcon": "/assets/faraday/faraday_m2.png",
    "color": "#F39C12",
    "icon": "/assets/faraday/faraday_m2.png"
  },
  {
    "id": "faraday_m3",
    "order": 9103,
    "titleEn": "The Faraday Cage",
    "titleEs": "La Jaula de Faraday",
    "badge": "Shield Master",
    "badgeEs": "Maestro del Escudo",
    "badgeIcon": "/assets/faraday/faraday_m3.png",
    "color": "#1ABC9C",
    "icon": "/assets/faraday/faraday_m3.png"
  },
  {
    "id": "faraday_m4",
    "order": 9104,
    "titleEn": "Electrolysis and Chemistry",
    "titleEs": "La Electrolisis y la Química",
    "badge": "Molecule Breaker",
    "badgeEs": "Rompedor de Moléculas",
    "badgeIcon": "/assets/faraday/faraday_m4.png",
    "color": "#E74C3C",
    "icon": "/assets/faraday/faraday_m4.png"
  },
  {
    "id": "faraday_m5",
    "order": 9105,
    "titleEn": "Faraday's Legacy",
    "titleEs": "El Legado de Faraday",
    "badge": "Electricity Champion",
    "badgeEs": "Campeón de la Electricidad",
    "badgeIcon": "/assets/faraday/faraday_m5.png",
    "color": "#8E44AD",
    "icon": "/assets/faraday/faraday_m5.png"
  },
  {
    "id": "davinci_m1",
    "order": 9201,
    "titleEn": "The Universal Genius",
    "titleEs": "El Genio Universal",
    "badge": "Renaissance Mind",
    "badgeEs": "Mente del Renacimiento",
    "badgeIcon": "/assets/davinci/davinci_m1.png",
    "color": "#D4A843",
    "icon": "/assets/davinci/davinci_m1.png"
  },
  {
    "id": "davinci_m2",
    "order": 9202,
    "titleEn": "Leonardo's Flying Machines",
    "titleEs": "Las Máquinas Voladoras de Leonardo",
    "badge": "Dream Flyer",
    "badgeEs": "Soñador del Vuelo",
    "badgeIcon": "/assets/davinci/davinci_m2.png",
    "color": "#2980B9",
    "icon": "/assets/davinci/davinci_m2.png"
  },
  {
    "id": "davinci_m3",
    "order": 9203,
    "titleEn": "Leonardo and Human Anatomy",
    "titleEs": "Leonardo y la Anatomía Humana",
    "badge": "Body Scholar",
    "badgeEs": "Estudioso del Cuerpo",
    "badgeIcon": "/assets/davinci/davinci_m3.png",
    "color": "#C0392B",
    "icon": "/assets/davinci/davinci_m3.png"
  },
  {
    "id": "davinci_m4",
    "order": 9204,
    "titleEn": "Leonardo the Engineer",
    "titleEs": "Leonardo el Ingeniero",
    "badge": "Master Builder",
    "badgeEs": "Constructor Maestro",
    "badgeIcon": "/assets/davinci/davinci_m4.png",
    "color": "#27AE60",
    "icon": "/assets/davinci/davinci_m4.png"
  },
  {
    "id": "davinci_m5",
    "order": 9205,
    "titleEn": "Leonardo's Scientific Method",
    "titleEs": "El Método Científico de Leonardo",
    "badge": "Observer Supreme",
    "badgeEs": "Observador Supremo",
    "badgeIcon": "/assets/davinci/davinci_m5.png",
    "color": "#16A085",
    "icon": "/assets/davinci/davinci_m5.png"
  },
  {
    "id": "dinos_m1",
    "order": 8001,
    "titleEn": "The Triassic Dawn",
    "titleEs": "El Amanecer del Triásico",
    "badge": "Triassic Explorer",
    "badgeEs": "Explorador del Triásico",
    "badgeIcon": "/assets/dinosaurios/dinos_m1.png",
    "color": "#8B4513",
    "icon": "/assets/dinosaurios/dinos_m1.png"
  },
  {
    "id": "dinos_m2",
    "order": 8002,
    "titleEn": "The Jurassic Giants",
    "titleEs": "Gigantes del Jurásico",
    "badge": "Jurassic Giant",
    "badgeEs": "Gigante del Jurásico",
    "badgeIcon": "/assets/dinosaurios/dinos_m2.png",
    "color": "#2E7D32",
    "icon": "/assets/dinosaurios/dinos_m2.png"
  },
  {
    "id": "dinos_m3",
    "order": 8003,
    "titleEn": "Tyrannosaurus Rex",
    "titleEs": "Tyrannosaurus Rex: El Rey Supremo",
    "badge": "T-Rex Master",
    "badgeEs": "Maestro del T-Rex",
    "badgeIcon": "/assets/dinosaurios/dinos_m3.png",
    "color": "#C62828",
    "icon": "/assets/dinosaurios/dinos_m3.png"
  },
  {
    "id": "dinos_m4",
    "order": 8004,
    "titleEn": "Velociraptors",
    "titleEs": "Velociraptores: Cazadores Inteligentes",
    "badge": "Raptor Tracker",
    "badgeEs": "Rastreador de Raptores",
    "badgeIcon": "/assets/dinosaurios/dinos_m4.png",
    "color": "#E65100",
    "icon": "/assets/dinosaurios/dinos_m4.png"
  },
  {
    "id": "dinos_m5",
    "order": 8005,
    "titleEn": "Flying Pterosaurs",
    "titleEs": "Pterosaurios: Los Señores del Cielo",
    "badge": "Sky Watcher",
    "badgeEs": "Vigía del Cielo",
    "badgeIcon": "/assets/dinosaurios/dinos_m5.png",
    "color": "#0277BD",
    "icon": "/assets/dinosaurios/dinos_m5.png"
  },
  {
    "id": "dinos_m6",
    "order": 8006,
    "titleEn": "Armored Dinosaurs",
    "titleEs": "Dinosaurios Acorazados",
    "badge": "Armor Specialist",
    "badgeEs": "Especialista en Armaduras",
    "badgeIcon": "/assets/dinosaurios/dinos_m6.png",
    "color": "#5D4037",
    "icon": "/assets/dinosaurios/dinos_m6.png"
  },
  {
    "id": "dinos_m7",
    "order": 8007,
    "titleEn": "Dinosaur Nests",
    "titleEs": "Nidos y Crías de Dinosaurio",
    "badge": "Nest Discoverer",
    "badgeEs": "Descubridor de Nidos",
    "badgeIcon": "/assets/dinosaurios/dinos_m7.png",
    "color": "#F9A825",
    "icon": "/assets/dinosaurios/dinos_m7.png"
  },
  {
    "id": "dinos_m8",
    "order": 8008,
    "titleEn": "The Cretaceous World",
    "titleEs": "El Mundo del Cretácico",
    "badge": "Cretaceous Navigator",
    "badgeEs": "Navegante del Cretácico",
    "badgeIcon": "/assets/dinosaurios/dinos_m8.png",
    "color": "#00695C",
    "icon": "/assets/dinosaurios/dinos_m8.png"
  },
  {
    "id": "dinos_m9",
    "order": 8009,
    "titleEn": "The Asteroid Impact",
    "titleEs": "El Asteroide que Cambió Todo",
    "badge": "Impact Survivor",
    "badgeEs": "Sobreviviente del Impacto",
    "badgeIcon": "/assets/dinosaurios/dinos_m9.png",
    "color": "#B71C1C",
    "icon": "/assets/dinosaurios/dinos_m9.png"
  },
  {
    "id": "dinos_m10",
    "order": 8010,
    "titleEn": "Paleontology Today",
    "titleEs": "Paleontología del Futuro",
    "badge": "Future Paleontologist",
    "badgeEs": "Paleontólogo del Futuro",
    "badgeIcon": "/assets/dinosaurios/dinos_m10.png",
    "color": "#6A1B9A",
    "icon": "/assets/dinosaurios/dinos_m10.png"
  },
  {
    "id": "marinos_m1",
    "order": 8101,
    "titleEn": "Ichthyosaurs",
    "titleEs": "Ictiosaurios: Los Delfines del Mesozoico",
    "badge": "Ichthyosaur Finder",
    "badgeEs": "Descubridor de Ictiosaurios",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m1.png",
    "color": "#0D47A1",
    "icon": "/assets/reptiles_marinos/marinos_m1.png"
  },
  {
    "id": "marinos_m2",
    "order": 8102,
    "titleEn": "Plesiosaurs",
    "titleEs": "Plesiosaurios: Los Cuellos del Abismo",
    "badge": "Plesiosaur Expert",
    "badgeEs": "Experto en Plesiosaurios",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m2.png",
    "color": "#1565C0",
    "icon": "/assets/reptiles_marinos/marinos_m2.png"
  },
  {
    "id": "marinos_m3",
    "order": 8103,
    "titleEn": "Mosasaurs",
    "titleEs": "Mosasaurios: Los Depredadores Supremos",
    "badge": "Mosasaur Hunter",
    "badgeEs": "Cazador de Mosasaurios",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m3.png",
    "color": "#283593",
    "icon": "/assets/reptiles_marinos/marinos_m3.png"
  },
  {
    "id": "marinos_m4",
    "order": 8104,
    "titleEn": "Prehistoric Sharks",
    "titleEs": "Tiburones Prehistóricos",
    "badge": "Shark Researcher",
    "badgeEs": "Investigador de Tiburones",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m4.png",
    "color": "#37474F",
    "icon": "/assets/reptiles_marinos/marinos_m4.png"
  },
  {
    "id": "marinos_m5",
    "order": 8105,
    "titleEn": "Giant Ammonites",
    "titleEs": "Amonites: Los Caracoles del Abismo",
    "badge": "Ammonite Collector",
    "badgeEs": "Coleccionista de Amonites",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m5.png",
    "color": "#4527A0",
    "icon": "/assets/reptiles_marinos/marinos_m5.png"
  },
  {
    "id": "marinos_m6",
    "order": 8106,
    "titleEn": "Nothosaurs and Placodonts",
    "titleEs": "Notosaurios y Placodontos",
    "badge": "Triassic Diver",
    "badgeEs": "Buzo del Triásico",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m6.png",
    "color": "#00838F",
    "icon": "/assets/reptiles_marinos/marinos_m6.png"
  },
  {
    "id": "marinos_m7",
    "order": 8107,
    "titleEn": "Sea Turtles Through Time",
    "titleEs": "Tortugas Marinas Prehistóricas",
    "badge": "Turtle Tracker",
    "badgeEs": "Rastreador de Tortugas",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m7.png",
    "color": "#2E7D32",
    "icon": "/assets/reptiles_marinos/marinos_m7.png"
  },
  {
    "id": "marinos_m8",
    "order": 8108,
    "titleEn": "Deep Sea Creatures",
    "titleEs": "Criaturas de las Profundidades",
    "badge": "Abyss Explorer",
    "badgeEs": "Explorador del Abismo",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m8.png",
    "color": "#1A237E",
    "icon": "/assets/reptiles_marinos/marinos_m8.png"
  },
  {
    "id": "marinos_m9",
    "order": 8109,
    "titleEn": "Marine Ecosystems",
    "titleEs": "Ecosistemas Marinos Prehistóricos",
    "badge": "Ecosystem Master",
    "badgeEs": "Maestro de Ecosistemas",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m9.png",
    "color": "#006064",
    "icon": "/assets/reptiles_marinos/marinos_m9.png"
  },
  {
    "id": "marinos_m10",
    "order": 8110,
    "titleEn": "Marine Paleontology Today",
    "titleEs": "Paleontología Marina Moderna",
    "badge": "Marine Scientist",
    "badgeEs": "Científico Marino",
    "badgeIcon": "/assets/reptiles_marinos/marinos_m10.png",
    "color": "#01579B",
    "icon": "/assets/reptiles_marinos/marinos_m10.png"
  },
  {
    "id": "tesla_m1",
    "order": 8201,
    "titleEn": "Born in a Storm",
    "titleEs": "Nacido en una Tormenta",
    "badge": "Lightning Born",
    "badgeEs": "Nacido del Rayo",
    "badgeIcon": "/assets/tesla/tesla_m1.png",
    "color": "#1565C0",
    "icon": "/assets/tesla/tesla_m1.png"
  },
  {
    "id": "tesla_m2",
    "order": 8202,
    "titleEn": "AC vs DC",
    "titleEs": "Corriente Alterna vs Corriente Continua",
    "badge": "Current Master",
    "badgeEs": "Maestro de la Corriente",
    "badgeIcon": "/assets/tesla/tesla_m2.png",
    "color": "#F57F17",
    "icon": "/assets/tesla/tesla_m2.png"
  },
  {
    "id": "tesla_m3",
    "order": 8203,
    "titleEn": "The Tesla Coil",
    "titleEs": "La Bobina de Tesla",
    "badge": "Coil Builder",
    "badgeEs": "Constructor de Bobinas",
    "badgeIcon": "/assets/tesla/tesla_m3.png",
    "color": "#7B1FA2",
    "icon": "/assets/tesla/tesla_m3.png"
  },
  {
    "id": "tesla_m4",
    "order": 8204,
    "titleEn": "Wireless Dreams",
    "titleEs": "El Sueño de la Energía Inalámbrica",
    "badge": "Wireless Pioneer",
    "badgeEs": "Pionero Inalámbrico",
    "badgeIcon": "/assets/tesla/tesla_m4.png",
    "color": "#00695C",
    "icon": "/assets/tesla/tesla_m4.png"
  },
  {
    "id": "tesla_m5",
    "order": 8205,
    "titleEn": "Radio and Remote Control",
    "titleEs": "Radio y Control Remoto",
    "badge": "Radio Inventor",
    "badgeEs": "Inventor de la Radio",
    "badgeIcon": "/assets/tesla/tesla_m5.png",
    "color": "#E65100",
    "icon": "/assets/tesla/tesla_m5.png"
  },
  {
    "id": "tesla_m6",
    "order": 8206,
    "titleEn": "X-Rays and Medicine",
    "titleEs": "Rayos X y Medicina",
    "badge": "X-Ray Pioneer",
    "badgeEs": "Pionero de los Rayos X",
    "badgeIcon": "/assets/tesla/tesla_m6.png",
    "color": "#2E7D32",
    "icon": "/assets/tesla/tesla_m6.png"
  },
  {
    "id": "tesla_m7",
    "order": 8207,
    "titleEn": "Niagara Falls Power",
    "titleEs": "La Central de las Cataratas del Niágara",
    "badge": "Hydroelectric Master",
    "badgeEs": "Maestro Hidroeléctrico",
    "badgeIcon": "/assets/tesla/tesla_m7.png",
    "color": "#0277BD",
    "icon": "/assets/tesla/tesla_m7.png"
  },
  {
    "id": "tesla_m8",
    "order": 8208,
    "titleEn": "Tesla's Inventions",
    "titleEs": "Las Invenciones Olvidadas de Tesla",
    "badge": "Invention Hunter",
    "badgeEs": "Cazador de Inventos",
    "badgeIcon": "/assets/tesla/tesla_m8.png",
    "color": "#AD1457",
    "icon": "/assets/tesla/tesla_m8.png"
  },
  {
    "id": "tesla_m9",
    "order": 8209,
    "titleEn": "Tesla's Later Years",
    "titleEs": "Los Últimos Años de Tesla",
    "badge": "Tesla Historian",
    "badgeEs": "Historiador de Tesla",
    "badgeIcon": "/assets/tesla/tesla_m9.png",
    "color": "#546E7A",
    "icon": "/assets/tesla/tesla_m9.png"
  },
  {
    "id": "tesla_m10",
    "order": 8210,
    "titleEn": "Tesla's Legacy",
    "titleEs": "El Legado Eterno de Tesla",
    "badge": "Tesla Legacy Keeper",
    "badgeEs": "Guardián del Legado de Tesla",
    "badgeIcon": "/assets/tesla/tesla_m10.png",
    "color": "#311B92",
    "icon": "/assets/tesla/tesla_m10.png"
  },
  {
    "id": "curie_m1",
    "order": 8001,
    "titleEn": "Maria Skłodowska: The Girl from Warsaw",
    "titleEs": "Maria Skłodowska: la niña de Varsovia",
    "badge": "Star of Warsaw",
    "badgeEs": "Estrella de Varsovia",
    "badgeIcon": "/assets/marie_curie/curie_m1.png",
    "color": "#00FF88",
    "icon": "/assets/marie_curie/curie_m1.png"
  },
  {
    "id": "curie_m2",
    "order": 8002,
    "titleEn": "Paris, the Sorbonne, and Pierre Curie",
    "titleEs": "París, la Sorbona y Pierre Curie",
    "badge": "Pioneer of Paris",
    "badgeEs": "Pionera de París",
    "badgeIcon": "/assets/marie_curie/curie_m2.png",
    "color": "#2ECC71",
    "icon": "/assets/marie_curie/curie_m2.png"
  },
  {
    "id": "curie_m3",
    "order": 8003,
    "titleEn": "The Discovery of Polonium and Radium",
    "titleEs": "El descubrimiento del Polonio y el Radio",
    "badge": "Element Discoverer",
    "badgeEs": "Descubridora de Elementos",
    "badgeIcon": "/assets/marie_curie/curie_m3.png",
    "color": "#E8D44D",
    "icon": "/assets/marie_curie/curie_m3.png"
  },
  {
    "id": "curie_m4",
    "order": 8004,
    "titleEn": "Two Nobel Prizes: Physics (1903) and Chemistry (1911)",
    "titleEs": "Dos Premios Nobel: Física (1903) y Química (1911)",
    "badge": "Double Nobel",
    "badgeEs": "Doble Nobel",
    "badgeIcon": "/assets/marie_curie/curie_m4.png",
    "color": "#FFD700",
    "icon": "/assets/marie_curie/curie_m4.png"
  },
  {
    "id": "curie_m5",
    "order": 8005,
    "titleEn": "The 'Petites Curies' and World War I",
    "titleEs": "Las 'Petites Curies' y la Primera Guerra Mundial",
    "badge": "War Heroine",
    "badgeEs": "Heroína de Guerra",
    "badgeIcon": "/assets/marie_curie/curie_m5.png",
    "color": "#E74C3C",
    "icon": "/assets/marie_curie/curie_m5.png"
  },
  {
    "id": "curie_m6",
    "order": 8006,
    "titleEn": "Her Legacy: Irène Joliot-Curie and Modern Science",
    "titleEs": "Su legado: Irène Joliot-Curie y la ciencia moderna",
    "badge": "Radiant Legacy",
    "badgeEs": "Legado Radiante",
    "badgeIcon": "/assets/marie_curie/curie_m6.png",
    "color": "#9B59B6",
    "icon": "/assets/marie_curie/curie_m6.png"
  }
];
