const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

function replaceSection(src, moduleId, newParagraphs, newQuiz) {
  const moduleStart = src.indexOf(`"id": "${moduleId}"`);
  if (moduleStart === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  const sectionsStart = src.indexOf('"sections"', moduleStart);
  const textStart = src.indexOf('"text"', sectionsStart);
  const arrStart = src.indexOf('[', textStart);
  let depth = 0, i = arrStart;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  const arrEnd = i;
  const newTextBlock = JSON.stringify(newParagraphs, null, 14);
  src = src.slice(0, arrStart) + newTextBlock + src.slice(arrEnd + 1);

  if (newQuiz) {
    const quizStart = src.indexOf('"quizEs"', src.indexOf(`"id": "${moduleId}"`));
    const quizArrStart = src.indexOf('[', quizStart);
    let d2 = 0, j = quizArrStart;
    while (j < src.length) {
      if (src[j] === '[') d2++;
      else if (src[j] === ']') { d2--; if (d2 === 0) break; }
      j++;
    }
    src = src.slice(0, quizArrStart) + JSON.stringify(newQuiz, null, 4) + src.slice(j + 1);
  }
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// egypt_m13 — 365 Días: El Calendario Civil
const egypt_m13_paragraphs = [
  "¡Atención al reloj cósmico, cadete! El calendario que usas hoy, con 365 días divididos en 12 meses, es una invención que tiene más de 5,000 años de historia y nació en las orillas del río Nilo. Los antiguos egipcios fueron los primeros en crear un calendario civil de 365 días, independiente de las fases de la Luna, basado exclusivamente en el movimiento del Sol y las estrellas. Este calendario revolucionó la organización de la vida humana.",
  "Antes de los egipcios, la mayoría de las civilizaciones antiguas usaban calendarios lunares, basados en las fases de la Luna. El problema es que el mes lunar dura 29.5 días, y 12 meses lunares solo suman 354 días, no 365. Esto significa que un calendario puramente lunar 'se corre' 11 días cada año respecto a las estaciones. En 33 años, el mes de 'primavera' en un calendario lunar habrá completado el ciclo anual y vuelto al invierno. Coordinar un calendario lunar con las estaciones de la agricultura era complicado.",
  "Los egipcios resolvieron este problema de forma elegante: observaron que el año solar exacto dura 365 días y un cuarto. Crearon un calendario de 365 días dividido en 12 meses de 30 días cada uno, más 5 días extra al final del año (llamados 'días epagómenos' o días adicionales). Estos 5 días extra eran considerados días peligrosos, fuera del tiempo normal, cuando los dioses celebraban sus cumpleaños.",
  "El año egipcio estaba dividido en tres estaciones de cuatro meses cada una. La primera estación era 'Akhet' (la inundación), cuando el Nilo se desbordaba y fertilizaba los campos. La segunda era 'Peret' (la siembra y el crecimiento), cuando los agricultores plantaban en el barro fértil dejado por la inundación. La tercera era 'Shemu' (la cosecha), la época seca cuando los cultivos maduraban. Este ciclo de inundación-siembra-cosecha era la columna vertebral de la vida egipcia.",
  "El problema del 'cuarto de día' extra que tiene el año solar real (365.25 días) fue resuelto siglos después por Julio César, quien en el año 46 a.C. reformó el calendario romano usando el modelo egipcio de 365 días y añadió el año bisiesto: cada cuatro años, febrero tiene un día extra para compensar los cuartos de día acumulados. El astrónomo egipcio Sosígenes de Alejandría fue quien asesoró a César en esta reforma, que llamamos 'calendario juliano'.",
  "En el año 1582, el papa Gregorio XIII hizo una nueva reforma al calendario para corregir un pequeño error: el año solar real no es exactamente 365.25 días, sino 365.2422 días. Esta diferencia de 0.0078 días por año acumulada durante 1,600 años había desplazado el equinoccio de primavera 10 días antes de su fecha correcta. La reforma gregoriana eliminó 10 días del calendario (después del 4 de octubre de 1582 vino el 15 de octubre) y modificó la regla del año bisiesto. Este es el calendario que usamos hoy.",
  "El mes es una unidad de tiempo antigua basada originalmente en el ciclo lunar de 29.5 días. Sin embargo, los meses del calendario egipcio (y los del nuestro) ya no corresponden a las fases de la Luna. Nuestros meses tienen 28, 29, 30 o 31 días, longitudes que no corresponden a ningún ciclo astronómico natural. Son un compromiso histórico entre el mes lunar y la necesidad de que 12 meses sumen cerca de 365 días.",
  "Los egipcios observaron que la estrella Sirio (Sopdet) volvía a ser visible en el horizonte justo antes del amanecer (orto helíaco) aproximadamente cada 365 días. Usaron este evento astronómico como el ancla de su calendario: el primer día del año coincidía con el orto helíaco de Sirio, que a su vez coincidía con el comienzo de la inundación del Nilo. Astronomía, calendario y agricultura estaban perfectamente sincronizados.",
  "El sacerdote-astrónomo 'Khery-hebet' era responsable de mantener el calendario. Cada mes observaba el cielo con instrumentos precisos para confirmar que las estrellas estaban en las posiciones correctas y que ninguna desviación se estaba acumulando. Cuando el calendario se desviaba (porque 365 días no es exactamente el año solar), los sacerdotes calculaban los ajustes necesarios y los comunicaban a los escribas que llevaban los registros administrativos.",
  "El calendario egipcio fue adoptado y modificado por los persas, los griegos (con Alejandro Magno), los romanos (con Julio César) y finalmente los europeos medievales. En cada etapa, el calendario fue refinado usando mejores medidas astronómicas. El calendario que usamos hoy en todo el mundo es, en esencia, el calendario egipcio de 365 días, modificado para compensar el pequeño error del cuarto de día extra del año solar real.",
  "Los mayas también desarrollaron un calendario solar de 365 días de manera independiente, llamado 'Haab'. Como los egipcios, los mayas dividieron el año en 18 meses de 20 días más 5 días extra (los 'días sin nombre' o 'Wayeb'). Esta convergencia independiente de dos civilizaciones en la misma solución al problema del calendario es notable: ambas llegaron al número 365 observando el mismo Sol con ojos igualmente atentos.",
  "El calendario civil de 365 días era diferente del calendario religioso egipcio de 360 días que usaban para ciertos rituales. El calendario de 360 días (12 meses de 30 días exactos) era más simple matemáticamente pero menos preciso astronómicamente. Los escribas sabían que el año real tenía 365 días y añadían los 5 días epagómenos al final. Esta dualidad entre el calendario 'ideal' de 360 días y el 'real' de 365 refleja la tensión entre la simplicidad matemática y la precisión astronómica.",
  "El nombre de los meses del calendario actual en los idiomas europeos viene del calendario romano, que a su vez adaptó el modelo egipcio. Enero viene de Janus (dios romano de los principios); Julio viene de Julio César; Agosto viene del emperador Augusto. Los nombres de los días de la semana vienen de los planetas: Lunes (Luna), Martes (Marte), Miércoles (Mercurio), Jueves (Júpiter), Viernes (Venus), Sábado (Saturno), Domingo (Sol). Los egipcios usaban los siete 'astros errantes' (Sol, Luna, 5 planetas) como base para su semana.",
  "La sincronización entre el calendario civil y el calendario astronómico requería observaciones continuas y precisas. Los sacerdotes egipcios llevaban registros de las salidas y puestas de las estrellas más importantes durante generaciones. Esta base de datos astronómica acumulada a lo largo de siglos fue uno de los grandes legados del Antiguo Egipto a la ciencia. Cuando los griegos llegaron a Egipto, accedieron a siglos de datos astronómicos que les permitieron desarrollar sus propias teorías.",
  "El calendario es quizás el legado más práctico y duradero de la astronomía egipcia. Cada vez que miras el mes en tu teléfono, estás usando un sistema de contar el tiempo que tiene sus raíces en las observaciones que los sacerdotes del Nilo hacían hace 5,000 años. De las canciones de la diosa Sopdet a los datos de satélites GPS, el calendario de 365 días ha atravesado toda la historia humana como el invento que nos permitió sincronizar nuestras vidas con el cosmos."
];

const egypt_m13_quiz = [
  { "q": "¿Cuántos días tenía el calendario civil egipcio?", "options": ["360", "354", "365", "400"], "a": 2 },
  { "q": "¿Cómo se llamaban los 5 días extra del calendario egipcio?", "options": ["Días dorados", "Días epagómenos", "Días de Osiris", "Días del caos"], "a": 1 },
  { "q": "¿Quién reformó el calendario romano añadiendo los años bisiestos?", "options": ["Augusto", "Nerón", "Julio César", "Alejandro Magno"], "a": 2 },
  { "q": "¿Cuáles eran las tres estaciones del año egipcio?", "options": ["Verano, otoño, invierno", "Akhet, Peret y Shemu", "Sirio, Orión y Nut", "Lluvia, sol y viento"], "a": 1 },
  { "q": "¿Qué estrella usaban los egipcios como ancla de su calendario?", "options": ["Polaris", "Vega", "Sirio (Sopdet)", "Betelgeuse"], "a": 2 }
];

// egypt_m14 — Apofis y el Devorador de Soles
const egypt_m14_paragraphs = [
  "¡Alarma de nivel máximo, cadete! Hoy vamos a explorar uno de los mitos más poderosos del Antiguo Egipto: Apofis, la gran serpiente del caos. Para los egipcios, el Sol no simplemente 'se ponía' cada noche y 'salía' cada mañana como si nada. En su cosmología, cada amanecer era el resultado de una batalla épica que Ra, el dios del Sol, libraba cada noche contra Apofis, la serpiente gigante de la oscuridad, para que la humanidad pudiera sobrevivir otro día.",
  "Apofis (también llamado Apep) era una serpiente colosal de decenas de kilómetros de longitud que habitaba en las profundidades del caos primordial. Cada noche, cuando la barca solar de Ra descendía bajo el horizonte para navegar por el inframundo hacia el amanecer, Apofis la atacaba. Los dioses del inframundo, encabezados por Seth (en este contexto un protector, no el malvado de otros mitos), luchaban ferozmente para proteger la barca de Ra. Si alguna vez Apofis ganaba, el Sol no volvería a salir y el mundo terminaría.",
  "Esta mitología no era solo fantasía poética; reflejaba la comprensión empírica de los eclipses solares. Cuando la Luna pasaba frente al Sol y lo oscurecía totalmente, los egipcios interpretaban este fenómeno aterrador como el momento en que Apofis había logrado engullir al Sol. Las eclipse solares podían durar hasta 7 minutos y durante ese tiempo el cielo se oscurecía, las estrellas aparecían, los animales se confundían y la temperatura bajaba. Para quienes no sabían lo que era un eclipse, debía parecer literalmente el fin del mundo.",
  "Los sacerdotes egipcios sabían que los eclipses eran predecibles. Llevaban registros detallados de los eclipses durante siglos, notando que seguían patrones repetitivos. El ciclo de 18 años, 11 días y 8 horas llamado 'Saros' (aunque los egipcios no le pusieron ese nombre) es el período después del cual los eclipses se repiten en posiciones similares relativas a la Tierra, la Luna y el Sol. Con registros suficientes, los sacerdotes podían predecir los eclipses con anticipación y así tranquilizar al pueblo en lugar de aterrorizarlo.",
  "El asteroide Apophis (29075) fue descubierto el 19 de junio de 2004 por los astrónomos Roy Tucker, David Tholen y Fabrizio Bernardi. Lo nombraron 'Apophis' en honor a la serpiente del caos egipcia porque, cuando calcularon su órbita, descubrieron algo que dejó a la comunidad científica en estado de alerta: el asteroide podría impactar con la Tierra en 2029. Fue la primera vez en 50 años que un asteroide recibió la máxima calificación de peligro en la escala de Palermo.",
  "Las observaciones adicionales del asteroide Apophis (con 370 metros de diámetro) refinaron los cálculos orbitales. En diciembre de 2004, las estimaciones de la probabilidad de impacto llegaron al 2.7%, la más alta jamás registrada para un cuerpo celeste conocido de ese tamaño. Esto generó cobertura mediática mundial. Sin embargo, con más datos, la probabilidad fue bajando. Para 2021, la NASA confirmó que Apophis NO impactará la Tierra ni en 2029, ni en 2036, ni en 2068.",
  "El 13 de abril de 2029, el asteroide Apophis pasará a apenas 31,000 kilómetros de la Tierra: más cerca que la órbita de los satélites geoestacionarios (que orbitan a 35,800 km). Será visible a simple vista desde Europa, África y Asia, como un punto de luz moviéndose rápidamente a través del cielo. Jamás un asteroide de ese tamaño ha pasado tan cerca de la Tierra en el tiempo registrado de la historia humana. Será un evento astronómico histórico.",
  "Una misión de la NASA llamada OSIRIS-Apex (anteriormente OSIRIS-REx, que recolectó muestras del asteroide Bennu) cambiará su destino hacia Apophis después de entregar las muestras de Bennu en 2023. Llegará a Apophis justo después de su paso cercano a la Tierra en 2029, cuando el asteroide habrá sido ligeramente perturbado gravitacionalmente por nuestra planeta. Estudiará cómo esta interacción cambió la órbita y rotación de Apophis.",
  "Los egipcios tenían razón en una cosa: la serpiente del caos es real, aunque no es una serpiente sino un asteroide. El impacto de un asteroide del tamaño de Apophis contra la Tierra liberaría una energía equivalente a 1,200 megatones de TNT (unas 80,000 veces la bomba de Hiroshima). Podría destruir un área del tamaño de un país europeo mediano y lanzar suficiente polvo a la atmósfera para afectar el clima global durante años.",
  "El mito de Apofis también tiene conexiones con los fenómenos astronómicos de las tormentas de arena del Sahara. Cuando una tormenta de arena gigante ('haboob' en árabe) avanzaba sobre Egipto, el Sol se ocultaba bajo una nube de polvo de color naranja intenso. Los colores y la oscuridad de estas tormentas podían durar días. Para los egipcios, estas tormentas eran manifestaciones de Apofis atacando incluso sin llegar a devorar completamente al Sol.",
  "En los textos del Libro de los Muertos egipcio (más correctamente llamado 'Libro para Salir al Día'), hay fórmulas específicas que el difunto debía recitar para ayudar a Ra a vencer a Apofis durante su viaje nocturno por el inframundo. El difunto, como pasajero en la barca solar, participaba activamente en la batalla cósmica. Esta concepción del alma humana como participante en la lucha cósmica entre el orden y el caos es una de las ideas más fascinantes de la religión egipcia.",
  "Los rituales contra Apofis que los sacerdotes realizaban en los templos incluían escupir en un dibujo de la serpiente, pisotearlo, quemarlo y luego disolver las cenizas. Era un ritual de magia simpática: al destruir la imagen, se debilitaba a la serpiente real del caos. Estos rituales se realizaban diariamente en los templos más importantes de Egipto, especialmente el de Heliópolis (ciudad del Sol). Era la 'defensa antichaos' del Antiguo Egipto.",
  "La amenaza de asteroides como Apophis ha llevado a la NASA y la ESA (Agencia Espacial Europea) a desarrollar programas de defensa planetaria. En 2022, la misión DART (Double Asteroid Redirection Test) impactó deliberadamente contra el asteroidito Dimorphos (el satélite del asteroide Didymos) y logró cambiar su período orbital en 32 minutos. Fue la primera vez en la historia que la humanidad demostró poder cambiar la trayectoria de un asteroide. Los egipcios habrían llamado a esto 'vencer a Apofis'.",
  "El sistema de alerta temprana de asteroides peligrosos incluye varios programas como el Catalina Sky Survey, Pan-STARRS y el Observatorio de Monte Palomar, que escanean el cielo cada noche buscando objetos que se muevan contra el fondo fijo de las estrellas. Cuando encuentran un objeto sospechoso, calculan su órbita y evalúan si podría acercarse peligrosamente a la Tierra. Es la versión moderna de los sacerdotes que vigilaban el cielo todas las noches buscando a Apofis.",
  "El gran legado del mito de Apofis es que captura una verdad científica real: el cosmos no es un lugar seguro y ordenado. Los impactos de asteroides han moldeado la historia de la Tierra: el impacto de Chicxulub hace 66 millones de años causó la extinción de los dinosaurios. Sin ese impacto, probablemente no existirían los mamíferos, y por lo tanto tampoco existiríamos nosotros. Apofis, la serpiente del caos, es real. Pero también son reales los Ra modernos: los científicos y las agencias espaciales que vigilan el cielo para proteger a la humanidad."
];

const egypt_m14_quiz = [
  { "q": "¿Quién era Apofis en la mitología egipcia?", "options": ["El dios del Sol", "La serpiente del caos que atacaba a Ra cada noche", "El faraón de las sombras", "Un cocodrilo sagrado"], "a": 1 },
  { "q": "¿En qué año pasará el asteroide Apophis muy cerca de la Tierra?", "options": ["2025", "2029", "2036", "2068"], "a": 1 },
  { "q": "¿A qué distancia pasará Apophis de la Tierra en 2029?", "options": ["31,000 km", "384,000 km (distancia lunar)", "1 millón de km", "100 km"], "a": 0 },
  { "q": "¿Qué misión demostró en 2022 que podemos cambiar la órbita de un asteroide?", "options": ["Cassini", "New Horizons", "DART", "Voyager"], "a": 2 },
  { "q": "¿Qué interpretaban los egipcios cuando ocurría un eclipse solar?", "options": ["Que Ra descansaba", "Que Apofis había engullido temporalmente al Sol", "Que era momento de fiesta", "Que llovería mucho"], "a": 1 }
];

// egypt_m15 — Ojo Satelital: Arqueología Espacial
const egypt_m15_paragraphs = [
  "¡Último módulo de nuestra misión egipcia, cadete élite! Para cerrar con broche de oro nuestro viaje a través de 5,000 años de astronomía del Nilo, vamos a hablar de algo que une perfectamente el pasado más antiguo con el futuro más avanzado: la arqueología espacial. Hoy, los científicos usan los mismos satélites que se usan para la navegación GPS, para pronósticos del tiempo y para la teledetección ambiental, para buscar sitios arqueológicos ocultos bajo las arenas del desierto egipcio.",
  "La arqueología espacial, también llamada 'teledetección arqueológica', usa imágenes de satélite y radar de penetración de suelo para detectar estructuras enterradas que son invisibles a nivel del suelo. Los edificios y muros enterrados de piedra tienen densidades y temperaturas ligeramente diferentes a la arena del desierto. Estas diferencias, aunque invisibles al ojo humano, son detectables por los sensores infrarrojos y de microondas de los satélites modernos.",
  "La arqueóloga espacial Sarah Parcak, de la Universidad de Birmingham, es pionera en esta técnica. Usando imágenes satelitales de alta resolución del satélite WorldView de DigitalGlobe, ha identificado más de 3,000 asentamientos perdidos, 17 posibles pirámides enterradas y miles de tumbas desconocidas bajo las arenas de Egipto. Su trabajo ha transformado completamente la arqueología: ahora se sabe que hay más sitios arqueológicos enterrados en Egipto de los que jamás se podrían excavar.",
  "Las 17 posibles pirámides 'perdidas' detectadas por Parcak son especialmente emocionantes. En 2011, un equipo excavó dos de las ubicaciones señaladas y encontró pirámides de ladrillo de barro, más pequeñas que las de Guiza pero arqueológicamente significativas. Las pirámides de ladrillo de barro son mucho más vulnerables a la erosión y los saqueadores, por lo que muchas han desaparecido a nivel de la superficie pero su base aún está enterrada. El satélite puede ver lo que el arqueólogo parado sobre el sitio no puede.",
  "El radar de apertura sintética (SAR) es otra herramienta poderosa. Este tipo de radar, montado en satélites como el Sentinel-1 de la ESA, emite ondas de radio que pueden penetrar varios metros de arena seca. Al rebotar en estructuras enterradas, estas ondas crean imágenes que revelan formas geométricas perfectas, como círculos, rectángulos y líneas rectas, que no ocurren naturalmente sino que son creaciones humanas. Cada forma geométrica detectada es un candidato a sitio arqueológico.",
  "El desierto egipcio es ideal para la arqueología satelital por dos razones. Primero, la arena seca es transparente a las ondas de microondas, lo que permite ver a mayor profundidad que en suelos húmedos. Segundo, la arqueología del desierto tiene menos 'ruido' biológico: no hay raíces de árboles ni actividad agrícola moderna que enmascare las señales de las estructuras antiguas. Esto hace de Egipto uno de los mejores laboratorios del mundo para probar nuevas técnicas de detección remota.",
  "Las imágenes del satélite LandSat de la NASA han revelado el sistema completo de canales del Nilo en la antigüedad. El Nilo moderno tiene solo dos brazos principales (en el delta), pero hace 4,000 años tenía siete brazos diferentes. Los canales antiguos, ahora secos, son visibles desde el espacio como ligeras variaciones en el color del suelo. Estas imágenes permiten a los arqueólogos entender por qué las ciudades antiguas estaban donde estaban: siempre junto a los brazos del Nilo de su época.",
  "La tecnología LiDAR (Light Detection and Ranging), usada en Egipto desde aviones especiales, usa pulsos de láser para medir la topografía del terreno con centímetros de precisión. En Camboya, LiDAR descubrió la ciudad perdida de Mahendraparvata bajo la selva, más grande que la ciudad moderna de Phnom Penh. En Egipto, LiDAR ha revelado sistemas de canales y muros de contención en el delta del Nilo que eran completamente desconocidos. Cada vuelo de LiDAR descubre sitios que los arqueólogos tardarían décadas en encontrar manualmente.",
  "Google Earth democratizó la arqueología satelital. Antes de 2005, acceder a imágenes satelitales de alta resolución requería contratos millonarios con empresas especializadas. Con Google Earth, cualquier persona con computadora puede examinar el planeta con imágenes de metros de resolución. Aficionados de todo el mundo han identificado miles de sitios arqueológicos potenciales en Google Earth, muchos de ellos confirmados posteriormente por arqueólogos profesionales. La ciencia ciudadana está acelerando el descubrimiento del pasado.",
  "La misión CORONA de la CIA (1960-1972) fue el primer programa de satélites espía de la historia. Durante años 60 y 70, tomó fotos de alta resolución del mundo desde el espacio. Aunque fue diseñado para espiar a la Unión Soviética, sus fotografías del Medio Oriente han demostrado ser un tesoro arqueológico: muestran el estado de los sitios antes de la urbanización moderna y la agricultura intensiva. Los arqueólogos de hoy usan las fotografías CORONA desclasificadas para ver cómo lucían los sitios hace 60 años.",
  "Un descubrimiento reciente especialmente emocionante fue realizado en 2020 por el proyecto ScanPyramids: usando muones cósmicos (partículas subatómicas que penetran la roca como radiografías), el equipo confirmó la existencia de un corredor oculto de 9 metros de largo en el interior de la Gran Pirámide de Keops, justo debajo de la famosa hendidura en la fachada norte. En marzo de 2023, se introdujeron endoscopios por grietas existentes y se fotografió el interior: un corredor vacío, con paredes de caliza y techo abovedado, que nunca había sido visto por ojos humanos modernos.",
  "El proyecto JAXA/ESA de mapeo del subsuperficial terrestre con radar desde satélites ha identificado un gran lago subterráneo debajo de las mesetas de Guiza. Este lago, a unos 30 metros de profundidad, podría haber sido una fuente de agua para los miles de obreros que construyeron las pirámides. Confirmar su existencia y conectarlo con la logística de construcción de las pirámides es uno de los proyectos arqueológicos más emocionantes del mundo actualmente.",
  "La arqueología espacial también ayuda a proteger el patrimonio arqueológico de Egipto. Los satélites pueden detectar saqueos nocturnos: los campos del desierto donde han aparecido cráteres de excavaciones ilegales son claramente visibles en las imágenes satelitales tomadas con días de diferencia. Este monitoreo satelital permite alertar a las autoridades egipcias rápidamente y ha contribuido a reducir el saqueo de sitios arqueológicos no excavados.",
  "Los satélites también se usan para monitorear el estado de conservación de los sitios ya conocidos. El templo de Karnak, el sitio arqueológico más grande del mundo (200 hectáreas), es monitoreado constantemente desde el espacio. Los cambios en los niveles del agua subterránea (que pueden causar la salinización y degradación de las piedras), los cambios en el albedo superficial (que indican desecación o humedad excesiva) y los movimientos de tierras no autorizados son detectados automáticamente por algoritmos de inteligencia artificial que analizan las imágenes satelitales.",
  "El gran mensaje de la arqueología espacial es que el cielo, que los egipcios miraban desde abajo buscando pistas sobre el universo, ahora nos mira desde arriba y nos revela sus propios secretos. Los satélites son los ojos de nuestra civilización proyectados al espacio, mirando hacia abajo hacia la Tierra con la misma curiosidad con que los astrónomos del Nilo miraban hacia arriba al cosmos. En un sentido profundo, los satélites modernos son los 'Decanos tecnológicos' del siglo XXI: instrumentos de observación que, como las estrellas de los relojes estelares egipcios, revelan verdades ocultas a quienes saben leerlos."
];

const egypt_m15_quiz = [
  { "q": "¿Qué es la arqueología espacial?", "options": ["Arqueología en Marte", "Uso de satélites para detectar sitios arqueológicos en la Tierra", "Buscar naves espaciales antiguas", "Excavar en la Luna"], "a": 1 },
  { "q": "¿Cuántas posibles pirámides perdidas detectó Sarah Parcak con satélites?", "options": ["3", "7", "17", "100"], "a": 2 },
  { "q": "¿Qué tecnología usa pulsos de láser para mapear el terreno?", "options": ["SAR", "LiDAR", "GPS", "Infrarrojo"], "a": 1 },
  { "q": "¿Qué descubrió el proyecto ScanPyramids en 2023 dentro de la Gran Pirámide?", "options": ["Un tesoro de oro", "Un corredor oculto de 9 metros", "Una momia desconocida", "Una sala con jeroglíficos"], "a": 1 },
  { "q": "¿Cómo ayudan los satélites a proteger los sitios arqueológicos egipcios?", "options": ["Lanzando rayos a los saqueadores", "Detectando saqueos nocturnos como cráteres en el suelo", "Enviando policías espaciales", "Cubriendo los sitios con energía"], "a": 1 }
];

src = replaceSection(src, 'egypt_m13', egypt_m13_paragraphs, egypt_m13_quiz);
src = replaceSection(src, 'egypt_m14', egypt_m14_paragraphs, egypt_m14_quiz);
src = replaceSection(src, 'egypt_m15', egypt_m15_paragraphs, egypt_m15_quiz);

fs.writeFileSync(FILE, src, 'utf8');
console.log('Done writing file.');
