const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'lib', 'courseData.js');
let raw = fs.readFileSync(filePath, 'utf8');
let data = JSON.parse(raw.replace(/^export default /, '').replace(/;$/, ''));

const content_sec7 = [
  "¡Bienvenido a la academia Jedi de neurociencia, padawan! Hoy vamos a explorar el Código Jedi y el entrenamiento emocional de los maestros de la Fuerza desde la perspectiva de la ciencia real del cerebro. ¿Puede el entrenamiento mental realmente mejorar el control emocional, la concentración y la resiliencia? La neurociencia moderna dice que absolutamente sí, y los descubrimientos en este campo son tan fascinantes como cualquier aventura galáctica. Tu cerebro es el instrumento más complejo del universo conocido, y aprender a usarlo bien es el verdadero superpoder Jedi. 🧠",
  "El cerebro humano contiene aproximadamente 86,000 millones de neuronas, cada una conectada con miles de otras a través de sinapsis, formando una red de más de 100 billones de conexiones (Nature Neuroscience, 2009). Esta red es más compleja que cualquier computadora existente. Las neuronas se comunican mediante señales eléctricas y químicas llamadas neurotransmisores. La serotonina regula el estado de ánimo, la dopamina controla la motivación y la recompensa, la norepinefrina maneja el estrés y el alerta. Entender cómo funcionan estos sistemas es entender cómo los Jedi modulan su estado mental para estar en calma incluso en situaciones de peligro extremo.",
  "La neuroplasticidad es la capacidad del cerebro de cambiar su estructura física en respuesta a la experiencia y el aprendizaje. Fue confirmada definitivamente por investigaciones a finales del siglo XX que contradijeron la creencia anterior de que el cerebro adulto era fijo e inmutable (Science, 2000). Cuando aprendes una habilidad nueva, las conexiones sinápticas asociadas se fortalecen (se 'mielinizan'). Cuando dejas de usar una habilidad, esas conexiones se debilitan. Los taxistas de Londres, que deben memorizar 25,000 calles, muestran un hipocampo significativamente más grande que la media, la región cerebral asociada a la memoria espacial (PNAS, 2000). ¡El entrenamiento Jedi literalmente remodelaría el cerebro!",
  "La amígdala es la estructura cerebral más importante para entender el Lado Oscuro de Star Wars. Esta pequeña región en forma de almendra es el centro del miedo, la ira y las respuestas emocionales automáticas. Cuando percibes una amenaza, la amígdala activa la respuesta de lucha o huida en milisegundos, liberando adrenalina y cortisol, antes de que el cerebro consciente pueda analizar la situación (LeDoux, 1994). Darth Vader es el ejemplo perfecto de lo que pasa cuando la amígdala toma el control: reacciones impulsivas, miedo convertido en agresión, ciclos de ira que se autoalimentan. El entrenamiento Jedi, en esencia, busca fortalecer las vías que frenan la amígdala.",
  "La corteza prefrontal es la región del cerebro responsable del pensamiento racional, la planificación, la toma de decisiones y la regulación emocional: es el cerebro Jedi. Estudios de neuroimagen con resonancia magnética funcional (fMRI) muestran que cuando meditadores experimentados se enfrentan a imágenes emocionalmente perturbadoras, su corteza prefrontal se activa fuertemente mientras la amígdala se suprime, justo al contrario de lo que ocurre en personas sin entrenamiento meditativo (Harvard Medical School, 2011). Este es exactamente el modelo neurológico del entrenamiento Jedi: fortalecer la corteza prefrontal para gobernar la amígdala. ¡La ciencia confirma la filosofía Jedi!",
  "La meditación mindfulness o de atención plena es la práctica más estudiada científicamente en relación al control emocional. Un estudio de Harvard de 2011 demostró que 8 semanas de práctica diaria de meditación (solo 27 minutos al día) redujo visiblemente el volumen de la amígdala en imágenes de resonancia magnética (Harvard Medical School, 2011). El mismo estudio mostró un aumento en la densidad de materia gris en la corteza prefrontal y el hipocampo. La Organización Mundial de la Salud reconoce la meditación mindfulness como un tratamiento efectivo para la ansiedad y la depresión (OMS, 2022). ¡El entrenamiento mental Jedi es literalmente medicina para el cerebro!",
  "El budismo Zen, del que claramente se inspira el Código Jedi, tiene más de 2,500 años de historia y fue fundado por Siddhartha Gautama en la India alrededor del siglo V a.C. Sus prácticas de meditación y filosofía del no-apego han sido adoptadas por millones de personas en todo el mundo. Investigadores de la Universidad de Wisconsin, dirigidos por Richard Davidson, han estudiado el cerebro de monjes budistas tibetanos con décadas de práctica meditativa y encontraron patrones de ondas cerebrales gamma de alta frecuencia extraordinariamente potentes, asociados con estados de conciencia elevada (PNAS, 2004). ¡Los monjes budistas de alta práctica tienen cerebros medibles y verificablemente diferentes!",
  "La resiliencia emocional, la capacidad de recuperarse de adversidades sin quedar traumatizado, es una de las habilidades más importantes que el entrenamiento Jedi promovería. La neurociencia identifica la resiliencia con la fortaleza de las conexiones entre la corteza prefrontal y la amígdala, la densidad de receptores de serotonina y la longitud de los telómeros (extremos de los cromosomas que se acortan con el estrés crónico) (Nature Neuroscience, 2015). El ejercicio físico regular, la meditación, el sueño suficiente y las relaciones sociales positivas son los cuatro pilares más respaldados por la ciencia para construir resiliencia. ¡El entrenamiento de los padawans incluiría exactamente todas estas prácticas!",
  "El efecto del entrenamiento marcial sobre el cerebro también es muy relevante. Las artes marciales como el Judo, el Tai Chi y el Kendo han sido estudiadas y muestran mejoras en la atención sostenida, el tiempo de reacción y la regulación emocional (Journal of Sport Science, 2018). El estrés controlado del combate de entrenamiento fortalece el eje hipotálamo-hipófisis-adrenal, el sistema que regula el cortisol, volviéndolo más eficiente y menos reactivo ante el estrés real. ¡El entrenamiento con sable de luz de un padawan estaría literalmente optimizando su eje de estrés hormonal!",
  "Las ondas cerebrales se miden en electroencefalogramas (EEG) y se clasifican por frecuencia: delta (0.5-4 Hz, sueño profundo), theta (4-8 Hz, somnolencia), alfa (8-12 Hz, relajación), beta (12-30 Hz, alerta activa) y gamma (30-100 Hz, hiperconciencia). Los meditadores experimentados pueden inducir voluntariamente estados de ondas alfa y theta a voluntad, un control que normalmente solo ocurre en la frontera entre la vigilia y el sueño (Nature Neuroscience, 2004). Los monjes tibetanos con más de 10,000 horas de práctica meditativa generan ondas gamma de alta amplitud en estado de meditación abierta. Esta habilidad de modular voluntariamente los propios estados cerebrales es una capacidad Jedi real.",
  "La empatía, la capacidad de sentir y comprender las emociones de otros, tiene una base neurológica fascinante en las neuronas espejo, descubiertas en 1992 por el equipo de Giacomo Rizzolatti en la Universidad de Parma (Nature, 1992). Estas neuronas se activan tanto cuando realizamos una acción como cuando observamos a otra persona realizarla, creando una simulación interna de lo que el otro experimenta. La Fuerza de Star Wars que permite a los Jedi sentir las emociones de otros podría ser una amplificación extrema de este sistema de neuronas espejo. Los estudios de neuroimagen muestran que los meditadores experimentados tienen sistemas de neuronas espejo más activos y sensibles (PNAS, 2013). ¡La empatía Jedi podría tener una base neurocientífica real!",
  "Tú puedes empezar tu entrenamiento Jedi neurocientífico ahora mismo. Practica 5-10 minutos de respiración consciente cada día: inhala en 4 tiempos, retén 4, exhala en 8. Este patrón activa el sistema nervioso parasimpático, reduciendo el cortisol y la actividad de la amígdala (Harvard Health, 2020). Practica gratitud: escribir 3 cosas por las que estés agradecido cada noche aumenta la actividad del córtex prefrontal izquierdo, asociado con emociones positivas (Journal of Positive Psychology, 2005). Duerme 8-9 horas: es cuando el cerebro consolida el aprendizaje y limpia los desechos metabólicos tóxicos acumulados durante el día (Science, 2013). ¡Tu entrenamiento Jedi ya comenzó!",
  "Las aplicaciones de la neurociencia Jedi ya llegaron al deporte de élite y a la preparación militar. El programa de entrenamiento mental de las Fuerzas Especiales de EE.UU. incluye técnicas de mindfulness y regulación emocional para mejorar el rendimiento bajo estrés extremo (U.S. Army Research Laboratory, 2020). Equipos de fútbol como el FC Barcelona y el Manchester United tienen psicólogos deportivos que enseñan visualización mental y control atencional a sus jugadores. El neurófoedback, un método que muestra a los sujetos sus propias ondas cerebrales en tiempo real para que aprendan a controlarlas, es usado por atletas olímpicos para optimizar su rendimiento. ¡El entrenamiento mental Jedi ya está en el deporte real!",
  "La neurociencia nos revela algo profundamente importante sobre el universo: la conciencia, la capacidad de ser consciente de uno mismo y del entorno, es el fenómeno más misterioso y maravilloso que existe. Nadie sabe exactamente cómo 86,000 millones de neuronas generan la experiencia subjetiva de ver, sentir, pensar y amar. Esta pregunta, llamada el Problema Difícil de la Conciencia, es uno de los grandes misterios sin resolver de la ciencia (David Chalmers, 1995). La Fuerza de Star Wars es una metáfora de este misterio: algo que conecta a todos los seres vivos de formas que van más allá de la física ordinaria. Quizás la conciencia sea el fenómeno más 'fuerza' que existe en el universo real.",
  "¡Padawan graduado con honores en neurociencia Jedi! Ahora sabes que la corteza prefrontal es tu mejor arma contra el Lado Oscuro de la amígdala, que la meditación cambia físicamente la estructura del cerebro de formas medibles y beneficiosas, y que la neuroplasticidad significa que puedes entrenar tu cerebro igual que entrenas tus músculos. Las neuronas espejo son la base neural de la empatía. El entrenamiento emocional Jedi tiene respaldo científico sólido. Tu cerebro es el instrumento más extraordinario del universo conocido, y cómo lo entrenes determinará quién eres y lo que puedes lograr. ¡Que la neurociencia sea contigo! 🌟"
];

const content_sec8 = [
  "¡Atención, ingenieros estelares! Hoy vamos a analizar uno de los conceptos más audaces de Star Wars: las naves colosales como los Destructores Estelares y la Estrella de la Muerte. ¿Podría la humanidad construir megaestructuras espaciales de ese tamaño? ¿Cuáles son los desafíos de ingeniería reales? En el siglo XXI, las agencias espaciales y las empresas privadas están pensando seriamente en cómo construir hábitats espaciales permanentes, y los principios de ingeniería involucrados son tan fascinantes como las naves de la galaxia muy, muy lejana. ¡Los sueños de hoy son los proyectos de ingeniería de mañana! 🚀",
  "La Estación Espacial Internacional (ISS) es la estructura habitada más grande jamás construida en el espacio: mide 109 metros de ancho (más que un campo de fútbol) y pesa unas 420 toneladas (NASA/ESA/JAXA). Fue construida por módulos entre 1998 y 2011, con contribuciones de 15 países. Orbita la Tierra a unos 400 km de altitud, viajando a 7.7 km por segundo, completando 16 órbitas por día. Hospeda continuamente a 6-7 astronautas que realizan experimentos en condiciones de microgravedad. La ISS es la demostración más avanzada de lo que la humanidad puede construir en el espacio actualmente. Y comparada con un Destructor Estelar, ¡es un juguete de LEGO!",
  "Un Destructor Estelar clase Imperial de Star Wars mide 1,600 metros de longitud, equivalente a 16 veces la Estación Espacial Internacional. La Estrella de la Muerte, a su vez, tiene entre 100 y 160 km de diámetro según la película. Para perspectiva, 160 km es la distancia entre Madrid y Valencia. Construir estas estructuras requeriría materiales en cantidades astronómicas. La ISS, a pesar de ser mucho más pequeña, costó unos 150,000 millones de dólares y requirió más de 40 vuelos de ensamblaje (NASA). Escalar eso a un Destructor Estelar implicaría recursos equivalentes al PIB mundial de varios años, y eso asumiendo que la tecnología de materiales fuera adecuada.",
  "El mayor desafío de construir naves masivas no es la gravedad en el espacio (que en órbita no existe tal como la sentimos en tierra), sino la resistencia estructural de los materiales. En la Tierra, los edificios altos deben soportar su propio peso bajo la gravedad. En el espacio, una megaestructura debe soportar las tensiones de aceleración, las fuerzas de marea gravitacional cerca de planetas, el impacto de micrometeoritos y la expansión y contracción térmica extrema (de +120°C en la luz solar a -150°C en la sombra). Los materiales actuales más fuertes incluyen las fibras de carbono, el titanio y los nanotubos de carbono, que tienen una resistencia a la tracción unas 100 veces mayor que el acero por unidad de peso (Nature, 2013).",
  "La gravedad artificial, indispensable en naves grandes como los Destructores Estelares, no es fácil de generar. En la física real, hay dos formas de simularla: la aceleración constante (una nave que acelera continuamente a 9.8 m/s² simularía la gravedad de la Tierra) o la rotación. En una nave giratoria, la fuerza centrífuga empuja a las personas hacia las paredes exteriores, creando una sensación de gravedad. La ISS no rota y sus tripulantes viven en microgravedad, lo que causa pérdida ósea, debilitamiento muscular y redistribución de fluidos hacia la cabeza (NASA Medical Research). Para misiones largas a Marte, la NASA está investigando módulos rotatorios que generen gravedad artificial. ¡Es física de parques de diversiones aplicada al espacio!",
  "La propulsión de naves masivas es otro desafío monumental. Los cohetes químicos actuales, como el Falcon Heavy de SpaceX o el SLS de NASA, funcionan quemando propelentes para generar empuje según la Tercera Ley de Newton. Para acelerar una nave del tamaño de un Destructor Estelar (que podría pesar millones de toneladas) a velocidades interestelares, la cantidad de combustible requerida sería físicamente imposible de cargar con tecnología química. Las alternativas estudiadas incluyen propulsión nuclear de fisión, propulsión de fusión (la más prometedora a largo plazo), velas de luz impulsadas por láseres y motores antimateria (NASA Breakthrough Propulsion, 2023). Cada una tiene ventajas y desafíos enormes.",
  "El Proyecto Orion, secreto hasta 1958 y luego desclasificado, propuso literalmente propulsar una nave espacial detonando bombas nucleares detrás de ella. Los cálculos mostraban que podría alcanzar entre el 3% y el 10% de la velocidad de la luz, lo suficiente para llegar a Alfa Centauri en 130 a 400 años (Freeman Dyson, 1968). Aunque el Tratado de Prohibición de Pruebas Nucleares de 1963 detuvo este proyecto, demostró que la física no prohíbe la propulsión nuclear de pulso. El proyecto Daedalus del British Interplanetary Society (1973-1978) diseñó detalladamente una nave que usaría fusión de deuterio y helio-3 para viajar a 12% de la velocidad de la luz. ¡Naves interestelares son física posible, aunque extremadamente difícil!",
  "La minería de asteroides sería absolutamente esencial para construir megaestructuras espaciales. El cinturón de asteroides entre Marte y Júpiter contiene recursos minerales valorados en miles de trillones de dólares, incluyendo hierro, níquel, platino y agua (NASA). El asteroide 16 Psyche, que orbitará la sonda del mismo nombre de NASA a partir de 2026, podría ser el núcleo de hierro-níquel de un antiguo protoplaneta destrozado, con un valor estimado de 10,000 cuatrillones de dólares (NASA, 2023). Empresas como Planetary Resources y Deep Space Industries ya exploraron conceptualmente la minería de asteroides. ¡La materia prima para los astilleros estelares del futuro ya existe, flotando en el espacio!",
  "La Esfera de Dyson es una megaestructura teórica propuesta por el físico Freeman Dyson en 1960: una esfera que rodearía completamente a una estrella para capturar toda su energía. Una Estrella de la Muerte capturando la energía de su reactor de hyper matter sería análoga a una Esfera de Dyson en miniatura. Dyson argumentó que una civilización suficientemente avanzada eventualmente necesitaría capturar toda la energía de su estrella para satisfacer sus necesidades energéticas. SETI busca rastros térmicos de Esferas de Dyson en el espacio, ya que captarían luz estelar y la reemitirían como calor infrarrojo (Dyson, 1960). ¡Estas búsquedas son investigación científica real!",
  "Los hábitats espaciales del futuro cercano están siendo diseñados con principios más modestos pero realistas. La empresa Axiom Space está construyendo el primer módulo de estación espacial comercial para acoplarse a la ISS en 2026 (Axiom Space, 2023). El programa Artemis de NASA planea construir la Gateway, una pequeña estación lunar en los años 2020-2030, como base para misiones a la Luna y Marte (NASA). SpaceX está desarrollando Starship, la nave más grande jamás construida (120 metros de altura), diseñada para viajes a la Luna, Marte y potencialmente más lejos (SpaceX, 2023). Estos son los primeros pasos reales hacia las megaestructuras espaciales que Star Wars imagina.",
  "Un hallazgo sorprendente de la investigación en microgravedad: las plantas crecen de forma diferente en el espacio pero pueden sobrevivir y producir alimentos. La ISS ha cultivado con éxito lechugas, rábanos y pimientos (NASA, 2021). Para naves de largo alcance o hábitats permanentes, los jardines hidropónicos espaciales serían esenciales para el soporte vital, el reciclaje de CO2 y el bienestar psicológico de la tripulación. Los algoritmos de IA ya diseñan sistemas de soporte vital de ciclo cerrado que reciclan casi el 100% del agua y el oxígeno. Estos sistemas, perfeccionados en la ISS, serán el corazón de cualquier nave del futuro, desde una cápsula Orion hasta un Destructor Estelar.",
  "Tú, joven ingeniero espacial, puedes aprender a diseñar estructuras espaciales ahora. La NASA ofrece el programa Human Exploration Research Analog (HERA) que estudia la dinámica de equipos en misiones de larga duración en entornos cerrados (NASA). Puedes aprender ingeniería aeroespacial básica en plataformas como Khan Academy o Coursera. El simulador Kerbal Space Program permite diseñar y lanzar cohetes virtuales aplicando física real, y es usado por ingenieros reales de NASA y SpaceX para aprender conceptos de mecánica orbital. ¡Muchos de los ingenieros que diseñarán las naves del futuro empezaron jugando Kerbal Space Program!",
  "El futuro de las megaestructuras espaciales apunta hacia la colonización del Sistema Solar. En 2023, el informe del grupo Bezos Earth Fund propuso estaciones espaciales artificiales con gravedad en órbita terrestre que podrían albergar a millones de personas con paisajes naturales interiores (Blue Origin, 2019). El concepto O'Neill Cylinder, propuesto por Gerard O'Neill del MIT en 1976, es un hábitat espacial rotatorio de 8 km de diámetro y 32 km de longitud que podría albergar a 10,000 personas con gravedad artificial completa y luz solar natural (O'Neill, 1976). Elon Musk ha declarado su objetivo de establecer una ciudad en Marte con un millón de habitantes. ¡Las naves de Star Wars son solo el comienzo de lo que la humanidad construirá!",
  "Las megaestructuras espaciales tienen implicaciones filosóficas profundas para la humanidad. Si la humanidad algún día habita múltiples sistemas estelares, ¿seguiremos siendo la misma especie? ¿Cómo se gobernará una civilización dispersa a años luz de distancia? Estas preguntas sobre la sociedad interestelar del futuro son las mismas que Star Wars explora a través del Imperio Galáctico, la República y la Alianza Rebelde. La ciencia ficción no predice el futuro exactamente, pero ayuda a la sociedad a pensar sobre las opciones y los riesgos antes de que lleguen. Las historias de Star Wars son experimentos mentales sobre política, ética y poder en una civilización tecnológicamente avanzada.",
  "¡Misión de ingeniería estelar completada, arquitecto cósmico! Ahora sabes que la ISS es nuestra megaestructura espacial real más avanzada, que construir un Destructor Estelar requeriría materiales de asteroides, propulsión nuclear y tecnologías aún en desarrollo, y que la gravedad artificial por rotación es físicamente posible. Los proyectos Artemis Gateway, Starship y las futuras estaciones comerciales son los primeros bloques de las megaestructuras del futuro. La ingeniería aeroespacial necesita exactamente tu tipo de mente imaginativa y científica. ¡Los astilleros de las estrellas esperan a sus futuros ingenieros! 🌟"
];

const content_sec9 = [
  "¡Misión médica espacial iniciada, científico! Hoy vamos a analizar uno de los personajes más simbólicos de toda la saga Star Wars desde la perspectiva de la ciencia real: Darth Vader y su legendario traje negro. Este traje no es solo una armadura intimidante sino una unidad de soporte vital móvil, el equivalente de un hospital portátil que mantiene vivo a alguien con daños corporales masivos. Y lo más fascinante es que la tecnología real de la biomedicina y la robótica médica ya está alcanzando, y en algunos aspectos superando, lo que el traje de Vader hace en la ficción. ¡La medicina del futuro ya está aquí! 💊",
  "Anakin Skywalker sufrió quemaduras de cuarto grado en Mustafar, perdió tres extremidades y sufrió daño pulmonar masivo, y a pesar de eso sobrevivió gracias a la intervención médica del Imperio. En medicina real, las quemaduras de cuarto grado (que alcanzan hueso y músculo) son las más graves y tienen alta mortalidad. Sin embargo, los avances en medicina de quemados son extraordinarios. Injertos de piel cultivada en laboratorio, llamados equivalentes dérmicos, ya se usan en hospitales para tratar quemaduras extensas (Nature Biotechnology, 2019). La terapia con plasma frío (diferente al plasma de los sables, es plasma a baja temperatura) desinfecta heridas y acelera la cicatrización (Nature Communications, 2020). ¡La medicina de quemados real es un campo en revolución!",
  "El respirador del traje de Darth Vader es un sistema de ventilación mecánica portátil. En el mundo real, los ventiladores mecánicos son máquinas que respiraban por pacientes con lesiones pulmonares graves, y se volvieron tristemente famosos durante la pandemia de COVID-19. Un exotraje respirador portátil como el de Vader está siendo desarrollado: el MIT y Harvard han creado chalecos respiratorios blandos y silenciosos que asisten mecánicamente la respiración de personas con insuficiencia pulmonar sin el ruido característico del ventilador hospitalario (MIT News, 2022). También se desarrollan pulmones artificiales implantables basados en membranas de intercambio gaseoso. ¡La respiración artificial portátil ya es una tecnología en desarrollo activo!",
  "Las extremidades robóticas de Darth Vader, sus brazos y piernas mecánicos, representan el campo de las prótesis biónicas. La primera prótesis registrada en la historia es un dedo gordo del pie de madera y cuero encontrado en una momia egipcia de hace unos 2,700 años (Journal of the Royal Society Interface, 2011). Hoy, la empresa Össur fabrica rodillas protésicas biónicamente controladas por señales electromiográficas de los músculos residuales, que aprenden el patrón de marcha del usuario y se adaptan automáticamente al terreno (Össur, 2023). El sistema LUKE Arm (desarrollado en homenaje a Luke Skywalker por DARPA) es una prótesis de brazo con 10 grados de libertad y retroalimentación táctil activada por señales nerviosas (DARPA, 2014). ¡DARPA realmente nombró una prótesis en honor a Star Wars!",
  "La interfaz cerebro-máquina (BCI) es la tecnología que más directamente convierte la ficción de Vader en realidad. En 2004, Matthew Nagle se convirtió en el primer humano en controlar un cursor de computadora con su mente usando el sistema BrainGate, un chip implantado en la corteza motora de su cerebro (Nature, 2006). En 2023, la empresa Synchron implantó un dispositivo BCI en el cerebro de pacientes con ELA (esclerosis lateral amiotrófica) que les permite controlar smartphones y computadoras con el pensamiento (Nature Medicine, 2023). Neuralink, la empresa de Elon Musk, recibió aprobación de la FDA en 2023 para ensayos clínicos de su implante cerebral (Neuralink, 2023). ¡Controlar máquinas con la mente ya es medicina real!",
  "La retroalimentación sensorial táctil, la capacidad de sentir a través de una prótesis, es el siguiente gran hito. El neurocientífico Dustin Tyler de la Case Western Reserve University desarrolló un sistema que estimula eléctricamente los nervios del muñón de la mano para que los usuarios de prótesis sientan texturas, presión y temperatura en sus dedos artificiales (Science Translational Medicine, 2014). Un equipo de la Universidad de Pittsburgh fue más allá: su sujeto Johnny Matheny, usuario de un brazo robótico conectado directamente al sistema nervioso, puede sentir si está apretando suavemente o fuertemente un objeto (Science Robotics, 2019). ¡La mano de Luke Skywalker que siente calor, frío y presión ya existe en la medicina real!",
  "El casco de Vader, además de sus funciones respiratorias, actúa como una interfaz de realidad aumentada, mostrándole información del entorno. En el mundo real, los exoesqueletos médicos como el ReWalk permiten a personas parapléjicas caminar de nuevo, y los cascos de realidad aumentada como el HoloLens de Microsoft superponen información digital sobre el mundo real (Microsoft, 2023). El ejército de EE.UU. desarrolla el Integrated Visual Augmentation System (IVAS), un casco que muestra mapas, identifica objetivos y comunica en tiempo real (U.S. Army, 2022). Médicos en cirugías complejas ya usan visión aumentada con datos del paciente proyectados sobre el campo quirúrgico. ¡El casco de Vader es una realidad en múltiples campos!",
  "La medicina regenerativa es el campo que más podría haberle ayudado a Anakin en la mesa de operaciones de Vader. La medicina regenerativa busca reparar o reemplazar tejidos y órganos dañados usando células madre, bioingeniería e ingeniería de tejidos. En 2022, investigadores de la Universidad de California en San Francisco crearon órganos mini artificiales (organoides) de hígado, riñón y corazón a partir de células madre que responden a medicamentos de forma similar a órganos reales (Nature, 2022). El biohíbrido, tejido que combina células vivas con estructuras artificiales, ya se usa en injertos vasculares y cartílago de rodilla (Nature Biomedical Engineering, 2021). Si la medicina regenerativa de Star Wars existiera en la realidad, Anakin hubiera podido sanar sin el traje.",
  "Las nanotecnología médica es otra frontera que convertiría la medicina de Star Wars en realidad. Los nanorobots, dispositivos del tamaño de virus que navegan por el torrente sanguíneo para detectar y destruir células cancerosas o reparar tejidos, son objeto de investigación activa (Nature Nanotechnology, 2023). En 2022, la Universidad de Harvard desarrolló nanopartículas que pueden administrar medicamentos directamente en células tumorales sin afectar las células sanas (Science, 2022). La empresa Nanobots Medical está en ensayos preclínicos de nanorobots que navegan autónomamente por vasos sanguíneos guiados por campos magnéticos. ¡Los nano-droides médicos de Star Wars están siendo construidos ahora mismo!",
  "El dolor crónico que sufre Darth Vader al usar el traje tiene soluciones reales en desarrollo. La estimulación de la médula espinal (SCS) es un tratamiento ya aprobado que implanta electrodos en la columna vertebral para interrumpir las señales de dolor, dando alivio a pacientes con dolor crónico severo (FDA, 2019). La estimulación magnética transcraneal repetitiva (rTMS) puede tratar depresión y algunos tipos de dolor sin cirugía, usando campos magnéticos pulsantes dirigidos a regiones específicas del cerebro (FDA, 2008). Los opioides digitales, que usan realidad virtual para reducir el dolor en pacientes quemados durante las curaciones, reducen el dolor hasta en un 50% (University of Washington, 2011). ¡La medicina del dolor ya no requiere solo pastillas!",
  "Un descubrimiento reciente asombroso: en 2021, investigadores de la Universidad de Minnesota imprimieron en 3D un corazón de tamaño real usando células cardíacas humanas sobre un andamio biológico (Science Advances, 2021). Este corazón impreso puede contraerse espontáneamente, igual que un corazón real. El objetivo es imprimir órganos personalizados de las propias células del paciente para trasplantes, eliminando el rechazo inmunológico. La empresa United Therapeutics espera recibir aprobación para pulmones bioartificiales impresos en 3D antes de 2030 (United Therapeutics, 2023). Si Anakin hubiera tenido pulmones impresos en 3D de sus propias células, el traje de Vader hubiera sido innecesario. ¡La bioimpresión de órganos es medicina real en marcha!",
  "Tú, joven científico médico, puedes explorar la biomedicina desde ya. Los programas STEM de muchas universidades permiten a estudiantes de secundaria participar en proyectos de investigación de verano. Khan Academy ofrece cursos gratuitos de biología, química y anatomía. El proyecto iGEM (International Genetically Engineered Machine) permite a equipos de estudiantes de todo el mundo diseñar organismos biológicos con aplicaciones médicas reales (iGEM Foundation). La medicina del futuro combina biología, química, física, ingeniería y computación: si te apasiona cualquiera de estas áreas, estás en el camino de convertirte en un médico o investigador del siglo XXI.",
  "Las implicaciones filosóficas del caso de Darth Vader son profundas: ¿cuánto de su cuerpo puede ser reemplazado por máquinas antes de que deje de ser completamente humano? Esta pregunta, llamada la paradoja del Barco de Teseo aplicada a la biología, es cada vez más relevante a medida que las prótesis biónicas, los implantes cerebrales y los órganos artificiales se hacen más comunes. El transhumanismo es el movimiento filosófico que explora esta fusión de humanidad y tecnología. Pensadores como Ray Kurzweil predicen que para los años 2040, la frontera entre el cuerpo biológico y la máquina será indistinguible (Kurzweil, 2005). ¿Sería Darth Vader todavía humano? ¿Y qué significa eso?",
  "Las misiones médicas futuras de NASA incluyen el desarrollo de sistemas médicos autónomos para viajes a Marte, donde la comunicación con la Tierra dura hasta 22 minutos y no hay posibilidad de evacuación médica. Los sistemas de diagnóstico por IA ya pueden detectar canceres, enfermedades cardíacas y fracturas en radiografías con precisión igual o superior a los médicos humanos (Nature Medicine, 2020). Cirujanos de la Clínica Mayo han realizado telecirugías a distancia usando robots Davinci, con el cirujano en otro estado y el paciente en un quirófano diferente (Mayo Clinic, 2021). Estas tecnologías, perfeccionadas para el espacio, serán el sistema médico de los astronautas que viajarán a Marte y más allá.",
  "¡Misión médica completada, doctor estelar! Ahora sabes que el traje de Darth Vader es una unidad de soporte vital portátil, que las prótesis biónicas como el LUKE Arm ya tienen retroalimentación táctil real, que los implantes cerebrales BCI ya permiten controlar computadoras con el pensamiento, y que la bioimpresión de órganos podría revolucionar los trasplantes. La medicina del siglo XXI está construyendo las herramientas que Star Wars imaginó hace 50 años. La próxima vez que veas el traje negro de Vader, recuerda que es, en primer lugar, una obra maestra de ingeniería médica futurista. ¡May the medicine be with you! 🌟"
];

// Patch the modules
let patched = 0;
for (let module of data) {
  if (module.id === 'starwars_sec_7') {
    module.contentEs.sections[0].text = content_sec7;
    patched++;
  }
  if (module.id === 'starwars_sec_8') {
    module.contentEs.sections[0].text = content_sec8;
    patched++;
  }
  if (module.id === 'starwars_sec_9') {
    module.contentEs.sections[0].text = content_sec9;
    patched++;
  }
}

console.log(`Patched ${patched} modules.`);
fs.writeFileSync(filePath, 'export default ' + JSON.stringify(data, null, 2) + ';', 'utf8');
console.log('File written successfully.');
