const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'lib', 'courseData.js');
let raw = fs.readFileSync(filePath, 'utf8');
let data = JSON.parse(raw.replace(/^export default /, '').replace(/;$/, ''));

const content_sec4 = [
  "¡Alerta de experimento cuántico, explorador científico! Hoy vamos a explorar una de las ideas más extrañas y fascinantes de toda la física: el entrelazamiento cuántico. Y lo vamos a conectar con el concepto de la Fuerza de Star Wars, ese misterioso campo energético que conecta a todos los seres vivos de la galaxia. ¿Pueden las partículas realmente estar 'conectadas' a distancia, como los Jedi a través de la Fuerza? La respuesta de la física cuántica es sí... pero de una manera muy particular. ¡Prepárate para que tu mente se doble como el espacio-tiempo! 🌌",
  "El entrelazamiento cuántico es un fenómeno donde dos partículas quedan conectadas de tal forma que el estado de una instantáneamente influye en el estado de la otra, sin importar la distancia entre ellas. Fue descrito matemáticamente por Einstein, Podolsky y Rosen en 1935, en lo que se conoce como la Paradoja EPR (Physical Review, 1935). Einstein lo llamó 'acción fantasmal a distancia' y le parecía tan absurdo que pensó que debía haber un error en la mecánica cuántica. Sin embargo, los experimentos de Alain Aspect en 1982 demostraron que el entrelazamiento es real (Physical Review Letters, 1982). ¡Einstein se equivocó en esto, y la naturaleza es más extraña de lo que pensó!",
  "El físico irlandés John Bell desarrolló en 1964 un test matemático, llamado las Desigualdades de Bell, para determinar si el entrelazamiento era un fenómeno real o simplemente una ilusión estadística (Physics, 1964). Los experimentos que pusieron a prueba las desigualdades de Bell, culminando con los realizados por el equipo de Anton Zeilinger en Viena en los años 1990, confirmaron definitivamente que el entrelazamiento cuántico es real (Nature, 1998). En 2022, Alain Aspect, John Clauser y Anton Zeilinger recibieron el Premio Nobel de Física precisamente por estos experimentos sobre el entrelazamiento cuántico (Nobel Prize, 2022). ¡Un Nobel de Física por confirmar algo que parece magia!",
  "¿Pero en qué consiste exactamente el entrelazamiento? Imagina que tienes dos monedas mágicas: si tiras una y cae cara, la otra cae automáticamente cruz, estén donde estén en el universo. En el mundo cuántico, dos partículas entrelazadas comparten un estado cuántico conjunto. Cuando mides el estado de una, el estado de la otra queda determinado instantáneamente. Lo extraño es que antes de la medición, ninguna de las dos tiene un estado definido: ambas están en superposición, en todos los estados posibles a la vez. La medición 'colapsa' el estado de ambas simultáneamente. ¡Es como si el universo tomara una decisión al mismo tiempo en dos lugares!",
  "Aunque el entrelazamiento parece una conexión instantánea a distancia como la Fuerza Jedi, hay una diferencia crucial: no puede usarse para enviar información más rápido que la luz. Cuando mides una partícula entrelazada, obtienes un resultado aleatorio. Tu copia remota obtendrá el resultado correlacionado, pero no sabes cuál fue tu resultado antes de medirlo, y tampoco puedes controlarlo. Para compartir el resultado, necesitas usar un canal de comunicación clásico, que no puede ir más rápido que la luz (Einstein, Relatividad Especial, 1905). El entrelazamiento es real y fascinante, pero no viola la relatividad. ¡La naturaleza tiene sus reglas!",
  "Los midiclorianos de Star Wars, esas criaturas microscópicas que según la saga median la conexión de un ser con la Fuerza, tienen un paralelo científico interesante. Las mitocondrias, los organelos que producen energía en las células de todos los seres vivos, se cree que fueron originalmente bacterias libres que hace 2,000 millones de años se fusionaron simbioticamente con células más grandes (teoría de la Endosimbiosis, Lynn Margulis, 1967). Son partes de nosotros que una vez vivieron libres. Además, las mitocondrias generan campos eléctricos dentro de las células. ¿Podría una red de señales bioeléctricas interconectadas ser la 'Fuerza' biológica real? La biofísica lo investiga.",
  "El entrelazamiento cuántico no solo es un fenómeno teórico: ya tiene aplicaciones prácticas en desarrollo. La criptografía cuántica usa partículas entrelazadas para crear códigos inquebrantables: cualquier intento de espiar la comunicación altera el estado cuántico y es detectado inmediatamente (Nature, 2020). China lanzó en 2016 el satélite Micius, el primer satélite de comunicaciones cuánticas del mundo, y demostró entrelazamiento cuántico entre tierra y órbita a distancias de más de 1,200 km (Science, 2017). ¡La comunicación cuántica segura, como los mensajes de los Jedi, ya es una tecnología real en desarrollo!",
  "La computación cuántica aprovecha la superposición y el entrelazamiento para resolver ciertos problemas matemáticos de forma exponencialmente más rápida que las computadoras clásicas. En 2019, Google anunció que su computadora cuántica Sycamore realizó un cálculo en 200 segundos que a la computadora clásica más potente le habría tomado 10,000 años (Nature, 2019). IBM y otras empresas están compitiendo para construir computadoras cuánticas prácticas que transformen la medicina, la química y la criptografía. Los qubits, las unidades de información cuántica, pueden estar en superposición de 0 y 1 simultáneamente, lo que hace posible este poder de cálculo. ¡La revolución cuántica ya comenzó!",
  "Para entender la mecánica cuántica, los físicos usan un concepto llamado función de onda, que describe todas las posibilidades de estado de una partícula a la vez. El gato de Schrödinger es el experimento mental más famoso para ilustrar esto: un gato dentro de una caja podría estar vivo y muerto al mismo tiempo, en superposición, hasta que alguien abre la caja y observa (Schrödinger, 1935). Este experimento muestra la rareza de la mecánica cuántica cuando se escala al mundo cotidiano. En el universo cuántico real, estas superposiciones ocurren constantemente a escala subatómica. ¡El universo es fundamentalmente incierto y probabilístico a sus escalas más pequeñas!",
  "La meditación Jedi, con la que los Jedis se conectan con la Fuerza y perciben el mundo a distancia, tiene un eco en la neurociencia moderna. Estudios de neuroimagen han demostrado que la meditación regular cambia físicamente la estructura del cerebro, aumentando la densidad de la corteza prefrontal, asociada con la toma de decisiones, y reduciendo la actividad de la amígdala, asociada con el miedo (Harvard Medical School, 2011). Los practicantes de meditación tibetana de largo plazo muestran ondas gamma de alta frecuencia en el EEG, un patrón asociado con estados de conciencia expandida (Nature Neuroscience, 2004). ¡La meditación cambia el cerebro de forma mesurable y real!",
  "Un descubrimiento reciente fascinante conecta la biología cuántica con la navegación animal. Los petirrojos y otras aves migratorias usan el entrelazamiento cuántico en proteínas de sus ojos para 'ver' el campo magnético de la Tierra y orientarse durante la migración (Nature, 2019). Esta capacidad, llamada magnetorrecepción cuántica, usa pares de electrones entrelazados en la proteína criptocromos para detectar la dirección del campo magnético. ¡Los pájaros usan mecánica cuántica para navegar! Si los seres vivos de la Tierra ya usan procesos cuánticos para percibir su entorno, la idea de una Fuerza cuántica biológica no es tan descabellada.",
  "Tú puedes explorar la mecánica cuántica desde casa. La plataforma de aprendizaje IBM Quantum Experience permite a cualquier persona en el mundo acceder a computadoras cuánticas reales de IBM a través de internet de forma gratuita. Puedes ejecutar tus propios experimentos cuánticos con qubits reales. El canal de YouTube de Instituto Perimeter ofrece conferencias gratuitas sobre mecánica cuántica para principiantes. El libro '¿Qué es la mecánica cuántica?' de Carlos Barceló es una introducción accesible en español. ¡La física cuántica no es solo para adultos con doctorado, también es para exploradores curiosos como tú!",
  "El futuro de la tecnología cuántica incluye comunicaciones cuánticas globales a través de satélites, una red llamada 'internet cuántica' que haría las comunicaciones completamente seguras (Nature, 2022). También se espera que las computadoras cuánticas revolucionen la búsqueda de nuevos medicamentos simulando moléculas complejas, el diseño de materiales superconductores y la solución de problemas de logística global. La ESA y NASA investigan si los efectos cuánticos podrían ser aprovechados para detectar señales de otros civilizaciones (ESA). Si la comunicación cuántica intergaláctica fuera posible, ¡los Jedi no serían tan ficticios!",
  "La física cuántica nos conecta con el universo de formas profundas. Los átomos que componen tu cuerpo fueron creados en el interior de estrellas antiguas mediante reacciones nucleares cuánticas. La luz del Sol que hace crecer las plantas usa el entrelazamiento cuántico en la fotosíntesis para transferir energía con una eficiencia casi perfecta (Nature Chemistry, 2007). Los transistores de tu teléfono funcionan gracias al efecto túnel cuántico, un fenómeno donde los electrones atraviesan barreras de energía que clásicamente no deberían poder cruzar. Sin la mecánica cuántica, no existirían los teléfonos, los láseres ni los escáneres médicos. ¡La física cuántica no es abstracta: es el motor del mundo moderno!",
  "¡Asombroso trabajo, científico cuántico! Ahora entiendes que el entrelazamiento cuántico es un fenómeno real confirmado por experimentos y premiado con el Nobel. Los midiclorianos de Star Wars tienen un paralelo en las mitocondrias y la biofísica cuántica. La criptografía cuántica ya protege comunicaciones reales. Y la computación cuántica está transformando la ciencia. La Fuerza de Star Wars, aunque ficticia, nos invita a explorar los misterios más profundos del universo real. Sigue preguntando, sigue explorando, porque las preguntas más grandes sobre el cosmos todavía esperan ser respondidas por jóvenes científicos como tú. ¡Que la física sea contigo! 🌟"
];

const content_sec5 = [
  "¡Activando sensores de xenobiología, explorador! Hoy vamos a sumergirnos en uno de los campos más fascinantes y especulativos de la ciencia: la búsqueda de vida extraterrestre y el estudio de cómo podría ser la biología de criaturas de otros mundos. Star Wars nos presenta una galaxia llena de especies increíbles, desde Wookiees hasta Hutts, Ewoks y criaturas marinas gigantescas. ¿Podría existir vida así de diversa en el universo real? La astrobiología, que es la ciencia que estudia la posibilidad de vida más allá de la Tierra, dice que es mucho más probable de lo que pensamos. 🌌",
  "La xenobiología es la rama de la biología que estudia hipotéticamente cómo podría ser la vida en otros planetas. En la Tierra, la vida usa carbono como elemento base para construir moléculas complejas, agua como solvente universal y ADN como código genético. Pero los científicos se preguntan si podrían existir vidas basadas en silicio en lugar de carbono, usando amoniaco en lugar de agua como solvente, o con un código genético completamente diferente (NASA Astrobiology). La química del carbono es extraordinariamente versátil, ya que puede formar millones de compuestos diferentes. Sin embargo, el silicio también puede formar cadenas largas, aunque con menos flexibilidad.",
  "Charles Darwin publicó en 1859 'El Origen de las Especies', estableciendo que la vida en la Tierra evoluciona por selección natural: los organismos con características que les dan ventaja en su entorno sobreviven y se reproducen más (Darwin, 1859). Este principio es tan poderoso que los astrobiólogos creen que si hay vida en otros planetas, probablemente también evolucionó por algún mecanismo similar. La evolución convergente, que ocurre cuando especies no relacionadas desarrollan características parecidas por vivir en entornos similares (como las alas de murciélagos, aves e insectos), sugiere que ciertos diseños biológicos son 'inevitables' bajo ciertas condiciones. ¡En otros mundos podrían repetirse patrones similares!",
  "El Dragón Krayt de Tatooine, una criatura masiva de desierto, tiene su equivalente real en los dinosaurios saurópodos que vivieron en la Tierra hace 70 millones de años. El Argentinosaurus medía hasta 40 metros de longitud y pesaba más de 70 toneladas, siendo el animal más grande que ha caminado sobre la Tierra (Nature, 1993). En ambientes desérticos extremos, la vida desarrolla adaptaciones fascinantes: el escarabajo de Namibia recoge agua de la niebla matutina con estructuras microscópicas en su caparazón (Nature, 2001). Las larvas de nemátodos sobreviven deshidratación total y radiación letal entrando en criptobiosis. ¡La vida en la Tierra ya es tan extrema como cualquier criatura de Star Wars!",
  "El Sarlacc del Pozo de Carkoon, que digiere a sus víctimas durante mil años, tiene un paralelo real en las plantas carnívoras como la Venus atrapamoscas y las plantas pitcher, que capturan insectos y los digieren lentamente. Pero la criatura real más fascinante es la ballena de Groenlandia: puede vivir más de 200 años y se ha encontrado con arpones del siglo XIX incrustados en su cuerpo, lo que confirma su longevidad excepcional (Science, 2007). En el océano profundo, los tubos de Riftia, gusanos de 2 metros que viven cerca de chimeneas hidrotermales sin luz solar, usan quimiosíntesis para producir energía, igual que los Sarlacc podrían hacer en el Desierto de Dune Sea.",
  "Los ecosistemas de las chimeneas hidrotermales del fondo oceánico son el ejemplo más relevante para entender mundos como Dagobah. Sin ninguna luz solar, comunidades enteras de criaturas sobreviven usando energía química de compuestos sulfurosos emitidos por el fondo volcánico (Science, 1977). Estas comunidades incluyen tubos de gusanos, almejas gigantes, camarones ciegos y bacterias termófilas que viven a 120°C. Esto demuestra que la vida no necesita luz solar para existir. En las lunas heladas del Sistema Solar como Europa y Encélado, que tienen océanos subsuperficiales calentados por fuerzas de marea, podrían existir ecosistemas similares (NASA, 2023).",
  "La búsqueda de señales de vida extraterrestre inteligente se llama SETI (Search for Extraterrestrial Intelligence). Desde 1960, cuando Frank Drake realizó el primer proyecto SETI moderno llamado Project Ozma, los científicos han escaneado el espacio en busca de señales de radio o láser de origen artificial (SETI Institute). En 1977, el radiotelescopio Big Ear de Ohio captó la famosa señal 'Wow!', un pulso de 72 segundos de intensidad inusual que nunca se repitió ni se explicó satisfactoriamente (SETI Institute). En 2024, SETI Institute usa inteligencia artificial para analizar datos de radiotelescopios buscando patrones que podrían indicar tecnología artificial. ¡La búsqueda continúa!",
  "La Ecuación de Drake, formulada por Frank Drake en 1961, intenta calcular cuántas civilizaciones tecnológicas podrían existir en la galaxia multiplicando factores como la tasa de formación de estrellas, la fracción de estrellas con planetas, la fracción de planetas habitables y la duración de las civilizaciones (SETI Institute). Dependiendo de los valores que se usen, el resultado varía entre 1 (solo nosotros) y millones de civilizaciones. Esta incertidumbre enorme refleja lo poco que aún sabemos. La Paradoja de Fermi pregunta: si hay tantas civilizaciones posibles, ¿dónde están todas? Esta pregunta sin respuesta es uno de los grandes misterios de la ciencia actual.",
  "Las criaturas más extrañas de Star Wars tienen sus equivalentes reales en los organismos extremófilos de la Tierra. El tardígrado, también conocido como oso de agua, es un animal microscópico de 8 patas que puede sobrevivir en el vacío del espacio, radiación letal, temperaturas de -272°C y de 150°C, y presiones extremas (Nature, 2008). La bacteria Deinococcus radiodurans puede sobrevivir dosis de radiación 1,000 veces letales para los humanos. Hongos negros están creciendo en las paredes del reactor nuclear de Chernóbil, usando radiación como fuente de energía (PLoS Biology, 2007). ¡La vida en la Tierra ya tiene superpoderes que parecen de ciencia ficción!",
  "El gusano espacial (space slug) que vive dentro de un asteroide en El Imperio Contraataca es ficción, pero la idea de microorganismos en meteoritos es completamente seria en ciencia. En 1996, la NASA anunció el hallazgo de estructuras parecidas a bacterias fosilizadas en el meteorito marciano ALH84001, encontrado en la Antártida (Science, 1996). Aunque la comunidad científica sigue debatiendo si son realmente fósiles biológicos o artefactos geológicos, el meteorito Murchison, caído en Australia en 1969, contiene aminoácidos orgánicos que se formaron en el espacio (Nature, 1970). Los aminoácidos son los bloques básicos de las proteínas. ¡Los ingredientes de la vida viajan por el universo en meteoritos!",
  "Un descubrimiento extraordinario reciente: en 2020, astrónomos detectaron fosfina en la atmósfera de Venus (Nature Astronomy, 2020). La fosfina en la Tierra solo es producida por organismos vivos o en laboratorios. Aunque el hallazgo fue controvertido y algunos científicos ofrecieron explicaciones alternativas, la posibilidad de que microbios flotantes vivan en las nubes frías de Venus (a 50 km de altitud, donde la temperatura y presión son similares a las de la Tierra) sigue siendo investigada activamente. La misión DAVINCI de NASA, planeada para los años 2030, descenderá a través de la atmósfera de Venus buscando signos de química biológica (NASA). ¡Venus podría tener vida en sus nubes!",
  "Joven astrobióloga o astrobiólogo, tú puedes aprender más sobre la búsqueda de vida extraterrestre de muchas formas. El NASA Astrobiology Institute tiene recursos educativos gratuitos en línea sobre extremófilos, exoplanetas y la búsqueda de vida. El libro 'Astrobiology: A Very Short Introduction' de David Catling es una excelente introducción. Puedes observar la Luna y los planetas del Sistema Solar con binoculares o un telescopio básico. Y puedes participar en proyectos de ciencia ciudadana como SETI@home (que distribuye el análisis de señales de radio entre millones de computadoras) o el Planetary Habitability Laboratory de la Universidad de Puerto Rico. ¡Tu curiosidad puede contribuir a uno de los descubrimientos más grandes de la historia!",
  "Las misiones futuras para buscar vida en el Sistema Solar son fascinantes. La misión Europa Clipper de NASA, lanzada en 2024, realizará 49 sobrevuelos de Europa para estudiar si su océano subsuperficial tiene las condiciones para la vida (NASA). La misión EnVision de ESA a Venus (2031) estudiará la geología y atmósfera venusiana. La misión Dragonfly de NASA enviará un dron nuclear a la luna Titán de Saturno en 2028, donde hay lagos de metano líquido y química orgánica compleja en su superficie (NASA). ¡El Sistema Solar podría tener múltiples mundos con vida, y las misiones de la próxima década lo confirmarán o descartarán!",
  "La xenobiología de Star Wars nos enseña algo importante: la diversidad de la vida es enorme incluso en nuestro único planeta conocido con vida. En la Tierra existen más de 8 millones de especies estimadas, de las cuales solo hemos descrito unos 2 millones (Nature, 2011). Cada año se descubren miles de especies nuevas, desde profundidades oceánicas hasta cuevas sin explorar. La diversidad de la vida en un planeta con condiciones tan similares es asombrosa. Imagina entonces la variedad potencial de vida en planetas con química, temperatura y composición completamente diferentes. ¡La xenobiología de Star Wars podría ser conservadora comparada con la realidad!",
  "¡Expedición completada, explorador de vida cósmica! Ahora sabes que los extremófilos de la Tierra ya tienen superpoderes parecidos a los de las criaturas de Star Wars, que la búsqueda de vida extraterrestre es una ciencia seria con misiones reales como Europa Clipper y Dragonfly, y que los ingredientes químicos de la vida viajan por el universo en meteoritos. La pregunta '¿Estamos solos en el universo?' es la más importante que la humanidad puede hacerse, y tu generación podría ser la que la responda definitivamente. Sigue soñando con mundos lejanos, porque la ciencia te llevará ahí. ¡La galaxia te espera! 🌟"
];

const content_sec6 = [
  "¡Alerta de laboratorio de física de plasmas, científico! Hoy vamos a analizar dos de los artefactos más icónicos de Star Wars: el sable de luz y el blaster. ¿Son posibles en la física real? ¿Qué tecnologías reales se acercan más a estas armas de ciencia ficción? El plasma, el cuarto estado de la materia después del sólido, líquido y gaseoso, juega un papel central en ambas. Y en el universo real, el plasma es el estado de materia más común: el 99.9% de la materia visible del universo está en estado de plasma (NASA). ¡El sable de luz tiene más ciencia real detrás de lo que imaginas! ⚡",
  "El plasma es un gas tan caliente que sus átomos han perdido sus electrones, creando una mezcla de iones positivos y electrones libres que responden fuertemente a campos magnéticos y eléctricos. El Sol, las estrellas, los relámpagos y las auroras boreales son plasma natural. En laboratorios, los científicos crean plasma en reactores de fusión nuclear, en tubos de neón y en propulsores iónicos de satélites. La temperatura del plasma solar en la corona es de aproximadamente 1 a 3 millones de grados Celsius, ¡mientras que la superficie visible del Sol está 'solo' a 5,500°C! (NASA). El plasma es una de las fronteras más activas de la física experimental.",
  "Los sables de luz de Star Wars fueron concebidos por George Lucas en la década de 1970 como armas de energía pura. En 1977, cuando se estrenó la primera película, la tecnología láser apenas estaba en sus primeras etapas. Hoy, los láseres son omnipresentes: en reproductores de música, cirugía ocular, telemetría, comunicaciones por fibra óptica y apuntadores. Sin embargo, un láser real no se vería como el sable de luz de Star Wars: la luz de un láser es invisible en el vacío si no hay partículas para dispersarla, no se detiene a una longitud determinada y no bloquearía otro láser. El sable de luz ficticio viola estas reglas básicas de la óptica.",
  "La versión físicamente más plausible del sable de luz sería un campo de plasma confinado magnéticamente en forma de hoja o espada. En reactores de fusión como el Tokamak, el plasma se confina usando potentes campos magnéticos para evitar que destruya las paredes del reactor. Un campo magnético toroidal podría, en principio, confinar plasma a muy alta temperatura en una forma alargada. El problema es que los campos magnéticos que pueden contener plasma actualmente pesan toneladas y llenan salas enteras. Miniaturizar esa tecnología al tamaño de un mango de espada requeriría superconductores de temperatura ambiente, que todavía no existen de forma práctica (Nature, 2023).",
  "La fusión nuclear, el proceso que podría alimentar un sable de luz real, es el mismo proceso que hace brillar al Sol: combinar núcleos de hidrógeno para formar helio, liberando cantidades colosales de energía (E=mc², Einstein, 1905). En diciembre de 2022, el National Ignition Facility de Estados Unidos logró por primera vez que una reacción de fusión produjera más energía de la que se necesitó para iniciarla, un hito histórico (Science, 2022). Empresas privadas como Commonwealth Fusion Systems, con respaldo del MIT, esperan tener reactores de fusión comerciales antes de 2035. ¡La energía de las estrellas podría estar disponible para la humanidad en esta generación!",
  "Los blasters de Star Wars disparan proyectiles de 'plasma excitado', llamados paquetes de energía cargada. En la física real, los dispositivos más parecidos son los cañones de riel (railguns), que aceleran proyectiles metálicos usando campos electromagnéticos a velocidades de más de 3,000 metros por segundo, y los cañones de plasma experimentales que disparan campos de plasma comprimido (U.S. Navy, 2023). Sin embargo, el plasma se dispersa muy rápidamente en el aire porque los iones se repelen entre sí. Otro candidato real son los láseres de alta energía: el sistema LaWS de la Marina de EE.UU. ya puede derribar drones con un láser de 30 kilovatios a distancias de varios kilómetros (U.S. Navy, 2014).",
  "Los láseres militares reales ya son funcionales. El sistema HELIOS (High Energy Laser with Integrated Optical-dazzler and Surveillance) de Northrop Grumman puede destruir blancos a distancias de varios kilómetros con una potencia de 60 kilovatios (U.S. Navy, 2022). Israel usa el sistema Iron Beam, un láser de alta energía, para interceptar cohetes y drones (Rafael Advanced Defense Systems, 2023). Estos sistemas tienen ventajas reales: operan a velocidad de la luz, con costo por disparo casi cero y munición ilimitada mientras haya energía. Sus desafíos incluyen la dispersión atmosférica y la generación de calor en el propio sistema. ¡Los láseres de combate ya son una tecnología de defensa real!",
  "Los cristales kyber de Star Wars, que alimentan los sables de luz y concentran la energía, tienen un equivalente científico real: los cristales de rubí y las gemas de zafiro sintéticas usadas en algunos tipos de láseres. El primer láser de la historia, construido por Theodore Maiman en 1960, usaba un cristal de rubí sintético como medio de amplificación de luz (Physical Review Letters, 1960). Hoy se usan cristales de Nd:YAG (granate de itrio y aluminio con neodimio) en láseres médicos e industriales de alta potencia. ¡Los cristales concentradores de luz de Star Wars están directamente inspirados en la física real de los láseres de cristal!",
  "Las auroras boreales y australes son el espectáculo de plasma más hermoso que existe en la naturaleza. Se producen cuando partículas del viento solar (protones y electrones) son atrapadas por el campo magnético de la Tierra y colisionan con los gases de la atmósfera superior, haciendo que estos brillen como tubos de neón gigantescos (NASA). El color depende del gas: el oxígeno a 100 km produce verde, el oxígeno a 200 km produce rojo, el nitrógeno produce azul y violeta. Las auroras se pueden ver desde tierra a latitudes altas. Si alguna vez ves una aurora, recuerda: estás viendo plasma solar bailando en el campo magnético de la Tierra. ¡Es el sable de luz de nuestro planeta!",
  "Los propulsores iónicos de las naves espaciales reales son la tecnología de plasma más exitosa aplicada a la exploración espacial. En lugar de quemar combustible químico, estos motores aceleran iones de xenón usando campos eléctricos, creando un chorro de plasma que propulsa la nave (NASA). La nave Dawn de NASA usó propulsores iónicos para visitar los asteroides Vesta y Ceres entre 2011 y 2018, siendo la primera nave en orbitar dos cuerpos celestes distintos (NASA, 2018). Aunque el empuje de estos motores es muy pequeño, son extremadamente eficientes en el uso de combustible y pueden acelerar de forma continua durante meses. ¡Los propulsores iónicos son los motores de plasma más avanzados que existen hoy!",
  "Un descubrimiento reciente fascinante: en 2023, investigadores del MIT lograron crear 'chispas de plasma' miniaturizadas del tamaño de una célula usando técnicas de nanofabricación (MIT News, 2023). Estas microplasmas podrían usarse para esterilizar heridas quirúrgicas, tratar infecciones resistentes a antibióticos o incluso, en el futuro, para crear pantallas de plasma ultrafinas. El proyecto ITER en Francia, una colaboración de 35 países, está construyendo el reactor de fusión de plasma más grande del mundo, que se espera produzca 10 veces más energía de la que necesita para funcionar (ITER Organization, 2023). ¡La física de plasma está transformando tanto la medicina como la energía global!",
  "Tú, joven físico, puedes experimentar con plasma de forma segura. Un tubo fluorescente contiene gas a baja presión que se convierte en plasma cuando la electricidad lo excita. Las bolas de plasma que se venden como decoración usan el mismo principio. Si tienes acceso a un laboratorio escolar con generador Van de Graaff, puede producir pequeñas descargas de plasma. El microscopio de plasma de baja temperatura, también llamado microscopio de efecto corona, permite visualizar campos eléctricos alrededor de objetos. Los experimentos con plasma de baja temperatura son seguros y demuestran de forma espectacular la física de este cuarto estado de la materia.",
  "El futuro de la tecnología de plasma incluye reactores de fusión comerciales que podrían proporcionar energía limpia e ilimitada para toda la humanidad. La empresa Commonwealth Fusion Systems espera tener su primer reactor SPARC operativo alrededor de 2025 y una planta de energía comercial hacia 2030 (MIT News, 2023). Los propulsores de fusión de plasma podrían reducir el viaje a Marte de 7 meses a solo 90 días (NASA, 2023). Los láseres de plasma de alta potencia se investigan como herramientas para la defensa planetaria contra asteroides. ¡El dominio del plasma es la clave para la energía del futuro y la exploración espacial de largo alcance!",
  "La física del plasma nos conecta con el universo más grande de todas las formas posibles. Las estrellas son plasma, las nebulosas son plasma, los chorros de los agujeros negros son plasma, y el medio interestelar es en gran parte plasma ionizado. Cuando el universo tenía solo 380,000 años de edad, era completamente plasma: un mar caliente de protones y electrones que no podían formar átomos neutros. El momento en que ese plasma se enfrió lo suficiente para que los electrones se unieran a los protones se llama Recombinación, y la luz que se emitió en ese momento la detectamos hoy como la Radiación de Fondo de Microondas (NASA). ¡Estudiando el plasma, estudiamos el origen mismo del universo!",
  "¡Laboratorio de plasma cerrado exitosamente, físico estelar! Ahora sabes que los sables de luz serían más parecidos a plasma confinado magnéticamente que a láseres, que los blasters tienen equivalentes reales en láseres de combate y cañones de plasma, y que la fusión nuclear —la fuente de energía de una estrella— está siendo dominada por la humanidad en este momento histórico. Los cristales kyber tienen su equivalente en los cristales de rubí de los primeros láseres. El plasma no es solo ciencia ficción: es el estado más común de la materia en el universo. ¡Que el plasma esté contigo, explorador! 🌟"
];

// Patch the modules
let patched = 0;
for (let module of data) {
  if (module.id === 'starwars_sec_4') {
    module.contentEs.sections[0].text = content_sec4;
    patched++;
  }
  if (module.id === 'starwars_sec_5') {
    module.contentEs.sections[0].text = content_sec5;
    patched++;
  }
  if (module.id === 'starwars_sec_6') {
    module.contentEs.sections[0].text = content_sec6;
    patched++;
  }
}

console.log(`Patched ${patched} modules.`);
fs.writeFileSync(filePath, 'export default ' + JSON.stringify(data, null, 2) + ';', 'utf8');
console.log('File written successfully.');
