const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'lib', 'courseData.js');
let raw = fs.readFileSync(filePath, 'utf8');
let data = JSON.parse(raw.replace(/^export default /, '').replace(/;$/, ''));

const content_sec1 = [
  "¡Bienvenido, explorador galáctico! Imagina que estás a bordo del Halcón Milenario con Han Solo y de repente él grita que harán el Corredor de Kessel en menos de 12 pársecs. Espera, ¡un pársec es una unidad de distancia, no de tiempo! Hoy vamos a descubrir cómo funciona realmente la medida de las distancias en el universo y qué tan lejos están las estrellas. Prepárate porque las escalas del cosmos son tan enormes que van a dejar tu mente absolutamente volada. La astronomía real es incluso más emocionante que cualquier película de ciencia ficción. 🚀",
  "Un pársec es la unidad que usan los astrónomos para medir distancias estelares gigantescas. Equivale aproximadamente a 3.26 años luz, es decir, la distancia que recorre la luz en 3.26 años viajando a 300,000 kilómetros por segundo. Para darte una idea, la estrella más cercana a la Tierra, Próxima Centauri, está a 1.3 pársecs de nosotros (NASA, 2023). Los astrónomos obtienen esta medida usando algo llamado paralaje estelar: observan una estrella desde dos puntos distintos de la órbita terrestre y miden cuánto parece moverse en el cielo. Es como cuando cierras un ojo y luego el otro mirando tu dedo: parece que se mueve aunque no lo haga.",
  "El concepto de paralaje estelar fue utilizado por primera vez con éxito por el astrónomo alemán Friedrich Bessel en 1838, quien midió la distancia a la estrella 61 Cygni (ESA). Antes de ese momento, los humanos sabían que las estrellas estaban lejos, pero no cuánto exactamente. Esta fue una de las mayores revoluciones en la historia de la astronomía. Bessel demostró que 61 Cygni estaba a unos 11 años luz de la Tierra, lo cual era un número que nadie había imaginado con exactitud antes. ¡Gracias a esa medición, comenzamos a comprender de verdad la escala infinita del universo!",
  "La Vía Láctea, nuestra galaxia, mide aproximadamente 100,000 años luz de diámetro, lo que equivale a casi 30,660 pársecs (NASA). El centro de la galaxia está a unos 26,000 años luz de la Tierra, un número tan grande que es casi imposible de imaginar. Comparados con eso, los 12 pársecs del Corredor de Kessel de Han Solo serían apenas un paseo por el vecindario galáctico. Hay más de 200,000 millones de estrellas solo en nuestra galaxia, y cada una puede tener planetas orbitando a su alrededor. ¡El universo es inconmensurablemente grande!",
  "El hiperespacio de Star Wars, esa dimensión alternativa donde las naves viajan a velocidades imposibles, no existe en la física real. Sin embargo, hay una idea científica fascinante que se le parece: la Métrica de Alcubierre, propuesta por el físico mexicano Miguel Alcubierre en 1994 (Physical Review D, 1994). Esta teoría matemática sugiere que en lugar de mover la nave más rápido que la luz, podrías comprimir el espacio-tiempo delante de la nave y expandirlo detrás. Sería como si la nave estuviera quieta dentro de una burbuja de espacio que se mueve. ¡Es física real basada en las ecuaciones de Einstein, aunque por ahora requeriría energía equivalente a la masa de Júpiter para funcionar!",
  "La velocidad de la luz, que en física se denota como 'c', es exactamente 299,792,458 metros por segundo en el vacío (NIST). Ningún objeto con masa puede alcanzar ni superar esta velocidad según la Teoría de la Relatividad Especial de Einstein de 1905. Si algo pudiera viajar a la velocidad de la luz, su masa se volvería infinita y requeriría energía infinita para seguir acelerando. Es como tratar de empujar una pelota que se vuelve cada vez más pesada cuanto más rápido va, hasta que sería imposible de mover. Por eso los viajes estelares reales serán siempre un enorme desafío de ingeniería y física.",
  "La misión Gaia de la ESA, lanzada en 2013, ha cartografiado con precisión las posiciones y distancias de más de mil millones de estrellas de nuestra galaxia (ESA, 2022). Gracias a Gaia, ahora tenemos el mapa estelar más detallado y preciso jamás creado. Los datos de esta misión han revolucionado nuestra comprensión de la estructura de la Vía Láctea, revelando corrientes estelares, cúmulos y los brazos espirales de la galaxia con detalle sin precedentes. Cada dato de Gaia confirma que las distancias en el universo son gigantescas. ¡Es como tener un GPS galáctico ultrapreciso!",
  "El famoso Corredor de Kessel de Star Wars está inspirado en algo real: las rutas de navegación estelar que tendrían que trazarse sorteando objetos peligrosos como agujeros negros o nebulosas densas. En la película Solo (2018), se explica que la ruta corta implica pasar peligrosamente cerca del Maw, un cúmulo de agujeros negros. En el universo real, los agujeros negros curvan el espacio-tiempo a su alrededor de forma tan extrema que ni la luz puede escapar (NASA). La distancia efectiva de una ruta que rodea un agujero negro podría ser mucho mayor que la línea recta. ¡Han Solo en realidad estaba hablando de geometría cósmica!",
  "Para los jóvenes astrónomos en casa hay mucho que explorar: aplicaciones como Stellarium o SkySafari muestran el cielo nocturno con las distancias reales de las estrellas en años luz. Cuando miras la estrella Betelgeuse en la constelación de Orión, estás viendo luz que salió de esa estrella hace unos 700 años (ESA). Es decir, ¡estás mirando al pasado! Cada estrella del cielo nocturno es una ventana temporal a diferentes épocas del universo. Si tuvieras un telescopio potente, podrías ver galaxias a millones de años luz, lo que significa que verías cómo eran hace millones de años. 🔭",
  "El telescopio espacial James Webb, lanzado en diciembre de 2021 por NASA y ESA, puede observar galaxias a más de 13,000 millones de años luz de distancia (NASA, 2023). Esto significa que vemos esas galaxias tal como eran cuando el universo tenía apenas unos cientos de millones de años de edad. Los datos del James Webb están revelando galaxias masivas que existieron mucho antes de lo que los científicos esperaban, obligando a revisar modelos de formación galáctica. La profundidad del universo observable es de unos 46,500 millones de años luz en todas direcciones. ¡El cosmos es incomprensiblemente vasto!",
  "Un hecho sorprendente y reciente: en 2022, el James Webb capturó la imagen de Earendel, la estrella más lejana jamás observada, ubicada a 28,000 millones de años luz (NASA/ESA, 2022). Antes, la estrella más lejana conocida individualmente, Ícaro, estaba a 9,000 millones de años luz y fue descubierta por el Hubble en 2018. Estas observaciones son posibles gracias al efecto de lente gravitacional, donde la gravedad de un cúmulo de galaxias curva y amplifica la luz de objetos más distantes detrás de él. Esto confirma algo que Einstein predijo: la gravedad curva la luz. ¡La física real supera a la ciencia ficción!",
  "Si quieres convertirte en astrónomo, cadete, puedes empezar esta misma noche. Observa las estrellas sin telescopio e intenta identificar las constelaciones con una aplicación gratuita. Busca la Estrella Polar, que siempre señala el norte y está a 433 años luz de la Tierra (NASA). Intenta localizar la constelación de Orión con su famoso cinturón de tres estrellas. Lleva un cuaderno de campo y anota lo que observas cada noche. Los grandes astrónomos empezaron así, mirando el cielo con curiosidad e imaginación, y tú también puedes hacerlo.",
  "Las misiones futuras para medir distancias estelares incluyen el Observatorio Nancy Grace Roman de NASA, previsto para lanzarse alrededor de 2027. Este telescopio tendrá un campo de visión 100 veces mayor que el Hubble, permitiendo cartografiar enormes extensiones del cosmos (NASA). También se planean observatorios terrestres como el Extremely Large Telescope (ELT) en Chile, que con su espejo de 39 metros será el telescopio óptico más grande jamás construido (ESO). Estos instrumentos nos permitirán medir distancias a estrellas que hoy son invisibles incluso para el James Webb. ¡El futuro de la astronomía es emocionante!",
  "Las distancias estelares conectan directamente con nuestra vida cotidiana de formas inesperadas. El GPS de tu teléfono usa señales de satélites que tienen que corregir sus relojes por los efectos de la relatividad de Einstein, ya que el tiempo corre ligeramente diferente a alta altitud y velocidad (NASA). La física que explica por qué las estrellas están tan lejos es la misma que hace funcionar tu navegador. Además, el hierro en tu sangre fue forjado en explosiones de supernovas a miles de años luz de la Tierra hace miles de millones de años. ¡Eres literalmente polvo de estrellas que aprendió a medir distancias estelares!",
  "¡Enhorabuena, explorador estelar! Ahora sabes que un pársec es una unidad de distancia de 3.26 años luz, que la Vía Láctea mide 30,660 pársecs de diámetro, y que el hiperespacio ficticio tiene un eco real en la Métrica de Alcubierre. La ciencia real de las distancias cósmicas es tan asombrosa como cualquier aventura galáctica. Cada vez que mires el cielo nocturno, recuerda que estás contemplando un océano infinito de soles a pársecs de distancia. El universo nos espera, y los científicos de hoy están construyendo los instrumentos que nos llevarán más lejos que nunca. ¡May the science be with you! 🌟"
];

const content_sec2 = [
  "¡Prepara tu casco de explorador, cadete! Hoy vamos a visitar algunos de los mundos más extraños y fascinantes que aparecen en la saga Star Wars, y vamos a comparar cada uno con planetas y lunas reales que los astrónomos han descubierto. ¿Sabías que los científicos han encontrado planetas reales que se parecen sorprendentemente a Tatooine, Hoth y Dagobah? La ciencia de los mundos extraterrestres se llama planetología y es uno de los campos más emocionantes de la astronomía moderna. ¡Abróchate el cinturón porque este viaje por la ciencia real será alucinante! 🌍",
  "Tatooine, el planeta con dos soles de Luke Skywalker, parecía pura fantasía hasta que en 2011 el telescopio espacial Kepler de NASA descubrió Kepler-16b (NASA, 2011). Este planeta real orbita alrededor de dos estrellas, igual que Tatooine, y está a unos 200 años luz de la Tierra en la constelación del Cisne. Kepler-16b es un mundo gaseoso frío, parecido a Saturno, con una temperatura de unos -100°C. Tiene dos soles: uno de tipo solar y otro más pequeño y frío. ¡Desde su superficie podrías ver dos atardeceres cada día, igual que en la película!",
  "Los sistemas binarios, es decir, dos estrellas que orbitan una alrededor de la otra, son en realidad muy comunes en el universo. Se estima que más del 50% de las estrellas en la Vía Láctea son parte de sistemas dobles o múltiples (ESA). La mecánica de cómo un planeta puede tener una órbita estable alrededor de dos estrellas fue estudiada matemáticamente durante décadas. Para que la órbita sea estable, el planeta debe estar suficientemente alejado de ambas estrellas, en lo que los científicos llaman una órbita circumbinaria. ¡La física de estos sistemas es un ballet gravitacional perfecto!",
  "Hoth, el planeta de hielo congelado de El Imperio Contraataca, tiene su equivalente científico real: Europa, la luna de Júpiter. Europa está cubierta por una capa de hielo de varios kilómetros de grosor, bajo la cual los científicos creen que existe un océano de agua líquida de unos 100 km de profundidad (NASA). Este océano subterráneo es mantenido líquido por el calor generado por las fuerzas de marea de Júpiter, que estiran y comprimen la luna. La misión Europa Clipper de NASA, lanzada en octubre de 2024, estudiará si ese océano podría albergar vida microbiana. ¡Un mundo de hielo con potencial de vida real!",
  "Dagobah, el planeta pantanoso y húmedo donde vive el Maestro Yoda, es muy similar a lo que la Tierra era durante el período Carbonífero, hace unos 300 millones de años. En esa época, nuestra planeta estaba cubierto de enormes bosques pantanosos, con una atmósfera rica en oxígeno que permitía a los insectos crecer a tamaños gigantescos (NASA). Los científicos buscan exoplanetas con características similares usando telescopios como el James Webb. Un mundo con tanta biomasa como Dagobah produciría enormes cantidades de oxígeno y metano detectables desde el espacio. ¡Los telescopios del futuro podrían detectar mundos como Dagobah!",
  "La zona habitable, también llamada zona de Goldilocks, es la región alrededor de una estrella donde las temperaturas permiten que el agua exista en estado líquido en la superficie de un planeta (NASA). Ni muy caliente como el mercurio, ni muy fría como Plutón, sino justa como la Tierra. Tatooine, con dos soles, tendría una zona habitable mucho más compleja de calcular, ya que cambiaría según la posición de ambas estrellas. Hoth estaría definitivamente fuera de la zona habitable de su sistema. Dagobah, en cambio, parece estar perfectamente situada, lo que es otra razón por la que es tan exuberante y llena de vida.",
  "El telescopio Kepler de NASA, activo entre 2009 y 2018, descubrió más de 2,600 exoplanetas confirmados (NASA, 2018). Su sucesor, el telescopio TESS, lanzado en 2018, ha descubierto miles más buscando planetas alrededor de estrellas cercanas. Hasta la fecha, los astrónomos han confirmado más de 5,500 exoplanetas en nuestra galaxia (NASA, 2023). Entre ellos hay mundos de lava, mundos de diamante, planetas con lluvia de hierro fundido y planetas que orbitan dos estrellas como Tatooine. ¡La realidad del cosmos es más variada y extraña que cualquier película de ciencia ficción!",
  "Uno de los hallazgos más sorprendentes recientes es el exoplaneta 55 Cancri e, a 41 años luz de la Tierra. Los científicos creen que podría tener una superficie de carbono cristalizado bajo presión extrema, lo que en teoría significaría que parte de su interior podría ser diamante (Nature, 2012). Su año dura solo 18 horas terrestres porque orbita muy cerca de su estrella. La temperatura en su superficie supera los 2,000°C. Comparado con esto, Mustafar, el planeta de lava de Star Wars donde Anakin lucha con Obi-Wan, no suena tan descabellado.",
  "Para estudiar otros mundos, los astrónomos usan principalmente el método del tránsito: cuando un exoplaneta pasa frente a su estrella, bloquea un pequeño porcentaje de la luz, y los telescopios pueden detectar ese parpadeo (ESA). Otro método es la velocidad radial: si un planeta orbita una estrella, su gravedad hace que la estrella se tambalee ligeramente, y ese movimiento cambia la longitud de onda de la luz estelar. Combinando ambos métodos, podemos calcular el tamaño, masa y composición de un exoplaneta. Es como deducir el tamaño de un pez invisible viendo cómo se mueve el barco cuando tira del anzuelo. ¡Astronomía como detective cósmico!",
  "La búsqueda de mundos habitables es la misión central del programa de exoplanetas de NASA. El James Webb puede analizar la atmósfera de exoplanetas buscando huellas químicas de vida: oxígeno, metano, vapor de agua, ozono (NASA, 2023). En 2023, el James Webb detectó dióxido de carbono y posibles señales de sulfuro de dimetilo en la atmósfera del exoplaneta K2-18b, un compuesto que en la Tierra solo es producido por organismos vivos (Nature, 2023). Esto no confirma vida, pero es la pista más emocionante jamás encontrada. ¡El descubrimiento de vida extraterrestre podría ocurrir en nuestra generación!",
  "Una luna que merece atención especial es Encélado, la luna de Saturno. Bajo su superficie helada hay un océano líquido que lanza géiseres de vapor de agua al espacio, detectados por la sonda Cassini de NASA (NASA/ESA, 2014). El análisis de esos géiseres reveló moléculas orgánicas, hidrógeno molecular y sílice, todos ingredientes necesarios para la vida tal como la conocemos. Si Dagobah fuera una luna pantanosa como Encélado, solo que más cerca de su planeta y con una fuente de calor mayor, podría ser científicamente posible. ¡Las lunas heladas del Sistema Solar son uno de los lugares más prometedores para buscar vida!",
  "Tú, joven científico, puedes participar en la búsqueda de exoplanetas desde tu casa. El programa Planet Hunters de la plataforma Zooniverse permite que cualquier persona analice datos reales del telescopio Kepler para encontrar tránsitos de exoplanetas (NASA/Zooniverse). Varios planetas han sido descubiertos gracias a ciudadanos científicos de todas las edades. También puedes descargar los datos abiertos de NASA en el archivo de exoplanetas y explorarlos con herramientas gratuitas. La ciencia ciudadana es real y produce resultados reales. ¡Tú también puedes descubrir un mundo nuevo!",
  "Las misiones futuras para el estudio de mundos extremos incluyen el Ariel Space Mission de ESA, previsto para 2029, que caracterizará la atmósfera de cientos de exoplanetas (ESA). La misión PLATO de ESA, planeada para 2026, buscará planetas parecidos a la Tierra alrededor de estrellas similares al Sol. El Extremely Large Telescope (ELT) en Chile permitirá, por primera vez, tomar imágenes directas de exoplanetas y analizar su composición en detalle (ESO). Estas misiones nos darán un catálogo completo de mundos habitables en nuestra vecindad galáctica. ¡El mapa del universo habitado se está dibujando ahora mismo!",
  "Los planetas extremos del universo real nos enseñan algo importante sobre la vida en la Tierra: somos extraordinariamente afortunados. Nuestra posición en la zona habitable, nuestra Luna que estabiliza el eje de la Tierra, nuestro campo magnético que nos protege del viento solar, el tamaño de Júpiter que desvía asteroides peligrosos... todo está calibrado de forma que parece casi milagrosa (NASA). Estudiar mundos como Tatooine o Hoth nos hace valorar más nuestro planeta azul. La astrobiología, la ciencia que estudia la posibilidad de vida en otros mundos, nos recuerda que la Tierra es un tesoro cósmico.",
  "¡Misión completada, explorador de mundos! Ahora sabes que Tatooine tiene un equivalente real en Kepler-16b, que mundos como Europa y Encélado nos muestran que los océanos de hielo son comunes en el Sistema Solar, y que el James Webb está buscando activamente señales de vida en otros planetas. La ciencia de los mundos extremos nos conecta con el cosmos de una forma que ninguna película puede igualar. La próxima vez que veas el cielo estrellado, recuerda que ahí afuera hay más de 5,500 mundos conocidos y probablemente miles de millones más por descubrir. ¡El universo te espera, cadete! 🌟"
];

const content_sec3 = [
  "¡Activando sistemas principales, cadete! Hoy vamos a hablar de dos de los personajes más queridos de toda la saga Star Wars: C-3PO y R2-D2. Pero no los vamos a ver como personajes de película, sino como ventanas al fascinante mundo de la robótica, la inteligencia artificial y la biomecatrónica real. ¿Te has preguntado alguna vez cuánto se parece R2-D2 a los robots que ya existen hoy en día? ¡La respuesta te va a sorprender mucho! La ciencia de construir robots inteligentes es una de las áreas que más rápido avanza en el mundo entero. 🤖",
  "La robótica es la ciencia e ingeniería de diseñar, construir y programar robots: máquinas que pueden realizar tareas de forma autónoma o asistida. Un robot, en su definición más básica, necesita tres componentes: sensores para percibir el entorno, procesadores para tomar decisiones y actuadores para moverse o actuar (IEEE). C-3PO es un androide, es decir, un robot con forma humana, mientras que R2-D2 es un droide astromecánico de forma cilíndrica. En el mundo real, los ingenieros construyen robots de todas las formas según la tarea que deben realizar. No todos los robots se parecen a los humanos, ¡ni tienen por qué!",
  "El primer robot industrial fue Unimate, instalado en una planta de General Motors en 1961, diseñado para levantar piezas de metal caliente en líneas de ensamblaje (Smithsonian Institution). Sin embargo, la robótica moderna ha avanzado de forma espectacular en los últimos 20 años. En 2001, el robot Canadarm2 fue instalado en la Estación Espacial Internacional y sigue funcionando hoy, asistiendo en caminatas espaciales y manipulando cargas externas (NASA/CSA). Este brazo robótico espacial es en muchos sentidos parecido a las funciones que haría R2-D2: asistir en el mantenimiento de naves espaciales. ¡La robótica espacial es completamente real!",
  "C-3PO habla más de seis millones de formas de comunicación, lo que en el mundo real se llama procesamiento de lenguaje natural. Esta tecnología permite a las computadoras comprender y generar lenguaje humano. Los sistemas modernos de inteligencia artificial como los grandes modelos de lenguaje pueden procesar cientos de idiomas y realizar traducciones en tiempo real (Nature, 2023). Google Translate soporta más de 100 idiomas. Pero hay una gran diferencia: C-3PO comprende el contexto cultural profundo de cada idioma, algo que los sistemas actuales de IA todavía hacen de forma imperfecta. ¡La comprensión verdadera del lenguaje sigue siendo un desafío enorme para la IA!",
  "R2-D2 es especialmente interesante porque demuestra personalidad a través de sus pitidos y acciones. En inteligencia artificial, esto se llama comportamiento emergente: cuando un sistema complejo desarrolla características que no fueron explícitamente programadas. Los robots modernos con aprendizaje por refuerzo, como los desarrollados por Boston Dynamics o DeepMind de Google, aprenden estrategias y comportamientos que sorprenden incluso a sus creadores (Nature, 2022). Es como si el robot inventara sus propias soluciones a problemas nuevos. ¡La línea entre comportamiento programado y personalidad emergente es cada vez más borrosa!",
  "Los robots reales más parecidos a R2-D2 son los rovers marcianos de NASA. El rover Perseverance, que aterrizó en Marte en febrero de 2021, puede navegar de forma autónoma por el terreno marciano, tomar muestras de roca y analizar su composición química sin instrucciones en tiempo real desde la Tierra (NASA, 2021). Cada comunicación con Marte tarda entre 3 y 22 minutos según la posición de los planetas, por lo que los robots marcianos deben tomar decisiones propias. Perseverance incluso cargó consigo al helicóptero Ingenuity, que realizó el primer vuelo propulsado en otro planeta. ¡Los robots de exploración espacial ya son increíbles hoy!",
  "La inteligencia artificial que permitiría que C-3PO funcione se basa en redes neuronales artificiales, modelos matemáticos inspirados en cómo funciona el cerebro humano. Una red neuronal aprende reconociendo patrones en grandes cantidades de datos, igual que tú aprendes a reconocer caras al ver muchas caras (Nature, 2015). Los sistemas de reconocimiento facial actuales, como los usados en desbloqueo de teléfonos, son redes neuronales profundas. El sistema AlphaFold de DeepMind, usando IA, resolvió en 2021 el problema del plegamiento de proteínas que la biología llevaba 50 años intentando resolver (Nature, 2021). ¡La IA ya está salvando vidas en medicina real!",
  "Las prótesis biónicas son la versión real de los miembros robóticos de los personajes de Star Wars, como la mano de Luke Skywalker. Empresas como Open Bionics ya producen manos robóticas impresas en 3D que se controlan mediante señales eléctricas de los músculos del usuario, con un costo de unos 10,000 dólares (Open Bionics, 2023). Los investigadores del MIT y de la Universidad de Pittsburgh han desarrollado brazos robóticos conectados directamente al sistema nervioso que permiten sentir la textura de los objetos (Science, 2022). ¡Las prótesis del siglo XXI ya tienen sensaciones táctiles reales, igual que la mano de Luke!",
  "Para jóvenes científicos que quieren explorar la robótica, existen recursos accesibles. La plataforma LEGO Mindstorms y su sucesor LEGO Spike permiten construir y programar robots desde los 8 años. Arduino y Raspberry Pi son plataformas de electrónica de bajo costo con las que millones de jóvenes en todo el mundo construyen robots, sensores y dispositivos. NASA ofrece el programa FIRST Robotics, en el que estudiantes de secundaria compiten construyendo robots reales (NASA Education). Los robots que ganarán los desafíos del futuro serán diseñados por personas que empezaron exactamente como tú: curiosas y apasionadas.",
  "Un campo que conecta la robótica con la medicina es la cirugía robótica. El sistema Da Vinci, utilizado en hospitales de todo el mundo, permite a los cirujanos operar a través de pequeñas incisiones usando brazos robóticos controlados por joystick, con una precisión milimétrica imposible para la mano humana sola (Intuitive Surgical, 2023). En el espacio, la ESA y NASA investigan robots quirúrgicos para atender emergencias médicas en misiones de larga duración, como un viaje a Marte (ESA). C-3PO y R2-D2 podrían ser los ancestros ficticios de los robots médicos que salvarán vidas en las misiones espaciales del futuro.",
  "Un descubrimiento sorprendente de los últimos años es la robótica blanda o soft robotics. En lugar de usar metales rígidos, estos robots están hechos de materiales flexibles y elásticos, inspirados en los tentáculos del pulpo (Science, 2018). Son capaces de agarrar objetos frágiles como huevos sin romperlos, algo muy difícil para los robots tradicionales. Harvard ha desarrollado robots blandos impulsados por aire que pueden reptar, nadar y doblarse como animales reales. Los robots blandos son perfectos para explorar entornos hostiles o realizar cirugías delicadas. ¡La naturaleza sigue siendo la mejor ingeniera del universo!",
  "Tú, joven científico, puedes empezar tu camino en robótica ahora mismo. Busca en YouTube tutoriales de Arduino o Scratch para aprender programación básica. Construye un robot con cartón y motores de bajo costo siguiendo instrucciones en línea. Participa en clubes de robótica en tu escuela o comunidad. La robótica es un campo interdisciplinario que combina matemáticas, física, biología, diseño e ingeniería. Cada uno de los robots que cambiarán el mundo fue soñado primero por alguien joven que se preguntó: '¿Sería posible construir un R2-D2 real?'. ¡Esa persona podrías ser tú!",
  "El futuro de los robots es aún más emocionante que el presente. Los robots humanoides como Atlas de Boston Dynamics ya pueden hacer saltos mortales y correr en terreno irregular (Boston Dynamics, 2023). Tesla está desarrollando Optimus, un robot humanoide diseñado para trabajar en fábricas. La NASA planea enviar robots humanoides a la Luna antes de los astronautas humanos para preparar las bases (NASA Artemis). En medicina, se investigan robots del tamaño de bacterias, llamados nanorobots, que podrían viajar por el torrente sanguíneo para destruir células cancerosas (Nature Nanotechnology, 2023). ¡El futuro que Star Wars imaginó ya está llegando!",
  "La robótica tiene implicaciones profundas para nuestra sociedad que debemos pensar con cuidado. Si los robots hacen cada vez más trabajos, ¿qué pasará con las personas que hacían esos trabajos? ¿Cómo aseguramos que la inteligencia artificial sea justa y no discrimine? Estas preguntas de ética tecnológica son tan importantes como la ingeniería en sí misma. Organizaciones como el MIT Media Lab y el Centro Berkman Klein de Harvard estudian el impacto social de la IA (Harvard Law, 2023). C-3PO con sus preocupaciones y R2-D2 con su lealtad nos recuerdan que los robots son herramientas que reflejan los valores de quienes los crean.",
  "¡Misión de robótica completada, ingeniero espacial! Ahora sabes que C-3PO y R2-D2 representan tecnologías reales: procesamiento de lenguaje natural, navegación autónoma, aprendizaje automático y prótesis biónicas. Los robots marcianos de NASA ya realizan misiones que R2-D2 hubiera reconocido. La inteligencia artificial está transformando la medicina, la exploración espacial y la ciencia. Y tú, con curiosidad y aprendizaje, puedes ser parte de la próxima generación de ingenieros robóticos que llevarán estas máquinas a las estrellas. ¡El universo necesita tus ideas, cadete! 🌟"
];

// Patch the modules
let patched = 0;
for (let module of data) {
  if (module.id === 'starwars_sec_1') {
    module.contentEs.sections[0].text = content_sec1;
    patched++;
  }
  if (module.id === 'starwars_sec_2') {
    module.contentEs.sections[0].text = content_sec2;
    patched++;
  }
  if (module.id === 'starwars_sec_3') {
    module.contentEs.sections[0].text = content_sec3;
    patched++;
  }
}

console.log(`Patched ${patched} modules.`);
fs.writeFileSync(filePath, 'export default ' + JSON.stringify(data, null, 2) + ';', 'utf8');
console.log('File written successfully.');
