const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

function replaceSection(src, moduleId, newParagraphs, newQuiz) {
  const moduleStart = src.indexOf(`"id": "${moduleId}"`);
  if (moduleStart === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  const sectionsStart = src.indexOf('"sections"', moduleStart);
  const textStart = src.indexOf('"text"', sectionsStart);
  const arrStart = src.indexOf('[', textStart);
  let depth = 0, i = arrStart;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  const arrEnd = i;
  src = src.slice(0, arrStart) + JSON.stringify(newParagraphs, null, 14) + src.slice(arrEnd + 1);
  if (newQuiz) {
    const quizStart = src.indexOf('"quizEs"', src.indexOf(`"id": "${moduleId}"`));
    const quizArrStart = src.indexOf('[', quizStart);
    let d2 = 0, j = quizArrStart;
    while (j < src.length) {
      if (src[j] === '[') d2++;
      else if (src[j] === ']') { d2--; if (d2 === 0) break; }
      j++;
    }
    src = src.slice(0, quizArrStart) + JSON.stringify(newQuiz, null, 4) + src.slice(j + 1);
  }
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// ====== GALILEO ======

src = replaceSection(src, 'galileo_m1', [
  "¡Bienvenido al laboratorio de Galileo Galilei, cadete inventor! Estamos en Pisa, Italia, año 1609. Un hombre de 45 años sube las escaleras de una torre con un tubo de madera en la mano. Lo apunta al cielo y... el universo nunca vuelve a ser el mismo. Galileo Galilei no inventó el telescopio (eso lo hizo el fabricante de lentes holandés Hans Lippershey en 1608), pero fue el primero en apuntarlo sistemáticamente al cielo nocturno y registrar con rigor científico lo que vio.",
  "El telescopio de Galileo era primitivo comparado con los modernos. Tenía solo 20x de aumento, comparado con los miles de aumentos de los telescopios actuales. Pero fue suficiente para ver cosas que nadie había visto antes: montañas y cráteres en la Luna, manchas oscuras en el Sol, las fases de Venus y cuatro lunas orbitando Júpiter. Cada observación contradecía la cosmología aristotélica que dominaba el pensamiento europeo desde hacía 2,000 años.",
  "Antes de Galileo, el modelo oficial del universo en Europa era el sistema ptolemaico: la Tierra estaba en el centro inmóvil del universo, y el Sol, la Luna, los planetas y las estrellas giraban alrededor de ella en esferas de cristal perfecto. Este modelo venía de Aristóteles (384-322 a.C.) y Claudio Ptolomeo (100-170 d.C.) y había sido adoptado por la Iglesia Católica como parte de su cosmología religiosa. Cuestionarlo era peligroso.",
  "El descubrimiento más revolucionario de Galileo fue ver que la superficie de la Luna no era una esfera perfecta de cristal (como decía Aristóteles) sino un mundo rugoso, lleno de montañas y cráteres, similar a la Tierra. Usando el principio del claroscuro (la forma en que la sombra revela el relieve), midió la altura de las montañas lunares proyectando las sombras que creaban cerca del terminador (la línea que separa la parte iluminada de la oscura). Calculó montañas de 4,000 metros de altura.",
  "Galileo vio que el Sol tenía manchas oscuras en su superficie que cambiaban de día en día y que se movían de un lado al otro del disco solar. Esto era otra prueba de que los objetos celestes no eran perfectos e inmutables como decía Aristóteles. El movimiento de las manchas también le permitió calcular que el Sol rotaba sobre su propio eje en aproximadamente 27 días (el valor moderno es 25-35 días según la latitud solar, porque el Sol no rota igual que un sólido).",
  "Las fases de Venus fueron el golpe de gracia para el modelo geocéntrico. Si Venus orbitara la Tierra (como decía Ptolomeo), solo tendría fases menguantes y crecientes muy pequeñas, porque siempre estaría entre la Tierra y el Sol. Pero Galileo observó que Venus pasaba por todas las fases, incluyendo llena, igual que la Luna. Esto solo era posible si Venus orbitaba alrededor del Sol, pasando a veces del lado iluminado y otras del lado oscuro. La evidencia era irrefutable.",
  "Galileo construyó varios telescopios con sus propias manos, mejorando el diseño cada vez. Aprendió a pulir lentes de vidrio con una precisión que sus contemporáneos no podían igualar. Su mejor telescopio final tenía 33x de aumento. Fabricó telescopios de regalo para el Dux (gobernante) de Venecia y para otros nobles, demostrando prácticamente el valor militar del instrumento para detectar barcos enemigos con horas de anticipación, lo que le ganó el apoyo político y económico que necesitaba.",
  "En 1610, Galileo publicó 'Sidereus Nuncius' (Mensajero Estelar), un pequeño libro de 60 páginas que describía sus descubrimientos telescópicos. Fue un bestseller inmediato: en pocos meses se agotaron las copias en toda Europa. Por primera vez, el público ilustrado europeo leía sobre una nueva visión del universo con evidencia observacional concreta. El libro transformó a Galileo en la celebridad científica más famosa de su época.",
  "El telescopio refractor que Galileo usaba funcionaba con dos lentes: una lente convexa (objetivo) al frente que recogía la luz y la convergiría hacia un punto focal, y una lente ocular cóncava que interceptaba el haz antes del punto focal y lo paralelizaba para que el ojo lo viera como una imagen ampliada. Este diseño, llamado 'telescopio galileano', no invertía la imagen, lo que lo hacía útil también para observaciones terrestres.",
  "El mayor telescopio refractor jamás construido está en el Observatorio Yerkes en Wisconsin, EE.UU., con una lente de 102 cm de diámetro. Pero los telescopios refractores han sido superados por los reflectores, que usan espejos en lugar de lentes. El telescopio espacial James Webb, lanzado en 2021, usa un espejo primario de 6.5 metros de diámetro y puede ver galaxias a más de 13,000 millones de años luz de distancia. De la lente pulida de Galileo al espejo dorado del James Webb: 400 años de progreso tecnológico.",
  "Galileo fue el primero en aplicar el método cuantitativo a la astronomía: no solo describía lo que veía sino que lo medía. Calculó el tamaño aparente de las lunas de Júpiter, el período de sus órbitas, el ángulo de inclinación del eje de la Luna respecto a su órbita. Sus cuadernos de notas están llenos de diagramas y números precisos. Esta combinación de observación sistemática y cuantificación matemática es la base del método científico moderno.",
  "La invención del telescopio dio inicio a la era de la astronomía observacional moderna. Antes del telescopio, los astrónomos como Tycho Brahe medían las posiciones de los planetas a simple vista con instrumentos de extraordinaria precisión pero sin poder ver nada más allá. Con el telescopio, de repente el universo se expandió: había objetos que nunca se habían visto, fenómenos que nadie había sospechado. El cielo pasó de ser una bóveda de puntos de luz a ser un universo poblado de mundos.",
  "Galileo demostró también que el telescopio revelaba estrellas invisibles a simple vista. La Vía Láctea, que parecía ser una nube difusa de luz, se resolvía con el telescopio en millones de estrellas individuales demasiado débiles para verlas sin ayuda. Esta observación fue la primera pista de que el universo era mucho más grande y contenía muchas más estrellas de lo que nadie había imaginado. Dos siglos después, William Herschel contaría miles de esas estrellas para cartografiar nuestra galaxia.",
  "El legado del telescopio de Galileo no fue solo científico sino también filosófico y social. Al demostrar que el cielo era imperfecto y cambiante (manchas solares, montañas lunares, lunas de Júpiter), Galileo socavó la autoridad de Aristóteles y la cosmología eclesiástica. Esto contribuyó a la 'Revolución Científica' del siglo XVII: el proceso por el cual la observación y la experimentación reemplazaron a la autoridad de los textos antiguos como fuente de conocimiento.",
  "Hoy, millones de telescopios de aficionados en todo el mundo permiten que cualquier persona vea lo mismo que vio Galileo en 1609: las lunas de Júpiter, las fases de Venus, los cráteres de la Luna, las manchas solares. Un telescopio básico de 60mm de apertura, que cuesta lo mismo que un libro de texto escolar, muestra el universo de Galileo. La ciencia que comenzó en una torre de Pisa ahora está al alcance de cualquier niño curioso con ganas de mirar hacia arriba."
], null);

src = replaceSection(src, 'galileo_m2', [
  "¡Activa los visores de largo alcance, cadete! El 7 de enero de 1610 fue una noche que cambió la historia de la humanidad. Galileo Galilei apuntó su telescopio hacia Júpiter, el planeta más grande del sistema solar, y vio algo que ningún astrónomo había visto antes: tres pequeñas estrellas alineadas cerca del planeta. Al día siguiente, las tres 'estrellas' habían cambiado de posición. En las noches siguientes, aparecieron cuatro. No eran estrellas: eran lunas orbitando alrededor de Júpiter.",
  "Las cuatro lunas que descubrió Galileo son hoy conocidas como las 'Lunas Galileanas': Ío, Europa, Ganimedes y Calisto. Son mundos fascinantes en sí mismos. Ío tiene los volcanes más activos del sistema solar, constantemente erupcionando por las fuerzas de marea de Júpiter. Europa tiene un océano de agua líquida bajo su superficie de hielo que podría albergar vida. Ganimedes es la luna más grande del sistema solar, mayor que el planeta Mercurio. Calisto es uno de los objetos más craterizado del sistema solar.",
  "El descubrimiento más importante de las lunas de Júpiter no fue científico en sí mismo sino filosófico: demostraron que no todo en el universo orbita alrededor de la Tierra. Si cuatro objetos orbitaban alrededor de Júpiter, entonces el modelo geocéntrico (todo orbita la Tierra) era falso. Era evidencia directa y observable de que el universo era más complejo que lo que la cosmología tradicional europea había asumido.",
  "Galileo observó las lunas de Júpiter noche tras noche durante varios meses, registrando meticulosamente sus posiciones en diagramas. Calculó los períodos orbitales de cada luna: Ío orbita Júpiter en 1.77 días; Europa en 3.55 días; Ganimedes en 7.15 días; Calisto en 16.69 días. Estas medidas son notablemente precisas comparadas con los valores modernos. En diciembre de 1610, tenía suficientes datos para publicar sus resultados en 'Sidereus Nuncius'.",
  "El astrónomo alemán Simon Marius también observó las lunas de Júpiter casi simultáneamente con Galileo y las describió en 1614. Marius propuso los nombres mitológicos actuales de las lunas: Ío, Europa, Ganimedes y Calisto, todos amantes del dios Júpiter en la mitología griega. Galileo prefería llamarlas 'planetas Medicea' en honor a sus mecenas, los Médici de Florencia. La comunidad científica adoptó los nombres de Marius, que son los que usamos hoy.",
  "El período orbital de las lunas Galileanas tiene una relación matemática notable llamada 'resonancia de Laplace'. Los períodos de Ío, Europa y Ganimedes están en proporción exacta de 1:2:4. Por cada vez que Ganimedes orbita Júpiter una vez, Europa lo hace dos veces e Ío cuatro veces. Esta sincronía orbital no es coincidencia sino el resultado de interacciones gravitacionales a lo largo de millones de años que 'afinaron' las órbitas como un instrumento musical. Galileo no lo sabía, pero estaba observando un fenómeno de física orbital de extraordinaria elegancia.",
  "Las fuerzas de marea que Júpiter ejerce sobre Ío son tan intensas que literalmente amasarán el interior de la luna como si fuera plastilina, generando el calor que impulsa sus volcanes. Este calentamiento por mareas es el mismo fenómeno que hace que la Tierra tenga mareas oceánicas causadas por la Luna, pero multiplicado por la inmensa gravedad de Júpiter. La energía que Ío disipa en forma de calor volcánico es equivalente a toda la energía eléctrica que consume la humanidad.",
  "Europa es la luna que más excita a los astrobiólogos (científicos que estudian la posibilidad de vida extraterrestre). Bajo su superficie de hielo de 10-30 km de grosor hay un océano de agua líquida de 100 km de profundidad, con más agua que todos los océanos de la Tierra combinados. El calentamiento por mareas de Júpiter mantiene ese agua líquida. Donde hay agua líquida, energía y ciertos compuestos químicos, la vida como la conocemos puede existir. Europa es el candidato número uno para buscar vida en el sistema solar.",
  "La misión Europa Clipper de la NASA, lanzada en octubre de 2024, llegará a Júpiter en 2030 y realizará 50 sobrevuelos de Europa estudiando su océano subglacial. Otra misión, JUICE (Jupiter Icy Moons Explorer) de la ESA, también está en camino hacia las lunas galileanas. En unas décadas, podremos saber si el océano de Europa alberga microorganismos. Esto comenzó cuando Galileo vio tres puntitos de luz junto a Júpiter en 1610.",
  "Ganimedes, la luna más grande del sistema solar, es más grande que Mercurio aunque menos masiva (porque Mercurio es más denso, principalmente de hierro). Ganimedes tiene su propio campo magnético, algo extremadamente raro para una luna. Este campo magnético crea auroras visibles con el telescopio Hubble en las regiones polares de Ganimedes, un espectáculo de luz que hubiera dejado boquiabierto al propio Galileo.",
  "Calisto es la luna más alejada de Júpiter de las cuatro galileanas y la más craterizada. Su superficie no ha cambiado significativamente en miles de millones de años porque está tan lejos de Júpiter que las fuerzas de marea son demasiado débiles para producir actividad geológica. Es como un fósil del sistema solar primitivo: su superficie muestra cómo eran los mundos rocosos hace 4,000 millones de años. Estudiar Calisto es como leer el primer capítulo de la historia del sistema solar.",
  "Los sistemas de lunas de los planetas gigantes son en cierta forma sistemas solares en miniatura. Júpiter tiene 95 lunas conocidas (al 2024), Saturno tiene 146, Urano 28 y Neptuno 16. Las lunas galileanas son las cuatro más grandes de Júpiter, pero hay decenas de lunas más pequeñas orbitando a mayor distancia. Algunas son asteroides capturados por la gravedad de Júpiter. La familia de las lunas de un planeta gigante refleja la historia de su formación y su interacción con el cinturón de asteroides.",
  "Galileo usó las lunas de Júpiter como un reloj cósmico para resolver un problema práctico crucial: cómo determinar la longitud geográfica en el mar. La longitud (posición este-oeste) se determina comparando la hora local con la hora de un meridiano de referencia. Si un marinero podía saber la hora exacta en, digamos, Madrid, y compararla con la hora local a bordo del barco, podía calcular su longitud. Las lunas de Júpiter, con sus eclipses predecibles, podían servir como reloj universal. En tierra firme, este método funcionó; en barcos que se movían, no fue práctico.",
  "El descubrimiento de las lunas galileanas influyó profundamente en la filosofía de la ciencia. Mostró que el telescopio era una herramienta de descubrimiento legítima, no una fuente de ilusiones ópticas (que era la principal objeción de los conservadores de la época). Mostró también que el universo contenía objetos que no podían verse a simple vista, lo que implicaba que el universo podría ser mucho más grande y complejo de lo que las observaciones directas sugerían. Esta idea de un universo incognoscible por los sentidos sin instrumentos fue revolucionaria.",
  "Hoy, cualquier telescopio de aficionado de 60mm o más puede ver las lunas galileanas de Júpiter, exactamente como las vio Galileo. Aparecen como cuatro puntitos de luz alineados a ambos lados del disco amarillento de Júpiter. Sus posiciones cambian de noche en noche, y en ocasiones pueden verse eclipses (cuando una luna pasa por la sombra de Júpiter) y tránsitos (cuando una luna pasa por el disco de Júpiter). Galileo pasó horas en el frío de la noche italiana observando este espectáculo; tú puedes verlo desde el jardín de tu casa."
], null);

src = replaceSection(src, 'galileo_m3', [
  "¡Prepárate para la batalla más épica entre la ciencia y el dogma, cadete valiente! El proceso de Galileo ante la Inquisición Romana en 1633 es uno de los eventos más famosos y malinterpretados de la historia de la ciencia. No fue simplemente un hombre de ciencia contra una institución religiosa ignorante. Fue una confrontación compleja entre el conocimiento nuevo y las estructuras de poder establecidas, una batalla que Galileo a veces ganó y otras perdió, pero que finalmente dejó una huella imborrable en la historia del pensamiento humano.",
  "Galileo publicó en 1632 su obra maestra 'Diálogo sobre los dos grandes sistemas del mundo' después de años de negociaciones con las autoridades eclesiásticas. El libro presentaba un debate entre tres personajes: Salviati (que defendía el sistema copernicano heliocéntrico), Simplicio (que defendía el sistema ptolemaico geocéntrico) y Sagredo (un observador imparcial). El problema fue que Galileo hizo a Simplicio parecer un tonto y puso en su boca palabras que habían sido dichas por el propio Papa Urbano VIII.",
  "El Papa Urbano VIII se sintió insultado y traicionado. Él mismo había dado permiso a Galileo para escribir el libro, con la condición de que presentara ambos sistemas como hipótesis igualmente válidas sin pronunciarse a favor de ninguno. Galileo no cumplió con esa condición: el libro claramente favorecía el sistema copernicano. El papa, que anteriormente había sido amigo de Galileo, ordenó su comparecencia ante el Tribunal de la Inquisición en Roma.",
  "En 1633, con 69 años y en mal estado de salud, Galileo viajó desde Florencia a Roma para enfrentar el juicio. Fue amenazado con la tortura si no se retractaba. La Inquisición le acusó de haber defendido el heliocentrismo (que la Tierra giraba alrededor del Sol) contra la doctrina de la Iglesia. Bajo estas presiones, Galileo se retractó: declaró públicamente que el sistema copernicano era falso y que la Tierra no se movía. Fue condenado a arresto domiciliario de por vida.",
  "La famosa frase atribuida a Galileo después de su retractación, 'Eppur si muove' (Y sin embargo, se mueve), casi con certeza es apócrifa (inventada posteriormente). No hay evidencia contemporánea de que Galileo la dijera en ese momento, aunque refleja bien la ironía de la situación: que la Tierra se movía independientemente de lo que Galileo dijera o no dijera. La leyenda de esta frase ilustra cómo los momentos históricos importantes se convierten en símbolos que van más allá de los hechos literales.",
  "El arresto domiciliario de Galileo duró hasta su muerte en 1642. Vivió en su villa de Arcetri, cerca de Florencia. A pesar de su condición y de perder la vista en sus últimos años, continuó trabajando. Dictó a sus discípulos sus 'Discursos y demostraciones matemáticas' (1638), un tratado fundamental sobre la ciencia del movimiento y la resistencia de materiales, que muchos consideran más importante que el Diálogo. La Inquisición no pudo detener el pensamiento de Galileo.",
  "La relación de Galileo con la Iglesia fue más compleja de lo que el mito popular sugiere. Galileo era un hombre profundamente religioso. Creía que la Biblia y la naturaleza eran dos 'libros' de Dios y que, cuando parecían contradecirse, era porque la Biblia debía interpretarse metafóricamente. En una famosa carta a la Duquesa Cristina de Lorena (1615), argumentó que la Biblia enseña cómo ir al cielo, no cómo van los cielos, distinción teológica sofisticada que muchos clérigos moderados compartían.",
  "Muchos sacerdotes y cardenales estaban de acuerdo con Galileo. El cardenal Barberini (que más tarde sería el Papa Urbano VIII que lo condenaría) fue su amigo y protector durante años. Los jesuitas del Colegio Romano confirmaron independientemente muchos de sus descubrimientos telescópicos en 1611. El conflicto no fue entre 'la ciencia' y 'la religión' como entidades monolíticas, sino entre Galileo y una facción específica de la Iglesia que interpretaba la Biblia de forma literal y veía el heliocentrismo como una amenaza teológica.",
  "Las consecuencias del proceso de Galileo para la ciencia europea fueron paradójicas. A corto plazo, frenó el desarrollo de la astronomía en Italia (que dejó de ser el centro de la investigación astronómica europea). A largo plazo, aceleró el desarrollo de la ciencia en los países protestantes del norte de Europa (Holanda, Inglaterra, Alemania) donde la Inquisición no tenía poder. Isaac Newton, que nació el mismo año en que murió Galileo (1642), construyó su física sobre los fundamentos que Galileo había establecido.",
  "En 1992, el Papa Juan Pablo II reconoció oficialmente que la Iglesia había cometido un error al condenar a Galileo. La Pontificia Academia de las Ciencias (que tiene su sede en el Vaticano) coordinó una investigación de 13 años sobre el caso Galileo antes de esta declaración. Fue un acto histórico de autocorrección institucional, aunque llegara 350 años tarde. La ciencia y la fe religiosa no son inherentemente contradictorias, pero el proceso de Galileo demostró cuán peligroso puede ser cuando el poder político se mezcla con la interpretación doctrinal.",
  "El juicio a Galileo tuvo consecuencias intelectuales que van más allá de la astronomía. Contribuyó al desarrollo del concepto moderno de libertad de pensamiento y de expresión científica. René Descartes, que vivía en Holanda cuando se enteró de la condena de Galileo en 1633, decidió no publicar su propio trabajo cosmológico 'Le Monde' por temor a represalias. John Milton visitó a Galileo bajo arresto domiciliario y más tarde escribió sobre la 'libertad de imprenta' en su 'Areopagitica'. El caso Galileo fue un catalizador del pensamiento ilustrado.",
  "La Inquisición Romana que juzgó a Galileo era una institución judicial de la Iglesia Católica, establecida en el siglo XIII principalmente para combatir la herejía. En 1633, aún tenía poder real sobre los ciudadanos de los estados pontificios y podía condenar a muerte. Sin embargo, en el caso de Galileo, optó por el arresto domiciliario, posiblemente porque Galileo tenía muchos amigos poderosos que intercedieron por él. El proceso mostró que el poder científico e intelectual podía ser una protección, aunque no siempre suficiente.",
  "Galileo tenía una hija, Suor Maria Celeste (Virginia Galilei en el siglo), que vivía como monja en el convento de San Mateo, cerca de la villa de Arcetri donde Galileo estuvo bajo arresto domiciliario. Los dos mantuvieron una correspondencia extraordinaria: más de 120 cartas de ella a su padre se conservan. Se llamaba a sí misma su 'luz más brillante' y le enviaba comida, ropa y apoyo emocional. Las cartas revelan a un Galileo humano, afectuoso y a veces deprimido, muy diferente del héroe mítico de la historia de la ciencia.",
  "El telescopio Galileo, lanzado por la ESA en 1995 y operado hasta 2003, fue enviado a Júpiter en homenaje al científico. Estudió las lunas galileanas en detalle, descubriendo el océano subterráneo de Europa y los volcanes de Ío. En 2003, cuando se acabó el combustible, fue deliberadamente dirigido para hundirse en la atmósfera de Júpiter, evitando así contaminar las lunas que podría tener vida. Fue un final poético para una misión que celebraba al hombre que primero descubrió esas lunas.",
  "El proceso de Galileo nos enseña que la verdad científica no depende de la autoridad ni del consenso: depende de la evidencia y de la coherencia lógica. Galileo tenía razón sobre el heliocentrismo no porque lo dijera él, sino porque la evidencia observacional lo confirmaba. El universo no pidió permiso a la Inquisición para moverse como se mueve. Esta independencia de la realidad respecto al poder humano es el principio fundamental de la ciencia, y Galileo lo vivió en carne propia."
], null);

src = replaceSection(src, 'galileo_m4', [
  "¡Laboratorio de física en marcha, cadete experimentador! Antes de Galileo, la física del movimiento estaba dominada por Aristóteles, que había propuesto hace 2,000 años que los objetos más pesados caen más rápido que los ligeros. Parecía obvio: una piedra cae más rápido que una pluma. Pero Galileo se preguntó: ¿es esto realmente verdad? ¿O hay algo más que no estamos viendo? Para averiguarlo, decidió hacer algo radical: experimentar.",
  "La famosa historia de Galileo soltando dos bolas de diferente peso desde la Torre de Pisa para demostrar que caen al mismo tiempo es probablemente una leyenda. No hay evidencia directa de que ocurriera. Sin embargo, el principio que ilustra sí lo demostró Galileo, aunque de forma más sofisticada. Usó planos inclinados: hacía rodar bolas de diferente peso por una rampa y medía el tiempo con su pulso o con un reloj de agua. Al reducir la aceleración con la rampa, pudo medir los tiempos con mayor precisión.",
  "Galileo descubrió la Ley de Caída Libre: todos los objetos, independientemente de su masa, caen con la misma aceleración en ausencia de resistencia del aire. La distancia recorrida en caída libre es proporcional al cuadrado del tiempo: si en 1 segundo cae 5 metros, en 2 segundos habrá caído 20 metros (4x más), en 3 segundos 45 metros (9x más). Esta relación cuadrática fue la primera ley matemática del movimiento de la historia, y sentó las bases de la física newtoniana.",
  "La razón por la que Aristóteles se equivocó es la resistencia del aire. Una pluma cae más lento que una piedra no porque sea más liviana sino porque el aire la frena más (tiene más área superficial y menos densidad). En el vacío, ambas caerían a la misma velocidad. El astronauta David Scott demostró esto en la Luna en 1971: soltó simultáneamente un martillo y una pluma desde la misma altura. Ambos cayeron exactamente al mismo tiempo y llegaron juntos al suelo lunar. Galileo tenía razón, Aristóteles estaba equivocado.",
  "Galileo también estudió el movimiento de los proyectiles. Aristóteles creía que un proyectil disparado horizontalmente caía inmediatamente al suelo porque 'ya no tiene nada que lo impulse hacia adelante'. Galileo demostró que el movimiento horizontal y el vertical son independientes: un proyectil disparado horizontalmente cae exactamente igual que uno soltado sin movimiento horizontal, mientras simultáneamente avanza horizontalmente. La trayectoria resultante es una parábola matemática perfecta.",
  "El péndulo fue otra herramienta de investigación de Galileo. Según la leyenda, a los 19 años observó una lámpara columpiándose en la catedral de Pisa y notó algo sorprendente: el período de oscilación (el tiempo en dar un vaivén) era el mismo independientemente de la amplitud (cuánto se desviaba la lámpara). Esto se llama isocronismo del péndulo. Galileo no inventó el reloj de péndulo (eso lo hizo Huygens en 1656), pero descubrió el principio que lo hace funcionar.",
  "El principio de inercia, que Galileo formuló antes que Newton, es uno de los conceptos más contraintuitivos de la física. Según Aristóteles, un objeto que se mueve necesita una fuerza continua para seguir moviéndose. Galileo demostró experimentalmente que esto es falso: un objeto en movimiento continúa moviéndose a velocidad constante a menos que una fuerza actúe sobre él. Si eliminas la fricción (en el hielo, en el espacio), un objeto se mueve indefinidamente sin ninguna fuerza. Este es el origen de la Primera Ley de Newton.",
  "Galileo desarrolló el concepto de 'velocidad relativa', comprendiendo que el movimiento solo puede definirse en relación a un punto de referencia. Si estás en un barco que se mueve a 10 km/h y caminas a 5 km/h en la dirección del barco, tu velocidad respecto al mar es 15 km/h. Pero respecto al barco, solo 5 km/h. Este 'principio de relatividad galileana' fue el precursor directo de la Teoría Especial de la Relatividad de Einstein en 1905.",
  "Los experimentos de Galileo con el plano inclinado son notablemente modernos en su metodología. Usaba el mismo plano para eliminar las variaciones en la inclinación, medía los tiempos con un reloj de agua (midiendo el peso del agua que fluía en un recipiente durante el tiempo del experimento), repetía cada experimento muchas veces para verificar la consistencia, y registraba los resultados numéricamente. Es exactamente el procedimiento que un laboratorio científico moderno seguiría.",
  "El movimiento uniforme (a velocidad constante) y el movimiento uniformemente acelerado fueron las dos categorías que Galileo distinguió y analizó matemáticamente. Para el movimiento uniformemente acelerado (como la caída libre), derivó que la velocidad en cada instante es proporcional al tiempo transcurrido, y la distancia al cuadrado del tiempo. Isaac Newton usó estos resultados de Galileo como punto de partida para desarrollar el cálculo diferencial e integral en la década de 1660.",
  "El concepto de 'experimento mental' también fue desarrollado por Galileo. Cuando no podía hacer un experimento real, imaginaba uno en detalle y razonaba sobre sus resultados. Por ejemplo, imaginó un plano inclinado cada vez más suave: una bola rodando por un plano muy inclinado baja muy rápido, un plano menos inclinado la frena más. ¿Qué pasaría con un plano completamente horizontal? La bola seguiría moviéndose indefinidamente porque no habría nada que la detuviera. Esto lo llevó a enunciar el principio de inercia sin necesitar el experimento real.",
  "La física de Galileo rompió definitivamente con el modo aristotélico de conocer el mundo. Aristóteles deducía las propiedades del movimiento de principios filosóficos generales: 'los objetos pesados tienden naturalmente a caer'. Galileo midió el movimiento, buscó patrones matemáticos en los datos, y construyó leyes a partir de las medidas. Este giro de la deducción filosófica a la inducción experimental es el corazón del método científico moderno.",
  "Las Leyes del Movimiento de Galileo fueron el trampolín directo para Newton. Cuando Newton publicó sus 'Principia Mathematica' en 1687, reconoció explícitamente que estaba construyendo sobre los resultados de Galileo. La Primera Ley de Newton (inercia) es esencialmente la formulación de Galileo refinada. La Segunda Ley (F=ma) generaliza la ley de caída de Galileo. Sin Galileo, Newton habría tenido que empezar desde cero, y sin Newton, toda la física, ingeniería y astronomía modernas habrían tardado siglos más en desarrollarse.",
  "La importancia de los trabajos de mecánica de Galileo va más allá de la física teórica. Sus leyes permiten calcular trayectorias de proyectiles (crucial para la artillería militar de su época), diseñar mecanismos de relojería (el péndulo isócrono), entender las mareas (aunque su teoría de las mareas era incorrecta), y diseñar artefactos mecánicos. La mecánica galileana es la base de toda la ingeniería desde el siglo XVII hasta hoy.",
  "El legado de las leyes del movimiento de Galileo es literalmente universal: se aplican en la Tierra y en el espacio. Los ingenieros que calculan las trayectorias de los cohetes, que diseñan los satélites y que planifican los aterrizajes en Marte usan las ecuaciones que Galileo derivó observando bolas rodar por rampas en su laboratorio de Pisa. Cada nave espacial que despega lleva consigo la física del hombre que, por primera vez, reemplazó la autoridad aristotélica con la evidencia experimental."
], null);

src = replaceSection(src, 'galileo_m5', [
  "¡Última misión galileana, cadete estelar! Galileo Galilei murió en 1642, el mismo año en que nació Isaac Newton. Esta coincidencia parece casi simbólica: como si el antorcha del genio científico pasara directamente de manos de uno al otro. Pero el legado de Galileo en el espacio va mucho más allá de ser el maestro de Newton. Sus ideas, sus instrumentos y su método se han multiplicado durante 400 años hasta llegar a las misiones espaciales más sofisticadas de la humanidad.",
  "La sonda espacial Galileo, lanzada por la NASA en 1989 y operada hasta 2003, fue una misión épica al sistema de Júpiter. Durante 8 años, la sonda realizó 35 sobrevuelos de las lunas galileanas, descubriendo el océano subterráneo de Europa (confirmado por las perturbaciones del campo magnético de Júpiter), la actividad volcánica de Ío (con volcanes activos en tiempo real), y la composición detallada de la atmósfera de Júpiter. La sonda fue nombrada en honor al hombre que descubrió esas lunas con un tubo de cristal en 1610.",
  "El sistema de posicionamiento global europeo se llama 'Galileo' en honor al científico. Este sistema de 30 satélites en órbita, operado por la ESA, proporciona posicionamiento con precisión de centímetros en tierra. El nombre es un homenaje a que Galileo fue el primero en entender la relación entre la observación precisa de posiciones celestes y la determinación exacta de posiciones geográficas en la Tierra. El moderno GPS y su equivalente europeo son, en cierta forma, los herederos de los telescopios galileanos.",
  "La mecánica de Galileo, refinada por Newton y Kepler, es la base de toda la mecánica orbital. Cada vez que la NASA o la ESA calculan la trayectoria de una nave espacial, usan las leyes de movimiento que Galileo comenzó a formular. El principio de inercia de Galileo explica por qué las naves espaciales pueden viajar por el vacío del espacio sin combustible: en ausencia de fricción, un objeto en movimiento continúa moviéndose indefinidamente. Las sondas Voyager 1 y 2, lanzadas en 1977, siguen viajando por el espacio interestelar usando este principio.",
  "El concepto de 'año internacional de la astronomía' fue celebrado en 2009 para conmemorar exactamente 400 años de las primeras observaciones telescópicas de Galileo. Durante ese año, más de 100 millones de personas en 148 países participaron en actividades de astronomía: noches de observación, conferencias, documentales. El evento demostró cuán profundamente el legado de Galileo sigue vivo en la cultura científica global.",
  "Las manchas solares que Galileo observó con su telescopio primitivo son estudiadas hoy por observatorios espaciales como el Solar Dynamics Observatory (SDO) de la NASA, que toma imágenes del Sol en tiempo real con resolución de 0.5 segundos de arco, miles de veces más detallada que lo que Galileo podía ver. El SDO ha confirmado que las manchas solares siguen los ciclos de 11 años que los astrónomos del siglo XIX identificaron, y ha revelado la extraordinaria violencia de las tormentas magnéticas solares.",
  "El principio galileano de que la física es la misma en todos los marcos de referencia inerciales (que se mueven a velocidad constante) fue extendido por Einstein en 1905 a su Teoría Especial de la Relatividad. Einstein añadió a la invariancia galileana la restricción de que la velocidad de la luz es también invariante: la misma para todos los observadores. Esta pequeña adición al principio de Galileo transformó completamente nuestra comprensión del espacio, el tiempo y la materia.",
  "La astronomía moderna en longitudes de onda invisibles (radio, infrarrojo, ultravioleta, rayos X, rayos gamma) es en cierta forma la extensión del telescopio óptico de Galileo. Galileo amplió la percepción humana del universo visible, demostrando que había objetos que los ojos no podían ver sin ayuda. Los radiotelescopios, los observatorios de rayos X como Chandra y los detectores de rayos gamma como Fermi han extendido esa percepción a todo el espectro electromagnético, revelando un universo completamente invisible a los ojos.",
  "Los detectores de ondas gravitacionales como LIGO (Laser Interferometer Gravitational-Wave Observatory) son, conceptualmente, los 'telescopios' de una nueva ventana al universo: no detectan luz sino las ondas en el espacio-tiempo predichas por Einstein. En 2015, LIGO detectó las primeras ondas gravitacionales de la historia, producidas por la fusión de dos agujeros negros hace 1,300 millones de años. Galileo abrió una ventana al universo con su telescopio; LIGO ha abierto una nueva dimensión.",
  "La filosofía científica de Galileo, que combina observación sistemática, cuantificación matemática y experimentación, es el ADN de toda la ciencia moderna. Cada experimento que se hace hoy en un laboratorio, desde la química hasta la biología molecular, sigue los principios metodológicos que Galileo estableció. La ciencia moderna no es solo un conjunto de conocimientos; es una manera de producir conocimiento, y esa manera fue definida en gran medida por Galileo.",
  "El telescopio espacial Hubble, lanzado en 1990, es la realización más completa del sueño de Galileo: un telescopio libre de la distorsión de la atmósfera terrestre, apuntando al universo con claridad perfecta. Ha fotografiado galaxias a 13,000 millones de años luz, nebulosas planetarias de extraordinaria belleza, y ha permitido medir con precisión la tasa de expansión del universo. De los 20x de aumento de Galileo a las imágenes del Hubble: una línea continua de 400 años de progreso óptico.",
  "Galileo fue el primer científico en comunicar sus descubrimientos al público general a través de libros escritos en italiano (no en latín académico). Su 'Diálogo' y sus 'Discursos' estaban escritos en el idioma del pueblo, no en el idioma de los académicos. Esta democratización del conocimiento científico fue tan revolucionaria como sus descubrimientos telescópicos. Hoy, la divulgación científica (en libros, podcasts, videos de YouTube) continúa esa tradición que Galileo comenzó.",
  "La estatua más famosa de Galileo está en la Galleria degli Uffizi de Florencia. Su dedo índice derecho, separado de su cuerpo después de su muerte, se conserva en el Museo Galileo de Florencia, extendido hacia arriba, apuntando al cielo. Es una reliquia que mezcla lo sagrado con lo científico: el dedo que apuntó el telescopio hacia las estrellas, reverenciado como si fuera el dedo de un santo. No hay mejor símbolo del papel casi mítico que Galileo ocupa en la historia de la ciencia.",
  "El impacto de Galileo en la educación es incalculable. Sus experimentos con el plano inclinado y el péndulo son reproducidos en laboratorios de física de todo el mundo por millones de estudiantes cada año. Sus argumentos metodológicos sobre la superioridad de la evidencia experimental sobre la autoridad de los textos son el corazón de cualquier curso introductorio de filosofía de la ciencia. Galileo no es solo un científico histórico: es el maestro de todos los científicos.",
  "El gran legado de Galileo es que demostró que el universo habla el lenguaje de las matemáticas, y que podemos aprender ese lenguaje mirando el mundo con atención y rigor. No necesitamos revelarles a los dioses ni las escrituras: necesitamos observar, medir, calcular y razonar. Esta fue la contribución más profunda de Galileo: no este o aquel descubrimiento específico, sino la convicción de que el conocimiento del universo es alcanzable por la mente humana armada de curiosidad y método."
], null);

fs.writeFileSync(FILE, src, 'utf8');
console.log('All Galileo modules done.');
