const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

function replaceSection(src, moduleId, newParagraphs) {
  const moduleStart = src.indexOf(`"id": "${moduleId}"`);
  if (moduleStart === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  const sectionsStart = src.indexOf('"sections"', moduleStart);
  const textStart = src.indexOf('"text"', sectionsStart);
  const arrStart = src.indexOf('[', textStart);
  let depth = 0, i = arrStart;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  src = src.slice(0, arrStart) + JSON.stringify(newParagraphs, null, 14) + src.slice(i + 1);
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// davinci_m1 — El Hombre Universal
src = replaceSection(src, 'davinci_m1', [
  "¡Bienvenido al estudio del genio más completo de la historia, cadete renacentista! Leonardo da Vinci nació el 15 de abril de 1452, en un pequeño pueblo llamado Vinci, en la Toscana italiana. Fue hijo ilegítimo de Ser Piero da Vinci, un notario respetado, y de una joven campesina llamada Caterina. Aunque su nacimiento fuera del matrimonio significó que no podía heredar los títulos ni las propiedades de su padre, ni asistir a la universidad formal, esto paradójicamente lo liberó: aprendió a observar directamente la naturaleza sin el peso de los libros de texto aristotélicos.",
  "A los 14 años, Leonardo fue enviado como aprendiz al taller del pintor y escultor florentino Andrea del Verrocchio, uno de los artistas más importantes de su época. En aquel tiempo, los talleres de los maestros artistas eran también laboratorios de ciencia aplicada: se usaban instrumentos ópticos, se estudiaban las proporciones del cuerpo humano, se experimentaba con pigmentos y barnices. Leonardo aprendió en este ambiente que el arte y la ciencia no eran campos separados sino aspectos complementarios de la comprensión del mundo.",
  "El término 'hombre del Renacimiento' o 'uomo universale' fue acuñado precisamente para describir el ideal humanista del siglo XV: una persona que domina múltiples campos del saber y los integra en una visión coherente del mundo. Leonardo da Vinci fue la realización más completa de este ideal. Era pintor, escultor, arquitecto, músico, matemático, ingeniero, inventor, anatomista, geólogo, cartógrafo, botánico y escritor. No era un 'generalista' superficial: en cada campo, sus aportes estaban a la vanguardia del conocimiento de su época.",
  "Los cuadernos de Leonardo son el legado científico más valioso que ha sobrevivido del Renacimiento. Leonardo llenó más de 13,000 páginas con anotaciones, observaciones, dibujos técnicos, experimentos, especulaciones filosóficas y diseños de inventos. Escribía en espejo (de derecha a izquierda) y en italiano vernáculo (no en latín académico), lo que ha dado lugar a la especulación de que intentaba proteger sus ideas. Es más probable que escribiera así simplemente porque era zurdo y así evitaba embarrar la tinta.",
  "La 'Última Cena', pintada entre 1495 y 1498 en el refectorio del convento de Santa Maria delle Grazie en Milán, es una de las obras de arte más estudiadas de la historia. Leonardo eligió representar el momento en que Jesús dice 'uno de vosotros me traicionará', capturando las doce reacciones psicológicas diferentes de los apóstoles ante esta revelación. Para lograr este nivel de expresividad, Leonardo estudió durante años la psicología de las emociones humanas, los gestos y las expresiones faciales.",
  "La 'Mona Lisa', pintada entre 1503 y 1519, es la obra de arte más famosa y estudiada del mundo. Lo que la distingue de los retratos anteriores es la técnica del 'sfumato' (italiano para 'evaporado'): Leonardo difumina los contornos de la figura y los paisajes del fondo con transiciones tan graduales que es imposible señalar dónde termina una zona y comienza otra. Esta técnica crea una sensación de atmósfera y de vida que ningún retrato anterior había logrado. La sonrisa de la Mona Lisa es ambigua precisamente por el sfumato: los contornos de las comisuras de la boca están difuminados.",
  "Leonardo tenía una teoría de la percepción óptica que anticipaba las ciencias cognitivas modernas. Entendía que el ojo no ve la realidad directamente sino que la reconstruye a partir de la luz que lo alcanza. Describió fenómenos como la perspectiva aérea (los objetos lejanos parecen más azules y menos contrastados porque la atmósfera dispersa la luz), la irradiación (objetos brillantes parecen más grandes que objetos oscuros del mismo tamaño) y la visión nocturna (la periferia del ojo es más sensible en la oscuridad que el centro).",
  "Como músico, Leonardo diseñó varios instrumentos musicales nuevos, incluyendo un laúd de plata en forma de cráneo de caballo. Era lautista excepcional y poeta improvisado, según los testimonios de sus contemporáneos. La música era para Leonardo la forma de arte más pura porque era fugaz e inmaterial: existía solo en el momento de su ejecución, sin dejar huella física. Esta fugacidad era precisamente lo que la hacía bella a sus ojos: era el arte del tiempo, igual que la pintura era el arte del espacio.",
  "La relación de Leonardo con la geometría era la de un artista-matemático. Ilustró el libro 'De Divina Proportione' del matemático Luca Pacioli con dibujos de sólidos geométricos tridimensionales de extraordinaria precisión y belleza. Estos poliedros (el cubo, el octaedro, el icosaedro, el dodecaedro) representaban la estructura geométrica de los elementos en la filosofía platónica. Leonardo los dibujó con una perspectiva perfecta que les daba apariencia tridimensional, haciendo visibles conceptos que antes eran solo abstractos.",
  "La anatomía fue quizás el campo en que Leonardo más avanzó más allá de sus contemporáneos. Realizó más de 30 disecciones de cadáveres humanos en hospitales florentinos y milaneses, una práctica controvertida pero no ilegal en su época. Sus dibujos anatómicos, redescubiertos siglos después, muestran el corazón, los pulmones, el útero grávido, el cerebro, los músculos y los huesos con una precisión que no fue igualada en la literatura médica hasta el siglo XIX. Describió correctamente el mecanismo de las válvulas cardíacas 400 años antes de que la ciencia médica los confirmara.",
  "Leonardo fue el primer científico en proponer correctamente que los fósiles son restos de organismos vivos, no 'juegos de la naturaleza' ni colocados por Dios durante el Diluvio Universal (las dos explicaciones dominantes de su época). Observó que los fósiles de conchas marinas se encontraban en los Apeninos, a cientos de metros de altitud, y razonó que el mar debía haber cubierto esas montañas en algún momento del pasado remoto. Esta intuición de que la Tierra tiene una historia geológica larga precedió por más de un siglo a los primeros geólogos sistemáticos.",
  "La perspectiva matemática en la pintura fue desarrollada en Florencia a principios del siglo XV por Filippo Brunelleschi y Filippo Alberti. Leonardo la dominó completamente y la llevó más allá: estudió la perspectiva aérea (ya mencionada), la perspectiva de color (objetos lejanos pierden saturación), y desarrolló la 'perspectiva isométrica' para sus dibujos técnicos, donde las líneas paralelas permanecen paralelas en lugar de converger en un punto de fuga. Esta técnica, usada hoy en dibujos de ingeniería, fue inventada o redescubierta por Leonardo.",
  "La relación de Leonardo con sus mecenas (patrocinadores) fue compleja y a veces tumultuosa. Trabajó para Lorenzo de Medici en Florencia, Ludovico Sforza en Milán, Cesare Borgia como ingeniero militar, los papas Julio II y León X en Roma, y finalmente para el rey Francisco I de Francia. Cada patrón quería obras de arte terminadas; Leonardo siempre tenía docenas de proyectos en desarrollo simultáneamente y raramente terminaba los encargos en los plazos prometidos. Su perfeccionismo y su curiosidad insaciable eran incompatibles con las demandas de la producción artística comercial.",
  "Los últimos tres años de la vida de Leonardo (1516-1519) los pasó en el Château de Clos Lucé, en Amboise, Francia, como 'primer pintor, arquitecto e ingeniero del rey' Francisco I. El rey lo admiraba profundamente y le daba una pensión generosa sin exigirle producción específica. En este período, Leonardo continuó organizando sus cuadernos sin llegar a publicarlos. Murió el 2 de mayo de 1519, según el testimonio de Francisco I, en los brazos del propio rey. Tenía 67 años.",
  "El legado de Leonardo da Vinci es que demostró que la frontera entre el arte y la ciencia es artificial. Para Leonardo, ambas eran formas de comprender y representar la realidad. El artista necesita entender la anatomía, la óptica, la geometría y la física para representar el mundo con verdad. El científico necesita la capacidad de observación, la creatividad y la representación visual del artista para descubrir y comunicar sus hallazgos. La separación entre las 'dos culturas' (humanidades y ciencias) que el siglo XX convirtió en dogma era, para Leonardo, una absurdidad. Tenía razón."
]);

// davinci_m2 — Vuelo de Aves y Máquinas Voladoras
src = replaceSection(src, 'davinci_m2', [
  "¡Despliega las alas del conocimiento, cadete inventor! El sueño de volar fue la obsesión más persistente de Leonardo da Vinci durante toda su vida. En sus cuadernos hay más de 500 dibujos relacionados con el vuelo de aves e insectos y con el diseño de máquinas voladoras. Leonardo fue el primero en tratar el problema del vuelo como un desafío científico y de ingeniería, no como una fantasía o un milagro divino, y sus intuiciones sobre la aerodinámica anticiparon principios que la ciencia no formalizaría hasta 400 años después.",
  "La observación de aves fue el punto de partida de Leonardo. Pasó horas innumerables observando cómo vuelan los pájaros: cómo despliegan y doblan sus alas, cómo cambian la curvatura de las plumas para controlar la sustentación y el planeo, cómo usan las corrientes térmicas ascendentes para ganar altitud sin esfuerzo. Sus dibujos de aves en vuelo son los primeros estudios sistemáticos de aerodinámica de la historia, aunque la palabra 'aerodinámica' no existiera hasta el siglo XIX.",
  "Leonardo entendió intuitivamente el principio de Bernoulli, que no sería formulado matemáticamente hasta 1738. El principio establece que cuando el aire fluye más rápido sobre una superficie curvada (como la parte superior del ala), la presión es menor, creando sustentación. Leonardo describió este fenómeno en sus notas: 'El pájaro es un instrumento que funciona de acuerdo con la ley matemática, y es posible al hombre fabricar todos sus movimientos, pero no con la misma potencia'. Sabía que el vuelo era física, no magia.",
  "El 'ornitóptero' fue el primer diseño de máquina voladora de Leonardo: una máquina con alas articuladas movidas por la fuerza muscular humana, inspirada directamente en el vuelo de los pájaros y murciélagos. El problema es que la potencia muscular humana es insuficiente para generar sustentación con un ala batiente del tamaño necesario para sostener un ser humano. Incluso con los materiales modernos más ligeros, este principio no es viable. Leonardo intuía esta limitación y eventualmente exploraron diseños alternativos.",
  "La máquina voladora con forma de tornillo helicoidal, el 'tornillo aéreo', es uno de los diseños más famosos de Leonardo. Consiste en una hélice en espiral de lino encolado sobre un armazón de alambre de hierro. La idea era que al girar, la hélice 'atornillaría' el aire hacia arriba, generando sustentación. Este principio es correcto en teoría: es el mismo que usan los helicópteros modernos. El problema de Leonardo era la fuente de energía: girar la hélice con suficiente velocidad para generar sustentación requería una potencia que ningún motor de su época podía proporcionar.",
  "El planeador de Leonardo, diseñado hacia 1485, es el más avanzado de sus conceptos de vuelo. A diferencia de los ornitópteros (que intentan batir alas), el planeador usa alas fijas y aprovecha las corrientes de aire para mantenerse en el aire. El diseño muestra alas con una forma curvada (perfil de ala) que sugiere que Leonardo entendía la importancia de la curvatura alar para generar sustentación. Este principio, el perfil aerodinámico, es la base de todas las alas de avión modernas.",
  "Leonardo diseñó también el primer paracaídas de la historia, aunque fuera redescubierto independientemente por otros inventores siglos después. Su diseño mostraba una pirámide de lino de cuatro metros de lado que permitiría a un hombre 'lanzarse desde cualquier gran altura sin ningún daño'. En 2000, el aventurero suizo Adrian Nicholas saltó desde 3,000 metros con una réplica exacta del paracaídas de Leonardo y aterrizó suavemente. El diseño, con 500 años de antigüedad, funcionó perfectamente.",
  "El 'carro de asalto', diseñado por Leonardo para Ludovico Sforza, muestra su comprensión del movimiento y la mecánica aplicada a la guerra. Era una plataforma circular con cañones apuntando en todas direcciones, tirada por caballos. El diseño incluye un detalle curioso: los engranajes del mecanismo de tracción están orientados de manera que las ruedas no puedan moverse. Algunos investigadores creen que Leonardo lo hizo deliberadamente, saboteando su propio diseño para que no fuera usado como arma de destrucción masiva.",
  "El helicóptero moderno usa el principio del tornillo aéreo de Leonardo, aunque con motores de gas o eléctricos en lugar de fuerza muscular. El primer helicóptero que voló con éxito fue el VS-300 de Igor Sikorsky en 1939. Sin embargo, en el año 2000, el inventor británico Paul MacCready construyó un helicóptero impulsado exclusivamente por energía muscular (el 'Snowbird') que logró volar brevemente. El límite de la potencia muscular para el vuelo que Leonardo intuía fue así confirmado y también vencido, usando los materiales ultraligeros del siglo XXI.",
  "Los hermanos Wright, que realizaron el primer vuelo motorizado de la historia en 1903, también comenzaron su investigación observando aves y estudiando la curvatura de sus alas. Sin saber nada de los cuadernos de Leonardo (que estaban dispersos en colecciones privadas y no habían sido sistematizados), llegaron a conclusiones similares sobre la importancia del perfil aerodinámico y el control de la torsión del ala para maniobrar. La convergencia entre Leonardo y los Wright es un ejemplo de cómo la observación sistemática de la naturaleza conduce a las mismas verdades.",
  "Leonardo estudió también el vuelo de los insectos, mucho más difícil de analizar por su velocidad. Describió correctamente que las libélulas usan sus cuatro alas de manera independiente, pudiendo volar hacia adelante, atrás y lateralmente. Los insectos 'recogen el aire bajo sus alas' y sus movimientos de alas crean sustentación y propulsión simultáneamente. Los entomólogos modernos usan cámaras de alta velocidad (miles de fotogramas por segundo) para estudiar el vuelo de los insectos en detalle, confirmando y refinando las observaciones de Leonardo.",
  "El concepto de 'resistencia aerodinámica' (el arrastre que el aire ejerce sobre un objeto en movimiento) fue intuido por Leonardo. Observó que los objetos de punta redondeada pasaban más fácilmente por el agua que los de punta plana. Describió que el aire 'se cierra detrás del objeto que lo penetra', sugiriendo que entendía la formación de turbulencias. El diseño 'aerodinámico' (aerodinámico en el sentido moderno) de las cabezas de las aves y los cuerpos de los peces fue observado y anotado por Leonardo como principio de diseño óptimo.",
  "Las máquinas voladoras de Leonardo fueron redescubiertas sistemáticamente en el siglo XX cuando sus cuadernos fueron publicados y estudiados. Los ingenieros quedaron asombrados al ver que muchos conceptos aparentemente modernos habían sido esbozados 400-500 años antes. El artista y científico francés Pierre Sabatier construyó réplicas funcionales de varios diseños de Leonardo en la década de 1960 y demostró que varios de ellos, aunque no podían volar por falta de motor apropiado, eran aerodinámicamente sólidos.",
  "El mayor obstáculo para los diseños de vuelo de Leonardo era la fuente de energía. Los motores de vapor no fueron inventados hasta el siglo XVIII; los motores de gasolina, hasta el siglo XIX; los motores eléctricos ligeros, hasta el siglo XX. Sin una fuente de potencia adecuada, incluso el diseño más brillante es solo un papel. Este es el patrón recurrente en la obra inventiva de Leonardo: las ideas estaban correctas, pero la tecnología de materiales y energía de su época no podía realizarlas. La ingeniería siempre está limitada por la física disponible.",
  "El legado del trabajo de vuelo de Leonardo es que fue el primero en tratar el vuelo como un problema de física e ingeniería abordable con método y observación. Antes de Leonardo, volar era el dominio de los dioses y los ángeles, no de los hombres. Después de Leonardo, era un problema técnico que esperaba la solución técnica correcta. Esta secularización del sueño del vuelo fue tan importante como los diseños específicos: abrió el camino mental para que, 400 años después, los hermanos Wright construyeran lo que Leonardo había dibujado."
]);

// davinci_m3 — Anatomía y el Cuerpo Como Máquina
src = replaceSection(src, 'davinci_m3', [
  "¡Prepara el escáner de anatomía, cadete médico! En el renacimiento italiano, diseccionar cadáveres humanos era una práctica que requería permisos especiales y era mal vista por muchos. Sin embargo, Leonardo da Vinci realizó más de 30 disecciones, trabajando muchas noches en hospitales y estudios. Lo hacía no para curiosidad morbosa sino movido por una convicción científica: entender cómo funciona el cuerpo humano era inseparable de entender cómo pintarlo con verdad. La anatomía era para Leonardo ciencia y arte simultáneamente.",
  "Los dibujos anatómicos de Leonardo, redescubiertos en el siglo XIX, dejaron atónitos a los médicos modernos. En ellos se veían representaciones del corazón, los pulmones, el cerebro, el útero grávido, los riñones, los ojos y el sistema vascular con un nivel de detalle y precisión que no fue igualado en la literatura médica hasta el siglo XIX, con el microscopio óptico. Leonardo dibujó el corazón desde múltiples ángulos, en sección transversal y longitudinal, mostrando las cuatro cavidades, las válvulas y los grandes vasos.",
  "El corazón fue uno de los grandes objetos de estudio de Leonardo. Fue el primero en describir correctamente el mecanismo de las válvulas cardíacas: propuso que los 'senos de Valsalva' (los espacios detrás de las valvas de la válvula aórtica) se llenaban de sangre cuando la válvula se abría, y esa sangre al caer de vuelta cerraba la válvula. Este mecanismo, descubierto por Leonardo hace 500 años, fue confirmado experimentalmente en el siglo XX usando modelos de vidrio y fluidos coloreados. Hoy se usa para diseñar mejores válvulas cardíacas artificiales.",
  "Leonardo fue pionero en el estudio del sistema vascular (arterias y venas). Notó que las arterias de los cadáveres de personas mayores tenían paredes más gruesas y endurecidas que las de los jóvenes, y lo describió como 'el envejecimiento del árbol de la vida'. Estaba describiendo la arteriosclerosis, aunque sin ese nombre. También estudió la circulación sanguínea, aunque no llegó a comprender el circuito completo que Harvey describiría en 1628: Leonardo aún seguía parcialmente la teoría galena que veía al hígado como el origen de la sangre.",
  "El estudio del cerebro por Leonardo incluye representaciones de los ventrículos cerebrales (las cavidades llenas de líquido cerebroespinal) que obtuvo inyectando cera fundida en el cerebro de un buey. Al solidificarse la cera y disolver el tejido circundante, obtuvo un molde preciso de las cavidades ventriculares. Esta técnica de crear moldes en cavidades anatómicas fue reinventada independientemente en el siglo XX para estudiar los vasos sanguíneos y los pulmones. Leonardo la usó 500 años antes.",
  "Los dibujos del feto en el útero son quizás los más famosos de los dibujos anatómicos de Leonardo. Muestran al feto en posición fetal correcta, con el cordón umbilical visible y la placenta en su lugar. El nivel de detalle es asombroso para la época. Sin embargo, hay un error: Leonardo representó la placenta humana con cotiledones (como en el ganado bovino que probablemente diseccionó con más frecuencia), cuando en realidad la placenta humana es discoidal y no tiene cotiledones. Es un ejemplo de cómo incluso el observador más cuidadoso puede ser llevado a error por sus fuentes anteriores.",
  "La representación de los músculos fue otro campo en que Leonardo revolucionó la anatomía. Desarrolló la técnica de mostrar los músculos en 'capas': primero el esqueleto, luego los músculos profundos, luego los músculos superficiales, y finalmente la figura completa. Esta técnica 'de capas' se usa hoy en los atlas de anatomía modernos (como el 'Gray's Anatomy'). Leonardo también fue el primero en representar los músculos en acción, mostrando cuáles se contraen y cuáles se relajan en diferentes movimientos.",
  "La visión de Leonardo del cuerpo humano era mecánica: veía los huesos como palancas, los músculos como cuerdas que tiraban de esas palancas, y las articulaciones como poleas y bisagras. Esta metáfora mecanicista del cuerpo, que hoy nos parece obvia, era revolucionaria en el siglo XV. La medicina medieval veía el cuerpo en términos de 'humores' (líquidos corporales) y energías espirituales. Leonardo fue uno de los primeros en pensar en el cuerpo como una máquina gobernada por las mismas leyes físicas que las palancas y las poleas.",
  "Los ojos fueron otro gran objeto de estudio. Leonardo fue el primero en describir correctamente la estructura del ojo como una cámara oscura: la luz entra a través de la pupila (la apertura), es refractada por el cristalino (la lente) y forma una imagen invertida en la retina. Pero se confundió: pensó que había un segundo mecanismo que reinvertía la imagen para que la percibamos correctamente. Hoy sabemos que la inversión y corrección de la imagen ocurre en el cerebro, no en el ojo mismo.",
  "La neurología de Leonardo estaba limitada por las herramientas de su época. No podía ver las neuronas (demasiado pequeñas para el ojo desnudo), así que razonó sobre la función del sistema nervioso basándose en observaciones de comportamiento y en sus disecciones del cerebro. Identificó correctamente que el cerebro (no el corazón, como se creía) era la sede del pensamiento y la percepción. También describió los nervios como canales por los que viajaba el 'spirito animale' (un concepto que anticipaba vagamente la transmisión nerviosa eléctrica).",
  "Los estudios de Leonardo sobre la locomoción humana y animal son extraordinariamente modernos. Analizó cómo un hombre se levanta de una silla, cómo sube escaleras, cómo corre y cómo salta. Observó que cuando un hombre camina, su centro de gravedad se desplaza lateralmente de un lado al otro. Estos estudios del movimiento no eran solo para la anatomía: Leonardo los aplicaba directamente a sus pinturas y esculturas para darles verosimilitud y vida. La 'biomecánica', campo científico que existe desde el siglo XIX, fue anticipada por Leonardo 400 años antes.",
  "Los dibujos de Leonardo a menudo incluyen múltiples vistas del mismo órgano o estructura: frontal, lateral, posterior, en sección. Esta representación desde múltiples ángulos, que hoy llamamos 'vistas ortogonales', fue inventada o reinventada por Leonardo para la anatomía. En los planos de arquitectura e ingeniería, usó el mismo principio: plantas, alzados y secciones. Esta manera sistemática de representar objetos tridimensionales en papel bidimensional es la base del dibujo técnico moderno, tanto arquitectónico como de ingeniería.",
  "La patología también interesó a Leonardo. Examinó el corazón y los vasos sanguíneos de personas mayores y describió el endurecimiento de las arterias. Examinó hígados con cirrosis y describió correctamente los cambios patológicos que observó. Estudió la estructura del hueso y describió el tejido esponjoso interior y el tejido compacto exterior. Estas observaciones de patología, basadas en disecciones directas, eran radicalmente más precisas que las enseñanzas médicas de la época, que seguían a Galeno (siglo II d.C.) sin haberlo cuestionado.",
  "El impacto de la anatomía de Leonardo en la medicina habría sido inmenso si sus cuadernos hubieran sido publicados. Pero Leonardo nunca publicó sus notas anatómicas. A su muerte, los cuadernos pasaron a manos de su discípulo Francesco Melzi, quien los mantuvo juntos. Después de la muerte de Melzi, la colección se dispersó y la mayor parte fue a parar a la colección real española y luego a la biblioteca del rey de Inglaterra, donde permanecieron sin estudiar hasta el siglo XVII. La medicina del siglo XVI se perdió los descubrimientos de Leonardo y tuvo que redescubrirlos.",
  "El legado de la anatomía de Leonardo es que mostró que el cuerpo humano puede y debe ser estudiado con el mismo rigor y la misma metodología que cualquier otro fenómeno natural. La disección sistemática, la representación detallada y el razonamiento mecanicista sobre el cuerpo transformaron la medicina. La anatomía de Vesalius (1543), considerada la fundación de la anatomía moderna, fue posterior a los trabajos de Leonardo y probablemente influenciada por ellos. El cuerpo humano como objeto de estudio científico riguroso comenzó en el estudio de Leonardo."
]);

// davinci_m4 — Máquinas e Inventos: El Ingeniero del Futuro
src = replaceSection(src, 'davinci_m4', [
  "¡Activa los talleres de ingeniería, cadete! Leonardo da Vinci no era solo un artista y anatomista: era un ingeniero apasionado que diseñó máquinas para casi todas las necesidades de su época y muchas más que su época no podía imaginar. Sus cuadernos contienen más de 200 diseños de máquinas diferentes, desde herramientas de taller simples hasta vehículos automáticos y robots. Muchos de estos diseños anticiparon inventos que no serían realizados hasta siglos después, demostrando que la imaginación del ingeniero puede correr muy por delante de las capacidades tecnológicas de su momento.",
  "El carro automotriz de Leonardo (hacia 1478) es considerado el primer diseño de un vehículo autopropulsado de la historia. Funcionaba mediante resortes de ballesta pretensos: al liberarse, los resortes hacían girar las ruedas a través de un sistema de engranajes. Un mecanismo de leva permitía programar giros a izquierda y derecha. En 2004, ingenieros del Museo de Historia de la Ciencia de Florencia construyeron una réplica funcional y comprobaron que el carro efectivamente se movía solo, con la trayectoria programada. Es el primer 'robot' automotriz de la historia.",
  "El puente giratorio de Leonardo era un puente militar que podía montarse y desmontarse rápidamente para permitir el paso de tropas. Se inspiró en los puentes de cuerda de las regiones montañosas de Italia. El diseño usaba poleas y cuerdas para girar el puente en torno a un pivote, permitiendo cruzar un río en minutos. Leonardo también diseñó un puente que podría ser desmontado y transportado por los soldados, un 'puente portátil' que fue redescubierto y usado en campaña durante la Segunda Guerra Mundial.",
  "El robot caballero, conocido solo por un conjunto de diagramas sin nombre específico en los cuadernos, fue redescubierto en 2002 por el roboticista de la NASA Mark Rosheim. Los diagramas muestran un caballero con armadura capaz de sentarse, agitar los brazos, girar la cabeza y abrir y cerrar la mandíbula, accionado por un sistema de cables y poleas desde el exterior. Era posiblemente una exhibición de entretenimiento para los banquetes de los Sforza en Milán. Rosheim construyó una réplica funcional y confirmó que el diseño era mecánicamente coherente.",
  "Las armas de guerra diseñadas por Leonardo para sus patrocinadores militares son una de las secciones más ambivalentes de su obra. Diseñó cañones de múltiple cañón (antecesores de las ametralladoras), bombardas gigantes, barcos acorazados y sistemas de trincheras defensivas. Sin embargo, en sus cuadernos escribió que guardaba deliberadamente en secreto ciertas invenciones de destrucción 'por la naturaleza bestial de los hombres'. Es posible que el error deliberado en los engranajes del carro de asalto sea otro ejemplo de este sabotaje ético.",
  "El reloj de agua de Leonardo es un ejemplo de su habilidad para mejorar tecnologías existentes. Los relojes de agua (clepsidras) existían desde la antigüedad, pero perdían precisión porque el flujo del agua varía con el nivel del tanque. Leonardo diseñó un sistema con un tanque secundario que mantenía el nivel del agua constante mediante un flotador, garantizando un flujo uniforme. Es el mismo principio que hoy se usa en los depósitos de los inodoros para mantener el nivel de agua constante.",
  "La fresadora continua diseñada por Leonardo para trabajar el mármol muestra su comprensión de los procesos de manufactura repetitivos. La máquina usaba una serie de cinceles o fresas montadas en un arco rotatorio que cortaban el mármol en un patrón continuo. Este principio del corte continuo (en lugar del corte golpe a golpe del cincel manual) es el fundamento de todas las fresadoras y tornos modernos de control numérico (CNC). Las piezas de metal y plástico de los coches y aviones se hacen hoy con máquinas que usan el principio que Leonardo esbozó.",
  "La excavadora de canales fue uno de los diseños de ingeniería civil más ambiciosos de Leonardo. Fue diseñada para el proyecto de Ludovico Sforza de modificar el curso del río Arno. La máquina usaba una serie de palas articuladas movidas por poleas y palancas para excavar tierra y depositarla a los lados. El proyecto del Arno nunca se llevó a cabo, pero el diseño de la excavadora anticipaba los principios de las excavadoras modernas de cadenas y cangilones que se usaron a finales del siglo XIX para construir el Canal de Panamá.",
  "El molino de viento horizontal de Leonardo es notable porque anticipa el principio de las turbinas eólicas modernas. Las turbinas de viento medievales (las que vemos en los paisajes de Holanda) tienen aspas verticales que giran en torno a un eje horizontal. El diseño de Leonardo tenía aspas horizontales que giraban en torno a un eje vertical, lo que tiene la ventaja de no necesitar alinearse con la dirección del viento. Las turbinas eólicas de eje vertical modernas (como las turbinas de tipo Darrieus) usan exactamente este principio.",
  "La grúa rotatoria de 360 grados diseñada por Leonardo para la construcción fue usada (o al menos fue propuesta) para la construcción de edificios en Milán. Permitía levantar materiales pesados y depositarlos en cualquier ángulo en torno al eje de la grúa, sin necesitar mover la base. Las grúas de torre de la construcción moderna funcionan con el mismo principio: un brazo horizontal giratorio que puede alcanzar cualquier punto del área de obra sin mover la estructura de soporte.",
  "La imprenta de texto era conocida en Europa desde 1440 (Gutenberg), pero Leonardo diseñó una versión mejorada para la impresión de textos e imágenes. Su diseño incluía un sistema de entintado automático de los tipos, una prensa de tornillo mejorada y un mecanismo de avance del papel. Aunque no construyó esta máquina, el diseño muestra que entendía el principio de la impresión mecánica y lo mejoraría con sus conocimientos de mecanismos.",
  "Los instrumentos musicales que Leonardo diseñó incluyen no solo mejoras de instrumentos existentes sino instrumentos completamente nuevos. El 'viola organista' (reconstruido en 2013 por el pianista polaco Slawomir Zubrzycki) era una combinación de teclado y cuerda frotada: al pulsar las teclas, se accionaban ruedas de crin que frotaban cuerdas de diferente longitud, produciendo sonidos similares a los de un violonchelo pero controlados por teclado. El instrumento fue tocado en públicos por primera vez en 500 años en 2013.",
  "La máquina de hilado de Leonardo automatizaba el proceso de hilar fibras (lana o lino) en hilo. El hilado manual (con rueca y huso) era uno de los trabajos más laboriosos de la Europa preindustrial. La máquina de Leonardo usaba un sistema de poleas y engranajes para alimentar la fibra, girar el huso y enrollar el hilo producido en una bobina, todo simultáneamente y de manera continua. La 'spinning jenny' de James Hargreaves (1764), que inició la Revolución Industrial textil, usa principios similares.",
  "El submarino o 'barco sumergible' fue otro concepto de Leonardo, aunque solo dejó fragmentos de dibujos y describió haberlo pensado sin revelar los detalles 'por la maldad de los hombres que podrían usarlo para hundir barcos'. Este ejemplo de auto-censura científica muestra que Leonardo era consciente de las implicaciones éticas de sus inventos: no todo lo que se puede diseñar debe construirse. La historia de la bomba atómica, siglos después, daría la razón a su preocupación.",
  "El legado de las máquinas de Leonardo es que transformó la ingeniería de un oficio artesanal en una disciplina intelectual. Antes de Leonardo, las máquinas se construían por tradición y ensayo-error. Leonardo las diseñaba en papel con precisión matemática antes de construirlas, analizando las fuerzas, los engranajes, las palancas y las poleas de manera sistemática. Este enfoque 'de diseño' de la ingeniería, que hoy llamamos 'diseño asistido por computadora' (CAD), tiene en los cuadernos de Leonardo su primer ejemplo sistemático."
]);

// davinci_m5 — Arte, Ciencia y la Visión del Cosmos
src = replaceSection(src, 'davinci_m5', [
  "¡Última misión leonardesca, cadete filósofo! Para cerrar nuestro viaje por el universo de Leonardo da Vinci, vamos a explorar su visión más profunda: la relación entre el arte, la ciencia y el cosmos. Leonardo no veía el mundo como un conjunto de disciplinas separadas (la pintura, la música, la mecánica, la astronomía) sino como un sistema integrado donde los mismos principios matemáticos y geométricos se repetían en todas las escalas: desde la espiral de un caracol hasta la espiral de una galaxia, desde el flujo del río hasta el flujo de la sangre en las arterias.",
  "La proporción áurea (Φ ≈ 1.618) y la secuencia de Fibonacci aparecen repetidamente en la naturaleza: en los espirales de las conchas de nautilo, en la distribución de las semillas en un girasol, en la ramificación de los árboles, en la proporción de las extremidades del cuerpo humano. Leonardo era profundamente consciente de estos patrones y los buscaba activamente en todo lo que observaba. Su ilustración del 'Hombre de Vitruvio' (1490) es la representación más famosa de la armonía matemática del cuerpo humano.",
  "El 'Hombre de Vitruvio' de Leonardo muestra un hombre con los brazos y piernas extendidos, inscrito en un círculo y un cuadrado. Las proporciones del cuerpo muestran que la envergadura de los brazos es igual a la altura del cuerpo (relación 1:1), que el ombligo es el centro del círculo y que el cuerpo puede dividirse en proporciones simples (la altura total = 8 cabezas; la cabeza = 1/8 del cuerpo; etc.). Leonardo tomó el texto del arquitecto romano Vitruvio (siglo I a.C.) y lo refinó con sus propias medidas de cuerpos reales.",
  "La perspectiva atmosférica que Leonardo desarrolló en su pintura refleja su comprensión de la física de la luz. Los objetos lejanos parecen más azulados y difusos porque las partículas del aire dispersan la luz azul más que la roja (el mismo fenómeno que hace que el cielo sea azul y los atardeceres sean rojos). Leonardo fue el primero en aplicar sistemáticamente este principio a la pintura, creando la ilusión de profundidad y distancia que caracteriza sus fondos paisajísticos, especialmente en la Mona Lisa.",
  "El agua fue uno de los grandes objetos de estudio de Leonardo. Pasó años observando el flujo del agua en ríos, el movimiento de las olas, los remolinos, las cascadas y las corrientes submarinas. Sus dibujos de flujo de agua son los primeros estudios sistemáticos de hidrodinámica de la historia. Reconoció que el agua sigue patrones geométricos repetibles: los remolinos forman espirales; el agua que choca con un obstáculo crea formas específicas que dependen de la velocidad y el ángulo de impacto.",
  "La analogía entre el flujo del agua y el flujo del aire fue uno de los grandes insights de Leonardo para su estudio del vuelo. Si el agua sigue patrones predecibles al pasar alrededor de un objeto, el aire debe hacer lo mismo. Esta analogía entre la hidrodinámica y la aerodinámica es completamente correcta: los ingenieros modernos usan túneles de agua (con tintes de color) además de túneles de viento para estudiar el flujo alrededor de objetos, porque los patrones de flujo son matemáticamente equivalentes a velocidades similares.",
  "Los estudios de Leonardo sobre las nubes, la lluvia, el granizo y la nieve son otro ejemplo de su enfoque unificado de los fenómenos naturales. Observó que las nubes tienen formas fractales: a diferentes escalas de observación, muestran la misma complejidad estructural. El concepto de fractal (una figura que se repite a diferentes escalas) fue formalizado matemáticamente por Benoit Mandelbrot en 1975, pero Leonardo lo vio 500 años antes sin tener las matemáticas para formalizarlo.",
  "La geología fue otra disciplina que Leonardo practicó antes de que existiera como ciencia formal. Reconoció que las capas de roca sedimentaria eran depósitos de materiales en fondos de antiguos mares o lagos, y que las montañas se formaban por la elevación de estos fondos marinos a lo largo de enormes períodos de tiempo. Describió que los fósiles marinos en las cimas de los Apeninos eran evidencia directa de que esas montañas habían estado bajo el agua. Estas ideas de Leonardo son correctas y anticipan la geología moderna en más de 200 años.",
  "La astronomía interesó a Leonardo aunque no fue su campo principal. Observó la Luna y notó que 'el brillo de la Luna no es su propio' sino reflejo del Sol. Describió el fenómeno de la 'luz cenicienta' (la parte de la Luna no iluminada directamente por el Sol que aparece ligeramente brillante): esta luz es el reflejo de la Tierra sobre la Luna, el mismo fenómeno que el 'resplandor de la Tierra' que los astronautas del Apolo vieron desde la Luna. Leonardo lo explicó correctamente.",
  "La búsqueda de las leyes universales de la naturaleza fue el hilo conductor de toda la obra científica de Leonardo. Creía que la naturaleza seguía principios matemáticos simples y elegantes que se repetían en todas las escalas y en todos los fenómenos. 'La necesidad es la madrastra de la naturaleza', escribió, expresando su convicción de que la naturaleza siempre elige la solución más eficiente y económica. Este principio, que hoy llamamos 'principio de economía de la naturaleza', es la intuición detrás del cálculo variacional y el principio de mínima acción de la física moderna.",
  "El conflicto entre la visión artística y la visión científica del mundo fue irrelevante para Leonardo porque, para él, ambas buscaban lo mismo: la verdad de la naturaleza. El artista que no entiende la anatomía pinta figuras falsas. El científico que no puede representar claramente sus observaciones no puede comunicarlas. La síntesis entre el rigor del análisis científico y la sensibilidad de la representación artística era para Leonardo no solo posible sino necesaria. Esta síntesis es la que define el 'estilo leonardesco' en sus cuadernos.",
  "Los escritos de Leonardo contienen reflexiones filosóficas sobre la naturaleza del conocimiento que son sorprendentemente modernas. 'La experiencia es la madre de toda certeza', escribió, anticipando el empirismo de Locke y Hume 200 años después. 'Quien discute citando la autoridad no usa la mente sino la memoria', anticipando la crítica ilustrada de la autoridad. 'La ciencia es el capitán y la práctica son los soldados', describiendo la relación entre teoría y aplicación. Leonardo tenía una filosofía de la ciencia coherente y moderna.",
  "El cuaderno más completo de Leonardo que ha sobrevivido es el 'Códice Leicester', comprado por Bill Gates en 1994 por 30.8 millones de dólares (el libro más caro jamás vendido en una subasta hasta entonces). El Códice contiene 72 páginas con observaciones sobre el agua, la luna, la geología y los fósiles. Gates permite que sus páginas sean digitalizadas y exhibidas rotativamente en exposiciones alrededor del mundo, democratizando el acceso a la visión de Leonardo.",
  "El futuro imaginado por Leonardo no era un futuro de utopías abstractas sino de soluciones concretas a problemas concretos: cómo volar, cómo construir mejor, cómo sanar el cuerpo, cómo proteger las ciudades, cómo organizar el agua. Su 'futuro' era el nuestro presente: vivimos rodeados de máquinas, de estructuras construidas con ingeniería matemática, de medicina basada en el conocimiento del cuerpo. Cada coche, cada edificio, cada avión, cada scanner médico es la realización de un sueño que Leonardo esbozó en papel 500 años antes.",
  "El gran legado de Leonardo da Vinci es que nos enseñó a mirar el mundo con ojos que no distinguen entre lo bello y lo verdadero, entre lo artístico y lo científico, entre lo práctico y lo teórico. El universo que Leonardo veía era un cosmos de extraordinaria coherencia y elegancia matemática, donde cada fenómeno reflejaba los mismos principios que todos los demás. Esa visión unificada del conocimiento, que Leonardo encarnó como ningún otro, es el ideal al que toda educación científica y humanista aspira. Somos, cada uno de nosotros, potenciales Leonardos: la diferencia es la curiosidad y la perseverancia para seguirla."
]);

fs.writeFileSync(FILE, src, 'utf8');
console.log('All Da Vinci modules done.');
