/**
 * patch_rocosos.js — patches rocosos_m1 through rocosos_m6 with 15 paragraphs each
 * Topics: Rocky planets, geology, Mercury, Venus, Earth, Mars
 */
const fs = require('fs');
const { replaceTextAndQuiz, FILE } = require('./patch_helpers');
let src = fs.readFileSync(FILE, 'utf8');

const ROCOSOS = {
  rocosos_m1: {
    text: [
      "Los planetas rocosos son mundos sólidos compuestos principalmente de roca y metal. En nuestro sistema solar hay cuatro: Mercurio, Venus, la Tierra y Marte. A diferencia de los gigantes gaseosos como Júpiter y Saturno, los planetas rocosos tienen superficies definidas sobre las que podrías (teóricamente) pararte.",
      "La formación de los planetas rocosos ocurrió hace unos 4,600 millones de años, en los primeros millones de años de vida del sistema solar. Del disco de gas y polvo que rodeaba el joven Sol, pequeñas partículas comenzaron a unirse por gravedad, formando planetesimales, luego protoplanetas, y finalmente los cuatro planetas rocosos que conocemos.",
      "El proceso de formación de los planetas se llama 'acreción'. Las partículas de polvo se pegaban entre sí por fuerzas electrostáticas. Cuando los objetos crecían lo suficiente (unos 100 metros de diámetro), la gravedad tomaba el control y aceleraba la acreción. Los planetas actuales son el resultado de miles de millones de colisiones a lo largo de decenas de millones de años.",
      "La diferenciación planetaria es el proceso por el que los planetas rocosos desarrollaron capas: núcleo metálico denso en el centro, manto rocoso intermedio y corteza exterior. Ocurrió cuando los planetas recién formados estaban tan calientes (por los impactos y la radiactividad) que los materiales más densos (hierro y níquel) se hundieron al centro mientras los más ligeros flotaron hacia arriba.",
      "El hierro y el níquel forman el núcleo de todos los planetas rocosos. La Tierra tiene un núcleo interno sólido de hierro-níquel y un núcleo externo líquido. El movimiento del hierro líquido en el núcleo externo genera el campo magnético de la Tierra mediante un efecto dinamo. Este campo magnético protege la superficie de la radiación solar dañina.",
      "Mercurio es el planeta más pequeño del sistema solar y el más cercano al Sol. Tiene un diámetro de 4,879 km, solo el 38% del diámetro terrestre. Sin embargo, su densidad es sorprendentemente alta (la segunda más alta después de la Tierra), lo que sugiere que tiene un núcleo de hierro desproporcionadamente grande, quizás el resultado de un impacto gigante en sus primeros tiempos.",
      "La superficie de Mercurio está cubierta de cráteres acumulados durante 4,000 millones de años de bombardeo meteórico. A diferencia de la Tierra, Mercurio no tiene tectónica de placas que recicle su corteza, ni atmósfera significativa que erosione los cráteres. Su superficie es un archivo geológico del sistema solar primitivo.",
      "Venus es casi del mismo tamaño que la Tierra (diámetro de 12,104 km vs 12,742 km de la Tierra), pero es el planeta más diferente de nuestro mundo. Tiene una atmósfera densa de dióxido de carbono (CO₂) con presión 92 veces mayor que la Tierra. Su efecto invernadero es tan extremo que la temperatura superficial es de 465°C, más caliente que Mercurio a pesar de estar más lejos del Sol.",
      "Marte es el cuarto planeta rocoso, con un diámetro de 6,779 km (la mitad que la Tierra). Tiene una atmósfera delgada de CO₂, casquetes polares de hielo agua-CO₂, y evidencias de que en el pasado tuvo agua líquida en su superficie. Olympus Mons, en Marte, es el volcán más grande del sistema solar: 21 km de alto y 600 km de diámetro.",
      "La tectónica de placas es el proceso que hace única a la Tierra entre los planetas rocosos. La corteza terrestre está dividida en grandes fragmentos (placas) que flotan sobre el manto semi-fluido y se mueven lentamente. Cuando chocan, crean montañas; cuando se separan, crean océanos; cuando una se hunde bajo la otra, hay volcanes y terremotos.",
      "La geología comparada de los planetas rocosos nos enseña sobre la historia del sistema solar. Los cráteres de Mercurio y la Luna (un mundo rocoso sin atmósfera) muestran que el período de bombardeo intenso terminó hace unos 3,800 millones de años. Los volcanes de Marte muestran que la geología activa en planetas sin tectónica de placas puede concentrarse en un punto.",
      "El agua es el factor que más diferencia a los planetas rocosos. La Tierra tiene agua líquida en su superficie, que es esencial para la vida que conocemos. Venus podría haber tenido océanos en el pasado antes de que su efecto invernadero se descontrolara. Marte también tuvo agua líquida hace miles de millones de años. Mercurio solo tiene hielo en los cráteres polares permanentemente sombreados.",
      "La vida (tal como la conocemos) solo ha aparecido con certeza en la Tierra. Sin embargo, Marte tuvo condiciones similares a las primitivas terrestres hace 3,000-4,000 millones de años: agua líquida, atmósfera más densa y temperatura más templada. Si la vida surgió en Marte en ese período, podría existir en forma de microbios en el subsuelo aún hoy.",
      "Los planetas rocosos del sistema solar no son los únicos en el universo. El telescopio Kepler y el TESS han descubierto miles de exoplanetas rocosos alrededor de otras estrellas. Algunos están en la 'zona habitable' (a la distancia correcta para tener agua líquida) y tienen tamaños similares al de la Tierra. La búsqueda de uno habitable es uno de los objetivos más apasionantes de la astronomía actual.",
      "Estudiar los planetas rocosos es estudiar la historia de la Tierra desde una perspectiva cósmica. Venus nos muestra lo que la Tierra podría haberse convertido sin sus océanos. Marte nos muestra lo que la Tierra podría volverse si pierde su magnetosfera y su atmósfera. Mercurio nos muestra lo que queda cuando un planeta pierde casi todo. Somos afortunados de vivir en el único que lo hace bien."
    ],
    quiz: [
      { q: "¿Cuántos planetas rocosos hay en el sistema solar?", options: ["Dos","Tres","Cuatro","Cinco"], a: 2 },
      { q: "¿Qué es la diferenciación planetaria?", options: ["La formación de satélites","El proceso por el que los planetas desarrollan capas: núcleo, manto y corteza","La división en hemisferios","La formación de cráteres"], a: 1 },
      { q: "¿Cuál es la temperatura superficial de Venus?", options: ["100°C","200°C","350°C","465°C"], a: 3 },
      { q: "¿Cuál es el volcán más grande del sistema solar?", options: ["El Mauna Loa terrestre","El Olimpo Mons en Marte","El Vesubio en Venus","El Mons Huygens en la Luna"], a: 1 },
      { q: "¿Qué genera el campo magnético de la Tierra?", options: ["El Sol","La Luna","El movimiento del hierro líquido en el núcleo externo","La tectónica de placas"], a: 2 }
    ]
  },
  rocosos_m2: {
    text: [
      "Mercurio, el planeta más cercano al Sol, es un mundo de extremos. Su día dura 59 días terrestres pero su año dura solo 88 días. Esto significa que en Mercurio, el Sol aparece muy raramente saliendo por el mismo punto del horizonte dos veces consecutivas: la mecánica orbital crea fenómenos visuales únicos.",
      "La resonancia orbital de Mercurio es 3:2: da tres rotaciones completas por cada dos órbitas alrededor del Sol. Durante mucho tiempo, los astrónomos pensaban que Mercurio siempre mostraba la misma cara al Sol (como la Luna a la Tierra), pero mediciones de radar en los años 60 revelaron la verdad más compleja.",
      "Las variaciones de temperatura en Mercurio son las más extremas del sistema solar: desde -180°C en la noche hasta +430°C durante el día. Esta diferencia de más de 600°C ocurre porque Mercurio no tiene atmósfera (solo una exosfera muy tenue) para distribuir el calor. El suelo rocoso absorbe o libera calor sin moderación.",
      "La densidad de Mercurio es de 5.43 g/cm³, la segunda más alta del sistema solar después de la Tierra. Para un planeta tan pequeño, esta densidad es anómalamente alta. Los científicos creen que en sus primeros tiempos, Mercurio era mucho más grande, pero un impacto gigante le arrancó la mayor parte de su manto rocoso, dejando solo el núcleo denso de hierro.",
      "Las misiones a Mercurio son difíciles de realizar. Estando tan cerca del Sol, una nave espacial que viaja hacia él se acelera enormemente por la gravedad solar y necesita mucho combustible para frenar. La sonda Mariner 10 sobrevoló Mercurio en 1974-75 y fotografió el 45% de su superficie. La sonda MESSENGER orbitó Mercurio entre 2011 y 2015.",
      "MESSENGER descubrió que Mercurio tiene hielo de agua en el interior de los cráteres de sus polos norte y sur. Estos cráteres permanecen en sombra permanente y nunca reciben luz solar directa, por lo que el hielo (probablemente traído por cometas) se mantiene congelado a pesar del calor extremo en el resto del planeta.",
      "La superficie de Mercurio muestra llanuras volcánicas antiguas y sistemas de escarpes (acantilados) que rodean el planeta. Estos escarpes se formaron cuando Mercurio se contrajo al enfriarse durante sus primeros miles de millones de años. La corteza se arrugó como una uva que se convierte en pasa, creando estos acantilados de hasta 3 kilómetros de alto.",
      "BepiColombo es la misión más reciente a Mercurio, lanzada en 2018 por la ESA (Agencia Espacial Europea) y la JAXA (Agencia Espacial Japonesa). Llegará a Mercurio en 2025 y estudiará su campo magnético, su interior y su exosfera con instrumentos mucho más avanzados que los de MESSENGER.",
      "El campo magnético de Mercurio es débil pero real, un 1% del terrestre. Teniendo en cuenta que su rotación es lenta (factor importante para el efecto dinamo), la existencia de este campo magnético sugiere que su núcleo de hierro aún está parcialmente líquido y activo, un dato sorprendente para un planeta tan pequeño.",
      "Los cráteres en la superficie de Mercurio tienen nombres que siguen una tradición astronómica: se llaman como artistas, escritores, compositores y pintores famosos de la historia humana. Hay cráteres llamados Bach, Shakespeare, Dostoievski, Cervantes y Hokusai. Esta práctica conecta las humanidades con la exploración científica.",
      "La llanura de Caloris es una de las mayores estructuras de impacto del sistema solar: 1,550 km de diámetro, formada por un asteroide enorme que impactó Mercurio hace unos 3,900 millones de años. El impacto fue tan violento que el sonido de la colisión viajó a través del planeta y fracturó la superficie en el punto antipodal (exactamente en el lado opuesto).",
      "Los espectrómetros de MESSENGER detectaron en la superficie de Mercurio compuestos de azufre, magnesio, calcio, sodio, potasio y cloro, en proporciones que sugieren una composición diferente a la de la Tierra. Esta composición confirma que Mercurio se formó bajo condiciones únicas en el sistema solar primitivo.",
      "La geología de Mercurio nos ayuda a entender la historia de todos los planetas rocosos. Al ser el más antiguo en términos de actividad geológica (está 'muerto' desde hace miles de millones de años), conserva las características de la etapa más temprana de la formación planetaria, incluyendo cráteres del Gran Bombardeo Tardío.",
      "El Gran Bombardeo Tardío fue un período hace unos 4,100-3,800 millones de años en que el sistema solar interior fue impactado por una lluvia de asteroides y cometas. Este período coincide con el surgimiento de la vida en la Tierra, lo que ha llevado a algunos investigadores a sugerir que los impactos podrían haber traído los componentes orgánicos necesarios para la vida.",
      "Mercurio es un recordatorio de que incluso los mundos pequeños y aparentemente inhóspitos tienen historias geológicas ricas y complejas. Cada cráter es un registro de un impacto, cada llanura es una historia de volcanismo, y cada escarpe es la memoria de un planeta que se contrajo y se enfrió. El universo escribe su historia en la piedra de los planetas."
    ],
    quiz: [
      { q: "¿Cuánto dura un día en Mercurio en días terrestres?", options: ["12","29","59","88"], a: 2 },
      { q: "¿Cómo se llama la misión conjunta ESA-JAXA a Mercurio lanzada en 2018?", options: ["Mariner 11","MESSENGER 2","BepiColombo","Hermes"], a: 2 },
      { q: "¿Qué causó los escarpes (acantilados) en la superficie de Mercurio?", options: ["Erosión por viento","La contracción al enfriarse tras el volcansimo primitivo","Impactos de asteroides","Tectonismo activo"], a: 1 },
      { q: "¿Cuál es el diámetro de la llanura de Caloris?", options: ["550 km","1,000 km","1,550 km","3,000 km"], a: 2 },
      { q: "¿Dónde encontró MESSENGER hielo de agua en Mercurio?", options: ["En el ecuador","En los polos, en cráteres permanentemente en sombra","En el fondo de grietas volcánicas","En el interior del planeta"], a: 1 }
    ]
  },
  rocosos_m3: {
    text: [
      "Venus es el planeta más brillante en nuestro cielo nocturno (después de la Luna), visible al amanecer y al anochecer como la 'Estrella de la Mañana' o la 'Estrella de la Tarde'. Su brillo se debe a sus nubes altamente reflectantes de ácido sulfúrico, que reflejan el 70% de la luz solar que reciben.",
      "Venus es el planeta del sistema solar que más se parece a la Tierra en tamaño: solo un 5% más pequeño en diámetro. Por esta razón fue llamado 'el gemelo de la Tierra' durante mucho tiempo. Pero es el 'gemelo malvado': a pesar de su tamaño similar, sus condiciones son completamente diferentes y hostiles para la vida.",
      "La atmósfera de Venus es 96.5% dióxido de carbono (CO₂), el mismo gas que las plantas absorben en la Tierra y que se acumula por el uso de combustibles fósiles. La densa atmósfera veneniana crea un efecto invernadero tan extremo que la temperatura superficial llega a 465°C: suficiente para derretir el plomo.",
      "La presión atmosférica en la superficie de Venus es 92 veces mayor que en la Tierra (equivalente a estar a 900 metros de profundidad en el océano). Las sondas soviéticas Venera que aterrizaron en Venus en los años 70-80 soportaban esta presión pero solo funcionaban durante 23-127 minutos antes de ser destruidas por el calor y la presión.",
      "Venus rota en dirección opuesta a la de la Tierra y la mayoría de los planetas (rotación retrógrada). Además, rota muy lentamente: un día venusiano dura 243 días terrestres, más que su año (225 días). Esto significa que en Venus, el Sol sale por el oeste y se pone por el este, al contrario que en todos los demás planetas del sistema solar (excepto Urano).",
      "La superficie de Venus, debajo de las nubes, fue mapeada principalmente por la sonda Magellan entre 1990 y 1994, usando radar para penetrar las nubes. Magellan reveló una superficie con volcanes, llanuras y dos grandes 'continentes' elevados (Ishtar Terra e Aphrodite Terra), aunque sin crateres de impacto pequeños (la atmósfera densa los destruye antes de que lleguen al suelo).",
      "Venus tiene más volcanes que ningún otro planeta del sistema solar: más de 1,600 volcanes mayores. La pregunta de si algunos siguen activos fue respondida en 2023 cuando el análisis de imágenes de Magellan reveló cambios en la forma de un volcán durante la misión. Venus tiene volcanismo activo, lo que lo hace geológicamente vivo.",
      "Las nubes de Venus son hermosas pero letales. Están compuestas principalmente de gotitas de ácido sulfúrico (H₂SO₄). Sin embargo, algunas investigaciones recientes han detectado fosfina (PH₃) en las nubes venusianas, un gas que en la Tierra solo produce la vida. Si se confirma, sería una señal potencial de vida en las nubes de Venus donde las temperaturas son más tolerables (30-70°C).",
      "La hipótesis de la vida en las nubes de Venus es especulativa pero intrigante. A 50 km de altitud en las nubes venusianas, la temperatura está entre 30°C y 70°C y la presión es similar a la de la superficie terrestre. Aunque el ácido sulfúrico sería mortal para la vida terrestre, hay microorganismos en la Tierra (acidófilos extremos) que viven en ambientes muy ácidos.",
      "Venus podría haber sido habitable en el pasado. Modelos climáticos recientes sugieren que hace unos 2,000 millones de años, Venus podría haber tenido temperaturas superficiales templadas y quizás agua líquida. Un aumento en la actividad volcánica pudo haber desencadenado un efecto invernadero descontrolado que lo convirtió en el infierno que es hoy.",
      "El estudio de Venus es urgente para la ciencia climática terrestre. Venus es el ejemplo extremo de lo que ocurre cuando un efecto invernadero se descontrola. Entender en detalle cómo ocurrió el colapso climático venusiano podría ayudarnos a entender mejor los mecanismos del cambio climático terrestre y cómo prevenirlos.",
      "Las misiones futuras a Venus son múltiples. La NASA aprobó DAVINCI y VERITAS, y la ESA aprobó EnVision. Todas están programadas para la década de 2030. DAVINCI enviará una sonda que descenderá a través de la atmósfera venusiana, tomando muestras de gases y fotografiando la superficie durante su descenso.",
      "La denominación de las características geográficas de Venus sigue una tradición única: todo lleva nombres de mujeres míticas y diosas de diversas culturas. Los cráteres llevan nombres de mujeres famosas históricas: hay cráteres llamados Cleopatra, Marie Curie y Sacagawea. Esta convención fue elegida por la Unión Astronómica Internacional para honrar el papel histórico de las mujeres.",
      "Desde el espacio, Venus es simplemente un disco blanco y brillante sin detalles superficiales visibles. Sus nubes opacas ocultaron sus secretos durante siglos. La exploración espacial fue necesaria para revelar la verdad detrás de la belleza: un mundo aparentemente sereno que en realidad es uno de los lugares más hostiles del sistema solar.",
      "El contraste entre la apariencia de Venus y su realidad es una lección filosófica sobre las apariencias engañosas. Lo que parece hermoso y cercano puede ser peligroso. Lo que parece lejano e inhóspito (como Marte) puede ser más accesible. La ciencia nos enseña a ir más allá de las apariencias y buscar la realidad con instrumentos, datos y razonamiento riguroso."
    ],
    quiz: [
      { q: "¿Por qué Venus es tan brillante en el cielo nocturno?", options: ["Es un planeta muy grande","Sus nubes reflejan el 70% de la luz solar","Tiene luz propia","Está muy cerca de la Tierra"], a: 1 },
      { q: "¿Cuál es la temperatura superficial de Venus?", options: ["200°C","300°C","400°C","465°C"], a: 3 },
      { q: "¿Qué gas inesperado detectaron científicos en las nubes de Venus en 2020?", options: ["Oxígeno","Nitrógeno","Fosfina (PH₃)","Metano"], a: 2 },
      { q: "¿Por qué en Venus el Sol sale por el oeste?", options: ["Está más lejos del Sol","Tiene rotación retrógrada","Su eje está inclinado 90°","El campo magnético lo invierte"], a: 1 },
      { q: "¿Qué sondas soviéticas aterrizaron en Venus en los años 70-80?", options: ["Luna","Venera","Marsnik","Sputnik-V"], a: 1 }
    ]
  },
  rocosos_m4: {
    text: [
      "La Tierra es el tercer planeta desde el Sol y el único mundo que conocemos con certeza que alberga vida. Desde el espacio, aparece como un mármol azul y blanco: el azul de sus océanos, el blanco de sus nubes y el verde y marrón de sus continentes. Es el planeta más densamente habitado del universo conocido.",
      "La Tierra tiene la diversidad geológica más rica de todos los planetas rocosos. La tectónica de placas recicla continuamente su corteza, creando montañas, océanos, volcanes y terremotos. Este reciclaje de corteza es también un reciclaje de nutrientes y minerales que alimenta los ciclos biogeoquímicos que sostienen la vida.",
      "La atmósfera de la Tierra es una mezcla única: 78% nitrógeno, 21% oxígeno y 1% otros gases (principalmenre argón y CO₂). El oxígeno fue producido por los primeros organismos fotosintéticos (cianobacterias) hace unos 2,400 millones de años, en un evento llamado la 'Gran Oxidación'. Antes de esto, la atmósfera terrestre carecía de oxígeno libre.",
      "La capa de ozono (O₃) en la estratosfera terrestre protege la superficie de la radiación ultravioleta del Sol, que destruiría el ADN y haría imposible la vida en tierra firme. Sin la capa de ozono, la vida solo existiría en el agua (que también bloquea la radiación UV). La capa de ozono fue dañada por los clorofluorocarbonos (CFC) en el siglo XX pero se está recuperando gracias al Protocolo de Montreal (1987).",
      "El campo magnético de la Tierra es generado por el movimiento convectivo del hierro líquido en el núcleo externo. Este campo actúa como un escudo que desvía las partículas cargadas del viento solar. Sin él, el viento solar habría erosionado gradualmente nuestra atmósfera, como ocurrió con Marte cuando su campo magnético se apagó hace unos 4,000 millones de años.",
      "Las auroras boreales y australes son fenómenos visuales generados cuando las partículas del viento solar que logran penetrar la magnetosfera (a través de los polos) colisionan con los gases de la atmósfera superior. Los átomos de oxígeno y nitrógeno emiten colores específicos: el verde es del oxígeno a 100-150 km de altura, el rojo del oxígeno a mayor altitud, y el azul/violeta del nitrógeno.",
      "Los océanos cubren el 71% de la superficie terrestre y son el mayor depósito de vida del planeta. Tienen una profundidad media de 3,680 metros, con el punto más profundo en la Fosa de Marianas a 11,034 metros. Los océanos regulan el clima terrestre: absorben calor del Sol, redistribuyen energía térmica a través de las corrientes oceánicas, y absorben CO₂.",
      "La biodiversidad de la Tierra es asombrosa: se han identificado más de 8.7 millones de especies, y se estima que existen entre 8 y 10 millones más sin descubrir. Esta diversidad es el resultado de 3,800 millones de años de evolución. La diversidad genética es también la base de la resiliencia de los ecosistemas: a mayor diversidad, mayor capacidad de adaptación al cambio.",
      "La Tierra tiene una luna desproporcionadamente grande en comparación con el planeta: la Luna tiene un cuarto del diámetro terrestre. Esta proporción es única en el sistema solar (salvo el sistema Plutón-Caronte, que no son planetas). La Luna estabiliza la inclinación axial de la Tierra, previniendo las dramáticas variaciones climáticas que ocurrirían sin ella.",
      "La inclinación axial de la Tierra (23.5°) produce las estaciones del año: cuando el hemisferio norte está inclinado hacia el Sol (verano boreal), el hemisferio sur está alejado (invierno austral), y viceversa. Sin esta inclinación, no habría estaciones y el clima sería más uniforme pero también menos productivo para la vegetación.",
      "El ciclo del agua es el proceso que mantiene el agua moviéndose entre los océanos, la atmósfera y la superficie terrestre. El Sol calienta el agua, que se evapora y sube a la atmósfera como vapor, donde se condensa en nubes y cae como precipitación. Este ciclo es el motor del clima y el transporte de nutrientes desde las montañas hacia los valles y los océanos.",
      "La tectónica de placas tiene velocidades comparables al crecimiento de las uñas: entre 2 y 10 cm por año. Pero a lo largo de millones de años, estos pequeños movimientos han rediseñado completamente la superficie terrestre. Hace 200 millones de años, todos los continentes eran uno solo (Pangea). En 250 millones de años, un nuevo supercontinente (Amasia) podría formarse.",
      "El ciclo del carbono es el proceso por el que el carbono circula entre la atmósfera, los océanos, el suelo y los seres vivos. Las plantas absorben CO₂ y lo convierten en materia orgánica. Los animales lo devuelven al respirar. Los volcanes lo liberan del interior de la Tierra. Los océanos lo absorben. La tectónica de placas lo recicla a lo largo de millones de años.",
      "El cambio climático actual es una perturbación del ciclo del carbono causada por la quema de combustibles fósiles. Desde la Revolución Industrial, la concentración de CO₂ en la atmósfera ha aumentado de 280 ppm a más de 420 ppm (2024), el nivel más alto en 3 millones de años. Esta acumulación refuerza el efecto invernadero y sube la temperatura global.",
      "La Tierra es extraordinaria no porque sea grande o masiva (Júpiter es 1,321 veces más grande), sino porque tiene la combinación precisa de características que permiten la vida: agua líquida, temperatura templada, atmósfera con oxígeno, campo magnético protector, Luna estabilizadora y tectónica de placas que recicla nutrientes. Somos privilegiados de vivir aquí."
    ],
    quiz: [
      { q: "¿Qué porcentaje de la superficie terrestre cubren los océanos?", options: ["50%","60%","71%","85%"], a: 2 },
      { q: "¿Cómo se llama el evento que hace 2,400 millones de años llenó la atmósfera de oxígeno?", options: ["La Gran Explosión","La Gran Oxidación","El Gran Bombardeo","La Gran Extinción"], a: 1 },
      { q: "¿Cuántas especies de seres vivos se han identificado en la Tierra?", options: ["1 millón","4 millones","8.7 millones","100 millones"], a: 2 },
      { q: "¿Qué genera las auroras boreales?", options: ["Tormentas magnéticas en la Tierra","Partículas del viento solar que chocan con la atmósfera superior","Erupciones volcánicas","El reflejo de las luces de las ciudades"], a: 1 },
      { q: "¿Cómo se llamaba el supercontinente hace 200 millones de años?", options: ["Gondwana","Laurasia","Pangea","Amasia"], a: 2 }
    ]
  },
  rocosos_m5: {
    text: [
      "Marte, el 'Planeta Rojo', lleva ese nombre por el color de su suelo: un polvo fino de óxido de hierro (herrumbre). Es el cuarto planeta del sistema solar y el más similar a la Tierra después de Venus, aunque sus diferencias son enormes. Tiene un día de 24.6 horas (casi igual al terrestre), estaciones (porque su inclinación axial es 25°) y agua helada en sus polos.",
      "La atmósfera de Marte es 100 veces más delgada que la terrestre: una presión de solo 0.6% de la terrestre, principalmente de CO₂. Es demasiado delgada para que el agua sea líquida en la superficie bajo condiciones normales: el agua se evaporaría directamente (sublima) o se congelaría. Sin embargo, existen pruebas de agua líquida antigua en Marte.",
      "El Monte Olimpo (Olympus Mons) en Marte es el volcán y la montaña más alta del sistema solar. Mide 21.9 km de altura sobre el nivel base marciano (casi 3 veces el Everest sobre el nivel del mar terrestre) y tiene una base de 624 km de diámetro. La cumbre está tan alta que sobresale de la mayor parte de la atmósfera marciana.",
      "Olympus Mons es tan enorme porque Marte no tiene tectónica de placas. En la Tierra, el movimiento de las placas mueve la corteza sobre los puntos calientes del manto, creando cadenas de volcanes (como las islas Hawái). En Marte, la corteza no se mueve, así que el magma sigue acumulándose en el mismo punto durante miles de millones de años.",
      "El cañón Valles Marineris tiene 4,000 km de largo, 200 km de ancho y hasta 7 km de profundidad. Si estuviera en la Tierra, cruzaría Estados Unidos de costa a costa. No fue formado por erosión fluvial (como el Gran Cañón del Colorado) sino por la tectónica del bulto de Tharsis: la corteza marciana se fracturó cuando el peso volcánico de esa región estiró la corteza circundante.",
      "Los rovers Mars Exploration Rover (Spirit y Opportunity), Curiosity (desde 2012) y Perseverance (desde 2021) han explorado la superficie marciana. Curiosity descubrió que el cráter Gale fue un lago hace unos 3,500 millones de años, con agua apta para la vida microbiana. Perseverance busca evidencias de vida antigua en el delta del cráter Jezero.",
      "Perseverance también tiene a bordo el helicóptero Ingenuity, el primer vehículo motorizado que voló en otro planeta. Ingenuity voló por primera vez el 19 de abril de 2021, un logro histórico. Volar en la atmósfera marciana es enormemente difícil porque es 100 veces más delgada que la terrestre: las aspas deben rotar 2,400 veces por minuto.",
      "Marte tiene dos lunas pequeñas e irregulares: Fobos y Deimos. Fobos (miedo) tiene 26 km de diámetro y orbita Marte a solo 9,376 km de distancia (20 veces más cerca que nuestra Luna de la Tierra). Se acerca a Marte 1.8 metros por siglo y en unos 50 millones de años se fragmentará, formando un anillo o cayendo en Marte.",
      "La búsqueda de vida en Marte se centra en el subsuelo, donde podría haber agua líquida protegida de la radiación. La sonda Mars Express de la ESA detectó en 2018 lo que parecía ser un lago subterráneo de agua líquida bajo el polo sur. Análisis posteriores son más escépticos, pero la posibilidad aún no ha sido descartada.",
      "Los planes de colonización humana de Marte son objeto de debate científico y público. SpaceX, con su cohete Starship, planea enviar los primeros humanos a Marte en los años 2030. La NASA también estudia misiones humanas marcianas. Los desafíos son enormes: radiación cósmica (sin campo magnético marciano), gravedad reducida (38% de la terrestre) y el viaje de 7-9 meses.",
      "La terraformación de Marte es el proceso especulativo de modificar su atmósfera y temperatura para hacerlo más parecido a la Tierra. En principio, liberar gases de efecto invernadero (como el CO₂ del suelo y los polos) podría aumentar la temperatura y la presión. Pero los modelos actuales sugieren que los recursos disponibles en Marte son insuficientes para una terraformación completa.",
      "El polvo marciano es uno de los mayores peligros para los futuros exploradores. Las tormentas de polvo en Marte pueden cubrir el planeta entero durante meses: en 2018, una tormenta global cubrió el Sol y mató al rover Opportunity al cortarle la energía solar. El polvo también contiene percloratos (sales tóxicas) que serían peligrosas para los humanos.",
      "El color rojo de Marte es producto de la oxidación (herrumbre) del hierro en su suelo. Marte perdió su campo magnético hace unos 4,000 millones de años cuando su núcleo se enfrió y solidificó. Sin campo magnético, el viento solar erosionó su atmósfera durante millones de años, hasta dejarla tan delgada como es hoy.",
      "Los meteoritos marcianos han sido encontrados en la Tierra: fragmentos de roca marciana expulsados por impactos que viajaron por el espacio durante millones de años hasta llegar a la Tierra. Uno de ellos, ALH84001 encontrado en la Antártida, generó un gran revuelo en 1996 cuando los científicos creyeron ver estructuras microscópicas que podían ser microbios fosilizados. La polémica nunca fue resuelta definitivamente.",
      "Marte representa la frontera más realista de la exploración humana en las próximas décadas. Si los humanos llegamos a Marte, no solo expandiremos nuestra presencia en el sistema solar: aprenderemos sobre los límites de la adaptabilidad humana, encontraremos respuestas sobre el origen de la vida, y quizás descubriremos que no estamos solos en el universo."
    ],
    quiz: [
      { q: "¿Cuánto mide Olympus Mons en altura?", options: ["10 km","15 km","21.9 km","35 km"], a: 2 },
      { q: "¿Cómo se llama el primer helicóptero que voló en Marte?", options: ["Curiosity","Perseverance","Ingenuity","Phoenix"], a: 2 },
      { q: "¿Por qué es rojo el suelo de Marte?", options: ["Por volcanes activos","Por óxido de hierro (herrumbre)","Por la radiación solar","Por su composición de cobre"], a: 1 },
      { q: "¿Cuánto dura un día en Marte?", options: ["12 horas","18 horas","24.6 horas","36 horas"], a: 2 },
      { q: "¿Cuál es la luna más grande de Marte?", options: ["Deimos","Fobos","Tritón","Caronte"], a: 1 }
    ]
  },
  rocosos_m6: {
    text: [
      "Comparar los cuatro planetas rocosos nos da una perspectiva única sobre la evolución planetaria. Los cuatro se formaron al mismo tiempo, de los mismos materiales básicos, en la misma región del sistema solar. Sin embargo, hoy son mundos completamente diferentes. ¿Qué hizo que tomaran caminos tan distintos?",
      "El tamaño importa enormemente en la evolución planetaria. La Tierra (masa 1.0) y Venus (masa 0.82) son lo suficientemente masivos para retener una atmósfera gruesa y mantener calor interno durante miles de millones de años. Marte (masa 0.11) perdió su atmósfera y su campo magnético. Mercurio (masa 0.055) perdió casi todo su manto en un impacto gigante primitivo.",
      "La distancia al Sol también define el destino de un planeta. Mercurio está demasiado cerca: el calor solar y los vientos son demasiado intensos para retener atmósfera. Venus está en la frontera interna de la zona habitable: podría haber sido habitable en el pasado pero su efecto invernadero se descontroló. La Tierra está en el centro de la zona habitable. Marte está en la frontera externa: demasiado frío para agua líquida estable.",
      "La zona habitable (o 'zona de Ricitos de Oro') es el rango de distancias a una estrella donde las condiciones permiten que el agua sea líquida en la superficie de un planeta. Para el Sol, esta zona va aproximadamente de 0.95 a 1.67 veces la distancia Tierra-Sol. La Tierra está perfectamente dentro de ella; Marte está en el borde externo.",
      "El campo magnético es otro factor decisivo. La Tierra tiene un campo magnético fuerte generado por su núcleo líquido activo. Este campo protege la atmósfera del viento solar. Venus no tiene campo magnético global (o es muy débil), lo que es sorprendente dado su tamaño similar al terrestre; quizás su rotación lenta impide el efecto dinamo. Marte perdió su campo hace 4,000 millones de años.",
      "La geología activa es el factor que más diferencia a la Tierra. La tectónica de placas terrestre recicla la corteza, crea montañas, forma océanos nuevos y recicla el carbono desde el manto hacia la atmósfera y viceversa. Este ciclo del carbono regula el clima terrestre en escalas de millones de años, actuando como un termostato planetario.",
      "La luna de la Tierra también juega un papel estabilizador. La gravedad de la Luna estabiliza la inclinación axial de la Tierra en torno a los 23.5°. Sin la Luna, la inclinación podría variar caóticamente entre 0° y 85°, causando extremas variaciones climáticas. Marte (cuyas lunas son insignificantes en masa) sufre variaciones caóticas de su eje a lo largo de millones de años.",
      "Los exoplanetas rocosos descubiertos en los últimos años ofrecen una perspectiva ampliada. El telescopio Kepler descubrió miles de planetas en todas las configuraciones posibles: planetas rocosos muy cercanos a sus estrellas, planetas en zonas habitables de estrellas enanas rojas, planetas del tamaño de la Tierra con todo tipo de densidades. El sistema solar ya no parece una plantilla única del universo.",
      "Los planetas en zonas habitables de estrellas enanas rojas son los candidatos más numerosos para la búsqueda de vida. Trappist-1, una estrella enana roja a 39 años luz, tiene 7 planetas del tamaño de la Tierra, 3 de ellos en la zona habitable. Pero las enanas rojas emiten fuertes llamaradas UV y los planetas están tan cerca que probablemente siempre muestran la misma cara a la estrella.",
      "La búsqueda de biosignatures (señales de vida) en exoplanetas es el próximo gran objetivo de la astronomía. El telescopio James Webb puede estudiar la composición atmosférica de exoplanetas cuando transitan frente a su estrella. Si detectara oxígeno, metano y ozono simultáneamente en la atmósfera de un exoplaneta, sería la señal más fuerte posible de vida fuera de la Tierra.",
      "La geología comparativa ha producido uno de los mayores logros de la astrofísica: la comprensión de la habitabilidad planetaria como función de múltiples parámetros interconectados. Ningún factor único (distancia, tamaño, composición) determina la habitabilidad: es la combinación de todos ellos, interactuando a lo largo de miles de millones de años, lo que produce un mundo vivo.",
      "Los estudios de los planetas rocosos también nos dan perspectiva sobre el futuro de la Tierra. En unos 1,000 millones de años, el Sol será un 10% más luminoso y la Tierra podría ser demasiado caliente para el agua líquida. En unos 5,000 millones de años, el Sol se convertirá en gigante roja y podría engullir la Tierra. El sistema solar es mortal como todos los sistemas estelares.",
      "Sin embargo, 1,000 millones de años es un tiempo enorme: el tiempo que tardó en surgir la vida inteligente en la Tierra. En ese tiempo, si la humanidad sobrevive, podría haber desarrollado la tecnología para terraformar otros planetas, emigrar a otras estrellas o proteger la Tierra de los efectos del Sol envejeciente.",
      "La geología es la ciencia que estudia la historia de los planetas a través de las rocas. En la Tierra, cada estrato de roca es un capítulo de la historia. En Marte, cada cráter es un reloj. En Mercurio, cada escarpe es la memoria de un planeta que se enfrió. En Venus, cada volcán activo es una señal de que la historia aún no ha terminado.",
      "Los cuatro planetas rocosos del sistema solar son más que rocas en el espacio: son laboratorios naturales para entender cómo funciona la evolución planetaria, cómo surge la habitabilidad, y cuán frágil o robusta es la vida en el universo. Al estudiarlos, estudiamos nuestros propios orígenes y, quizás, nuestro propio futuro."
    ],
    quiz: [
      { q: "¿Qué es la 'zona de Ricitos de Oro' en astronomía?", options: ["El cinturón de asteroides","La zona habitable donde el agua puede ser líquida en la superficie","La región cerca del Sol donde orbitan los planetas rocosos","La zona entre Júpiter y Saturno"], a: 1 },
      { q: "¿Qué papel tiene la Luna en la estabilidad del clima terrestre?", options: ["Ninguno","Crea las mareas","Estabiliza la inclinación axial de la Tierra","Produce el campo magnético"], a: 2 },
      { q: "¿Cuántos planetas del tamaño de la Tierra tiene el sistema Trappist-1?", options: ["Tres","Cinco","Siete","Nueve"], a: 2 },
      { q: "¿Qué gases en la atmósfera de un exoplaneta serían señal de vida?", options: ["CO₂ y nitrógeno","Helio y hidrógeno","Oxígeno, metano y ozono simultáneamente","Vapor de agua y argón"], a: 2 },
      { q: "¿En cuántos años el Sol será tan luminoso que la Tierra podría volverse inhabitable?", options: ["1,000","10,000","1,000,000","1,000,000,000"], a: 3 }
    ]
  }
};

for (const [id, data] of Object.entries(ROCOSOS)) {
  src = replaceTextAndQuiz(src, id, data.text, data.quiz);
}

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ Rocosos (m1-m6) all patched!');
