const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

function patchModule(src, moduleId, newText, newQuiz) {
  const modIdx = src.indexOf(`"id": "${moduleId}"`);
  if (modIdx === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  const sectionsIdx = src.indexOf('"sections"', modIdx);
  const textIdx = src.indexOf('"text"', sectionsIdx);
  const arrOpen = src.indexOf('[', textIdx);
  let depth = 0, i = arrOpen;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  src = src.slice(0, arrOpen) + JSON.stringify(newText, null, 12) + src.slice(i + 1);

  const modIdx2 = src.indexOf(`"id": "${moduleId}"`);
  const quizIdx = src.indexOf('"quizEs"', modIdx2);
  const nextModIdx = src.indexOf('"id": "', modIdx2 + 10);
  if (quizIdx !== -1 && (nextModIdx === -1 || quizIdx < nextModIdx)) {
    const qArrOpen = src.indexOf('[', quizIdx);
    let d2 = 0, j = qArrOpen;
    while (j < src.length) {
      if (src[j] === '[') d2++;
      else if (src[j] === ']') { d2--; if (d2 === 0) break; }
      j++;
    }
    src = src.slice(0, qArrOpen) + JSON.stringify(newQuiz, null, 4) + src.slice(j + 1);
  }
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// ========== APOLLO 8 M1 ==========
src = patchModule(src, 'apollo8_m1', [
  "¡Misión Apollo 8, cuenta regresiva iniciada! En diciembre de 1968, tres astronautas americanos se convirtieron en los primeros seres humanos en abandonar la órbita de la Tierra y viajar hasta la Luna. Aunque no aterrizaron en su superficie, su viaje fue uno de los más audaces de la historia de la humanidad. En este módulo, vamos a explorar por qué la Apollo 8 fue tan importante y cómo cambió nuestra visión del mundo para siempre.",
  "El año 1968 fue uno de los más turbulentos del siglo XX. En los Estados Unidos, el movimiento por los derechos civiles estaba en su punto álgido, había protestas masivas contra la guerra de Vietnam, y dos grandes líderes habían sido asesinados ese año: Martin Luther King en abril y Robert Kennedy en junio. El mundo parecía desgarrarse por sus divisiones. En ese contexto de caos y tristeza, la misión Apollo 8 llegó como un rayo de esperanza y maravilla que unió a millones de personas alrededor del planeta.",
  "La tripulación de la Apollo 8 estaba formada por tres astronautas extraordinarios. Frank Borman era el comandante, un piloto militar con experiencia y un líder tranquilo bajo presión. James Lovell era el piloto del módulo de comando, un astronauta experimentado que volvería a la Luna en la dramática misión Apollo 13. William Anders era el piloto del módulo lunar, un ingeniero meticuloso que haría la fotografía más famosa de la historia. Juntos formaban un equipo complementario y perfectamente preparado.",
  "La decisión de enviar a los astronautas a la Luna en 1968 fue tomada con una audacia sorprendente. La NASA originalmente planeaba que la Apollo 8 fuera una misión de prueba en órbita terrestre. Pero en agosto de 1968, la agencia recibió inteligencia de que los soviéticos podrían estar planeando enviar cosmonautas alrededor de la Luna antes de fin de año. Para ganar la carrera espacial, la NASA tomó la arriesgada decisión de cambiar el plan y enviar a la Apollo 8 directamente a la Luna.",
  "El cohete Saturn V que lanzó la Apollo 8 el 21 de diciembre de 1968 era la máquina más poderosa jamás construida por el ser humano hasta ese momento. Con sus 36 pisos de altura y más de 2,800 toneladas de peso, el Saturn V producía una cantidad de empuje equivalente a 32 motores de avión Boeing 747 encendidos al mismo tiempo. El lanzamiento hacía temblar el suelo a kilómetros de distancia y creaba una columna de fuego y humo que podía verse desde Florida hasta Carolina del Norte.",
  "El viaje hasta la Luna duró aproximadamente tres días. Durante ese tiempo, los astronautas viajaron 384,400 kilómetros a través del espacio vacío, más lejos de la Tierra de lo que ningún ser humano había estado jamás. La cápsula de la Apollo 8 era pequeña, apenas del tamaño de un automóvil familiar, y los tres astronautas debían compartir ese espacio reducido durante días. No había ducha, la comida venía en tubos y paquetes, y dormir en gravedad cero requería sujetarse para no flotar.",
  "El 24 de diciembre de 1968, Nochebuena, la Apollo 8 realizó la maniobra más crítica de toda la misión: encender el motor del cohete para frenar la nave y quedar capturada por la gravedad lunar en órbita alrededor de la Luna. Si el motor no encendía, los astronautas morirían en el espacio. Si encendía demasiado tiempo o muy poco, la nave chocaba con la Luna o escapaba de vuelta al espacio. La maniobra se realizó cuando la nave estaba detrás de la Luna, fuera del alcance de las comunicaciones con la Tierra. Por 34 minutos, en Houston solo pudieron esperar y rezar.",
  "Cuando la Apollo 8 salió por el otro lado de la Luna y Frank Borman anunció 'Houston, Apollo 8. Encendido perfecto', las lágrimas corrieron por las mejillas de los ingenieros en el Centro de Control de Misión. Los astronautas realizaron diez órbitas alrededor de la Luna, fotografiando su superficie gris y desolada en busca de posibles sitios de aterrizaje para las futuras misiones. La superficie lunar que veían era un desierto de cráteres, rocas y polvo, sin atmósfera, sin agua, sin vida.",
  "El momento más memorable de toda la misión ocurrió cuando Bill Anders miraba por la ventana y vio algo que nunca antes había visto ningún ser humano: la Tierra saliendo sobre el horizonte lunar. Una esfera azul, blanca y verde, viva y frágil, suspendida en la oscuridad absoluta del espacio. Anders agarró rápidamente su cámara y tomó la fotografía, la 'Earthrise' (Amanecer de la Tierra), que se convirtió en una de las imágenes más importantes de la historia humana y en el símbolo del movimiento ambientalista.",
  "La fotografía 'Earthrise' capturó algo que ninguna descripción verbal podía transmitir completamente: lo pequeña, sola y preciosa que es nuestra Tierra en el cosmos. Desde la Luna, no se ven fronteras entre países, no se ven idiomas ni religiones ni guerras. Solo esa pequeña esfera azul, la única isla de vida conocida en el universo observable. Esta perspectiva cambió profundamente cómo muchas personas pensaban sobre el medioambiente, la política global y la necesidad de cooperar como especie.",
  "La noche del 24 de diciembre de 1968, con la nave en órbita lunar, los astronautas realizaron una transmisión de radio en vivo que fue vista por más de un billón de personas, la audiencia más grande de la historia hasta ese momento. Borman, Lovell y Anders leyeron alternadamente los primeros diez versículos del Génesis, el libro del inicio de la Biblia: 'En el principio, Dios creó los cielos y la Tierra'. Para finalizar, Borman dijo: 'Buenas noches, buena suerte, Feliz Navidad, y que Dios bendiga a todos ustedes, todos ustedes en la buena Tierra'. Fue un momento profundamente emotivo.",
  "El regreso a la Tierra también requirió una maniobra crítica: encender el motor para salir de la órbita lunar y emprender el viaje de vuelta. De nuevo, la maniobra se realizó detrás de la Luna, fuera de las comunicaciones. Esta vez la espera en Houston fue igualmente angustiante. Cuando la nave salió del lado oscuro de la Luna y se escuchó la voz de Frank Borman, el Centro de Control de Misión estalló en celebración. Los astronautas estaban en camino a casa.",
  "La Apollo 8 amerizó en el Océano Pacífico el 27 de diciembre de 1968, seis días después de haber partido. Los astronautas fueron recuperados por el portaaviones USS Yorktown. A su regreso fueron recibidos como héroes en todo el mundo. El poeta Archibald MacLeish escribió: 'Vemos la Tierra ahora, realmente la vemos, pequeña, hermosa y frágil en ese oscuro vacío. Y por primera vez en toda la historia del hombre, vemos nuestra Tierra como es: hermosa, pequeña, con el calor en ella.' Esas palabras capturaron el legado de la Apollo 8.",
  "La misión Apollo 8 demostró que los seres humanos podían viajar al espacio profundo y regresar con seguridad. Validó los sistemas de navegación, comunicación y soporte vital que se necesitarían para la misión de aterrizaje lunar. Proporcionó fotografías detalladas de la superficie lunar para elegir sitios de aterrizaje. Y mostró al mundo entero que los Estados Unidos estaban a punto de ganar la carrera a la Luna, logrando uno de los mayores triunfos tecnológicos del siglo XX.",
  "El legado de la Apollo 8 vive en esa fotografía azul suspendida en la oscuridad. Nos recuerda que la Tierra es nuestra única casa, que sus recursos son finitos, y que como especie somos responsables de cuidarla. También nos recuerda que cuando los seres humanos se proponen algo verdaderamente extraordinario, cuando combinan coraje, inteligencia, trabajo en equipo y visión, pueden hacer cosas que parecen imposibles. La Apollo 8 no solo llegó a la Luna: llegó al corazón de la humanidad."
], [
  { q: "¿En qué año se realizó la misión Apollo 8?", options: ["1966", "1967", "1968", "1969"], a: 2 },
  { q: "¿Quién tomó la famosa fotografía 'Earthrise' (Amanecer de la Tierra)?", options: ["Frank Borman", "James Lovell", "William Anders", "Neil Armstrong"], a: 2 },
  { q: "¿Cuánto duró aproximadamente el viaje de la Tierra a la Luna?", options: ["Un día", "Tres días", "Una semana", "Dos semanas"], a: 1 },
  { q: "¿Por qué era tan crítica la maniobra de inserción en órbita lunar?", options: ["Porque requería mucho combustible", "Porque se realizaba sin comunicación con la Tierra, detrás de la Luna", "Porque los astronautas debían salir al espacio", "Porque el cohete podía explotar"], a: 1 },
  { q: "¿Qué texto leyeron los astronautas en la transmisión de Nochebuena desde la órbita lunar?", options: ["El Corán", "El Quijote", "Los primeros versículos del Génesis", "La Declaración de Independencia"], a: 2 }
]);

// ========== APOLLO 8 M2 ==========
src = patchModule(src, 'apollo8_m2', [
  "¡Continuamos nuestra misión Apollo 8! En este módulo vamos a explorar la tecnología que hizo posible este viaje extraordinario, las personas que trabajaron en tierra para hacerlo realidad, y el impacto científico que tuvo la misión. Porque detrás de los tres astronautas que viajaron a la Luna había miles de personas en la Tierra que hicieron ese sueño posible con su trabajo, su ingenio y su dedicación.",
  "El cohete Saturn V fue la columna vertebral del programa Apollo. Fue diseñado por un equipo liderado por Wernher von Braun, un ingeniero alemán que había soñado con los viajes espaciales desde niño y que luego de la Segunda Guerra Mundial se unió al programa espacial americano. El Saturn V tenía tres etapas: la primera encendía al despegue y caía al océano después de consumir su combustible, la segunda llevaba la nave a la órbita terrestre, y la tercera encendía para enviar la nave hacia la Luna.",
  "El módulo de comando de la Apollo 8, donde viajaban los astronautas, era un cono de metal de apenas 3.9 metros de diámetro. Dentro, había tres asientos reclinables, paneles de control con cientos de interruptores e indicadores, computadoras de navegación, y los sistemas de soporte vital. El espacio era tan reducido que los astronautas bromeaban diciendo que era más pequeño que un baño mediano. Sin embargo, estaba diseñado con precisión milimétrica para proteger a sus ocupantes del vacío del espacio.",
  "La computadora de guía Apollo (AGC) que llevaba la nave era una maravilla tecnológica para 1968. Pesaba 32 kilogramos, tenía 4 kilobytes de memoria RAM y podía ejecutar varias operaciones por segundo. Por contexto, el teléfono más básico de hoy tiene millones de veces más potencia computacional. Sin embargo, esta computadora fue suficiente para navegar desde la Tierra hasta la Luna y de regreso con precisión milimétrica. Fue uno de los primeros usos de circuitos integrados de silicio en un sistema crítico.",
  "La ropa espacial de los astronautas de la Apollo 8 era una obra de ingeniería impresionante. Cada traje tenía 21 capas de diferentes materiales: capas de protección térmica para resistir temperaturas extremas, capas anti-micrometeorito para proteger contra partículas de polvo espacial que viajan a velocidades de bala, capas de presión para mantener el cuerpo a presión adecuada, y capas de refrigeración con tubos de agua para mantener la temperatura corporal. Un traje completo costaba lo equivalente a varios millones de dólares de hoy.",
  "El Centro de Control de Misión en Houston, Texas, fue el cerebro de la Apollo 8 durante todo el viaje. Cientos de ingenieros, técnicos y científicos monitoreaban continuamente cada sistema de la nave desde pantallas y computadoras. Trabajaban en turnos de ocho horas para garantizar cobertura las 24 horas del día durante toda la misión. Cada persona en control de misión era responsable de sistemas específicos: propulsión, soporte vital, comunicaciones, navegación. Si algo fallaba, ellos serían los primeros en saberlo.",
  "Las comunicaciones entre la nave y la Tierra durante la Apollo 8 eran realizadas por una red global de antenas llamada la Red de Espacio Profundo. Tres grandes estaciones en California (Estados Unidos), Madrid (España) y Honeysuckle Creek (Australia) garantizaban que siempre hubiera al menos una antena apuntando hacia la nave, sin importar la rotación de la Tierra. La señal de radio viajaba a la velocidad de la luz, pero como la distancia a la Luna es enorme, había un retraso de 1.3 segundos en las comunicaciones.",
  "La fotografía fue una misión científica crucial de la Apollo 8. William Anders tomó cientos de fotografías de la superficie lunar usando cámaras Hasselblad de alta precisión con película especial. Estas imágenes revelaron detalles de la geología lunar nunca antes vistos: cráteres de todos los tamaños, desde gigantes de kilómetros hasta pequeños como una pelota de tenis, montañas lunares, y las llanuras oscuras que los primeros astrónomos llamaban 'mares' pensando que eran océanos de agua.",
  "Las observaciones científicas de la Apollo 8 también incluyeron el estudio del campo gravitacional lunar. A medida que la nave orbitaba la Luna, los ingenieros de tierra analizaban pequeñas variaciones en la señal de radio para detectar cambios en la velocidad de la nave. Estas variaciones revelaron que la Luna tiene concentraciones de masa llamadas 'mascons' bajo algunas regiones, que alteran levemente la trayectoria de las naves en órbita. Entender estos mascons fue crucial para planificar los aterrizajes lunares de las misiones futuras.",
  "El sistema de soporte vital de la Apollo 8 era otra maravilla de ingeniería. Tenía que proveer a los tres astronautas todo lo que necesitaban para sobrevivir: oxígeno para respirar, absorber el dióxido de carbono que exhalaban, agua potable, temperatura confortable, y presión adecuada. También debía manejar los desechos corporales en condiciones de microgravedad, lo que era un desafío sorprendentemente complicado. Cada gramo de masa en la nave era cuidadosamente calculado para minimizar el peso total.",
  "La misión también probó los sistemas de navegación que la NASA necesitaría para las misiones de aterrizaje. Navegar en el espacio profundo, sin puntos de referencia terrestres, requería métodos completamente nuevos. Los astronautas usaban la navegación celeste: medían los ángulos entre estrellas conocidas y la nave con un sextante especial para determinar su posición. Esta técnica medieval adaptada al espacio fue complementada con las computadoras de tierra que calculaban continuamente la trayectoria de la nave.",
  "Uno de los mayores logros técnicos de la Apollo 8 fue el reingreso seguro a la atmósfera terrestre. La nave regresó de la Luna a una velocidad de aproximadamente 40,000 kilómetros por hora, muchísimo más rápida que las naves en órbita terrestre baja. Al entrar en la atmósfera, el escudo térmico debía soportar temperaturas de más de 2,700 grados Celsius, suficiente para derretir el acero. El escudo estaba hecho de un material especial que se quemaba en capas absorbiendo el calor y protegiendo la cápsula interior.",
  "El amerizaje de la Apollo 8 también fue técnicamente complejo. La cápsula desplegó tres grandes paracaídas para desacelerar desde 330 km/h a 35 km/h antes de tocar el agua del Océano Pacífico. La precisión del aterrizaje fue impresionante: a pesar de haber viajado casi 800,000 kilómetros de ida y vuelta, la cápsula amerizó a solo 5 kilómetros del portaaviones de recuperación que esperaba en el punto calculado. Era un testimonio del extraordinario nivel de precisión de los cálculos de trayectoria.",
  "El impacto de la Apollo 8 en la ingeniería y la tecnología fue enorme. Los problemas que la NASA tuvo que resolver para enviar astronautas a la Luna: miniaturizar computadoras, desarrollar materiales resistentes al calor extremo, crear sistemas de soporte vital compactos y confiables, diseñar trajes espaciales multi-capa, perfeccionar las comunicaciones de largo alcance, son problemas cuyas soluciones beneficiaron a la industria civil. Muchas tecnologías que usamos hoy tienen sus raíces en el programa Apollo.",
  "La Apollo 8 fue un triunfo de la colaboración humana a una escala nunca antes vista. Más de 400,000 ingenieros, técnicos, científicos y trabajadores de la industria contribuyeron al programa Apollo. Eran personas de todos los estados de América, trabajando para empresas diferentes, con especialidades distintas, pero unidas por un objetivo común: enviar humanos a la Luna y traerlos de regreso sanos y salvos. Es quizás el mayor proyecto de cooperación en la historia de la ingeniería, y la Apollo 8 fue uno de sus momentos más brillantes."
], [
  { q: "¿Quién diseñó el cohete Saturn V?", options: ["Neil Armstrong", "Wernher von Braun", "John Glenn", "Alan Shepard"], a: 1 },
  { q: "¿Cuántas capas tenía el traje espacial de los astronautas de la Apollo 8?", options: ["5 capas", "10 capas", "21 capas", "35 capas"], a: 2 },
  { q: "¿Cuál era el retraso en las comunicaciones entre la nave y la Tierra?", options: ["0.5 segundos", "1.3 segundos", "5 segundos", "10 segundos"], a: 1 },
  { q: "¿A qué velocidad regresó la Apollo 8 a la atmósfera terrestre?", options: ["5,000 km/h", "15,000 km/h", "25,000 km/h", "40,000 km/h"], a: 3 },
  { q: "¿Cuántas personas aproximadamente contribuyeron al programa Apollo?", options: ["10,000", "50,000", "200,000", "400,000"], a: 3 }
]);

// ========== APOLLO 10 M1 ==========
src = patchModule(src, 'apollo10_m1', [
  "¡Misión Apollo 10, preparados para el ensayo final! En mayo de 1969, la NASA realizó uno de los vuelos de prueba más audaces de la historia: la Apollo 10 voló hasta la Luna, descendió hasta solo 15 kilómetros de la superficie lunar, y luego regresó a la Tierra, todo sin aterrizar. Era el ensayo general perfecto antes del gran debut: el alunizaje de la Apollo 11 dos meses después. Este módulo narra la historia de ese viaje extraordinario que preparó el camino para que Neil Armstrong dijera sus palabras inmortales.",
  "La tripulación de la Apollo 10 fue un equipo de veteranos experimentados. Thomas Stafford era el comandante, un piloto y astronauta con dos misiones anteriores en su haber. John Young era el piloto del módulo de comando, uno de los astronautas más respetados de la NASA que luego pisaría la Luna en la Apollo 16 y comandaría el primer vuelo del transbordador espacial. Eugene Cernan era el piloto del módulo lunar, el hombre que sería el último humano en pisar la Luna en la Apollo 17. Era un equipo de leyendas.",
  "La misión de la Apollo 10 era probar todos los sistemas en condiciones reales de vuelo lunar, pero sin el riesgo del aterrizaje. La NASA quería verificar que el módulo lunar funcionaba correctamente en el espacio real, que los procedimientos de separación y acoplamiento entre los dos módulos funcionaban, que los sitios de aterrizaje seleccionados para la Apollo 11 eran adecuados, y que el control de misión podía manejar todos los procedimientos en tiempo real. Era un ensayo de máxima fidelidad.",
  "El módulo lunar de la Apollo 10 recibió nombres de personajes de la famosa caricatura 'Peanuts' de Charles Schulz. El módulo lunar se llamó Snoopy y el módulo de comando Charlie Brown. La NASA había pedido permiso a Schulz para usar los nombres, y el caricaturista aceptó encantado. Desde entonces, Snoopy se convirtió en el mascota de la seguridad de vuelo de la NASA: el premio Snoopy de plata es hoy uno de los reconocimientos más codiciados que se dan a los empleados de la agencia por contribuciones excepcionales a la seguridad.",
  "El 18 de mayo de 1969, el Saturn V lanzó la Apollo 10 hacia la Luna. Después de tres días de viaje, la nave entró en órbita lunar. Stafford y Cernan se transfirieron al módulo lunar Snoopy mientras Young permanecía solo en el Charlie Brown en órbita. Esto era exactamente lo que haría la tripulación de la Apollo 11 dos meses después, pero sin el paso de aterrizar. La separación de los módulos y la transferencia de tripulantes fue un momento de alta tensión que salió perfectamente.",
  "El Snoopy descendió hasta 15.2 kilómetros sobre la superficie de la Luna, el punto más cercano a la superficie que ningún ser humano había estado hasta entonces sin aterrizar. Desde esa altitud, Stafford y Cernan podían ver los cráteres y rocas de la superficie lunar con una claridad asombrosa. Fotografiaron el Mar de la Tranquilidad, el sitio elegido para el aterrizaje de la Apollo 11, confirmando que era lo suficientemente plano y libre de obstáculos para un aterrizaje seguro.",
  "El momento más dramático de la Apollo 10 ocurrió cuando Stafford y Cernan intentaban separar la etapa de descenso del módulo lunar para usar solo la etapa de ascenso para regresar al Charlie Brown. De repente, el módulo lunar comenzó a girar y rodar de manera descontrolada, dando ocho giros completos en pocos segundos. Un interruptor había sido activado accidentalmente en la posición equivocada, haciendo que el módulo buscara una señal para acoplarse con el Charlie Brown. Stafford tomó el control manual y estabilizó la nave. El corazón de todos en Houston se detuvo por un momento.",
  "Una vez estabilizado el Snoopy, Stafford y Cernan encendieron el motor de ascenso y se dirigieron de regreso al Charlie Brown en órbita. El acoplamiento fue perfecto. Los tres astronautas se reunieron en el módulo de comando y se prepararon para el regreso a la Tierra. El Snoopy fue liberado en órbita solar, donde sigue viajando hasta hoy como un recuerdo inerte de esa misión histórica en el espacio entre la Tierra y la Luna.",
  "Durante la misión, la Apollo 10 estableció un récord de velocidad que todavía no ha sido superado por naves tripuladas: durante el regreso a la Tierra, la nave alcanzó una velocidad máxima de 39,897 kilómetros por hora, la velocidad más alta a la que jamás han viajado seres humanos. Este récord está registrado en el Libro Guinness de los Récords y probablemente permanecerá así durante décadas, hasta que futuras misiones a Marte alcancen velocidades similares.",
  "Las observaciones científicas de la Apollo 10 fueron igualmente valiosas. Los astronautas estudiaron las diferencias de iluminación solar en diferentes ángulos sobre la superficie lunar, lo que ayudó a entender mejor la topografía del terreno para el aterrizaje. También identificaron exactamente las características geológicas del sitio del Mar de la Tranquilidad: el tipo y tamaño de los cráteres, la presencia de rocas y la uniformidad del terreno. Esta información fue crítica para los controladores de vuelo que guiarían el aterrizaje de la Apollo 11.",
  "La Apollo 10 también probó los trajes espaciales en el entorno lunar real. Aunque Stafford y Cernan no salieron al espacio exterior, sus trajes fueron presurizados y sometidos a las condiciones reales del espacio profundo durante horas. Los datos recopilados sobre el comportamiento de los trajes en esas condiciones fueron usados para hacer ajustes finales antes de la Apollo 11, donde Neil Armstrong y Buzz Aldrin sí caminarían sobre la Luna con esos trajes.",
  "Los datos de telemetría recopilados durante la Apollo 10 fueron analizados exhaustivamente por miles de ingenieros en la NASA. Cada sistema: el motor del módulo lunar, los computadoras de guía, los sistemas de soporte vital, las comunicaciones, el radar de aterrizaje, fue evaluado en condiciones de vuelo real. Los ingenieros identificaron docenas de pequeñas mejoras que se implementaron en el hardware y los procedimientos antes de la Apollo 11. La Apollo 10 fue, en todos los sentidos prácticos, la misión que garantizó el éxito de la Apollo 11.",
  "Uno de los aspectos más interesantes de la Apollo 10 es lo cerca que estuvo de ser la primera misión en aterrizar en la Luna. Algunos ingenieros y astronautas argumentaron que ya que la Apollo 10 estaba tan cerca y todo funcionaba perfectamente, ¿por qué no aterrizar? La NASA tomó la decisión conservadora de no hacerlo: el módulo lunar de la Apollo 10 no llevaba suficiente combustible para el aterrizaje y regreso, y los procedimientos de aterrizaje aún no habían sido completamente finalizados. Era demasiado arriesgado.",
  "La importancia de la Apollo 10 en la historia espacial es quizás la más subestimada de todas las misiones Apollo. Sin su meticuloso ensayo, el aterrizaje de la Apollo 11 hubiera sido mucho más arriesgado e incierto. La Apollo 10 es el ejemplo perfecto de que en proyectos complejos y de alto riesgo, la preparación, las pruebas y los ensayos cuidadosos son tan importantes como el evento principal. El éxito del 20 de julio de 1969 se construyó sobre los hombros de la Apollo 10.",
  "La tripulación de la Apollo 10 regresó a la Tierra el 26 de mayo de 1969, amerizando en el Océano Pacífico. Apenas 50 días después, Neil Armstrong daría el primero de sus pasos históricos en la Luna. La Apollo 10 había cumplido perfectamente su misión: validar todos los sistemas, confirmar el sitio de aterrizaje, y preparar a la humanidad para el salto más grande de su historia. Stafford, Young y Cernan habían hecho posible el 'un pequeño paso para el hombre, un gran salto para la humanidad'."
], [
  { q: "¿Cómo se llamaba el módulo lunar de la Apollo 10?", options: ["Eagle", "Charlie Brown", "Snoopy", "Columbia"], a: 2 },
  { q: "¿A qué distancia mínima de la superficie lunar llegó el módulo lunar de la Apollo 10?", options: ["5 kilómetros", "15 kilómetros", "50 kilómetros", "100 kilómetros"], a: 1 },
  { q: "¿Qué récord estableció la Apollo 10 que sigue en pie hasta hoy?", options: ["El cohete más poderoso", "La mayor velocidad alcanzada por seres humanos", "El vuelo más largo en la Luna", "El mayor número de órbitas lunares"], a: 1 },
  { q: "¿Qué incidente dramático ocurrió cuando Stafford y Cernan intentaban separar los módulos del Snoopy?", options: ["Se quedaron sin combustible", "El módulo comenzó a girar descontroladamente", "Se rompió la antena de comunicaciones", "Perdieron contacto con Houston"], a: 1 },
  { q: "¿Por qué la NASA decidió no aterrizar durante la Apollo 10?", options: ["Porque los astronautas tenían miedo", "Porque el sistema de aterrizaje estaba roto", "Porque el módulo no llevaba suficiente combustible y los procedimientos no estaban finalizados", "Porque la superficie era demasiado rocosa"], a: 2 }
]);

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ Apollo 8 (m1+m2) and Apollo 10 (m1) patched!');
