const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'lib', 'courseData.js');
let raw = fs.readFileSync(filePath, 'utf8');
let data = JSON.parse(raw.replace(/^export default /, '').replace(/;$/, ''));

const bttf_m1 = [
  "¡Bienvenido al laboratorio del Dr. Emmett Brown, científico del tiempo! En la película Volver al Futuro de 1985, el Condensador de Flujo es el dispositivo que 'hace posible el viaje en el tiempo' dentro del automóvil DeLorean. El Dr. Brown lo inventó en 1955 al golpearse la cabeza con el lavabo del baño mientras intentaba colgar un reloj. Hoy vamos a explorar qué diría la física real sobre esta máquina ficticia, qué sabemos realmente sobre el tiempo y si los viajes temporales son posibles según las leyes del universo. ¡Abróchate el cinturón porque vamos a alcanzar 88 millas por hora en ciencia! ⚡",
  "El Condensador de Flujo en la película requiere exactamente 1.21 gigawatts de energía para funcionar. Un gigawatt es igual a 1,000 megawatts, o un billón de watts. Para comparar, una central nuclear moderna produce entre 1 y 1.5 gigawatts de electricidad, suficiente para abastecer a unos 750,000 hogares (U.S. Energy Information Administration). El rayo que usa Doc Brown para activar el condensador en 1955 (cuando todavía no tenía plutonio) es real en cuanto a la energía: un rayo promedio libera entre 1 y 5 gigajoules de energía en microsegundos, lo que equivale a una potencia momentánea de millones de watts (NOAA). Sin embargo, capturar y usar esa energía con precisión es extraordinariamente difícil.",
  "El tiempo, en la física moderna, no es el fluido constante e inmutable que intuimos en nuestra vida cotidiana. Albert Einstein demostró en 1905, con su Teoría de la Relatividad Especial, que el tiempo es relativo: pasa a diferentes velocidades según la velocidad del observador (Einstein, 1905). En 1915, con la Relatividad General, Einstein mostró que la gravedad también ralentiza el tiempo: los relojes en altitudes más elevadas (con menos gravedad) corren ligeramente más rápido que los relojes en el suelo (Einstein, 1915). Ambos efectos han sido medidos experimentalmente con una precisión extraordinaria. El tiempo no es absoluto: es una dimensión del espacio-tiempo que puede curvarse y dilatarse.",
  "La dilatación del tiempo no es solo teoría: es una realidad comprobada que afecta nuestra tecnología cotidiana. Los satélites GPS orbitan la Tierra a unos 20,200 km de altitud, donde la gravedad es menor, por lo que sus relojes avanzan unas 38 microsegundos más rápido al día que los relojes en la Tierra (NASA). Si los ingenieros no corrigieran este efecto relativista, el GPS se desviría unos 10 kilómetros por día, haciendo inútil la navegación. Los relojes atómicos en aviones de alta velocidad también pierden nanoseguntos respecto a los relojes en tierra, exactamente como predice Einstein (Hafele-Keating Experiment, 1971). ¡La relatividad del tiempo ya vive en tu teléfono!",
  "El plutonio que usa el Condensador de Flujo en la primera película es un elemento real, el elemento 94 de la tabla periódica. El Pu-239 es fisible, es decir, cuando un neutrón golpea su núcleo, se divide liberando más neutrones y una enorme cantidad de energía (E=mc²). Un kilogramo de plutonio-239 contiene energía equivalente a unas 20,000 toneladas de TNT cuando se fisiona completamente (U.S. Department of Energy). Es el material que se usó en la bomba de Nagasaki en 1945. Sin embargo, producir plutonio requiere reactores nucleares especiales, y su manejo es extremadamente peligroso por su alta toxicidad y radiactividad. En la segunda película, Doc sustituye el plutonio por residuos domésticos en el Mr. Fusion: la fusión nuclear en casa, un concepto inspirador aunque actualmente irreal.",
  "La fusión nuclear, la fuente de energía de las estrellas, es en realidad el sueño más ambicioso de la energía limpia. En diciembre de 2022, el National Ignition Facility de California logró por primera vez producir más energía de fusión de la que se inyectó en el experimento: 3.15 megajoules producidos frente a 2.05 megajoules inyectados, un rendimiento de 153% (Science, 2022). Esta fue una de las noticias científicas más importantes de la década. El proyecto ITER en Francia, con 35 países colaborando, construye el reactor de fusión más grande del mundo y espera demostrar producción sostenida de energía de fusión en los años 2030 (ITER Organization). ¡El Mr. Fusion se está acercando a la realidad!",
  "Para que el Condensador de Flujo creara un agujero de gusano o una curvatura del espacio-tiempo (aunque la película no lo dice explícitamente), necesitaría manipular la geometría del espacio-tiempo. Según la Relatividad General de Einstein, el espacio-tiempo puede curvarse localmente cuando hay masa o energía concentrada (Einstein, 1915). Los agujeros de gusano, también llamados puentes de Einstein-Rosen, son soluciones matemáticas a las ecuaciones de campo de Einstein que permiten en teoría conectar dos puntos distantes del espacio-tiempo (Einstein & Rosen, 1935). El problema es que requieren cantidades de energía negativa exótica que no existen en la naturaleza conocida. ¡Los agujeros de gusano son matemáticamente posibles pero físicamente especulativos!",
  "Los relojes atómicos, los instrumentos de medición del tiempo más precisos que existen, son una tecnología real nacida de la misma física que haría posible el Condensador de Flujo. Un reloj atómico moderno se desvía menos de un segundo cada 300 millones de años. Se basan en las transiciones entre estados de energía de átomos, típicamente cesio-133, que ocurren a frecuencias perfectamente constantes (NIST). La definición del segundo desde 1967 se basa precisamente en 9,192,631,770 oscilaciones de la radiación emitida por el cesio-133 (Bureau International des Poids et Mesures). ¡El segundo que usas cada día es una medida cuántica basada en átomos de cesio!",
  "La pregunta '¿Pueden existir los viajes al pasado?' es una de las más debatidas en física teórica. Las Curvas Cerradas de Tipo Tiempo (CTC, por sus siglas en inglés) son soluciones de las ecuaciones de Einstein que permitirían volver al pasado, y fueron descubiertas matemáticamente por Kurt Gödel en 1949 (Reviews of Modern Physics, 1949). Sin embargo, Stephen Hawking formuló la Conjetura de Protección de la Cronología, que propone que la naturaleza conspira para evitar viajes al pasado, posiblemente mediante fluctuaciones cuánticas que destruirían cualquier máquina del tiempo antes de que pudiera usarse (Physical Review D, 1992). ¡El tiempo parece protegerse a sí mismo!",
  "Para los jóvenes científicos que quieren explorar la física del tiempo, hay recursos excelentes. La plataforma Coursera ofrece el curso 'From the Big Bang to Dark Energy' de la Universidad de Tokio, que explica la relatividad de forma accesible. El libro '¿Qué es el tiempo?' de Sean Carroll es una introducción brillante al problema del tiempo en física (Carroll, 2010). El simulador GPS relativistico de NASA demuestra visualmente cómo la relatividad corrige las señales GPS. Y puedes observar un efecto real del tiempo relativístico: los muones cósmicos. Estos partículas subatómicas creadas en la atmósfera alta llegan al suelo porque su tiempo se dilata al viajar casi a la velocidad de la luz (Physical Review, 1941). ¡La dilatación del tiempo real ocurre sobre tu cabeza ahora mismo!",
  "Un descubrimiento notable: en 2020, investigadores de la Universidad Nacional de Australia usaron una computadora cuántica para simular el 'retroceso' en el tiempo de un fotón, haciendo que el estado del fotón evolucionara hacia atrás en el tiempo por una fracción de segundo (Science Advances, 2020). Aunque esto no es viajar al pasado como en la película, demuestra que la mecánica cuántica tiene características que parecen violar la flecha del tiempo clásica. El teorema CPT de la física de partículas afirma que las leyes de la física son simétricas bajo la inversión simultánea de carga, paridad y tiempo, lo que sugiere que el tiempo invertido es matemáticamente consistente. ¡La física cuántica y el tiempo son compañeros extraños y fascinantes!",
  "Tú, explorador del tiempo, puedes hacer un experimento real con dilatación del tiempo. Descarga una aplicación de reloj atómico en tu teléfono. Los relojes de los satélites GPS que sincronizan tu teléfono corren más rápido que tu reloj local por las correcciones relativistas. Investiga cuánto se desviaría el GPS si no se aplicaran estas correcciones (¡más de 10 km al día!). Busca el experimento de Hafele y Keating de 1971, donde dos relojes atómicos en aviones dieron tiempos diferentes al reloj de tierra, exactamente como predice Einstein. ¡Estás comprobando la física de Einstein con herramientas que tienes en el bolsillo!",
  "Las misiones futuras que dependen de la física del tiempo incluyen los relojes de red óptica, que serán 1,000 veces más precisos que los relojes de cesio actuales y permitirán detectar variaciones gravitacionales minúsculas (NIST, 2022). Estos relojes ultraprecisos podrían detectar el paso de asteroides cercanos por las variaciones en el campo gravitacional, o medir la variación temporal entre cimas de montañas y valles con una precisión que revelará la estructura interna de la Tierra (Nature Physics, 2022). La Agencia Espacial Europea planea la misión STE-QUEST para medir la dilatación gravitacional del tiempo con precisión sin precedentes (ESA). ¡Los relojes del futuro medirán la curvatura del universo!",
  "El tiempo, en la física moderna, tiene una dirección privilegiada: va del pasado al futuro. Esta dirección se llama la Flecha del Tiempo, y es uno de los mayores misterios de la física porque las leyes fundamentales de la naturaleza son simétricas en el tiempo: funcionan igual hacia adelante que hacia atrás. La dirección del tiempo emerge de la termodinámica, específicamente de la Segunda Ley: la entropía (el desorden) siempre aumenta. Un vaso roto no se reensambla espontáneamente porque habría que reducir la entropía del sistema (Boltzmann, 1877). El Condensador de Flujo de Doc Brown viola esta flecha al viajar al pasado, lo que muchos físicos consideran el mayor obstáculo para los viajes temporales reales.",
  "¡Sesión en el laboratorio de Doc Brown completada, explorador del tiempo! Ahora sabes que el Condensador de Flujo requiere energía equivalente a una planta nuclear, que la dilatación del tiempo de Einstein es un fenómeno real que afecta a tu GPS cada día, y que el plutonio es un material nuclear real con una energía enorme pero peligroso. Los viajes al pasado enfrentan obstáculos matemáticos y físicos enormes, aunque la física cuántica sigue sorprendiéndonos. El tiempo es la dimensión más misteriosa del universo, y los científicos del futuro —quizás tú— podrían revelar sus secretos más profundos. ¡El flujo continúa! 🌟"
];

const bttf_m2 = [
  "¡Doctor en relatividad aquí, explorador del espacio-tiempo! En Volver al Futuro, el DeLorean viaja 30 años hacia el pasado y hacia el futuro. En el universo real, la Teoría de la Relatividad de Albert Einstein, publicada en dos partes en 1905 y 1915, es la mejor descripción que tenemos del espacio, el tiempo, la gravedad y la velocidad. Y sus predicciones son tan asombrosas que parecen sacadas de una película de ciencia ficción. Hoy vamos a explorar cómo la relatividad funciona realmente y por qué dice que el tiempo es mucho más extraño de lo que pensamos. ¡Activa tu motor de relatividad! ⏰",
  "La Teoría de la Relatividad Especial de Einstein tiene dos postulados fundamentales. Primero: las leyes de la física son las mismas para todos los observadores que se mueven a velocidad constante entre sí. Segundo: la velocidad de la luz en el vacío es siempre la misma (299,792,458 m/s) para todos los observadores, independientemente de si la fuente de luz o el observador se mueven (Einstein, 1905). Estas dos ideas simples tienen consecuencias extraordinarias: el tiempo se dilata, el espacio se contrae y la masa aumenta a velocidades relativistas. ¡Con solo dos postulados, Einstein cambió para siempre nuestra comprensión del universo!",
  "La paradoja del gemelo es el ejemplo más famoso de dilatación del tiempo relativista. Si un gemelo viaja a una estrella cercana a casi la velocidad de la luz y regresa, encontrará que su hermano gemelo ha envejecido mucho más que él. El gemelo viajero experimentó el tiempo más lentamente debido a su alta velocidad. Esto no es paradoja: los gemelos no están en situaciones simétricas porque uno aceleró y desaceleró (que son cambios de velocidad). La fórmula de dilatación del tiempo es t' = t × √(1 - v²/c²): si viajas al 87% de la velocidad de la luz, el tiempo transcurre a la mitad de velocidad para ti que para los observadores estacionarios (Einstein, 1905). ¡El tiempo realmente pasa más despacio para objetos en movimiento!",
  "Partículas subatómicas llamadas muones son la prueba experimental más elegante de la dilatación del tiempo. Los muones se crean en la atmósfera superior cuando los rayos cósmicos chocan con moléculas de aire, a unos 15 km de altitud. Los muones tienen una vida media de solo 2.2 microsegundos antes de desintegrarse. Viajando a casi la velocidad de la luz, clásicamente solo recorrerían unos 660 metros antes de desintegrarse, nunca llegarían al suelo. Pero los detectores al nivel del mar sí detectan muones porque su tiempo de vida se dilata por su velocidad relativista: para ellos, apenas han pasado 2.2 microsegundos aunque externamente hayan pasado décadas de distancia (Physical Review, 1941). ¡Los muones son máquinas del tiempo naturales!",
  "La gravedad también dilata el tiempo, según la Relatividad General de Einstein (1915). Cuanto más fuerte es el campo gravitacional, más lentamente transcurre el tiempo. En la superficie de un agujero negro, el tiempo se pararía completamente desde la perspectiva de un observador lejano. En la superficie de la Tierra, el tiempo transcurre levemente más despacio que en la órbita de los satélites GPS. Esta diferencia es pequeña, solo unos 38 microsegundos por día, pero los satélites GPS deben corregir sus relojes exactamente por esta cantidad para dar posiciones precisas (NASA). ¡Sin la corrección relativista, tu aplicación de mapas se equivocaría 10 km al día!",
  "La contracción de Lorentz es otro efecto relativista: los objetos en movimiento rápido se contraen en la dirección del movimiento según observadores estacionarios. Si el DeLorean viajara al 87% de la velocidad de la luz, los observadores externos lo verían comprimido a la mitad de su longitud. Sin embargo, el Dr. Brown y Marty dentro del DeLorean no notarían nada especial: para ellos todo tiene el tamaño normal. Este efecto es recíproco: cada observador ve al otro comprimido (Einstein, 1905). A las velocidades cotidianas (incluso en aviones o cohetes), la contracción de Lorentz es completamente imperceptible. Pero cerca de la velocidad de la luz, el universo cambia de forma dramática.",
  "E=mc² es quizás la ecuación más famosa de la historia, publicada por Einstein en 1905. Establece que la masa y la energía son equivalentes: una pequeña cantidad de masa puede convertirse en una cantidad enorme de energía multiplicada por el cuadrado de la velocidad de la luz (89,875,517,873,681,764 m²/s²). Un gramo de masa convertido completamente en energía liberaría 9×10¹³ joules, equivalente a la bomba atómica de Hiroshima. Las reacciones nucleares de fisión (centrales nucleares, bombas atómicas) convierten solo el 0.1% de la masa en energía. La fusión nuclear convierte el 0.7%. La antimateria convertiría el 100%. ¡La equivalencia masa-energía de Einstein hace posibles las centrales nucleares y también explica por qué las estrellas brillan!",
  "El experimento de Michelson-Morley de 1887 fue el que pavimentó el camino para Einstein demostrando que la velocidad de la luz es la misma en todas las direcciones, aunque la Tierra se mueva alrededor del Sol (Physical Review, 1887). Hasta entonces, los físicos pensaban que la luz viajaba a través de un medio llamado éter, como el sonido viaja a través del aire. Michelson y Morley construyeron un interferómetro ultrapreciso para detectar el movimiento de la Tierra a través del éter. Para su sorpresa, no encontraron ninguna diferencia: la velocidad de la luz era la misma en todas las direcciones. Este resultado desconcertante fue el que Einstein explicó perfectamente con sus dos postulados 18 años después.",
  "En 2016, el detector LIGO detectó por primera vez ondas gravitacionales, ondas en el tejido del espacio-tiempo predichas por Einstein en 1916 (Physical Review Letters, 2016). Estas ondas fueron producidas por la colisión de dos agujeros negros a 1,300 millones de años luz de la Tierra. La deformación del espacio-tiempo que produjeron fue de solo 10⁻¹⁸ metros, menos que el diámetro de un protón. Detectarlas requirió uno de los instrumentos más sensibles jamás construidos. Este descubrimiento confirmó la última gran predicción de Einstein que quedaba sin verificar experimentalmente, 100 años después. ¡Einstein tenía razón en todo, un siglo más tarde!",
  "La teoría de cuerdas y la gravedad cuántica son los intentos actuales de unificar la Relatividad General (que rige lo muy grande) con la Mecánica Cuántica (que rige lo muy pequeño). Estas dos teorías son incompatibles matemáticamente: cuando se aplican juntas en condiciones extremas como el interior de los agujeros negros o el Big Bang, producen resultados infinitos sin sentido (Physical Review, 2023). La teoría de cuerdas propone que las partículas fundamentales no son puntos sino cuerdas vibrantes en 10 o 11 dimensiones. Aunque no hay pruebas experimentales directas todavía, es la candidata más estudiada para una 'Teoría del Todo'. ¡La física del universo todavía tiene misterios sin resolver que esperan a la próxima generación de científicos!",
  "Un hecho asombroso y real: los astrónomos han observado el tiempo dilatándose directamente en supernovas distantes. Cuando una supernova explota en una galaxia lejana que se aleja de nosotros a alta velocidad, la explosión parece ocurrir más lentamente de lo esperado, exactamente en la proporción predicha por la relatividad especial (Leibundgut et al., 1996). Este efecto, combinado con la expansión del universo, demostró que el universo no solo se expande sino que lo hace de forma acelerada, lo que llevó al descubrimiento de la energía oscura en 1998 y al Premio Nobel de Física de 2011 (Nobel Prize, 2011). ¡La relatividad de Einstein ayudó a descubrir la fuerza misteriosa que domina el universo!",
  "Tú puedes experimentar con la relatividad desde casa de formas sorprendentes. Sincroniza un reloj de alta precisión de tu teléfono con un servidor NTP (Network Time Protocol) antes de salir en un vuelo largo, y compara la hora al regresar: la diferencia de nanosegundos existe aunque sea muy pequeña. Usa la aplicación GPS de tu teléfono y aprecia que funciona gracias a correcciones relativistas. Lee el libro 'Relativity: The Special and General Theory' de Einstein, publicado en 1916, que él mismo escribió para el público general y está disponible gratis en internet (Einstein, 1916). ¡El padre de la relatividad quería que todos la entendieran!",
  "Las aplicaciones futuras de la relatividad incluyen relojes ópticos de red de estroncio que son tan precisos que podrían medir diferencias de altura de solo un centímetro en la Tierra a través de la dilatación gravitacional del tiempo (Nature, 2018). Estos relojes ultra-precisos podrían usarse para predecir erupciones volcánicas detectando el movimiento de magma en el interior de la Tierra. La sincronización de tiempo relativista también será esencial para la futura red de comunicaciones cuánticas global. Y si alguna vez se construye una nave que viaje a fracciones significativas de la velocidad de la luz, la relatividad determinará cómo calcular el tiempo de viaje para la tripulación frente al tiempo transcurrido en la Tierra.",
  "La relatividad nos enseña algo profundo sobre la naturaleza de la realidad: no existe un 'ahora' universal compartido por todos los observadores. Lo que es simultáneo para un observador puede no serlo para otro que se mueve a diferente velocidad. El tiempo y el espacio son partes de una misma entidad cuatridimensional, el espacio-tiempo, y cada observador tiene su propia historia temporal. Esta idea, aunque antiintuitiva, ha sido verificada con una precisión de décimas de trillonésimas de partes (NIST, 2023). La relatividad no es una teoría incompleta o provisional: es una de las teorías más precisas y verificadas de toda la física. ¡Einstein cambió para siempre cómo entendemos la realidad!",
  "¡Graduado en relatividad einsteiniana, explorador del tiempo! Ahora sabes que E=mc² conecta masa y energía de forma fundamental, que los muones son máquinas del tiempo naturales que prueban la dilatación temporal, que el GPS de tu teléfono corrige efectos relativistas todos los días, y que las ondas gravitacionales confirmaron en 2016 la última gran predicción de Einstein. La relatividad no es solo teoría abstracta: es una tecnología activa en todos los satélites GPS, los aceleradores de partículas y los detectores de ondas gravitacionales. El universo es más extraño y maravilloso que cualquier película. ¡El tiempo te espera! 🌟"
];

const bttf_m3 = [
  "¡Bienvenido al departamento de paradojas temporales, explorador lógico! En Volver al Futuro, Marty McFly viaja al pasado y casi impide que sus padres se conozcan, lo que podría borrar su propia existencia. Esta situación dramática ilustra la famosa Paradoja del Abuelo, uno de los argumentos más clásicos contra los viajes en el tiempo. Pero los físicos y filósofos modernos tienen respuestas fascinantes a estas paradojas. ¿Qué dicen la mecánica cuántica y la cosmología sobre los universos paralelos y las líneas de tiempo divergentes? ¡Prepárate para que tu lógica se doble! 🌀",
  "La Paradoja del Abuelo es el argumento filosófico más famoso contra los viajes al pasado: si pudieras viajar al pasado y matar a tu propio abuelo antes de que naciera tu padre, tú nunca habrías nacido. Pero si nunca naciste, no pudiste viajar al pasado a matarlo. Y si no lo mataste, naciste, y entonces sí podías viajar... Esto crea un bucle lógico sin solución. El filósofo David Lewis propuso en 1976 que los viajes al pasado son posibles solo si ocurren de formas consistentes con la historia que ya sucedió (Philosophical Review, 1976). Es decir, si viajaste al pasado, ya formabas parte de esa historia todo el tiempo, aunque no lo supieras.",
  "La Conjetura de Consistencia de Novikov, formulada por el físico ruso Igor Novikov en los años 1980, propone que los viajes al pasado son posibles pero solo si no crean paradojas: el principio de autoconsistencia requiere que todo lo que ocurra en el pasado al que viajes sea consistente con la historia (Physical Review D, 1990). En otras palabras, la probabilidad de ocurrencia de eventos que creen paradojas es exactamente cero. Si intentas matar a tu abuelo, algo te lo impedirá siempre. La propia física del universo lo evitaría. Esta idea es matemáticamente elegante: el universo se protege a sí mismo de las inconsistencias temporales.",
  "El físico Hugh Everett III propuso en 1957 la Interpretación de los Muchos Mundos de la mecánica cuántica (Reviews of Modern Physics, 1957). Según esta interpretación, cada vez que ocurre un evento cuántico con múltiples resultados posibles (como si un electrón gira hacia arriba o hacia abajo), el universo se divide en ramas separadas donde ambos resultados ocurren. Hay una rama donde el electrón gira hacia arriba y otra donde gira hacia abajo, ambas igualmente reales pero incomunicadas entre sí. Si esta interpretación es correcta, existen literalmente infinitos universos paralelos con todas las variaciones posibles de la historia. ¡Cada decisión que tomas crea nuevas ramas de realidad!",
  "La interpretación de los Muchos Mundos resolveía la Paradoja del Abuelo de forma elegante: cuando Marty viaja al pasado y cambia la historia, no borra su propia realidad original sino que crea una rama paralela del universo donde sus padres no se conocen. El Marty original sigue existiendo en su universo, mientras que en la nueva rama el Marty que viajó quizás no nació. Esta solución de 'universos paralelos' es exactamente la que usa la saga Volver al Futuro, especialmente en la segunda película con el libro 'Lo guía del viaje en el tiempo' de Doc Brown. ¡La película usa física cuántica real como base narrativa!",
  "Otros físicos prefieren la Hipótesis de Protección de la Cronología de Stephen Hawking: las leyes de la física conspiran para impedir los viajes al pasado (Physical Review D, 1992). Hawking argumentó que la mecánica cuántica impediría la formación de bucles cerrados de tipo tiempo (CTCs) porque las fluctuaciones cuánticas del vacío aportarían cantidades de energía que destruirían cualquier máquina del tiempo en el momento de su creación. En 2005, Hawking actualizó esta hipótesis con cálculos que sugieren que la radiación cuántica siempre desestabiliza las condiciones necesarias para un CTC. ¡El universo tendría un sistema de seguridad automático contra las paradojas temporales!",
  "El Principio Antrópico fuerte afirma que el universo debe tener las propiedades que permitan la existencia de observadores conscientes, ya que de otra forma nadie estaría aquí para observarlo. Algunos físicos como John Wheeler lo extienden para argumentar que la presencia de observadores es necesaria para que el universo exista en su forma actual (Wheeler, 1983). Esto crea una suerte de paradoja de bootstrap: la existencia del universo depende de que haya observadores que lo observen, y los observadores solo pueden existir si el universo existe. La paradoja de Marty McFly que casi se borra a sí mismo tiene ecos en este tipo de paradojas cosmológicas reales sobre la auto-referencia del universo.",
  "La topología del espacio-tiempo permite, en las ecuaciones de Einstein, soluciones con topologías exóticas. Las Regiones de Malament-Hogarth son regiones del espacio-tiempo donde un observador puede vivir un tiempo infinito mientras para otro observador externo solo pasa un tiempo finito (Classical and Quantum Gravity, 1992). Los universos de Gödel, soluciones exactas de las ecuaciones de Einstein encontradas por Kurt Gödel en 1949, son universos rotatorios donde las Curvas Cerradas de Tipo Tiempo son posibles en principio (Reviews of Modern Physics, 1949). En estos universos, las líneas de tiempo cerradas existen matemáticamente. ¡Las ecuaciones de Einstein realmente admiten viajes al pasado en ciertos universos exóticos!",
  "La teleportación cuántica, a diferencia del viaje en el tiempo, ya es una tecnología real. En 2022, un equipo de Caltech teleportó información cuántica a través de una red de fibra óptica de 44 km en California (Nature, 2022). La teleportación cuántica no teletransporta materia física: teletransporta el estado cuántico de una partícula a otra partícula distante usando el entrelazamiento cuántico. Es como copiar perfectamente el patrón de información de un qubit aquí y reproducirlo allá instantáneamente, destruyendo el original en el proceso. China teletransportó estados cuánticos desde la Tierra al satélite Micius a más de 1,400 km de distancia (Science, 2017). ¡La teleportación real ya existe, aunque no para personas!",
  "Las computadoras cuánticas tienen un vínculo fascinante con las paradojas temporales. El algoritmo de Grover para computadoras cuánticas puede buscar en una base de datos desordenada en √N pasos en lugar de los N pasos que requiere una computadora clásica. Esto se debe en parte a que la computación cuántica explora múltiples caminos de computación simultáneamente, como si todas las historias posibles del cálculo ocurrieran a la vez (Grover, 1996). Algunos investigadores han propuesto que las computadoras cuánticas de circuito cerrado (que usan CTCs simuladas) podrían resolver ciertos problemas computacionales imposibles para computadoras ordinarias. ¡Las paradojas temporales cuánticas podrían tener aplicaciones computacionales!",
  "Un experimento real que roza las paradojas temporales es el del borrador de medición cuántica. En mecánica cuántica, el experimento de borrador cuántico muestra que el resultado de un experimento de doble rendija puede cambiar retroactivamente después de que las partículas han completado su viaje, dependiendo de si se obtiene o se 'borra' la información de cuál rendija usó la partícula (Physical Review Letters, 2000). Es como si el pasado cambiara según decisiones tomadas en el futuro. Aunque no viola la causalidad (no puede transmitirse información útil hacia el pasado), sí muestra que la causalidad cuántica es mucho más sutil y extraña de lo que nuestra intuición sugiere. ¡El universo cuántico es el mejor escritor de paradojas!",
  "Para explorar las paradojas temporales y la física cuántica, tú puedes: ver el documental 'The Quantum Tamers' del CBC que explica la mecánica cuántica con ejemplos visuales. Leer 'Cracking the Quantum Code' de David Deutsch (Deutsch, 2011), el fundador de la computación cuántica, que explica la interpretación de los Muchos Mundos. Jugar al videojuego 'Braid', un juego de plataformas que usa mecánicas de manipulación del tiempo para resolver puzzles, ilustrando muchos conceptos de líneas de tiempo alternativas. Y participar en el proyecto Quantum Game, una plataforma educativa online del Instituto Perimeter que enseña mecánica cuántica de forma interactiva. ¡La paradoja más divertida es que aprender física cuántica no es una paradoja!",
  "Las misiones futuras relacionadas con las paradojas temporales incluyen el estudio de los agujeros negros con el Event Horizon Telescope, que en 2019 capturó la primera imagen de un agujero negro (la sombra del agujero negro de M87) (Nature, 2019). Los agujeros negros son el lugar donde la física del tiempo se vuelve más extrema: el tiempo se detiene en el horizonte de sucesos desde la perspectiva de un observador externo. El estudio del interior de los agujeros negros, donde la Relatividad General y la Mecánica Cuántica se fusionan, podría revelar si las líneas de tiempo cerradas son físicamente posibles. La misión LISA de ESA, prevista para 2034, detectará ondas gravitacionales de agujeros negros supermasivos con precisión sin precedentes (ESA).",
  "Las paradojas temporales nos enseñan algo profundo sobre la lógica y la causalidad. La causalidad, la idea de que las causas preceden a los efectos, es uno de los principios más fundamentales de la física clásica y de nuestra percepción del mundo. Sin causalidad, la ciencia y la lógica perderían sus fundamentos: si los efectos pudieran preceder a las causas, no habría forma de construir modelos predecibles del universo. La mayoría de los físicos creen que, aunque las ecuaciones de Einstein admitan matemáticamente líneas de tiempo cerradas, las leyes del universo reales, especialmente las cuánticas, protejan la causalidad. ¡La lógica del universo parece estar del lado de Hawking!",
  "¡Paradoja resuelta, explorador del espacio-tiempo! Ahora sabes que la Paradoja del Abuelo se resuelve por consistencia (Novikov) o por universos paralelos (Everett), que la Hipótesis de Protección de la Cronología de Hawking sugiere que el universo se defiende de las paradojas, y que la teleportación cuántica ya es real aunque no para personas. Los Muchos Mundos de Everett son una interpretación tomada en serio por muchos físicos. Las paradojas temporales no son solo juegos mentales: revelan los límites y las profundidades de nuestra comprensión del universo. ¡Sigue explorando las paradojas porque ahí viven las preguntas más interesantes! 🌟"
];

// Patch the modules
let patched = 0;
for (let module of data) {
  if (module.id === 'bttf_m1') {
    module.contentEs.sections[0].text = bttf_m1;
    patched++;
  }
  if (module.id === 'bttf_m2') {
    module.contentEs.sections[0].text = bttf_m2;
    patched++;
  }
  if (module.id === 'bttf_m3') {
    module.contentEs.sections[0].text = bttf_m3;
    patched++;
  }
}

console.log(`Patched ${patched} modules.`);
fs.writeFileSync(filePath, 'export default ' + JSON.stringify(data, null, 2) + ';', 'utf8');
console.log('File written successfully.');
