const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

function replaceSection(src, moduleId, newParagraphs, newQuiz) {
  const moduleStart = src.indexOf(`"id": "${moduleId}"`);
  if (moduleStart === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  const sectionsStart = src.indexOf('"sections"', moduleStart);
  const textStart = src.indexOf('"text"', sectionsStart);
  const arrStart = src.indexOf('[', textStart);
  let depth = 0, i = arrStart;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  const arrEnd = i;
  const newTextBlock = JSON.stringify(newParagraphs, null, 14);
  src = src.slice(0, arrStart) + newTextBlock + src.slice(arrEnd + 1);

  if (newQuiz) {
    const quizStart = src.indexOf('"quizEs"', src.indexOf(`"id": "${moduleId}"`));
    const quizArrStart = src.indexOf('[', quizStart);
    let d2 = 0, j = quizArrStart;
    while (j < src.length) {
      if (src[j] === '[') d2++;
      else if (src[j] === ']') { d2--; if (d2 === 0) break; }
      j++;
    }
    src = src.slice(0, quizArrStart) + JSON.stringify(newQuiz, null, 4) + src.slice(j + 1);
  }
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// egypt_m8 — Abu Simbel y la Luz del Solsticio
const egypt_m8_paragraphs = [
  "¡Bienvenido a la misión más luminosa del año, cadete! El 22 de febrero de cada año, algo mágico ocurre en el sur de Egipto. En el templo de Abu Simbel, cuatro estatuas colosales de 20 metros de altura vigilan la entrada de una montaña de roca. Pero dos veces al año, en fechas exactas que los ingenieros del faraón Ramsés II calcularon hace 3,200 años, los primeros rayos del sol naciente se cuelan por la puerta del templo y viajan 65 metros por el corredor oscuro.",
  "Al final de ese corredor, la luz ilumina directamente las estatuas del santuario interior: Ramsés II, Ra-Horajti (dios del sol) y Amón (rey de los dioses). Solo la estatua de Ptah, dios de las tinieblas, permanece en sombra. Este fenómeno ocurre exactamente dos veces al año: el 22 de febrero y el 22 de octubre. Los historiadores creen que estas fechas corresponden al cumpleaños y al día de coronación de Ramsés II.",
  "Para lograr este efecto, los ingenieros egipcios tuvieron que calcular el ángulo exacto al que sale el Sol sobre el horizonte en esas dos fechas en esa latitud específica (22° Norte). Luego excavaron el corredor de 65 metros de largo con exactamente ese ángulo. Un error de un solo grado habría desplazado el rayo de luz varios metros y perdido el santuario en la oscuridad. La precisión requerida equivale a apuntar un láser a un blanco del tamaño de una moneda desde 100 metros de distancia.",
  "Abu Simbel fue excavado directamente en la roca de una montaña de arenisca roja entre 1264 y 1244 a.C. La montaña tiene 30 metros de alto, y el santuario interior está a 65 metros de profundidad. Los cuatro colosos de la fachada miden entre 17 y 20 metros de altura. Esta escala monumental no era para impresionar a los turistas; era para que los nubios al sur y los libios al oeste entendieran que Ramsés II era un dios en la Tierra.",
  "En 1964, cuando la construcción de la Presa de Asuán amenazó con inundar Abu Simbel bajo las aguas del Lago Nasser, la UNESCO organizó una de las operaciones de salvamento arqueológico más grandes de la historia. El templo fue cortado en 1,036 bloques de hasta 30 toneladas cada uno, transportados y reensamblados en una colina artificial 65 metros más arriba y 200 metros alejado del original. La nueva ubicación mantiene exactamente las mismas orientaciones astronómicas.",
  "El traslado de Abu Simbel fue una hazaña de ingeniería moderna comparable en audacia a las pirámides originales. Tardó cuatro años (1964-1968), costó 80 millones de dólares (equivalentes a 600 millones de hoy), e involucró a ingenieros de 50 países diferentes. La cúpula artificial que cubre el interior del templo trasladado fue diseñada para reproducir exactamente la oscuridad interna del original, garantizando que el fenómeno luminoso del 22 de febrero se repitiera.",
  "El fenómeno luminoso de Abu Simbel ocurre también en el templo adyacente de Nefertari, la esposa favorita de Ramsés II. En este caso, la luz ilumina la estatua de Hathor, diosa del amor y la belleza. Es uno de los pocos templos de Egipto dedicado a una reina, y su orientación astronómica refuerza el mensaje de la importancia de Nefertari en la ideología del reinado de Ramsés II.",
  "La arenisca roja de Abu Simbel tiene una característica física especial: cuando la luz del sol la ilumina, absorbe y re-emite el calor de manera que la roca 'brilla' con un tono dorado intenso. Los ingenieros egipcios escogieron deliberadamente este material por su comportamiento óptico, creando un efecto visual donde las estatuas parecen literalmente encenderse con fuego divino durante los momentos de iluminación solar.",
  "El templo de Abu Simbel está orientado hacia el este, hacia el lugar donde sale el Sol. Pero los egipcios sabían que el Sol no sale exactamente por el Este todos los días: cambia su posición a lo largo del año entre los puntos de los solsticios. Solo en los equinoccios (21 de marzo y 22 de septiembre) el Sol sale exactamente por el Este. En las otras fechas, como el 22 de febrero, el Sol sale ligeramente al norte o al sur del Este exacto, y los ingenieros calcularon ese ángulo preciso.",
  "La inscripción en los muros de Abu Simbel narra la batalla de Qadesh, librada hacia el 1274 a.C. entre Ramsés II y los hititas. Aunque el resultado fue un empate diplomático, Ramsés lo representó como una victoria aplastante. Las pinturas muestran al faraón como un guerrero sobrehumano, solo contra miles de enemigos. Este mismo espíritu de grandiosidad y exageración estratégica está presente en las dimensiones astronómicas del templo: todo en Abu Simbel está diseñado para impresionar y afirmar la divinidad del faraón.",
  "Los sacerdotes de Abu Simbel mantenían un calendario ritual vinculado a las alineaciones astronómicas del templo. Cada año, el 22 de febrero, celebraban una gran festividad que comenzaba antes del amanecer. Los sacerdotes con antorchas guiaban a los peregrinos al interior del templo en la oscuridad total. Cuando los primeros rayos del sol tocaban las estatuas, los sacerdotes comenzaban los cánticos y las ofrendas. Era un momento de unión entre el cosmos, el dios y el pueblo.",
  "Además del efecto del 22 de febrero, el templo de Abu Simbel tiene otras alineaciones secundarias. Los cuatro colosos de la fachada están orientados de manera que sus sombras proyectadas al mediodía marcan exactamente el centro geométrico de la puerta de entrada. Las estatuas de los prisioneros esculpidas en los pilones exteriores están orientadas para que el Sol del solsticio de verano proyecte sus sombras en ángulos que forman un patrón geométrico deliberado en el suelo.",
  "El lago artificial creado por la presa de Asuán (Lago Nasser) refleja el templo trasladado de Abu Simbel. Esta reflexión, visible claramente desde el aire, crea una imagen especular del templo sobre las aguas. Los fotógrafos del mundo entero viajan a Abu Simbel específicamente para capturar esta imagen doble del templo y su reflejo, que recuerda a los mapas antiguos donde el mundo terrenal era un reflejo del mundo celestial.",
  "Abu Simbel es hoy el sitio arqueológico más visitado de Egipto después de las pirámides de Guiza, atrayendo más de medio millón de visitantes al año. El 22 de febrero y el 22 de octubre, miles de personas viajan específicamente para presenciar el fenómeno de la luz solar. Es uno de los pocos momentos en que la arqueología y la astronomía se unen en un espectáculo que puede verse en tiempo real, sin necesidad de instrumentos científicos.",
  "El legado de Abu Simbel va más allá de la arqueología. Su traslado en los años 1960 inspiró la creación de la Convención del Patrimonio Mundial de la UNESCO en 1972, que hoy protege más de 1,100 sitios culturales y naturales en todo el planeta. Sin Abu Simbel, quizás no existiría el sistema internacional de protección del patrimonio humano. Un templo construido para glorificar a un faraón se convirtió, 3,000 años después, en la inspiración para proteger el patrimonio de toda la humanidad."
];

const egypt_m8_quiz = [
  { "q": "¿Cuándo ocurre el fenómeno de luz en Abu Simbel?", "options": ["Todos los días al mediodía", "El 22 de febrero y el 22 de octubre", "Solo en el solsticio de invierno", "Durante los eclipses"], "a": 1 },
  { "q": "¿Qué estatua permanece en sombra durante el fenómeno?", "options": ["Ramsés II", "Ra-Horajti", "Ptah", "Amón"], "a": 2 },
  { "q": "¿Por qué fue trasladado Abu Simbel en 1964?", "options": ["Para hacerlo más grande", "Porque la presa de Asuán lo iba a inundar", "Por un terremoto", "Para protegerlo de piratas"], "a": 1 },
  { "q": "¿En qué año se completó el traslado del templo?", "options": ["1960", "1968", "1975", "1985"], "a": 1 },
  { "q": "¿Qué tratado internacional inspiró el salvamento de Abu Simbel?", "options": ["El Tratado de Roma", "La Convención del Patrimonio Mundial de la UNESCO", "El Acuerdo de Viena", "La Carta de la ONU"], "a": 1 }
];

// egypt_m9 — Zodiaco de Dendera
const egypt_m9_paragraphs = [
  "¡Misión de descubrimiento secreto, cadete! En el techo de un pequeño cuarto en el templo de Hathor en Dendera, Egipto, existe un tesoro que cambió para siempre lo que sabemos sobre la historia de la astronomía. Se llama el Zodiaco de Dendera, y es el primer mapa circular completo del cielo nocturno que ha sobrevivido hasta nuestros días. Fue tallado en piedra hace aproximadamente 2,050 años, durante la época en que los faraones eran griegos (la dinastía ptolemaica).",
  "El Zodiaco de Dendera muestra las 12 constelaciones del zodíaco que todavía conocemos hoy: Aries, Tauro, Géminis, Cáncer, Leo, Virgo, Libra, Escorpio, Sagitario, Capricornio, Acuario y Piscis. Pero también incluye constelaciones puramente egipcias, como el Cocodrilo Celestial, el Hipopótamo y el Chacal. Es una fusión perfecta de astronomía griega y egipcia, creada en la época en que ambas culturas convivían en el mismo país.",
  "El disco mide aproximadamente 2.5 metros de diámetro y pesa varias toneladas. En el centro muestra el polo norte celeste y las estrellas circumpolares. En los círculos exteriores se representan las 36 constelaciones del calendario estelar egipcio (los Decanos). Figuras humanas y animales con brazos levantados sostienen el disco celeste completo, representando el esfuerzo de los dioses por mantener el cielo en su lugar.",
  "El original del Zodiaco de Dendera ya no está en Egipto. En 1820, el ingeniero francés Claude Lelorrain cortó el bloque de piedra del techo del templo usando sierras y pólvora, lo transportó a Francia y lo vendió al rey Luis XVIII. Hoy está expuesto en el Museo del Louvre en París. En el templo de Dendera, en su lugar, hay una copia de yeso pintado. Esta historia de robo y pérdida es desafortunadamente común en la arqueología del siglo XIX.",
  "Gracias al Zodiaco de Dendera, los astrónomos modernos han podido calcular con precisión la fecha en que fue tallado. El mapa muestra posiciones específicas del Sol, la Luna y los planetas que corresponden a una alineación celeste única que ocurrió en el año 50 a.C. Esta capacidad de usar la astronomía como una máquina del tiempo para fechar monumentos antiguos es una de las herramientas más poderosas de la arqueología moderna.",
  "El templo de Hathor en Dendera, donde se encontraba el Zodiaco, es uno de los templos mejor conservados de todo Egipto. Fue construido principalmente entre el 54 a.C. y el 20 d.C., durante los últimos faraones ptolemaicos y los primeros emperadores romanos. La famosa Cleopatra VII (la última faraona de Egipto) está representada en los relieves exteriores del templo junto a su hijo Cesarión (hijo de Julio César).",
  "El zodíaco egipcio original no era igual al zodíaco que usamos hoy. Los egipcios usaban 36 'meses estelares' de 10 días cada uno, basados en los Decanos (grupos de estrellas que salían en el horizonte sucesivamente a lo largo del año). El zodíaco de 12 constelaciones que aparece en Dendera fue adoptado de los griegos y babilonios, quienes lo habían desarrollado varios siglos antes. El Zodiaco de Dendera representa el momento histórico en que el sistema de 12 constelaciones reemplazó al sistema egipcio de 36 Decanos.",
  "Las representaciones de los planetas en el Zodiaco de Dendera son especialmente interesantes. Saturno aparece como un hombre en una barca; Júpiter como un águila sobre una serpiente; Marte como un guerrero con cabeza de halcón. Estas representaciones mezclan iconografía griega (las figuras de los planetas como dioses) con iconografía egipcia (los animales sagrados y las barcas divinas). Es una obra de arte que refleja la fusión de dos grandes tradiciones astronómicas.",
  "El Zodiaco de Dendera incluye también los cinco planetas visibles dispuestos en posiciones específicas relativas a las constelaciones. Los astrónomos han verificado que esta disposición planetaria corresponde exactamente al cielo del año 50 a.C., confirmando la fecha de creación del mapa. Esta convergencia entre el arte astronómico antiguo y la ciencia moderna es emocionante: el mapa funciona como una fotografía del cielo de hace 2,000 años.",
  "El templo de Hathor en Dendera también tiene un sistema de subterráneos debajo de las cámaras principales. En estas criptas estaban guardados los objetos rituales más sagrados del templo, incluyendo estatuillas de oro y papiros con textos secretos. En las paredes de las criptas hay relieves que muestran lo que parece ser una representación de bombillas eléctricas o tubos de descarga, lo que ha dado lugar a teorías populares (sin base científica) de que los egipcios tenían electricidad.",
  "El contexto histórico del Zodiaco de Dendera es fascinante. Fue creado en una época turbulenta: Egipto estaba bajo el dominio de los faraones griegos ptolemaicos, que habían gobernado desde la muerte de Alejandro Magno (323 a.C.). Roma crecía como potencia dominante. La reina Cleopatra VII intentaba mantener la independencia de Egipto alternando alianzas con Julio César y Marco Antonio. El templo de Dendera fue construido precisamente en este período de tensión política y fusión cultural.",
  "En el exterior del templo de Hathor en Dendera, sobre el pórtico principal, hay una galería de retratos de los faraones ptolemaicos. Entre ellos está la famosa imagen de Cleopatra VII en perfil, flanqueada por su hijo Cesarión. Es una de las pocas representaciones auténticas de Cleopatra que ha sobrevivido. Contrariamente a las representaciones modernas de Cleopatra como una mujer de extraordinaria belleza, las monedas e inscripciones de la época la muestran como una mujer de rasgos más comunes pero expresión inteligente y determinada.",
  "El zodíaco como sistema de predicción del futuro (la astrología) tuvo su origen en Babilonia y fue adoptado por los griegos, que lo transmitieron a los egipcios. En Egipto, la astrología se fusionó con la teología de los dioses y con el sistema médico. Se creía que los planetas influían en la salud, el destino y el carácter de las personas. Esta creencia, aunque científicamente incorrecta, impulsó siglos de observación astronómica meticulosa porque los astrólogos necesitaban predecir exactamente las posiciones planetarias.",
  "El Zodiaco de Dendera ha sido estudiado por generaciones de matemáticos, astrónomos e historiadores. El matemático francés Jean-Baptiste Fourier (famoso por la Transformada de Fourier, fundamental en telecomunicaciones modernas) fue uno de los primeros en analizar matemáticamente el Zodiaco en la década de 1800. La historia de cómo científicos modernos han usado el mapa para entender la astronomía antigua es en sí misma un capítulo fascinante de la historia de la ciencia.",
  "El legado del Zodiaco de Dendera es que nos muestra cómo el conocimiento astronómico ha viajado a través del tiempo y las culturas. Los mesopotamios observaron el cielo, crearon el zodíaco de 12 constelaciones y se lo transmitieron a los griegos. Los griegos lo refinaron matemáticamente y se lo llevaron a Egipto con Alejandro Magno. Los egipcios lo fusionaron con su propia tradición milenaria y crearon el Zodiaco de Dendera. Este mapa llegó a Roma, y de Roma a toda Europa. Hoy, cuando lees tu horóscopo en el periódico, estás viendo el último destello de este largo viaje de 5,000 años de astronomía."
];

const egypt_m9_quiz = [
  { "q": "¿Qué representa el Zodiaco de Dendera?", "options": ["Un mapa de Egipto", "El primer mapa circular completo del cielo nocturno", "Un calendario lunar simple", "El mapa del Nilo"], "a": 1 },
  { "q": "¿Dónde está el Zodiaco de Dendera hoy?", "options": ["En El Cairo", "En Londres", "En el Museo del Louvre, París", "En Nueva York"], "a": 2 },
  { "q": "¿A qué año corresponde la posición planetaria del Zodiaco?", "options": ["2500 a.C.", "1200 a.C.", "50 a.C.", "300 d.C."], "a": 2 },
  { "q": "¿Cuántas constelaciones zodiacales muestra el Zodiaco de Dendera?", "options": ["6", "10", "12", "36"], "a": 2 },
  { "q": "¿Quién aparece representada en el exterior del templo de Dendera?", "options": ["Nefertiti", "Cleopatra VII y su hijo Cesarión", "La reina Hatshepsut", "La diosa Isis"], "a": 1 }
];

// egypt_m10 — Daga Espacial de Tutankamón
const egypt_m10_paragraphs = [
  "¡Prepara los sensores de análisis de materiales, cadete! Uno de los misterios más emocionantes de la arqueología moderna se descubrió en la tumba del faraón niño Tutankamón, fallecido hace aproximadamente 3,300 años. Entre los miles de objetos de increíble belleza que acompañaban a la momia, había una daga con hoja de hierro. Nada extraordinario para un arma, ¿verdad? Pero hay un detalle que cambia todo: hace 3,300 años, el hierro era prácticamente desconocido en Egipto.",
  "En el Antiguo Egipto, los metales usados para hacer armas eran el bronce (una mezcla de cobre y estaño) y el cobre puro. El hierro, para los egipcios de esa época, era tan raro y misterioso que lo llamaban 'ba en pet': el metal del cielo. Lo consideraban un regalo de los dioses, literalmente caído del espacio. Y resulta que... ¡tenían absolutamente razón! El análisis científico de la daga de Tutankamón confirmó algo extraordinario.",
  "En 2016, un equipo de científicos italianos y egipcios usó una técnica llamada fluorescencia de rayos X para analizar la composición química de la hoja de la daga sin dañarla. Los resultados mostraron que la hoja contiene hierro, níquel y cobalto en proporciones que son completamente atípicas para el hierro terrestre pero perfectamente características del hierro meteorítico: hierro que llegó del espacio exterior.",
  "Los meteoritos de hierro son fragmentos de asteroides que caen a la Tierra. Cuando un asteroide se forma en el sistema solar, su núcleo metálico contiene una mezcla específica de hierro, níquel (entre 5% y 35%) y cobalto. El hierro de la hoja de Tutankamón contiene un 11% de níquel y 0.6% de cobalto, una proporción que solo se encuentra en los meteoritos de hierro. La daga de Tutankamón fue forjada usando metal que viajó por el espacio antes de llegar a manos de un artesano egipcio.",
  "¿Cómo llegó este meteorito de hierro a Egipto? Los meteoritos de hierro son bastante raros en cualquier lugar de la Tierra, pero el desierto del Sahara es uno de los mejores lugares del mundo para encontrarlos, porque el suelo árido y sin vegetación los preserva perfectamente durante miles de años y además facilita encontrarlos visualmente (son piedras negras sobre arena dorada). Los egipcios del desierto aprendieron a reconocerlos y los recogían sistemáticamente.",
  "La hoja de la daga muestra señales de haber sido forjada con técnicas avanzadas. El hierro meteorítico es más difícil de trabajar que el bronce porque requiere temperaturas más altas y técnicas de martillado más precisas. Sin embargo, los artesanos egipcios lograron crear una hoja fina, bien equilibrada y con un filo funcional. Los análisis microscópicos muestran que fue trabajada a baja temperatura para evitar el agrietamiento, una técnica conocida como 'forjado en frío'.",
  "La empuñadura de la daga es tan espectacular como su hoja meteórica. Está cubierta de oro con incrustaciones de granito y lapislázuli, formando patrones de flores de loto y estrellas. El lapislázuli, esa piedra azul intenso que tanto amaban los egipcios, venía de las montañas de Afganistán, a miles de kilómetros de distancia. Que una sola daga combinara metal del espacio exterior, oro de los desiertos de Nubia y piedras de las montañas de Asia Central demuestra el alcance del comercio en el mundo antiguo.",
  "Tutankamón tenía apenas 19 años cuando murió, hacia el 1323 a.C. Gobernó durante unos 10 años, desde los 9. No fue un faraón particularmente poderoso; su importancia histórica reside principalmente en que su tumba fue descubierta en 1922 casi intacta por Howard Carter, conservando miles de objetos que en las demás tumbas reales fueron robados por saqueadores. La daga meteórica era uno de sus objetos personales más preciados.",
  "Howard Carter tardó 10 años en catalogar y conservar los más de 5,000 objetos de la tumba de Tutankamón. La daga meteórica estaba colocada a lo largo del muslo derecho de la momia, dentro de las vendas de lino, junto a otra daga de hoja de oro. La posición de los objetos en la momia tenía significado religioso: los objetos colocados junto al cuerpo eran los más sagrados, destinados a acompañar al faraón en su viaje por el inframundo.",
  "El análisis de hierro meteorítico en la daga de Tutankamón inspiró a los investigadores a buscar más objetos de hierro espacial en las colecciones egipcias de los museos. En 2022, un estudio analizó 24 objetos de hierro del Antiguo Egipto conservados en museos europeos y encontró que la mayoría de ellos, especialmente los más antiguos, eran de origen meteorítico. El 'hierro del cielo' era el material preferido para los objetos más sagrados y suntuarios del Egipto prerromano.",
  "La daga meteórica de Tutankamón no es única en la historia. Los inuit del Ártico forjaron herramientas durante siglos usando fragmentos de un enorme meteorito de hierro llamado 'Cabo York' que cayó en Groenlandia hace unos 10,000 años. Los pueblos precolombinos de América del Norte también usaban hierro meteorítico para hacer puntas de flecha y cuchillos ceremoniales. En todas las culturas antiguas del mundo, el hierro del cielo era tratado como un material sagrado de origen divino.",
  "Los egipcios no estaban equivocados al llamar al hierro meteorítico 'metal del cielo'. Desde el punto de vista astronómico, todos los metales pesados de la Tierra, incluyendo el hierro, el níquel y el cobalto, fueron forjados en el interior de estrellas masivas que explotaron como supernovas hace miles de millones de años. Las partículas de esas explosiones se reunieron para formar el sistema solar, incluyendo la Tierra. Así que en cierto sentido, ¡todo el hierro de la Tierra es 'metal del cielo'!",
  "En el Museo Egipcio de El Cairo, la daga de Tutankamón está expuesta junto a otros tesoros del joven faraón. Atrae a miles de visitantes al año que no saben que están contemplando un objeto forjado con metal que viajó por el espacio durante millones de años antes de llegar a las manos de un artesano egipcio. La daga es literalmente un puente entre el espacio exterior y la historia humana.",
  "Los meteoritos de hierro caen a la Tierra aproximadamente a razón de 500 toneladas por año, aunque la mayoría son fragmentos pequeños. Los grandes meteoritos de hierro, de varios kilogramos o más, son raros. El meteorito de Gibeon, en Namibia (África del Sur), dispersó miles de fragmentos de hierro-níquel que los pueblos locales usaron para hacer herramientas durante siglos. El meteorito de Hoba, también en Namibia, pesa 60 toneladas y es el meteorito más grande conocido que sigue en su lugar de caída.",
  "El legado de la daga meteórica de Tutankamón es que nos recuerda que el universo y la historia humana están más conectados de lo que pensamos. El metal que viajó desde un asteroide lejano, sobrevivió el viaje por el espacio, atravesó la atmósfera en llamas y cayó en el desierto fue recogido por manos humanas, forjado con maestría y colocado junto al cuerpo de un rey. Es una historia de cosmología, arte, comercio y humanidad fundidos en una sola hoja de metal del espacio."
];

const egypt_m10_quiz = [
  { "q": "¿Qué material inusual tiene la hoja de la daga de Tutankamón?", "options": ["Bronce de Nubia", "Hierro meteorítico del espacio", "Plata de Siria", "Titanio moderno"], "a": 1 },
  { "q": "¿Cómo llamaban los egipcios al hierro en su idioma?", "options": ["Kemet", "Ba en pet (metal del cielo)", "Osiris blanco", "Hierro rojo"], "a": 1 },
  { "q": "¿Qué técnica se usó para analizar la daga en 2016?", "options": ["Carbono-14", "Rayos X de fluorescencia", "Microscopio óptico", "Análisis de ADN"], "a": 1 },
  { "q": "¿Quién descubrió la tumba de Tutankamón?", "options": ["Napoleon Bonaparte", "Howard Carter", "Zahi Hawass", "Jean Champollion"], "a": 1 },
  { "q": "¿Dónde estaba colocada la daga dentro de la tumba?", "options": ["En una caja de madera", "Junto al muslo derecho de la momia", "En el altar del dios Osiris", "Dentro de un ataúd de oro"], "a": 1 }
];

// egypt_m11 — El Nilo de Nut: La Vía Láctea
const egypt_m11_paragraphs = [
  "¡Activa los telescopios de tu nave y apunta hacia el centro de la galaxia, cadete! Cuando los antiguos egipcios miraban el cielo en una noche oscura, sin la contaminación lumínica de las ciudades modernas, veían algo que nosotros raramente podemos apreciar: la Vía Láctea en todo su esplendor. Una banda de luz blanca y difusa que cruzaba el cielo de horizonte a horizonte, como un río de estrellas tan denso que parecía una nube luminosa.",
  "Para los egipcios, este río de luz celestial tenía un nombre y una historia: era el cuerpo de la diosa Nut, la gran diosa del cielo. Nut era representada como una mujer esbelta que se arqueaba sobre la Tierra, con los dedos de los pies en un horizonte y los de las manos en el otro, formando una bóveda celeste con su cuerpo. Las estrellas eran joyas pintadas en su piel. La Vía Láctea era el reflejo celestial del río Nilo, el río sagrado que daba vida a Egipto.",
  "Esta correspondencia entre el Nilo terrenal y la Vía Láctea celestial era fundamental en la cosmología egipcia. El principio que los guiaba se puede resumir en una frase de los textos herméticos: 'Como es arriba, es abajo'. Lo que ocurría en el cielo tenía su reflejo en la Tierra, y viceversa. El Nilo inundaba Egipto con agua y vida justo cuando la Vía Láctea estaba en su posición más prominente en el cielo veraniego.",
  "Los arqueólogos han descubierto que el conjunto de monumentos de Guiza (las tres pirámides y la Esfinge) está orientado de manera que imita la relación espacial de las tres estrellas del Cinturón de Orión con la Vía Láctea. La Vía Láctea, de este a oeste en el mapa celeste, corresponde al Nilo, de sur a norte en el mapa terrestre. Las pirámides están 'a orillas' del Nilo terrestre igual que las estrellas de Orión están 'a orillas' de la Vía Láctea celestial.",
  "La Vía Láctea que vemos en el cielo es el plano de nuestra galaxia, donde se concentra la mayor densidad de estrellas. Nuestro Sol está ubicado a unos 26,000 años luz del centro galáctico, en un brazo espiral llamado Brazo de Orión. Cuando miramos la Vía Láctea en el cielo nocturno, estamos mirando hacia el interior del disco galáctico, viendo millones de estrellas superpuestas. Los egipcios no sabían esto, pero vieron el patrón y le dieron sentido con su mitología.",
  "En los textos de las pirámides, los más antiguos textos religiosos del mundo (fechados hacia el 2400 a.C.), se describe el viaje del alma del faraón muerto hacia las estrellas circumpolares o hacia la constelación de Orión. El faraón era identificado con Osiris, dios de la muerte y resurrección, representado por Orión. La reina era Isis, identificada con Sirio. El alma real viajaba por el 'campo de las cañas', que era la Vía Láctea, para reunirse con los dioses.",
  "El centro de la Vía Láctea, visible como la parte más brillante y densa de la banda de luz en la constelación de Sagitario, es donde se encuentra Sagitario A*, un agujero negro supermasivo de 4 millones de masas solares. Si los egipcios hubieran sabido esto, probablemente habrían imaginado a Apofis, el gran dragón del caos, devorando eternamente la luz en el corazón del cielo. La astronomía moderna y la mitología egipcia comparten una apreciación por los extremos dramáticos del cosmos.",
  "Uno de los aspectos más interesantes de la relación entre los egipcios y la Vía Láctea es el calendario. La posición de la Vía Láctea en el cielo cambia a lo largo del año. En el verano egipcio (julio-agosto), cuando el Nilo se inundaba, la Vía Láctea era visible directamente sobre el cielo nocturno. Los sacerdotes usaban la posición de la Vía Láctea como señal adicional para confirmar que la época de inundación había llegado, coordinando múltiples señales astronómicas para sus predicciones.",
  "Las pinturas en los sarcófagos y las tumbas representan frecuentemente a Nut como una figura que rodea completamente al difunto, protegiéndolo en su viaje por el más allá. El techo pintado con estrellas de las cámaras funerarias representaba la barriga de Nut: el difunto estaba literalmente dentro del vientre de la diosa del cielo, esperando renacer como una nueva estrella. Esta es una metáfora astronómica de extraordinaria belleza poética.",
  "La observación de la Vía Láctea requería cielos oscuros, y los egipcios del desierto los tenían. En el desierto del Sahara, lejos de las ciudades, el cielo nocturno es tan oscuro que la Vía Láctea proyecta una sombra tenue sobre el suelo. Los astrónomos modernos que instalan telescopios en desiertos remotos están reproduciendo exactamente las condiciones en que los sacerdotes egipcios hacían sus observaciones: máxima oscuridad y máxima claridad atmosférica.",
  "La Vía Láctea también servía como guía de navegación para los marinos egipcios que surcaban el Mediterráneo. La banda de luz era visible claramente en el horizonte y ayudaba a los navegantes a mantener el rumbo durante la noche. Combinada con la posición de la estrella polar y las constelaciones conocidas, la Vía Láctea era parte del 'GPS astronómico' que permitía a los comerciantes egipcios navegar desde Egipto hasta Creta, Fenicia y más allá.",
  "El nombre 'Vía Láctea' (Milky Way en inglés, Galaxias kyklos en griego, que significa 'círculo de leche') viene de la mitología griega. Zeus colocó al bebé Heracles sobre el pecho de la diosa Hera mientras dormía para que la leche divina lo volviera inmortal. Hera se despertó, rechazó al niño, y el chorro de leche que brotó de su pecho se convirtió en la Vía Láctea. La palabra griega 'galaxias' (leche) nos dio la palabra moderna 'galaxia'. Los egipcios la llamaban simplemente 'el Nilo del cielo'.",
  "Nuestra Vía Láctea tiene entre 100,000 y 200,000 años luz de diámetro y contiene entre 100,000 millones y 400,000 millones de estrellas. Es una galaxia espiral barrada, con un núcleo central y brazos espirales que se extienden hacia afuera. A lo largo de estos brazos se forman nuevas estrellas y planetas. El sistema solar completa una órbita alrededor del centro galáctico cada 225 millones de años (un 'año galáctico'). Los dinosaurios vivieron hace un año galáctico.",
  "La gran pregunta que los egipcios nunca pudieron responder, pero que la astronomía moderna sí ha respondido, es: ¿qué hay del otro lado de la Vía Láctea? Más allá de nuestra galaxia hay miles de millones de otras galaxias, agrupadas en cúmulos y supercúmulos que forman la estructura de la gran tela cósmica. La galaxia más cercana a la Vía Láctea es Andrómeda, a 2.5 millones de años luz. Y más allá, el universo observable se extiende por 46,000 millones de años luz en todas las direcciones.",
  "El legado de Nut, la diosa del cielo que era la Vía Láctea, es que nos enseña que los humanos siempre hemos necesitado dar sentido al cosmos que nos rodea. Los egipcios convirtieron la banda de luz en una diosa amorosa que protegía a los muertos y conectaba el cielo con la Tierra. Los astrónomos modernos la convierten en ecuaciones y telescopios. Pero el impulso original es el mismo: mirar hacia arriba, asombrarse, y preguntar: ¿qué es todo esto y cuál es nuestro lugar en ello?"
];

const egypt_m11_quiz = [
  { "q": "¿Cómo llamaban los egipcios a la Vía Láctea?", "options": ["El camino de Osiris", "El Nilo del cielo o el cuerpo de Nut", "La serpiente de Ra", "El cinturón de Orión"], "a": 1 },
  { "q": "¿Quién era Nut en la mitología egipcia?", "options": ["La diosa del Nilo", "La gran diosa del cielo", "La diosa de la guerra", "La diosa de la luna"], "a": 1 },
  { "q": "¿Qué hay en el centro de nuestra Vía Láctea?", "options": ["Una estrella gigante", "Un agujero negro supermasivo (Sagitario A*)", "Un planeta de diamante", "El paraíso de los dioses"], "a": 1 },
  { "q": "¿Cuánto tarda el Sol en dar una vuelta alrededor del centro de la galaxia?", "options": ["1,000 años", "1 millón de años", "225 millones de años", "1 segundo"], "a": 2 },
  { "q": "¿Cuál es la galaxia más cercana a la Vía Láctea?", "options": ["La galaxia del Triángulo", "Andrómeda", "La Nube de Magallanes", "La galaxia del Cigarro"], "a": 1 }
];

// egypt_m12 — Obeliscos: Relojes del Sol
const egypt_m12_paragraphs = [
  "¡Calibra tus instrumentos de medición solar, cadete! Hoy vamos a aprender sobre uno de los inventos más elegantes de la historia: el obelisco egipcio. Esta aguja de piedra puntiaguda que los egipcios construyeron a lo largo de miles de años es mucho más que una decoración impresionante. Era una máquina de precisión científica: un reloj solar, un calendario, un instrumento de navegación y un símbolo del poder del sol, todo en uno.",
  "Los obeliscos egipcios son monolitos (bloques de piedra de una sola pieza) de granito rosado, tallados en las canteras de Asuán y transportados cientos de kilómetros por el Nilo hasta sus destinos finales en Karnak, Luxor, Heliópolis y otras ciudades. Los más grandes miden hasta 30 metros de altura y pesan más de 300 toneladas. Cada uno fue tallado con un solo cincel de cobre, en granito que es uno de los materiales más duros de la naturaleza.",
  "La función principal del obelisco era medir el tiempo usando la sombra que su punta proyectaba sobre el suelo. Cuando el Sol sale por el este, la sombra del obelisco apunta hacia el oeste y es muy larga. A medida que el Sol sube en el cielo, la sombra se hace más corta y gira. Al mediodía solar exacto, la sombra apunta hacia el Norte verdadero y es la más corta del día. Por la tarde, la sombra se alarga hacia el este. Este movimiento de la sombra era el 'minutero' del reloj solar.",
  "Los sacerdotes marcaban en el suelo alrededor del obelisco las posiciones de la sombra a diferentes horas del día, creando una escala de tiempo que cualquier persona podía leer. También marcaban las posiciones de la sombra en los días especiales del año: solsticio de verano (sombra más corta del año), solsticio de invierno (sombra más larga del año) y equinoccios (la sombra del mediodía tiene la misma longitud en primavera y otoño). El obelisco era así un calendario perpetuo grabado en piedra.",
  "La punta del obelisco, llamada 'piramidión', era recubierta con una aleación de oro y plata llamada 'electrum'. Cuando el Sol naciente iluminaba primero la punta brillante del obelisco, antes de que sus rayos llegaran al suelo, la punta resplandecía como una pequeña estrella en la oscuridad del amanecer. Los egipcios interpretaban esto como el primer contacto del dios Ra (el Sol) con la Tierra cada mañana: la punta del obelisco era el punto de contacto entre el cielo y la Tierra.",
  "Los obeliscos fueron adoptados con entusiasmo por los emperadores romanos como símbolos de poder. Cuando Augusto conquistó Egipto en el 30 a.C., se llevó varios obeliscos a Roma. Hoy, Roma tiene más obeliscos egipcios originales que cualquier otra ciudad del mundo, incluyendo Egipto. El obelisco más famoso de Roma está en el centro de la Plaza de San Pedro, en el Vaticano, y fue traído desde Heliópolis por el emperador Calígula en el año 37 d.C.",
  "Los egipcios también usaban gnómons: varillas verticales simples que funcionaban como versiones portátiles del obelisco. A diferencia del obelisco que era monumental e inamovible, el gnómon era una herramienta que los astrónomos podían llevar consigo. Medían la longitud de la sombra del gnómon al mediodía en diferentes lugares de Egipto, lo que les permitía calcular la latitud geográfica de cada lugar. Eratóstenes usó este principio para calcular la circunferencia de la Tierra con notable precisión.",
  "El astrónomo griego Eratóstenes de Cirene (276-194 a.C.), director de la Biblioteca de Alejandría, calculó la circunferencia de la Tierra usando el principio del gnómon. Midió el ángulo de la sombra al mediodía del solsticio en Alejandría (7.2 grados) y sabía que en Siena (la actual Asuán) no había sombra ese mismo momento (el Sol estaba directamente sobre la cabeza). La diferencia angular dividida entre 360 grados y multiplicada por la distancia entre las dos ciudades le dio la circunferencia total de la Tierra: 40,074 km. El valor real es 40,075 km. ¡Un error del 0.002%!",
  "El obelisco de la Plaza del Popolo en Roma es el segundo más alto del mundo fuera de Egipto, con 24 metros. Fue traído desde el templo de Ramsés II en Heliópolis y erigido en el Circo Máximo por el emperador Augusto. En su base, el papa Sixto V ordenó instalar marcas en el suelo para convertirlo en un reloj solar monumental en el siglo XVI. Así, un instrumento astronómico egipcio de 3,000 años fue reutilizado por el Renacimiento europeo, uniendo a través del tiempo dos grandes civilizaciones.",
  "Hoy se conservan unos 25 obeliscos egipcios en pie en todo el mundo. Además de Roma (13 obeliscos), hay obeliscos en París (el Obelisco de Luxor en la Plaza de la Concordia), en Londres (la Aguja de Cleopatra en el Embankment del Támesis), en Nueva York (otra Aguja de Cleopatra en Central Park), en Estambul y en Etiopía. Ninguno de los grandes obeliscos originales queda en pie en su ubicación original en Egipto.",
  "La Aguja de Cleopatra en Nueva York fue un regalo del gobierno egipcio a los Estados Unidos en 1879 para celebrar la inauguración del Canal de Suez. Tiene 3,500 años de antigüedad y fue originalmente erigida en Heliópolis por el faraón Tutmosis III. En su base se colocaron varios 'tesoros modernos' en una cápsula del tiempo: monedas de la época, un Censo de los Estados Unidos, ejemplares del periódico New York Tribune y una foto de Ulysses Grant. Es un obelisco que une el 1450 a.C. con el 1879 d.C.",
  "El material de los obeliscos, el granito rosado de Asuán, es extraordinariamente resistente. La roca de granito tiene una dureza de 7 en la escala de Mohs (donde el diamante es 10). Sin embargo, los artesanos egipcios la tallaban usando únicamente herramientas de dolerita (una piedra aún más dura) y raspadores de cuarzo. El proceso de tallar un obelisco grande tardaba varios años. La cantera de Asuán todavía conserva un obelisco inacabado (el 'Obelisco Inacabado') que muestra exactamente cómo se hacía el proceso de extracción.",
  "El obelisco más alto del mundo está en Roma: el Obelisco de Letrán, con 45.7 metros de altura. Fue mandado construir por el faraón Tutmosis III y terminado por su sucesor Tutmosis IV alrededor del 1400 a.C. Tardó más de un siglo en construirse. Fue trasladado a Roma en el año 357 d.C. por el emperador Constancio II. Cayó durante las invasiones bárbaras y fue redescubierto en tres fragmentos en el siglo XVI. El papa Sixto V lo restauró y lo colocó en la Piazza di San Giovanni in Laterano en 1588.",
  "La sombra del obelisco como herramienta de medición inspiró el desarrollo de los relojes solares portátiles, los cuadrantes solares medievales y, eventualmente, los relojes mecánicos. La necesidad de saber la hora (para coordinar rituales religiosos, para determinar cuándo plantar, para regular el trabajo en los templos) fue el motor que impulsó el desarrollo de la ciencia del tiempo a lo largo de miles de años. El obelisco fue el primer eslabón de esa cadena que llevó a los relojes atómicos modernos.",
  "La próxima vez que veas una imagen de un obelisco, recuerda que estás mirando uno de los instrumentos científicos más duraderos de la historia. Diseñado hace 4,000 años para medir el tiempo y el espacio usando la sombra del Sol, el obelisco sigue en pie en plazas de todo el mundo, uniendo a nuestra generación con los astrónomos-sacerdotes que lo concibieron bajo el intenso sol del Sahara. La ciencia de medir el cielo comenzó en Egipto, y sus monumentos siguen apuntando hacia las estrellas."
];

const egypt_m12_quiz = [
  { "q": "¿Qué función científica tenía el obelisco?", "options": ["Era un reloj solar y un calendario", "Solo era decorativo", "Servía para escalar al cielo", "Era una antena de comunicaciones"], "a": 0 },
  { "q": "¿Cómo se llamaba la punta del obelisco?", "options": ["Piramidión", "Merkhet", "Bay", "Kemet"], "a": 0 },
  { "q": "¿Quién usó el principio del gnómon para calcular la circunferencia de la Tierra?", "options": ["Pitágoras", "Eratóstenes", "Ptolomeo", "Aristóteles"], "a": 1 },
  { "q": "¿En qué ciudad hay más obeliscos egipcios en el mundo?", "options": ["El Cairo", "Londres", "Roma", "París"], "a": 2 },
  { "q": "¿De qué material están hechos los obeliscos egipcios?", "options": ["Mármol blanco", "Granito rosado de Asuán", "Caliza de Tura", "Basalto negro"], "a": 1 }
];

src = replaceSection(src, 'egypt_m8', egypt_m8_paragraphs, egypt_m8_quiz);
src = replaceSection(src, 'egypt_m9', egypt_m9_paragraphs, egypt_m9_quiz);
src = replaceSection(src, 'egypt_m10', egypt_m10_paragraphs, egypt_m10_quiz);
src = replaceSection(src, 'egypt_m11', egypt_m11_paragraphs, egypt_m11_quiz);
src = replaceSection(src, 'egypt_m12', egypt_m12_paragraphs, egypt_m12_quiz);

fs.writeFileSync(FILE, src, 'utf8');
console.log('Done writing file.');
