const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

function replaceSection(src, moduleId, newParagraphs) {
  const moduleStart = src.indexOf(`"id": "${moduleId}"`);
  if (moduleStart === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  const sectionsStart = src.indexOf('"sections"', moduleStart);
  const textStart = src.indexOf('"text"', sectionsStart);
  const arrStart = src.indexOf('[', textStart);
  let depth = 0, i = arrStart;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  const arrEnd = i;
  src = src.slice(0, arrStart) + JSON.stringify(newParagraphs, null, 14) + src.slice(arrEnd + 1);
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// faraday_m1 — El Autodidacta del Electromagnetismo
src = replaceSection(src, 'faraday_m1', [
  "¡Bienvenido al laboratorio más emocionante del siglo XIX, cadete! Hoy vamos a conocer a Michael Faraday, uno de los científicos más extraordinarios de la historia, no solo por sus descubrimientos sino por su historia personal. Faraday nació en 1791 en el sur de Londres, en una familia muy pobre. Su padre era herrero y apenas podía alimentar a sus cuatro hijos. Michael tuvo que dejar la escuela a los 13 años para trabajar como repartidor de periódicos y, luego, como aprendiz en una encuadernadora de libros.",
  "El trabajo en la encuadernadora resultó ser una bendición disfrazada. Faraday tenía acceso ilimitado a libros, y los leyó con voracidad. Se enamoró de la ciencia después de leer la 'Enciclopedia Británica' y los libros de química de Jane Marcet. Comenzó a hacer experimentos en casa con materiales baratos. A los 20 años, asistió a cuatro conferencias del famoso químico Humphry Davy en la Royal Institution de Londres. Tomó notas detalladas, encuadernó el cuaderno con cuidado y se lo envió a Davy como muestra de su trabajo.",
  "Davy quedó tan impresionado con las notas que contrató a Faraday como asistente de laboratorio en 1813. Fue el comienzo de una de las carreras científicas más brillantes de la historia. Faraday comenzó haciendo trabajos menores: lavar el vidrio, preparar reactivos químicos, limpiar el laboratorio. Pero observaba, aprendía y preguntaba. En pocos años, sus contribuciones eran tan importantes que comenzó a eclipsar al propio Davy. La historia del científico autodidacta que supera a su maestro.",
  "En 1821, Faraday construyó el primer motor eléctrico de la historia. Era un aparato elegante pero simple: una barra de metal sumergida en mercurio, cerca de un imán permanente. Cuando pasaba corriente eléctrica por la barra, esta comenzaba a girar alrededor del imán. El movimiento de la barra era causado por la interacción entre el campo magnético del imán y el campo magnético creado por la corriente eléctrica. Era el nacimiento de la electromecánica.",
  "El principio del motor eléctrico que Faraday descubrió es el mismo que funciona en todos los motores eléctricos modernos: en los coches eléctricos, en los trenes de alta velocidad, en las lavadoras, en los ventiladores y en cientos de dispositivos más. Una corriente eléctrica que fluye por un conductor dentro de un campo magnético experimenta una fuerza que lo mueve. Este principio ha sido la base de la industria moderna durante 200 años.",
  "En 1831, Faraday hizo su descubrimiento más importante: la inducción electromagnética. Si el motor eléctrico convierte electricidad en movimiento, la inducción hace lo contrario: convierte movimiento en electricidad. Faraday descubrió que al mover un imán cerca de una bobina de alambre, se generaba una corriente eléctrica en la bobina. O equivalentemente, al cambiar el campo magnético a través de una bobina, aparecía una fuerza eléctrica (voltaje) en la bobina.",
  "La inducción electromagnética es el principio detrás de todos los generadores eléctricos del mundo: las centrales hidroeléctricas, las centrales nucleares, las turbinas de viento, los alternadores de los coches. En todos estos casos, un imán o electroimán gira dentro de una bobina (o una bobina gira dentro de un campo magnético), y ese movimiento relativo genera electricidad. Toda la electricidad que usamos en el mundo moderno se produce gracias al principio que Faraday descubrió en 1831.",
  "Faraday también inventó el transformador: un dispositivo que puede aumentar o disminuir el voltaje de una corriente alterna. El transformador usa la inducción mutua: la corriente alterna en una bobina primaria crea un campo magnético cambiante que induce una corriente en una bobina secundaria. La relación de voltajes es proporcional a la relación de vueltas de las dos bobinas. Los transformadores son esenciales para transmitir electricidad a grandes distancias sin perder demasiada energía.",
  "La contribución de Faraday a la química también fue enorme. Descubrió que el cloro podía licuarse bajo presión, estableciendo los principios básicos de la refrigeración que llevarían al desarrollo de frigoríficos y aire acondicionado. También descubrió el benceno (C6H6), la molécula orgánica más importante de la química industrial, base de los plásticos, tintes, medicamentos y explosivos. Y formuló las Leyes de la Electrólisis que llevan su nombre.",
  "Las Leyes de la Electrólisis de Faraday establecen cuánta sustancia se deposita en los electrodos cuando pasa una corriente eléctrica por una solución. La primera ley dice que la masa depositada es proporcional a la carga eléctrica total que pasa. La segunda ley dice que la masa depositada también depende del 'equivalente electroquímico' del elemento (relacionado con su masa atómica). Estas leyes vincularon por primera vez la electricidad con la estructura atómica de la materia.",
  "Faraday introdujo el concepto de 'líneas de fuerza' para visualizar los campos eléctricos y magnéticos. Imaginó que el espacio alrededor de un imán o una carga eléctrica estaba lleno de líneas invisibles que mostraban la dirección y la intensidad de la fuerza. Aunque parecía solo una herramienta pictórica, este concepto fue revolucionario. James Clerk Maxwell tomó la idea de Faraday y la formuló matemáticamente para crear las ecuaciones de Maxwell, la teoría completa del electromagnetismo.",
  "La Royal Institution de Londres, donde Faraday trabajó durante toda su vida, instituyó las 'Conferencias de Navidad' para niños en 1825, una tradición que Faraday convirtió en celebres eventos de divulgación científica. Faraday era un comunicador extraordinario, capaz de explicar conceptos complejos con experimentos visuales y lenguaje sencillo. Las Conferencias de Navidad de la Royal Institution continúan hasta hoy, y la serie de conferencias de Faraday sobre 'La Historia Química de una Vela' de 1860 es considerada la primera gran obra de divulgación científica.",
  "Faraday sufrió durante años de problemas de memoria y síntomas que hoy asociaríamos con intoxicación por metales pesados, probablemente causada por su trabajo con mercurio y otros productos químicos sin protección adecuada. Estos problemas de salud le obligaron a reducir su trabajo científico en sus últimos años. Sin embargo, continuó visitando su laboratorio y reflexionando sobre sus teorías hasta poco antes de su muerte en 1867. La imagen del científico que sacrifica su salud por la ciencia es un cliché, pero en el caso de Faraday era literalmente cierto.",
  "Einstein admiraba tanto a Faraday que tenía su retrato en la pared de su oficina, junto a los de Newton y Maxwell. Einstein reconoció que el concepto de 'campo' que Faraday introdujo fue el precursor directo de la idea de que la gravedad no es una fuerza que actúa a distancia sino una curvatura del espacio-tiempo. Sin el 'campo electromagnético' de Faraday-Maxwell, es difícil imaginar cómo Einstein habría llegado a su concepto de 'campo gravitacional' en la Relatividad General.",
  "El legado de Michael Faraday es el más democrático de todos los grandes científicos: literalmente ilumina nuestras vidas. La electricidad que da luz a nuestras casas, carga nuestros teléfonos, mueve nuestros coches eléctricos y alimenta los centros de datos de internet es producida y distribuida gracias a los principios de inducción y transformación que él descubrió. El niño pobre del sur de Londres que aprendió ciencia leyendo libros prestados cambió el mundo de maneras que ningún rey o millonario de su época podría haber imaginado."
]);

// faraday_m2 — La Jaula de Faraday y el Escudo Eléctrico
src = replaceSection(src, 'faraday_m2', [
  "¡Activa los escudos electromagnéticos, cadete! Hoy vamos a aprender sobre uno de los inventos más útiles de Faraday: la jaula de Faraday. En 1836, Faraday notó algo curioso mientras hacía experimentos con electricidad estática: si colocaba objetos dentro de un conductor hueco (una caja de metal), los objetos quedaban completamente protegidos de los campos eléctricos exteriores. La superficie conductora 'absorbía' y redistribuía las cargas eléctricas de manera que el interior quedaba en un campo eléctrico nulo.",
  "Para demostrar este efecto de forma espectacular, Faraday construyó una habitación completa recubierta de papel de estaño, una 'jaula de Faraday' a escala humana. Luego entró en la habitación y permitió que se le aplicaran descargas eléctricas masivas desde el exterior. Las chispas eléctricas saltaban visiblemente por las paredes metálicas, pero Faraday, dentro, no sentía nada. El interior de la jaula estaba perfectamente protegido. Fue una de las demostraciones científicas más dramáticas del siglo XIX.",
  "El principio físico detrás de la jaula de Faraday es la redistribución de cargas en un conductor. Cuando se aplica un campo eléctrico exterior a una superficie conductora, las cargas libres del metal (los electrones) se redistribuyen inmediatamente para cancelar exactamente el campo en el interior. Las cargas van a la superficie exterior, dejando el interior sin campo eléctrico. Este proceso ocurre en una fracción de nanosegundo, más rápido de lo que podemos medir directamente.",
  "La jaula de Faraday está presente en decenas de aplicaciones cotidianas que usamos sin saberlo. El microondas de tu cocina es una jaula de Faraday: la malla metálica en su puerta de vidrio impide que las microondas salgan al exterior (protegiéndote) pero deja pasar la luz visible (para que puedas ver la comida). Los cables coaxiales de las antenas de televisión son cables rodeados de una malla metálica que funciona como jaula de Faraday, protegiendo la señal interior de las interferencias eléctricas exteriores.",
  "Los vehículos metálicos son jaulas de Faraday imperfectas. Si te quedas dentro de tu coche durante una tormenta de rayos, el metal de la carrocería distribuye la energía del rayo alrededor del exterior del vehículo, protegiendo el interior. Por eso se recomienda permanecer dentro del coche durante una tormenta eléctrica severa. Los aviones están especialmente diseñados como jaulas de Faraday: pueden ser alcanzados por rayos (lo que ocurre varias veces al año para un avión comercial típico) sin que los pasajeros se enteren.",
  "Las tarjetas de crédito y débito con chip RFID (comunicación por radiofrecuencia) pueden ser leídas por aparatos especiales sin que el titular lo sepa, un tipo de robo llamado 'skimming'. Las fundas de seguridad para tarjetas que se venden para evitar este robo son pequeñas jaulas de Faraday: la funda metálica bloquea las señales de radiofrecuencia que usaría el ladrón para leer tu tarjeta. La tecnología de Faraday de 1836 protege tu dinero en el siglo XXI.",
  "Los hospitales y centros de resonancia magnética (MRI) usan cuartos apantallados que son jaulas de Faraday a gran escala. Las máquinas de MRI usan campos magnéticos y ondas de radio extremadamente potentes. Si estas ondas se escaparan al exterior, interferirían con los equipos electrónicos del hospital y los teléfonos móviles. Las paredes metálicas del cuarto de MRI contienen todas las radiaciones electromagnéticas en el interior. Faraday habría quedado fascinado.",
  "Los edificios modernos actúan frecuentemente como jaulas de Faraday parciales. El acero de la estructura, la malla metálica de las paredes y los conductos de ventilación metálicos crean una red conductora que atenúa las señales de radio y telefonía móvil en el interior. Esto explica por qué a veces hay mala señal de teléfono dentro de edificios con estructura metálica. Los diseñadores de edificios modernos deben considerar este efecto e instalar repetidores de señal en el interior.",
  "En el mundo militar, las jaulas de Faraday se usan para proteger los equipos electrónicos de los pulsos electromagnéticos (EMP). Un EMP es un estallido de radiación electromagnética extremadamente intensa producida por una explosión nuclear a gran altitud. Un solo EMP de suficiente intensidad puede destruir todos los equipos electrónicos no protegidos en un área de miles de kilómetros. Los equipos militares críticos se guardan en contenedores especiales de jaula de Faraday para protegerlos de este tipo de ataque.",
  "Los laboratorios de medición eléctrica de alta precisión usan salas de apantallamiento electromagnético (cámaras anecoicas electromagnéticas) que son versiones avanzadas de la jaula de Faraday. Estas salas eliminan completamente las señales electromagnéticas externas (WiFi, telefonía móvil, señales de radio) para que las mediciones internas no estén contaminadas por ruido eléctrico. Son especialmente importantes para probar antenas, dispositivos de comunicación y equipos médicos.",
  "La jaula de Faraday también tiene aplicaciones en la música. Las guitarras eléctricas y los bajos están protegidos de las interferencias electromagnéticas (el 'zumbido' de 50-60 Hz causado por la red eléctrica) apantallando las cavidades internas de la guitarra con láminas de cobre o aluminio. Las salas de grabación profesionales están construidas como jaulas de Faraday para eliminar cualquier ruido eléctrico del entorno. El sonido limpio de una grabación profesional es posible gracias a Faraday.",
  "El principio de la jaula de Faraday puede extenderse a los campos magnéticos, aunque con diferencias importantes. Los campos eléctricos son perfectamente apantallados por cualquier conductor. Los campos magnéticos, en cambio, requieren materiales ferromagnéticos de alta permeabilidad magnética (como la aleación mu-metal) para ser apantallados efectivamente. Estos materiales 'atraen' las líneas de campo magnético hacia sí mismos, desviándolas alrededor del espacio protegido en lugar de dentro.",
  "La física moderna ha extendido el concepto de la jaula de Faraday al nivel cuántico. Las técnicas de 'electrónica de un solo electrón' usan estructuras metálicas nanométricas para controlar el movimiento de electrones individuales. En estas nanoestructuras, el apantallamiento electrostático a nivel de decenas de nanómetros permite crear 'puntos cuánticos' donde los electrones están completamente aislados de su entorno y pueden ser manipulados individualmente. Es la jaula de Faraday en escala nanométrica.",
  "Las redes de datos bancarias y los centros de datos críticos están alojados en instalaciones que incluyen protección tipo jaula de Faraday contra ataques EMP o interferencias electromagnéticas. La seguridad de la información bancaria global depende en parte de que los servidores estén protegidos por las mismas leyes físicas que Faraday descubrió experimentando con papel de estaño en su laboratorio de Londres hace casi 200 años.",
  "El gran legado de la jaula de Faraday es que nos muestra cómo los principios fundamentales de la física tienen aplicaciones que se multiplican exponencialmente con el tiempo. Faraday no inventó la jaula para proteger tarjetas de crédito, mejorar grabaciones musicales ni blindar aviones militares: simplemente estaba estudiando cómo se distribuyen las cargas eléctricas en los conductores. Siglo y medio después, sus observaciones protegen billones de dólares en transacciones financieras y mantienen seguros a miles de pasajeros de aeronaves. La ciencia básica siempre encuentra aplicaciones que nadie podía predecir."
]);

// faraday_m3 — El Campo Magnético y Sus Maravillas
src = replaceSection(src, 'faraday_m3', [
  "¡Activa los detectores de campos magnéticos, cadete explorador! El campo magnético de la Tierra nos rodea, nos protege y hace posible la vida en nuestro planeta, aunque no podamos verlo ni sentirlo directamente. Michael Faraday fue el primero en desarrollar el concepto de 'campo' como una realidad física que llena el espacio, no solo como una descripción matemática conveniente. Esta idea transformó completamente la física y tuvo consecuencias que Faraday mismo no pudo prever.",
  "Antes de Faraday, la visión dominante de las fuerzas físicas era la 'acción a distancia': dos imanes o dos cargas eléctricas se atraen o repelen a través del espacio vacío, sin ningún mecanismo intermedio. Newton había descrito la gravedad de esta manera: la Tierra atrae a la Luna a través del espacio sin ningún contacto. Faraday no estaba satisfecho con esta explicación. Para él, el espacio entre los imanes no estaba vacío: estaba lleno de 'líneas de fuerza' que transmitían la interacción.",
  "Las líneas de fuerza magnéticas pueden visualizarse fácilmente con limaduras de hierro. Si colocas un imán debajo de una hoja de papel y esparces limaduras de hierro sobre el papel, las limaduras se alinean a lo largo de las líneas del campo magnético, revelando su estructura. Las líneas salen del polo Norte del imán, curvan por el espacio y vuelven a entrar por el polo Sur, formando bucles cerrados. Este patrón hermoso fue el que Faraday llamó 'líneas de fuerza' y que matemáticamente corresponde a lo que ahora llamamos 'campo magnético'.",
  "El campo magnético de la Tierra, llamado magnetosfera, es generado por las corrientes de hierro fundido que circulan en el núcleo externo líquido de nuestro planeta. Estas corrientes, impulsadas por la rotación terrestre y el calor interno, actúan como un dinamo gigante que produce un campo magnético que se extiende decenas de miles de kilómetros hacia el espacio. El polo magnético norte de la Tierra no está exactamente en el polo geográfico norte: está en el norte de Canadá y se mueve varios kilómetros al año.",
  "La magnetosfera terrestre protege la vida en la Tierra del viento solar: un flujo constante de partículas cargadas (principalmente protones y electrones) emitidas por el Sol a velocidades de 400-800 km/s. Sin la magnetosfera, el viento solar erosionaría la atmósfera terrestre y bombardearía la superficie con radiación que haría imposible la vida multicelular. Marte perdió su magnetosfera hace 4,000 millones de años y por eso su atmósfera fue arrancada por el viento solar hasta quedar extremadamente delgada.",
  "Las auroras boreales y australes son el espectáculo visual más hermoso del campo magnético en acción. Cuando el viento solar es especialmente intenso (durante tormentas solares), algunas partículas cargadas logran colarse por las líneas del campo magnético cerca de los polos y penetrar la atmósfera. Al colisionar con los átomos de nitrógeno y oxígeno de la alta atmósfera (a 100-300 km de altitud), los excitan y estos liberan luz al volver a su estado de energía normal. El verde es del oxígeno a 100-150 km; el rojo, del oxígeno a más altura; el azul-violeta, del nitrógeno.",
  "Las brújulas funcionan porque una aguja magnetizada libre de girar se alinea con el campo magnético terrestre, apuntando hacia el polo magnético norte. Esta propiedad fue conocida en China desde el siglo II d.C. y llegó a Europa alrededor del siglo XII, revolucionando la navegación marítima. Sin la brújula, no habría habido las exploraciones del siglo XV (Colón, Vasco da Gama) que conectaron los continentes. El campo magnético terrestre, estudiado por Faraday, es la base de 1,000 años de navegación.",
  "Los pájaros migratorios, las tortugas marinas, los salmones y muchos otros animales tienen un 'sentido magnético' que les permite detectar el campo magnético de la Tierra y usarlo para navegar. El mecanismo exacto varía entre especies: algunos tienen cristales de magnetita en el cerebro o el pico que actúan como una brújula biológica; otros parecen usar reacciones químicas en la retina sensibles al campo magnético. Este 'GPS biológico' permite a las aves volar miles de kilómetros hacia sus destinos migratorios sin necesidad de mapa ni satélite.",
  "Los electroimanes, inventados por Faraday como herramienta de laboratorio, son hoy esenciales en miles de aplicaciones. Los imanes superconductores de las máquinas de resonancia magnética (MRI) generan campos de 1.5 a 7 Teslas (comparado con 0.00005 Teslas del campo terrestre, es decir, hasta 140,000 veces más intenso). Estos campos son lo suficientemente potentes para alinear los átomos de hidrógeno del cuerpo humano, permitiendo obtener imágenes de órganos internos con una resolución que ninguna técnica de rayos X puede igualar.",
  "El magnetismo y la electricidad, que parecían fenómenos distintos, fueron unificados por Faraday y Maxwell en el electromagnetismo. Faraday mostró experimentalmente que el magnetismo puede generar electricidad (inducción) y que la electricidad puede generar magnetismo (electroimanes). Maxwell formuló matemáticamente esta unificación en cuatro ecuaciones (las Ecuaciones de Maxwell, 1865) que mostraron que la luz es una onda electromagnética. Esta fue la primera gran unificación de fuerzas de la física, seguida por la unificación de fuerzas nucleares en el siglo XX.",
  "Los trenes de levitación magnética (maglev) usan campos magnéticos para elevar el tren sobre los raíles, eliminando la fricción mecánica. El tren más rápido del mundo, el Maglev de Chuo en Japón, ha alcanzado velocidades de prueba de 603 km/h. Utiliza superconductores de alta temperatura que, enfriados con nitrógeno líquido, generan campos magnéticos sin resistencia eléctrica. La levitación del tren funciona por repulsión entre los imanes del tren y las corrientes inducidas en los raíles conductores, exactamente como Faraday habría predicho.",
  "Los discos duros de las computadoras almacenan información usando el magnetismo: millones de pequeños dominios magnéticos en el disco pueden orientarse en dos sentidos (representando el '0' y el '1' del código binario). La cabeza lectora/escritora del disco duro detecta y cambia la orientación de estos dominios usando campos magnéticos precisos. Un disco duro moderno puede almacenar terabytes de información en un espacio del tamaño de un libro, con densidades de almacenamiento que habrían parecido milagrosas a Faraday.",
  "Las tormentas solares extremas pueden interrumpir el campo magnético terrestre lo suficiente para afectar las redes eléctricas. En 1989, una tormenta geomagnética dejó sin electricidad a la provincia de Quebec, Canadá, durante 9 horas, afectando a 6 millones de personas. Las corrientes inducidas en los cables de alta tensión por las variaciones del campo magnético terrestre sobrecargaron los transformadores. El mismo tipo de tormenta que produce auroras espectaculares puede apagar las redes eléctricas de ciudades enteras.",
  "La imagen por resonancia magnética nuclear (RMN), la base de la tecnología MRI, fue desarrollada en la segunda mitad del siglo XX pero usa principios descubiertos por Faraday. Los átomos de hidrógeno del cuerpo humano actúan como pequeños imanes que se alinean con el campo magnético externo. Un pulso de ondas de radio hace que los átomos oscilen, y cuando se relajan, emiten señales de radio que los detectores recogen. Cada tipo de tejido tiene tiempos de relajación diferentes, creando el contraste que forma la imagen.",
  "El gran legado de Faraday y su concepto de campo magnético es que hoy entendemos que la Tierra no es un planeta aislado en el vacío sino un objeto inmerso en una telaraña de campos de fuerza. El campo magnético terrestre interacciona con el viento solar, que viene del Sol, que a su vez está inmerso en el campo magnético de la galaxia. La Tierra tiene una 'piel magnética' que la conecta con el Sol y el cosmos. Faraday fue el primero en intuir que estas fuerzas invisibles eran tan reales como los objetos sólidos que podemos tocar."
]);

// faraday_m4 — Electrólisis y Química Eléctrica
src = replaceSection(src, 'faraday_m4', [
  "¡Laboratorio de alquimia moderna, cadete químico! Cuando Faraday comenzó sus experimentos con la electrólisis en la década de 1830, estaba haciendo algo que los alquimistas medievales habían soñado durante siglos: usar una fuerza de la naturaleza para transformar unos materiales en otros. La electrólisis es el proceso de usar corriente eléctrica para descomponer compuestos químicos o depositar metales, y sus aplicaciones prácticas son tan importantes hoy como lo fueron hace 200 años.",
  "La electrólisis ocurre cuando se introduce corriente eléctrica en una solución conductora (electrolito). El electrodo positivo (ánodo) atrae los iones negativos de la solución, y el electrodo negativo (cátodo) atrae los iones positivos. En la celda de electrólisis más simple, el agua puede descomponerse en sus elementos: en el cátodo se produce hidrógeno gas (H₂) y en el ánodo se produce oxígeno gas (O₂). Este proceso, llamado electrólisis del agua, es hoy la principal tecnología para producir hidrógeno 'verde' usando energía renovable.",
  "Las Leyes de la Electrólisis de Faraday, publicadas en 1833-1834, son de extraordinaria precisión. La Primera Ley establece que la masa de sustancia depositada en un electrodo es directamente proporcional a la carga eléctrica total que pasa por la celda (medida en Culombios). La Segunda Ley establece que, para la misma carga eléctrica, la masa depositada de diferentes sustancias es proporcional a sus 'equivalentes electroquímicos' (masa atómica dividida por la valencia del ion).",
  "Las implicaciones de las Leyes de Faraday fueron inmensas. Por primera vez, había una relación cuantitativa precisa entre la electricidad (una fuerza difusa y misteriosa) y la cantidad de materia transformada. Esto implicaba que la electricidad estaba compuesta de 'unidades' discretas. Faraday no llegó a proponer que la electricidad estaba hecha de partículas (los electrones no fueron descubiertos hasta 1897 por J.J. Thomson), pero sus leyes lo implicaban matemáticamente. Las leyes de Faraday fueron la primera evidencia indirecta de que los electrones existen.",
  "La galvanoplastia, también llamada electrodeposición, usa la electrólisis para depositar capas delgadas de un metal sobre otro. Se usa para hacer los cubiertos 'plateados' (que en realidad son de acero con una capa de plata de apenas micras de espesor), las llantas 'cromadas' de los coches, los circuitos de cobre de los microchips y los recubrimientos de zinc en el acero galvanizado. Sin la galvanoplastia basada en los principios de Faraday, muchos objetos cotidianos serían mucho más caros o directamente imposibles de fabricar.",
  "La industria del aluminio existe gracias a la electrólisis. El aluminio es muy abundante en la corteza terrestre (el tercer elemento más abundante después del oxígeno y el silicio), pero nunca aparece como metal puro en la naturaleza: siempre está combinado con oxígeno en minerales como la bauxita. El proceso Hall-Héroult, desarrollado en 1886, usa electrólisis de alta temperatura para separar el aluminio del oxígeno. Sin este proceso, no existirían los aviones, las latas de refresco, ni los smartphones, porque el aluminio sería tan raro como el platino.",
  "El hidrógeno producido por electrólisis del agua tiene un enorme potencial como combustible del futuro. Cuando el hidrógeno se combina con oxígeno en una celda de combustible, produce agua y electricidad, sin ningún residuo contaminante. Si la electrólisis del agua se hace usando energía solar o eólica (energía 'verde'), el ciclo completo es perfectamente limpio: energía solar separa el agua en hidrógeno y oxígeno, el hidrógeno se transporta y almacena, y al quemarlo en una celda de combustible produce electricidad y agua. Es el ciclo energético más limpio imaginable.",
  "La producción de cloro e hidróxido de sodio (soda cáustica) por electrólisis de sal (cloruro de sodio) es una de las industrias químicas más grandes del mundo. El proceso 'cloro-álcali' produce 70 millones de toneladas de cloro al año, usado para desinfectar el agua potable, fabricar plásticos PVC, producir solventes y preparar papel. Sin la electrólisis de Faraday, el tratamiento del agua potable para ciudades de millones de personas sería imposible.",
  "La recarga de las baterías recargables es esencialmente electrólisis inversa. En una batería de litio-ión, cuando se descarga, los iones de litio fluyen de un electrodo al otro y producen corriente eléctrica. Cuando se recarga, la corriente eléctrica externa fuerza a los iones a regresar a su posición original. Este proceso de electrólisis inversa puede repetirse miles de veces. Sin comprender la electrólisis, no existirían los teléfonos móviles, los coches eléctricos ni los paneles solares con baterías.",
  "La anodización del aluminio es un proceso electrolítico que crea una capa de óxido de aluminio en la superficie del metal, haciéndolo mucho más resistente a la corrosión y a los arañazos. Esta capa puede además ser coloreada con tintes para obtener colores duraderos. Los MacBooks de aluminio de Apple, las carcasas de los iPhones y los marcos de las bicicletas de alta gama están anodizados. El aspecto mate y sofisticado del aluminio anodizado es el resultado directo de la electrólisis que Faraday estudió en el siglo XIX.",
  "La producción de cobre de alta pureza para la industria electrónica usa la electrólisis. El cobre ordinario contiene impurezas que reducen su conductividad eléctrica. Para los cables de alta calidad y los circuitos electrónicos, se necesita cobre de pureza 99.99%. El 'refinado electrolítico' del cobre usa electrólisis para depositar solo los átomos de cobre en el cátodo, dejando las impurezas en la solución o depositándolas como lodo en el ánodo. Sin este proceso, no existirían los chips de computadora ni las redes de fibra óptica.",
  "Faraday inventó el vocabulario que usamos hoy en electrólisis, en colaboración con el filósofo William Whewell. Los términos 'ion', 'anión', 'catión', 'electrodo', 'ánodo', 'cátodo' y 'electrólisis' fueron todos acuñados por Faraday y Whewell en la década de 1830. Antes de Faraday, no existía la terminología para describir con precisión lo que ocurría en una celda electrolítica. Crear el vocabulario de un campo es tan importante como descubrir los fenómenos mismos: sin palabras precisas, no puede haber ciencia precisa.",
  "Los sensores electroquímicos, que miden la concentración de sustancias químicas detectando cambios en corriente eléctrica o voltaje, usan los principios de la electrólisis de Faraday. El glucómetro que los diabéticos usan para medir su nivel de azúcar en sangre es un sensor electroquímico: usa la reacción de la glucosa con la glucosa oxidasa (una enzima) para producir una pequeña corriente eléctrica proporcional a la concentración de glucosa. El sensor de oxígeno de los hospitales funciona de manera similar.",
  "Las pilas de combustible de los coches eléctricos como el Toyota Mirai usan hidrógeno y oxígeno para generar electricidad mediante una reacción electroquímica inversa a la electrólisis. En la pila de combustible, el hidrógeno se oxida en el ánodo (perdiendo electrones) y el oxígeno se reduce en el cátodo (ganando electrones). La corriente fluye entre los electrodos, generando electricidad. El único subproducto es agua limpia. Faraday habría reconocido inmediatamente el principio de sus propias celdas de electrólisis, invertido.",
  "El legado de la electrólisis de Faraday es que dio a la humanidad el poder de transformar la materia usando electricidad. Esta capacidad ha dado forma a la modernidad: el aluminio para los aviones, el cobre para los cables, el hidrógeno para la energía limpia, los metales para la electrónica, el cloro para el agua potable. Cada uno de estos materiales es producido, purificado o procesado usando el mismo principio que Faraday descubrió meticulosamente en su laboratorio de la Royal Institution hace casi dos siglos."
]);

// faraday_m5 — Las Líneas de Fuerza y el Cosmos Electromagnético
src = replaceSection(src, 'faraday_m5', [
  "¡Última misión faradáica, cadete cosmológico! Para cerrar nuestro viaje a través del electromagnetismo de Faraday, vamos a explorar la idea más filosóficamente profunda que este científico desarrolló: las líneas de fuerza y su visión del cosmos como un tejido de campos de energía. Esta idea, que Faraday no pudo formalizar matemáticamente porque nunca aprendió las matemáticas avanzadas necesarias, fue sin embargo la semilla de todas las teorías de campo de la física moderna.",
  "Las líneas de fuerza de Faraday eran originalmente una herramienta pictórica: una manera de visualizar cómo se distribuye la fuerza en el espacio alrededor de un imán o una carga eléctrica. Pero Faraday fue más allá: llegó a creer que las líneas de fuerza eran físicamente reales, que el campo magnético y eléctrico eran realidades físicas tan tangibles como el imán mismo, aunque ocuparan el espacio aparentemente vacío entre los objetos. Esta fue una idea revolucionaria que chocaba con el pensamiento físico dominante de su época.",
  "James Clerk Maxwell tomó las ideas intuitivas de Faraday sobre las líneas de fuerza y las formuló matemáticamente en sus cuatro ecuaciones (1861-1865). Las Ecuaciones de Maxwell describían matemáticamente cómo los campos eléctricos y magnéticos se generan, se propagan y se interrelacionan. Maxwell descubrió en sus propias ecuaciones que los campos electromagnéticos podían propagarse como ondas a una velocidad que calculó: era exactamente la velocidad de la luz. Concluyó que la luz es una onda electromagnética.",
  "Las ondas electromagnéticas predichas por Maxwell y verificadas experimentalmente por Heinrich Hertz en 1887 son las ondas de radio, microondas, infrarrojas, luz visible, ultravioleta, rayos X y rayos gamma, según su frecuencia. Todo el espectro electromagnético, desde las ondas de radio de kilómetros de longitud hasta los rayos gamma de picómetros, son ondas del mismo tipo: perturbaciones del campo electromagnético que se propagan por el espacio a la velocidad de la luz (300,000 km/s en el vacío).",
  "La radio y la televisión, el WiFi y el Bluetooth, los teléfonos móviles, el GPS, los microondas, los rayos X médicos, las comunicaciones por satélite: todos son aplicaciones del descubrimiento que siguió directamente de las líneas de fuerza de Faraday. Las ondas electromagnéticas de Maxwell-Hertz son la base de toda la tecnología de comunicaciones moderna. Si Faraday pudiera ver un smartphone, reconocería en él la realización de sus intuiciones más profundas sobre la naturaleza del electromagnetismo.",
  "Einstein relacionó directamente las líneas de fuerza de Faraday con su propia teoría de la Relatividad Especial. Cuando Einstein tenía 16 años, se preguntó qué vería si viajara a la velocidad de la luz junto a una onda electromagnética. Esta pregunta lo llevó, 10 años después, a la Relatividad Especial. En su famoso artículo de 1905, Einstein cita explícitamente la asimetría en el movimiento relativo de un imán y un conductor (un problema que surge directamente de las líneas de fuerza de Faraday) como la motivación para su teoría.",
  "Las líneas de fuerza de Faraday se convirtieron, en la física moderna, en el concepto de 'campo cuántico'. La teoría cuántica de campos (QED: Electrodinámica Cuántica) es la teoría más precisa de toda la física: predice propiedades del electrón con una precisión de 12 dígitos significativos, igual que medir la distancia de Nueva York a Los Ángeles con un error menor que el ancho de un cabello humano. En QED, las líneas de fuerza de Faraday son representadas por fotones virtuales que los electrones intercambian cuando se atraen o repelen.",
  "El campo electromagnético del Sol (la radiación solar) es la fuente de prácticamente toda la energía de la Tierra. La luz solar impulsa la fotosíntesis que crea el oxígeno y los alimentos. Los combustibles fósiles son energía solar almacenada por plantas hace millones de años. La energía solar directa, la energía eólica (causada por las diferencias de temperatura solar en la atmósfera) y la energía hidroeléctrica (el ciclo del agua impulsado por el Sol) son todas formas de energía solar. El cosmos electromagnético que Faraday intuía literalmente sustenta la vida en la Tierra.",
  "El 'problema del horizonte' en cosmología está relacionado con el electromagnetismo. Las regiones del universo más separadas que la luz ha tenido tiempo de conectar desde el Big Bang muestran las mismas temperaturas del fondo de microondas cósmico (la 'radiación de fondo'). ¿Cómo puede ser tan uniforme el universo si la luz no ha tenido tiempo de conectar esas regiones? La respuesta es la 'inflación cósmica': en el primer microsegundo del universo, el cosmos se expandió mucho más rápido que la velocidad de la luz, estirando las fluctuaciones cuánticas del campo electromagnético primordial a escalas macroscópicas.",
  "Los pulsares, estrellas de neutrones que giran a cientos de veces por segundo y emiten potentes haces de ondas de radio, son los 'faros electromagnéticos' del cosmos. Fueron descubiertos en 1967 por Jocelyn Bell Burnell. Sus señales de radio, tan regulares que inicialmente se pensó que podían ser señales de inteligencia extraterrestre, son producidas por la rotación de un campo magnético de 10 trillones de Teslas (200 billones de veces el campo magnético de la Tierra) alrededor del eje de rotación de la estrella. Son la realización más extrema del electromagnetismo en el universo.",
  "Las ondas gravitacionales, detectadas por primera vez en 2015 por LIGO, son la contraparte gravitacional de las ondas electromagnéticas. Así como los campos eléctricos y magnéticos oscilantes crean ondas electromagnéticas (luz, radio, etc.), los campos gravitacionales oscilantes (producidos por masas que se aceleran) crean ondas gravitacionales. La analogía matemática entre las ecuaciones de Maxwell del electromagnetismo y las ecuaciones de Einstein de la gravedad fue señalada muchas veces por físicos del siglo XX que buscaban una 'teoría de campos unificada'.",
  "La 'física más allá del Modelo Estándar' busca unificar el electromagnetismo (descrito por la QED) con las fuerzas nucleares fuertes y débiles y con la gravedad en una única 'Teoría del Todo'. La primera unificación parcial fue lograda por Glashow, Salam y Weinberg en 1968-1979 (Premio Nobel 1979): demostraron que el electromagnetismo y la fuerza nuclear débil son manifestaciones de una única fuerza 'electrodébil'. El sueño de Faraday de un universo unificado por campos de fuerza está más cerca de realizarse que nunca.",
  "Los detectores de partículas como el Gran Colisionador de Hadrones (LHC) del CERN usan el electromagnetismo para acelerar y controlar los haces de protones. Electroimanes superconductores de 8.3 Teslas (fabricados con niobio-titanio enfriado a -271°C) curvan y focalizan los haces. Campos eléctricos de radiofrecuencia aceleran los protones hasta el 99.9999991% de la velocidad de la luz. El LHC es el instrumento científico más complejo de la historia humana, y funciona gracias a los principios de electromagnetismo que Faraday descubrió.",
  "Faraday pasó sus últimos años reflexionando sobre la unidad de las fuerzas de la naturaleza. Intentó, sin éxito, demostrar que la gravedad y el electromagnetismo eran manifestaciones de la misma fuerza fundamental. Los experimentos que hizo, aunque negativos, fueron metodológicamente impecables y están documentados en detalle. La búsqueda de la unificación de las fuerzas es el hilo conductor de la física desde Faraday hasta hoy. Einstein dedicó sus últimos 30 años a esta búsqueda. Los físicos del siglo XXI continúan la misma empresa.",
  "El legado de Faraday es que nos dio la visión de un cosmos fundamentalmente electromagnético: un universo donde el espacio aparentemente vacío está lleno de campos de energía que conectan todos los objetos y transmiten todas las fuerzas. Esta visión, que comenzó con líneas de fuerza dibujadas con limaduras de hierro en un cuaderno de laboratorio, se ha convertido en la base matemática de la física cuántica de campos, la teoría más exitosa de la ciencia. El autodidacta del sur de Londres que nunca aprendió cálculo intuyó el corazón matemático del universo."
]);

fs.writeFileSync(FILE, src, 'utf8');
console.log('All Faraday modules done.');
