/**
 * patch_wormhole.js — Expands wormhole_m1 through wormhole_m15 to 15 paragraphs
 * Uses the universal "order" boundary patcher from patch_universal.js
 */
const fs = require('fs');
const path = require('path');
const { patchModule, replaceTextAndQuiz, getModuleChunk } = require('./patch_universal');
const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

const WORMHOLE = {
  wormhole_m1: {
    extra: [
      "Los agujeros de gusano son estructuras hipotéticas del espacio-tiempo que conectarían dos puntos distantes del universo. La idea surgió de las ecuaciones de la relatividad general de Albert Einstein en 1915, aunque Einstein mismo no les llamó así.",
      "El término 'agujero de gusano' (wormhole en inglés) fue inventado por el físico John Wheeler en 1957. Lo usó como analogía: si una manzana tiene un gusano que la perfora, el gusano puede ir de un lado al otro mucho más rápido que si rodea la superficie.",
      "Para entender un agujero de gusano, imagina que el espacio es como una hoja de papel. Si doblas el papel hasta que dos puntos distantes se toquen, un túnel que conecte esos dos puntos sería un agujero de gusano. El camino a través del túnel sería mucho más corto que el camino sobre la superficie del papel.",
      "La relatividad general de Einstein dice que la gravedad no es solo una fuerza, sino una curvatura del espacio-tiempo. Los objetos masivos como estrellas y agujeros negros doblan el tejido del espacio-tiempo. Los agujeros de gusano serían pliegues extremos de ese tejido.",
      "Einstein y su colega Nathan Rosen describieron en 1935 una solución matemática a las ecuaciones de la relatividad llamada 'puente de Einstein-Rosen'. Era la primera descripción matemática rigurosa de lo que hoy llamamos un agujero de gusano.",
      "La física moderna distingue varios tipos de agujeros de gusano. Los 'atravesables' permitirían viajar de un lado al otro. Los 'no atravesables' se colapsarían instantáneamente. Hasta ahora, todas las soluciones conocidas son del tipo no atravesable o requieren materia exótica para ser estables.",
      "La materia exótica es un tipo hipotético de material con energía negativa. En física normal, toda energía es positiva. Pero la mecánica cuántica predice que en escalas muy pequeñas puede haber fluctuaciones de energía negativa (el efecto Casimir). Si existiera materia exótica en grandes cantidades, podría mantener abierto un agujero de gusano.",
      "El efecto Casimir es real y ha sido medido en laboratorio: si colocas dos placas metálicas muy juntas en el vacío, la presión entre ellas es ligeramente menor que la del exterior. Esto significa que el vacío entre las placas tiene menos energía que el vacío normal: energía negativa a pequeña escala.",
      "La escala de los agujeros de gusano teóricos más simples sería extremadamente pequeña: del orden de la longitud de Planck (10⁻³⁵ metros), trillones de veces más pequeños que un protón. Hacerlos atravesables requeriría expandirlos a tamaño macroscópico, lo cual es energéticamente colosal.",
      "A pesar de no haber evidencia observacional directa de agujeros de gusano, su existencia es consistente con las leyes de la física que conocemos. No están prohibidos por ninguna ley física fundamental. Solo son extraordinariamente difíciles de crear o detectar."
    ],
    quiz: [
      { q: "¿Quién inventó el término 'agujero de gusano' (wormhole)?", options: ["Albert Einstein","Nathan Rosen","John Wheeler","Stephen Hawking"], a: 2 },
      { q: "¿Cómo se llama la primera descripción matemática de un agujero de gusano?", options: ["Túnel cuántico","Puente de Einstein-Rosen","Solución de Kerr","Métrica de Schwarzschild"], a: 1 },
      { q: "¿Qué se necesita teóricamente para mantener estable un agujero de gusano?", options: ["Energía oscura","Materia exótica con energía negativa","Un agujero negro gigante","Velocidad mayor que la luz"], a: 1 },
      { q: "¿Qué es el efecto Casimir?", options: ["La atracción entre dos agujeros negros","Una medición real de energía negativa entre placas metálicas","La velocidad de la luz en el vacío","La temperatura de un agujero negro"], a: 1 },
      { q: "¿De qué tamaño serían los agujeros de gusano más simples según la teoría?", options: ["Del tamaño de un estadio","Del tamaño de un protón","Del orden de la longitud de Planck (10⁻³⁵ m)","Del tamaño de la Tierra"], a: 2 }
    ]
  },
  wormhole_m2: {
    extra: [
      "La relatividad especial de Einstein establece que nada con masa puede viajar más rápido que la luz, cuya velocidad es de 299,792 kilómetros por segundo. Sin embargo, los agujeros de gusano no romperían esta regla: el objeto no viaja más rápido que la luz, sino que el espacio mismo se 'acorta'.",
      "El espacio intergaláctico es inmensamente vasto. La estrella más cercana a la Tierra (Proxima Centauri) está a 4.24 años luz: la luz tarda más de cuatro años en llegar. Viajar allí con la tecnología actual tomaría más de 70,000 años.",
      "Con un agujero de gusano traversable, podrías entrar en un extremo cercano a la Tierra y salir en el otro extremo cerca de Proxima Centauri en segundos, sin violar las leyes de la física. No has viajado más rápido que la luz; simplemente has tomado un 'atajo' por una curvatura del espacio-tiempo.",
      "La geometría del espacio-tiempo en un agujero de gusano es descrita por la métrica de Morris-Thorne (1988), propuesta por los físicos Michael Morris y Kip Thorne. Es la primera descripción matemática detallada de un agujero de gusano atravesable.",
      "Kip Thorne ganó el Premio Nobel de Física en 2017 por su trabajo en ondas gravitacionales. También es conocido por ser el asesor científico de la película 'Interstellar' (2014), donde los agujeros de gusano jugaron un papel central en la trama.",
      "Las ondas gravitacionales son perturbaciones en el tejido del espacio-tiempo causadas por eventos catastróficos como la fusión de dos agujeros negros. Fueron detectadas por primera vez el 14 de septiembre de 2015 por el detector LIGO. Esta detección confirmó otra predicción de Einstein y abrió una nueva era de la astronomía.",
      "Si los agujeros de gusano existieran naturalmente, podrían formarse en las condiciones extremas de los primeros instantes del universo, justo después del Big Bang, cuando la densidad de energía era tan alta que el espacio-tiempo podría haberse plegado y retorcido formando estructuras topológicas complejas.",
      "Algunos físicos proponen que los agujeros de gusano podrían estar conectados con los agujeros negros. En 2013, Juan Maldacena y Leonard Susskind propusieron la conjetura ER=EPR: que un par de partículas entrelazadas cuánticamente (EPR) equivale matemáticamente a un micro agujero de gusano (ER, por Einstein-Rosen).",
      "El entrelazamiento cuántico es un fenómeno donde dos partículas están tan correlacionadas que medir el estado de una afecta instantáneamente el estado de la otra, sin importar la distancia. Einstein lo llamó 'acción fantasmal a distancia' y no le gustaba. Hoy es una de las bases de la computación cuántica.",
      "La conjetura ER=EPR sugeriría que la información puede viajar a través de micro agujeros de gusano cuánticos. Esto podría resolver la paradoja de la información de los agujeros negros, uno de los problemas abiertos más importantes de la física teórica actual."
    ],
    quiz: [
      { q: "¿Qué es un año luz?", options: ["El tiempo que la Tierra tarda en rodear el Sol","La distancia que recorre la luz en un año","La velocidad promedio de un cometa","La distancia de la Tierra a la Luna"], a: 1 },
      { q: "¿Cómo se llama la primera descripción matemática de un agujero de gusano atravesable?", options: ["Puente de Einstein-Rosen","Métrica de Morris-Thorne","Solución de Kerr","Conjetura ER=EPR"], a: 1 },
      { q: "¿Qué detectó el instrumento LIGO en 2015?", options: ["Un agujero de gusano","Un agujero negro","Ondas gravitacionales","Materia exótica"], a: 2 },
      { q: "¿Qué propone la conjetura ER=EPR?", options: ["Que los agujeros negros no existen","Que las partículas entrelazadas equivalen matemáticamente a un micro agujero de gusano","Que el espacio-tiempo no existe","Que la luz puede viajar más rápido en un agujero de gusano"], a: 1 },
      { q: "¿Cuánto tarda la luz en llegar desde Proxima Centauri a la Tierra?", options: ["4 minutos","4 meses","4.24 años","42 años"], a: 2 }
    ]
  },
  wormhole_m3: {
    extra: [
      "Un agujero negro es una región del espacio-tiempo donde la gravedad es tan extrema que nada, ni siquiera la luz, puede escapar. El límite desde el cual ya no hay retorno se llama 'horizonte de eventos'. Dentro de ese horizonte, el tiempo y el espacio intercambian sus roles de maneras que desafían la intuición.",
      "Los agujeros negros no son 'aspiradoras cósmicas'. Si el Sol se convirtiera en un agujero negro (lo cual no ocurrirá, es demasiado pequeño), la Tierra seguiría orbitándolo exactamente igual. Lo que cambia es que ya no recibiríamos su luz ni su calor.",
      "Los agujeros negros se forman cuando una estrella muy masiva (más de unas 20 veces la masa del Sol) agota su combustible nuclear y colapsa sobre sí misma. La presión del colapso es tan extrema que aplasta toda la masa en un punto matemático de densidad infinita llamado 'singularidad'.",
      "Hay diferentes tipos de agujeros negros. Los de masa estelar tienen entre 3 y 100 veces la masa del Sol. Los supermasivos, que se encuentran en el centro de casi todas las galaxias grandes (incluida la nuestra, con Sagitario A*), tienen millones o miles de millones de veces la masa del Sol.",
      "Sagitario A*, el agujero negro supermasivo en el centro de la Vía Láctea, tiene unos 4 millones de veces la masa del Sol. En 2022, el Telescopio del Horizonte de Sucesos (EHT) publicó la primera imagen directa de Sagitario A*, revelando su silueta oscura rodeada de un disco de gas caliente.",
      "La relación entre agujeros negros y agujeros de gusano es fascinante. Matemáticamente, un agujero negro de Schwarzschild (el tipo más simple, sin rotación ni carga) tiene una estructura geométrica que incluye dos 'regiones exteriores' conectadas por un puente, que es el agujero de gusano de Einstein-Rosen.",
      "Sin embargo, este agujero de gusano de Einstein-Rosen dentro de un agujero negro simple no puede ser atravesado: se forma y colapsa en un instante, más rápido de lo que cualquier objeto podría cruzarlo. Para ser traversable necesitaría ser 'sostenido' con materia exótica.",
      "Los agujeros negros en rotación (llamados 'de Kerr') tienen una estructura más compleja. Matemáticamente tienen dos horizontes de eventos concéntricos y una región llamada 'ergosfera' donde el espacio-tiempo mismo es arrastrado en la dirección de rotación. Algunos físicos proponen que los agujeros de gusano traversables podrían asociarse con agujeros negros de Kerr.",
      "La radiación de Hawking es una predicción teórica (aún no confirmada directamente) que dice que los agujeros negros emiten lentamente radiación térmica por efectos cuánticos en el horizonte de eventos. Con el tiempo, un agujero negro podría 'evaporarse' completamente. La temperatura de esta radiación es inversamente proporcional a la masa del agujero negro.",
      "La paradoja de la información de los agujeros negros pregunta: cuando un agujero negro se evapora, ¿qué pasa con la información de todo lo que cayó en él? La mecánica cuántica dice que la información nunca puede destruirse. Esta paradoja no está resuelta y es uno de los grandes problemas de la física teórica actual."
    ],
    quiz: [
      { q: "¿Cómo se llama el límite desde el cual nada puede escapar de un agujero negro?", options: ["Singularidad","Horizonte de eventos","Ergosfera","Punto de Schwarzschild"], a: 1 },
      { q: "¿Qué es Sagitario A*?", options: ["Una estrella muy brillante","El agujero negro supermasivo en el centro de la Vía Láctea","Un cúmulo de estrellas","Un agujero de gusano confirmado"], a: 1 },
      { q: "¿Por qué el agujero de gusano de Einstein-Rosen no puede atravesarse?", options: ["Porque es demasiado pequeño","Porque se forma y colapsa más rápido de lo que cualquier objeto podría cruzarlo","Porque tiene temperatura demasiado alta","Porque está dentro de una galaxia"], a: 1 },
      { q: "¿Cómo se llama el agujero negro que tiene rotación?", options: ["Agujero de Schwarzschild","Agujero de Kerr","Agujero de Reissner","Agujero de Hawking"], a: 1 },
      { q: "¿Qué es la radiación de Hawking?", options: ["Luz visible emitida por agujeros negros","Radiación térmica que los agujeros negros emiten teóricamente por efectos cuánticos","Ondas gravitacionales de agujeros negros","Radiación gamma de supernovas"], a: 1 }
    ]
  },
  wormhole_m4: {
    extra: [
      "El espacio-tiempo es la combinación de las tres dimensiones del espacio (largo, ancho, alto) con una cuarta dimensión: el tiempo. Einstein demostró que espacio y tiempo no son separados, sino aspectos diferentes de una misma realidad física: el tejido del espacio-tiempo.",
      "La curvatura del espacio-tiempo es lo que experimentamos como gravedad. Donde hay masa, el espacio-tiempo se curva. Los planetas orbitan el Sol no porque sean 'atraídos', sino porque siguen las trayectorias más naturales (geodésicas) en el espacio-tiempo curvado por la masa del Sol.",
      "Un experimento mental famoso: imagina una goma de caucho extendida. Si colocas una bola pesada en el centro, la goma se curva. Una pelota pequeña que pase cerca de la bola grande seguirá una trayectoria curvada. Así funciona la gravedad según la relatividad general.",
      "La curvatura del espacio-tiempo ha sido medida directamente. La luz de estrellas distantes se dobla al pasar cerca del Sol, lo que fue verificado por Arthur Eddington durante el eclipse solar de 1919. Ese experimento convirtió a Einstein en una celebridad mundial instantánea.",
      "El GPS en tu teléfono necesita corregir los efectos de la relatividad para funcionar con precisión. Los satélites GPS orbitan a alta velocidad y a gran altitud, donde el espacio-tiempo está menos curvado que en la superficie. Sin la corrección relativista, el GPS acumularía errores de varios kilómetros por día.",
      "Los agujeros de gusano son, en esencia, pliegues extremos del espacio-tiempo. Si el tejido del espacio-tiempo puede curvarse (lo cual es un hecho establecido), la pregunta es si puede plegarse tanto que dos puntos distantes se toquen, creando un puente.",
      "La topología es la rama de las matemáticas que estudia las propiedades del espacio que no cambian con deformaciones suaves. Los agujeros de gusano implicarían un cambio topológico del espacio-tiempo: una 'perforación' en su tejido, algo aún más radical que simplemente curvarlo.",
      "Los cambios topológicos del espacio-tiempo podrían estar prohibidos por la 'conjetura de la topología del espacio-tiempo' de Stephen Hawking, aunque esta conjetura no está completamente probada. Algunos modelos cuánticos de gravedad sugieren que los cambios topológicos son posibles a escalas de Planck.",
      "La energía de Planck es la escala en que los efectos cuánticos de la gravedad se vuelven importantes. A estas energías, el espacio-tiempo en sí podría tener una estructura 'espumosa' de fluctuaciones topológicas microscópicas, con micro agujeros de gusano abriéndose y cerrándose constantemente.",
      "Esta 'espuma cuántica' del espacio-tiempo fue propuesta por John Wheeler en los años 1950. En ella, a escalas de 10⁻³⁵ metros y 10⁻⁴³ segundos (la longitud y el tiempo de Planck), el tejido del espacio-tiempo no sería suave sino turbulento y caótico, lleno de fluctuaciones topológicas."
    ],
    quiz: [
      { q: "¿Qué demostró Einstein sobre el espacio y el tiempo?", options: ["Son independientes entre sí","Son aspectos diferentes de una misma realidad: el espacio-tiempo","El tiempo no existe","El espacio tiene solo 2 dimensiones"], a: 1 },
      { q: "¿Cómo verificó Arthur Eddington la curvatura del espacio-tiempo en 1919?", options: ["Midiendo la velocidad de la luz","Observando que la luz se dobla al pasar cerca del Sol durante un eclipse","Detectando ondas gravitacionales","Midiendo la masa de los agujeros negros"], a: 1 },
      { q: "¿Por qué el GPS necesita corregir efectos relativistas?", options: ["Porque los satélites van demasiado lento","Porque orbitan donde el espacio-tiempo está menos curvado y a alta velocidad","Porque la señal de radio se curva","Porque la Tierra rota"], a: 1 },
      { q: "¿Qué estudia la topología?", options: ["Los movimientos de los planetas","Las propiedades del espacio que no cambian con deformaciones suaves","La temperatura del universo","La velocidad de la luz"], a: 1 },
      { q: "¿Qué es la 'espuma cuántica' del espacio-tiempo propuesta por John Wheeler?", options: ["El agua del espacio interestelar","Fluctuaciones topológicas microscópicas del espacio-tiempo a escala de Planck","La energía oscura del universo","El fondo de microondas cósmico"], a: 1 }
    ]
  },
  wormhole_m5: {
    extra: [
      "Las propiedades de los agujeros de gusano dependen del tipo de solución matemática que los describe. El primer agujero de gusano de Einstein-Rosen era estático: no crecía ni se contraía. Pero era matemáticamente inestable: cualquier pequeña perturbación lo haría colapsar.",
      "Para que un agujero de gusano sea estable y traversable, necesita materia que ejerza una presión negativa en su interior, empujando las paredes del 'cuello' hacia afuera. Esta materia con presión negativa es lo que los físicos llaman materia exótica o materia de energía negativa.",
      "La energía oscura, que se cree que está acelerando la expansión del universo, tiene propiedades similares a la materia exótica: ejerce una presión negativa. Sin embargo, está distribuida uniformemente por todo el universo y no puede concentrarse para sostener un agujero de gusano.",
      "El perfil de densidad de energía a lo largo del eje de un agujero de gusano de Morris-Thorne tiene una forma característica: la energía es máxima en las 'bocas' y negativa (o al menos muy pequeña) en el cuello. Esto viola las llamadas 'condiciones de energía' de la relatividad general.",
      "Las condiciones de energía son restricciones físicas que dicen que la energía siempre debe ser positiva o al menos no negativa. La materia normal siempre cumple estas condiciones. Si un agujero de gusano las viola, necesita de un tipo de materia que no conocemos en la naturaleza.",
      "Kip Thorne y sus colaboradores demostraron en los años 1980 que la cantidad de materia exótica necesaria para sostener un agujero de gusano macroscópico sería enorme, posiblemente comparable a la masa de Júpiter pero con energía negativa. Esto hace que su creación artificial parezca prácticamente imposible con la tecnología previsible.",
      "Sin embargo, algunos investigadores han propuesto diseños de agujeros de gusano que requieren cantidades mucho menores de materia exótica, concentrándola en regiones muy pequeñas. Estos son los llamados 'agujeros de gusano cuánticos' o 'agujeros de gusano con pelos'.",
      "Los agujeros de gusano también tendrían propiedades gravitacionales peculiares desde el exterior. Un observador lejano vería la 'boca' del agujero de gusano como una región de curvatura espacial intensa, similar a un agujero negro pero sin horizonte de eventos. No atraparía a los objetos que no entren.",
      "La radiación de tidal forces (fuerzas de marea) sería un peligro para los viajeros en un agujero de gusano. Así como las mareas terrestres son causadas por diferencias de gravedad entre el lado cercano y lejano de la Tierra, un viajero en un agujero de gusano sufriría fuerzas que jalarían su cabeza y sus pies en direcciones opuestas.",
      "Para que un agujero de gusano sea 'gentil' con los viajeros, las fuerzas de marea en su interior deben ser tolerables. Esto requiere que el cuello del agujero de gusano sea suficientemente grande (al menos varios kilómetros de diámetro) y que la curvatura cambie gradualmente a lo largo del trayecto."
    ],
    quiz: [
      { q: "¿Por qué el agujero de gusano de Einstein-Rosen era inestable?", options: ["Porque era demasiado pequeño","Cualquier pequeña perturbación lo hacría colapsar","Porque estaba demasiado lejos","Por la radiación cósmica"], a: 1 },
      { q: "¿Qué tipo de materia se necesita para estabilizar un agujero de gusano?", options: ["Materia oscura","Antimateria","Materia exótica con energía negativa","Neutrones comprimidos"], a: 2 },
      { q: "¿Qué son las 'condiciones de energía' en física?", options: ["Las restricciones de que la energía siempre debe ser positiva o no negativa","El nivel mínimo de energía para encender un cohete","La temperatura mínima del espacio","La velocidad máxima de la materia"], a: 0 },
      { q: "¿Qué son las fuerzas de marea en un agujero de gusano?", options: ["Las mareas oceánicas causadas por la Luna","Fuerzas que jalarían la cabeza y los pies del viajero en direcciones opuestas","La gravedad en el centro del agujero de gusano","La presión del vacío"], a: 1 },
      { q: "¿Cuánta materia exótica se necesitaría para un agujero de gusano macroscópico?", options: ["Gramos","Kilogramos","La masa de la Luna","Comparable a la masa de Júpiter"], a: 3 }
    ]
  },
  wormhole_m6: {
    extra: [
      "Un agujero de gusano que conecta dos puntos del espacio también puede conectar dos momentos del tiempo si uno de sus extremos es acelerado o colocado en un campo gravitacional fuerte. Esto se debe a la dilatación temporal predicha por la relatividad.",
      "La dilatación temporal gravitacional significa que el tiempo pasa más lento cerca de objetos muy masivos. Si tomas uno de los extremos de un agujero de gusano y lo colocas cerca de un agujero negro, el tiempo en ese extremo pasará más lentamente que en el otro extremo.",
      "Después de cierto tiempo, los dos extremos del agujero de gusano existirían en momentos diferentes del universo. El extremo cercano al agujero negro habría 'envejecido' menos. Un viajero que entrara por el extremo 'joven' saldría por el extremo 'viejo' en el pasado.",
      "Esta posibilidad de viajar al pasado mediante un agujero de gusano fue analizada por Kip Thorne y sus colegas en 1988. Descubrieron que si se puede construir un agujero de gusano traversable, en principio también se puede construir una 'máquina del tiempo'.",
      "Sin embargo, Thorne también señaló que podría haber un mecanismo que prevenga el viaje al pasado: la 'conjetura de protección de la cronología' de Stephen Hawking. Esta conjetura dice que las leyes de la física siempre encontrarán una manera de impedir que se cree una máquina del tiempo.",
      "Uno de los argumentos contra el viaje al pasado es la paradoja del abuelo: si viajas al pasado y matas a tu abuelo antes de que tenga hijos, tú nunca habrías nacido, y por lo tanto nunca habrías viajado al pasado para matarlo. ¿Qué ocurriría entonces?",
      "Una solución a la paradoja del abuelo es la hipótesis de las 'historias consistentes': solo son posibles los viajes al pasado que no crean paradojas. Es decir, si viajas al pasado, solo puedes hacer cosas que ya ocurrieron. Eres parte del pasado desde el principio.",
      "Otra solución propone los universos paralelos: al viajar al pasado, creas una rama alternativa de la historia (un universo paralelo) donde tu abuelo sí es asesinado. Pero en tu universo original, nada cambia. Este es el modelo de los 'muchos mundos' de la mecánica cuántica.",
      "La mecánica cuántica ya implica la existencia de muchos mundos en su interpretación más extrema: cada vez que ocurre un evento cuántico aleatorio, el universo se divide en ramas donde ocurrió cada posibilidad. Esto es parte de la 'interpretación de los muchos mundos' de Hugh Everett III (1957).",
      "La intersección entre viaje en el tiempo, agujeros de gusano y mecánica cuántica es una de las fronteras más activas y especulativas de la física teórica. Algunos investigadores creen que una teoría completa de la gravedad cuántica (que aún no existe) podría resolver estas paradojas de manera definitiva."
    ],
    quiz: [
      { q: "¿Por qué un agujero de gusano podría también ser una máquina del tiempo?", options: ["Porque viaja más rápido que la luz","Porque la dilatación temporal puede hacer que sus extremos existan en momentos diferentes","Porque invierte el tiempo dentro de él","Porque conecta universos paralelos"], a: 1 },
      { q: "¿Qué es la 'conjetura de protección de la cronología' de Hawking?", options: ["Que el tiempo siempre avanza hacia adelante","Que las leyes de la física impiden crear máquinas del tiempo","Que los agujeros de gusano no existen","Que el universo tiene un límite temporal"], a: 1 },
      { q: "¿En qué consiste la paradoja del abuelo?", options: ["Si matas a tu abuelo en el pasado, tú nunca habrías nacido para hacer el viaje","Que los abuelos tienen más sabiduría que los nietos","Que los abuelos no pueden viajar en el tiempo","Que el tiempo es subjetivo para las personas mayores"], a: 0 },
      { q: "¿Qué propone la hipótesis de las 'historias consistentes'?", options: ["Que el viaje al pasado es imposible","Solo son posibles viajes al pasado que no crean paradojas","Que todos los viajes al pasado crean paradojas","Que la historia puede cambiar"], a: 1 },
      { q: "¿Qué es la 'interpretación de los muchos mundos' de Hugh Everett?", options: ["Que hay infinitas Tierras en el universo","Cada evento cuántico divide el universo en ramas donde ocurrió cada posibilidad","Que hay mundos paralelos de materia oscura","Que el universo es una simulación"], a: 1 }
    ]
  },
  wormhole_m7: {
    extra: [
      "Un agujero de gusano traversable funcionaría como un túnel bidireccional: se podría entrar por cualquiera de sus dos bocas y salir por la otra. Las bocas estarían fijas en el espacio-tiempo (aunque se podrían mover si se les aplica una fuerza), y el cuello entre ellas sería el camino más corto entre los dos puntos.",
      "La geometría del interior de un agujero de gusano de Morris-Thorne sería sorprendentemente tranquila comparada con la singularidad de un agujero negro. No habría singularidad: el espacio-tiempo sería suave y finito a lo largo de todo el trayecto. El cuello tendría una longitud determinada y una anchura mínima en su punto más estrecho.",
      "Un observador que cayera hacia un agujero de gusano (en lugar de un agujero negro) notaría que la gravedad en el exterior de la boca lo atrae, pero una vez dentro, la geometría cambia: el tejido del espacio-tiempo lo guía suavemente a través del cuello hacia la otra boca, sin aplastarlo.",
      "La duración del viaje a través de un agujero de gusano dependería de su longitud y de la velocidad del viajero. Podría ser casi instantánea si el cuello fuera muy corto, o podría durar minutos, horas o días si el cuello fuera largo. Un viajero que entrara en un extremo 'vería' el otro extremo desde el interior.",
      "Desde el exterior, un observador que mirara hacia la boca de un agujero de gusano vería el cielo del otro extremo, con todas sus estrellas y galaxias. Sería como mirar a través de una ventana hacia otra región del universo. Esto es muy diferente al horizonte de eventos negro de un agujero negro.",
      "En la película 'Interstellar' (2014), el agujero de gusano es representado como una esfera transparente que muestra el espacio en el otro lado. Aunque simplificada, esta representación es sorprendentemente fiel a cómo los físicos modelan matemáticamente la apariencia visual de un agujero de gusano atravesable.",
      "Un aspecto contraintuitivo: entrar en un agujero de gusano no requeriría caer 'hacia adentro' como en un pozo. La boca del agujero de gusano sería una región del espacio con curvatura intensa, pero el viajero podría entrar en ella simplemente llegando al borde y siguiendo la trayectoria natural del espacio-tiempo curvado.",
      "La fuerza gravitacional en el exterior de la boca de un agujero de gusano sería como la de cualquier objeto masivo: te atraería hacia la boca. Pero justo en la boca, la geometría cambia: en lugar de ir hacia una singularidad, el espacio-tiempo te desvía a través del cuello hacia la otra boca.",
      "Los fotones (partículas de luz) también podrían viajar a través de un agujero de gusano. Esto significa que, en principio, podrías ver a través de él, aunque la imagen estaría fuertemente distorsionada por la enorme curvatura del espacio-tiempo en las bocas y a lo largo del cuello.",
      "Las comunicaciones a través de un agujero de gusano serían instantáneas (o casi) independientemente de la distancia en el espacio exterior. Esto sería revolucionario: podrías enviar señales a galaxias lejanas sin esperar millones de años. Sin embargo, la cantidad de energía necesaria para abrir y mantener el canal de comunicación sería astronómica."
    ],
    quiz: [
      { q: "¿Cuántas bocas tiene un agujero de gusano traversable típico?", options: ["Una","Dos","Tres","Cuatro"], a: 1 },
      { q: "¿Qué vería un observador que mirara hacia la boca de un agujero de gusano?", options: ["Un punto completamente negro","El cielo del otro extremo del universo","Luz brillante infinita","Un espejo"], a: 1 },
      { q: "¿En qué se diferencia un agujero de gusano de un agujero negro para el viajero?", options: ["El agujero de gusano lo aplastaría más","No hay singularidad; el espacio-tiempo es suave en todo el trayecto","El agujero de gusano tiene más gravedad","El agujero de gusano solo permite viajar hacia el futuro"], a: 1 },
      { q: "¿Qué película de 2014 representa visualmente un agujero de gusano como una esfera?", options: ["Gravity","The Martian","Interstellar","2001: A Space Odyssey"], a: 2 },
      { q: "¿Qué ventaja tendrían las comunicaciones a través de un agujero de gusano?", options: ["Serían más baratas","Serían en color","Serían instantáneas independientemente de la distancia","No habría ventaja"], a: 2 }
    ]
  },
  wormhole_m8: {
    extra: [
      "Si un objeto cae en un agujero de gusano no traversable (como el de un agujero negro real), la imagen matemática es diferente a la de uno traversable. El objeto cruzaría el horizonte de eventos sin notar nada especial en el momento de cruzarlo (para un observador que cae), pero para alguien en el exterior, parecería que el objeto se detiene y se desvanece.",
      "Para un observador externo, un objeto que cae hacia un agujero negro parece ralentizarse cada vez más por la dilatación temporal, y su luz se vuelve cada vez más roja (corrimiento al rojo gravitacional) hasta que virtualmente desaparece. Nunca 'vería' al objeto cruzar el horizonte.",
      "Para el observador que cae, el cruce del horizonte de eventos de un agujero negro suficientemente grande (como uno supermasivo) sería imperceptible. Solo más tarde, al acercarse a la singularidad, las fuerzas de marea lo destruirían en un proceso que los físicos llaman 'espaguetización'.",
      "La espaguetización es la elongación extrema de un objeto cuando las fuerzas de marea de la gravedad son mucho más fuertes en un lado que en el otro. Un objeto que cae hacia una singularidad se estira primero y luego se desintegra, como un espagueti cósmico.",
      "En un agujero de gusano traversable diseñado correctamente, la espaguetización no ocurriría. La geometría del cuello estaría diseñada para que las fuerzas de marea sean mínimas. El viajero llegaría al otro lado intacto, como si simplemente hubiera viajado en un vehículo muy rápido.",
      "La velocidad requerida para cruzar un agujero de gusano no tendría por qué ser extrema. El viajero simplemente entraría por la boca y seguiría la trayectoria natural del espacio-tiempo curvado. No necesitaría propulsión adicional dentro del cuello si el agujero de gusano estuviera bien diseñado.",
      "Sin embargo, habría efectos de radiación dentro del agujero de gusano. Las fluctuaciones cuánticas del vacío se amplificarían por la geometría extrema del espacio-tiempo. Algunos cálculos sugieren que esta radiación podría ser tan intensa que destruiría tanto al viajero como al propio agujero de gusano.",
      "Este es el llamado 'problema de la estabilidad cuántica' de los agujeros de gusano: incluso si se puede crear uno con materia exótica, las fluctuaciones cuánticas podrían hacer que colapse antes de que cualquier viajero pueda cruzarlo. Es uno de los mayores obstáculos teóricos para los agujeros de gusano traversables.",
      "Algunos físicos proponen que este problema podría resolverse con un tipo especial de materia cuántica que tenga las propiedades correctas para estabilizar el agujero de gusano contra las fluctuaciones cuánticas. Esta materia hipotética está incluso más lejos de nuestra comprensión actual que la materia exótica.",
      "A pesar de todos estos obstáculos, la investigación teórica sobre agujeros de gusano sigue siendo activa porque podría revelar cosas fundamentales sobre la naturaleza de la gravedad, la mecánica cuántica y el espacio-tiempo. Incluso si los agujeros de gusano resultan ser imposibles, el proceso de intentar construirlos teóricamente nos enseña mucho."
    ],
    quiz: [
      { q: "¿Cómo parece, para un observador externo, un objeto que cae hacia un agujero negro?", options: ["Se mueve cada vez más rápido","Se ralentiza cada vez más y su luz se vuelve más roja","Explota","Desaparece instantáneamente"], a: 1 },
      { q: "¿Qué es la 'espaguetización'?", options: ["Un método de cocinar pasta en el espacio","La elongación extrema de un objeto por fuerzas de marea gravitacionales","La curvatura del espacio dentro de un agujero negro","La radiación emitida por agujeros negros"], a: 1 },
      { q: "¿Por qué un agujero de gusano traversable bien diseñado evitaría la espaguetización?", options: ["Porque no tiene gravedad","Porque las fuerzas de marea estarían minimizadas","Porque el viajero viaja a la velocidad de la luz","Porque el tiempo no pasa dentro"], a: 1 },
      { q: "¿Qué es el 'problema de la estabilidad cuántica' de los agujeros de gusano?", options: ["Que son demasiado pequeños","Las fluctuaciones cuánticas podrían hacer colapsar el agujero de gusano antes de cruzarlo","Que la materia exótica no existe","Que requieren demasiada energía para crearse"], a: 1 },
      { q: "¿Por qué sigue siendo útil investigar teóricamente los agujeros de gusano aunque sean imposibles?", options: ["Para ganar premios Nobel","Para hacer mejores películas de ciencia ficción","Porque revela cosas fundamentales sobre la gravedad, la mecánica cuántica y el espacio-tiempo","Para encontrar vida extraterrestre"], a: 2 }
    ]
  },
  wormhole_m9: {
    extra: [
      "Si caes en un agujero de gusano traversable, lo primero que notarías es que la región de espacio a tu alrededor comienza a curvarse visualmente. El campo de visión se distorsionaría: las estrellas y galaxias alrededor de la boca parecerían moverse y comprimirse hacia un anillo luminoso.",
      "Este anillo luminoso es similar al 'anillo de Einstein': cuando una fuente de luz, una masa masiva y un observador están alineados, la luz de la fuente se curva alrededor de la masa y forma un anillo perfecto. En la boca de un agujero de gusano, la fuente de luz es el cielo del otro extremo.",
      "A medida que te acercas a la boca, la imagen del otro extremo del universo (visible a través del agujero de gusano) comenzaría a 'abrirse' y ocupar una fracción cada vez mayor de tu campo de visión. Cuando estuvieras exactamente en la boca, la imagen del otro lado ocuparía la mitad de tu visión.",
      "Una vez dentro del cuello, estarías rodeado de espacio-tiempo curvado en todas las direcciones. El tiempo podría correr más rápido o más lento que en el exterior dependiendo de la geometría del agujero de gusano y de tu velocidad de movimiento.",
      "La experiencia sensorial dependería del tipo de agujero de gusano. En uno con fuerzas de marea mínimas, la experiencia sería como estar en una cápsula oscura que se mueve rápidamente. En uno con fuerzas de marea significativas, sentirías como si el espacio te estirara en una dirección y te comprimiera en otra.",
      "Una paradoja visual interesante: desde dentro del cuello, podrías ver hacia ambos extremos al mismo tiempo. Mirarías hacia adelante y verías el cielo del destino; mirarías hacia atrás y verías el cielo de tu punto de partida. Sería como estar en un pasillo con ventanas en ambos extremos.",
      "Si el agujero de gusano fuera también una máquina del tiempo (con sus extremos en momentos diferentes del tiempo), la experiencia de cruzarlo incluiría una 'discontinuidad temporal': saldrías en el mismo lugar en el espacio pero en un momento diferente. La diferencia podría ser segundos, años, o milenios.",
      "Físicamente, tu cuerpo no notaría directamente el viaje en el tiempo: no sentirías que el tiempo retrocede o avanza. Simplemente saldrías al otro extremo y notarías que el entorno ha cambiado: estrellas en posiciones diferentes, quizás una civilización diferente o ninguna en absoluto.",
      "La comunicación con el exterior durante el cruce dependería de si el agujero de gusano permite que las señales electromagnéticas viajen a través de él. Si sí, podrías mantener contacto por radio. Si no, el cruce sería como entrar en una zona sin señal, aislado del universo exterior hasta que salieras.",
      "Cuando salieras por el otro extremo, la experiencia visual sería la inversa de la entrada: la imagen del cielo de tu punto de partida se comprimiría en un disco cada vez más pequeño detrás de ti hasta que te alejaras lo suficiente para verlo como cualquier otra región del cielo. Habrías cruzado el universo."
    ],
    quiz: [
      { q: "¿Qué efecto visual ocurre cuando te acercas a la boca de un agujero de gusano?", options: ["Todo se vuelve negro","Las estrellas se comprimen en un anillo luminoso","La luz desaparece","Todo se vuelve muy brillante"], a: 1 },
      { q: "¿Qué es el 'anillo de Einstein'?", options: ["El anillo de saturno de un agujero negro","Cuando una fuente de luz, una masa y un observador están alineados formando un anillo luminoso","La forma de un agujero de gusano","Una constelación cerca del ecuador celeste"], a: 1 },
      { q: "¿Qué verías si estuvieras exactamente en la boca de un agujero de gusano?", options: ["Solo oscuridad","La imagen del otro extremo ocupando la mitad de tu campo de visión","Solo el punto de origen","Luz cegadora"], a: 1 },
      { q: "¿Cómo experimentarías un viaje en el tiempo a través de un agujero de gusano?", options: ["Sentirías el tiempo retroceder físicamente","Simplemente saldrías en un entorno diferente del esperado","Envejecerías muy rápido","Rejuvenecerías"], a: 1 },
      { q: "¿Desde dentro del cuello de un agujero de gusano, ¿qué podrías ver?", options: ["Nada, solo oscuridad","El cielo de ambos extremos, uno hacia adelante y uno hacia atrás","Solo el cielo del destino","Solo el cielo de origen"], a: 1 }
    ]
  },
  wormhole_m10: {
    extra: [
      "Si cayeras en un agujero de gusano no traversable (como el que existe matemáticamente dentro de un agujero negro real), el resultado sería muy diferente. Una vez cruzado el horizonte de eventos, no podrías volver al exterior. El futuro estaría completamente orientado hacia la singularidad.",
      "En el interior de un agujero negro, las dimensiones del espacio y el tiempo intercambian sus papeles. El 'tiempo futuro' apunta hacia la singularidad, así que es imposible evitarla: es tan inevitable como el hecho de que el tiempo avance hacia el futuro en la vida ordinaria.",
      "La singularidad de un agujero negro no es un 'lugar' en el espacio al que podrías dirigirte o evitar. Es un 'momento' en tu futuro inevitable. Una vez dentro del horizonte, todo tu futuro temporal apunta hacia ella. La espaguetización sería inevitable.",
      "Para un agujero negro supermasivo (como Sagitario A* con 4 millones de masas solares), el horizonte de eventos tendría un radio de unos 12 millones de kilómetros. Un viajero que cayera hacia él podría sobrevivir varios minutos o incluso horas después de cruzar el horizonte antes de llegar a la singularidad.",
      "Algunas teorías modernas proponen que la singularidad del agujero negro podría no existir en una teoría completa de gravedad cuántica. En lugar de una singularidad, podría haber una región de densidad extrema pero finita, o incluso una transición a otro universo (un 'universo bebé').",
      "La idea de los 'universos bebé' fue propuesta por Lee Smolin y otros físicos. Cada agujero negro podría generar un nuevo universo dentro de sí mismo, con constantes físicas ligeramente diferentes. Con el tiempo, el universo 'más apto' (que produce más agujeros negros) prevalecería: una especie de selección natural cósmica.",
      "Esta 'evolución cósmica' podría explicar por qué las constantes de la física tienen los valores exactos que tienen, y no otros. Si hubieran sido ligeramente diferentes, no se habrían formado estrellas, ni elementos pesados, ni la vida. Quizás nuestro universo es el producto de miles de generaciones de universos que se 'optimizaron' para producir agujeros negros.",
      "La conexión entre agujeros negros, singularidades, universos bebé y agujeros de gusano está en el corazón de la física teórica moderna. Estas ideas están en la frontera entre lo comprobable y lo especulativo, entre la ciencia establecida y la filosofía de la física.",
      "Un observador que cayera en un agujero negro real podría, en teoría, intentar enviar señales hacia afuera. Pero estas señales nunca podrían salir del horizonte de eventos. Para el observador externo, el objeto parece congelado en el tiempo justo en el horizonte. Hay una profunda asimetría de información entre el interior y el exterior.",
      "Esta asimetría de información es la base de la paradoja de la información de Hawking. Cuando el agujero negro finalmente se evapora por radiación de Hawking, la información de todo lo que cayó en él debería reaparecer de alguna forma para preservar el principio cuántico de conservación de la información. Cómo exactamente esto ocurre sigue siendo un misterio abierto."
    ],
    quiz: [
      { q: "¿Por qué es inevitable la singularidad para alguien dentro de un agujero negro?", options: ["Porque la gravedad es demasiado fuerte","Porque en el interior el tiempo y el espacio intercambian sus roles y la singularidad está en el 'futuro'","Porque la luz no puede escapar","Porque el espacio-tiempo colapsa"], a: 1 },
      { q: "¿Cuánto tiempo podría sobrevivir un astronauta después de cruzar el horizonte de un agujero negro supermasivo?", options: ["Microsegundos","Segundos","Minutos o incluso horas","No sobreviviría al cruce"], a: 2 },
      { q: "¿Qué son los 'universos bebé' propuestos por Lee Smolin?", options: ["Universos diminutos en el espacio","Nuevos universos que se formarían en el interior de los agujeros negros","Universos paralelos de materia oscura","Las primeras galaxias del universo"], a: 1 },
      { q: "¿En qué consiste la paradoja de la información de Hawking?", options: ["Que nadie sabe dónde están los agujeros negros","Cuando un agujero negro se evapora, ¿qué pasa con la información de lo que cayó en él?","Que la radiación de Hawking nunca ha sido medida","Que los agujeros negros no tienen masa"], a: 1 },
      { q: "¿Puede un observador externo ver directamente lo que ocurre dentro de un agujero negro?", options: ["Sí, con el telescopio suficiente","No, nada puede salir del horizonte de eventos","Sí, a través de ondas gravitacionales","Solo con luz ultravioleta"], a: 1 }
    ]
  },
  wormhole_m11: {
    extra: [
      "La física del siglo XXI enfrenta un gran desafío: unificar la relatividad general (que describe la gravedad y el cosmos a gran escala) con la mecánica cuántica (que describe las partículas subatómicas). Estas dos teorías son las más exitosas de la historia, pero son matemáticamente incompatibles entre sí.",
      "La teoría de cuerdas es uno de los intentos más desarrollados de unificar la gravedad con la mecánica cuántica. En ella, las partículas elementales no son puntos, sino pequeñas cuerdas vibrantes en un espacio de 10 dimensiones (o 11 en la teoría M). Los diferentes patrones de vibración corresponden a partículas diferentes.",
      "En la teoría de cuerdas, los agujeros de gusano son objetos naturales: aparecen en las soluciones de las ecuaciones y están relacionados con objetos llamados D-branas. Las branas son superficies multidimensionales en las que las cuerdas pueden terminar, y podrían ser las 'paredes' de los agujeros de gusano.",
      "La gravedad cuántica de bucles (LQG) es otra aproximación a la teoría cuántica de la gravedad. En lugar de cuerdas, propone que el espacio-tiempo mismo está discretizado en 'átomos de espacio' a escala de Planck. En este marco, los agujeros de gusano también aparecen de forma natural como posibles estructuras topológicas.",
      "El principio holográfico, desarrollado por Gerard 't Hooft y Leonard Susskind, propone que toda la información en un volumen del espacio puede ser codificada en su superficie bidimensional. Es como si el universo tridimensional fuera en realidad la 'proyección' de una realidad bidimensional.",
      "La correspondencia AdS/CFT (anti-de Sitter/teoría conformal de campos), descubierta por Juan Maldacena en 1997, es la implementación más concreta del principio holográfico. Dice que una teoría gravitacional en un espacio curvado (AdS) es matemáticamente equivalente a una teoría cuántica de campos sin gravedad en su frontera.",
      "Esta correspondencia ha sido extremadamente útil para estudiar los agujeros negros y los agujeros de gusano. Usando la 'dualidad' AdS/CFT, los físicos pueden calcular propiedades de los agujeros negros (como la temperatura de Hawking) usando la teoría cuántica de campos más simple en la frontera.",
      "La conjetura ER=EPR de Maldacena y Susskind (2013) usa la correspondencia AdS/CFT para proponer que dos agujeros negros entrelazados cuánticamente están conectados por un agujero de gusano. La geometría del agujero de gusano es el resultado geométrico del entrelazamiento cuántico.",
      "Si ER=EPR es correcto, tendría implicaciones profundas: la conectividad del espacio-tiempo (la existencia de agujeros de gusano) estaría relacionada con el entrelazamiento cuántico a nivel fundamental. El espacio-tiempo emergería del entrelazamiento cuántico, no al revés.",
      "Esta idea de que el espacio-tiempo 'emerge' de relaciones cuánticas más fundamentales es una de las fronteras más activas de la física teórica actual. Si es correcta, cambiaría completamente nuestra comprensión de qué es el espacio, el tiempo y la gravedad a nivel fundamental."
    ],
    quiz: [
      { q: "¿Cuál es el gran desafío de la física del siglo XXI?", options: ["Viajar más rápido que la luz","Unificar la relatividad general con la mecánica cuántica","Encontrar vida extraterrestre","Demostrar que el universo es finito"], a: 1 },
      { q: "¿Qué propone la teoría de cuerdas sobre las partículas elementales?", options: ["Son puntos matemáticos","Son pequeñas cuerdas vibrantes en múltiples dimensiones","Son agujeros negros microscópicos","Son ondas de gravedad"], a: 1 },
      { q: "¿Qué es el principio holográfico?", options: ["Que el universo es una imagen holográfica","Toda la información en un volumen del espacio puede codificarse en su superficie 2D","Que la materia oscura es un holograma","Que los agujeros negros emiten hologramas"], a: 1 },
      { q: "¿Qué propone la conjetura ER=EPR?", options: ["Que E=mc² está equivocada","Dos agujeros negros entrelazados cuánticamente están conectados por un agujero de gusano","Que la materia y la energía son iguales","Que el tiempo no existe"], a: 1 },
      { q: "¿Qué implicaría que el espacio-tiempo 'emerja' del entrelazamiento cuántico?", options: ["Que el espacio y el tiempo no son fundamentales, sino consecuencias de relaciones cuánticas","Que la mecánica cuántica es incorrecta","Que la relatividad general es perfecta","Que la física ya está completa"], a: 0 }
    ]
  },
  wormhole_m12: {
    extra: [
      "Los experimentos actuales para detectar o crear agujeros de gusano directamente son imposibles con la tecnología actual. Las energías requeridas son colosalmente superiores a las que puede producir cualquier acelerador de partículas, incluido el Gran Colisionador de Hadrones (LHC) del CERN.",
      "El LHC acelera protones hasta el 99.9999% de la velocidad de la luz y los hace colisionar con energías de hasta 13.6 TeV (teraelectronvoltios). Esto es enorme para la escala subatómica, pero es una fracción minúscula de la energía de Planck, la escala donde los agujeros de gusano cuánticos podrían existir.",
      "Algunos físicos esperaban que el LHC pudiera producir mini agujeros negros microscópicos si hay dimensiones extra del espacio. Si el espacio tiene más de 4 dimensiones (como predice la teoría de cuerdas), la gravedad podría ser mucho más fuerte a cortas distancias, y el LHC podría crear agujeros negros que evaporarían instantáneamente emitiendo radiación de Hawking.",
      "Esta hipótesis resultó incorrecta: el LHC no detectó mini agujeros negros. Esto no refuta la teoría de cuerdas directamente, pero limita los parámetros donde las dimensiones extra podrían existir. La física del LHC sigue siendo la más poderosa herramienta experimental disponible para la física de altas energías.",
      "Otra aproximación experimental propuesta es usar el entrelazamiento cuántico para sondear la existencia de micro agujeros de gusano. Si ER=EPR es correcta, crear pares de partículas fuertemente entrelazadas y medir sus propiedades correlacionadas podría revelar información sobre la geometría cuántica del espacio-tiempo entre ellas.",
      "En 2022, un equipo de investigadores del Instituto Tecnológico de California publicó un experimento en la computadora cuántica de Google que simuló un sistema físico equivalente a dos agujeros negros entrelazados y un agujero de gusano que los conecta. El experimento mostró comportamientos consistentes con la transferencia de información a través del 'agujero de gusano' simulado.",
      "Este experimento fue celebrado y debatido intensamente. Los críticos señalaron que la simulación cuántica ocurre en el espacio físico de la computadora cuántica, no en el espacio-tiempo del universo. No se creó un agujero de gusano real: se simuló uno matemáticamente usando entrelazamiento cuántico.",
      "Sin embargo, el experimento demostró que las ideas sobre la conexión entre entrelazamiento cuántico y geometría del espacio-tiempo son lo suficientemente concretas como para ser simuladas y probadas experimentalmente. Esto es un paso importante hacia una física de los agujeros de gusano basada en evidencia.",
      "Las observaciones astronómicas también buscan evidencia indirecta de agujeros de gusano. Si existieran naturalmente, podrían actuar como lentes gravitacionales que distorsionan la luz de las estrellas de fondo de maneras características. Las diferencias entre la lente de un agujero negro y la de un agujero de gusano son calculables teóricamente.",
      "Algunos investigadores proponen buscar 'ecos' en las señales de ondas gravitacionales de fusiones de agujeros negros. Según algunas teorías, si el objeto resultante es un agujero de gusano en lugar de un agujero negro, la señal de ondas gravitacionales tendría un patrón de ecos característico. Los detectores LIGO y Virgo buscan estos ecos en los datos."
    ],
    quiz: [
      { q: "¿Por qué no podemos crear agujeros de gusano en el laboratorio actualmente?", options: ["Están prohibidos por las leyes","Las energías requeridas son colosalmente superiores a las que producen los aceleradores actuales","No tenemos los materiales necesarios","Los gobiernos lo prohíben"], a: 1 },
      { q: "¿Qué hipótesis esperaba que el LHC pudiera probar sobre dimensiones extra?", options: ["Que el universo tiene solo 3 dimensiones","Que podrían producirse mini agujeros negros que se evaporarían instantáneamente","Que la materia oscura existe","Que el tiempo es la cuarta dimensión"], a: 1 },
      { q: "¿Qué simuló el experimento de 2022 en la computadora cuántica de Google?", options: ["Un viaje real a través de un agujero de gusano","Un sistema equivalente a dos agujeros negros entrelazados y un agujero de gusano","La creación de materia exótica","La evaporación de un agujero negro"], a: 1 },
      { q: "¿Cómo podrían detectarse agujeros de gusano astronómicamente?", options: ["Con telescopios de luz visible","Como lentes gravitacionales con patrones de distorsión diferentes a los agujeros negros","Con detectores de neutrinos","Con observatorios de rayos X"], a: 1 },
      { q: "¿Qué buscan los detectores LIGO y Virgo en las señales de fusiones de agujeros negros?", options: ["Señales de inteligencia extraterrestre","Ecos característicos que indicarían un agujero de gusano en lugar de un agujero negro","Materia exótica","Ondas de luz del Big Bang"], a: 1 }
    ]
  },
  wormhole_m13: {
    extra: [
      "La paradoja temporal del agujero de gusano más clásica es la 'paradoja del billar': una bola de billar entra en el pasado a través de un agujero de gusano y choca con su versión pasada, impidiéndole entrar al agujero de gusano. ¿Qué ocurre entonces?",
      "Los físicos Igor Novikov y Kip Thorne estudiaron la paradoja del billar y encontraron soluciones autoconsistentes. Por ejemplo: la bola llega al agujero de gusano con un ángulo ligeramente diferente porque la versión futura la golpeó tangencialmente en lugar de frontalmente. Siempre existen trayectorias consistentes.",
      "El principio de autoconsistencia de Novikov afirma que solo pueden ocurrir secuencias de eventos que sean consistentes consigo mismas. Si un viaje al pasado causaría una paradoja, ese viaje simplemente no puede ocurrir. Las leyes de la física seleccionan automáticamente las historias que no contienen paradojas.",
      "La paradoja del abuelo tiene una resolución diferente en el marco de los universos paralelos: al matar al abuelo, creas una rama alternativa de la historia. En esa rama, el asesino no existe (su abuelo fue asesinado antes de tener hijos), así que la paradoja se resuelve en un universo pero no afecta al universo de origen.",
      "La interpretación de los muchos mundos de la mecánica cuántica ya implica que cada medición cuántica divide el universo. Si esta interpretación es correcta, el viaje al pasado simplemente crearía otra división: el viajero aparecería en una rama histórica alternativa, no en su propio pasado.",
      "Hay paradojas más sutiles que la del abuelo. La 'paradoja del conocimiento': un científico del futuro viaja al pasado y le enseña al joven Einstein la teoría de la relatividad, que Einstein después desarrolla y que es el conocimiento que el científico del futuro aprendió en su época. ¿Quién inventó realmente la relatividad?",
      "Esta paradoja del conocimiento circula: la información existe en un bucle temporal sin un origen claro. Algunos físicos argumentan que estos 'bucles de información' violarían el segundo principio de la termodinámica, que dice que la entropía (el desorden) siempre aumenta. Un bucle temporal perfecto conservaría la información indefinidamente.",
      "La conjetura de protección de la cronología de Hawking no solo se basa en argumentos filosóficos. Hawking argumentó que, al crear un agujero de gusano que permita el viaje al pasado, las fluctuaciones cuánticas se amplificarían cada vez más cerca del 'horizonte de causación' hasta destruir el agujero de gusano.",
      "Este argumento de Hawking usa los mismos principios de la radiación de Hawking pero aplicados a los agujeros de gusano. La geometría del espacio-tiempo cerca de una máquina del tiempo sería inestable a nivel cuántico, auto-destruyéndose antes de que cualquier viajero pudiera usarla.",
      "Las paradojas temporales no son solo curiosidades filosóficas: son herramientas científicas. Cuando una teoría física produce paradojas, nos dice que la teoría está incompleta o incorrecta en ese régimen. Las paradojas de los agujeros de gusano y el viaje en el tiempo nos dicen que necesitamos una teoría cuántica de la gravedad para resolverlas."
    ],
    quiz: [
      { q: "¿En qué consiste la 'paradoja del billar' del viaje en el tiempo?", options: ["Una bola de billar es destruida por un agujero de gusano","Una bola entra al pasado y choca con su versión pasada, impidiéndose entrar","Una bola viaja más rápido que la luz","Una bola se duplica en el espacio-tiempo"], a: 1 },
      { q: "¿Qué afirma el principio de autoconsistencia de Novikov?", options: ["Que el viaje al pasado es imposible","Solo ocurren secuencias de eventos que son consistentes consigo mismas","Que el futuro determina el presente","Que la paradoja del abuelo es inevitable"], a: 1 },
      { q: "¿Cómo resuelven los 'muchos mundos' la paradoja del abuelo?", options: ["El viaje al pasado es imposible","Al matar al abuelo, creas una rama histórica alternativa sin afectar tu universo de origen","El tiempo se congela","El viajero desaparece"], a: 1 },
      { q: "¿En qué consiste la 'paradoja del conocimiento' del viaje en el tiempo?", options: ["Que nadie puede saber dónde está en el tiempo","La información existe en un bucle sin origen claro, como si alguien del futuro enseñara algo que ya aprendió del futuro","Que el viajero pierde la memoria","Que los libros del pasado son incorrectos"], a: 1 },
      { q: "¿Por qué la conjetura de protección de la cronología de Hawking afirma que las máquinas del tiempo se destruirían solas?", options: ["Por la radiación cósmica de fondo","Las fluctuaciones cuánticas se amplificarían hasta destruir el agujero de gusano","Por las paradojas del abuelo","Por las fuerzas de marea"], a: 1 }
    ]
  },
  wormhole_m14: {
    extra: [
      "Carl Sagan, el astrónomo y divulgador científico más famoso del siglo XX, escribió la novela 'Contacto' en 1985 (llevada al cine en 1997 con Jodie Foster). La novela presenta el primer contacto de la humanidad con una civilización extraterrestre que envía los planos para construir una 'máquina'.",
      "En 'Contacto', la máquina construida a partir de los planos extraterrestres resulta ser un vehículo que viaja a través de un agujero de gusano. Sagan era tan riguroso científicamente que consultó a Kip Thorne sobre los detalles físicos de los agujeros de gusano para hacer la novela lo más realista posible.",
      "Esta consulta de Sagan con Thorne fue el detonante que llevó a Thorne y a sus estudiantes a desarrollar la teoría matemática completa de los agujeros de gusano traversables. El artículo científico de Morris y Thorne de 1988 surgió directamente de la pregunta de Sagan: '¿Es posible un agujero de gusano físicamente?'",
      "Carl Sagan también es famoso por su serie de televisión 'Cosmos: Un viaje personal' (1980), que revolutionó la divulgación científica. Sagan podía hablar de los conceptos más abstractos de la astronomía y la física con claridad, emoción y rigor. Su lema era: 'Extraordinary claims require extraordinary evidence' (afirmaciones extraordinarias requieren evidencias extraordinarias).",
      "La filosofía científica de Sagan es una guía perfecta para pensar sobre los agujeros de gusano: podemos especular libremente mientras seamos honestos sobre qué es especulación y qué es conocimiento establecido. Los agujeros de gusano son especulación respaldada por matemáticas rigurosas, pero aún sin evidencia observacional directa.",
      "Sagan también desarrolló el concepto del 'Punto Azul Pálido': la fotografía de la Tierra tomada por la sonda Voyager 1 desde más allá de la órbita de Neptuno en 1990. La Tierra aparece como un punto azul diminuto en un rayo de luz solar. Sagan usó esta imagen para reflexionar sobre la fragilidad y la unicidad de nuestra civilización.",
      "La búsqueda de vida extraterrestre (SETI) fue una de las causas más importantes de Sagan. Si existieran civilizaciones avanzadas capaces de usar agujeros de gusano, ¿por qué no hemos detectado sus señales? Esta pregunta se conecta con la paradoja de Fermi: '¿Dónde están todos?'",
      "La paradoja de Fermi (formulada por el físico Enrico Fermi en 1950) pregunta: dado que el universo es tan vasto y antiguo, y que hay tantas estrellas similares al Sol con planetas similares a la Tierra, ¿por qué no hemos encontrado aún ninguna señal de vida inteligente extraterrestre?",
      "Una posible solución a la paradoja de Fermi relacionada con los agujeros de gusano: las civilizaciones avanzadas podrían no usar señales de radio (que viajan a la velocidad de la luz) sino sistemas de comunicación o transporte a través de agujeros de gusano que no emitirían señales detectables con nuestros instrumentos actuales.",
      "Otra solución: quizás la barrera tecnológica para crear agujeros de gusano es tan enorme que ninguna civilización, por avanzada que sea, puede superarla. En ese caso, las civilizaciones extraterrestres, por mucho que hayan avanzado, siguen siendo prisioneras de su sistema estelar igual que nosotros."
    ],
    quiz: [
      { q: "¿En qué año fue publicada la novela 'Contacto' de Carl Sagan?", options: ["1965","1975","1985","1995"], a: 2 },
      { q: "¿Quién es el asesor científico al que consultó Carl Sagan para la física de 'Contacto'?", options: ["Stephen Hawking","Richard Feynman","Kip Thorne","Neil deGrasse Tyson"], a: 2 },
      { q: "¿Qué es la paradoja de Fermi?", options: ["Por qué los agujeros negros tienen temperatura","Por qué la luz tiene velocidad constante","Si hay tantas estrellas con planetas, ¿por qué no hemos encontrado señales de vida inteligente?","Por qué el universo se expande"], a: 2 },
      { q: "¿Qué es el 'Punto Azul Pálido' de Sagan?", options: ["Un tipo de estrella enana","La fotografía de la Tierra desde más allá de Neptuno","Un cráter en la Luna","El nombre de la novela Contacto en inglés"], a: 1 },
      { q: "¿Cuál es el lema científico más famoso de Carl Sagan?", options: ["La ciencia es aburrida","Todo es posible con suficiente imaginación","Las afirmaciones extraordinarias requieren evidencias extraordinarias","Ver para creer"], a: 2 }
    ]
  },
  wormhole_m15: {
    extra: [
      "Carl Sagan tenía una visión del futuro humano que combinaba optimismo y cautela. Creía que la humanidad tenía el potencial de explorar la galaxia, comunicarse con civilizaciones extraterrestres y resolver sus problemas internos, pero también advertía sobre los peligros de la guerra nuclear, el cambio climático y el oscurantismo.",
      "En 'Contacto', el mensaje de los extraterrestres viene en forma de señales de radio. En la realidad, el proyecto SETI (Search for ExtraTerrestrial Intelligence) lleva décadas escuchando el cosmos buscando señales artificiales. Hasta ahora, el único candidato interesante fue la señal 'Wow!' detectada en 1977, pero nunca se repitió ni se confirmó su origen.",
      "La película 'Contact' (1997) dirigida por Robert Zemeckis y protagonizada por Jodie Foster como la astrónoma Ellie Arroway capturó perfectamente la esencia del libro: la tensión entre ciencia y fe, la búsqueda de significado en el universo, y la posibilidad de que no estemos solos. Fue la primera representación cinematográfica realista de un agujero de gusano.",
      "La representación del agujero de gusano en 'Contact' y en 'Interstellar' (2014) comparte una característica: ambas representan el viaje como una experiencia sensorial intensa y desorientadora, no como el simple cruce de una puerta. Esta intuición artística es compatible con lo que los físicos predicen que sería la experiencia de cruzar un agujero de gusano real.",
      "Kip Thorne, además de asesorar 'Contacto' e 'Interstellar', escribió el libro 'The Science of Interstellar' (La Ciencia de Interstellar, 2014), donde explica la física real detrás de cada elemento de la película. Es uno de los mejores puentes entre la física de vanguardia y el público general.",
      "La influencia de Carl Sagan en la cultura científica es enorme. Su serie 'Cosmos' fue revivida en 2014 y 2020 por Neil deGrasse Tyson, el astrofísico más famoso de la actualidad, quien también fue mentor de jóvenes científicos. La tradición de divulgación científica de Sagan continúa.",
      "La divulgación científica es fundamental para que la sociedad apoye la ciencia y entienda sus resultados. Los agujeros de gusano son un ejemplo perfecto: sin comunicadores como Sagan, Thorne o Tyson, estos conceptos permanecerían en artículos académicos inaccesibles y no inspirarían a las próximas generaciones de científicos.",
      "Tú, que estudias estos temas en este curso, eres parte de esa cadena de curiosidad científica que va de Einstein a Wheeler, de Wheeler a Thorne, de Thorne a Sagan, y que llega hasta aquí, hasta tu pantalla. La ciencia no es solo conocimiento: es una manera de mirar el mundo con asombro y rigor.",
      "Los agujeros de gusano pueden ser reales o no. Pero el proceso de imaginarlos, formularlos matemáticamente, buscar maneras de detectarlos y comunicar esas ideas al mundo es un ejemplo perfecto del método científico: imaginación guiada por la razón, restringida por la evidencia, y compartida con la humanidad.",
      "Quizás en el futuro, cuando los humanos hayan llegado a las estrellas (por agujeros de gusano o por otros medios), mirarán atrás a este período en el que comenzamos a imaginar cómo hacerlo, y verán a Sagan, Thorne, Wheeler y Einstein como los primeros exploradores de un universo que, con suerte, aprenderemos a cruzar."
    ],
    quiz: [
      { q: "¿Qué es la señal 'Wow!' detectada en 1977?", options: ["Una señal de un volcán marciano","El único candidato serio de señal extraterrestre detectado por SETI, nunca confirmado","La primera señal de ondas gravitacionales","La señal del satélite Sputnik"], a: 1 },
      { q: "¿Quién protagonizó la película 'Contact' de 1997?", options: ["Sigourney Weaver","Sandra Bullock","Jodie Foster","Natalie Portman"], a: 2 },
      { q: "¿Qué libro escribió Kip Thorne sobre la física de Interstellar?", options: ["Agujeros Negros y Tiempo Curvado","La Ciencia de Interstellar","El Universo en una Cáscara de Nuez","Contacto"], a: 1 },
      { q: "¿Quién revivió la serie Cosmos de Sagan en 2014?", options: ["Stephen Hawking","Richard Feynman","Brian Greene","Neil deGrasse Tyson"], a: 3 },
      { q: "¿Cuál es el mensaje principal que une a Sagan, Thorne y la física de los agujeros de gusano?", options: ["Solo los genios pueden hacer ciencia","La ciencia es inútil sin tecnología","La imaginación guiada por la razón, restringida por la evidencia, y compartida con la humanidad","Los agujeros de gusano son imposibles"], a: 2 }
    ]
  }
};

for (const [moduleId, data] of Object.entries(WORMHOLE)) {
  src = patchModule(src, moduleId, data.extra, data.quiz);
}

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ Wormhole (m1-m15) all patched!');
