/**
 * patch_interstellar.js — Patches interstellar_m1 through interstellar_m5
 * Uses the universal patcher from patch_universal.js
 * These modules have 1-4 paragraphs, need full replacement to 15.
 */
const fs = require('fs');
const path = require('path');
const { replaceTextAndQuiz, getModuleChunk } = require('./patch_universal');
const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

const INTERSTELLAR = {
  interstellar_m1: {
    text: [
      "Albert Einstein publicó en 1915 su Teoría de la Relatividad General, una de las ideas más revolucionarias en la historia de la ciencia. Antes de Einstein, la gravedad se entendía como una fuerza que los objetos ejercen unos sobre otros a distancia. Einstein cambió completamente esta visión.",
      "Para Einstein, la gravedad no es una fuerza sino una curvatura del espacio-tiempo. El espacio y el tiempo no son fondos fijos e independientes donde ocurren los fenómenos: son una entidad dinámica, el 'tejido del espacio-tiempo', que puede curvarse, estirarse y ondularse.",
      "Imagina que el espacio-tiempo es como una tela de goma extendida. Si colocas una bola de boliche (una estrella masiva) sobre ella, la tela se hunde y se curva. Una canica que pase cerca seguirá la curvatura y se moverá en órbita alrededor de la bola, no porque sea 'atraída', sino porque sigue la curva más natural del espacio-tiempo.",
      "Esta geometría del espacio-tiempo fue verificada en 1919 cuando Arthur Eddington observó durante un eclipse solar que la luz de estrellas distantes se curvaba al pasar cerca del Sol, exactamente como predecía Einstein. Esta prueba convirtió a Einstein en una celebridad mundial de la noche a la mañana.",
      "La relatividad general predice cosas extraordinarias: agujeros negros, ondas gravitacionales, la expansión del universo, y la dilatación del tiempo cerca de objetos muy masivos. Todas estas predicciones han sido verificadas experimentalmente con gran precisión en el siglo transcurrido desde que Einstein publicó su teoría.",
      "La dilatación del tiempo gravitacional es uno de los efectos más sorprendentes: el tiempo pasa más lento en lugares con mayor gravedad. Un reloj en la Tierra va ligeramente más lento que uno en un satélite (donde la gravedad es menor). Esta diferencia es tan real y medible que los sistemas GPS deben corregirla para funcionar con precisión.",
      "La película 'Interstellar' (2014) usa estos conceptos de manera magistral. La dilatación temporal cerca del agujero negro Gargantúa hace que los astronautas que visitan un planeta cercano envejezcan mucho más lento que sus colegas en la nave. Una hora en ese planeta equivale a siete años en el exterior.",
      "Kip Thorne, el físico que asesoró la película, ganó el Premio Nobel de Física en 2017 junto con Barry Barish y Rainer Weiss por la detección de ondas gravitacionales. Su trabajo no solo revolucionó la física, sino que también inspiró una de las películas de ciencia ficción más rigurosas de la historia.",
      "Las ondas gravitacionales son perturbaciones en el tejido del espacio-tiempo causadas por eventos catastróficos: la fusión de dos agujeros negros, la explosión de una estrella gigante, o incluso el Big Bang. Viajan a la velocidad de la luz y estiran y comprimen el espacio-tiempo a su paso.",
      "El detector LIGO (Laser Interferometer Gravitational-Wave Observatory) usó dos rayos láser perpendiculares para medir cambios en la longitud de sus brazos de 4 kilómetros con una precisión de 10⁻¹⁸ metros (mil veces más pequeño que un protón). El 14 de septiembre de 2015, detectó las ondas gravitacionales de la fusión de dos agujeros negros a 1,300 millones de años luz de distancia.",
      "La relatividad general también predice que el universo no puede ser estático: debe estar expandiéndose o contrayéndose. Edwin Hubble confirmó en 1929 que el universo se expande: las galaxias se alejan de nosotros y cuanto más lejos están, más rápido se alejan. Esto implica que el universo comenzó en un estado extremadamente caliente y denso: el Big Bang.",
      "La expansión del universo es acelerada, lo que se descubrió en 1998. Algo está empujando el universo a expandirse cada vez más rápido. Ese algo se llama 'energía oscura' y representa el 68% de la energía total del universo. La materia oscura representa otro 27%. Solo el 5% del universo es la materia normal que vemos.",
      "La red de gravedad invisible que menciona el título de este módulo es la trama del espacio-tiempo que conecta todo el universo. Es invisible porque no la vemos directamente, pero la experimentamos constantemente: es la razón por la que caes al suelo, por la que la Luna orbita la Tierra, por la que las galaxias forman cúmulos.",
      "La relatividad general es la base de toda la cosmología moderna: el estudio del universo a gran escala. Sin ella, no podríamos entender los agujeros negros, la expansión del universo, las ondas gravitacionales, ni los mapas de la materia oscura. Es la teoría más precisa y más bien verificada de la física.",
      "Para los estudiantes de hoy, la relatividad general no es solo historia de la ciencia. Es la herramienta que los astrónomos y cosmólogos usan cada día para interpretar los datos de los telescopios más poderosos del mundo, incluyendo el telescopio espacial James Webb que explora el universo en luz infrarroja hasta el borde mismo del tiempo observable."
    ],
    quiz: [
      { q: "Según Einstein, ¿qué es la gravedad?", options: ["Una fuerza entre objetos","Una curvatura del espacio-tiempo","Una onda electromagnética","Una propiedad de los electrones"], a: 1 },
      { q: "¿Qué observó Arthur Eddington en 1919 que verificó la relatividad general?", options: ["Las ondas gravitacionales","La expansión del universo","La luz de estrellas se curva al pasar cerca del Sol","Los agujeros negros existen"], a: 2 },
      { q: "¿Qué detectó el instrumento LIGO el 14 de septiembre de 2015?", options: ["Un agujero de gusano","Un planeta extrasolar","Ondas gravitacionales de dos agujeros negros fusionándose","La materia oscura"], a: 2 },
      { q: "¿Qué porcentaje del universo es la materia y energía 'normales' que podemos ver?", options: ["5%","27%","68%","95%"], a: 0 },
      { q: "¿Cuánto equivale 1 hora cerca de Gargantúa en 'Interstellar' en el exterior?", options: ["1 día","1 semana","7 años","100 años"], a: 2 }
    ]
  },
  interstellar_m2: {
    text: [
      "Gargantúa es el agujero negro que aparece en la película 'Interstellar' (2014). Es un agujero negro supermasivo con rotación, diseñado en colaboración con el físico Kip Thorne para ser la representación más realista de un agujero negro jamás mostrada en una película.",
      "Para crear las imágenes de Gargantúa, el equipo de efectos especiales de Double Negative trabajó con Kip Thorne para desarrollar un nuevo código de trazado de rayos (ray-tracing) que simulara con precisión cómo se vería la luz alrededor de un agujero negro en rotación. El resultado fue tan preciso que generó datos científicos reales.",
      "Un agujero negro en rotación (tipo Kerr) se diferencia de uno estático (tipo Schwarzschild) en que el espacio-tiempo en su entorno es arrastrado en la dirección de rotación. Esto se llama 'arrastre de marcos' o 'efecto Lense-Thirring'. Cerca de la singularidad, el espacio-tiempo rota tan rápido que es imposible permanecer quieto.",
      "Gargantúa tiene una masa de 100 millones de soles y rota casi al máximo posible (al 99.8% de la velocidad máxima de rotación permitida por la relatividad general). Esta rotación extrema es lo que permite que el planeta Miller (que orbita muy cerca) sea estable a pesar de estar tan cerca del horizonte de eventos.",
      "El disco de acreción de Gargantúa es el material caliente que orbita el agujero negro y brilla intensamente. En la película aparece como un disco plano y brillante con un toro de luz por encima y por debajo. Esta forma, que parece extraña, es en realidad la predicción correcta: la curvatura del espacio-tiempo dobla la luz del disco que está 'detrás' del agujero negro hacia adelante.",
      "La temperatura del disco de acreción de un agujero negro real podría alcanzar millones de grados, emitiendo principalmente rayos X. Gargantúa en la película tiene un disco más frío de lo que sería realista para no matar a los astronautas con radiación. Esta fue una de las libertades artísticas conscientes tomadas por Thorne.",
      "El radio del horizonte de eventos de Gargantúa sería de unos 300 millones de kilómetros, aproximadamente dos veces la distancia de la Tierra al Sol. Un horizonte de eventos tan grande significa que la densidad promedio del agujero negro sería solo un poco mayor que la del agua: la singularidad está muy lejos del horizonte.",
      "Para un observador externo, cualquier objeto que caiga hacia el horizonte de Gargantúa parecería ralentizarse infinitamente y su luz se volvería cada vez más roja (corrimiento al rojo gravitacional) hasta desvanecerse. Nunca parecería cruzar el horizonte, aunque en su propio tiempo de referencia lo cruzaría sin notar nada especial.",
      "La ergosfera de un agujero negro de Kerr como Gargantúa es una región fuera del horizonte de eventos donde el arrastre de marcos es tan intenso que nada puede permanecer quieto. El espacio-tiempo mismo está en rotación. Los objetos en la ergosfera pueden extraer energía del agujero negro (proceso de Penrose) y salir con más energía de la que entraron.",
      "En 'Interstellar', la nave Endurance orbita Gargantúa a una distancia segura mientras los astronautas visitan los planetas cercanos. Esta órbita sería posible gracias a que la rotación extrema de Gargantúa crea regiones de espacio-tiempo estable que no existirían alrededor de un agujero negro sin rotación.",
      "Kip Thorne publicó los datos científicos derivados de la simulación de Gargantúa en dos artículos académicos en 2015. Descubrió que las simulaciones revelaban nuevas comprensiones sobre cómo se vería la luz alrededor de un agujero negro de Kerr en rotación rápida, especialmente los efectos de su luminosidad en la imagen del disco de acreción.",
      "El agujero negro real más parecido a Gargantúa que conocemos es M87*, fotografiado por el Telescopio del Horizonte de Sucesos (EHT) en 2019. Tiene 6,500 millones de veces la masa del Sol y está a 55 millones de años luz de distancia en la galaxia M87. La imagen mostró claramente la sombra del horizonte de eventos y el disco de acreción.",
      "Sagitario A*, el agujero negro en el centro de nuestra Vía Láctea, fue fotografiado por el EHT en 2022. Tiene 'solo' 4 millones de masas solares y está a 27,000 años luz de nosotros. A pesar de ser mucho más cercano que M87*, fue más difícil fotografiar porque el material a su alrededor orbita más rápidamente.",
      "Las imágenes del EHT son prueba directa de que los agujeros negros no son solo soluciones matemáticas, sino objetos físicos reales que existen en el universo. La concordancia entre las imágenes observadas y las predicciones de la relatividad general es sorprendente y refuerza nuestra confianza en la teoría de Einstein.",
      "Para los estudiantes de hoy, los agujeros negros como Gargantúa son ventanas hacia los fenómenos más extremos del universo. Estudiarlos no solo satisface la curiosidad, sino que prueba la física en condiciones donde ningún otro laboratorio del universo podría hacerlo. Son los aceleradores de partículas naturales más poderosos que existen."
    ],
    quiz: [
      { q: "¿Cuántas veces la masa del Sol tiene Gargantúa en 'Interstellar'?", options: ["1 millón","10 millones","100 millones","1,000 millones"], a: 2 },
      { q: "¿Cómo se llama el efecto de que el espacio-tiempo es arrastrado en rotación por un agujero negro?", options: ["Radiación de Hawking","Efecto Casimir","Arrastre de marcos o efecto Lense-Thirring","Corrimiento al rojo gravitacional"], a: 2 },
      { q: "¿Qué es el disco de acreción de un agujero negro?", options: ["El propio agujero negro","Material caliente que orbita el agujero negro y brilla","La región de sombra alrededor del agujero negro","El horizonte de eventos"], a: 1 },
      { q: "¿Cuál fue el primer agujero negro fotografiado directamente, en 2019?", options: ["Sagitario A*","Gargantúa","M87*","Cygnus X-1"], a: 2 },
      { q: "¿Qué es la ergosfera de un agujero negro en rotación?", options: ["La región dentro del horizonte de eventos","Una región fuera del horizonte donde nada puede permanecer quieto","El disco de acreción brillante","La zona de los polos del agujero negro"], a: 1 }
    ]
  },
  interstellar_m3: {
    text: [
      "La dilatación del tiempo es uno de los efectos más extraordinarios y contraintuitivos de la relatividad de Einstein. Significa que el tiempo no transcurre a la misma velocidad para todos los observadores: depende de su velocidad y de la intensidad del campo gravitacional donde se encuentran.",
      "La dilatación temporal por velocidad (relatividad especial): cuanto más rápido se mueve un objeto, más lento transcurre el tiempo para él en comparación con un objeto en reposo. Si viajaras al 99.5% de la velocidad de la luz, el tiempo pasaría para ti unas 10 veces más lento que para alguien en la Tierra.",
      "La dilatación temporal gravitacional (relatividad general): cuanto más fuerte es el campo gravitacional, más lento transcurre el tiempo. Un reloj colocado en la superficie de la Tierra va más lento que uno en el espacio donde la gravedad es menor. Esta diferencia es minúscula pero medible con relojes atómicos modernos.",
      "Ambos tipos de dilatación temporal son reales y han sido medidos directamente. Los satélites GPS orbitan la Tierra a 20,200 kilómetros de altura y a 14,000 km/h. La velocidad ralentiza sus relojes (efecto especial) y la menor gravedad los acelera (efecto general). Sin corregir estos efectos, el GPS acumularía errores de 10 km/día.",
      "En 'Interstellar', la dilatación temporal cerca de Gargantúa es extrema porque la rotación del agujero negro maximiza el efecto. El planeta Miller orbita a solo 1.3 veces el radio del horizonte de eventos. En esas condiciones, 1 hora en el planeta = 7 años en el exterior, como demuestra el drama de la tripulación al regresar.",
      "El factor de dilatación de 7 años por hora es enorme pero físicamente plausible para una órbita tan cercana a un agujero negro supermasivo en rotación rápida. Kip Thorne calculó que se necesita una rotación de Gargantúa al 99.8% del máximo para lograr este factor. La película es científicamente correcta en este punto.",
      "Para los astronautas en el planeta Miller, el tiempo transcurre normalmente. No sienten que el tiempo pase lento. Solo cuando regresan a la nave (donde el tiempo pasa mucho más rápido) se dan cuenta del drama: su colega Brand ha envejecido 23 años mientras ellos estuvieron solo unas pocas horas en el planeta.",
      "La dilatación temporal también implica que, en principio, viajar al futuro es posible. Si pudieras colocarte durante un año en una órbita muy cercana a Gargantúa (donde el tiempo va mucho más lento), al regresar podrías haber 'saltado' al futuro en el tiempo del universo exterior.",
      "Esto no es ciencia ficción: los astronautas de la Estación Espacial Internacional (ISS), que orbitan a 7.7 km/s, experimentan una pequeña dilatación temporal. Después de 6 meses en la ISS, un astronauta ha 'envejecido' unos 0.01 segundos menos que alguien en la Tierra. Es real pero minúsculo.",
      "Viaje al pasado sería radicalmente diferente. Ninguna teoría física actualmente aceptada permite el viaje al pasado de manera directa (solo a través de construcciones teóricas como los agujeros de gusano). El viaje al futuro, en cambio, es no solo posible sino inevitable para objetos que se mueven o están en campos gravitacionales.",
      "La dilatación temporal también afecta a los muones cósmicos. Los muones son partículas subatómicas que se crean cuando los rayos cósmicos chocan con la atmósfera superior a 15 km de altura. Su vida media es de solo 2.2 microsegundos: deberían desintegrarse antes de llegar al suelo. Pero como viajan al 99.9% de la velocidad de la luz, su tiempo se dilata y sobreviven hasta llegar al suelo.",
      "Detectamos muones cósmicos a nivel del suelo constantemente. Son evidencia directa de la dilatación temporal relativista. Sin este efecto, los detectores no los verían. Es una de las pruebas más elegantes y accesibles de la relatividad especial.",
      "La dilatación temporal también cambia nuestra comprensión del envejecimiento en el espacio. Los astronautas que viajan en cohetes rápidos envejecen más lento que los que se quedan en la Tierra. Si algún día enviamos personas en viajes interestelares a velocidades relativistas, los viajeros regresarían jóvenes mientras la Tierra habría envejecido siglos.",
      "Esta asimetría del tiempo (los 'viajeros' envejecen menos que los 'sedentarios') se llama la paradoja de los gemelos. Si uno de dos gemelos viaja a una estrella cercana al 90% de la velocidad de la luz y regresa, habrá envejecido menos que su hermano. No es paradoja real: hay una asimetría física real porque el viajero aceleró y desaceleró.",
      "La dilatación del tiempo es uno de los pilares de la física moderna. Sin entenderla, no podemos entender la cosmología, los agujeros negros, las partículas relativistas, ni el funcionamiento del GPS. Einstein nos regaló una comprensión del tiempo radicalmente diferente a la intuición cotidiana, y el universo le ha dado la razón con cada experimento."
    ],
    quiz: [
      { q: "¿Qué causa la dilatación temporal gravitacional?", options: ["El movimiento rápido","La menor densidad del aire","El campo gravitacional más fuerte hace que el tiempo pase más lento","La temperatura extrema"], a: 2 },
      { q: "¿Cuánto equivale 1 hora en el planeta Miller de Interstellar?", options: ["1 día","1 semana","7 años","100 años"], a: 2 },
      { q: "¿Por qué los muones cósmicos llegan al suelo terrestre a pesar de su corta vida media?", options: ["Son más densos que los protones","Viajan bajo tierra","La dilatación temporal por su alta velocidad alarga su vida media observada","Son producidos a baja altitud"], a: 2 },
      { q: "¿Por qué los satélites GPS necesitan corregir la dilatación temporal?", options: ["Para ahorrar energía","Sin corrección acumularían errores de 10 km/día","Para mejorar la señal de radio","Por la rotación de la Tierra"], a: 1 },
      { q: "¿En qué consiste la paradoja de los gemelos?", options: ["Que los gemelos siempre tienen la misma edad","El viajero relativista envejece menos que el sedentario por la asimetría real del movimiento","Que los gemelos se confunden en el espacio","Que el espacio tiene dos tiempos"], a: 1 }
    ]
  },
  interstellar_m4: {
    text: [
      "En la física teórica, un agujero de gusano es una solución matemática a las ecuaciones de la relatividad general que describe un 'túnel' en el espacio-tiempo que conecta dos regiones separadas del universo. La idea fue formulada por primera vez por Einstein y Rosen en 1935.",
      "Para entender los agujeros de gusano, necesitas imaginar el espacio-tiempo como una superficie bidimensional (como una hoja de papel) en lugar de cuatro dimensiones. Si doblas esa hoja de papel de manera que dos puntos distantes se aproximen, un agujero a través del papel (perpendicular a él) sería el agujero de gusano.",
      "La clave es que el 'atajo' a través del agujero de gusano sería mucho más corto que el camino sobre la superficie del papel. En el universo real (cuatro dimensiones de espacio-tiempo), el agujero de gusano sería un atajo a través de una 'quinta dimensión' hipotética que el espacio-tiempo podría doblar.",
      "Kip Thorne y Michael Morris describieron en 1988 el primer agujero de gusano matemáticamente atravesable. A diferencia del agujero de gusano de Einstein-Rosen (que colapsa instantáneamente), el de Morris-Thorne podría permanecer abierto si se lo 'sostiene' con materia exótica de energía negativa.",
      "En 'Interstellar', el agujero de gusano aparece cerca de Saturno como una esfera perfecta y transparente, no como un túnel plano. Esta representación es más precisa que la habitual: en tres dimensiones, la boca de un agujero de gusano sería una esfera, no un círculo, porque el espacio tiene tres dimensiones.",
      "El agujero de gusano en 'Interstellar' fue colocado por seres de una 'quinta dimensión' (hipotéticamente, seres que existen en más dimensiones que nosotros). Esta idea está basada en especulaciones reales de la física: si existen dimensiones extra del espacio, seres que las habitaran podrían doblar el espacio-tiempo de maneras que nosotros no podemos.",
      "Las dimensiones extra son una predicción de la teoría de cuerdas. Si el universo tiene 10 o 11 dimensiones en lugar de 4, las dimensiones extra están 'compactificadas': enrolladas a escalas de Planck y por eso invisibles para nosotros. Sin embargo, la gravedad podría 'filtrarse' hacia esas dimensiones extra.",
      "Si la gravedad se filtra hacia dimensiones extra, se volvería más débil a largas distancias de lo que predice la relatividad general estándar. Algunos experimentos de precisión buscan desviaciones de la ley de la gravedad a escalas de milímetros o menos. Hasta ahora, no se han encontrado desviaciones.",
      "Los agujeros de gusano también podrían usarse como canales de comunicación. Si pudieras abrir un agujero de gusano entre la Tierra y una estrella a 100 años luz de distancia, podrías enviar un mensaje que llegara casi instantáneamente. Esto revolucionaría la comunicación interestelar sin necesitar velocidades superluminales.",
      "Sin embargo, abrir un agujero de gusano requeriría una cantidad colosal de energía. Algunas estimaciones sugieren que necesitarías concentrar una energía comparable a la de una estrella entera solo para abrir un agujero de gusano del tamaño suficiente para que pase un ser humano. Con la tecnología actual, esto es completamente imposible.",
      "El problema de la materia exótica es el obstáculo principal. La materia exótica con energía negativa existe en principio (el efecto Casimir demuestra que hay regiones de energía negativa en el vacío cuántico), pero en cantidades infinitesimalmente pequeñas. Amplificarla a la escala necesaria para un agujero de gusano no tiene solución conocida.",
      "Algunos físicos como Pedro González-Díaz y sus colaboradores han explorado 'agujeros de gusano de fantasma' (ghost wormholes) que usarían energía de la expansión acelerada del universo (energía oscura) en lugar de materia exótica. Estas ideas son especulativas pero matemáticamente consistentes.",
      "Otro enfoque es el de los 'agujeros de gusano cuánticos': en la espuma cuántica del espacio-tiempo a escala de Planck, los micro agujeros de gusano se formarían y colapsarían espontáneamente. Si pudiéramos ampliar y estabilizar uno de estos micro agujeros de gusano, tendríamos un agujero de gusano macroscópico sin necesidad de crearlo de la nada.",
      "La idea de ampliar micro agujeros de gusano cuánticos es tan teórica que no hay ningún mecanismo físico conocido para hacerlo. Pero como principio, no está prohibida por ninguna ley fundamental de la física. Podría ser que una civilización suficientemente avanzada (de tipo III en la escala de Kardashev) pudiera encontrar la manera.",
      "La escala de Kardashev clasifica las civilizaciones por su uso de energía: Tipo I usa toda la energía disponible en su planeta, Tipo II usa toda la energía de su estrella, y Tipo III usa toda la energía de su galaxia. Los humanos somos actualmente una civilización de Tipo 0.7 aproximadamente. Una civilización de Tipo III podría, quizás, tener la energía para crear agujeros de gusano."
    ],
    quiz: [
      { q: "¿Qué forma tendría la boca de un agujero de gusano en el espacio tridimensional?", options: ["Un círculo","Un túnel recto","Una esfera","Un cubo"], a: 2 },
      { q: "¿Qué tipo de materia se necesita para mantener abierto un agujero de gusano traversable?", options: ["Antimateria","Materia oscura","Materia exótica con energía negativa","Neutrones comprimidos"], a: 2 },
      { q: "¿Qué es la escala de Kardashev?", options: ["La escala de temperatura de los agujeros negros","Una clasificación de civilizaciones por su uso de energía","La distancia en años luz a las estrellas cercanas","La escala de magnitud de los agujeros de gusano"], a: 1 },
      { q: "¿Dónde aparece el agujero de gusano en 'Interstellar'?", options: ["Cerca de Júpiter","Entre Marte y la Tierra","Cerca de Saturno","En el borde del sistema solar"], a: 2 },
      { q: "¿Por qué los 'micro agujeros de gusano cuánticos' son importantes teóricamente?", options: ["Porque ya los hemos creado en laboratorio","Podrían ser la semilla de agujeros de gusano macroscópicos si pudiéramos ampliarlos","Porque refutan la relatividad general","Porque son la principal fuente de energía del universo"], a: 1 }
    ]
  },
  interstellar_m5: {
    text: [
      "El teseracto es un cubo de cuatro dimensiones espaciales, también llamado hipercubo. Así como un cubo es la versión 3D de un cuadrado, el teseracto es la versión 4D de un cubo. Si pudiéramos 'desplegar' un teseracto en tres dimensiones, se vería como una serie de cubos conectados de manera aparentemente imposible.",
      "En la película 'Interstellar', el teseracto es una estructura construida por seres de una quinta dimensión para que el astronauta Cooper pueda interactuar con el tiempo de una manera imposible en el espacio-tiempo normal. Dentro del teseracto, el tiempo aparece como una dimensión espacial que se puede atravesar.",
      "La idea de que el tiempo podría ser 'espacializado' y tratado como una dimensión que se puede recorrer en cualquier dirección (pasado y futuro) es una especulación que surge de la relatividad general. En el espacio-tiempo de Einstein, el tiempo y el espacio son aspectos de la misma entidad, pero el tiempo no es una dimensión 'libre': siempre avanza hacia el futuro.",
      "En física, el 'bloque del universo' es una visión del espacio-tiempo donde todo el pasado, presente y futuro coexiste simultáneamente como un bloque cuadridimensional estático. En esta visión, el tiempo no 'fluye': solo nuestra conciencia se mueve a través de él. El teseracto de 'Interstellar' visualiza este concepto de manera narrativa.",
      "La quinta dimensión hipotética de 'Interstellar' (habitada por los seres que construyeron el teseracto) podría ser una de las dimensiones extra predichas por la teoría de cuerdas. Si estas dimensiones existen, seres que las habitaran podrían ver y manipular nuestro espacio-tiempo de la misma manera que nosotros podemos ver y manipular un dibujo bidimensional.",
      "Un ser bidimensional en una superficie plana no puede ver 'arriba'. Si alguien en tres dimensiones coloca un objeto encima de la superficie, el ser 2D no lo detectaría hasta que ese objeto 'chocara' con su plano. Análogamente, nosotros no podemos 'ver' una quinta dimensión si existe, pero podría afectarnos de maneras indirectas.",
      "La gravedad podría ser una de esas maneras indirectas. La teoría de Randall-Sundrum (2000) propone que el universo que conocemos es una 'brana' (membrana) tridimensional sumergida en un espacio de dimensiones superiores. La gravedad sería la única fuerza que se 'filtra' hacia las dimensiones extra, lo que explicaría por qué la gravedad es tan débil comparada con las otras fuerzas.",
      "La debilidad relativa de la gravedad es un misterio fundamental de la física. La fuerza electromagnética es 10³⁶ veces más fuerte que la gravedad a las mismas distancias. Si la gravedad se 'diluye' en dimensiones extra, eso explicaría su debilidad sin necesitar una explicación ad hoc.",
      "En 'Interstellar', la gravedad es el mecanismo por el que Cooper puede enviar mensajes al pasado desde dentro del teseracto. Manipula los objetos en la habitación de su hija a través de la quinta dimensión gravitacional. Esto es poético pero también está basado en la física real: la gravedad podría ser la única fuerza que traverse todas las dimensiones.",
      "El concepto de información transmitida al pasado en 'Interstellar' es la parte más especulativa de la película. Enviar información al pasado requeriría violar la causalidad, lo cual está prohibido por la relatividad especial estándar. Kip Thorne mismo admitió que esta parte de la película cruza la frontera de la física establecida hacia la especulación.",
      "Sin embargo, la especulación científica es fundamental para el progreso. Muchas de las ideas más revolucionarias de la física comenzaron como especulaciones que desafiaban el conocimiento establecido: la relatividad, la mecánica cuántica, los agujeros negros. La pregunta de qué pasaría si existiera una quinta dimensión que permita manipular el tiempo es una especulación fértil.",
      "Los estudiantes que estudian estos temas hoy podrían ser los físicos que en 50 años resuelvan las preguntas que 'Interstellar' plantea. La película no es un manual de física, pero es una invitación a hacerse preguntas que los mejores físicos del mundo se están haciendo ahora mismo.",
      "El legado científico de 'Interstellar' va más allá del entretenimiento. Los artículos científicos que Kip Thorne publicó basados en las simulaciones de Gargantúa revelaron nueva física. Las discusiones que la película generó en el público general sobre agujeros negros, dilatación temporal y dimensiones extra aumentaron el interés en la física entre una generación entera.",
      "La divulgación científica a través del cine, la literatura y el arte es una de las herramientas más poderosas para inspirar a futuras generaciones de científicos. Sagan, Thorne, Hawking y muchos otros físicos entendieron esto y dedicaron parte de su vida a comunicar la ciencia al público general con rigor y pasión.",
      "El universo es un lugar de una complejidad, belleza y misterio inmensos. Los agujeros negros como Gargantúa, los agujeros de gusano, la dilatación del tiempo, el teseracto y las dimensiones extra son solo algunas de las facetas de ese misterio que la física nos ha permitido explorar. Cada respuesta abre nuevas preguntas. Esa es la esencia de la ciencia."
    ],
    quiz: [
      { q: "¿Qué es un teseracto?", options: ["Un agujero negro de cuatro dimensiones","Un hipercubo: el equivalente 4D de un cubo","Una unidad de medida astronómica","El nombre del agujero de gusano en Interstellar"], a: 1 },
      { q: "¿Qué es el 'bloque del universo' en física?", options: ["Una estructura galáctica","Una visión donde todo el pasado, presente y futuro coexiste como un bloque estático cuadridimensional","El universo observable","La materia oscura comprimida"], a: 1 },
      { q: "¿Qué propone la teoría de Randall-Sundrum sobre las dimensiones extra?", options: ["Que el universo tiene solo 3 dimensiones","Que nuestro universo es una 'brana' en un espacio de dimensiones superiores, y la gravedad se filtra hacia ellas","Que el tiempo es una ilusión","Que hay universos paralelos sin gravedad"], a: 1 },
      { q: "¿Cuántas veces más fuerte que la gravedad es la fuerza electromagnética?", options: ["10 veces","1,000 veces","10⁶ veces","10³⁶ veces"], a: 3 },
      { q: "¿Cuál es la parte más especulativa de Interstellar según el propio Kip Thorne?", options: ["La existencia de agujeros negros","La dilatación temporal","La transmisión de información al pasado","El agujero de gusano cerca de Saturno"], a: 2 }
    ]
  }
};

for (const [moduleId, data] of Object.entries(INTERSTELLAR)) {
  src = replaceTextAndQuiz(src, moduleId, data.text, data.quiz);
}

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ Interstellar (m1-m5) all patched!');
