const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'lib', 'courseData.js');
let raw = fs.readFileSync(filePath, 'utf8');
let data = JSON.parse(raw.replace(/^export default /, '').replace(/;$/, ''));

const bttf_m6 = [
  "¡Bienvenido al almanaque deportivo del futuro, explorador de predicciones! En Volver al Futuro II, el malvado Biff Tannen usa un almanaque deportivo del futuro para apostar con conocimiento anticipado de los resultados. Esta idea es una variación de una pregunta científica profunda: ¿puede el futuro predecirse? ¿Es el universo determinista, con cada evento causado inevitablemente por los anteriores, o hay aleatoriedad fundamental en la naturaleza? La mecánica cuántica, la teoría del caos y las computadoras de predicción nos dan respuestas fascinantes y a veces sorprendentes. ¡El futuro te espera para ser explorado! 🔮",
  "El determinismo es la idea filosófica de que si conocieras la posición y velocidad exactas de todas las partículas del universo en un momento dado, podrías predecir perfectamente todo lo que ocurrirá en el futuro. Esta idea fue formulada por el matemático francés Pierre-Simon Laplace en 1814: imaginó a un demonio (el Demonio de Laplace) con ese conocimiento infinito y capacidad infinita de cálculo (Laplace, 1814). La mecánica clásica de Newton apoyaba completamente el determinismo. Pero la mecánica cuántica, descubierta en el siglo XX, destruyó este sueño determinista: el Principio de Incertidumbre de Heisenberg muestra que es físicamente imposible conocer simultáneamente la posición y el momento exactos de una partícula. ¡El universo tiene aleatoriedad fundamental incorporada!",
  "El Principio de Incertidumbre de Heisenberg, formulado en 1927, establece que el producto de las incertidumbres en la posición y el momento de una partícula nunca puede ser menor que ℏ/2 (donde ℏ es la constante de Planck reducida, 1.054×10⁻³⁴ J·s) (Heisenberg, 1927). Esto no es un límite de la tecnología de medición: es una propiedad fundamental de la naturaleza. Las partículas subatómicas genuinamente no tienen posición y velocidad exactas simultáneamente. La desintegración radiactiva de un núcleo atómico es completamente aleatoria: no hay ninguna causa que determine cuándo exactamente ocurrirá, solo una probabilidad por unidad de tiempo. ¡El Demonio de Laplace es imposible en principio, no solo en práctica!",
  "La teoría del caos estudia sistemas deterministas (que siguen leyes exactas) pero cuyo comportamiento es imposible de predecir a largo plazo porque son extremadamente sensibles a las condiciones iniciales. El meteorólogo Edward Lorenz descubrió este efecto en 1961 cuando simuló un modelo climático en computadora y encontró que pequeñísimas diferencias en los datos iniciales producían pronósticos completamente diferentes después de varias semanas (Lorenz, 1963). Llamó a esto el Efecto Mariposa: el aleteo de una mariposa en Brasil podría desencadenar un tornado en Texas. Esta sensibilidad a las condiciones iniciales hace que el pronóstico del tiempo tenga un límite fundamental de alrededor de dos semanas, independientemente de la potencia de los computadores (European Centre for Medium-Range Weather Forecasts).",
  "Los sistemas de predicción deportiva usan estadística, análisis de datos masivos (big data) y aprendizaje automático para hacer pronósticos probabilísticos. La empresa Opta Sports recopila miles de datos por partido de fútbol y los usa para calcular probabilidades de resultado que los bookmakers usan en sus apuestas (Opta Sports, 2023). Los modelos de predicción de la NBA de ESPN utilizan redes neuronales entrenadas en datos de decenas de años. Sin embargo, incluso los mejores modelos tienen tasas de error significativas porque el rendimiento humano individual tiene componentes impredecibles que los modelos no capturan completamente. ¡El almanaque de Biff nunca podría ser perfecto ni en el futuro porque el caos siempre gana!",
  "La predicción del clima global a largo plazo es uno de los mayores retos computacionales de la ciencia. Los modelos climáticos del IPCC corren en supercomputadoras que simulan la atmósfera, los océanos, los hielos y la biósfera con resoluciones de decenas de kilómetros. El supercomputador europeo de predicción meteorológica (ECMWF) en Reading, Reino Unido, realiza 270 billones de operaciones por segundo para producir pronósticos de 10 días (ECMWF, 2023). Sin embargo, más allá de 2 semanas, la atmósfera caótica hace que cualquier pronóstico específico sea imposible, aunque las tendencias climáticas a escala de décadas sí son predecibles porque se basan en forzamientos físicos como los gases de efecto invernadero (IPCC, 2021). ¡Hay predicciones posibles e imposibles, y la diferencia la marca el caos!",
  "Los mercados financieros son otro sistema que muchos sueñan con predecir perfectamente, como el almanaque de Biff. La Hipótesis del Mercado Eficiente del economista Eugene Fama (Nobel de Economía, 2013) propone que los precios del mercado ya incorporan toda la información disponible, por lo que es imposible obtener rendimientos consistentemente superiores al mercado usando información pública (Fama, 1970). Sin embargo, los algoritmos de trading de alta frecuencia de fondos como Renaissance Technologies han obtenido rendimientos extraordinariamente consistentes usando patrones estadísticos oscuros en datos de mercado. El debate entre determinismo y aleatoriedad en los mercados financieros sigue siendo uno de los más calientes en economía. ¡Nadie ha encontrado todavía el almanaque perfecto del mercado bursátil!",
  "La mecánica cuántica tiene algo que parece aún más extraño que la incertidumbre: el entrelazamiento cuántico. Dos partículas entrelazadas pueden estar separadas por cualquier distancia, y cuando se mide el estado de una, el estado de la otra queda instantáneamente determinado, independientemente de la distancia. Einstein llamó a esto 'acción fantasmal a distancia' y argumentó que debía haber variables ocultas que determinaran los resultados (Einstein, Podolsky & Rosen, 1935). En 1964, John Bell demostró matemáticamente que las variables ocultas locales son incompatibles con las predicciones cuánticas (Physics, 1964). Experimentos de 2022 confirmaron definitivamente que las variables ocultas locales no existen: el universo es genuinamente no-local y probabilístico (Nobel Prize, 2022). ¡Einstein estaba equivocado en la mecánica cuántica!",
  "Las computadoras cuánticas tienen el potencial de romper algunos límites de predicción. Un ordenador cuántico con suficientes qubits podría simular exactamente la dinámica cuántica de moléculas y materiales complejos, lo que permitiría predecir con precisión exacta las propiedades de nuevos fármacos, superconductores y catalizadores (Nature, 2023). Google anunció en 2019 que su procesador cuántico Sycamore realizó en 200 segundos un cálculo que un supercomputador tardaría 10,000 años (Nature, 2019), aunque IBM disputó esta afirmación. En 2023, IBM presentó el procesador de 1,121 qubits Condor, el más grande hasta la fecha (IBM, 2023). Las computadoras cuánticas no predicen el futuro, pero sí amplían dramáticamente lo que podemos calcular y modelar.",
  "La predicción en biología evolutiva tiene una dimensión cuántica y caótica fascinante. Si pudieras rebobinar la película de la vida en la Tierra y volverla a reproducir desde el principio, ¿evolucionarían de nuevo los seres humanos? El paleontólogo Stephen Jay Gould argumentó que no, que la historia evolutiva depende tanto del azar (mutaciones aleatorias, extinciones masivas aleatorias) que el resultado sería completamente diferente (Gould, 1989). Richard Dawkins y Simon Conway Morris argumentan lo contrario: que la evolución converge hacia formas similares por las limitaciones del diseño adaptativo, por lo que algo parecido a la inteligencia emergería de nuevo (Dawkins, 2004). Este debate sobre el determinismo en la evolución todavía no tiene resolución definitiva. ¡El árbol de la vida también está gobernado por el caos y el azar!",
  "Un descubrimiento reciente asombroso: en 2019, un equipo de la Universidad de Yale usó una computadora cuántica para 'retroceder' el estado de un qubit en el tiempo, revertiendo su evolución temporal durante una fracción de segundo usando un proceso llamado protocolo de Loschmidt (Physical Review Letters, 2019). Esto no es un viaje al pasado real, sino una reversión del estado cuántico dentro de la computadora. Sin embargo, demuestra que la mecánica cuántica tiene simetría temporal a nivel de partículas individuales. También en 2020, investigadores australianos simularon en una computadora cuántica un proceso de 'retroceso temporal' de un fotón, revertiendo su estado hacia configuraciones anteriores (Science Advances, 2020). ¡Las computadoras cuánticas pueden simular la dirección inversa del tiempo!",
  "Tú, joven predictor cuántico, puedes explorar la teoría del caos de forma práctica. El péndulo doble (dos péndulos conectados) es el ejemplo más simple de un sistema caótico: trayectorias inicialmente casi idénticas divergen rápidamente. Puedes construir uno con dos varillas y tres pivotes usando materiales de ferretería. El programa Chaos de Paul Bourke, disponible gratis online, simula el atractor de Lorenz y otros sistemas caóticos en 3D. La plataforma Scratch del MIT tiene decenas de proyectos de simulación caótica que puedes modificar. Y el libro 'Caos' de James Gleick (Gleick, 1987) es una lectura apasionante que cuenta la historia del descubrimiento de la teoría del caos con narrativa de aventura. ¡El caos es fascinante y predecible en sus impredecibilidades!",
  "El futuro de la predicción incluye sistemas de inteligencia artificial que combinan grandes modelos de lenguaje con modelos físicos para hacer predicciones más robustas. DeepMind's GraphCast produjo en 2023 un sistema de predicción meteorológica de 10 días que supera en precisión al ECMWF con solo una fracción del costo computacional (Science, 2023). Los modelos de lenguaje grandes (LLMs) como GPT-4 muestran capacidades emergentes de razonamiento complejo que sus creadores no anticiparon explícitamente, lo que sugiere que los sistemas de IA podrían capturar regularidades en sistemas complejos que los modelos físicos explícitos no detectan. Sin embargo, el caos fundamental de la naturaleza pone un límite absoluto a cualquier predicción, IA o no. ¡El futuro siempre conservará parte de su misterio!",
  "La predicción y el libre albedrío están profundamente conectados. Si el universo fuera completamente determinista, todas tus decisiones estarían predeterminadas desde el Big Bang, y el libre albedrío sería una ilusión. La mecánica cuántica introduce aleatoriedad genuina, pero aleatoriedad no es lo mismo que libre albedrío: decisiones aleatorias tampoco son libremente elegidas. El neurocientífico Benjamin Libet mostró en 1983 que la actividad cerebral que precede a una decisión voluntaria comienza 300-500 ms antes de que el sujeto sea consciente de haber decidido (Brain, 1983), lo que generó debate sobre si las decisiones conscientes son verdaderamente libres. La ciencia todavía no tiene una respuesta definitiva al libre albedrío, pero la mecánica cuántica asegura al menos que el universo no es un reloj predeterminado. ¡El almanaque de Biff es imposible por razones tanto físicas como filosóficas!",
  "¡Apuesta ganada, explorador del caos! Ahora sabes que el Principio de Incertidumbre de Heisenberg hace que el universo tenga aleatoriedad fundamental, que la teoría del caos limita la predicción incluso en sistemas deterministas, que el entrelazamiento cuántico es real y no-local, y que las computadoras cuánticas amplían enormemente nuestras capacidades de modelado y simulación. El almanaque deportivo de Biff Tannen es imposible en el universo real, y eso es una buena noticia: hace la vida más libre, más sorprendente y más apasionante. ¡Un universo predecible sería un universo aburrido! 🌟"
];

const bttf_m7 = [
  "¡Explorador del futuro real, atención! En Volver al Futuro II, ambientada en el octubre de 2015, se muestran tecnologías futuristas como pantallas planas gigantes, videoconferencias, drones de pasear perros, tabletas de pago digital y ropa autorregulable. Cuando la película se estrenó en 1989, el año 2015 parecía el futuro lejano. Hoy sabemos que 2015 ya pasó: ¿cuántas de las predicciones de la película se cumplieron? ¿Y cuáles siguen siendo futuro? Un análisis de las tecnologías reales del siglo XXI frente a las predicciones de Volver al Futuro es una lección brillante sobre cómo la ciencia ficción imagina el futuro. ¡Comparemos! 📱",
  "Las pantallas de televisión planas y de alta definición que aparecen en Volver al Futuro II ya son una realidad totalmente rutinaria. En 1989, los televisores eran tubos de rayos catódicos de décadas de grosor y resolución estándar. En 2015, el año ficticio de la película, los televisores OLED de LG y Samsung ya tenían resoluciones de 4K (3840×2160 píxeles) y espesores de pocos milímetros. En 2023, los televisores 8K (7680×4320 píxeles) ya están disponibles comercialmente, y las pantallas enrollables o plegables son productos del mercado (Samsung Galaxy Z Fold, 2023). La predicción de pantallas planas gigantes en la película fue completamente correcta. ¡La ficción de 1989 es la tecnología ordinaria de hoy!",
  "Las videoconferencias que aparecen en la película, donde Marty habla por video con su jefe Needles en una pantalla enorme, también son hoy realidad cotidiana. FaceTime de Apple se lanzó en 2010, Skype ya existía desde 2003, y Zoom creció de 10 millones a 300 millones de usuarios diarios durante la pandemia de COVID-19 en 2020 (Zoom, 2020). Las reuniones de trabajo por video se convirtieron en la norma global. La predicción fue acertada, aunque la película imaginaba pantallas de pared entera, no la pequeña pantalla del smartphone. ¡La videoconferencia es quizás la tecnología más profundamente adoptada de las últimas décadas, y Volver al Futuro lo vio venir en 1989!",
  "Los drones que aparecen en la película paseando perros automáticamente son casi una realidad. Los drones comerciales DJI ya pueden seguir objetos en movimiento automáticamente usando visión por computadora (DJI, 2023). Existen servicios de entrega por drone de Amazon Prime Air en pruebas en EE.UU. y UK, y Wing de Alphabet (Google) opera entregas por drone en Australia (Wing, 2023). Un drone que pasee a un perro autónomamente requeriría inteligencia artificial de manejo de situaciones imprevistas que todavía no existe a nivel comercial, pero técnicamente está muy cerca. El ejército de EE.UU. ya usa enjambres de drones autónomos (DARPA, 2022). ¡Los drones de la película son un pronóstico casi exacto de 2023!",
  "Los pagos digitales sin efectivo que la película muestra con tabletas de pago son también una realidad completa. Apple Pay se lanzó en 2014, Google Pay en 2015, y las criptomonedas como Bitcoin en 2009 (Satoshi Nakamoto, 2008). En países como Suecia y China, el efectivo prácticamente ha desaparecido de las transacciones cotidianas: más del 98% de los pagos en China se realizan digitalmente vía WeChat Pay o Alipay (People's Bank of China, 2023). Las tarjetas de crédito contactless, los pagos NFC con el teléfono y las billeteras digitales son hoy la norma en la mayoría de países desarrollados. ¡La predicción de la película sobre el dinero digital también fue completamente acertada!",
  "La ropa autorregulable que Marty lleva al llegar al futuro (chaqueta que se seca sola y ajusta su talla automáticamente) es el área donde la película se equivocó más. Aunque los materiales inteligentes son un campo activo de investigación, textiles que respondan autónomamente al entorno todavía no están disponibles comercialmente. Se han desarrollado telas con sensores integrados que monitorean la temperatura corporal, el ritmo cardíaco o los movimientos (MIT Media Lab, 2022). Nike presentó las zapatillas Nike Adapt BB con cordones que se ajustan eléctricamente con una aplicación (Nike, 2019). Pero una chaqueta que se seque y ajuste autónomamente sigue siendo tecnología del futuro real. ¡Uno de pocos pronósticos de la película que todavía no se ha cumplido!",
  "El aeropatín (hoverboard) que Marty usa en la película es quizás la tecnología más icónica y la más comentada. Aunque los aeropatines magnéticos reales como el de Hendo (2014) existen, solo flotan sobre superficies de cobre específicas. Lexus construyó un prototipo de skateboard magnético usando superconductores enfriados con nitrógeno líquido que flota sobre una pista de metal (Lexus, 2015), pero requiere refrigeración continua. El 'hoverboard' comercial que se popularizó en 2015 era en realidad un patinete eléctrico de dos ruedas, no un tablero volador: la industria adoptó el nombre de forma engañosa. Un aeropatín que funcione sobre cualquier superficie como en la película sigue siendo ficción. ¡Esta es la predicción más famosa todavía pendiente de cumplirse!",
  "La inteligencia artificial en 2015 ficticio de la película muestra sistemas bastante sofisticados de automatización. La IA real de 2023 ha superado en muchos sentidos lo que la película imaginaba. GPT-4 de OpenAI puede mantener conversaciones, escribir código, analizar imágenes y razonar sobre problemas complejos (OpenAI, 2023). AlphaFold2 de DeepMind predice la estructura 3D de proteínas a partir de su secuencia con precisión experimental, resolviendo un problema de 50 años de biología (Nature, 2021). Los sistemas de conducción autónoma de Tesla, Waymo y Cruise ya operan en ciudades reales. La IA en 2023 es más avanzada que cualquier computadora que la película de 1989 pudiera imaginar para 2015. ¡La IA real superó la ficción en este campo!",
  "La energía del futuro en la película se representa con el Mr. Fusion que Doc instala en el DeLorean, que convierte residuos domésticos en combustible de fusión para viajar en el tiempo. La fusión nuclear real, como vimos, está más cercana que nunca: el hito del NIF en 2022 demostró ignición neta por primera vez (Science, 2022). Sin embargo, los reactores de fusión comerciales se esperan para los años 2030-2040 en el mejor de los casos. La transición energética real de 2023 está siendo liderada por energías renovables: la solar y la eólica son ya las fuentes de generación más baratas en la historia, y en 2023 representaron más del 30% de la electricidad global (International Energy Agency, 2023). ¡La transición energética real es más solar que de fusión!",
  "El mundo de 2015 real vs el de la película muestra también grandes diferencias en el transporte. La película imagina coches voladores y aeropatines pero no smartphones ni internet tal como los conocemos. El iPhone se lanzó en 2007, y para 2015 había 3,000 millones de smartphones en el mundo (Statista, 2015). Internet tenía en 2015 unos 3,200 millones de usuarios, más del 40% de la población mundial (Internet World Stats, 2015). Las redes sociales como Facebook, Twitter e Instagram no aparecen en la película porque eran inimaginables en 1989. ¡La película acertó en muchas tecnologías físicas pero no anticipó la revolución digital de internet y los smartphones!",
  "Un hallazgo fascinante sobre el poder de predicción de la ciencia ficción: un estudio de la Universidad de Miami de 2020 analizó 2,000 predicciones tecnológicas de 250 novelas y películas de ciencia ficción publicadas entre 1950 y 1995 y encontró que el 40% de ellas se habían cumplido o parcialmente cumplido para 2020 (Futures, 2020). Las predicciones más exitosas eran sobre tecnologías ya en desarrollo, mientras que las más fallidas eran sobre revoluciones completamente disruptivas como la fusión o los viajes interestelares. La ciencia ficción es mejor en extrapolaciones que en rupturas radicales. Volver al Futuro tuvo una tasa de predicciones correctas de más del 60% para las tecnologías que muestra, lo que es notablemente alto.",
  "Tú, explorador del futuro, puedes hacer tus propias predicciones tecnológicas. Investiga las tecnologías emergentes actuales: ¿qué veremos en 2050? La inteligencia artificial general, la computación cuántica práctica, la fusión comercial, la colonización lunar, los viajes a Marte, la medicina de longevidad, los materiales cuánticos. Elige tres tecnologías que crees que serán realidad en 2050 y escribe cómo cambiarán la vida cotidiana. Investiga el Informe de Tecnologías Emergentes del World Economic Forum (WEF, 2023) y el reporte de McKinsey Global Institute sobre el futuro de la tecnología. ¡Las predicciones más audaces de hoy son los inventos ordinarios del mañana, igual que las pantallas planas de 1989!",
  "El futuro real que la ciencia y la ingeniería están construyendo ahora mismo incluye: computadoras cuánticas tolerantes a fallos para 2030 (IBM, Google, IonQ); órganos humanos impresos en 3D para trasplantes hacia 2030 (Organovo, United Therapeutics); colonias humanas en la Luna hacia 2035 (NASA Artemis); misiones tripuladas a Marte hacia 2040 (SpaceX, NASA); superconductores de temperatura ambiente si los resultados de 2023 se confirman; e inteligencia artificial general (AGI) de cronología incierta pero posiblemente décadas. La diferencia entre el futuro que imaginamos y el que ocurre realmente siempre es que la tecnología real nos sorprende de formas que no anticipamos. ¡El futuro real siempre es más extraño y más maravilloso que la ficción!",
  "Volver al Futuro nos enseña algo profundo sobre la relación entre la imaginación y la innovación. Los investigadores de Bell Labs, que inventaron el transistor en 1947, la industria de los videojuegos, que nació en los años 1970, y los pioneros de internet en los años 1990, todos estaban inspirados en parte por la ciencia ficción que habían consumido en su juventud. Arthur C. Clarke, Isaac Asimov y Carl Sagan son citados repetidamente por astronautas, físicos e ingenieros como sus mayores inspiraciones de infancia. La ciencia ficción no predice el futuro con precisión, pero expande el espacio de lo que las personas creen que es posible, y esa expansión de posibilidades es exactamente lo que motiva la innovación real. ¡Imaginar es el primer paso de inventar!",
  "¡Misión al futuro completada, explorador del tiempo real! Ahora sabes que Volver al Futuro II acertó en las pantallas planas, las videoconferencias, los pagos digitales y los drones, que el aeropatín sigue siendo la predicción pendiente más icónica, que la inteligencia artificial de 2023 superó lo que la película imaginaba, y que el futuro real es siempre más sorprendente que la ficción porque incluye cosas que nadie anticipó, como los smartphones e internet. La ciencia ficción no predice el futuro, pero nos ayuda a imaginar posibilidades y a inspirar a los inventores que las hacen realidad. ¡Tú eres el inventor que el futuro necesita! 🌟"
];

// Patch the modules
let patched = 0;
for (let module of data) {
  if (module.id === 'bttf_m6') {
    module.contentEs.sections[0].text = bttf_m6;
    patched++;
  }
  if (module.id === 'bttf_m7') {
    module.contentEs.sections[0].text = bttf_m7;
    patched++;
  }
}

console.log(`Patched ${patched} modules.`);
fs.writeFileSync(filePath, 'export default ' + JSON.stringify(data, null, 2) + ';', 'utf8');
console.log('File written successfully.');
