/**
 * patch_bttf.js — patches bttf_m1 through bttf_m7 with 15 paragraphs each
 */
const fs = require('fs');
const { replaceTextAndQuiz, FILE } = require('./patch_helpers');
let src = fs.readFileSync(FILE, 'utf8');

const BTTF = {
  bttf_m1: {
    text: [
      "¡Bienvenido, viajero del tiempo! La película 'Regreso al Futuro' (Back to the Future, 1985) es mucho más que entretenimiento: es una exploración de ideas científicas reales sobre el tiempo, la física y la naturaleza de la causalidad. En este módulo comenzamos a descubrir qué hay de ciencia real detrás de la ficción.",
      "La película presenta al inventor excéntrico Doc Brown y a su amigo adolescente Marty McFly. Doc ha construido una máquina del tiempo dentro de un DeLorean (un automóvil de acero inoxidable de los años 80) alimentada por un flujo de condensador que requiere 1.21 gigavatios de electricidad. Aunque el flujo de condensador es ficción, los principios que exploran son fascinantes.",
      "El tiempo es uno de los conceptos más fundamentales y misteriosos de la física. En la física clásica de Newton, el tiempo era un fondo fijo y absoluto en el que ocurrían los eventos. Einstein cambió esto radicalmente: el tiempo no es fijo sino relativo, y puede pasar a velocidades diferentes dependiendo de la velocidad y la gravedad.",
      "En la relatividad especial de Einstein (1905), el tiempo se dilata cuando un objeto se mueve a velocidades cercanas a la de la luz. Si pudieras viajar al 99.9% de la velocidad de la luz, el tiempo pasaría para ti unas 22 veces más lento que para alguien en reposo. Viajarías hacia el futuro sin darte cuenta.",
      "El universo tiene una dirección preferida del tiempo: la 'flecha del tiempo'. El tiempo siempre avanza del pasado al futuro. Esto está relacionado con el segundo principio de la termodinámica: la entropía (el desorden) siempre aumenta. Un vaso que se rompe nunca se vuelve a armar solo. El tiempo tiene dirección.",
      "Una de las razones por las que el viaje al pasado es problemático es que violaria la causalidad: la ley de que la causa siempre precede al efecto. Si pudieras viajar al pasado y matar a tu abuelo antes de que tuviera hijos, tú nunca habrías nacido para hacer el viaje. Esta contradicción se llama la paradoja del abuelo.",
      "La física moderna tiene varias respuestas posibles a la paradoja del abuelo. La primera es la 'interpretación de los muchos mundos': cada viaje al pasado crea una nueva rama del universo, por lo que en tu universo original nada cambia. La segunda es el 'principio de autoconsistencia': solo son posibles viajes al pasado que no crean paradojas.",
      "La velocidad de la luz es el límite máximo de velocidad en el universo: 299,792 kilómetros por segundo en el vacío. Ningún objeto con masa puede alcanzarla porque requeriría energía infinita. Sin embargo, nada prohíbe que el espacio-tiempo en sí mismo se expanda o curve más rápido que la luz: el universo lo hace constantemente.",
      "El DeLorean en la película necesita alcanzar 88 millas por hora (141 km/h) para activar el viaje en el tiempo. Esta cifra es completamente arbitraria desde el punto de vista de la física real. Ninguna velocidad por debajo de la de la luz podría producir efectos de viaje en el tiempo según la relatividad especial.",
      "Sin embargo, la elección del DeLorean tiene una elegancia narrativa: es un automóvil que muchos asociaban con el futuro cuando fue fabricado en 1981 (su chasis de acero inoxidable le daba un aspecto futurista). El uso de un objeto cotidiano como máquina del tiempo refuerza la idea de que la ciencia puede estar al alcance de las personas ordinarias.",
      "El flujo de condensador que Doc Brown describe como la clave de la máquina del tiempo es ficción, pero el concepto de usar energía extremadamente concentrada para doblar el espacio-tiempo no es completamente descabellado. En la física teórica, la materia exótica con densidad de energía negativa podría en principio doblar el espacio-tiempo de manera radical.",
      "Los 1.21 gigavatios de potencia que requiere la máquina son reales en magnitud: 1.21 GW equivale aproximadamente a la potencia de producción de una central nuclear grande. La idea de que el viaje en el tiempo requeriría cantidades masivas de energía es consistente con la física teórica de los agujeros de gusano.",
      "La física del tiempo sigue siendo uno de los campos más activos y misteriosos de la ciencia. Los científicos estudian la naturaleza del tiempo en el contexto de la mecánica cuántica, la relatividad general y las teorías de cuerdas. La pregunta de si el viaje al pasado es posible sigue abierta y genera investigación activa.",
      "La película 'Regreso al Futuro' ha inspirado a generaciones de científicos. Muchos físicos y matemáticos actuales mencionan haberla visto como jóvenes y sentir fascinación por las preguntas que planteaba. El arte y la ciencia se alimentan mutuamente: las preguntas que hace el arte a veces guían la investigación científica.",
      "Al estudiar las ideas científicas detrás de 'Regreso al Futuro', no solo aprendemos física: aprendemos a hacernos preguntas. ¿Qué es el tiempo? ¿Puede tener dirección contraria? ¿Qué pasaría si pudiéramos cambiar el pasado? Estas preguntas son las que impulsan el conocimiento humano hacia adelante."
    ],
    quiz: [
      { q: "¿A qué velocidad debía ir el DeLorean para viajar en el tiempo?", options: ["55 mph","88 mph","100 mph","150 mph"], a: 1 },
      { q: "¿Cuántos gigavatios de potencia necesitaba la máquina del tiempo?", options: ["0.88","1.21","10","100"], a: 1 },
      { q: "¿Qué es la paradoja del abuelo?", options: ["Que los abuelos son más sabios","Si matas a tu abuelo en el pasado, tú nunca habrías nacido para hacer el viaje","Que el tiempo avanza más rápido con la edad","Que los viajes en el tiempo envejecen"], a: 1 },
      { q: "¿Cuál es la velocidad de la luz en el vacío?", options: ["30,000 km/s","300,000 km/s","3,000,000 km/s","30,000,000 km/s"], a: 1 },
      { q: "¿Qué ley física está relacionada con la 'flecha del tiempo'?", options: ["La ley de gravedad","El segundo principio de la termodinámica","La ley de Coulomb","La ley de Ohm"], a: 1 }
    ]
  },
  bttf_m2: {
    text: [
      "En 'Regreso al Futuro II' (1989), Doc y Marty viajan al 21 de octubre de 2015 para resolver un problema familiar. La película hizo predicciones sobre cómo sería ese año: algunas sorprendentemente acertadas y otras completamente erróneas. Analizar estas predicciones es una lección de cómo funciona la predicción tecnológica.",
      "Las tabletas y las gafas tecnológicas que muestran información fueron predicciones acertadas: en 2015 existían los iPad, las Google Glass y los smartwatches. La idea de que las pantallas estarían en todas partes y que accederíamos a información de manera ubicua fue visionaria para 1989.",
      "El pago biométrico (pagar con las huellas dactilares) que aparece en la película es también una predicción cumplida: hoy pagamos con huella digital en millones de establecimientos. La autenticación biométrica es rutinaria en smartphones y terminales de pago de todo el mundo.",
      "Las zapatillas que se atan solas (Nike Mag) aparecieron literalmente en el mundo real. Nike las presentó en 2016, un año después de la fecha de la película, con un sistema de ajuste automático. Son un ejemplo raro de un producto de ficción científica que se volvió realidad casi literalmente.",
      "Las tablas flotantes (hoverboards) que aparecen en la película no llegaron a 2015 tal y como se mostraban. Los 'hoverboards' que se popularizaron en 2015 son patinetas con ruedas, no tablas magnéticas flotantes. Las tablas flotantes reales existen pero requieren pistas especiales con metal debajo y no son de uso cotidiano.",
      "La película predijo pantallas planas en las paredes: hoy son comunes. Pero también predijo que los fax serían la tecnología de comunicación dominante en 2015, algo que claramente no ocurrió: el email e internet los desplazaron completamente. Las predicciones tecnológicas son difíciles porque no podemos saber qué tecnologías serán reemplazadas.",
      "El tiempo en la física cuántica tiene propiedades aún más extrañas que en la relatividad. A nivel cuántico, las partículas pueden existir en múltiples estados simultáneamente (superposición cuántica). El tiempo en estas escalas tiene propiedades no intuibles que los físicos aún estudian activamente.",
      "La 'paradoja de los gemelos' es un efecto real de la relatividad especial. Si uno de dos gemelos viajara a una estrella al 90% de la velocidad de la luz y regresara, habría envejecido menos que el gemelo que se quedó en la Tierra. No es solo teoría: experimentos con relojes atómicos en aviones han verificado la dilatación temporal.",
      "La causalidad es el principio de que la causa siempre precede al efecto. Es uno de los pilares de la física. Si los viajes al pasado fueran posibles, podrían crear 'bucles causales' donde un efecto ocurre antes de su causa. La mayoría de los físicos creen que la naturaleza tiene mecanismos para prevenir estas violaciones de la causalidad.",
      "El principio de incertidumbre de Heisenberg dice que no podemos conocer simultáneamente la posición exacta y el momento exacto de una partícula. Este principio no es un fallo de nuestros instrumentos sino una propiedad fundamental de la realidad. Tiene implicaciones profundas para la naturaleza del tiempo y la predicción del futuro.",
      "Si el principio de incertidumbre se aplica a nivel cuántico, el universo tiene una aleatoriedad fundamental. El futuro no está determinado con precisión: hay probabilidades, no certezas absolutas. Esto hace que 'ver el futuro' sea físicamente imposible en el sentido estricto: el futuro aún no existe de manera determinada.",
      "La película muestra múltiples líneas temporales que se bifurcan cuando cambia el pasado. Esta imagen es consistente con la 'interpretación de los muchos mundos' de la mecánica cuántica, propuesta por Hugh Everett en 1957. Según esta interpretación, cada vez que ocurre un evento cuántico, el universo se divide en ramas.",
      "En 2015 real (el año al que viajaron en la película), la humanidad tenía acceso a internet de alta velocidad, smartphones poderosos, televisores 4K y coches parcialmente autónomos. Pero no teníamos coches voladores de uso cotidiano ni turismo interestelar. El progreso tecnológico es desigual: avanza más rápido en información que en transporte físico.",
      "La predicción más importante de la película no fue tecnológica sino social: mostró un mundo donde la tecnología está integrada en la vida cotidiana de manera natural, donde las personas interactúan con dispositivos constantemente y donde el acceso a la información es inmediato. Esto describe perfectamente 2015 y más.",
      "La ciencia ficción es una herramienta extraordinaria para explorar posibilidades futuras. Las mejores películas y novelas de ciencia ficción no solo imaginan gadgets: imaginan cómo cambia la sociedad humana con la tecnología. 'Regreso al Futuro II' hizo esto con humor y brillantez, y sigue siendo relevante décadas después."
    ],
    quiz: [
      { q: "¿A qué fecha del futuro viajan Doc y Marty en la segunda película?", options: ["21 de octubre de 2000","21 de octubre de 2015","21 de octubre de 2025","21 de octubre de 2045"], a: 1 },
      { q: "¿Qué predicción de la película se cumplió casi literalmente con las Nike Mag?", options: ["Los coches voladores","Las zapatillas que se atan solas","Los hoverboards","Las pantallas 3D"], a: 1 },
      { q: "¿Qué tecnología de comunicación predijo la película para 2015 pero resultó obsoleta?", options: ["Email","Internet","Redes sociales","Fax"], a: 3 },
      { q: "¿Qué dice el principio de incertidumbre de Heisenberg?", options: ["Todo puede medirse con precisión","No podemos conocer simultáneamente posición exacta y momento de una partícula","El futuro está determinado","La luz viaja siempre a la misma velocidad"], a: 1 },
      { q: "¿En qué consiste la interpretación de los 'muchos mundos' de Everett?", options: ["Que hay múltiples Tierras","Cada evento cuántico divide el universo en ramas","Que el tiempo no existe","Que somos una simulación"], a: 1 }
    ]
  },
  bttf_m3: {
    text: [
      "En 'Regreso al Futuro III' (1990), Doc y Marty viajan al Lejano Oeste americano de 1885. La película explora el contraste entre la tecnología del siglo XIX y la del siglo XX, y cómo resolver un problema tecnológico moderno con los recursos disponibles 100 años antes.",
      "El siglo XIX fue un período de revolución tecnológica comparable al que vivimos hoy. En pocas décadas, la humanidad pasó de la tracción animal a la locomotora de vapor, del correo a caballo al telégrafo, del candil de aceite a la bombilla eléctrica. Edison, Tesla, Bell, Faraday: gigantes de la ciencia que transformaron el mundo.",
      "La locomotora de vapor fue el 'cohete' del siglo XIX. Podía viajar a 100-150 km/h cuando los caballos llegaban a 40. Conectó continentes, hizo posible el comercio masivo de mercancías, y cambió la percepción del espacio y el tiempo: lo que antes tomaba semanas ahora tomaba días.",
      "En la película, Doc Brown usa la locomotora de vapor para acelerar el DeLorean hasta 88 mph y viajar en el tiempo. El detalle físico interesante es que la locomotora necesita impulsar el DeLorean (que no puede generar su propia energía en ese momento) a través de rieles. Esta solución ingeniosa con los recursos disponibles es una metáfora de la ciencia: resolver problemas con lo que tienes.",
      "El efecto mariposa es un concepto de la teoría del caos que dice que pequeños cambios en las condiciones iniciales de un sistema complejo pueden producir grandes diferencias en los resultados a largo plazo. El aleteo de una mariposa en Brasil podría, teóricamente, influir en que haya un tornado en Texas semanas después.",
      "En la física del tiempo, el efecto mariposa sería extremadamente importante. Cualquier pequeña intervención en el pasado podría tener consecuencias enormes y no predecibles en el futuro. Esta es una razón más por la que muchos físicos son escépticos del viaje al pasado: incluso si fuera posible, las consecuencias serían incontrolables.",
      "La teoría del caos, desarrollada en la segunda mitad del siglo XX, cambió radicalmente la física. Antes de ella, se pensaba que si conocías con suficiente precisión las condiciones iniciales de un sistema, podrías predecir su futuro indefinidamente. El caos demostró que esto es imposible en sistemas complejos, no por ignorancia sino por la naturaleza de las ecuaciones no lineales.",
      "El tiempo en el universo tiene una dirección: siempre avanza del pasado al futuro. Pero en las ecuaciones de la física (la relatividad y la mecánica cuántica), las leyes son simétricas respecto al tiempo: funcionan igual hacia adelante que hacia atrás. La asimetría del tiempo es un problema profundo que los físicos llaman el 'problema de la flecha del tiempo'.",
      "La solución más aceptada al problema de la flecha del tiempo está en la termodinámica estadística. El universo comenzó en un estado de entropía extremadamente baja (muy ordenado) con el Big Bang. El tiempo avanza en la dirección en que la entropía aumenta, porque hay muchos más estados desordenados que ordenados: la probabilidad estadística favorece el desorden.",
      "El telégrafo, inventado en 1837 por Samuel Morse, fue la primera comunicación casi instantánea a larga distancia. En 1865, el primer cable telegráfico transatlántico conectó América con Europa. Esto redujo el tiempo de comunicación de semanas (viaje en barco) a minutos. Esta revolución comunicacional fue tan dramática como el internet para el siglo XX.",
      "La fotografía también nació en el siglo XIX (daguerrotipo, 1839). Por primera vez en la historia, la apariencia de las personas podía ser capturada objetivamente. Antes de la fotografía, el recuerdo visual de personas fallecidas dependía de pinturas y retratos, accesibles solo a los ricos. La fotografía democratizó la memoria visual.",
      "En la película, Doc Brown explica que los viajes al pasado crean líneas temporales alternativas. Esto es coherente con la física cuántica de los muchos mundos: cada elección o cambio en el pasado crearía una nueva rama del universo, no modificaría el pasado de la rama original. El Marty que regresa al futuro en la película 3 regresaría a una rama diferente, no a la misma.",
      "La tecnología del siglo XIX sentó las bases para la del siglo XX y XXI. Sin la locomotora de vapor no habría coches. Sin el telégrafo no habría teléfono ni internet. Sin la bombilla eléctrica no habría computadoras. La historia de la tecnología es una cadena donde cada eslabón depende de los anteriores.",
      "Una lección que ofrece 'Regreso al Futuro III': el genio no está en tener la tecnología perfecta, sino en resolver problemas creativamente con lo disponible. Doc Brown usa madera, alcohol de maíz y la fuerza de la locomotora para resolver un problema que ningún recurso moderno podía resolver. El ingenio supera a los recursos.",
      "Al terminar la trilogía, lo que queda en la memoria no son los efectos especiales sino la amistad entre Doc y Marty, la creatividad para resolver problemas imposibles y las preguntas filosóficas sobre el tiempo y el destino. La mejor ciencia ficción usa la tecnología como telón de fondo para explorar lo que significa ser humano."
    ],
    quiz: [
      { q: "¿A qué época viajan en la tercera película de Regreso al Futuro?", options: ["1776","1855","1885","1920"], a: 2 },
      { q: "¿Qué invento se usa para acelerar el DeLorean en la tercera película?", options: ["Un cohete de combustible","Una locomotora de vapor","Electricidad de un rayo","Un globo aerostático"], a: 1 },
      { q: "¿Qué es el efecto mariposa en la teoría del caos?", options: ["Los insectos afectan el clima","Pequeños cambios iniciales pueden producir grandes diferencias en sistemas complejos","El tiempo vuela como las mariposas","Los sistemas simples son caóticos"], a: 1 },
      { q: "¿En qué año se inventó el telégrafo moderno?", options: ["1800","1837","1865","1890"], a: 1 },
      { q: "¿Por qué el tiempo avanza siempre del pasado al futuro según la termodinámica?", options: ["Por la fuerza de gravedad","Las leyes físicas lo exigen","La entropía siempre aumenta y hay más estados desordenados","Por la velocidad de la luz"], a: 2 }
    ]
  },
  bttf_m4: {
    text: [
      "El tiempo es quizás el concepto más familiar y más misterioso de la física. Todos lo experimentamos constantemente, pero definirlo con precisión resulta asombrosamente difícil. San Agustín, en el siglo IV, escribió: 'Si nadie me pregunta qué es el tiempo, lo sé; si quiero explicarlo a quien me pregunta, no lo sé.'",
      "La física newtoniana (siglos XVII-XVIII) trataba el tiempo como un flujo uniforme, absoluto, el mismo para todos. Newton lo llamó 'tiempo absoluto, verdadero y matemático'. En este universo, el tiempo era como un río que fluía igual para todos los observadores, independientemente de su movimiento o posición.",
      "Einstein cambió todo esto con la relatividad. En su universo, el tiempo es relativo: depende del estado de movimiento del observador y de la intensidad del campo gravitacional donde se encuentra. Dos observadores en movimiento relativo entre sí medirán tiempos diferentes entre los mismos eventos. Ninguno está equivocado: ambos tienen razón en su propio marco de referencia.",
      "El concepto de 'simultaneidad' es relativo según Einstein. Dos eventos que ocurren simultáneamente para un observador pueden no ser simultáneos para otro observador que se mueve respecto al primero. Esto parece contraintuitivo, pero ha sido verificado experimentalmente y es completamente consistente con la relatividad especial.",
      "La flecha del tiempo (por qué el tiempo avanza solo hacia adelante) sigue siendo uno de los mayores misterios de la física. Las leyes fundamentales de la naturaleza son simétricas en el tiempo: las ecuaciones funcionan igual si reemplazas t por -t. Sin embargo, nuestra experiencia del tiempo es claramente asimétrica: el pasado es fijo, el futuro incierto.",
      "La termodinámica ofrece la explicación más convincente: el universo comenzó en un estado de entropía extremadamente baja (muy ordenado) después del Big Bang. Desde entonces, la entropía aumenta continuamente porque hay muchos más formas de estar desordenado que ordenado. El tiempo avanza en la dirección en que aumenta la entropía.",
      "La memoria también tiene relación con la flecha del tiempo. Recordamos el pasado porque los eventos dejaron 'huellas' físicas en nuestro cerebro y en el mundo: un vaso roto, una cicatriz, un registro. No 'recordamos' el futuro porque aún no ha ocurrido y no ha dejado huellas. La memoria es posible solo porque el tiempo tiene dirección.",
      "La mecánica cuántica complica aún más la imagen del tiempo. En la mecánica cuántica, el colapso de la función de onda (cuando medimos una partícula en superposición cuántica) tiene una asimetría temporal: es un proceso irreversible. Esto conecta el tiempo cuántico con la flecha termodinámica.",
      "Algunos físicos proponen que el tiempo no existe como entidad fundamental, sino que emerge de relaciones entre estados cuánticos. En la formulación Wheeler-DeWitt de la gravedad cuántica, la ecuación fundamental no contiene el tiempo en absoluto: el tiempo emergiría de la correlación entre diferentes partes del universo cuántico.",
      "El presente es el único momento en que realmente 'vivimos'. El pasado es una abstracción (memoria e inferencias) y el futuro es una posibilidad aún no realizada. La física del tiempo cuántico sugiere que incluso el 'presente' es una construcción: las partículas cuánticas no tienen posición definida hasta que son medidas.",
      "La pregunta '¿puede el tiempo ir hacia atrás?' tiene respuestas diferentes dependiendo del nivel. A nivel macroscópico (tazas de té, vidas humanas, galaxias), no. A nivel microscópico (partículas individuales), las leyes físicas son simétricas en el tiempo. A nivel cuántico, existe el 'reversal de tiempo' T en la simetría CPT, que sugiere que la física tiene una simetría profunda respecto al tiempo.",
      "El viaje al futuro es físicamente posible y ha sido observado directamente. Los muones creados en la atmósfera superior sobreviven hasta el suelo porque su tiempo interno se dilata a velocidades relativistas. Los astronautas de la ISS envejecen unos milisegundos menos por año que en la Tierra. El viaje al futuro ocurre todo el tiempo.",
      "El viaje al pasado es mucho más problemático. Requeriría violar la causalidad o al menos crear líneas causales cerradas (bucles). La 'conjetura de protección de la cronología' de Hawking sugiere que las leyes de la física naturalmente previenen la formación de máquinas del tiempo. Pero esta conjetura no ha sido demostrada definitivamente.",
      "La exploración filosófica del tiempo tiene miles de años: desde los presocráticos griegos hasta los físicos cuánticos del siglo XXI. El tiempo ha fascinado a los pensadores porque toca algo profundamente personal: somos seres temporales, vivimos EN el tiempo, y ninguna pregunta sobre nuestra existencia puede separarse de la pregunta sobre el tiempo.",
      "Películas como 'Regreso al Futuro' hacen un servicio extraordinario al popularizar estas preguntas. Cuando Marty McFly se preocupa por no nacer si sus padres no se enamoran, el espectador intuye la paradoja temporal. Cuando Doc Brown dibuja las líneas del tiempo en una pizarra, el espectador vislumbra la complejidad del espacio-tiempo. El arte puede enseñar lo que ningún libro de texto puede."
    ],
    quiz: [
      { q: "¿Cómo definía Newton el tiempo?", options: ["Relativo y variable","Absoluto y uniforme para todos los observadores","Un producto de la conciencia","Una dimensión del espacio"], a: 1 },
      { q: "¿Qué es la 'simultaneidad relativa' de Einstein?", options: ["Que todos los eventos ocurren a la vez","Eventos simultáneos para un observador pueden no serlo para otro en movimiento","Que el tiempo es siempre el mismo","Que la luz siempre llega simultáneamente"], a: 1 },
      { q: "¿Por qué recordamos el pasado y no el futuro, según la física?", options: ["Por capacidades del cerebro","El pasado dejó huellas físicas; el futuro no ha ocurrido aún","Por la velocidad de la luz","Por la gravedad terrestre"], a: 1 },
      { q: "¿Qué es la 'conjetura de protección de la cronología' de Hawking?", options: ["Las leyes físicas previenen la formación de máquinas del tiempo","El tiempo siempre avanza","Los viajes al futuro son posibles","El tiempo puede revertirse"], a: 0 },
      { q: "¿El viaje al futuro ha sido observado directamente?", options: ["No, es solo teoría","Sí, en los muones cósmicos y los relojes de satélites GPS","Solo en laboratorio","Nunca ha sido verificado"], a: 1 }
    ]
  },
  bttf_m5: {
    text: [
      "Las paradojas del tiempo son uno de los temas más fascinantes de la física teórica y la filosofía. Una paradoja es una situación que parece contradictoria o absurda pero que puede seguir una lógica interna coherente. Las paradojas del tiempo surgen cuando imaginamos situaciones de viaje al pasado.",
      "La paradoja del abuelo es la más famosa: si viajas al pasado y evitas que tu abuelo conozca a tu abuela, tus padres nunca se conocerían y tú nunca nacerías. Pero si nunca naciste, nunca puedes hacer el viaje para matar a tu abuelo. Y si no hiciste el viaje, tu abuelo vivió y tú naciste. La contradicción es infinita.",
      "El principio de autoconsistencia de Novikov ofrece una resolución: solo son físicamente posibles las historias temporales que no crean paradojas. Si intentas matar a tu abuelo, algo (coincidencia, error de puntería, tu propia desaparición momentánea) siempre lo impedirá. El universo selecciona automáticamente las historias consistentes.",
      "Los bucles causales son versiones menos dramáticas de la paradoja del abuelo. Un bucle causal ocurre cuando A causa B que causa A. Por ejemplo: alguien del futuro viaja al pasado y le da la receta de la penicilina a Fleming, quien la descubre y la usa. ¿Quién inventó realmente la penicilina? La información existe sin origen claro.",
      "La paradoja del abuelo también puede resolverse con universos paralelos. Cuando viajas al pasado, no llegas a tu propio pasado sino a una rama del universo idéntica al pasado. En esa rama, matas a tu abuelo y tú nunca naces en ella. Pero en tu rama original, el viaje nunca interrumpió nada porque nunca ocurrió allí.",
      "La 'paradoja de la información' surge en los viajes al tiempo cuando la información existe sin origen. Si alguien del futuro te da los planos de la máquina del tiempo que usó para viajar, y tú la construyes y viajas al futuro para darte esos planos, ¿quién diseñó la máquina? La información existe en un bucle sin comenzar.",
      "Algunos físicos, como Igor Novikov y Kip Thorne, han explorado matemáticamente si los bucles causales son consistentes. Sus análisis sugieren que los bucles causales sin paradoja podrían ser físicamente permisibles. La información que existe en un bucle no viola ninguna ley física, aunque su origen sea circular.",
      "La mecánica cuántica añade otra dimensión a las paradojas temporales. En la interpretación de Copenhague, el futuro no existe de manera definida hasta que es observado. Si el futuro no existe, no puede enviar información al pasado. Sin embargo, en la interpretación de los muchos mundos, el futuro existe en todas sus ramas posibles simultáneamente.",
      "La 'paradoja del héroe' es cuando alguien viaja al pasado para salvar a alguien que de hecho fue salvado. El héroe llega al pasado y actúa, pero si no hubiera viajado, el resultado habría sido el mismo porque otro factor ya había salvado a la persona. El viaje fue innecesario pero no paradójico.",
      "Las paradojas del tiempo son útiles en la física teórica porque ayudan a identificar los límites de las teorías. Si una teoría permite paradojas (situaciones lógicamente contradictorias), probablemente esté incompleta. Las paradojas del tiempo señalan donde la relatividad y la mecánica cuántica necesitan una teoría más completa: la gravedad cuántica.",
      "La ficción ha explorado las paradojas temporales con creatividad extraordinaria. 'Regreso al Futuro', '12 Monkeys', 'Primer', 'Tenet', 'Looper' y muchas otras películas usan paradojas temporales como motor narrativo. Cada una propone una solución diferente (muchos mundos, autoconsistencia, determinismo) y todas revelan aspectos diferentes de la física del tiempo.",
      "La paradoja de la identidad personal también surge con los viajes temporales. Si tu versión futura viaja al pasado y convive contigo durante horas, ¿son dos personas diferentes o la misma? ¿Tienen las mismas memorias? ¿Los mismos derechos legales? Estos dilemas no son solo filosóficos: apuntan a problemas profundos de identidad en el tiempo.",
      "La paradoja del bootstrap (o bucle de información) en 'Regreso al Futuro' aparece cuando Marty, en el pasado, toca 'Johnny B. Goode' en el baile de sus padres. Marty sabía la canción de su época. Pero la canción fue escrita por Chuck Berry en 1958 (el año a donde viaja). La película sugiere que Marty puede haber inspirado a Berry, creando un bucle musical.",
      "Las paradojas nos recuerdan que la consistencia lógica es un requisito de la física. Una teoría que produce paradojas genuinas no puede ser una descripción correcta de la realidad. Si alguna vez se encuentra que los viajes al tiempo producen paradojas insolubles, eso sería evidencia de que son imposibles. Si no producen paradojas, podrían ser posibles.",
      "Al final, las paradojas temporales son una invitación a pensar más profundamente sobre el tiempo, la causalidad y la física. Son preguntas que unen la filosofía y la ciencia en su punto más emocionante: donde los conceptos más básicos de la realidad se vuelven misteriosos. Bienvenido al club de los que disfrutan los misterios del universo."
    ],
    quiz: [
      { q: "¿En qué consiste la paradoja del abuelo?", options: ["Que los abuelos son más sabios","Si evitas el nacimiento de tus padres en el pasado, tú nunca habrías nacido para hacer el viaje","Que el tiempo es diferente para cada generación","Que el pasado no puede cambiarse"], a: 1 },
      { q: "¿Qué propone el principio de autoconsistencia de Novikov?", options: ["Que todos los viajes al tiempo crean paradojas","Solo son posibles historias temporales que no crean paradojas","Que los viajes al tiempo son imposibles","Que el universo tiene múltiples ramas"], a: 1 },
      { q: "¿Qué es un bucle causal?", options: ["Un agujero de gusano circular","Cuando A causa B que causa A, sin origen claro","Una paradoja del abuelo resuelta","Una dimensión temporal extra"], a: 1 },
      { q: "¿Cómo resuelven los universos paralelos la paradoja del abuelo?", options: ["El abuelo nunca muere","Viajas a una rama diferente del universo, no a tu propio pasado","El tiempo se congela","Creas una copia de ti mismo"], a: 1 },
      { q: "¿Por qué las paradojas son útiles en física teórica?", options: ["Son entretenidas","Ayudan a identificar límites e incompletudes de las teorías","Son buenas para las películas","Demuestran que el tiempo existe"], a: 1 }
    ]
  },
  bttf_m6: {
    text: [
      "Las máquinas del tiempo han sido un sueño de la ciencia ficción desde que H.G. Wells publicó su novela 'La Máquina del Tiempo' en 1895. Wells imaginó una máquina que podía viajar físicamente a través del tiempo como un vehículo viaja a través del espacio. Esta imagen ha persistido en la cultura popular durante 130 años.",
      "Desde la perspectiva de la física, no existe ninguna razón teórica definitiva que haga completamente imposible el viaje en el tiempo. Sin embargo, los obstáculos prácticos son astronómicos. La relatividad permite el viaje al futuro (y lo observamos), pero el viaje al pasado requeriría o bien velocidades superluminales (imposibles) o bien estructuras topológicas del espacio-tiempo como los agujeros de gusano.",
      "Los agujeros de gusano pueden funcionar como máquinas del tiempo si uno de sus extremos se acelera o se coloca en un campo gravitacional fuerte durante un tiempo. Esto haría que los dos extremos del agujero de gusano existan en momentos diferentes del universo. Un viajero que cruzara el agujero de gusano estaría viajando en el tiempo.",
      "Sin embargo, hay un problema de 'horizonte': solo podrías viajar de regreso hasta el momento en que la máquina del tiempo fue creada. No podrías viajar antes de que la máquina existiera. Esto explicaría (en una teoría de viaje al tiempo) por qué no somos visitados por turistas del futuro: la primera máquina del tiempo aún no ha sido construida.",
      "El Theoretical Advance Warp Drive ('motor warp') de la ciencia ficción es otra idea que los físicos han explorado. En 1994, el físico Miguel Alcubierre propuso matemáticamente una forma de mover una región del espacio-tiempo más rápido que la luz sin que ningún objeto dentro de esa región viaje más rápido que la luz (violando así la relatividad especial en el sentido técnico pero no en el espíritu).",
      "El motor Alcubierre requeriría materia exótica en cantidades imposibles con la física conocida, y tendría otros problemas (radiación de Hawking en las paredes de la burbuja, incapacidad de controlarlo una vez iniciado). Pero demostró que las leyes de la física son más flexibles de lo que parecen cuando se aplican a estructuras del espacio-tiempo en sí mismas.",
      "La TARDIS del Doctor Who (máquina del tiempo con forma de cabina telefónica inglesa) es 'más grande por dentro que por fuera'. Esta idea tiene un referente en la física real: los espacios curvos del espacio-tiempo pueden parecer más pequeños desde afuera de lo que son por dentro. En un agujero negro, el volumen interior puede ser enorme aunque el horizonte de eventos sea pequeño.",
      "El DeLorean de 'Regreso al Futuro' es uno de los iconos más reconocibles de la ciencia ficción. El modelo real DMC-12 fue fabricado en Belfast, Irlanda del Norte, entre 1981 y 1983. Solo se fabricaron 9,000 unidades antes de que la empresa quebrara. Hoy los DeLorean originales son piezas de colección muy valiosas.",
      "El 'condensador de flujo' es el corazón de la máquina del tiempo del DeLorean. Doc Brown lo describe como 'lo que hace posible el viaje en el tiempo'. Aunque es ficción, el nombre captura algo real: el flujo de información, energía y causalidad a través del espacio-tiempo es lo que conecta el pasado, el presente y el futuro.",
      "Las máquinas del tiempo en la ficción suelen ser dispositivos que el individuo puede usar. En la realidad, si el viaje al pasado fuera posible, probablemente requeriría instalaciones civilizatorias: la energía equivalente a una estrella, estructuras macroscópicas de espacio-tiempo, y tecnologías que solo una civilización de tipo III en la escala de Kardashev podría manejar.",
      "Los agentes del tiempo y los guardianes de la historia son personajes ficticios que previenen cambios no autorizados en el pasado. Aunque ficticios, representan un problema real: si el viaje al pasado fuera posible, ¿quién controlaría quién puede hacerlo y qué puede cambiar? La gobernanza temporal sería el mayor desafío ético y político de la historia.",
      "La paradoja del turista del futuro (¿por qué no vienen turistas del futuro a visitarnos?) tiene varias respuestas posibles: los viajes al tiempo son imposibles, requieren tecnología tan avanzada que nadie los usa para turismo, las máquinas del tiempo solo pueden ir al presente de quien las construye, o quizás nos visitan pero de manera imperceptible.",
      "El tiempo en la narrativa tiene una función diferente al tiempo en la física. En la narrativa, el tiempo puede comprimirse (resúmenes), expandirse (escenas en cámara lenta), invertirse (flashbacks) o ramificarse (historias paralelas). Estas herramientas narrativas nos ayudan a entender el tiempo de maneras que la física pura no puede.",
      "La relación entre física y narrativa es bidireccional. La física cuántica adoptó metáforas narrativas (el 'observador', los 'muchos mundos') que facilitan la comunicación de ideas. La narrativa adoptó conceptos físicos (la 'burbuja temporal', la 'línea de tiempo') para explorar posibilidades humanas. Las dos formas de conocimiento se enriquecen mutuamente.",
      "Al reflexionar sobre las máquinas del tiempo, nos preguntamos también qué querríamos cambiar del pasado si pudiéramos. Esta pregunta es profundamente filosófica: ¿Hay cosas que no deberían cambiarse aunque pudiéramos? ¿Estaríamos mejor si no hubiera guerras o si todos los errores hubieran sido evitados? La 'Regreso al Futuro' sugiere que el presente, con todos sus defectos, es el resultado de una historia que debemos respetar."
    ],
    quiz: [
      { q: "¿Quién escribió 'La Máquina del Tiempo', la primera novela sobre viaje temporal?", options: ["Jules Verne","Isaac Asimov","H.G. Wells","Arthur C. Clarke"], a: 2 },
      { q: "¿Qué propuso el físico Miguel Alcubierre en 1994?", options: ["Un motor que viaja al pasado","Una forma matemática de mover el espacio-tiempo más rápido que la luz","Una máquina del tiempo cuántica","Un agujero de gusano artificial"], a: 1 },
      { q: "¿Por qué un agujero de gusano puede ser una máquina del tiempo?", options: ["Porque está fuera del espacio-tiempo","Si un extremo se acelera, los dos extremos existen en momentos diferentes","Porque conecta universos paralelos","Porque absorbe la luz del tiempo"], a: 1 },
      { q: "¿Cuántas unidades del DeLorean DMC-12 real se fabricaron?", options: ["100","1,000","9,000","50,000"], a: 2 },
      { q: "¿Por qué no podríamos viajar a fechas anteriores a la creación de la máquina del tiempo?", options: ["Por razones de combustible","No habría punto de llegada antes de que la máquina existiera","El motor no funciona en el pasado lejano","La paradoja del abuelo lo impediría"], a: 1 }
    ]
  },
  bttf_m7: {
    text: [
      "La trilogía 'Regreso al Futuro' nos lleva desde 1985 a 1955, 2015, y 1885, explorando cómo diferentes épocas tienen diferentes tecnologías, normas sociales y visiones del mundo. Esta perspectiva histórica comparada es uno de los mayores valores educativos de la serie.",
      "La ciencia no es solo conocimiento: es un método de descubrimiento. El método científico —observar, hipotetizar, experimentar, analizar, concluir y verificar— es la herramienta más poderosa que la humanidad ha desarrollado para entender la realidad. Doc Brown aplica este método instintivamente: observa que tiene un problema, formula hipótesis, prueba soluciones.",
      "La curiosidad es el motor de la ciencia. Sin curiosidad, no hay preguntas; sin preguntas, no hay descubrimiento. Einstein decía que lo más importante no era el conocimiento sino la imaginación. Doc Brown encarna esta filosofía: un científico que imagina lo imposible (una máquina del tiempo) y luego trabaja sistemáticamente para hacerlo realidad.",
      "El fracaso es parte esencial del método científico. Doc Brown falla muchas veces antes de que el condensador de flujo funcione. Esta representación del fracaso como parte normal del proceso científico es pedagógicamente valiosa: los niños que ven la película aprenden que los científicos no tienen éxito en el primer intento.",
      "La colaboración es otro tema central de la trilogía. Doc y Marty resuelven problemas que ninguno podría resolver solo: Doc tiene el conocimiento teórico, Marty tiene energía, intuición y valentía. La ciencia real también es colaborativa: los grandes descubrimientos generalmente involucran equipos de personas con habilidades complementarias.",
      "La física de la electricidad es central en la primera película: un rayo proporciona los 1.21 gigavatios necesarios para el viaje. Los rayos son uno de los fenómenos eléctricos naturales más poderosos: pueden alcanzar 1,000 megavatios de potencia en un instante, con temperaturas de 30,000°C. Son literalmente pequeños rayos de plasma.",
      "Benjamin Franklin fue uno de los primeros científicos en estudiar sistemáticamente la electricidad. Su famoso experimento con una cometa en 1752 demostró que los rayos son electricidad. Pero la leyenda que muestra a Franklin subiendo una cometa en una tormenta eléctrica minimiza el peligro real: Franklin usó una cometa en un campo abierto con precauciones cuidadosas.",
      "Tesla y Edison tuvieron la 'guerra de las corrientes' a finales del siglo XIX: Edison defendía la corriente continua (DC) y Tesla la alterna (AC). Tesla y Westinghouse ganaron cuando demostraron que la AC podía transmitirse a larga distancia de manera mucho más eficiente. La energía eléctrica que llega a tu casa hoy es AC gracias a Tesla.",
      "Los semiconductores son la base de toda la electrónica moderna: computadoras, smartphones, paneles solares, LED. Los semiconductores permiten controlar el flujo de electricidad a nivel atómico. Sin ellos, no existiría la revolución digital. Los primeros transistores de semiconductores fueron inventados en 1947 en Bell Labs por Shockley, Bardeen y Brattain.",
      "La inteligencia artificial (IA) es la tecnología que más ha cambiado el mundo en los últimos años. Los algoritmos de IA aprenden de datos masivos para reconocer patrones, traducir idiomas, generar imágenes, y diagnosticar enfermedades. La IA no es magia: es estadística muy sofisticada ejecutada en chips de semiconductores muy rápidos.",
      "La biotecnología es otra frontera de la ciencia moderna. La edición genética CRISPR-Cas9, descubierta en 2012, permite modificar el ADN con una precisión sin precedentes. Podría eliminar enfermedades hereditarias, crear cultivos más resistentes y quizás, en el futuro, extender la vida humana. Sus implicaciones éticas son tan enormes como sus potenciales beneficios.",
      "La exploración espacial ha dado saltos enormes en años recientes. El telescopio James Webb, lanzado en 2021, nos da imágenes del universo con una resolución sin precedentes, viendo galaxias a 13,000 millones de años luz. SpaceX ha hecho que viajar al espacio sea más barato. El turismo espacial ya existe. El viaje a Marte es un objetivo realista para los próximos 20 años.",
      "La sostenibilidad es el gran desafío de la ciencia del siglo XXI. El cambio climático, la pérdida de biodiversidad, la contaminación y el agotamiento de recursos requieren soluciones científicas urgentes. Los científicos trabajan en energías renovables, captura de carbono, materiales biodegradables y sistemas agrícolas sostenibles. Nunca ha habido más necesidad de buenos científicos.",
      "Tú, que estudias este curso, eres parte de la generación que enfrentará y (esperamos) resolverá estos desafíos. La física, la química, la biología, la informática y las matemáticas que aprendes ahora son las herramientas que necesitas. No sabemos qué descubrimientos harás, pero sabemos que los descubrimientos del futuro dependen de jóvenes como tú.",
      "Al terminar este recorrido por la ciencia de 'Regreso al Futuro', recuerda lo esencial: la ciencia no es solo información en libros. Es una forma de pensar: curiosa, rigurosa, creativa, honesta y colaborativa. Es la aventura más grande que puede emprender un ser humano. Y como dijo Doc Brown: '¡El futuro aún no está escrito!' Escríbelo tú."
    ],
    quiz: [
      { q: "¿Cuál es el método científico en el orden correcto?", options: ["Concluir, observar, experimentar","Observar, hipotetizar, experimentar, analizar, concluir","Hipotetizar, concluir, observar","Experimentar, hipotetizar, observar"], a: 1 },
      { q: "¿Quién demostró que los rayos son electricidad?", options: ["Nikola Tesla","Thomas Edison","Benjamin Franklin","Michael Faraday"], a: 2 },
      { q: "¿Qué tecnología de edición genética fue descubierta en 2012?", options: ["PCR","CRISPR-Cas9","Secuenciación de ADN","Clonación"], a: 1 },
      { q: "¿En qué año se lanzó el telescopio espacial James Webb?", options: ["2015","2018","2021","2023"], a: 2 },
      { q: "¿Quién ganó la 'guerra de las corrientes' entre Edison y Tesla?", options: ["Edison con la corriente continua","Tesla con la corriente alterna","Empataron","Ninguno de los dos"], a: 1 }
    ]
  }
};

for (const [id, data] of Object.entries(BTTF)) {
  src = replaceTextAndQuiz(src, id, data.text, data.quiz);
}

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ BTTF (m1-m7) all patched!');
