const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, '../lib/courseData.js');
let src = fs.readFileSync(FILE, 'utf8');

function patchModule(src, moduleId, newText, newQuiz) {
  const modIdx = src.indexOf(`"id": "${moduleId}"`);
  if (modIdx === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  const sectionsIdx = src.indexOf('"sections"', modIdx);
  const textIdx = src.indexOf('"text"', sectionsIdx);
  const arrOpen = src.indexOf('[', textIdx);
  let depth = 0, i = arrOpen;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  src = src.slice(0, arrOpen) + JSON.stringify(newText, null, 12) + src.slice(i + 1);

  const modIdx2 = src.indexOf(`"id": "${moduleId}"`);
  const quizIdx = src.indexOf('"quizEs"', modIdx2);
  const nextModIdx = src.indexOf('"id": "', modIdx2 + 10);
  if (quizIdx !== -1 && (nextModIdx === -1 || quizIdx < nextModIdx)) {
    const qArrOpen = src.indexOf('[', quizIdx);
    let d2 = 0, j = qArrOpen;
    while (j < src.length) {
      if (src[j] === '[') d2++;
      else if (src[j] === ']') { d2--; if (d2 === 0) break; }
      j++;
    }
    src = src.slice(0, qArrOpen) + JSON.stringify(newQuiz, null, 4) + src.slice(j + 1);
  } else if (newQuiz) {
    // Insert quizEs before closing brace of module
    const modStart = src.indexOf(`"id": "${moduleId}"`);
    const closingBrace = src.indexOf('\n  }', modStart);
    src = src.slice(0, closingBrace) + ',\n    "quizEs": ' + JSON.stringify(newQuiz, null, 4) + src.slice(closingBrace);
  }
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// copernico_m1 - El universo antes de Copérnico
src = patchModule(src, 'copernico_m1', [
  "¡Bienvenido, viajero del tiempo astronómico! Hoy vamos a explorar cómo entendían el universo los seres humanos antes de que llegara un brillante astrónomo polaco llamado Nicolás Copérnico. Imagina que vives en la Europa del siglo XV: no hay televisión, no hay internet, no hay telescopios, pero sí hay un cielo nocturno absolutamente espectacular, lleno de estrellas que nadie contamina con luces artificiales. Cada noche puedes ver la Vía Láctea completa como una banda de luz plateada cruzando el cielo. Y observando ese cielo maravilloso, los sabios de la época intentaban entender el universo.",
  "La idea que dominaba el pensamiento científico era el modelo geocéntrico: 'geo' significa Tierra, y 'céntrico' significa en el centro. Así que el modelo geocéntrico decía que la Tierra estaba quieta, fija, en el centro del universo, y que todo lo demás, el Sol, la Luna, los planetas y las estrellas, giraba alrededor de ella. Esta idea parecía perfectamente lógica: si te paras en un campo y miras el cielo, efectivamente parece que todo se mueve alrededor de ti y tú estás quieto. Nuestros sentidos nos engañan completamente.",
  "El modelo geocéntrico más elaborado fue creado por el astrónomo griego Claudio Ptolomeo alrededor del año 150 d.C. Ptolomeo era extraordinariamente inteligente y observador. Para explicar por qué los planetas a veces parecen moverse hacia atrás en el cielo (lo que llamamos movimiento retrógrado), inventó un sistema de círculos dentro de círculos llamados epiciclos. Era un sistema matemático muy complejo pero funcionaba: podía predecir con bastante precisión dónde estaría cada planeta en el cielo.",
  "El sistema de Ptolomeo fue usado durante más de 1,300 años. Piensa en eso: durante catorce siglos, generaciones y generaciones de astrónomos calcularon posiciones de planetas usando las fórmulas de Ptolomeo. Las universidades medievales lo enseñaban como verdad absoluta. La Iglesia Católica también lo adoptó porque encajaba con la idea de que Dios había puesto a la Tierra, y por tanto a la humanidad, en el centro del universo. Cambiar esta idea no iba a ser nada fácil.",
  "Uno de los problemas del modelo de Ptolomeo era que para que funcionara correctamente, necesitabas agregar cada vez más correcciones y ajustes complicados. Los planetas no seguían exactamente las trayectorias predichas, así que los astrónomos medievales tenían que agregar más epiciclos y correcciones matemáticas constantemente. Era como intentar explicar algo con una historia que se vuelve cada vez más complicada: una señal de que quizás la historia fundamental no es correcta.",
  "En la antigua Grecia, antes de Ptolomeo, ya hubo pensadores que propusieron ideas diferentes. Aristarco de Samos, alrededor del año 270 a.C., propuso que era el Sol el que estaba en el centro y que la Tierra giraba alrededor de él. ¡Era correcto! Pero en su época no lo pudieron demostrar con suficiente rigor matemático y la idea fue descartada. La historia de la ciencia muestra que tener la idea correcta no es suficiente: también necesitas la manera de demostrarlo.",
  "Durante la Edad Media en Europa, el conocimiento astronómico de los griegos fue preservado y expandido principalmente por astrónomos árabes. Nombres como Al-Battani, Ibn al-Haytham y Al-Biruni realizaron observaciones precisas y corrigieron muchos de los errores de Ptolomeo. También tradujeron los textos griegos al árabe, y más tarde esas traducciones árabes fueron traducidas al latín para las universidades europeas. Sin los árabes, mucho del conocimiento astronómico antiguo se hubiera perdido.",
  "En la Europa del siglo XV, los navegantes y exploradores necesitaban astronomía precisa para cruzar los océanos. Colón cruzó el Atlántico en 1492 usando tablas astronómicas para navegar. Los marinos calculaban su posición observando las estrellas con instrumentos como el astrolabio y el cuadrante. Esta necesidad práctica de astronomía precisa creó presión para mejorar los modelos del universo. Los errores del sistema de Ptolomeo, aunque pequeños, se acumulaban en viajes largos y podían llevar a los barcos fuera de curso.",
  "También era importante la astronomía para el calendario. La Iglesia Católica necesitaba calcular exactamente cuándo caía la Pascua cada año, y el calendario que usaban (el calendario juliano) tenía pequeños errores que se acumulaban con los siglos. Para corregir el calendario necesitaban entender mejor los movimientos del Sol y la Tierra. Esta necesidad práctica religiosa fue una de las razones por las que el Papa encargó a astrónomos que mejoraran los modelos astronómicos, sin saber que eso llevaría a una revolución científica.",
  "Fue en este contexto, a finales del siglo XV y principios del XVI, cuando nació y creció Nicolás Copérnico. Europa estaba en pleno Renacimiento: un período de enorme creatividad intelectual donde los artistas, escritores y pensadores cuestionaban ideas antiguas y exploraban nuevas. Leonardo da Vinci pintaba sus obras maestras, Gutenberg había inventado la imprenta, y los descubrimientos geográficos de Colón, Magallanes y otros mostraban que el mundo era mucho más grande de lo que se creía.",
  "Copérnico estudió en las mejores universidades de la época: primero en Cracovia, Polonia, y luego en Bologna y Padua, en Italia. En esas universidades aprendió astronomía, matemáticas, medicina y derecho. Era un estudiante brillante con una mente capaz de manejar cálculos matemáticos enormemente complejos. Y mientras estudiaba el sistema de Ptolomeo, comenzó a notar que era demasiado complicado, demasiado lleno de correcciones artificiales. Algo le decía que debía haber una explicación más elegante y simple.",
  "La elegancia matemática era algo muy valorado por los matemáticos y astrónomos del Renacimiento. Una buena teoría científica debía ser no solo correcta sino también bella: simple, poderosa, capaz de explicar mucho con pocas suposiciones. El sistema de Ptolomeo era lo opuesto: complejo, lleno de parches y correcciones, una pesadilla matemática. Copérnico comenzó a preguntarse: ¿y si la razón por la que el sistema es tan complicado es que tenemos la idea fundamental equivocada?",
  "En sus notas privadas, Copérnico comenzó a explorar la posibilidad de que fuera la Tierra la que giraba alrededor del Sol y no al revés. Pronto descubrió que con esta simple suposición, muchas de las complicaciones del sistema de Ptolomeo desaparecían mágicamente. El movimiento retrógrado de los planetas, por ejemplo, se explicaba de manera natural: simplemente era un efecto óptico de que la Tierra se mueve más rápido que los planetas exteriores en sus órbitas alrededor del Sol.",
  "Pero Copérnico era un hombre cauteloso. Sabía que su idea era radical y que encontraría oposición fuerte de la Iglesia y de los astrónomos tradicionales. Pasó décadas refinando sus cálculos, verificando sus predicciones contra las observaciones reales, y perfeccionando su modelo matemático. No quería publicar hasta estar absolutamente seguro de sus resultados. Esta cautela científica es admirable: prefería tomarse el tiempo necesario para hacer un trabajo sólido antes de presentarlo al mundo.",
  "La historia que ocurrió antes de Copérnico nos enseña que las ideas científicas tienen un contexto histórico. Las ideas no surgen de la nada: brotan de las necesidades, los problemas y las conversaciones de su época. Ptolomeo respondía a las preguntas de su tiempo, y Copérnico respondía a las de la suya. La ciencia no es una colección de verdades fijas sino una conversación continua que va mejorando nuestro entendimiento del mundo. Y en esa conversación, cada generación tiene su parte que aportar."
], [
  { q: "¿Qué significa el modelo 'geocéntrico' del universo?", options: ["El Sol está en el centro", "La Luna está en el centro", "La Tierra está en el centro", "Las estrellas están en el centro"], a: 2 },
  { q: "¿Quién creó el modelo geocéntrico más elaborado alrededor del año 150 d.C.?", options: ["Aristarco", "Ptolomeo", "Copérnico", "Galileo"], a: 1 },
  { q: "¿Cómo se llaman los círculos dentro de círculos que usaba Ptolomeo para explicar el movimiento de los planetas?", options: ["Espirales", "Parábolas", "Epiciclos", "Elipses"], a: 2 },
  { q: "¿Quién fue el antiguo griego que ya había propuesto que el Sol estaba en el centro, antes de Copérnico?", options: ["Aristóteles", "Platón", "Ptolomeo", "Aristarco de Samos"], a: 3 },
  { q: "¿Dónde estudió Copérnico en Italia para aprender astronomía y matemáticas?", options: ["Roma y Florencia", "Venecia y Milán", "Bologna y Padua", "Nápoles y Génova"], a: 2 }
]);

// copernico_m2 - La revolución heliocéntrica
src = patchModule(src, 'copernico_m2', [
  "¡Prepárate para presenciar el momento en que el mundo cambió para siempre! En este módulo vamos a explorar la gran revolución de Copérnico: su propuesta de que el Sol, y no la Tierra, está en el centro del sistema solar. Esta idea, que hoy nos parece obvia, fue en su tiempo tan radical como decirle a alguien hoy que el cielo es verde. Requirió un coraje intelectual enorme y cambió el rumbo de toda la ciencia humana.",
  "El término 'heliocéntrico' viene del griego 'helios' que significa Sol, y 'céntrico' que significa en el centro. Así que el modelo heliocéntrico de Copérnico proponía que el Sol era el cuerpo central del sistema solar y que todos los planetas, incluyendo la Tierra, giraban alrededor de él. Aunque no era completamente correcto (sabemos que el Sol tampoco está exactamente en el centro del universo), era un salto gigantesco en la dirección correcta.",
  "Copérnico no llegó a esta conclusión de repente: fue un proceso de años de cálculos y reflexión. Su punto de partida fue observar que el sistema de Ptolomeo era innecesariamente complicado. Los matemáticos del Renacimiento creían en un principio llamado 'la navaja de Ockham': si dos explicaciones predicen lo mismo, la más simple es probablemente la correcta. El modelo heliocéntrico explicaba los movimientos planetarios de forma mucho más elegante y simple.",
  "Una de las grandes victorias del modelo heliocéntrico fue explicar naturalmente el movimiento retrógrado de los planetas. En el modelo de Ptolomeo, los planetas a veces parecen moverse hacia atrás en el cielo, y explicar esto requería los complicados epiciclos. Pero en el modelo heliocéntrico, la explicación es simple: cuando la Tierra, que se mueve más rápido, 'adelanta' a un planeta exterior en sus órbitas alrededor del Sol, ese planeta parece moverse hacia atrás. Es pura perspectiva, como cuando adelantas a otro auto en la autopista y parece que él va hacia atrás.",
  "Copérnico también pudo calcular correctamente el orden de los planetas y sus distancias relativas al Sol. Determinó que Mercurio y Venus están más cerca del Sol que la Tierra, lo que explicaba por qué nunca los vemos en el lado opuesto del Sol en el cielo. Calculó que Marte, Júpiter y Saturno están más lejos, lo que explicaba sus movimientos más lentos. Por primera vez en la historia, el orden del sistema solar tenía una explicación física racional.",
  "Una predicción audaz de Copérnico fue que la Tierra gira sobre su propio eje una vez al día, lo que explica por qué el Sol, la Luna y las estrellas parecen girar alrededor de la Tierra. Esta idea era contraintuitiva: si la Tierra girara, ¿no sentiríamos ese movimiento? ¿No saldría volando todo lo que está en la superficie? Copérnico argumentó que todo en la Tierra, incluyendo el aire y los objetos que se lanzan al aire, participa del mismo movimiento rotacional y por eso no lo sentimos.",
  "La magnitud del movimiento de la Tierra que propuso Copérnico era impresionante. La Tierra gira alrededor del Sol a una velocidad de aproximadamente 107,000 kilómetros por hora. Y rota sobre su propio eje a 1,670 kilómetros por hora en el ecuador. Estas velocidades son enormes, pero no las sentimos porque todo a nuestro alrededor se mueve junto con nosotros. Es como estar en un avión que vuela a 900 km/h: mientras el movimiento sea suave y constante, sientes que estás quieto.",
  "Copérnico tardó muchos años en compartir su teoría con el mundo. Circuló primero un resumen corto llamado el Commentariolus entre sus amigos y colegas de confianza. Las reacciones fueron mixtas: algunos quedaron fascinados por la elegancia matemática, otros escépticos, y algunos indignados. Pero la idea comenzó a circular en los círculos intelectuales de Europa, generando debates y discusiones que prepararon el terreno para la publicación de su obra completa.",
  "La resistencia que encontró Copérnico no era solo religiosa: también era científica. Muchos astrónomos de la época señalaban un problema real: si la Tierra se movía alrededor del Sol, las estrellas deberían mostrar algo llamado 'paralaje estelar', un pequeño cambio aparente en su posición a medida que la Tierra cambia su perspectiva durante el año. Copérnico respondió correctamente que las estrellas son tan lejanas que ese paralaje es demasiado pequeño para medir con los instrumentos de la época. Tenía razón, pero eso no se pudo confirmar hasta el siglo XIX.",
  "Uno de los aspectos más revolucionarios de la propuesta de Copérnico fue el desplazamiento filosófico que implicaba. Durante siglos, los seres humanos habían creído que ocupaban un lugar privilegiado en el universo: el centro. La Tierra era el escenario principal de la creación divina. Copérnico dijo que no, que la Tierra era solo uno de varios planetas que giran alrededor del Sol. Este 'destronamiento' de la humanidad de su posición central en el cosmos fue tan impactante como la idea astronómica en sí.",
  "El modelo heliocéntrico de Copérnico no era perfecto. Él seguía creyendo que las órbitas de los planetas eran círculos perfectos, cuando en realidad son elipses (óvalo). Esta suposición lo obligó a mantener algunas correcciones matemáticas del sistema de Ptolomeo. Las órbitas elípticas fueron descubiertas décadas después por Johannes Kepler, quien usó el trabajo de Copérnico como base pero lo mejoró con las observaciones precisísimas de Tycho Brahe. La ciencia avanza paso a paso, cada generación construyendo sobre el trabajo de la anterior.",
  "El nombre de Copérnico para la teoría heliocéntrica aparece en su obra cumbre, que analizaremos en el próximo módulo. Pero vale mencionar que Copérnico no usó el término 'revolución' en sentido político: simplemente describía los movimientos circulares de los planetas. Fue el tiempo quien convirtió su trabajo en 'la revolución copernicana', porque efectivamente revolucionó nuestra comprensión del cosmos. Hoy el término 'revolución copernicana' se usa metafóricamente para describir cualquier cambio radical en cómo pensamos sobre algo.",
  "La influencia de la revolución copernicana fue más allá de la astronomía. Al demostrar que la Tierra se mueve y que nuestros sentidos pueden engañarnos sobre la naturaleza de la realidad, Copérnico inició una era de cuestionamiento sistemático de las ideas tradicionales. Si habíamos estado equivocados sobre algo tan fundamental como la posición de la Tierra, ¿en qué otras cosas podríamos estar equivocados? Esta actitud de cuestionamiento crítico es la esencia del método científico moderno.",
  "Copérnico también fue un pionero en su manera de hacer ciencia. En lugar de solo aceptar las autoridades del pasado, decidió observar, medir y calcular por sí mismo. No tenía un telescopio, solo sus ojos y algunos instrumentos simples de medición. Pero los usó con paciencia y rigor durante décadas para construir su caso. Nos enseñó que la autoridad en ciencia no viene de ser famoso o antiguo sino de la calidad de las observaciones y los argumentos lógicos que las respaldan.",
  "La revolución heliocéntrica de Copérnico cambió para siempre la posición de la humanidad en el universo. Ya no éramos el centro de todo: éramos habitantes de un planeta que orbita una estrella ordinaria. Esto podría haber sido deprimente, pero también fue liberador. Nos abrió a la idea de que el universo es un lugar inmenso y maravilloso, lleno de otros soles, otros planetas y posiblemente otras formas de vida. La pequeñez de nuestra posición nos hace preguntarnos sobre la grandeza del todo."
], [
  { q: "¿Qué significa el modelo 'heliocéntrico'?", options: ["La Tierra en el centro", "La Luna en el centro", "El Sol en el centro", "Las estrellas en el centro"], a: 2 },
  { q: "¿Cómo explicó el modelo heliocéntrico el movimiento retrógrado de los planetas?", options: ["Con epiciclos matemáticos", "Como un efecto de perspectiva al adelantar la Tierra a los planetas exteriores", "Con la atracción de la Luna", "Por las mareas del Sol"], a: 1 },
  { q: "¿A qué velocidad aproximada orbita la Tierra alrededor del Sol?", options: ["10,000 km/h", "50,000 km/h", "107,000 km/h", "300,000 km/h"], a: 2 },
  { q: "¿Cuál era el error principal en el modelo heliocéntrico de Copérnico?", options: ["Pensaba que el Sol giraba", "Creía que las órbitas eran círculos perfectos en vez de elipses", "No incluía a la Luna", "Ignoraba a Saturno"], a: 1 },
  { q: "¿Cómo se llama el documento corto que Copérnico circuló primero entre amigos antes de publicar su libro?", options: ["Heliocentricus", "Commentariolus", "Orbium Coelestium", "Revolutionibus"], a: 1 }
]);

// copernico_m3 - De Revolutionibus Orbium Coelestium
src = patchModule(src, 'copernico_m3', [
  "¡Hola, explorador del conocimiento! Hoy vamos a conocer el libro más importante de la historia de la astronomía: 'De Revolutionibus Orbium Coelestium', cuyo título en español significa 'Sobre las Revoluciones de las Esferas Celestes'. Este libro, publicado en 1543, cambió para siempre nuestra comprensión del universo. Es considerado por muchos científicos e historiadores como el punto de inicio de la revolución científica moderna.",
  "Copérnico tardó casi treinta años en escribir y perfeccionar este libro. Lo inició alrededor de 1510 y lo completó hacia 1530, pero no lo publicó de inmediato. Era un hombre perfeccionista que no quería presentar al mundo una obra a medias. Durante esos años revisó sus cálculos una y otra vez, incorporó observaciones nuevas, y refinó sus argumentos matemáticos. También temía la reacción que podría generar, especialmente por parte de la Iglesia Católica.",
  "El libro está dividido en seis partes llamadas libros. El primero expone la idea general del modelo heliocéntrico y los argumentos filosóficos y matemáticos en su favor. Los libros siguientes van entrando en detalles técnicos cada vez más complejos: los movimientos del Sol, de la Luna, y de cada uno de los cinco planetas conocidos en la época: Mercurio, Venus, Marte, Júpiter y Saturno. Era una obra monumental que cubría todo el conocimiento astronómico de la época.",
  "Una característica notable del libro es que está lleno de matemáticas muy avanzadas. Copérnico no escribió para el público general sino para astrónomos y matemáticos profesionales. Usó geometría esférica, trigonometría y álgebra para respaldar cada afirmación con demostraciones matemáticas precisas. Este rigor matemático fue crucial: aunque las autoridades podían rechazar la idea filosófica, les era difícil refutar los cálculos matemáticos que la respaldaban.",
  "Una figura clave en la publicación del libro fue Georg Rheticus, un joven matemático alemán que viajó desde Wittenberg hasta Frauenburg, en Polonia, para conocer a Copérnico en 1539. Rheticus quedó tan impresionado con el trabajo de Copérnico que pasó dos años con él aprendiendo la teoría. Fue él quien convenció a Copérnico de que publicara el libro completo, no solo el resumen que había circulado. Sin Rheticus, quizás nunca hubiéramos conocido la obra completa de Copérnico.",
  "La historia de cómo llegó el libro a la imprenta es dramática. Copérnico, ya viejo y enfermo, no pudo supervisar la publicación en Nuremberg personalmente. Lo hizo Andreas Osiander, un teólogo protestante que tomó una decisión controversial: escribió un prólogo no autorizado en el que presentaba el modelo heliocéntrico no como una verdad real sino como un 'modelo matemático útil para los cálculos'. Copérnico nunca vio ese prólogo antes de que el libro fuera impreso.",
  "Existe la famosa historia de que Copérnico recibió los primeros ejemplares del libro impreso el mismo día de su muerte, el 24 de mayo de 1543. Aunque los historiadores debaten si realmente pudo ver el libro terminado o solo lo tocó mientras estaba inconsciente, la imagen es poderosa: el hombre que cambió nuestra visión del cosmos dejando este mundo justo cuando su obra máxima llegaba al mundo. Es una de las historias más dramáticas de la historia de la ciencia.",
  "Inicialmente, el libro no causó la tormenta que Copérnico temía. Los astrónomos lo leían principalmente por sus tablas matemáticas, que eran más precisas que las del sistema ptolemaico, sin necesariamente aceptar la interpretación física del modelo heliocéntrico. El prólogo de Osiander había ayudado a 'suavizar' la recepción del libro al presentarlo como un ejercicio matemático, no como una afirmación sobre la realidad física del cosmos.",
  "La Iglesia Católica no puso el libro en el Índice de Libros Prohibidos hasta 1616, ¡setenta y tres años después de su publicación! Esto muestra que inicialmente la reacción institucional no fue de condena inmediata. Lo que cambió la situación fue Galileo: cuando Galileo usó las observaciones telescópicas para defender el modelo copernicano en los años 1610, la Iglesia reaccionó duramente y entonces sí prohibió el libro de Copérnico hasta 1835.",
  "El título del libro, 'Revoluciones', es interesante. En latín, 'revolutio' se refería al movimiento circular de los planetas alrededor del Sol, no a un cambio político o social radical. Pero la palabra adoptó ese significado más amplio precisamente gracias al impacto de este libro. Hoy cuando decimos que algo es 'revolucionario' o que ocurrió una 'revolución', usamos inadvertidamente el vocabulario que Copérnico popularizó con su obra astronómica.",
  "Las tablas astronómicas incluidas en el libro de Copérnico, llamadas tablas prutenicas, fueron adoptadas rápidamente por astrónomos de toda Europa porque eran más precisas que las tablas existentes basadas en el sistema de Ptolomeo. Los navegantes las usaban para calcular posiciones de estrellas. Los cronistas para establecer calendarios. Los médicos, que en esa época usaban la astrología como parte de su práctica, las necesitaban para sus horóscopos. La utilidad práctica del libro le ganó aceptación antes que la idea filosófica.",
  "El impacto del libro de Copérnico en la educación fue gradual pero profundo. A medida que las décadas pasaron y más astrónomos estudiaron el modelo heliocéntrico, fue ganando adeptos. Tycho Brahe lo estudió pero propuso su propio modelo híbrido. Johannes Kepler lo abrazó y lo perfeccionó con sus leyes de las órbitas elípticas. Galileo lo defendió públicamente usando el telescopio. Isaac Newton lo explicó con su teoría de la gravedad. Cada genio posterior construyó sobre los cimientos que Copérnico había puesto.",
  "La importancia histórica del libro es difícil de exagerar. Inició la revolución científica, un período de 150 años durante el cual la ciencia moderna se desarrolló. Antes de Copérnico, la ciencia europea estaba atrapada en la autoridad de los textos antiguos. Después de Copérnico, los científicos comenzaron a confiar más en la observación y el razonamiento matemático que en lo que decían los libros tradicionales. Este cambio de mentalidad es la base de toda la ciencia que existe hoy.",
  "El libro de Copérnico también es un ejemplo del poder de la perseverancia intelectual. Trabajar treinta años en un proyecto, revisándolo y mejorándolo constantemente, sin la certeza de que sería bien recibido, requiere una determinación extraordinaria. Copérnico creyó en su trabajo lo suficiente como para dedicarle décadas de su vida. Nos enseña que las grandes ideas requieren tiempo, paciencia y trabajo duro para madurar hasta que son lo suficientemente sólidas para cambiar el mundo.",
  "Hoy puedes ver ejemplares originales del 'De Revolutionibus Orbium Coelestium' en algunas de las bibliotecas y museos más importantes del mundo. Científicos del proyecto 'Book That Changed the Universe' han catalogado y estudiado todos los ejemplares sobrevivientes, encontrando las notas y marcas que los primeros lectores hicieron en sus márgenes. Leer esas notas es como tener una ventana al momento exacto en que una idea radical comenzó a cambiar mentes y, con ellas, el mundo."
], [
  { q: "¿Cuándo se publicó 'De Revolutionibus Orbium Coelestium'?", options: ["1410", "1492", "1543", "1610"], a: 2 },
  { q: "¿Quién convenció a Copérnico de publicar su libro completo?", options: ["Galileo Galilei", "Johannes Kepler", "Georg Rheticus", "Tycho Brahe"], a: 2 },
  { q: "¿Quién escribió el prólogo no autorizado que presentaba el modelo como solo un 'modelo matemático'?", options: ["Georg Rheticus", "Andreas Osiander", "Johannes Kepler", "Papa Paulo III"], a: 1 },
  { q: "¿Cuántos años después de su publicación puso la Iglesia Católica el libro de Copérnico en el Índice de Libros Prohibidos?", options: ["10 años", "30 años", "50 años", "73 años"], a: 3 },
  { q: "¿Cómo se llamaban las tablas astronómicas incluidas en el libro de Copérnico?", options: ["Tablas ptolemaicas", "Tablas brutas", "Tablas prutenicas", "Tablas copernicanas"], a: 2 }
]);

// copernico_m4 - Astronomía a ojo desnudo
src = patchModule(src, 'copernico_m4', [
  "¡Cadete, imagina hacer astronomía sin ningún instrumento óptico! Eso fue exactamente lo que hizo Copérnico: cambió nuestra visión del universo usando solo sus ojos, paciencia, instrumentos simples de medición, y una mente matemática extraordinaria. El telescopio no sería inventado hasta 1608, más de 60 años después de la muerte de Copérnico. Sin embargo, sus observaciones fueron lo suficientemente precisas para demostrar que el modelo tradicional del universo estaba equivocado.",
  "Los instrumentos que usaba Copérnico eran sencillos pero efectivos. El triquetrum era un aparato de madera con tres brazos articulados que servía para medir la altitud de las estrellas y los planetas, es decir, qué tan alto estaban sobre el horizonte. El cuadrante era un semicírculo graduado con el que también se medían ángulos en el cielo. El astrolabio era un disco plano con marcas que permitía calcular la posición de estrellas a partir de su altitud. Todos estos instrumentos habían sido usados durante siglos, pero Copérnico los usaba con una precisión y sistematicidad excepcionales.",
  "La práctica de la astronomía de la época requería noches enteras de observación meticulosa. Copérnico anotaba la posición exacta de los planetas y la Luna en momentos precisos, usando los mismos puntos de referencia noche tras noche. Con esas anotaciones, podía calcular el movimiento de los planetas a lo largo de semanas, meses y años. Era un trabajo que requería una paciencia enorme y una dedicación que solo un verdadero apasionado podía sostener durante décadas.",
  "Copérnico vivió la mayor parte de su vida adulta en Frauenburg (hoy Frombork, en Polonia), una pequeña ciudad medieval junto al Mar Báltico. Su observatorio no era un edificio especial: simplemente hacía sus observaciones desde las torres y terrazas de la catedral donde trabajaba como canónigo, un cargo religioso que le daba estabilidad económica para dedicarse a la astronomía. La combinación de su trabajo religioso diurno y sus observaciones astronómicas nocturnas era su vida cotidiana.",
  "El clima del norte de Polonia no era ideal para la astronomía: el cielo estaba frecuentemente nublado, especialmente en invierno. Copérnico tenía que aprovechar cada noche despejada para observar, sabiendo que podría pasar semanas sin otra oportunidad. Esta limitación lo obligó a ser extremadamente sistemático y a sacar el máximo provecho de cada observación. Algunos historiadores creen que por eso también se apoyó tanto en observaciones de astrónomos anteriores: para compensar las nubes del norte europeo.",
  "La luna era uno de los objetos de observación favoritos de Copérnico. Estudiaba cuidadosamente sus fases, su posición en el cielo, y cómo estas cambiaban con el tiempo. La Luna completa un ciclo de fases en aproximadamente 29.5 días, y su posición en el cielo cambia noche a noche. Copérnico desarrolló un modelo matemático del movimiento de la Luna que era más preciso que el de Ptolomeo para ciertas predicciones, aunque aún tenía limitaciones por suponer órbitas circulares.",
  "Las estrellas también eran cruciales para la astronomía de Copérnico. Las estrellas fijas (que no se mueven relativas entre sí) servían como un sistema de referencia inmóvil contra el cual medía los movimientos de los planetas. Copérnico sabía que las estrellas están enormemente lejos: propuso que si la Tierra se mueve, las estrellas deberían mostrar paralaje (un pequeño desplazamiento aparente), pero que ese paralaje sería demasiado pequeño para medir con los instrumentos de la época por la enorme distancia de las estrellas.",
  "Los eclipses eran eventos especiales para los astrónomos de la época porque permitían calibrar sus modelos con gran precisión. Tanto los eclipses solares como los lunares siguen patrones matemáticos precisos que dependen de las órbitas relativas del Sol, la Tierra y la Luna. Copérnico analizó registros históricos de eclipses que se remontaban siglos atrás para refinar sus cálculos. Esta capacidad de usar datos históricos fue una ventaja importante: tenía siglos de observaciones europeas y árabes disponibles.",
  "Una de las observaciones más importantes de Copérnico fue de los planetas Mercurio y Venus. Estos planetas nunca aparecen en el cielo nocturno lejos del Sol: siempre se ven cerca del Sol, ya sea poco antes del amanecer o poco después del atardecer. En el sistema de Ptolomeo esto requería una explicación complicada. En el sistema heliocéntrico, la explicación era simple y elegante: Mercurio y Venus están entre la Tierra y el Sol, por lo que desde la Tierra siempre los vemos en dirección al Sol.",
  "Copérnico también observó pacientemente el movimiento retrógrado de Marte, Júpiter y Saturno. Esto ocurre cuando la Tierra 'adelanta' a estos planetas en sus órbitas alrededor del Sol, haciendo que parezcan moverse hacia atrás por unas semanas. Copérnico registró cuidadosamente cuándo ocurría este fenómeno para cada planeta y demostró que su modelo heliocéntrico predecía estos episodios de manera mucho más natural que el modelo de Ptolomeo con sus complicados epiciclos.",
  "La precisión de las observaciones de Copérnico era notable para la época, pero no era perfecta. Sin telescopio, era imposible ver detalles finos. Los ángulos que podía medir tenían un error de varios minutos de arco (cada grado tiene 60 minutos de arco). Paradójicamente, fue precisamente la mayor precisión de las observaciones de Tycho Brahe décadas después la que permitió a Kepler descubrir que las órbitas son elipses, corrigiendo el error de las órbitas circulares de Copérnico.",
  "La técnica de observación de Copérnico incluía algo fundamental que a veces olvidamos: el registro sistemático. Cada observación era anotada con fecha, hora (tan precisa como los relojes de la época permitían), posición del planeta y condiciones atmosféricas. Sin estos registros cuidadosos, los datos hubieran sido inútiles. Esta disciplina del registro sistemático es uno de los pilares del método científico: las observaciones que no se registran con rigor no pueden ser verificadas ni usadas por otros científicos.",
  "Para entender el movimiento de los planetas en su modelo, Copérnico necesitaba conocer el período orbital de cada planeta (cuánto tiempo tarda en dar una vuelta completa al Sol). Calculó estos períodos con gran precisión a partir de sus observaciones. Por ejemplo, calculó que la Tierra tarda 365.25 días (un año), que Marte tarda 686.98 días (aproximadamente 1.88 años), y que Júpiter tarda 4,332 días (aproximadamente 11.86 años). Sus valores estaban muy cerca de los que conocemos hoy.",
  "Copérnico también usó las observaciones de astrónomos anteriores, especialmente los griegos y los árabes. Los textos de Al-Battani, un astrónomo árabe del siglo IX, eran especialmente valiosos por sus observaciones precisas de la posición del Sol durante todo el año. Al combinar observaciones antiguas con las suyas propias, Copérnico tenía una base de datos que cubría siglos. Esto le permitió detectar patrones a largo plazo que no hubiera podido ver solo con sus observaciones personales.",
  "La astronomía a ojo desnudo que practicó Copérnico tenía una ventaja que a menudo olvidamos: lo obligaba a pensar con más cuidado en la geometría y la física para interpretar sus datos. Con un telescopio, puedes ver detalles que a veces distraen del patrón general. Con solo los ojos y la mente, te concentras en los movimientos y patrones geométricos. Esta limitación tecnológica paradójicamente ayudó a Copérnico a ver el patrón grande: que el Sol estaba en el centro y todos los planetas giraban alrededor de él."
], [
  { q: "¿Cuándo fue inventado el telescopio, en relación a la vida de Copérnico?", options: ["30 años antes de su nacimiento", "Durante su vida", "10 años después de su muerte", "Más de 60 años después de su muerte"], a: 3 },
  { q: "¿En qué ciudad polaca vivió y trabajó Copérnico la mayor parte de su vida adulta?", options: ["Varsovia", "Cracovia", "Gdansk", "Frauenburg (Frombork)"], a: 3 },
  { q: "¿Qué instrumento con tres brazos articulados usaba Copérnico para medir la altitud de los planetas?", options: ["Astrolabio", "Triquetrum", "Cuadrante", "Sextante"], a: 1 },
  { q: "¿Por qué Mercurio y Venus siempre se ven cerca del Sol en el cielo?", options: ["Porque son los planetas más brillantes", "Porque giran muy rápido", "Porque están entre la Tierra y el Sol en el sistema heliocéntrico", "Porque tienen lunas propias"], a: 2 },
  { q: "¿De qué astrónomo árabe del siglo IX usó Copérnico observaciones valiosas?", options: ["Ibn Battuta", "Al-Battani", "Al-Biruni", "Avicena"], a: 1 }
]);

// copernico_m5 - El legado de Copérnico
src = patchModule(src, 'copernico_m5', [
  "¡Hemos llegado al módulo final del curso de Copérnico! Hoy vamos a explorar el legado colosal que dejó este astrónomo polaco del siglo XVI. El legado de Copérnico va mucho más allá de la astronomía: transformó la filosofía, la religión, la ciencia y la manera en que la humanidad se entiende a sí misma en el universo. Su idea más simple, que la Tierra gira alrededor del Sol, abrió una puerta a través de la cual toda la ciencia moderna entró al mundo.",
  "El primer heredero directo de Copérnico fue Tycho Brahe, un astrónomo danés que vivió de 1546 a 1601. Brahe no aceptó completamente el modelo heliocéntrico: propuso un modelo híbrido donde la Tierra estaba en el centro pero todos los planetas giraban alrededor del Sol, y el Sol con ellos giraba alrededor de la Tierra. Aunque su modelo físico era incorrecto, Brahe hizo algo invaluable: construyó el observatorio más preciso de la época antes del telescopio y pasó décadas tomando las mediciones más exactas jamás realizadas de los movimientos planetarios.",
  "Las observaciones de Tycho Brahe cayeron en manos de Johannes Kepler, un matemático alemán que fue su asistente y heredó sus datos. Kepler era un apasionado del modelo copernicano y utilizó los datos ultraprrecísos de Brahe para descubrir algo que Copérnico había errado: las órbitas de los planetas no son círculos perfectos sino elipses. Esta corrección, publicada en las tres leyes de Kepler entre 1609 y 1619, perfeccionó enormemente el modelo de Copérnico y por primera vez las predicciones de las posiciones planetarias coincidieron perfectamente con las observaciones.",
  "Galileo Galilei fue quizás el defensor más famoso y valiente del modelo copernicano. Usando el telescopio recién inventado, Galileo descubrió evidencias que apoyaban directamente el heliocentrismo: vio que Júpiter tenía lunas propias (lo que demostraba que no todo giraba alrededor de la Tierra), que Venus mostraba fases como la Luna (lo que era imposible en el modelo geocéntrico de Ptolomeo), y que el Sol tenía manchas que rotaban, mostrando que el Sol también gira. Galileo pagó caro por defender a Copérnico: fue juzgado por la Inquisición y pasó el resto de su vida bajo arresto domiciliario.",
  "Isaac Newton fue quien proporcionó la explicación física definitiva del por qué los planetas orbitan el Sol. En 1687, publicó los Principia Mathematica, donde presentó la teoría de la gravitación universal: todos los objetos con masa se atraen mutuamente. El Sol, con su enorme masa, atrae gravitacionalmente a todos los planetas. Newton demostró matemáticamente que si la gravedad funciona como él lo describía, las leyes de Kepler se siguen naturalmente. El edificio de la astronomía moderna estaba completo: Copérnico puso los cimientos, Kepler construyó las paredes, Newton el techo.",
  "El impacto de la revolución copernicana en la filosofía fue profundo. El filósofo Immanuel Kant, en el siglo XVIII, llamó a sus propios cambios filosóficos una 'revolución copernicana en la filosofía'. Kant argumentó que al estudiar el conocimiento humano, hay que reconocer que el observador (nosotros) también influye en lo que observa, igual que Copérnico reconoció que la posición de la Tierra afecta lo que observamos del cielo. El nombre de Copérnico se convirtió en sinónimo de cambio radical de perspectiva.",
  "La revolución copernicana también transformó la relación entre la ciencia y la religión. Antes de Copérnico, ciencia y religión coexistían relativamente en paz, con la ciencia subordinada a la autoridad religiosa. El conflicto de Galileo con la Iglesia mostró que cuando la ciencia y la religión discrepan sobre hechos verificables del mundo físico, el método científico tiene la última palabra. Este principio, dolorosamente establecido durante los siglos XVI y XVII, es la base de la libertad intelectual de la ciencia moderna.",
  "El 'principio de Copérnico' es un concepto científico moderno derivado de su nombre. Propone que la Tierra no está en ningún lugar especial ni privilegiado del universo: somos un planeta ordinario alrededor de una estrella ordinaria en una galaxia ordinaria en un universo sin centro definido. Este principio de mediocridad cósmica paradójicamente nos hace más humildes pero también más curiosos: si somos tan ordinarios, ¿cuántos otros planetas como el nuestro podría haber? ¿Cuántas otras formas de vida?",
  "La búsqueda de exoplanetas, planetas alrededor de otras estrellas, es directamente heredera del pensamiento copernicano. Si la Tierra es un planeta ordinario alrededor de un Sol ordinario, tiene sentido buscar otros planetas alrededor de otras estrellas. Los telescopios espaciales modernos como el Kepler (nombrado en honor a Johannes Kepler, sucesor de Copérnico) han descubierto miles de exoplanetas. Algunos podrían ser similares a la Tierra. Esta búsqueda emocionante comenzó intelectualmente con la idea de Copérnico.",
  "El nombre de Copérnico aparece en muchos lugares de la ciencia y la cultura: el elemento químico copernicium (número atómico 112) lleva su nombre, también lo llevan varios cráteres en la Luna y en Marte, un asteroide (número 1322), y la Universidad de Toruń en Polonia. El Papa Juan Pablo II, él mismo polaco, honró formalmente a Copérnico y reconoció que la Iglesia Católica se había equivocado al oponerse al heliocentrismo. Este reconocimiento tardío muestra cómo la historia juzga la ciencia más favorablemente que las instituciones que la resistieron.",
  "El legado educativo de Copérnico es quizás el más duradero. Cambió lo que enseñamos a los niños sobre el universo: que la Tierra gira alrededor del Sol, que somos parte de un sistema solar, que el universo es inmenso. Estas ideas que ahora aprenden los niños en sus primeros años de escuela eran radicales herejías en el siglo XVI. Cada vez que un niño aprende en la escuela que la Tierra orbita el Sol, está recibiendo el regalo intelectual que Copérnico le dio a la humanidad.",
  "La metodología científica de Copérnico también es parte de su legado. Demostró que la observación cuidadosa y el razonamiento matemático pueden superar a las autoridades más respetadas. Que la elegancia matemática y la simplicidad son guías confiables hacia la verdad. Que una teoría que explica más con menos suposiciones es probable que sea correcta. Estos principios metodológicos son tan importantes como el modelo heliocéntrico en sí y forman parte del ADN de la ciencia moderna.",
  "Uno de los aspectos más conmovedores del legado de Copérnico es que trabajó toda su vida sin poder ver la plena confirmación de su teoría. Murió en 1543 sin un telescopio, sin poder ver las lunas de Júpiter ni las fases de Venus. Esas confirmaciones vinieron décadas después con Galileo. Copérnico tuvo que confiar en la fuerza de los argumentos matemáticos y en la elegancia de su modelo. Nos enseña que en ciencia, a veces las confirmaciones llegan después que los que hicieron el trabajo, y aun así el trabajo vale la pena.",
  "En el siglo XXI, la relevancia de Copérnico continúa. Cada nuevo telescopio espacial que lanzamos, cada exoplaneta que descubrimos, cada sonda que mandamos a otros planetas del sistema solar, es una continuación directa de la aventura intelectual que Copérnico inició hace cinco siglos. La pregunta que implícitamente hizo al mover a la Tierra de su posición central, '¿qué más hay ahí afuera?', sigue siendo la pregunta motora de la astronomía y la exploración espacial modernas.",
  "El legado final de Copérnico es una invitación: a cuestionar lo que todos dan por sentado, a buscar explicaciones más simples y elegantes, a confiar en las matemáticas y las observaciones más que en las autoridades. En una época donde la desinformación y las ideas simplistas compiten con la ciencia, el ejemplo de Copérnico es más relevante que nunca. Un hombre con paciencia, curiosidad y rigor intelectual cambió para siempre la manera en que toda la humanidad entiende su lugar en el cosmos. ¿Qué podrías cambiar tú con esas mismas herramientas?"
], [
  { q: "¿Qué descubrió Johannes Kepler al estudiar los datos de Tycho Brahe?", options: ["Que el Sol giraba alrededor de la Tierra", "Que las órbitas de los planetas son elipses, no círculos", "Que Copérnico estaba equivocado", "Que la Luna tiene cráteres"], a: 1 },
  { q: "¿Qué evidencias telescópicas presentó Galileo para apoyar el modelo copernicano?", options: ["Las manchas del Sol y las lunas de Júpiter", "La existencia de Neptuno", "Las órbitas de los cometas", "El anillo de Saturno"], a: 0 },
  { q: "¿Qué libro publicó Isaac Newton en 1687 que explicó por qué los planetas orbitan el Sol?", options: ["Astronomia Nova", "De Revolutionibus", "Principia Mathematica", "Sidereus Nuncius"], a: 2 },
  { q: "¿Cómo se llama el principio científico moderno, derivado del nombre de Copérnico, que dice que la Tierra no tiene ninguna posición privilegiada en el universo?", options: ["Principio de relatividad", "Principio de incertidumbre", "Principio de Copérnico", "Principio antrópico"], a: 2 },
  { q: "¿Cómo se llama el elemento químico número 112 de la tabla periódica, nombrado en honor a Copérnico?", options: ["Galileo", "Keplerino", "Copernicium", "Tychonium"], a: 2 }
]);

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ All Copernicus modules patched!');
