/**
 * patch_interestelar.js — patches interestelar_m1 through interestelar_m6 with 15 paragraphs each
 * Topics: Interstellar travel, star systems, light years, relativistic flight, generation ships, etc.
 * NOTE: These are "interestelar" (Spanish spelling with i), different from "interstellar" course
 */
const fs = require('fs');
const { replaceTextAndQuiz, FILE } = require('./patch_helpers');
let src = fs.readFileSync(FILE, 'utf8');

// Check what interestelar modules actually contain (they had 1 paragraph each)
// These need complete replacement with 15 paragraphs

const INTERESTELAR = {
  interestelar_m1: {
    text: [
      "¡Bienvenido al módulo de viaje interestelar! Imagina que puedes viajar entre las estrellas, cruzar los enormes abismos del espacio que separan los sistemas solares. Esta idea, que parece pura ciencia ficción, es en realidad el sueño más ambicioso de la exploración espacial humana. En este módulo exploramos la ciencia real detrás de este sueño.",
      "La primera pregunta es ¿qué tan lejos están las estrellas? La estrella más cercana al Sol (aparte del propio Sol) es Próxima Centauri, en el sistema Alfa Centauri. Está a 4.24 años luz de distancia. Un año luz es la distancia que recorre la luz en un año: 9.46 billones de kilómetros. Próxima Centauri está a 40,140,000,000,000 kilómetros de nosotros.",
      "Para entender esa distancia: la sonda Voyager 1, la nave más veloz que hemos lanzado (a 17 km/s), tardó 45 años en recorrer solo 1/500 de un año luz. A esa velocidad, tardaría unos 73,000 años en llegar a Próxima Centauri. Claramente, la tecnología actual no es suficiente para el viaje interestelar en escalas de tiempo humanas.",
      "La velocidad de la luz en el vacío es la barrera más fundamental del universo: 299,792 km/s. Ningún objeto con masa puede alcanzarla porque requeriría energía infinita. Sin embargo, a velocidades de un 10-20% de la velocidad de la luz (velocidades relativistas pero sublight), el viaje a los sistemas estelares más cercanos podría reducirse a decenas de años.",
      "El primer proyecto serio de nave interestelar fue Dédalo (Project Daedalus), diseñado por científicos de la Sociedad Interplanetaria Británica en la década de 1970. Usaría motores de fusión nuclear detonando cápsulas de combustible de helio-3 y deuterio a 250 explosiones por segundo. Podría alcanzar el 12% de la velocidad de la luz y llegar a Barnard's Star (5.9 años luz) en 50 años.",
      "El helio-3 es el combustible preferido para los motores de fusión nuclear porque libera una cantidad enorme de energía sin producir neutrones dañinos. Desafortunadamente, el helio-3 es extremadamente raro en la Tierra (solo unas decenas de kilogramos existen). La Luna tiene reservas significativas depositadas por el viento solar durante miles de millones de años.",
      "La propulsión por vela de luz es una alternativa completamente diferente: en lugar de llevar combustible, una nave podría usar la presión de la radiación de un láser poderoso para acelerarse. El proyecto Breakthrough Starshot planea enviar nanoaves de menos de 1 gramo de masa a Alfa Centauri usando un láser de 100 gigavatios. Podrían alcanzar el 20% de la velocidad de la luz.",
      "Breakthrough Starshot fue anunciado en 2016 por el físico Stephen Hawking y el multimillonario Yuri Milner. Las 'nanoaves' (Star Chips) serían circuitos electrónicos ultra delgados con una pequeña vela de luz. La vela recibiría el impulso del láser desde la Tierra durante unos minutos y luego viajaría en inercia durante 20 años hasta Alfa Centauri.",
      "El principal desafío de Breakthrough Starshot es que las nanoaves deben sobrevivir al viaje a través del medio interestelar, que no está completamente vacío: contiene polvo interestelar, partículas de hidrógeno y rayos cósmicos. A 20% de la velocidad de la luz, incluso un grano de polvo de un gramo tendría el impacto cinético de una bomba. Las nanoaves necesitarían escudos especiales.",
      "La relatividad especial tiene implicaciones profundas para el viaje interestelar. Conforme una nave se acerca a la velocidad de la luz, el tiempo a bordo se dilata: los pasajeros envejecen más lentamente que los que quedan en la Tierra. A 90% de la velocidad de la luz, por cada 2.3 años de viaje experimentados a bordo, pasarían 5.3 años en la Tierra.",
      "Este efecto de dilatación temporal es real y verificado experimentalmente. Sin embargo, la energía necesaria para acelerar una nave de tamaño significativo a velocidades relativistas es astronómica. Para acelerar 1 kg de masa al 10% de la velocidad de la luz, se necesitan 450 terajoules de energía: toda la producción eléctrica de España durante un día.",
      "Los motores de antimateria son teóricamente los más eficientes posibles. La reacción materia-antimateria convierte el 100% de la masa en energía (E=mc²), frente al 0.7% de la fusión nuclear. 1 kilogramo de antimateria reaccionando con 1 kg de materia libera la energía de una bomba nuclear de 43 megatones. El problema: la antimateria es extremadamente cara de producir.",
      "Producir 1 gramo de antimateria costaría hoy millones de millones de dólares con los aceleradores de partículas actuales. Toda la antimateria producida en la historia de los aceleradores equivale a unos nanogramos. Para un motor interestelar se necesitarían toneladas. Es un objetivo que requeriría una civilización de nivel energético muy superior al actual.",
      "El motor de curvatura (warp drive) de la ciencia ficción, popularizado por Star Trek, tiene un fundamento matemático real: la métrica de Alcubierre. En 1994, el físico mexicano Miguel Alcubierre demostró matemáticamente que las ecuaciones de la relatividad general permiten la existencia de una 'burbuja' de espacio-tiempo que se mueve más rápido que la luz. Sin embargo, requeriría materia con energía negativa.",
      "El viaje interestelar es el horizonte más ambicioso de la humanidad. Aunque los desafíos son enormes, la historia de la tecnología muestra que los logros que parecen imposibles en una generación se vuelven rutinarios en la siguiente. Lo importante es identificar claramente los desafíos, buscar las soluciones con rigor científico, y tener la paciencia para trabajar en escalas de tiempo más largas que una vida humana."
    ],
    quiz: [
      { q: "¿A qué distancia en años luz está Próxima Centauri?", options: ["1.2","4.24","10","25"], a: 1 },
      { q: "¿Qué es un año luz?", options: ["365 días","Un millón de km","La distancia que recorre la luz en un año","La distancia de la Tierra al Sol"], a: 2 },
      { q: "¿Qué propone el proyecto Breakthrough Starshot?", options: ["Un cohete de fusión nuclear","Nanoaves impulsadas por láser al 20% de la velocidad de la luz","Una nave generacional","Un motor de antimateria"], a: 1 },
      { q: "¿Cuál es la desventaja de la antimateria como combustible?", options: ["No es suficientemente energética","Es extremadamente cara y difícil de producir","No puede contenerse","No funciona en el espacio"], a: 1 },
      { q: "¿Qué planteó el físico Alcubierre en 1994?", options: ["Una nueva forma de fusión nuclear","Las ecuaciones matemáticas de una 'burbuja' de espacio-tiempo más rápida que la luz","La imposibilidad del viaje interestelar","Una nueva teoría de la gravedad"], a: 1 }
    ]
  },
  interestelar_m2: {
    text: [
      "Las estrellas más cercanas al Sol son el sistema triple de Alfa Centauri: Alfa Centauri A (similar al Sol), Alfa Centauri B (algo más pequeña y fresca) y Próxima Centauri (una enana roja a 4.24 años luz). Este sistema es el destino más probable para la primera misión interestelar de la humanidad.",
      "Alfa Centauri A y B orbitan mutuamente a una distancia promedio de 23 UA (unidades astronómicas, la distancia Tierra-Sol) con un período de 79.9 años. Próxima Centauri está mucho más lejos del par: unos 12,000 UA, y se pregunta si realmente está ligada gravitacionalmente al sistema o simplemente se encuentra de paso.",
      "Próxima Centauri tiene un planeta conocido, Próxima Centauri b, descubierto en 2016. Este exoplaneta tiene masa similar a la Tierra y orbita en la zona habitable de su estrella. Sin embargo, por tratarse de una enana roja, emite potentes llamaradas ultravioleta que podrían hacer difícil la vida en su superficie, al menos sin protección.",
      "Las enanas rojas son las estrellas más comunes del universo: constituyen el 70% de todas las estrellas de la Vía Láctea. Son mucho más pequeñas, más frías y más longevas que el Sol. Mientras el Sol vivirá unos 10,000 millones de años en total, las enanas rojas pueden vivir billones de años. Los planetas en sus zonas habitables tienen mucho más tiempo para desarrollar vida.",
      "La Vía Láctea es nuestra galaxia: una estructura espiral de unos 100,000 años luz de diámetro y 1,000-2,000 años luz de espesor, conteniendo entre 100,000 millones y 400,000 millones de estrellas. El Sol está situado en un brazo espiral llamado Brazo de Orión, a unos 27,000 años luz del centro galáctico.",
      "Nuestro Sol orbita el centro de la Vía Láctea a una velocidad de unos 220 km/s, tardando unos 225-250 millones de años en completar una órbita (el 'año galáctico'). Desde que la Tierra se formó, el Sol ha completado unas 18 órbitas galácticas. Cada órbita lleva al Sol a través de diferentes regiones de la galaxia con diferentes densidades de estrellas.",
      "El centro de la Vía Láctea alberga un agujero negro supermasivo llamado Sagitario A*, con una masa de unos 4 millones de masas solares. En 2022, el Event Horizon Telescope (la red de radiotelescopios que obtuvo la primera imagen de un agujero negro) capturó la primera imagen de Sagitario A*. Es el agujero negro más cercano que conocemos.",
      "Más allá de la Vía Láctea, el universo contiene miles de millones de galaxias. Las galaxias más cercanas a la nuestra son las Nubes de Magallanes (satélites irregulares de la Vía Láctea a 160,000 y 200,000 años luz) y la galaxia de Andrómeda (una espiral enorme a 2.5 millones de años luz que se aproxima a nosotros y colisionará con la Vía Láctea en unos 4,500 millones de años).",
      "El universo observable tiene un diámetro de unos 93,000 millones de años luz. Esto es mayor que los 13,800 millones de años de la edad del universo porque el espacio se ha estado expandiendo durante todo ese tiempo: la luz de los objetos más lejanos ha viajado durante 13,800 millones de años, pero los objetos en sí están ahora mucho más lejos debido a la expansión del espacio.",
      "La expansión del universo fue descubierta por Edwin Hubble en 1929. Observó que las galaxias distantes se alejaban de nosotros a velocidades proporcionales a su distancia (la Ley de Hubble). Esta observación llevó a la conclusión de que el universo se expande, y si se expande hacia afuera, debió comenzar en un estado comprimido: el Big Bang.",
      "La densidad de estrellas varía enormemente en la galaxia. En el disco galáctico donde estamos, hay una estrella por cada 10 años cúbicos de espacio aproximadamente. En el núcleo galáctico, la densidad es miles de veces mayor. En las regiones de formación estelar (nebulosas), nuevas estrellas se están formando ahora mismo de nubes de gas y polvo.",
      "La Nebulosa de Orión, visible a simple vista en el cinturón de Orión, está a 1,344 años luz de distancia y es la región de formación estelar más cercana al Sol. Con telescopios, se pueden ver miles de estrellas jóvenes formándose dentro de ella, con discos protoplanetarios (proplyds) que podrían estar desarrollando planetas en este momento.",
      "La búsqueda de inteligencia extraterrestre (SETI, Search for Extra-Terrestrial Intelligence) usa radiotelescopios para detectar señales de radio artificiales que podrían provenir de civilizaciones alienígenas. Desde 1960, miles de horas de observaciones no han detectado ninguna señal inequívocamente artificial. Esto es el Gran Silencio o Paradoja de Fermi: si hay tantos sistemas estelares, ¿dónde están todos?",
      "La ecuación de Drake (1961) estima el número de civilizaciones extraterrestres tecnológicas en la galaxia. Tiene varios factores: tasa de formación estelar, fracción de estrellas con planetas, fracción de planetas habitables, fracción donde surge la vida, la inteligencia, la tecnología, y la duración de las civilizaciones. Con valores optimistas, podría haber miles de civilizaciones. Con valores pesimistas, podríamos estar solos.",
      "Explorar las estrellas vecinas, ya sea con nanoaves o en el futuro con naves tripuladas, nos enseñaría más sobre el universo que siglos de observaciones desde la Tierra. La diferencia entre observar Próxima Centauri b desde aquí y visitarlo con una sonda es la misma que entre fotografiar el fondo del océano y descender en un submarino. El conocimiento de primera mano no tiene sustituto."
    ],
    quiz: [
      { q: "¿Cuántas estrellas tiene el sistema de Alfa Centauri?", options: ["Una","Dos","Tres","Cuatro"], a: 2 },
      { q: "¿Qué porcentaje de las estrellas de la Vía Láctea son enanas rojas?", options: ["10%","30%","50%","70%"], a: 3 },
      { q: "¿Cómo se llama el agujero negro en el centro de la Vía Láctea?", options: ["Sagitario A*","Cygnus X-1","Sagitario B","NGC 4649"], a: 0 },
      { q: "¿Qué es la Paradoja de Fermi?", options: ["Por qué los planetas orbitan el Sol","Si hay tantos sistemas estelares, por qué no detectamos señales de vida alienígena","Por qué el universo se expande","Cómo se forman las galaxias"], a: 1 },
      { q: "¿Cuándo colisionará la galaxia de Andrómeda con la Vía Láctea?", options: ["En 1,000 años","En 1 millón de años","En 4,500 millones de años","Ya están colisionando"], a: 2 }
    ]
  },
  interestelar_m3: {
    text: [
      "Si los seres humanos quisiéramos viajar a otra estrella en escalas de tiempo razonables (décadas, no milenios), necesitaríamos tecnologías de propulsión completamente diferentes a los cohetes químicos que usamos hoy. Los cohetes químicos son eficientes para llegar a la órbita terrestre o ir a la Luna, pero son completamente inadecuados para el viaje interestelar.",
      "El problema de los cohetes químicos para el viaje interestelar es la ecuación de Tsiolkovsky. Esta ecuación dice que para duplicar la velocidad de una nave, debes elevar al cuadrado la relación combustible/masa total. Escalar a velocidades interestelares requeriría llevar una cantidad imposible de combustible: más que toda la masa del universo observable.",
      "Los motores de propulsión nuclear pulsada son los más avanzados que se han diseñado en detalle. El Proyecto Orion (1958-1965) propuso detonar pequeñas bombas nucleares detrás de la nave para propulsarla. Una nave Orion podría alcanzar el 3-10% de la velocidad de la luz. El tratado de prohibición de pruebas nucleares en el espacio (1963) detuvo el proyecto.",
      "La propulsión de fusión nuclear es la tecnología más prometedora a mediano plazo. La fusión combina núcleos ligeros (deuterio, tritio, helio-3) liberando enormes cantidades de energía. Los motores de fusión para naves interestelares deberían funcionar a pulsos: detonar pequeñas cápsulas de combustible de fusión y usar las partículas expulsadas como propulsor.",
      "El Proyecto Dédalo (Project Daedalus) de los años 70 fue el diseño más detallado de nave interestelar jamás elaborado. Usaría 50,000 toneladas de combustible de helio-3/deuterio, consumiéndolo en 50,000 micro-explosiones de fusión por segundo. En 3.8 años de aceleración alcanzaría el 12% de la velocidad de la luz, y en 49 años más llegaría a Barnard's Star.",
      "El Proyecto Icarus (2011-presente) es el sucesor del Proyecto Dédalo, intentando mejorar el diseño con tecnología más moderna. Una de las innovaciones es el 'Icarus Firefly', una versión más pequeña que usaría un motor magnetoinercial de fusión, potencialmente más eficiente que la fusión por pulsos. Estos proyectos son ejercicios teóricos pero rigurosos.",
      "La propulsión por vela solar y por vela láser son tecnologías completamente distintas a los cohetes. En lugar de llevar combustible, capturan energía del exterior. Las velas solares usan la presión de radiación del Sol. Las velas láser reciben el impulso de un láser potente desde la Tierra o el sistema solar. En ambos casos, la nave viaja más ligera.",
      "El proyecto Breakthrough Starshot planea demostrar la tecnología de velas láser enviando nanoaves (chips con velas ultrafinas de metro cuadrado) a Alfa Centauri. El láser terrestre de 100 gigavatios las aceleraría al 20% de la velocidad de la luz en minutos. En 20 años llegarían a Alfa Centauri y fotografiarían sus planetas, transmitiendo las imágenes de vuelta.",
      "La propulsión por ramjet (motor de ramscoop) fue propuesta por Bussard en 1960. Recogería el hidrógeno interestelar (que existe en densidades de 1 átomo por cm³) con un enorme embudo magnético para usarlo como combustible de fusión. En teoría, podría acelerar indefinidamente. En práctica, la densidad del hidrógeno interestelar es demasiado baja y crearía más resistencia que empuje.",
      "La propulsión por materia-antimateria es la más eficiente teóricamente: convierte toda la masa en energía (100% de eficiencia, frente al 0.7% de la fusión). 1 gramo de antimateria reaccionando con 1 gramo de materia libera 180 terajoules de energía. El problema es producir antimateria: el acelerador LHC del CERN produce nanogramos al año.",
      "La propulsión por curvatura (warp drive) es ciencia ficción pero con bases matemáticas reales. La métrica de Alcubierre (1994) muestra que las ecuaciones de la relatividad general permiten teóricamente un 'globo' de espacio-tiempo que se mueve más rápido que la luz comprimiendo el espacio adelante y expandiéndolo atrás. La nave dentro del globo no violaría la relatividad localmente.",
      "El motor de curvatura requeriría materia con densidad de energía negativa en cantidades que no existen naturalmente. Cálculos iniciales indicaban que se necesitaría la masa equivalente a Júpiter en materia exótica. Cálculos posteriores han reducido esta cantidad a valores teóricos menores, pero sigue siendo insalvable con la física conocida.",
      "Los agujeros de gusano estabilizados por materia exótica podrían ser accesos a atajos del espacio-tiempo. Si existieran y fueran transitables, un agujero de gusano podría conectar dos puntos del universo separados por miles de años luz pero accesibles entre sí en minutos. Sin embargo, la física cuántica puede prevenir la existencia de agujeros de gusano transitables.",
      "La propulsión solar térmica usa el Sol como fuente de calor para calentar un propulsor (como hidrógeno) a temperaturas altísimas y expulsarlo para propulsión. Es una tecnología realista para viajes dentro del sistema solar. Para viajes interestelares, necesitaría una fuente de energía más potente: quizás un láser desde el Sol concentrado con espejos orbitales.",
      "La tecnología de propulsión interestelar está en la intersección de la física más avanzada, la ingeniería más ambiciosa y las matemáticas más complejas. Cada propuesta enfrentase desafíos formidables, pero cada análisis detallado nos enseña más sobre los límites del universo y qué es posible dentro de ellos. El viaje interestelar podría ser el mayor logro técnico de la humanidad."
    ],
    quiz: [
      { q: "¿Qué ecuación describe el problema del combustible en los cohetes?", options: ["La ecuación de Einstein","La ecuación de Tsiolkovsky","La ecuación de Hawking","La ecuación de Lorentz"], a: 1 },
      { q: "¿Qué tecnología usa el Proyecto Breakthrough Starshot?", options: ["Fusión nuclear pulsada","Motor de antimateria","Nanoaves con velas láser","Motor ramscoop"], a: 2 },
      { q: "¿Cuánto porcentaje de la masa convierte en energía la reacción materia-antimateria?", options: ["0.7%","10%","50%","100%"], a: 3 },
      { q: "¿Qué propuso Bussard en 1960 para la propulsión interestelar?", options: ["Detonar bombas nucleares","Un motor que recoge hidrógeno interestelar (ramscoop)","Velas solares enormes","Agujeros de gusano artificiales"], a: 1 },
      { q: "¿Quién propuso matemáticamente el motor de curvatura en 1994?", options: ["Stephen Hawking","Carl Sagan","Miguel Alcubierre","Kip Thorne"], a: 2 }
    ]
  },
  interestelar_m4: {
    text: [
      "Si el viaje interestelar tripulado a velocidades sublight (menores que la de la luz) se realizara, los viajeros enfrentarían desafíos físicos y psicológicos sin precedente. Un viaje a Alfa Centauri al 10% de la velocidad de la luz duraría 43 años. Los viajeros sabrían que cuando regresaran, todos sus familiares habrían muerto.",
      "Las naves generacionales son una solución a los viajes interestelares largos: en lugar de que una sola generación haga el viaje, múltiples generaciones nacen, viven y mueren durante el trayecto. Los bisnietos de los fundadores serían quienes llegaran al destino. Este concepto plantea preguntas filosóficas profundas: ¿es ético enviar personas que no eligieron el viaje?",
      "El tamaño de una nave generacional sería enorme: necesitaría ser un ecosistema cerrado autosuficiente. Habría áreas de cultivo hidropónico para alimentos, zonas de reciclaje completo de agua y aire, espacios de vivienda, educación y recreación, y un sistema de energía (probablemente nuclear) para mantener todo funcionando durante décadas o siglos.",
      "La radiación cósmica es uno de los mayores peligros del viaje interestelar prolongado. Fuera del campo magnético terrestre, los rayos cósmicos (partículas de alta energía que viajan a casi la velocidad de la luz) bombardean el cuerpo humano. En la ISS, los astronautas reciben el equivalente de 150 radiografías de pecho por año. En un viaje interestelar, la dosis sería mucho mayor.",
      "La microgravedad tiene efectos devastadores en el cuerpo humano a largo plazo: pérdida de masa muscular y densidad ósea, deterioro del sistema cardiovascular y fluidos hacia la cabeza que dañan la visión. Los astronautas en la ISS (que están en microgravedad) hacen 2 horas de ejercicio diario para minimizar estos efectos. En un viaje de décadas, serían insuficientes.",
      "La gravedad artificial mediante rotación es la solución propuesta para la microgravedad. Si la nave gira, la fuerza centrífuga simula la gravedad. Un cilindro rotando a la velocidad correcta crea una 'gravedad artificial' en su pared interior proporcional a su radio y velocidad de rotación. El diseño clásico de nave generacional es un cilindro o toro (donut) giratorio.",
      "La psicología de los viajeros interestelares es otro factor crítico. Vivir durante décadas en un espacio cerrado, sin poder salir, sabiendo que nunca verán la Tierra, es un desafío psicológico enorme. Los simuladores de viaje prolongado (como el experimento Mars-500, donde 6 personas vivieron en un módulo aislado durante 520 días) muestran que el aislamiento produce depresión, conflictos y problemas cognitivos.",
      "La hibernación o criogenia es una alternativa a la nave generacional. Si los viajeros pudieran ser puestos en un estado de animación suspendida (muy bajo metabolismo, casi sin actividad cerebral) durante el viaje, llegarían sin envejecer significativamente. Existen animales que hacen algo similar: los osos hibernan, algunos peces se congelan y se 'descongelan' en primavera.",
      "La criogenia humana real no existe actualmente. Las técnicas actuales de congelación dañan las células irreversiblemente (los cristales de hielo perforan las membranas celulares). Investigadores trabajan en el 'vitrificación': reemplazar el agua celular con sustancias que no cristalizan al enfriarse, solidificando el tejido como un vidrio en lugar de con cristales. Es promisorio pero no está listo.",
      "La edición genética podría ser parte del equipo de una nave generacional. CRISPR-Cas9 podría permitir adaptar gradualmente a los viajeros a las condiciones del viaje y del destino: mayor resistencia a la radiación, metabolismo más eficiente, necesidades nutricionales reducidas. Sin embargo, estos cambios genéticos en las generaciones nacidas durante el viaje serían permanentes e irreversibles.",
      "El destino de la nave generacional plantea otro dilema: ¿qué hacen los viajeros cuando llegan? Han vivido toda su vida en la nave y no conocen otro entorno. El planeta destino podría tener condiciones completamente inesperadas. ¿Están preparados psicológica y tecnológicamente para colonizarlo? ¿O simplemente enviarían robots y regresarían (si pueden)?",
      "La terraformación del planeta destino sería el proyecto más ambicioso jamás emprendido. Para hacer habitable un planeta como Marte o un exoplaneta similar, necesitarías modificar su atmósfera, temperatura y presión durante miles de años. Necesitarías robots y microorganismos engineered trabajando durante generaciones antes de que ningún humano pudiera vivir allí desprotegido.",
      "Los robots y la inteligencia artificial son alternativas tentadoras a los viajeros humanos. Los robots no envejecen, no necesitan comida, no sufren psicológicamente y pueden ser enviados en naves mucho más pequeñas. Podrían explorar el planeta destino, enviar datos de vuelta, y preparar la colonia durante décadas antes de que lleguen los humanos (en una segunda nave más lenta).",
      "La comunicación durante el viaje interestelar sería frustrante pero funcional. Incluso a la velocidad de la luz, las señales de radio tardan años en llegar. Una conversación entre una nave en Alfa Centauri y la Tierra tendría un retraso de 8.5 años (ida y vuelta). Las conversaciones en tiempo real serían imposibles; solo el intercambio lento de mensajes sería posible.",
      "El viaje interestelar humano, en cualquiera de sus formas, nos llevaría más allá de los límites físicos, tecnológicos y psicológicos conocidos. Pero la humanidad ya ha superado muchos límites que parecían infranqueables: el sonido, la órbita terrestre, la Luna. El viaje a las estrellas podría ser el siguiente gran paso, dado quizás por generaciones aún no nacidas."
    ],
    quiz: [
      { q: "¿Cuánto duraría un viaje a Alfa Centauri al 10% de la velocidad de la luz?", options: ["10 años","43 años","100 años","430 años"], a: 1 },
      { q: "¿Cuál es la solución clásica para simular gravedad en una nave generacional?", options: ["Motores que tiran de los objetos","Un cilindro o toro giratorio (fuerza centrífuga)","Campos magnéticos","Aumento de masa de la nave"], a: 1 },
      { q: "¿Por qué la criogenia humana no existe actualmente?", options: ["Es demasiado cara","Los cristales de hielo dañan irreversiblemente las células","Está prohibida por ley","No se han hecho experimentos"], a: 1 },
      { q: "¿Qué demostró el experimento Mars-500?", options: ["Que los humanos pueden vivir en Marte","Que el aislamiento prolongado produce depresión y conflictos","Que la comida marciana es saludable","Que los robots son mejores exploradores"], a: 1 },
      { q: "¿Por qué no podríamos tener conversaciones en tiempo real con una nave en Alfa Centauri?", options: ["No tenemos tecnología de radio suficientemente potente","Las señales de radio tardan años en llegar (retraso de 8.5 años ida y vuelta)","La nave estaría fuera del alcance de las señales","El espacio absorbe las ondas de radio"], a: 1 }
    ]
  },
  interestelar_m5: {
    text: [
      "El universo observable es un lugar de tamaño inconcebible. Tiene unos 93,000 millones de años luz de diámetro y contiene unos 2 billones de galaxias (según el estudio de Conselice de 2016). Cada galaxia contiene, en promedio, 100,000 millones de estrellas. Esto da un total estimado de 10^24 estrellas en el universo observable: un billón de billones.",
      "De todas estas estrellas, la fracción que tiene planetas es alta: datos del telescopio Kepler sugieren que prácticamente todas las estrellas tienen al menos un planeta. Incluso asumiendo que solo el 1% de los sistemas estelares tienen planetas en la zona habitable, y de esos solo el 1% desarrolló vida, el número de mundos habitados en el universo observable sería de 10^18 (un trillón).",
      "La Paradoja de Fermi (1950) es la pregunta: dado ese número enorme de posibles civilizaciones, ¿por qué no vemos ninguna señal de su presencia? Enrico Fermi hizo esta pregunta en una conversación informal. Sus compañeros de trabajo en Los Álamos no tenían respuesta. Décadas después, seguimos sin tenerla definitiva.",
      "La ecuación de Drake (1961) formaliza la Paradoja de Fermi. N = R* × fp × ne × fl × fi × fc × L, donde N es el número de civilizaciones detectables, R* la tasa de formación estelar, fp la fracción con planetas, ne los planetas habitables por sistema, fl la fracción donde surge la vida, fi donde surge la inteligencia, fc donde desarrollan tecnología detectable, y L la duración de la civilización.",
      "La gran incógnita de la ecuación de Drake es L: la duración de las civilizaciones tecnológicas. Si las civilizaciones se destruyen a sí mismas poco después de desarrollar tecnología avanzada (guerras nucleares, cambio climático catastrófico, etc.), L podría ser muy pequeño y N ≈ 1. Esta es la hipótesis del 'Gran Filtro' de Robin Hanson.",
      "El Gran Filtro es la idea de que en algún punto de la evolución desde materia simple a civilización interestelar, existe una barrera prácticamente infranqueable que filtra a casi todas las civilizaciones. Podría estar en el pasado (el surgimiento de la vida compleja fue casi imposible) o en el futuro (casi todas las civilizaciones avanzadas se autodestruyen). La segunda opción es aterradora.",
      "La hipótesis del 'Zoo Cósmico' sugiere que hay muchas civilizaciones avanzadas que nos observan pero deliberadamente evitan el contacto, quizás para permitir que nuestra civilización se desarrolle de manera independiente. Esto explicaría el Gran Silencio sin la devastadora conclusión del Gran Filtro. Sin embargo, es difícil imaginar que todas las civilizaciones acordaran tal política.",
      "La hipótesis de la 'Tierra Rara' (Ward y Brownlee, 2000) sugiere que la vida compleja (animales multicelulares e inteligencia) requiere una combinación tan específica de factores (posición en la galaxia, tipo de estrella, presencia de luna, tectónica de placas, etc.) que podría ser extremadamente rara en el universo aunque la vida microbiana sea común.",
      "SETI (Search for Extra-Terrestrial Intelligence) comenzó en 1960 con el proyecto Ozma de Frank Drake, que apuntó un radiotelescopio hacia dos estrellas cercanas. Desde entonces, se han realizado miles de horas de observación. La única señal potencialmente interesante fue la 'Señal Wow!' de 1977: una señal de 72 segundos de origen desconocido que nunca se repitió.",
      "La señal Wow! fue captada el 15 de agosto de 1977 por el telescopio Big Ear de Ohio. Era una señal de radio de las características que SETI busca: estrecha, a la frecuencia del hidrógeno (1420 MHz) y con una intensidad 30 veces mayor que el ruido de fondo. El investigador Jerry Ehman escribió '¡Wow!' en el margen del papel. Nunca se ha encontrado su origen.",
      "METI (Messaging Extra-Terrestrial Intelligence) es el reverso de SETI: en lugar de escuchar, enviar mensajes a las estrellas. En 1974, el Mensaje de Arecibo fue transmitido desde Puerto Rico hacia el cúmulo M13 (25,000 años luz). En 2008, el Mensaje de Gliese fue enviado hacia Gliese 581 (20 años luz). Estos mensajes son simbólicos: su recepción y respuesta está en el futuro lejano.",
      "La inteligencia artificial podría revolucionar la búsqueda de vida extraterrestre. Los radiotelescopios del proyecto Breakthrough Listen generan petabytes de datos que los humanos no pueden analizar manualmente. Los algoritmos de machine learning pueden buscar patrones en esas señales con una eficiencia miles de veces mayor que un humano. SETI@home distribuyó este análisis entre millones de computadoras voluntarias.",
      "La astrobiología es la ciencia que estudia la posibilidad de vida fuera de la Tierra. Se basa en tres preguntas: ¿Cómo surgió la vida? ¿Puede sobrevivir en condiciones extremas? ¿Puede existir en entornos diferentes al terrestre? Los extremófilos (organismos que viven en condiciones extremas en la Tierra) muestran que la vida puede adaptarse a casi cualquier entorno.",
      "Los extremófilos incluyen bacterias que viven en las fuentes hidrotermales del fondo oceánico (sin luz solar, a 350°C y alta presión), en los glaciares de la Antártida, en los lagos de ácido sulfúrico, en los reactores nucleares de Chernóbil y en el espacio exterior (tardigrados sobreviven el vacío y la radiación). Esto expande enormemente nuestro concepto de 'zona habitable'.",
      "El universo tiene 13,800 millones de años. Los primeros 1,000 millones de años no tenían planetas rocosos (no había metales pesados todavía, solo hidrógeno y helio). La vida en la Tierra tardó 4,000 millones de años en desarrollar inteligencia. Si otras civilizaciones siguieron el mismo ritmo pero comenzaron 1,000 millones de años antes, podrían llevar 1,000 millones de años de ventaja tecnológica. Serían prácticamente indistinguibles de dioses para nosotros."
    ],
    quiz: [
      { q: "¿Cuántas estrellas se estima que hay en el universo observable?", options: ["10^12","10^18","10^24","10^30"], a: 2 },
      { q: "¿Qué es la Paradoja de Fermi?", options: ["Por qué el universo se expande","Si hay tantas posibles civilizaciones, por qué no detectamos ninguna señal","Por qué los planetas son redondos","Por qué la vida tardó tanto en surgir"], a: 1 },
      { q: "¿Cuándo fue captada la 'Señal Wow!'?", options: ["1960","1977","1990","2001"], a: 1 },
      { q: "¿Qué es un extremófilo?", options: ["Una estrella muy caliente","Un organismo que vive en condiciones extremas","Una teoría sobre vida en el espacio","Un tipo de exoplaneta"], a: 1 },
      { q: "¿Qué plantea la hipótesis del 'Gran Filtro'?", options: ["El espacio tiene filtros contra la radiación","Existe una barrera casi infranqueable en la evolución hacia civilizaciones avanzadas","Las galaxias filtran la luz interestelar","Los agujeros negros filtran la materia"], a: 1 }
    ]
  },
  interestelar_m6: {
    text: [
      "El futuro de la exploración interestelar combina la mejor física teórica, la ingeniería más ambiciosa y la voluntad humana de ir más allá de los horizontes conocidos. En este módulo final repasamos lo que hemos aprendido y miramos hacia el futuro de la exploración del cosmos.",
      "La primera etapa del viaje interestelar ya ha comenzado: la humanidad ha enviado objetos artificiales más allá del sistema solar. Las sondas Voyager 1 y 2, lanzadas en 1977, cruzaron la heliopausa (el límite del sistema solar) en 2012 y 2018 respectivamente. Son los primeros objetos humanos en el espacio interestelar real.",
      "Voyager 1 está ahora a más de 23,000 millones de kilómetros del Sol (más de 150 UA). Sigue enviando señales a la velocidad de la luz, que tardan unos 22 horas en llegar a la Tierra. Su batería de radioisótopos aún produce algo de electricidad, aunque sus instrumentos se irán apagando uno a uno hasta 2025. Es el objeto humano más lejano.",
      "New Horizons, la sonda que sobrevoló Plutón en 2015, también está en camino hacia el espacio interestelar. Al pasar por Plutón, reveló que este mundo helado tiene montañas de hielo de agua, planicies de nitrógeno y una atmósfera delgada. En 2019, sobrevoló Arrokoth (2014 MU69), el objeto del sistema solar más lejano visitado por una nave.",
      "Las próximas décadas verán el lanzamiento de la primera misión diseñada específicamente para explorar el espacio interestelar. La Interstellar Probe de la NASA es una propuesta de misión que llegaría a 1,000 UA del Sol, mucho más lejos que las Voyager, en unos 50 años. Estudiaría las propiedades del medio interestelar y la heliosfera desde afuera.",
      "El telescopio espacial James Webb (lanzado en 2021) ya está revolucionando nuestra comprensión de los exoplanetas. Puede analizar la composición química de las atmósferas de planetas que orbitan otras estrellas. En 2022, detectó CO₂ en la atmósfera de WASP-39b (un exoplaneta gaseoso). En el futuro, buscará biosignatures en planetas rocosos.",
      "Las futuras misiones de telescopios espaciales (como el Habitable Worlds Observatory, propuesto para los años 2030-2040) serán diseñadas específicamente para detectar biosignatures en exoplanetas del tamaño de la Tierra. La detección simultánea de oxígeno, metano y vapor de agua en la atmósfera de un exoplaneta sería la evidencia más fuerte posible de vida.",
      "La inteligencia artificial será la herramienta clave para analizar los enormes volúmenes de datos que generarán los futuros telescopios y sondas. Los algoritmos de machine learning ya detectan exoplanetas en los datos de Kepler con mayor eficiencia que los análisis manuales. En el futuro, la IA podría identificar señales de vida que los humanos no podrían reconocer.",
      "La propulsión fotónica láser (velas de luz) avanza rápidamente. En 2022, el LightSail-2 de la Planetary Society demostró la propulsión solar exitosamente en órbita terrestre. Aunque solo el Sol, una vela más grande podría avanzar significativamente en el sistema solar. El siguiente paso es combinar esta tecnología con un potente láser terrestre o en órbita.",
      "Los nanomateriales son esenciales para la tecnología de velas interestelares. Una vela que debe ser acelerada al 20% de la velocidad de la luz debe ser extremadamente ligera (más que el papel más fino) pero resistente. El grafeno (una capa de átomos de carbono de un átomo de espesor) es 200 veces más resistente que el acero y casi sin masa. Es el material candidato para las velas interestelares.",
      "La manufactura de semiconductores ha seguido la Ley de Moore durante 50 años: la densidad de transistores en un chip se duplica cada dos años. Esto ha llevado a los chips actuales con miles de millones de transistores en un espacio del tamaño de una uña. Las nanoaves interestelares necesitarían integrar cámaras, comunicaciones, propulsión y energía en un chip de pocos gramos. Es desafiante pero plausible en décadas.",
      "La energía es el factor más limitante de la exploración interestelar. Todos los sistemas de propulsión avanzados requieren enormes cantidades de energía. La humanidad deberá escalar su producción energética dramáticamente para hacer viable el viaje interestelar. La energía de fusión nuclear (que ha estado '30 años lejos' durante 70 años) parece estar finalmente a punto de ser práctica: NIF logró ignición de fusión en 2022.",
      "La cooperación internacional será esencial para el viaje interestelar. Ninguna nación por sí sola tiene los recursos para proyectos de esta magnitud. Las misiones a planetas del sistema solar ya son colaboraciones internacionales (JWST involucra NASA, ESA y CSA). Las misiones interestelares requerirán un esfuerzo de toda la humanidad, similar a lo que una misión a la Luna fue pero a una escala incomparablemente mayor.",
      "El legado filosófico del viaje interestelar es tan importante como el técnico. Cuando seamos capaces de mirar atrás desde otra estrella y ver nuestro Sol como una estrella más entre miles, nuestra perspectiva de la humanidad cambiará para siempre. El filósofo Carl Sagan llamó a la Tierra un 'Pálido Punto Azul' cuando la vio en la fotografía de Voyager 1 desde 6,000 millones de km. Imagina verla desde otra estrella.",
      "Tú, que estudias este módulo, eres parte de la generación que podría ver los primeros pasos hacia las estrellas: el primer láser interestelar, la primera nanoave acelerada, la primera imagen de un planeta similar a la Tierra en otra estrella. El viaje interestelar no es solo el sueño de los físicos: es el destino de la humanidad curiosa, creativa y valiente que tú representas."
    ],
    quiz: [
      { q: "¿Cuándo cruzó Voyager 1 la heliopausa (límite del sistema solar)?", options: ["2000","2008","2012","2018"], a: 2 },
      { q: "¿Qué demostró LightSail-2 en 2022?", options: ["Propulsión de fusión nuclear","Propulsión solar por velas en órbita terrestre","Viaje a Marte","Un nuevo tipo de cohete"], a: 1 },
      { q: "¿Qué material es candidato para las velas interestelares ultraligeras?", options: ["Titanio","Kevlar","Grafeno","Aluminio reforzado"], a: 2 },
      { q: "¿En qué año logró el NIF ignición de fusión nuclear?", options: ["2018","2020","2022","2024"], a: 2 },
      { q: "¿Qué dijo Carl Sagan de la Tierra vista desde 6,000 millones de km?", options: ["Brillante estrella azul","Una pequeña luna","Pálido Punto Azul","Un misterioso punto verde"], a: 2 }
    ]
  }
};

for (const [id, data] of Object.entries(INTERESTELAR)) {
  src = replaceTextAndQuiz(src, id, data.text, data.quiz);
}

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ Interestelar (m1-m6) all patched!');
