const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'lib', 'courseData.js');
let raw = fs.readFileSync(filePath, 'utf8');
let data = JSON.parse(raw.replace(/^export default /, '').replace(/;$/, ''));

const bttf_m4 = [
  "¡Atención, ingeniero eléctrico! En Volver al Futuro, la escena más icónica es cuando el DeLorean necesita exactamente 1.21 gigawatts para activar el Condensador de Flujo, y Doc Brown tensa un cable entre la torre del reloj y la calle justo cuando cae el rayo. Hoy vamos a explorar la ciencia real de los rayos, la electricidad y cómo se generan, almacenan y canalizan cantidades colosales de energía. ¿Sabías que cada segundo caen unos 100 rayos en la Tierra? La física de la electricidad atmosférica es uno de los fenómenos naturales más espectaculares y poderosos del planeta. ¡Electrizante! ⚡",
  "Un gigawatt (GW) es una unidad de potencia igual a 1,000 megawatts o 1,000,000,000 watts. Para dar escala: una central nuclear típica produce entre 1 y 1.5 GW; el consumo eléctrico de una ciudad de un millón de habitantes es de aproximadamente 1-2 GW; y los paneles solares instalados en todo el mundo en 2023 tienen una capacidad total de más de 1,000 GW (International Energy Agency, 2023). La potencia que demanda el Condensador de Flujo, 1.21 GW, equivale al consumo instantáneo de toda la ciudad de Madrid durante varios segundos. ¡Es una cantidad de energía genuinamente monumental y no está fuera de escala para la tecnología nuclear moderna!",
  "Los rayos son descargas eléctricas gigantescas que ocurren cuando las diferencias de potencial eléctrico entre las nubes o entre las nubes y el suelo superan la capacidad aislante del aire. Las nubes de tormenta generan electricidad estática por colisiones entre cristales de hielo y gotitas de agua en su interior: los cristales pequeños cargados positivamente ascienden a la cima de la nube, mientras los cristales más grandes cargados negativamente descienden a la base (NOAA). Cuando la diferencia de carga es suficiente, el aire se ioniza formando un canal conductor, y la descarga cae en microsegundos. La temperatura del canal del rayo alcanza los 30,000 Kelvin, ¡cinco veces la temperatura de la superficie del Sol! (NOAA).",
  "La energía de un rayo promedio es de unos 5,000 millones de joules (5 gigajoules) en total, aunque la mayor parte se disipa como calor, luz y sonido. La energía eléctrica útil que se podría extraer de un rayo es de unos 250 kilovatios-hora, suficiente para iluminar una bombilla LED de 10 watts durante casi 3 años (NOAA). El problema de capturar energía de rayos es que son extremadamente impredecibles, duran microsegundos, y la potencia pico (millones de amperios en fracciones de segundo) destruiría cualquier equipo capturador. Los ingenieros de Harvard y MIT han experimentado con láseres que guían rayos hacia pararrayos específicos, lo que podría ser el primer paso para captura controlada (Nature Photonics, 2023).",
  "Benjamin Franklin fue el primero en demostrar experimentalmente que los rayos son electricidad, con su famoso experimento de la cometa en 1752. Conectó una llave metálica a una cometa durante una tormenta y recibió descargas eléctricas que le permitieron cargar una botella de Leyden (un condensador primitivo). Este experimento notablemente peligroso (varios científicos murieron repitiendo variantes de él) demostró que el rayo es una descarga electrostática y condujo a la invención del pararrayos. Franklin patentó el pararrayos en 1753, un dispositivo que protege edificios desviando las descargas hacia el suelo de forma segura (Franklin, 1753). ¡Un experimento de cometa cambió para siempre la relación de la humanidad con los rayos!",
  "Los supercondensadores son los dispositivos más cercanos a capturar la energía de un rayo de forma útil. Un condensador almacena energía eléctrica en un campo eléctrico entre dos placas separadas por un aislante. Los supercondensadores modernos, usados en vehículos eléctricos y electrónica portátil, pueden cargarse y descargarse en segundos, a diferencia de las baterías que tardan horas (Nature Energy, 2019). Tesla Motors usa supercondensadores en paralelo con baterías de litio para manejar picos de potencia en la aceleración. Sin embargo, almacenar 1.21 GW en un supercondensador del tamaño de un auto requeriría materiales con densidades de energía miles de veces superiores a los actuales. ¡Es un desafío de ingeniería de materiales monumental!",
  "La energía eléctrica de los rayos tiene aplicaciones reales en la geofísica y el estudio del clima. La red de detección de rayos Vaisala NLDN detecta cada rayo que cae en América del Norte con una precisión de cientos de metros y en tiempo real (Vaisala, 2023). Los científicos usan estos datos para estudiar patrones climáticos, predecir incendios forestales y calibrar modelos del sistema eléctrico global de la Tierra. La Tierra funciona como un gigantesco condensador: la ionosfera (cargada positivamente a 60-1000 km de altitud) y la superficie terrestre (cargada negativamente) forman las placas, con la atmósfera como aislante (NASA). Los rayos son la corriente de descarga de este condensador planetario. ¡La Tierra entera es un circuito eléctrico!",
  "Las tormentas eléctricas generan también rayos hacia arriba llamados 'sprites', 'elves' y 'blue jets', descubiertos científicamente en los años 1990. Los sprites son flashes rojos que aparecen sobre las nubes de tormenta a altitudes de 50-90 km, visibles desde aviones y satélites (Science, 1994). Los elves (siglas de Emission of Light and Very Low Frequency perturbations due to Electromagnetic Pulse Sources) son anillos de luz tenue que se expanden a 400 km de diámetro en milisegundos. Estos fenómenos, inaccesibles desde el suelo y solo recientemente documentados, muestran que las tormentas eléctricas son mucho más complejas de lo que parecen desde tierra. ¡La atmósfera todavía guarda secretos eléctricos asombrosos!",
  "La generación de energía eléctrica a escala de gigawatts tiene múltiples tecnologías reales. La presa Itaipú, en la frontera entre Brasil y Paraguay, genera 14 GW con turbinas hidroeléctricas y es una de las mayores plantas de energía del mundo (Itaipú Binacional, 2023). La presa de las Tres Gargantas en China produce 22.5 GW, la mayor del mundo. La fusión nuclear experimental del NIF en 2022 produjo 3.15 megajoules en nanosegundos, que extrapolado a un segundo equivaldría a gigawatts instantáneos de potencia de plasma. Los parques eólicos offshore modernos en Europa ya producen colectivamente varios GW (European Wind Energy Association, 2023). ¡Gigawatts reales se generan todos los días por la humanidad!",
  "Los efectos biológicos de la electricidad de alta potencia son fascinantes desde la perspectiva médica. El corazón humano late gracias a impulsos eléctricos de unos 80-120 milivolts generados por el nodo sinusal. Un desfibrilador eléctrico restablece el ritmo cardíaco aplicando hasta 360 joules en milisegundos, despolarizando todo el músculo cardíaco simultáneamente (American Heart Association). Las anguillas eléctricas (Electrophorus electricus) pueden generar hasta 860 voltios y 1 amperio de corriente, suficiente para aturdir a un ser humano (PNAS, 2019). Recién en 2019 se descubrió que algunas especies de anguilla eléctrica pueden sincronizar sus descargas en grupos para atacar presas más grandes: el primer caso conocido de caza eléctrica coordinada. ¡La electricidad biológica es tanto arma como herramienta!",
  "Un descubrimiento reciente muy relevante: en 2023, el MIT y la empresa Commonwealth Fusion Systems lograron generar el campo magnético superconductor más poderoso jamás creado por humanos: 20 teslas, usando imanes de REBCO (óxido de bario, cobre y tierras raras) a temperatura de nitrógeno líquido (Nature, 2021). Este campo magnético es necesario para confinar plasma de fusión a temperaturas de 100 millones de grados. Los superconductores de alta temperatura son también esenciales para construir sistemas de almacenamiento de energía magnética (SMES) que podrían acumular gigawatts en campos magnéticos y liberarlos en fracciones de segundo, ¡similar al Condensador de Flujo que carga y descarga 1.21 GW instantáneamente!",
  "Tú, joven ingeniero eléctrico, puedes explorar la electricidad de formas seguras y emocionantes. Los kits de electrónica de Arduino y Raspberry Pi permiten construir circuitos, sensores y proyectos de electrónica desde principiantes. El proyecto Science Buddies de la NSF ofrece cientos de experimentos eléctricos seguros para hacer en casa, incluyendo detectores de rayos con antenas simples. El simulador Circuit Lab permite diseñar y probar circuitos virtualmente sin riesgo. Y visita un museo de ciencias con sala de Tesla: la bobina de Tesla crea arcos eléctricos espectaculares que te permitirán ver el plasma en acción de forma segura. ¡La electricidad es el lenguaje de la naturaleza y puedes aprenderlo desde ya!",
  "El futuro de la energía eléctrica incluye redes inteligentes (smart grids) que equilibran producción y consumo en tiempo real usando algoritmos de inteligencia artificial (International Energy Agency, 2023). El almacenamiento de energía en baterías de estado sólido, que duplican la densidad energética del litio-ion actual, se espera para 2030 (Nature Energy, 2023). Los cables superconductores de alta temperatura, que transmiten electricidad sin pérdidas por calor, ya se instalan en redes de distribución en proyectos piloto en Europa y Asia. Y la fusión nuclear comercial, si se logra en los años 2030-2040, podría proporcionar electricidad de base limpia e ilimitada que haría obsoletas las preocupaciones de suministro energético global. ¡El futuro energético es eléctrico y brillante!",
  "La electricidad conecta todo el cosmos de maneras profundas. Las estrellas brillan por reacciones nucleares que producen calor que genera campos magnéticos que aceleran partículas cargadas que crean rayos cósmicos que caen sobre nuestra atmósfera que genera los rayos que vemos durante las tormentas. El universo temprano estaba completamente ionizado, es decir, era un plasma eléctricamente conductivo donde protones y electrones no podían unirse. El momento en que el universo se enfrió lo suficiente para que los electrones se unieran a los protones y formaran átomos neutros fue el momento en que la luz pudo viajar libremente por primera vez: ese instante lo vemos hoy como la Radiación de Fondo de Microondas (NASA). ¡La electricidad tiene una historia cósmica!",
  "¡Circuito completado, ingeniero del tiempo! Ahora sabes que 1.21 gigawatts es una cantidad de energía real equivalente a una central nuclear, que los rayos son descargas eléctricas a 30,000 K que duran microsegundos, que Benjamin Franklin demostró en 1752 que los rayos son electricidad, y que los supercondensadores y la fusión nuclear son los candidatos más prometedores para almacenar y liberar energía a escala de gigawatts. La electricidad es la fuerza que mueve la civilización humana y que hace bailar los rayos en la tormenta. ¡Que los 1.21 gigawatts estén contigo! 🌟"
];

const bttf_m5 = [
  "¡Súbete al aeropatín, explorador de la levitación! En Volver al Futuro II, Marty McFly usa un aeropatín (hoverboard) que flota sobre el suelo sin ruedas, en el año 2015 ficticio. Cuando la película salió en 1989, el año 2015 parecía lejano y lleno de maravillas tecnológicas. Hoy exploraremos la ciencia real de la levitación magnética, la superconductividad, y cuánto se han acercado los ingenieros del siglo XXI a construir un aeropatín funcional. ¡La respuesta te va a dejar flotando de asombro! 🛹",
  "La levitación magnética (maglev) es el principio de hacer flotar un objeto usando fuerzas magnéticas para contrarrestar la gravedad. Los trenes Maglev en Japón, China y Corea del Sur ya usan este principio para flotar sobre sus rieles: sin contacto físico con la superficie, eliminando la fricción y permitiendo velocidades extraordinarias (Japan Railway Technical Research Institute). El tren SCMaglev japonés alcanzó en 2015 una velocidad récord de 603 km/h en pruebas, más del doble de la velocidad de los trenes de alta velocidad convencionales (JR Central, 2015). El Shanghai Maglev, en servicio comercial desde 2004, transporta pasajeros a 431 km/h. ¡Los trenes que flotan ya son transporte real en Asia!",
  "Hay dos principios fundamentales de levitación magnética usados en tecnología real. El primero es la repulsión electromagnética: corrientes eléctricas en las bobinas del carril crean campos magnéticos que repelen imanes permanentes en el tren (principio EMS). El segundo usa superconductores: cuando ciertos materiales se enfrían a temperaturas cercanas al cero absoluto, su resistencia eléctrica cae a exactamente cero y expulsan completamente los campos magnéticos de su interior (efecto Meissner-Ochsenfeld, descubierto en 1933). Un superconductor enfriado puede flotar sobre un imán permanente porque el campo magnético del imán es repelido completamente por el superconductor. ¡El efecto Meissner es el aeropatín real de los laboratorios de física!",
  "Los superconductores fueron descubiertos en 1911 por el físico holandés Heike Kamerlingh Onnes al enfriar mercurio a 4 Kelvin (-269°C) y observar que su resistencia eléctrica desaparecía completamente (Kamerlingh Onnes, 1911). Este descubrimiento le valió el Premio Nobel de Física en 1913. Durante décadas, los superconductores solo funcionaban a temperaturas cercanas al cero absoluto, requiriendo helio líquido ultrafrío. En 1986, Georg Bednorz y Alex Müller descubrieron superconductores de alta temperatura en cerámicas de cobre y óxido, que funcionan a temperaturas de hasta -135°C (Nobel Prize, 1987). Y en 2023, un equipo de la Universidad de Rochester reportó superconductividad a temperatura ambiente y presión moderada en hidruro de lutecio, aunque los resultados son todavía controvertidos (Nature, 2023).",
  "En 2014, la empresa Hendo lanzó una campaña de crowdfunding para su aeropatín magnético real, que flotaba unos 2.5 cm sobre una superficie de cobre usando cuatro discos de levitación electromagnética (Hendo, 2014). El patinador profesional Tony Hawk lo probó públicamente. Sin embargo, solo funcionaba sobre superficies de cobre no ferroso, y su duración de batería era de solo unos minutos. La empresa ArcaBoard lanzó en 2016 un 'hoverboard' que usaba 36 ventiladores para flotar sobre cualquier superficie, con una duración de batería de 6 minutos y un precio de 20,000 dólares (ARCA Space Corporation, 2016). ¡Estos son los primeros aeropatines comerciales reales, aunque muy lejos del de Marty McFly!",
  "La levitación acústica es otra forma real de hacer flotar objetos sin contacto físico. Usando ondas de sonido de alta frecuencia (ultrasónicas), los investigadores pueden crear nodos de presión estacionaria que soportan pequeños objetos en el aire. El equipo del MIT demostró en 2013 que podían mover objetos levitados acústicamente en tres dimensiones (Physical Review Letters, 2013). La ESA investiga la levitación acústica para manipular muestras de materiales en el espacio sin contaminación por contacto (ESA, 2019). Aunque hoy solo funciona con objetos muy pequeños y ligeros, el principio es sólido. ¡El sonido puede levantar objetos reales, como un aeropatín mágico de ondas de presión!",
  "La levitación por diamagnetismo es quizás la forma más espectacular. Todos los materiales son ligeramente diamagnéticos, es decir, crean un campo magnético que se opone al campo externo cuando están dentro de uno. Aunque este efecto es débil en la mayoría de materiales, los imanes superconductores de alto campo (varios teslas) pueden levitar objetos diamagnéticos ordinarios. En 2000, el físico Andre Geim levitó una rana viva usando un campo magnético de 16 teslas, un experimento que le valió el Ig Nobel de Física en 2000 y el Nobel real en 2010 por el descubrimiento del grafeno (IgNobel, 2000). ¡La rana flotante de Geim es uno de los experimentos más memorables de la física experimental!",
  "El grafeno, el material descubierto por Andre Geim y Konstantin Novoselov en 2004 con una cinta adhesiva y grafito de lápiz (Science, 2004), es el candidato más prometedor para construir un aeropatín real del futuro. El grafeno es una lámina de carbono de un átomo de grosor, 200 veces más resistente que el acero por unidad de peso, con una conductividad eléctrica extraordinaria. Apilado en ciertos ángulos, el grafeno se vuelve superconductor a bajas temperaturas (un fenómeno llamado 'ángulo mágico' descubierto por Pablo Jarillo-Herrero del MIT en 2018). Si los superconductores de temperatura ambiente basados en grafeno se hicieran prácticos, el aeropatín magnético de Marty McFly sería tecnológicamente posible. ¡El grafeno podría ser el material del futuro del hoverboard!",
  "El tren Hyperloop, propuesto por Elon Musk en 2013, combina la levitación magnética con el transporte en tubos de baja presión para eliminar tanto la fricción como la resistencia del aire (Musk, 2013). En teoría, un Hyperloop podría transportar cápsulas de pasajeros a 1,200 km/h, más rápido que un avión comercial. Empresas como Virgin Hyperloop y Hardt Hyperloop están construyendo prototipos y realizando pruebas. En 2020, Virgin Hyperloop realizó la primera prueba con pasajeros humanos en una pista de 500 metros en Nevada, alcanzando 172 km/h (Virgin Hyperloop, 2020). Aunque hay desafíos de ingeniería enormes, el Hyperloop es la evolución lógica del Maglev: transporte levitado sin fricción ni aire. ¡El futuro del transporte ya flota!",
  "Los campos magnéticos también tienen aplicaciones médicas cruciales. La resonancia magnética (RM o MRI en inglés) usa imanes superconductores de 1.5 a 7 teslas para alinear los protones del agua en el cuerpo y luego detectar cómo se relajan, produciendo imágenes de tejidos blandos con resolución milimétrica sin radiación ionizante (Nobel Prize in Medicine, 2003). Los imanes superconductores de los escáneres MRI pesan varias toneladas y se enfrían con helio líquido a 4 Kelvin. La levitación magnética también se usa en bombas de sangre implantables para pacientes con insuficiencia cardíaca: el rotor de la bomba flota magnéticamente sin contacto mecánico, eliminando el desgaste y la posibilidad de coágulos (New England Journal of Medicine, 2019). ¡La levitación magnética salva vidas todos los días!",
  "Un descubrimiento reciente revolucionario: en 2023, el físico Ranga Dias de la Universidad de Rochester publicó en Nature el hallazgo de un material (hidruro de lutecio con nitrógeno) que superconducta a 21°C y a presiones de unos 10,000 atmósferas (Nature, 2023). Aunque la reproducibilidad del experimento está bajo escrutinio y varios grupos no han podido reproducirlo, si se confirma, sería el primer superconductor de temperatura ambiente real. Un superconductor que funcione a temperatura ambiente y presión razonable permitiría cables eléctricos sin pérdidas, trenes maglev sin refrigeración, y aeropatines magnéticos prácticos. ¡La superconductividad a temperatura ambiente es el santo grial de la física de materiales!",
  "Tú, joven inventor, puedes explorar la levitación magnética con materiales de bajo costo. Compra imanes de neodimio (los imanes más fuertes disponibles al público) en tiendas de electrónica o internet. Con imanes y una plataforma de cartón puedes construir un levitador pasivo donde un imán flota sobre otros imanes de la misma polaridad. Busca en YouTube el experimento del 'levitador de Meissner' usando nitrógeno líquido y un superconductor de YBCO, que ya se vende en kits educativos en varios países. El simulador FEMM (Finite Element Method Magnetics) es gratuito y permite simular campos magnéticos en computadora. ¡Tu próximo proyecto podría ser el prototipo del aeropatín del futuro!",
  "El futuro de la levitación magnética incluye sistemas de transporte Maglev de nueva generación como el EDS (Electrodynamic Suspension) japonés que usa superconductores criogénicos para flotar sin contacto activo, logrando alturas de levitación de 100 mm y velocidades de hasta 700 km/h (JR Central, 2023). La NASA investiga sistemas de lanzamiento de cargas al espacio usando rieles electromagnéticos (railguns) que acelerarían cargas a velocidades orbitales sin cohetes, usando solo electricidad (NASA, 2022). Los satélites de comunicaciones Starlink de SpaceX, que orbitan a 550 km de altitud, son en cierto sentido objetos levitados magnéticamente por el campo gravitacional terrestre en equilibrio con su velocidad orbital. ¡La levitación, en sus distintas formas, ya es la columna vertebral de nuestra civilización tecnológica!",
  "La levitación magnética conecta con uno de los conceptos más profundos de la física: el electromagnetismo y la gravedad son dos de las cuatro fuerzas fundamentales del universo. La gravedad atrae, el electromagnetismo puede tanto atraer como repeler, y la superconductividad es el estado en que el electromagnetismo vence perfectamente a la gravedad para ciertos materiales. Unificar estas dos fuerzas, como Einstein intentó hacer sin éxito en los últimos 30 años de su vida, sigue siendo uno de los grandes objetivos de la física teórica (Einstein, 1950). Los físicos modernos usan la Teoría M (extensión de la teoría de cuerdas) como candidata más prometedora para esta unificación. ¡El aeropatín de Marty McFly es una ventana a algunos de los misterios más profundos del universo!",
  "¡Aterrizaje suave completado, ingeniero de levitación! Ahora sabes que los trenes Maglev ya alcanzan 603 km/h en Japón usando levitación electromagnética, que los superconductores expulsan los campos magnéticos por el efecto Meissner y pueden flotar sobre imanes, que el grafeno a 'ángulo mágico' se vuelve superconductor, y que el aeropatín de Hendo ya es un prototipo real aunque limitado. La superconductividad a temperatura ambiente, si se confirma en materiales como el hidruro de lutecio, cambiaría completamente el mundo. El hoverboard de Marty McFly ya no es ciencia ficción: es un desafío de ingeniería que la próxima generación de científicos resolverá. ¡Flota hacia el futuro! 🌟"
];

// Patch the modules
let patched = 0;
for (let module of data) {
  if (module.id === 'bttf_m4') {
    module.contentEs.sections[0].text = bttf_m4;
    patched++;
  }
  if (module.id === 'bttf_m5') {
    module.contentEs.sections[0].text = bttf_m5;
    patched++;
  }
}

console.log(`Patched ${patched} modules.`);
fs.writeFileSync(filePath, 'export default ' + JSON.stringify(data, null, 2) + ';', 'utf8');
console.log('File written successfully.');
