const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, '../lib/courseData.js');

let src = fs.readFileSync(FILE, 'utf8');

function patchModule(src, moduleId, newText, newQuiz) {
  const modIdx = src.indexOf(`"id": "${moduleId}"`);
  if (modIdx === -1) { console.log(`NOT FOUND: ${moduleId}`); return src; }
  // Find sections array
  const sectionsIdx = src.indexOf('"sections"', modIdx);
  const textIdx = src.indexOf('"text"', sectionsIdx);
  const arrOpen = src.indexOf('[', textIdx);
  let depth = 0, i = arrOpen;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { depth--; if (depth === 0) break; }
    i++;
  }
  src = src.slice(0, arrOpen) + JSON.stringify(newText, null, 12) + src.slice(i + 1);

  // Patch quiz
  const modIdx2 = src.indexOf(`"id": "${moduleId}"`);
  const quizIdx = src.indexOf('"quizEs"', modIdx2);
  const nextModIdx = src.indexOf('"id": "', modIdx2 + 10);
  if (quizIdx !== -1 && (nextModIdx === -1 || quizIdx < nextModIdx)) {
    const qArrOpen = src.indexOf('[', quizIdx);
    let d2 = 0, j = qArrOpen;
    while (j < src.length) {
      if (src[j] === '[') d2++;
      else if (src[j] === ']') { d2--; if (d2 === 0) break; }
      j++;
    }
    src = src.slice(0, qArrOpen) + JSON.stringify(newQuiz, null, 4) + src.slice(j + 1);
  }
  console.log(`✅ Patched ${moduleId}`);
  return src;
}

// ========== AREA 51 M1 ==========
src = patchModule(src, 'area51_m1', [
  "¡Bienvenido, agente secreto espacial! Hoy tu misión es descubrir uno de los lugares más misteriosos del planeta Tierra: el Área 51. Está escondido en medio del desierto de Nevada, en los Estados Unidos, rodeado de montañas áridas y cielos azules donde el sol abrasa. Desde el aire parece solo una mancha gris en la arena, pero adentro ocurren cosas que cambiaron la historia de la aviación y la tecnología. El gobierno lo mantuvo en secreto durante décadas, y eso hizo que la imaginación de la gente volara sin límites.",
  "El nombre oficial de este lugar es Base de la Fuerza Aérea de Estados Unidos en Groom Lake, porque está construida junto a un enorme lago seco de sal que brilla como un espejo bajo el sol. Los pilotos y científicos que trabajan ahí deben firmar contratos de secreto total: no pueden contarle a nadie, ni siquiera a sus familias, lo que hacen en el trabajo. Este nivel de secretismo extremo fue lo que disparó todas las teorías y rumores que conocemos hoy.",
  "La base existe desde la década de 1950, cuando el gobierno americano necesitaba un lugar alejado de todo para probar sus aviones más avanzados en secreto. La guerra fría con la Unión Soviética estaba en su punto más caliente, y los dos países competían para ver quién construía los mejores aviones espía y los cohetes más potentes. El Área 51 se convirtió en el laboratorio secreto donde América desarrollaba sus armas tecnológicas más poderosas.",
  "Una de las razones por las que la gente comenzó a sospechar que ahí había cosas extrañas fue la gran cantidad de objetos voladores que los vecinos del desierto reportaban. Luces brillantes que se movían a velocidades imposibles, formas triangulares que giraban en silencio, y objetos que desaparecían en un segundo. Los avistamientos eran reales, pero la explicación no era extraterrestre: eran aviones secretos siendo probados de noche para que nadie los viera bien.",
  "El avión más famoso probado en el Área 51 fue el U-2, un espía de las alturas capaz de volar a más de 21 kilómetros sobre el suelo, donde el cielo comienza a volverse negro y las estrellas se ven incluso de día. Ningún avión de combate de la época podía alcanzarlo. El U-2 fotografiaba bases militares soviéticas sin que nadie pudiera detenerlo, y esas fotos dieron información crucial a los líderes americanos durante la guerra fría.",
  "Cuando los pilotos volaban el U-2 en el Área 51, el avión parecía una enorme mariposa plateada con alas larguísimas y delgadas. Volaba tan alto que el piloto necesitaba un traje especial parecido al de un astronauta para no congelarse ni quedarse sin oxígeno. A esas alturas, el cielo se ve completamente oscuro aunque sea de día, y desde allá arriba puedes ver la curvatura de la Tierra con tus propios ojos.",
  "Después del U-2 vino el SR-71 Blackbird, el avión más rápido jamás tripulado por humanos. Podía volar a más de tres veces la velocidad del sonido, lo que significa que cruzaba los Estados Unidos de costa a costa en apenas una hora. Si un misil enemigo intentaba derribarlo, el piloto simplemente aceleraba y el misil nunca podía alcanzarlo. Hoy el SR-71 sigue siendo un ícono de la ingeniería aeroespacial humana.",
  "El calor que producía el SR-71 al volar tan rápido era tan intenso que el avión se expandía varios centímetros. Por eso, cuando estaba en tierra y frío, los ingenieros lo construían con pequeñas ranuras entre las piezas de metal. Al volar, el calor dilataba el metal y cerraba esas ranuras. ¡Era como un rompecabezas de metal diseñado para expandirse a velocidades supersónicas! Esto requirió una ingeniería de precisión absolutamente extraordinaria.",
  "Otro proyecto secreto fue el Have Blue, el primer avión furtivo o stealth del mundo. Fue diseñado con formas angulosas, llenas de triángulos y planos inclinados, para que las ondas de radar rebotaran en direcciones diferentes en lugar de regresar al radar enemigo. En pantalla, el Have Blue aparecía tan pequeño como un pájaro, aunque en realidad era un avión de guerra. Esta tecnología luego evolucionó en el famoso bombardero B-2 Spirit.",
  "La tecnología stealth funciona gracias a la física de las ondas electromagnéticas. Cuando el radar emite su señal, esta viaja en línea recta hasta el avión y rebota de regreso. Si el avión tiene formas que desvían la señal en otra dirección, el radar nunca recibe el rebote y 'cree' que no hay nada ahí. Además, algunos materiales absorben las ondas de radar en lugar de reflejarlas, haciéndolo aún más invisible. ¡Es ciencia pura al servicio de la aviación!",
  "El secreto extremo del Área 51 también tiene una explicación práctica: si los ingenieros y pilotos que trabajaban ahí revelaban lo que hacían, los espías soviéticos podrían robar los diseños de los aviones. Durante la guerra fría, ambos países tenían redes de espionaje enormes, y un secreto filtrado podía cambiar el equilibrio de poder global. Por eso el gobierno prefería que la gente creyera en platillos voladores antes de revelar sus verdaderos proyectos.",
  "Hoy en día, muchos de los secretos del Área 51 han sido desclasificados por el gobierno americano. En 2013, la CIA publicó documentos oficiales reconociendo que el Área 51 existe y que se usaba para probar aviones espía. Pero eso no ha detenido las teorías conspirativas: mucha gente sigue creyendo que hay más secretos guardados, túneles subterráneos, o tecnología extraterrestre escondida en sus profundidades.",
  "Lo que sí podemos afirmar con certeza es que el Área 51 representa un capítulo brillante de la historia de la ingeniería y la aeronáutica humana. Los científicos e ingenieros que trabajaron ahí resolvieron problemas que parecían imposibles: cómo volar más alto, más rápido, más silencioso e invisible. Muchas tecnologías que usamos hoy en aviones comerciales, satélites y sistemas de comunicación tienen su origen en los experimentos secretos de ese desierto.",
  "Alrededor del Área 51 existe una atracción turística llamada la Autopista Extraterrestre, donde hay tiendas de souvenirs, restaurantes con nombres de alienígenas y hasta un motel con forma de nave espacial. Cada año, miles de turistas visitan la zona esperando ver algo misterioso en el cielo o encontrar evidencias de vida extraterrestre. Aunque no hay pruebas de alienígenas, el paisaje desértico con sus cielos estrellados es impresionante y vale mucho la pena verlo.",
  "¿Y los alienígenas? Hasta el día de hoy no hay ninguna evidencia científica de que el Área 51 guarde tecnología o seres extraterrestres. Lo que sí hay son décadas de brillante ingeniería humana, pilotos valientes que arriesgaron su vida probando máquinas nunca antes voladas, y científicos creativos que empujaron los límites de lo posible. La gran lección del Área 51 es que la mente humana, cuando trabaja con pasión y sin límites, puede crear cosas que parecen de otro mundo."
], [
  { q: "¿En qué estado de Estados Unidos se encuentra el Área 51?", options: ["Texas", "California", "Nevada", "Arizona"], a: 2 },
  { q: "¿Cuál fue uno de los primeros aviones espía probados en el Área 51?", options: ["SR-71 Blackbird", "U-2", "B-2 Spirit", "F-117"], a: 1 },
  { q: "¿Por qué la tecnología stealth hace que un avión sea casi invisible para el radar?", options: ["Porque vuela muy alto", "Porque vuela muy rápido", "Porque sus formas desvían las ondas de radar", "Porque está pintado de negro"], a: 2 },
  { q: "¿Cuántas veces la velocidad del sonido podía alcanzar el SR-71 Blackbird?", options: ["Una vez", "Dos veces", "Tres veces", "Cuatro veces"], a: 2 },
  { q: "¿Qué publicó la CIA en 2013 sobre el Área 51?", options: ["Que ahí vivían alienígenas", "Que el lugar no existe", "Que era una base para probar aviones espía", "Que tenía tecnología extraterrestre"], a: 2 }
]);

// ========== AREA 51 M2 ==========
src = patchModule(src, 'area51_m2', [
  "¡Cadete, prepárate para despegar hacia los cielos más secretos del mundo! En el módulo de hoy vamos a explorar los increíbles aviones que se desarrollaron en el Área 51. Estos no eran aviones ordinarios: eran máquinas diseñadas para volar donde ningún otro avión había llegado, más rápido que ninguno y sin ser detectados. Cada uno de ellos fue una revolución tecnológica que cambió para siempre cómo entendemos la aviación.",
  "El primero y más importante de estos aviones fue el Lockheed U-2, que comenzó a volar en 1955. Su diseño era elegante y extraño: tenía alas enormes como las de un planeador, pero impulsado por un potente motor a chorro. Esas alas largas le permitían volar con eficiencia a alturas extremas donde el aire es tan delgado que casi no existe. El U-2 podía llegar a 21 kilómetros de altura, un lugar donde el cielo se ve oscuro y las estrellas brillan incluso de día.",
  "Para los pilotos del U-2, cada vuelo era una aventura al límite de la supervivencia humana. El traje que usaban era básicamente un traje espacial: sellado herméticamente, con su propio suministro de oxígeno y sistemas de control de temperatura. Si el traje fallaba a esa altitud, el piloto perdería la conciencia en segundos. Cada detalle del equipo se revisaba cientos de veces antes de cada vuelo, porque no había margen para el error.",
  "El U-2 fotografiaba el territorio soviético con cámaras de una precisión asombrosa. Desde 21 kilómetros de altura podía tomar fotos donde se distinguía el número de matrícula de un automóvil. Imagina la calidad de esas imágenes: desde casi el espacio, podías leer los letreros de las calles en Moscú. Esas fotos revelaron la construcción de misiles, bases militares y movimientos de tropas que los líderes americanos necesitaban conocer urgentemente.",
  "En 1960 ocurrió un incidente dramático: un U-2 pilotado por Francis Gary Powers fue derribado sobre la Unión Soviética. Los soviéticos habían desarrollado un misil que finalmente podía alcanzar esa altitud. Powers sobrevivió pero fue capturado y juzgado como espía. El incidente provocó una crisis diplomática internacional y demostró que ninguna tecnología es invulnerable para siempre. Powers fue intercambiado por un espía soviético dos años después.",
  "Después del U-2, los ingenieros del Área 51 crearon algo aún más audaz: el A-12, el precursor del famoso SR-71 Blackbird. El A-12 era tan rápido que volaba a más de 3.200 kilómetros por hora, más de tres veces la velocidad del sonido. A esas velocidades, el avión se calentaba tanto que sus superficies alcanzaban temperaturas de más de 300 grados Celsius. Por eso estaba construido principalmente con titanio, un metal que soporta el calor extremo.",
  "El titanio para los A-12 y SR-71 tenía que comprarse de forma secreta porque su principal proveedor era... ¡la Unión Soviética! Los agentes de la CIA crearon empresas fantasma para comprar el titanio soviético sin que los soviéticos supieran que estaban ayudando a construir el avión espía que los vigilaría. Fue uno de los operativos secretos más ingeniosos de la guerra fría: usar el metal del enemigo para espiar al enemigo.",
  "El SR-71 Blackbird fue el avión más rápido con tripulación humana jamás construido. Podía volar tan rápido que si un misil enemigo lo disparaba, el piloto simplemente aceleraba un poco más y el misil nunca lo alcanzaba. Estableció récords de velocidad y altura que todavía no han sido superados por aviones tripulados. El SR-71 fue retirado en 1998, pero su legado sigue inspirando a diseñadores de aviones en todo el mundo.",
  "Un dato fascinante del SR-71 es que volaba tan rápido que los pilotos debían calcular cuánto avanzaría el avión durante el tiempo que tardaba en tomar una fotografía. Si no compensaban ese movimiento, las fotos saldrían borrosas. El avión también podía sobrevolar una ciudad entera y fotografiar todo su territorio en cuestión de segundos. Su cámara especial revelaba detalles con una precisión increíble desde alturas estratosféricas.",
  "El proyecto Have Blue fue el comienzo de los aviones stealth o furtivos. Sus diseñadores rompieron todas las reglas de aerodinámica tradicional: en lugar de curvas suaves, lo hicieron con superficies planas y angulosas que parecían extrañas. Los primeros pilotos que lo probaron decían que era el avión más difícil de volar que habían visto. Las computadoras tenían que hacer constantes correcciones para mantenerlo estable, porque aerodinámicamente era casi imposible de volar de forma natural.",
  "La tecnología stealth se basa en que las formas angulosas reflejan las ondas de radar en ángulos que no regresan al receptor. Imagina lanzar una pelota contra una pared inclinada: rebota hacia un lado, no de regreso a tus manos. Lo mismo pasa con el radar y el avión stealth. Además, los materiales con los que está construido absorben parte de la energía del radar en lugar de reflejarla, haciendo que la señal sea aún más débil.",
  "El F-117 Nighthawk fue el primer avión stealth operativo que voló desde el Área 51. Cuando lo veías en tierra parecía imposible que pudiera volar: era todo ángulos rectos y superficies planas. Pero en el radar enemigo era prácticamente invisible. El F-117 participó en misiones de combate reales y demostró que la tecnología stealth funcionaba perfectamente en condiciones reales de guerra. Fue un hito histórico en la aviación militar.",
  "Muchos otros proyectos secretos se probaron en el Área 51 a lo largo de los años. Drones de reconocimiento que volaban sin piloto, aviones de combate experimentales con formas nunca vistas, y sistemas de propulsión que aún no conocemos completamente. La base sigue activa hoy en día y sin duda continúa siendo el lugar donde se prueban las tecnologías aéreas más avanzadas del mundo, muchas de las cuales solo conoceremos dentro de décadas.",
  "La influencia del Área 51 en la aviación civil es enorme aunque pocos la conocen. Los materiales compuestos, los sistemas de navegación de precisión, los motores de alta eficiencia y las computadoras de control de vuelo que usamos en aviones comerciales modernos tienen sus raíces en los experimentos realizados en ese desierto. Cada vez que subes a un avión moderno, parte de la tecnología que te lleva sano y salvo a tu destino nació en el Área 51.",
  "¿Qué aviones secretos se están probando ahí ahora mismo? Eso no lo sabemos, y probablemente no lo sabremos por décadas. Pero podemos estar seguros de que los ingenieros y pilotos del Área 51 están empujando los límites de lo posible, soñando con volar más rápido, más alto y más eficientemente. Algún día, cuando esos proyectos sean desclasificados, el mundo se asombrará de lo que la mente humana fue capaz de crear en ese rincón secreto del desierto de Nevada."
], [
  { q: "¿A qué altura máxima podía volar el avión espía U-2?", options: ["5 kilómetros", "10 kilómetros", "21 kilómetros", "50 kilómetros"], a: 2 },
  { q: "¿De qué metal especial estaba construido principalmente el SR-71 Blackbird?", options: ["Aluminio", "Acero", "Titanio", "Platino"], a: 2 },
  { q: "¿Qué piloto americano fue capturado por los soviéticos en 1960?", options: ["Neil Armstrong", "Chuck Yeager", "John Glenn", "Francis Gary Powers"], a: 3 },
  { q: "¿Cómo se llama la tecnología que hace invisible a un avión para el radar?", options: ["Stealth", "Supersónica", "Hipersónica", "Subórbital"], a: 0 },
  { q: "¿Cuál fue el primer avión stealth operativo en volar desde el Área 51?", options: ["SR-71 Blackbird", "U-2", "F-117 Nighthawk", "B-2 Spirit"], a: 2 }
]);

// ========== AREA 51 M3 ==========
src = patchModule(src, 'area51_m3', [
  "¡Alerta, cadete! En este módulo vamos a investigar el misterio más grande del Área 51: ¿cómo comenzaron todos los rumores de extraterrestres? La historia es fascinante, y tiene más que ver con psicología humana, secretos gubernamentales y accidentes espectaculares que con seres de otro planeta. Ponte tu sombrero de detective porque estamos a punto de resolver uno de los grandes misterios de la cultura popular.",
  "Todo empezó en el verano de 1947, en un rancho cerca de Roswell, Nuevo México, cuando un granjero llamado Mac Brazel encontró restos de algo extraño esparcidos por su campo. Había trozos de metal liviano, caucho, papel de aluminio y varillas de madera. Era como si algo hubiera caído del cielo y se hubiera desintegrado. Brazel notificó a las autoridades militares, y lo que pasó después encendió décadas de especulaciones.",
  "El ejército americano emitió primero un comunicado diciendo que habían recuperado 'un disco volador'. ¡Un disco volador! Imagina el revuelo que causó eso en los periódicos de todo el mundo. Al día siguiente, el ejército corrigió su declaración y dijo que en realidad era solo un globo meteorológico de alta altitud. Pero el daño ya estaba hecho: la gente ya estaba imaginando platillos voladores y marcianitos verdes con antenas.",
  "La verdad detrás del incidente de Roswell fue revelada décadas después: lo que cayó era parte del Proyecto Mogul, un programa ultrasecreto que usaba globos de alta altitud para espiar a la Unión Soviética detectando explosiones nucleares. Los globos llevaban equipos sofisticados y podían volar a alturas enormes, lo que explica los materiales extraños que encontró el granjero. Era tecnología secreta de vigilancia, no tecnología alienígena.",
  "Pero los avistamientos de objetos voladores no identificados cerca del Área 51 continuaron durante los años 50, 60 y 70. Y la razón era simple: la base estaba probando aviones experimentales con formas y capacidades nunca vistas. El U-2, por ejemplo, volaba tan alto y era tan brillante bajo el sol que los pilotos de aerolíneas comerciales que volaban a 10 kilómetros de altura lo reportaban como un objeto brillante que se movía a velocidades imposibles.",
  "Los civiles que vivían en los pueblos alrededor del Área 51 veían luces extrañas moviéndose en el cielo nocturno durante las pruebas. Aviones triangulares con luces brillantes, objetos que hacían maniobras imposibles para los aviones convencionales, cosas que aparecían y desaparecían en segundos. El gobierno no podía explicar qué eran sin revelar los programas secretos, así que simplemente callaba o negaba todo. Ese silencio alimentó la imaginación popular.",
  "En 1989, un hombre llamado Bob Lazar dio una entrevista televisiva explosiva afirmando que había trabajado en el Área 51 en el análisis de naves espaciales extraterrestres. Sus declaraciones fueron increíblemente detalladas y técnicas, lo que convenció a muchas personas. Pero los investigadores no han podido verificar ninguna de sus afirmaciones sobre su trabajo o educación, y ninguna evidencia física ha aparecido para apoyar su historia. Aun así, Lazar se convirtió en un ícono de la cultura OVNI.",
  "La cultura popular tomó el misterio del Área 51 y lo convirtió en un fenómeno global. Películas como Independence Day, la serie de televisión X-Files, videojuegos y novelas han construido un universo imaginario donde el Área 51 es el centro de una conspiración galáctica. Aunque no hay evidencia de alienígenas, estas historias son tremendamente entretenidas y han hecho que millones de personas se interesen por la astronomía y la posibilidad de vida en otros planetas.",
  "Un evento curioso ocurrió en 2019 cuando alguien publicó en internet un evento de Facebook llamado 'Asaltemos el Área 51'. Era una broma, pero más de dos millones de personas indicaron que asistirían. El ejército americano emitió advertencias serias de que cualquier intento de ingresar a la base sería detenido con fuerza. Al final, solo algunos cientos de turistas llegaron al desierto de Nevada para una fiesta temática, pero el evento mostró el enorme poder cultural que tiene el Área 51 en el imaginario colectivo.",
  "¿Por qué la mente humana tiende a buscar explicaciones extraordinarias cuando no tiene información completa? Los psicólogos llaman a esto 'pensamiento conspirativo': cuando algo es misterioso y el poder oculta información, nuestra mente llena los huecos con las explicaciones más dramáticas posibles. En el caso del Área 51, el secretismo extremo del gobierno creó el ambiente perfecto para que florecieran las teorías más fantásticas sobre lo que ocurría ahí adentro.",
  "Los periodistas y investigadores que han seguido el rastro de los ovnis del Área 51 han llegado invariablemente a la misma conclusión: los avistamientos son reales, pero los objetos son aviones humanos muy avanzados. La gente genuinamente ve cosas extraordinarias en el cielo, objetos que se mueven a velocidades y en ángulos que los aviones convencionales no pueden. Pero eso es porque los aviones del Área 51 son décadas más avanzados que los aviones que conoce el público.",
  "El gobierno de los Estados Unidos ha desclasificado progresivamente información sobre el Área 51 a medida que los proyectos envejecen y ya no representan ventajas militares secretas. Documentos del U-2, el SR-71 y otros programas están ahora disponibles en los archivos nacionales. Esta apertura gradual ha confirmado que los grandes secretos del Área 51 eran tecnológicos y militares, no extraterrestres. Pero los creyentes en los alienígenas insisten en que aún quedan más secretos sin revelar.",
  "Lo que más debería asombrarnos del Área 51 no son los supuestos extraterrestres, sino la extraordinaria capacidad inventiva de los ingenieros y científicos humanos que trabajaron ahí. En décadas de trabajo secreto, desarrollaron tecnologías que cambiaron el mundo: fotografía aérea de altísima resolución, materiales que soportan temperaturas extremas, sistemas de sigilo que engañan al radar, y aviones que rompieron todos los récords posibles.",
  "Si alguna vez tienes la oportunidad de visitar el Museo Nacional del Aire y el Espacio en Washington D.C. o el Museo de la Fuerza Aérea en Dayton, Ohio, podrás ver de cerca algunos de los aviones que se desarrollaron en el Área 51. Ver el SR-71 Blackbird en persona es una experiencia impresionante: es un avión larguísimo, oscuro y elegante que parece más un objeto de ciencia ficción que un avión real. ¡Y pensar que volaba a más de tres veces la velocidad del sonido!",
  "La historia del Área 51 nos enseña lecciones importantes sobre el secretismo, la curiosidad humana y la tecnología. Nos muestra que el secreto crea misterio, que el misterio genera imaginación, y que la imaginación a veces vuela más lejos que la realidad. También nos recuerda que la mente humana es capaz de crear cosas tan extraordinarias que parecen de otro mundo. Quizás el mayor secreto del Área 51 es simplemente lo brillante que puede ser la humanidad cuando se propone resolver un problema imposible."
], [
  { q: "¿En qué año ocurrió el famoso incidente de Roswell?", options: ["1945", "1947", "1952", "1960"], a: 1 },
  { q: "¿Qué era realmente el objeto que cayó cerca de Roswell en 1947?", options: ["Una nave extraterrestre", "Un cohete soviético", "Un globo del Proyecto Mogul", "Un avión experimental U-2"], a: 2 },
  { q: "¿Por qué el gobierno americano no podía explicar los avistamientos de OVNIs cerca del Área 51?", options: ["Porque eran realmente extraterrestres", "Porque no sabían qué eran", "Porque revelar la verdad expondría sus aviones secretos", "Porque los pilotos mentían"], a: 2 },
  { q: "¿Qué evento masivo de internet en 2019 involucró al Área 51?", options: ["Un concierto de música", "Una maratón de videos", "Una propuesta de asaltar la base", "Un torneo de videojuegos"], a: 2 },
  { q: "¿Qué nombre recibe la tendencia humana a buscar explicaciones extraordinarias cuando hay secretos?", options: ["Pensamiento científico", "Pensamiento conspirativo", "Pensamiento crítico", "Pensamiento lateral"], a: 1 }
]);

// ========== AREA 51 M4 ==========
src = patchModule(src, 'area51_m4', [
  "¡Cadete científico, es hora de separar la ficción de la realidad! En este módulo vamos a explorar la diferencia entre la ciencia real que se practica en el Área 51 y las historias de ficción que rodean a la base. Es un viaje fascinante porque la realidad resulta ser tan asombrosa como cualquier película de ciencia ficción, solo que con ingeniería y física en lugar de magia alienígena.",
  "La ciencia real del Área 51 trata principalmente de aerodinámica, propulsión, materiales avanzados y sistemas electrónicos. Los ingenieros que trabajaban ahí se hacían preguntas como: ¿Cómo podemos volar más alto que cualquier misil enemigo? ¿Cómo construimos un avión que el radar no pueda detectar? ¿Qué materiales pueden soportar el calor de volar a tres veces la velocidad del sonido? Estas preguntas llevaron a innovaciones que definieron el siglo XX.",
  "La aerodinámica es la ciencia que estudia cómo se mueven los objetos a través del aire. Para diseñar el U-2, los ingenieros tuvieron que entender perfectamente cómo se comporta el aire a alturas extremas donde es muy delgado. Un ala normal no funciona ahí: necesitas alas mucho más largas para generar suficiente sustentación con tan poco aire. Calcular las proporciones exactas requirió miles de pruebas en túneles de viento y computadoras de la época.",
  "La propulsión supersónica fue otro gran desafío científico. A velocidades supersónicas, el aire que entra al motor del avión llega a temperaturas altísimas por compresión. Los motores tradicionales no podían manejar eso. Los ingenieros del Área 51 diseñaron entradas de aire especiales con formas que desaceleraban el aire antes de que entrara al motor, controlando la temperatura y la presión. Fue una solución elegante a un problema de física extremadamente complejo.",
  "Los materiales usados en los aviones del Área 51 representaron revoluciones en la ciencia de materiales. El titanio, por ejemplo, es un metal que pesa casi la mitad que el acero pero es igual de fuerte, y soporta temperaturas mucho más altas. Para trabajar el titanio se necesitan herramientas y procesos especiales: es un metal difícil de mecanizar. Los ingenieros del Área 51 desarrollaron técnicas completamente nuevas para cortar, dar forma y soldar el titanio con la precisión necesaria.",
  "Los materiales absorbentes de radar, usados en los aviones stealth, son otra maravilla científica. Están hechos de materiales compuestos que contienen partículas especiales capaces de convertir la energía de las ondas de radar en calor en lugar de reflejarla. Es como si el material 'comiera' las ondas de radar. Desarrollar estos materiales requirió una comprensión profunda de la física de las microondas, la química de los polímeros y la ingeniería de materiales compuestos.",
  "La ficción sobre el Área 51 generalmente ignora esta complejidad científica y va directo a los alienígenas. Películas y series muestran tecnología extraterrestre que simplemente 'funciona' sin que nadie tenga que entender cómo. Pero la ciencia real es diferente: cada avance requiere años de pruebas, cientos de experimentos fallidos, y una comprensión profunda de los principios físicos básicos. No hay atajos mágicos, ni siquiera en el Área 51.",
  "Una diferencia importante entre ciencia y ficción es la evidencia. La ciencia requiere que cada afirmación se respalde con datos medibles, experimentos repetibles y análisis cuidadoso. Cuando los creyentes en los extraterrestres del Área 51 dicen que hay naves alienígenas ahí, los científicos preguntan: ¿dónde está la evidencia? Hasta ahora, nadie ha presentado evidencia física verificable de tecnología extraterrestre. Solo testimonios personales y fotos borrosas.",
  "Los sistemas electrónicos desarrollados en el Área 51 fueron también revolucionarios. Las cámaras de reconocimiento del U-2 y el SR-71 eran obras maestras de óptica y electrónica: podían tomar miles de fotos de alta resolución desde alturas estratosféricas, compensar automáticamente el movimiento del avión, y sobrevivir las condiciones extremas de frío y vibración del vuelo. Cada componente debía ser cien veces más confiable que en un avión comercial.",
  "Los sistemas de navegación de los aviones del Área 51 también fueron pioneros. Antes del GPS, navegar con precisión a velocidades supersónicas y alturas extremas era enormemente difícil. Los ingenieros desarrollaron sistemas inerciales de navegación: aparatos que usan giroscopios ultra precisos para calcular la posición del avión sin necesidad de señales externas. Estos sistemas luego evolucionaron en la tecnología de navegación que usamos hoy en aviones comerciales y barcos.",
  "La ficción popular a menudo retrata a los científicos del Área 51 como personas que esconden la verdad maliciosamente, como villanos que saben todo sobre los alienígenas pero no lo cuentan. La realidad es más mundana y más admirable: eran ingenieros y científicos normales, apasionados por resolver problemas técnicos extraordinarios, que debían guardar secreto por razones legítimas de seguridad nacional. Su heroísmo fue intelectual, no de película de acción.",
  "La medicina aeroespacial también avanzó enormemente gracias a los programas del Área 51. Los médicos tenían que entender qué le pasaba al cuerpo humano a alturas extremas: cómo funciona la presión arterial cuando el aire exterior es casi inexistente, cómo respira el piloto, cómo mantiene la temperatura corporal, cómo su visión se adapta a ver el espacio negro y el sol al mismo tiempo. Estos conocimientos luego fueron fundamentales para los programas de astronautas.",
  "Una de las grandes lecciones científicas del Área 51 es el valor del fracaso controlado. Muchos de los aviones experimentales se estrellaron durante las pruebas. Los ingenieros analizaban meticulosamente cada accidente para entender qué había salido mal y cómo evitarlo. No era un fracaso sino un aprendizaje. Esta metodología científica de fallar, analizar y mejorar es la base del progreso tecnológico y se aplica en todas las áreas de la ciencia moderna.",
  "Hoy en día, muchas universidades y centros de investigación enseñan los principios científicos desarrollados en el Área 51. La aerodinámica de alta velocidad, los materiales avanzados, la electrónica de precisión y los sistemas de navegación inercial son temas de estudio en las mejores escuelas de ingeniería del mundo. Los jóvenes que estudian estas materias hoy son los herederos del trabajo pionero de aquellos ingenieros anónimos del desierto de Nevada.",
  "La próxima vez que alguien te hable de alienígenas en el Área 51, puedes responder con algo aún más fascinante: la verdad real. Que en ese desierto, ingenieros humanos normales crearon aviones que volaban tan alto que el cielo se volvía negro, tan rápido que derretían el metal, y tan sigilosos que los radares no los podían ver. Todo usando física, química, matemáticas e ingeniería. La ciencia real del Área 51 es más asombrosa que cualquier cuento de extraterrestres."
], [
  { q: "¿Qué estudia la aerodinámica?", options: ["El movimiento de los planetas", "El comportamiento de los objetos en el agua", "El movimiento de los objetos a través del aire", "La temperatura del espacio"], a: 2 },
  { q: "¿Por qué el titanio fue tan importante para los aviones del Área 51?", options: ["Porque es invisible al radar", "Porque es ligero, fuerte y soporta altas temperaturas", "Porque es el metal más barato", "Porque lo fabricaban en el Área 51"], a: 1 },
  { q: "¿Qué hacen los materiales absorbentes de radar usados en aviones stealth?", options: ["Reflejan el radar hacia el enemigo", "Convierten las ondas de radar en calor en lugar de reflejarlas", "Emiten señales que confunden al radar", "Bloquean físicamente las ondas de radar"], a: 1 },
  { q: "¿Qué necesita la ciencia para considerar válida una afirmación?", options: ["Testimonios personales", "Fotos borrosas", "Evidencia medible y experimentos repetibles", "La opinión de muchas personas"], a: 2 },
  { q: "¿Para qué sirven los sistemas inerciales de navegación?", options: ["Para ver a través de las nubes", "Para comunicarse con satélites", "Para calcular la posición sin señales externas usando giroscopios", "Para detectar aviones enemigos"], a: 2 }
]);

// ========== AREA 51 M5 ==========
src = patchModule(src, 'area51_m5', [
  "¡Llegamos al módulo final del Área 51, agente espacial! Hoy vamos a hablar del equipo humano detrás de los secretos: los pilotos valientes, los ingenieros brillantes y los científicos creativos que pasaron sus vidas trabajando en ese desierto misterioso. Son los verdaderos héroes de esta historia, personas reales que hicieron cosas extraordinarias en el anonimato más absoluto.",
  "Los pilotos del Área 51 eran personas especiales, seleccionadas entre los mejores aviadores militares de los Estados Unidos. Debían tener habilidades técnicas excepcionales, temperamento calmado bajo presión extrema, y la capacidad de tomar decisiones perfectas en fracciones de segundo. También tenían que ser capaces de guardar secretos absolutamente: no podían hablar de su trabajo con nadie fuera de la base, ni con sus esposas, ni con sus mejores amigos.",
  "Los pilotos que volaban el U-2 describe cada vuelo como una meditación silenciosa a alturas increíbles. A 21 kilómetros de altitud, el mundo abajo parecía un mapa, el cielo arriba era negro como la noche aunque fuera mediodía, y el silencio era casi total salvo por el suave rugido del motor. Era una experiencia sobrecogedora que pocos seres humanos han vivido. Muchos describen esos vuelos como los momentos más trascendentales de sus vidas.",
  "Un desafío técnico único del U-2 era que era muy difícil de aterrizar. A diferencia de los aviones normales, el U-2 tenía un fuselaje largo y frágil con alas inmensas que lo hacían comportarse extrañamente cerca del suelo. Había una técnica especial para aterrizar: otro piloto perseguía al U-2 en un auto de alta velocidad por la pista, gritando instrucciones por radio sobre la altitud exacta. Sin esa coordinación, el avión podía estrellarse en el aterrizaje.",
  "Kelly Johnson fue el genio detrás de muchos de los aviones más famosos del Área 51. Era el director del grupo secreto de ingeniería de Lockheed llamado Skunk Works, legendario en la industria aeroespacial. Johnson tenía un enfoque único: equipos pequeños de ingenieros muy capaces, trabajando sin burocracia, tomando decisiones rápidas y construyendo prototipos veloces para probar ideas. Esta filosofía de trabajo influyó en cómo se organizan hoy muchas empresas tecnológicas.",
  "El Skunk Works de Kelly Johnson produjo no solo el U-2 y el SR-71, sino también el primer avión stealth. Johnson creía en mantener los equipos de ingeniería pequeños y enfocados: mejor tener veinte ingenieros brillantes que doscientos ingenieros mediocres. También creía en la autonomía: sus ingenieros tenían libertad para tomar decisiones sin pedir aprobación a cada paso. Esta cultura de confianza y libertad creativa produjo resultados extraordinarios.",
  "Ben Rich sucedió a Kelly Johnson al frente del Skunk Works y llevó la tecnología stealth de la teoría a la realidad. Rich era un ingeniero de propulsión que inicialmente era escéptico sobre el stealth, pero cuando vio los datos matemáticos que probaban que funcionaba, se convirtió en su mayor defensor. Bajo su liderazgo, el F-117 Nighthawk pasó de ser un diseño en papel a un avión de combate operativo. Rich siempre decía que 'no hay nada que la ciencia no pueda resolver si la dejas trabajar libremente'.",
  "Las mujeres también jugaron roles importantes en los programas secretos del Área 51, aunque sus contribuciones tardaron en ser reconocidas. Matemáticas y analistas como las que trabajaron en la NASA procesaban los enormes volúmenes de datos de reconocimiento fotográfico, identificando instalaciones militares, contando aviones y misiles, y construyendo el cuadro de inteligencia que necesitaban los líderes americanos. Su trabajo era tan vital como el de los pilotos, pero mucho más anónimo.",
  "La vida cotidiana en el Área 51 tenía sus propias peculiaridades. Los trabajadores viajaban en autobuses especiales o en un servicio de transporte aéreo llamado JANET Airlines, que usaba aviones sin ninguna identificación para llevar empleados desde Las Vegas hasta la base. Los pilotos de JANET también tenían que guardar secreto sobre su trabajo. Era una infraestructura paralela, invisible al mundo exterior, que mantenía funcionando a toda una comunidad de científicos y técnicos.",
  "El sistema de seguridad del Área 51 era también una obra de ingeniería. Sensores sísmicos enterrados detectaban el movimiento de vehículos y personas. Cámaras ocultas vigilaban los perímetros. Patrullas con vehículos de alto rendimiento cubrían el desierto. El espacio aéreo alrededor estaba restringido a todos los aviones civiles y militares no autorizados. Era una burbuja de seguridad total en medio del desierto, diseñada para que nada entrara ni saliera sin autorización.",
  "Muchos de los trabajadores del Área 51 desarrollaron enfermedades relacionadas con la exposición a materiales tóxicos usados en los procesos de construcción de los aviones. Los solventes, pinturas y compuestos especiales de absorción de radar contenían químicos peligrosos. Durante décadas, el gobierno negó que hubiera exposición a tóxicos porque hacerlo requería admitir los programas secretos. Fue una batalla legal larga que eventualmente resultó en reconocimiento y compensaciones para los trabajadores afectados.",
  "El legado del Área 51 va más allá de los aviones que produjo. Estableció un modelo de innovación que todavía usamos: equipos pequeños, ágiles, con mucha libertad creativa y presupuestos para experimentar libremente. Muchas empresas tecnológicas de Silicon Valley han estudiado la cultura del Skunk Works para aprender cómo crear ambientes donde surjan innovaciones radicales. El espíritu del Área 51 vive en cada startup tecnológica que apuesta por ideas locas.",
  "Hoy, algunos de los ingenieros y pilotos que trabajaron en el Área 51 han podido hablar públicamente sobre sus experiencias, ahora que los programas son desclasificados. Sus memorias son fascinantes: describen un ambiente de energía y emoción, donde cada semana traía un nuevo desafío imposible. El sentido de misión era enorme: sabían que su trabajo era crucial para la seguridad de su país y que eran parte de algo históricamente significativo.",
  "Una de las grandes ironías del Área 51 es que sus trabajadores más secretos se convirtieron en los creadores involuntarios de los mitos extraterrestres. Cada vez que probaban un avión nuevo de noche y la gente lo veía moverse de formas imposibles en el cielo, nacía un nuevo rumor. Los propios ingenieros a veces escuchaban las teorías sobre alienígenas y encontraban chistoso que su trabajo de física e ingeniería fuera confundido con magia de otro mundo.",
  "El Área 51 nos deja una lección final y poderosa: el mayor tesoro no es el oro ni la tecnología extraterrestre sino la mente humana. Cuando se le da libertad, recursos, y un propósito claro, la mente humana puede crear cosas que parecen milagrosas. Los ingenieros del Área 51 no tenían poderes especiales: tenían curiosidad, determinación, creatividad y la disposición a trabajar duro por algo en lo que creían. Esas cualidades están disponibles para cualquiera que las cultive, incluyéndote a ti."
], [
  { q: "¿Cómo se llamaba el grupo secreto de ingeniería de Lockheed que trabajó en los aviones del Área 51?", options: ["Area Works", "Skunk Works", "Black Works", "Desert Works"], a: 1 },
  { q: "¿Qué ingeniero fue el fundador y primer director del Skunk Works?", options: ["Ben Rich", "Kelly Johnson", "Werner von Braun", "Howard Hughes"], a: 1 },
  { q: "¿Cómo se llamaba el servicio secreto de transporte aéreo que llevaba trabajadores al Área 51?", options: ["Shadow Air", "Ghost Airlines", "JANET Airlines", "Secret Wings"], a: 2 },
  { q: "¿Qué desafío único tenía el U-2 al momento de aterrizar?", options: ["Necesitaba una pista de 10 kilómetros", "Otro piloto en auto debía guiarlo por radio", "Debía aterrizar en la oscuridad", "Solo podía aterrizar con viento en contra"], a: 1 },
  { q: "¿Qué modelo de innovación estableció el Área 51 que sigue usándose hoy?", options: ["Equipos enormes con mucha burocracia", "Trabajo individual sin coordinación", "Equipos pequeños y ágiles con libertad creativa", "Solo ingenieros militares trabajando"], a: 2 }
]);

fs.writeFileSync(FILE, src, 'utf8');
console.log('\n✅ All Area 51 modules patched successfully!');
