const fs = require('fs');
const path = require('path');
const COURSE_DATA_PATH = path.join(__dirname, '../lib/courseData.js');

function findSectionsRange(text, moduleId) {
  const s1 = '"id": "' + moduleId + '"';
  const s2 = '"id":"' + moduleId + '"';
  let idIdx = text.indexOf(s1);
  if (idIdx < 0) idIdx = text.indexOf(s2);
  if (idIdx < 0) return null;
  const ceIdx = text.indexOf('"contentEs"', idIdx);
  if (ceIdx < 0 || ceIdx - idIdx > 5000) return null;
  const sectIdx = text.indexOf('"sections"', ceIdx);
  if (sectIdx < 0) return null;
  const arrStart = text.indexOf('[', sectIdx);
  if (arrStart < 0) return null;
  let depth = 0, arrEnd = arrStart;
  for (let i = arrStart; i < text.length; i++) {
    if (text[i] === '[') depth++;
    else if (text[i] === ']') { depth--; if (depth === 0) { arrEnd = i; break; } }
  }
  return { arrStart, arrEnd };
}

function replaceModule(moduleId, newSections) {
  let text = fs.readFileSync(COURSE_DATA_PATH, 'utf8');
  const range = findSectionsRange(text, moduleId);
  if (!range) { console.error('NOT FOUND: ' + moduleId); return; }
  const { arrStart, arrEnd } = range;
  const newArr = JSON.stringify(newSections, null, 6);
  text = text.substring(0, arrStart) + newArr + text.substring(arrEnd + 1);
  fs.writeFileSync(COURSE_DATA_PATH, text, 'utf8');
  const totalParas = newSections.reduce((s, x) => s + x.text.length, 0);
  console.log('OK: ' + moduleId + ' (' + totalParas + ' paras)');
}

const CONTENT = {

robots_historia: [
  { id: 'robots_historia_s1', title: 'El Sueño de las Máquinas que Piensan', image: '/assets/robots/historia.png', text: [
    'Un **robot** es cualquier máquina capaz de realizar tareas de forma autónoma o semiautónoma, es decir, sin que un humano tenga que darle instrucciones para cada movimiento. La palabra "robot" fue usada por primera vez en 1920 por el escritor checo Karel Čapek en su obra de teatro **"R.U.R." (Robots Universales Rossum)**. En la obra, los robots son seres artificiales creados para servir a los humanos, que finalmente se rebelan. La palabra viene del checo "robota", que significa "trabajo duro" o "servidumbre". Así que desde el principio, la idea de robot estuvo ligada a la noción de una máquina que hace el trabajo que los humanos no quieren hacer.',
    'Pero el sueño de construir máquinas que se muevan solas es mucho más antiguo que la palabra "robot". En la **antigua Grecia**, el inventor mítico Dédalo (el mismo que construyó el laberinto del Minotauro) habría creado estatuas de bronce que se movían solas. El filósofo Aristóteles (384-322 a.C.) escribió: "Si cada instrumento pudiera ejecutar su función propio o por anticipación a las órdenes, como dicen que hacían las estatuas de Dédalo... si las lanzaderas tejieran solas... los maestros no necesitarían sirvientes." Esta reflexión de hace 2,400 años captura perfectamente la idea central de la robótica moderna: automatizar el trabajo para liberar a los humanos.',
    'El primer **autómata mecánico** documentado fue construido por **Al-Jazarí**, un ingeniero árabe que vivió en lo que hoy es Turquía entre 1136 y 1206. Construyó un grupo de músicos mecánicos que flotaban en un bote sobre un estanque y tocaban música con mecanismos de leva y ruedas dentadas. También diseñó una figura mecánica que servía agua a los invitados, con un mecanismo de flotación que activaba un brazo para llenar vasos en intervalos regulares. Su libro "El libro del conocimiento de los ingeniosos mecanismos mecánicos" (1206) describe 100 dispositivos mecánicos, muchos de los cuales podemos considerar los primeros robots de la historia.',
    '**Leonardo da Vinci** (1452-1519) diseñó en 1495 lo que probablemente sea el primer robot humanoide de la historia occidental: un **caballero mecánico** articulado que podía mover los brazos, el cuello y la mandíbula mediante un sistema de cables y poleas. Los planos de Leonardo fueron redescubiertos en los años 1950 y el roboticista **Mark Rosheim**, quien trabajó para la NASA, construyó un prototipo funcional en 2002 basándose estrictamente en los diseños de Leonardo. El prototipo funcionó exactamente como Leonardo había previsto, demostrando que el genio del Renacimiento había concebido un robot funcional 500 años antes de que existiera la tecnología para construirlo.',
    'La **Revolución Industrial** del siglo XIX transformó la relación entre humanos y máquinas. Las fábricas textiles de Manchester (Inglaterra) usaban telares mecánicos programables, como el **telar de Jacquard** (1801), que usaba tarjetas perforadas para controlar patrones de tejido. Esta idea de "programar" una máquina con instrucciones grabadas en un soporte físico fue la semilla directa de los computadores modernos. Charles Babbage se inspiró en el telar de Jacquard para diseñar su "Máquina Analítica" en 1837, el primer diseño de computador mecánico de propósito general. Ada Lovelace escribió el primer algoritmo para esta máquina, convirtiéndose en la primera programadora de la historia.',
  ]},
  { id: 'robots_historia_s2', title: 'La Robótica Moderna: Del Laboratorio a la Fábrica', image: '/assets/robots/historia.png', text: [
    'El **primer robot industrial moderno** fue creado por George Devol y Joseph Engelberger en 1954. Se llamaba **Unimate** y fue instalado en 1961 en la fábrica de General Motors en Ewing Township, New Jersey. El Unimate era un brazo robótico hidráulico que pesaba 2 toneladas y realizaba tareas de soldadura y manipulación de metales calientes en la línea de producción de automóviles, tareas peligrosas y repetitivas que antes hacían obreros humanos. Su instalación fue el inicio de la automatización industrial moderna. Hoy, la fábrica promedio de automóviles tiene entre 1,000 y 4,000 robots industriales trabajando en líneas de producción.',
    'En 1956, el escritor de ciencia ficción **Isaac Asimov** publicó sus famosas **"Tres Leyes de la Robótica"** (en realidad las había formulado desde 1942): 1) Un robot no puede dañar a un ser humano, ni por inacción permitir que un ser humano sufra daño. 2) Un robot debe obedecer las órdenes de los seres humanos, excepto si estas órdenes entran en conflicto con la Primera Ley. 3) Un robot debe proteger su propia existencia mientras esta protección no entre en conflicto con las leyes anteriores. Estas "leyes" son ficción, no reglas reales de ingeniería, pero han influido profundamente en cómo los investigadores y filósofos piensan sobre la **ética de la robótica y la inteligencia artificial**.',
    'El **robot SHAKEY** (1966-1972), desarrollado en el Stanford Research Institute, fue el primer robot móvil con capacidad de razonar sobre sus propias acciones. Tenía cámaras de televisión, un sonar, y un computador que ocupaba una habitación entera. Podía recibir instrucciones en inglés simple como "mueve el cubo rojo a la habitación B" y planificar los pasos necesarios para lograrlo: navegar por corredores, esquivar obstáculos, empujar objetos. SHAKEY combinó por primera vez **robótica, visión artificial e inteligencia artificial**. Fue el precursor directo de los robots autónomos modernos como los rovers de Marte.',
    'La **robótica espacial** tiene sus raíces en los años 1960. El **Luna 9** soviético (1966) fue el primer objeto construido por humanos en aterrizar suavemente en la Luna. El **Lunokhod 1** (1970) fue el primer vehículo de exploración controlado remotamente en operar en otro mundo: un rover de 8 ruedas controlado desde la Tierra que recorrió 10.5 km de la superficie lunar en 10 meses. Los ingenieros soviéticos controlaban el rover desde una sala de control en Simferopol, Crimea, con un retraso de comunicación de 2.5 segundos (el tiempo que tarda la señal de radio en viajar de la Tierra a la Luna y regresar). Este retraso hizo que los controladores debieran planificar cada movimiento con cuidado, porque las órdenes llegaban 2.5 segundos tarde.',
    'Hoy, la robótica es un campo que combina **mecánica, electrónica, informática, inteligencia artificial y biología**. Los robots modernos pueden hacer cirugías (el robot **Da Vinci Surgical System** realiza más de 1 millón de operaciones al año), limpiar océanos de plástico, explorar Marte (el rover **Perseverance** lleva operando desde 2021), desactivar bombas, inspeccionar gasoductos submarinos, y fabricar chips de computadora con precisión de nanómetros. El mercado global de robótica superó los **62 mil millones de dólares** en 2023 y sigue creciendo. Se estima que para 2035 habrá más de **1 millón de robots quirúrgicos**, **20 millones de robots de servicio** y decenas de millones de robots industriales en el mundo.',
  ]},
  { id: 'robots_historia_s3', title: 'Robots que Exploran el Sistema Solar', image: '/assets/robots/historia.png', text: [
    'Los robots espaciales son los exploradores más valientes de la historia humana: van a lugares donde los humanos no pueden sobrevivir. La temperatura en la superficie de Marte varía entre -125°C en invierno y +20°C en verano, la presión atmosférica es el 1% de la terrestre (como estar a 35 km de altitud en la Tierra), y la radiación cósmica es 50 veces mayor que en la superficie terrestre. Ningún ser humano podría sobrevivir sin un elaborado sistema de soporte vital. Los robots, en cambio, no necesitan comer, respirar ni protegerse de la radiación de la misma manera. Un robot bien diseñado puede operar en estas condiciones durante años.',
    'Los **rovers de Marte** son el ejemplo más conocido de robots exploradores. El **Sojourner** (1997) fue el primero, pesando apenas 11 kg y del tamaño de un microondas. El **Spirit** y el **Opportunity** (2004) pesaban 180 kg cada uno y recorrieron 7.7 km y 45 km respectivamente. El **Curiosity** (desde 2012) pesa 899 kg y sigue operando hoy, habiendo recorrido más de 30 km. El **Perseverance** (desde 2021) pesa 1,025 kg y lleva el helicóptero **Ingenuity**, el primer vehículo con alas en volar en otro planeta. Cada generación de rover es más grande, más capaz y más autónomo que la anterior.',
    'Los robots espaciales no solo van a Marte. La **sonda Cassini** de NASA exploró Saturno y sus lunas desde 2004 hasta 2017, tomando más de 450,000 fotografías y descubriendo géiseres de agua en la luna Encélado, un océano bajo el hielo de Titán, y tormentas en Saturno mayores que la Tierra entera. La sonda **New Horizons** (lanzada en 2006) visitó Plutón en 2015 y reveló que tiene montañas de hielo de 3,500 metros de altura y un "corazón" de nitrógeno congelado. La sonda **Voyager 1** (lanzada en 1977) sigue funcionando hoy, a más de 23,000 millones de kilómetros de la Tierra, siendo el objeto hecho por humanos más lejano del sistema solar.',
    'El futuro de la robótica espacial incluye robots cada vez más autónomos. La **inteligencia artificial** permite a los rovers modernos tomar decisiones sin esperar instrucciones de la Tierra. El Perseverance tiene un sistema de navegación autónoma que le permite planificar rutas de hasta 20 metros sin ayuda humana, importante porque el retraso de comunicación con Marte varía entre 3 y 22 minutos (dependiendo de la posición relativa de los planetas). Los robots del futuro podrán construir bases en la Luna o en Marte antes de que lleguen los astronautas humanos, preparando el terreno para la colonización humana. La NASA planea usar robots para **imprimir en 3D** estructuras usando el regolito (polvo) lunar.',
    'El campo de la **robótica bioinspirada** (robots diseñados imitando a los animales) está produciendo robots que pueden moverse por terrenos imposibles para los rovers con ruedas. El robot **RHex** de Boston Dynamics puede trepar escaleras, cruzar rocas y nadar. El robot **RoboBee** de Harvard, del tamaño de una moneda, puede volar y posarse en superficies como una abeja. La NASA está estudiando robots del tamaño de arañas para explorar las cuevas de Marte (donde podría haber vida microbiana protegida de la radiación). Y el robot **LEMUR** (Limbed Excursion Mechanical Utility Robot) puede escalar paredes verticales usando ventosas, para inspeccionar la parte exterior de la ISS. El futuro de la robótica es tan diverso y creativo como la naturaleza que lo inspira.',
  ]},
],

robots_sojourner: [
  { id: 'sojourner_s1', title: 'El Primer Rover de Marte', image: '/assets/robots/sojourner.png', text: [
    'El **4 de julio de 1997**, el día de la independencia de los Estados Unidos, una nave espacial llamada **Mars Pathfinder** aterrizó en Marte usando un método nunca antes probado: **airbags inflables**. En lugar de usar cohetes de frenado para descender suavemente (como los rovers anteriores), la Pathfinder dejó caer su cápsula desde 300 metros de altura, la rodeó de airbags esféricos inflados como una pelota gigante, y la dejó rebotar en la superficie marciana hasta 15 veces antes de detenerse. Los ingenieros de la NASA calcularon que los airbags debían absorber una fuerza de impacto de hasta 35G (35 veces la gravedad terrestre) y resistir temperaturas de -80°C. Funcionó perfectamente.',
    'Dentro de la cápsula Pathfinder viajaba un pequeño rover llamado **Sojourner**, en honor a **Sojourner Truth**, la abolicionista y activista de los derechos de las mujeres afroamericana del siglo XIX. El nombre fue elegido por una estudiante de 12 años, Valerie Ambroise, ganadora de un concurso nacional de redacción de la NASA. Sojourner pesaba **10.6 kg**, aproximadamente como una mochila escolar llena de libros. Medía 65 cm de largo, 48 cm de ancho y 30 cm de alto. Tenía 6 ruedas de aluminio con aletas de titanio que le daban tracción en el polvo marciano, y cada rueda podía moverse independientemente para adaptarse al terreno irregular.',
    'Sojourner tenía tres cámaras (dos en blanco y negro al frente y una en color al lado), un **espectrómetro de rayos X** (llamado APXS, Alpha Proton X-Ray Spectrometer) en la parte trasera para analizar la composición química de las rocas, y sensores de temperatura y presión atmosférica. La energía provenía de un panel solar de 0.22 m² que generaba apenas **16 vatios** (suficiente para encender una bombilla pequeña). Con esa energía mínima, Sojourner operó durante **83 días**, mucho más que los 7 días originalmente planificados. Durante ese tiempo, analizó **16 rocas** y 11 manchas de polvo, tomó 550 fotografías, y recorrió un total de **100 metros** de la superficie marciana.',
    'Sojourner no podía navegar de forma completamente autónoma: tenía que recibir comandos de la Tierra. Pero con un retraso de comunicación de entre 10 y 20 minutos (el tiempo que la señal tarda en viajar de Marte a la Tierra y regresar), los controladores no podían dirigirlo en tiempo real como un coche teledirigido. En su lugar, los ingenieros planificaban la ruta del día anterior: identificaban las rocas de interés en las fotografías recibidas, calculaban la secuencia de movimientos para llegar hasta ellas, y enviaban esas instrucciones como un "plan de misión" que el rover ejecutaba de forma autónoma. Si encontraba un obstáculo no previsto, Sojourner se detenía y esperaba nuevas instrucciones.',
    'Los **resultados científicos** del Sojourner fueron significativos. El espectrómetro APXS reveló que las rocas marcianas analizadas eran de composición similar al **andesita**, una roca volcánica común en la Tierra que se forma en zonas de subducción de placas tectónicas. Esto sugería que Marte había tenido actividad tectónica en el pasado. Los análisis del polvo mostraron altos contenidos de **azufre y cloro**, consistentes con interacción entre el agua y las rocas en tiempos remotos. Y las mediciones atmosféricas mostraron variaciones de temperatura de hasta 40°C a lo largo del día marciano (un "sol" marciano dura 24 horas y 37 minutos), con tormentas de polvo que elevaban la temperatura varios grados en minutos.',
  ]},
  { id: 'sojourner_s2', title: 'Las Lecciones de Sojourner para la Ingeniería', image: '/assets/robots/sojourner.png', text: [
    'El diseño del Sojourner incorporó una innovación de ingeniería llamada **"Rocker-Bogie"** que revolucionó el diseño de rovers. Un rover con 4 ruedas en un terreno irregular puede quedar volcado si una rueda cae en un hueco. El sistema Rocker-Bogie distribuye el peso del rover entre 6 ruedas usando un mecanismo de palancas articuladas que mantiene el chasis nivelado aunque dos ruedas estén en posiciones completamente diferentes. La prueba de diseño exigía que el rover pudiera atravesar obstáculos de hasta 20 cm de altura y inclinarse hasta 45 grados sin volcarse. El mismo sistema Rocker-Bogie, mejorado, fue usado en los rovers Spirit, Opportunity, Curiosity y Perseverance. Es uno de los diseños de ingeniería más exitosos de la historia espacial.',
    'El **software de navegación** del Sojourner fue pionero en la robótica espacial. Usaba un sistema de detección de obstáculos basado en los datos de las cámaras estereoscópicas: comparando las mismas imágenes tomadas desde dos cámaras separadas por una distancia conocida, el software podía calcular la distancia a los objetos en el campo visual (el mismo principio que usa el cerebro humano para la visión en profundidad con dos ojos). Si detectaba un obstáculo a menos de 50 cm, se detenía y esperaba instrucciones. Esto era revolucionario: los rovers anteriores (los Lunokhod soviéticos) requerían que los operadores vieran cada obstáculo manualmente. Sojourner fue el primero en poder "ver" por sí mismo.',
    'La misión Sojourner/Pathfinder costó **280 millones de dólares**, una fracción del costo de misiones anteriores como la Viking (que costó 3,500 millones en dólares de hoy). El director de la misión, **Tony Spear**, aplicó la filosofía de **"Faster, Better, Cheaper"** (más rápido, mejor, más barato) que la NASA promovió en los años 90: en lugar de construir una nave perfecta con todos los equipos posibles, diseñar una nave más pequeña y económica que hiciera los experimentos más importantes. Aunque esta filosofía tuvo algunos fracasos (como las sondas Mars Climate Orbiter y Mars Polar Lander, perdidas en 1999), la misión Pathfinder demostró que era posible explorar Marte de forma más económica y frecuente.',
    'El éxito mediático de la misión Pathfinder fue extraordinario. El sitio web de la NASA que transmitía las imágenes en tiempo real recibió **47 millones de visitas** en los primeros tres días, un récord absoluto para Internet en 1997 (cuando la mayoría de las personas se conectaban con módems de 56 kbps). Las imágenes de Sojourner explorando la superficie marciana aparecieron en la portada de todos los periódicos del mundo. Los nombres que los ingenieros pusieron a las rocas (Barnacle Bill, Yogi, el Cupcake) se volvieron familiares para millones de personas. La misión popularizó la exploración robótica de Marte de una manera que ninguna misión anterior había logrado.',
    'Sojourner transmitió su **último mensaje** el 27 de septiembre de 1997. Se cree que el módulo base (la estación Pathfinder) perdió potencia eléctrica primero, dejando al rover sin forma de enviar datos. Los ingenieros enviaron comandos de recuperación durante meses, sin respuesta. Hoy, tanto el módulo Pathfinder como el rover Sojourner están en la superficie de Marte, a unos 12 metros de distancia uno del otro, en la región llamada **Ares Vallis** (el Valle de Ares, dios griego de la guerra). Son monumentos silenciosos de la primera exploración exitosa con rover de Marte. En 2012, cuando el rover Curiosity aterrizó exitosamente usando un nuevo sistema de "grúa aérea", los ingenieros de la NASA aplaudieron, muchos con lágrimas en los ojos, recordando las lecciones de Sojourner que hicieron posible ese momento.',
  ]},
  { id: 'sojourner_s3', title: 'El Sistema Solar Explorado por Robots', image: '/assets/robots/sojourner.png', text: [
    'La exploración robótica del sistema solar es uno de los mayores logros de la humanidad. En los 60+ años desde que los primeros satélites salieron al espacio, hemos enviado robots a explorar la Luna, Marte, Venus, Mercurio, Júpiter, Saturno, Urano, Neptuno, Plutón, varios asteroides, y dos cometas. El número total de misiones espaciales exitosas supera las **250**. Estos robots han tomado millones de fotografías, analizado cientos de miles de muestras de polvo y roca, medido temperaturas, presiones y campos magnéticos, y enviado de vuelta a la Tierra petabytes de datos científicos que han transformado nuestra comprensión del sistema solar.',
    'El rover **Opportunity** de la NASA aterrizó en Marte en enero de 2004 y se planeó que operara durante **90 días**. Funcionó durante **5,352 días** (casi 15 años), recorriendo 45.16 km y tomando más de 200,000 fotografías. Encontró evidencia concluyente de que la región donde aterrizó, la Bahía de Eagle, estuvo cubierta por agua salada superficial hace aproximadamente 3,000 millones de años. El análisis de rocas llamadas "esferas de hematita" (bautizadas "arándanos" por los científicos) mostró que se formaron en presencia de agua líquida. Esta fue una de las pruebas más directas de que Marte tuvo agua superficial en el pasado, un prerrequisito para la vida tal como la conocemos.',
    'El rover **Curiosity**, del tamaño de un coche, aterrizó en el **cráter Gale** de Marte el 5 de agosto de 2012 usando el innovador sistema de "grúa aérea": una plataforma de propulsión descendió hasta 20 metros sobre la superficie y bajó el rover con cables antes de alejarse y estrellarse. Curiosity lleva el **instrumento SAM** (Sample Analysis at Mars), un laboratorio de química completo en miniatura que puede analizar la composición molecular de rocas y suelos. En 2018, Curiosity encontró moléculas orgánicas complejas (tiofenos, bencenos, toluenos) en rocas de 3,000 millones de años, la evidencia más directa hasta ese momento de que en Marte hubo condiciones compatibles con la vida.',
    'La misión **Perseverance** (aterrizó el 18 de febrero de 2021) representa la vanguardia de la exploración robótica de Marte. Lleva 7 instrumentos científicos, incluyendo el espectrómetro **SHERLOC** (que busca compuestos orgánicos con luz ultravioleta), el instrumento **MOXIE** (que convierte el CO₂ de la atmósfera marciana en oxígeno, demostrando que futuras misiones tripuladas podrían producir oxígeno en Marte), y el helicóptero **Ingenuity**. También recoge muestras de roca en tubos sellados que serán recogidas por una misión futura (la **Mars Sample Return**) para traerlas de vuelta a la Tierra, donde podrán ser analizadas con instrumentos mucho más potentes que los que caben en un rover.',
    'El futuro de la exploración robótica del sistema solar es apasionante. La misión **Europa Clipper** de la NASA (lanzada en octubre de 2024) va a orbitar Europa, la luna de Júpiter que tiene un océano de agua líquida bajo su corteza de hielo. La sonda **Dragonfly** (planificada para 2034) aterrizará en Titán, la luna de Saturno que tiene lagos de metano líquido y una atmósfera densa. Y la misión **Artemis** enviará astronautas a la Luna para trabajar junto a robots: los humanos harán las tareas que requieren adaptabilidad y creatividad, los robots harán el trabajo peligroso, repetitivo o que requiere estar en lugares donde los humanos no pueden ir. En el futuro de la exploración espacial, humanos y robots no son alternativos sino complementarios.',
  ]},
],

robots_ingenuity: [
  { id: 'ingenuity_s1', title: 'Ingenuity: El Primer Vuelo en Otro Planeta', image: '/assets/robots/ingenuity.png', text: [
    'El **19 de abril de 2021**, a las 3:34 AM hora del este de los Estados Unidos, ocurrió uno de los momentos más extraordinarios de la historia de la exploración espacial: un helicóptero llamado **Ingenuity** despegó de la superficie de Marte y voló durante **39.1 segundos** a una altitud de **3 metros**. Fue el **primer vuelo motorizado y controlado** de un vehículo más pesado que el aire en la historia de otro planeta. El equivalente en importancia histórica al **primer vuelo de los hermanos Wright** en Kitty Hawk, Carolina del Norte, el 17 de diciembre de 1903, cuando el Flyer I voló durante 12 segundos a una altitud de 3 metros. La NASA lo reconoció explícitamente: un trozo de tela del ala del Flyer I de los Wright viajó a bordo de Ingenuity como homenaje.',
    'Ingenuity llegó a Marte pegado a la barriga del rover **Perseverance**. Una vez que Perseverance encontró un lugar llano adecuado (un área de 10 m × 10 m llamada el "aeródromo de Wright Brothers"), se bajó el helicóptero a la superficie. Ingenuity pesaba **1.8 kg** (como una botella de agua llena y media) y tenía dos pares de hélices contrarrotantes de **1.2 metros** de diámetro. Las hélices giraban a **2,537 revoluciones por minuto** (rpm), casi 5 veces más rápido que un helicóptero terrestre, porque la atmósfera de Marte es 99% menos densa que la de la Tierra. Para volar en Marte, un helicóptero necesita hélices mucho más grandes o que giren mucho más rápido que uno terrestre equivalente.',
    'El desafío de diseñar Ingenuity fue enorme. El equipo de ingenieros de la NASA en el **Jet Propulsion Laboratory** (JPL) en Pasadena, California, tardó **6 años** en desarrollarlo. El problema central era la densidad del aire marciano: en la superficie de Marte, el aire tiene la misma densidad que el aire terrestre a **34 km de altitud** (la estratosfera alta, donde ningún helicóptero terrestre puede volar). Para generar suficiente sustentación, las hélices de Ingenuity debían ser excepcionalmente livianas (cada hoja de hélice pesa 35 gramos, menos que un huevo) y girar muy rápido. Para probar el diseño, los ingenieros del JPL construyeron una **cámara de vacío** en la que simularon la atmósfera marciana en la Tierra, extrayendo el 99% del aire.',
    'Los **sistemas de control** de Ingenuity también fueron un desafío extraordinario. A diferencia de un drone terrestre, que recibe señales de radio en tiempo real desde un control remoto, Ingenuity no podía ser controlado en tiempo real desde la Tierra porque el retraso de comunicación con Marte es de entre 3 y 22 minutos. Cada vuelo tenía que planificarse completamente en la Tierra (trayectoria, altitud, velocidad, duración), enviarse como un programa de instrucciones a Ingenuity, y el helicóptero lo ejecutaba de forma completamente autónoma. Si algo salía mal durante el vuelo, el helicóptero tenía que resolverlo solo usando sus propios sensores: un giroscopio, un acelerómetro, una cámara de navegación que mira hacia abajo y fotografía el suelo para estimar su propia posición.',
    'El helicóptero Ingenuity estaba diseñado originalmente para **5 vuelos de demostración** durante 30 días. Pero siguió volando, vuelo tras vuelo. Para febrero de 2024, cuando tuvo un aterrizaje que dañó una de sus aspas de rotor y terminó su misión de vuelo, Ingenuity había completado **72 vuelos**, había recorrido **17 km** de distancia horizontal acumulada, había alcanzado velocidades de hasta **22.6 km/h** y altitudes de hasta **24 metros**, y había volado durante un total de **128 minutos** sobre la superficie de Marte. Pasó de ser un experimento tecnológico a ser un instrumento de exploración activo que ayudó al Perseverance a planificar rutas y fotografiar terrenos inaccesibles al rover.',
  ]},
  { id: 'ingenuity_s2', title: 'La Ciencia del Vuelo en Marte', image: '/assets/robots/ingenuity.png', text: [
    'El vuelo de Ingenuity en Marte demostró algo que los ingenieros calculaban pero nadie había confirmado experimentalmente: que es posible generar **sustentación aerodinámica** en la atmósfera marciana. La atmósfera de Marte es dióxido de carbono (CO₂) en un 95%, con pequeñas cantidades de nitrógeno y argón. Su presión media en la superficie es de **610 pascales**, comparada con 101,325 pascales en la Tierra (la presión atmosférica estándar). Esta baja densidad hace que las mismas ecuaciones de la aerodinámica funcionen, pero con números muy diferentes: las fuerzas de sustentación son mucho menores, y las velocidades necesarias para generar suficiente elevación son mucho mayores.',
    'La **Ley de Bernoulli** y las ecuaciones de **Navier-Stokes** son las bases matemáticas del vuelo. La sustentación se genera porque el ala (o la hoja de hélice) tiene una forma que hace que el aire se mueva más rápido por arriba que por abajo, creando una región de menor presión arriba y mayor presión abajo. Esta diferencia de presión empuja el ala hacia arriba. En Marte, con mucha menos densidad de aire, para generar la misma sustentación que en la Tierra se necesita que las hélices sean más grandes, giren más rápido, o ambas cosas. Ingenuity eligió ambas: hélices de 1.2 m de diámetro (muy grandes para su peso) girando a 2,537 rpm (mucho más rápido que un helicóptero terrestre del mismo tamaño).',
    'Los datos de vuelo de Ingenuity han permitido a los científicos refinar los **modelos de la atmósfera marciana**. Las condiciones atmosféricas de Marte varían significativamente con las estaciones y con la hora del día: al mediodía marciano, la convección térmica (el calentamiento del aire por el suelo caliente) crea turbulencias que dificultan el vuelo. En los primeros vuelos, Ingenuity voló a primera hora de la mañana marciana para evitar la turbulencia de mediodía. Los datos de presión, temperatura y velocidad del viento que Ingenuity registró durante sus vuelos son los datos meteorológicos más detallados jamás obtenidos a altura de vuelo en la atmósfera de Marte.',
    'El éxito de Ingenuity abrió la puerta a una nueva forma de explorar Marte: la **exploración aérea**. Un helicóptero puede ir a lugares donde un rover con ruedas no puede llegar: cráteres con paredes empinadas, zonas de terreno quebrado, áreas cubiertas de rocas grandes. Puede fotografiar desde el aire con mucho mayor campo visual que las cámaras del rover. Y puede moverse mucho más rápido: Ingenuity a veces completaba en minutos recorridos que al Perseverance le llevaban días. La NASA ya planea misiones que aprovechen estas ventajas: el **Mars Science Helicopter**, un sucesor de Ingenuity que pesaría unos 30 kg y podría llevar instrumentos científicos mientras vuela.',
    'El impacto de Ingenuity en la ingeniería aeroespacial es comparable al impacto de los primeros vuelos de los Wright. Antes de 1903, el vuelo motorizado controlado era considerado imposible por muchos científicos. Después del 17 de diciembre de 1903, todos los cálculos de qué era posible tuvieron que reescribirse. Antes del 19 de abril de 2021, ningún vehículo con alas había volado jamás en otro planeta. Ahora sabemos exactamente cómo hacerlo. Las futuras misiones a Titán (la densa luna de Saturno) o Venus (cuya atmósfera densa facilita el vuelo) ya se están diseñando con vehículos aéreos como parte central. Ingenuity no fue solo un logro: fue el comienzo de una nueva era de la exploración espacial aérea.',
  ]},
  { id: 'ingenuity_s3', title: 'El Futuro de los Robots Voladores en el Espacio', image: '/assets/robots/ingenuity.png', text: [
    'El éxito de Ingenuity demostró que los **vehículos aéreos** son una herramienta poderosa para la exploración planetaria. La misión **Dragonfly** de la NASA, aprobada en 2019 y planificada para aterrizar en Titán (la luna de Saturno) en 2034, es un helicóptero del tamaño de un coche (450 kg) que explorará docenas de lugares en la superficie de Titán en vuelos de decenas de kilómetros. Titán tiene una atmósfera 4 veces más densa que la de la Tierra, lo que hace el vuelo mucho más fácil que en Marte, y temperaturas de -179°C. Dragonfly buscará compuestos orgánicos complejos en la superficie, porque Titán tiene lagos de metano líquido y química orgánica que podría darnos pistas sobre el origen de la vida.',
    'Para la Luna, la NASA y empresas privadas estudian el uso de **cuadricópteros** (drones de 4 hélices) para explorar cráteres de impacto que podrían contener hielo de agua en sus zonas de sombra permanente. Estos cráteres, en los polos lunares, nunca han sido iluminados por el sol desde hace miles de millones de años. Las temperaturas en su interior pueden bajar a -250°C, suficiente para preservar hielo de agua, dióxido de carbono y otros compuestos volátiles. Un drone podría entrar en estos cráteres, tomar muestras y regresar, una tarea imposible para un rover (que necesita energía solar para funcionar).',
    'La **robótica de enjambre** es otra frontera de la exploración espacial. En lugar de enviar un único robot grande y costoso, se envían docenas o cientos de robots pequeños y económicos que trabajan juntos. Si uno falla, los demás continúan. Si encuentran algo interesante, todos se concentran en investigarlo. El proyecto **Swarmathon** de la NASA ha probado enjambres de robots pequeños en la Tierra con algoritmos de búsqueda inspirados en las hormigas. A largo plazo, enjambres de pequeños robots podrían explorar simultáneamente cientos de kilómetros cuadrados de la superficie de Marte, buscando señales de vida microbiana o recursos minerales para futuras colonias humanas.',
    'La **inteligencia artificial** está transformando la autonomía de los robots espaciales. Los rovers actuales toman decisiones simples (evitar obstáculos, detenerse si algo sale mal). Los robots futuros necesitarán tomar decisiones complejas: identificar muestras de roca interesantes usando modelos de aprendizaje automático entrenados con miles de fotos de minerales, decidir qué vale la pena fotografiar y qué ignorar, planificar rutas de semanas sin ayuda humana, e incluso auto-repararse si un componente falla. El rover **AEGIS** (Autonomous Exploration for Gathering Increased Science) ya implementado en el Curiosity puede seleccionar automáticamente rocas interesantes para fotografiar con el láser ChemCam, sin instrucciones humanas.',
    'El sueño final de la robótica espacial es la **terraformación autónoma**: robots que durante décadas o siglos modifiquen un planeta para hacerlo habitable para los humanos. Esto es ciencia ficción hoy, pero los primeros pasos ya se están dando: el instrumento **MOXIE** del Perseverance ha demostrado que se puede producir oxígeno en Marte. Robots futuros podrían producir oxígeno a escala industrial, imprimir estructuras habitables con materiales marcianos, plantar organismos modificados genéticamente que produzcan oxígeno y fijen nitrógeno, y preparar el camino para la llegada de los humanos. El legado de Ingenuity, el pequeño helicóptero que voló por primera vez en otro planeta, es el primer capítulo de esta historia que apenas comienza.',
  ]},
],

robots_futuras: [
  { id: 'robots_futuras_s1', title: 'Los Robots del Mañana', image: '/assets/robots/futuras.png', text: [
    'Los robots del futuro cercano serán radicalmente diferentes de los que conocemos hoy. El campo de la **robótica blanda** (soft robotics) crea robots sin partes rígidas, usando materiales flexibles como silicona, geles polimerizados y tejidos artificiales que imitan la musculatura animal. Un robot blando puede deslizarse por espacios estrechos, agarrar objetos frágiles sin romperlos, e interactuar con humanos sin riesgo de lesiones. El **Octobot** de Harvard (2016) fue el primer robot completamente blando y autónomo, inspirado en los pulpos, capaz de moverse usando solo reacciones químicas internas sin electrónica ni cables.',
    'La **inteligencia artificial general** (AGI), si se logra desarrollar, daría a los robots una capacidad de razonamiento comparable a la humana: la capacidad de aprender cualquier tarea, adaptarse a situaciones completamente nuevas, y resolver problemas que nunca han visto antes. Hoy, los robots más avanzados usan **inteligencia artificial estrecha**: son muy buenos en tareas específicas (jugar al ajedrez, reconocer caras, soldar piezas) pero no pueden hacer nada fuera de su dominio entrenado. Un robot que cocina no puede barrer, aunque barrer sea "más fácil" para un humano. La AGI eliminaría esta limitación, creando robots verdaderamente versátiles.',
    'Los **robots humanoides** son uno de los campos más activos de la investigación robótica. El robot **Atlas** de Boston Dynamics puede hacer parkour, saltar sobre obstáculos, dar volteretas hacia atrás y manipular objetos con sus manos. El robot **Digit** de Agility Robotics trabaja en almacenes de Amazon, moviendo cajas de forma autónoma. Tesla está desarrollando el robot **Optimus**, diseñado para hacer las tareas domésticas más comunes: doblar ropa, fregar platos, acarrear objetos. El objetivo a largo plazo es un robot humanoide que pueda hacer cualquier trabajo físico que haga un humano, en cualquier entorno diseñado para humanos (sin necesidad de adaptar edificios o herramientas).',
    'La **nanotecnología** podría llevar los robots a escalas inimaginablemente pequeñas: los **nanobots** son robots hipotéticos del tamaño de una molécula (1-100 nanómetros) que podrían circular por el torrente sanguíneo y realizar cirugías en el interior del cuerpo, destruir células cancerosas individualmente, reparar tejidos dañados célula por célula, o limpiar arterias bloqueadas. Aunque los nanobots médicos completos aún son ciencia ficción, ya existen **nanopartículas médicas** funcionales: nanocápsulas de medicamentos que liberan su carga solo cuando detectan células cancerosas, y nanopartículas de oro que absorben la luz láser y calientan los tumores selectivamente.',
    'El **exoesqueleto robótico** es una tecnología que ya existe y está cambiando vidas. Un exoesqueleto es un robot que se lleva puesto como una armadura: amplifica la fuerza muscular del usuario o le permite moverse aunque sus músculos no funcionen. El **EksoGT** permite a personas con parálisis completa de las piernas caminar de nuevo. El **Sarcos Guardian XO** permite a un trabajador industrial llevar cargas de 90 kg sin esfuerzo, reduciendo lesiones laborales. Para los astronautas, los exoesqueletos podrían permitir trabajar en superficies con alta gravedad (como Marte, con 0.38G) sin sufrir el desgaste muscular que la gravedad reducida causa durante meses de viaje espacial.',
  ]},
  { id: 'robots_futuras_s2', title: 'Robots y Humanos: Colaboración, no Competencia', image: '/assets/robots/futuras.png', text: [
    'Una de las preguntas más importantes del siglo XXI es: ¿qué trabajos harán los robots y qué trabajos seguirán haciendo los humanos? La historia de la automatización industrial muestra un patrón: los robots reemplazan tareas específicas (no trabajos enteros), creando nuevos trabajos que antes no existían. La **Revolución Industrial** del siglo XIX eliminó millones de trabajos de artesanos manuales, pero creó muchos más trabajos en fábricas, ferrocarriles, y en los servicios que soportan una economía industrial. La **revolución digital** de los años 1980-2000 eliminó cientos de miles de trabajos de mecanógrafos, operadores de centralitas y contables manuales, pero creó millones de empleos en programación, diseño web, marketing digital y soporte técnico.',
    'Los robots son excepcionalmente buenos en tareas **repetitivas, de precisión, peligrosas o que requieren gran fuerza física**. Sueldan coches en cadenas de montaje, empacan productos en almacenes, inspeccionan oleoductos submarinos, desactivan explosivos, y realizan cirugías con precisión milimétrica. Los humanos son excepcionalmente buenos en tareas que requieren **creatividad, empatía, juicio en situaciones ambiguas y habilidades sociales complejas**. Un robot puede diagnosticar una enfermedad a partir de una radiografía mejor que cualquier médico (en estudios específicos de diagnóstico por imagen, los sistemas de IA superan a los radiólogos humanos). Pero un robot no puede explicarle a un paciente su diagnóstico con compasión, escuchar sus miedos y adaptar el mensaje a su personalidad específica.',
    'La **colaboración humano-robot** (HRC, Human-Robot Collaboration) es el modelo del futuro para muchos entornos industriales. En lugar de tener zonas separadas donde los robots trabajan solos (como en las fábricas de automóviles tradicionales), los robots "colaborativos" (llamados **cobots**) trabajan codo a codo con personas, cada uno haciendo lo que hace mejor. Un cobot puede sostener una pieza pesada mientras un técnico humano la atornilla; puede traer herramientas al trabajador sin que este tenga que moverse; puede detectar cuando un humano está cansado (por la disminución de precisión en sus movimientos) y ajustar su ritmo. Las empresas que han implementado cobots reportan aumentos de productividad del 30-50% con **reducción** de lesiones laborales.',
    'Los **robots cuidadores** son una de las aplicaciones más prometedoras y éticamente complejas de la robótica moderna. En Japón, donde el 28% de la población tiene más de 65 años y hay escasez de trabajadores jóvenes, los robots cuidadores están siendo probados activamente. El robot **PARO** es una foca robótica blanda que responde a las caricias y habla, diseñada para acompañar a personas con demencia. Los estudios clínicos muestran que los pacientes que interactúan con PARO experimentan reducción del estrés y la agitación. El robot **ROBEAR** puede levantar a personas mayores de la cama o del baño, una tarea físicamente extenuante que causa lesiones en la espalda a millares de enfermeros cada año.',
    'La **ética de la robótica** es un campo en rápida expansión. Si un coche autónomo tiene que elegir entre atropellar a un peatón o poner en peligro a sus pasajeros, ¿qué debe hacer? ¿Quién es responsable legalmente cuando un robot médico comete un error? ¿Tienen los robots compañeros de trabajo el "derecho" a cierto trato por parte de los humanos? ¿Deberían los robots de combate (drones armados autónomos) poder tomar la decisión de disparar sin supervisión humana? Estas preguntas no tienen respuestas técnicas: son preguntas filosóficas, legales y políticas que las sociedades deben resolver colectivamente. El **Parlamento Europeo** adoptó en 2023 las primeras regulaciones legales del mundo sobre sistemas de inteligencia artificial, incluyendo restricciones sobre robots autónomos en contextos de seguridad.',
  ]},
  { id: 'robots_futuras_s3', title: 'Construye tu Propia Historia con la Robótica', image: '/assets/robots/futuras.png', text: [
    'Si te apasiona la robótica, hay excelentes caminos para empezar **hoy mismo**, independientemente de tu edad. Las plataformas de robótica educativa como **LEGO Mindstorms**, **VEX Robotics** y **Arduino** permiten construir y programar robots reales desde los 10 años. Con Arduino (un microcontrolador de bajo costo, unos 10 euros) y componentes electrónicos básicos (motores, sensores, LEDs), puedes construir un robot que sigue una línea, detecta obstáculos, o responde a comandos de voz. Miles de proyectos con instrucciones paso a paso están disponibles gratuitamente en internet. El primer robot que construyas probablemente no ganará ningún concurso, pero aprenderás más de ese fracaso que de cualquier libro.',
    'Las **competiciones de robótica estudiantil** son una de las mejores formas de aprender. La **First Robotics Competition** (FRC), para estudiantes de secundaria, involucra a 100,000 estudiantes de 100 países en la construcción de robots de 50 kg que compiten en tareas anuales específicas. La **RoboCup** es una competición internacional donde robots autónomos juegan al fútbol (el objetivo declarado de RoboCup es que para 2050 un equipo de robots autónomos pueda ganar al campeón del mundo humano de fútbol). La **NASA Swarmathon** involucra a equipos universitarios en el diseño de algoritmos de enjambre para robots. Participar en estas competiciones es una de las formas más directas de entrar en el mundo de la ingeniería robótica profesional.',
    'Las **carreras en robótica** son enormemente diversas. Puedes ser **ingeniero mecánico** y diseñar los sistemas físicos de un robot (brazos, piernas, ruedas, articulaciones). Puedes ser **ingeniero eléctrico o electrónico** y diseñar los sistemas de energía, sensores y actuadores. Puedes ser **programador** y escribir el software de control y los algoritmos de inteligencia artificial. Puedes ser **neurocientífico** y estudiar cómo funciona el cerebro animal para inspirar nuevos diseños robóticos. Puedes ser **filósofo ético** y ayudar a las empresas y gobiernos a navegar las implicaciones morales de la robótica. O puedes ser **educador** y enseñar a la próxima generación de ingenieros robóticos.',
    'Algunos de los **problemas más importantes** del siglo XXI que la robótica puede ayudar a resolver son: el **cambio climático** (robots que recolectan energía solar en el espacio o plantan árboles a escala industrial), la **seguridad alimentaria** (robots agricultores que cultivan y cosechan alimentos con la eficiencia de una fábrica), la **exploración del océano** (el 80% de los océanos de la Tierra no ha sido explorado nunca, y los robots submarinos son la mejor herramienta para hacerlo), la **medicina personalizada** (robots de laboratorio que analizan el genoma de cada paciente para diseñar tratamientos individualizados), y la **exploración espacial** (robots que preparan el camino para la humanidad en la Luna, Marte y más allá).',
    'El mensaje más importante sobre el futuro de la robótica es este: los robots **son herramientas**, no seres autónomos con voluntad propia (al menos por ahora). Son los humanos quienes los diseñan, los programan, los usan y deciden para qué propósitos. Cada robot que existe es el resultado de las decisiones de docenas o cientos de personas: ingenieros, científicos, gerentes, políticos. El futuro de la robótica no está determinado por ninguna ley inevitable: está determinado por las **decisiones que los humanos tomamos**. Eso significa que tú, como ciudadano del siglo XXI, participarás en decidir qué robots se construyen, qué pueden hacer y cuáles son sus límites. Estudiar robótica no es solo aprender a construir máquinas: es aprender a pensar críticamente sobre el futuro que queremos crear.',
  ]},
],

};

for (const [moduleId, sections] of Object.entries(CONTENT)) {
  replaceModule(moduleId, sections);
}
console.log('\nAll robots modules rebuilt!');
