const fs = require('fs');
const path = require('path');
const COURSE_DATA_PATH = path.join(__dirname, '../lib/courseData.js');

function findSectionsRange(text, moduleId) {
  const s1 = '"id": "' + moduleId + '"';
  const s2 = '"id":"' + moduleId + '"';
  let idIdx = text.indexOf(s1);
  if (idIdx < 0) idIdx = text.indexOf(s2);
  if (idIdx < 0) return null;
  const ceIdx = text.indexOf('"contentEs"', idIdx);
  if (ceIdx < 0 || ceIdx - idIdx > 5000) return null;
  const sectIdx = text.indexOf('"sections"', ceIdx);
  if (sectIdx < 0) return null;
  const arrStart = text.indexOf('[', sectIdx);
  if (arrStart < 0) return null;
  let depth = 0, arrEnd = arrStart;
  for (let i = arrStart; i < text.length; i++) {
    if (text[i] === '[') depth++;
    else if (text[i] === ']') { depth--; if (depth === 0) { arrEnd = i; break; } }
  }
  return { arrStart, arrEnd };
}

function replaceModule(moduleId, newSections) {
  let text = fs.readFileSync(COURSE_DATA_PATH, 'utf8');
  const range = findSectionsRange(text, moduleId);
  if (!range) { console.error('NOT FOUND: ' + moduleId); return; }
  const { arrStart, arrEnd } = range;
  const newArr = JSON.stringify(newSections, null, 6);
  text = text.substring(0, arrStart) + newArr + text.substring(arrEnd + 1);
  fs.writeFileSync(COURSE_DATA_PATH, text, 'utf8');
  const totalParas = newSections.reduce((s, x) => s + x.text.length, 0);
  console.log('OK: ' + moduleId + ' (' + totalParas + ' paras)');
}

const CONTENT = {

pioneros_svetlana: [
  { id: 'svetlana_s1', title: 'Svetlana Savitskaya: La Segunda Mujer en el Espacio', image: '/assets/pioneros/svetlana.png', text: [
    '**Svetlana Yevgenyevna Savitskaya** nació el 8 de agosto de 1948 en Moscú. A diferencia de Valentina Tereshkova, Savitskaya era una aviadora de élite antes de ser seleccionada para el programa espacial. A los 17 años obtuvo su licencia de piloto y comenzó a practicar paracaidismo de competición. A los 22 años estableció un **récord mundial de velocidad** en aviones a reacción pilotando un MiG-21 a 2,683 km/h, convirtiéndose en la mujer más rápida del mundo en ese momento. También fue campeona mundial de vuelo acrobático en 1970. Era, sin duda, una de las pilotas más talentosas de su generación, comparable en habilidad técnica a los mejores pilotos masculinos de la Fuerza Aérea Soviética.',
    'Savitskaya fue seleccionada para el programa de cosmonautas soviético en 1980, durante una nueva ola de reclutamiento después de años de pausa en la participación femenina. El contexto político era importante: la NASA había seleccionado a Sally Ride para su clase de astronautas en 1978, y la URSS quería enviar a una mujer al espacio antes que los americanos. Savitskaya fue seleccionada en parte por su experiencia técnica excepcional y en parte, nuevamente, por razones políticas. Sin embargo, a diferencia de Tereshkova, Savitskaya era ya una aviadora profesional de primera categoría antes de ser seleccionada. Pasó dos años de entrenamiento intensivo en el **Centro de Entrenamiento de Cosmonautas Yuri Gagarin** en la Ciudad de las Estrellas (Звёздный городок), cerca de Moscú.',
    'El **19 de agosto de 1982**, Savitskaya fue lanzada a bordo del **Soyuz T-7** rumbo a la estación espacial **Salyut 7**. Se convirtió en la **segunda mujer en el espacio** de la historia, 19 años después de Tereshkova. Pasó **7 días, 21 horas y 52 minutos** en la estación, realizando experimentos científicos, pruebas de equipos y observaciones de la Tierra. Durante su estancia en el Salyut 7, ocurrió un incidente revelador del sexismo institucional de la época: según Savitskaya, el comandante de la estación le ofreció un delantal al llegar, bromeando sobre que ella debería cocinar. Savitskaya respondió que era ella quien le enseñaría a él cómo trabajar en el espacio.',
    'Lo más notable de la primera misión de Savitskaya fue su demostración técnica en el espacio. A diferencia de Tereshkova, que había tenido un vuelo principalmente simbólico, Savitskaya realizó **experimentos tecnológicos concretos** con nuevos equipos de soldadura y corte de materiales en el vacío espacial. Fue la primera vez que estos experimentos se hacían con una mujer como operadora principal. Sus resultados fueron tan buenos que los ingenieros de la misión la calificaron como la mejor operadora de esos equipos de las misiones recientes, mejor que varios cosmonautas masculinos anteriores. Este resultado fue científicamente valioso: demostró que el género no afecta la habilidad para realizar tareas técnicas de precisión en microgravedad.',
    'Dos años después, Savitskaya regresó al espacio con una segunda misión igualmente histórica. El **17 de julio de 1984**, a bordo del **Soyuz T-12**, fue de nuevo al Salyut 7. El 25 de julio de 1984, a las 10:55 hora de Moscú, Savitskaya salió al espacio exterior con el cosmonauta Vladimir Dzhanibekov y se convirtió en la **primera mujer en realizar una EVA** (caminata espacial). Pasó **3 horas y 35 minutos** fuera de la estación, operando una herramienta multipropósito de soldadura, corte, y braseo en el vacío espacial. La herramienta, llamada **URI** (Universal Hand Tool), era tan nueva que los ingenieros querían probarla con un operador experto, y eligieron a Savitskaya.',
  ]},
  { id: 'svetlana_s2', title: 'La Primera Caminata Espacial Femenina', image: '/assets/pioneros/svetlana.png', text: [
    'La EVA de Svetlana Savitskaya el 25 de julio de 1984 fue un hito histórico, científico y técnico de primera magnitud. Para ponerlo en contexto: la primera caminata espacial había sido realizada por Alexei Leonov en 1965. Habían pasado **19 años** antes de que una mujer hiciera lo mismo. Durante esas 3 horas y 35 minutos, Savitskaya no estaba simplemente "flotando" en el espacio como ejercicio simbólico. Estaba realizando un **trabajo técnico real**: cortar, soldar y crear aleaciones de materiales en el vacío espacial, usando la herramienta URI en modos de corte electrónico, soldadura y braseo.',
    'La herramienta **URI** (en ruso: Universalny Ruchnoy Instrument, "Herramienta Universal de Mano") fue un avance tecnológico significativo. Combinaba en un solo dispositivo la capacidad de cortar metales usando un haz de electrones, soldar piezas juntas, y crear braseos de materiales diferentes. El problema en el espacio es que las herramientas convencionales no funcionan en el vacío: las llamas necesitan oxígeno, los adhesivos no curan igual, y las temperaturas extremas (-120°C en sombra, +120°C en sol) afectan los materiales. La URI usaba **energía eléctrica convertida en haz de electrones**, que sí funciona en el vacío. Savitskaya fue entrenada específicamente para operar esta herramienta, y sus resultados en la EVA fueron considerados excelentes por los ingenieros de misión.',
    'El valor científico de la EVA de Savitskaya fue doble. Primero, demostró técnicamente que la herramienta URI funcionaba en condiciones reales de vacío y temperatura extrema. Esto era fundamental para el futuro de las **reparaciones en el espacio**: si los astronautas podían soldar y cortar materiales fuera de la estación, podían reparar daños en el casco o construir estructuras nuevas sin necesidad de traer los materiales desde la Tierra. Segundo, y esto es igualmente importante, demostró que una mujer podía realizar trabajo técnico complejo en el espacio exterior con la misma eficacia que un hombre. Los análisis post-misión mostraron que Savitskaya completó el 100% de las tareas técnicas planificadas dentro del tiempo asignado.',
    'A diferencia de la misión de Leonov en 1965 (que casi terminó en tragedia por el inflado del traje), la EVA de Savitskaya transcurrió sin problemas técnicos. Esto fue en parte resultado de las **mejoras en los trajes** desarrolladas después de la crisis de Leonov: el traje Orlan soviético, diseñado en los años 70, tenía un sistema de presurización mucho más sofisticado y seguro que el Berkut de 1965. El traje Orlan usa una presurización a 0.4 atmósferas (igual que el de Leonov en crisis, pero este era el valor nominal de diseño), tiene articulaciones preformadas que permiten mayor movilidad, y tiene un sistema de control de temperatura activo que mantiene al cosmonauta entre 18°C y 28°C independientemente de la temperatura exterior.',
    'Savitskaya también tiene otro récord histórico que pocas personas conocen: fue la primera mujer seleccionada para una **tercera misión al espacio**, que habría incluido otra EVA y experimentos de larga duración. Esta misión, planificada para 1986, fue cancelada después del desastre del transbordador **Challenger** el 28 de enero de 1986, que causó una pausa en los vuelos espaciales soviéticos por revisión de seguridad. Savitskaya nunca voló una tercera vez. Trabajó en la industria aeroespacial soviética/rusa hasta los años 90, y luego tuvo una carrera política, siendo diputada de la Duma rusa (el parlamento) durante varias décadas. Recibió el título de **"Héroe de la URSS"** dos veces por sus dos misiones.',
  ]},
  { id: 'svetlana_s3', title: 'Las Mujeres en la ISS: El Legado de las Pioneras', image: '/assets/pioneros/svetlana.png', text: [
    'El camino de Tereshkova (1963), Savitskaya (1982, 1984) y Sally Ride (1983) abrió las puertas para las generaciones siguientes. Hoy, la **Estación Espacial Internacional** (ISS) ha sido visitada por más de 250 astronautas de 20 países, de los cuales más de 70 son mujeres. La primera comandante de la ISS fue **Peggy Whitson** en 2008, que también estableció el récord de la astronauta con más días en el espacio: **665 días** en tres misiones. Whitson es, en términos de tiempo en el espacio, una de las personas más experimentadas de la historia, hombre o mujer.',
    'En el campo de las caminatas espaciales, el récord lo ostenta **Christina Koch**, que realizó la primera **caminata espacial exclusivamente femenina** de la historia el 18 de octubre de 2019, junto con Jessica Meir. Durante esa EVA de 7 horas y 17 minutos, Koch y Meir reemplazaron un controlador de carga de baterías defectuoso en el exterior de la ISS. Koch también estableció el récord de la mayor **duración continua en el espacio para una mujer**: 328 días consecutivos (del 14 de marzo de 2019 al 6 de febrero de 2020), un récord diseñado específicamente para estudiar los efectos a largo plazo de la microgravedad en el cuerpo femenino.',
    'La razón científica por la que la NASA estudia específicamente la salud de las astronautas femeninas es que hay diferencias fisiológicas que importan en el espacio. Las mujeres tienden a tener una mayor sensibilidad a la **radiación cósmica** (un mayor porcentaje de tejido sensible a la radiación, como el tejido mamario). Los efectos de la microgravedad en la **densidad ósea** difieren ligeramente entre hombres y mujeres: en promedio, las mujeres pierden masa ósea algo más rápido durante el primer mes en el espacio, aunque la diferencia se iguala en misiones largas. El **síndrome de visión del espacio** (SANS, que causa problemas de visión por el aumento de presión intracraneal) parece afectar más a los hombres que a las mujeres, aunque las razones no están completamente claras.',
    'El programa **Artemis** de la NASA, que planea establecer una presencia humana permanente en la Luna en los años 2030, incluye el compromiso explícito de poner a la **primera mujer en la Luna**. Las candidatas entrenadas incluyen a astronautas como **Christina Koch** (que ya realizó la primera EVA exclusivamente femenina), **Kate Rubins** (microbióloga y astronauta con experiencia en la ISS) y **Zena Cardman** (geóloga marina). El módulo lunar del programa Artemis está diseñado con consideraciones ergonómicas para una gama más amplia de tallas corporales, reconociendo que los trajes y equipos históricos habían sido diseñados principalmente para cuerpos masculinos de talla media.',
    'El legado de Svetlana Savitskaya, más que cualquier otro, es haber demostrado que las mujeres pueden hacer el **trabajo técnico más duro** del espacio. Tereshkova fue la primera, sí, pero su vuelo fue en gran medida simbólico. Savitskaya soldó metales en el vacío del espacio, algo que ningún humano había hecho antes de esa manera. Demostró con hechos, no con palabras, que el género no es una limitación para ningún tipo de trabajo en el cosmos. Hoy, cuando una astronauta sale al espacio exterior a reparar un panel solar o instalar un nuevo módulo en la ISS, lo hace parada sobre los hombros (metafóricamente) de Savitskaya, la mujer que demostró que se podía hacer.',
  ]},
],

pioneros_sally: [
  { id: 'sally_s1', title: 'Sally Ride: La Primera Astronauta Estadounidense', image: '/assets/pioneros/sally.png', text: [
    '**Sally Kristen Ride** nació el 26 de mayo de 1951 en Los Ángeles, California. Era hija de un profesor de ciencias políticas y una terapeuta voluntaria en prisiones. Desde niña mostró dos pasiones que definen su historia: la **física y el tenis**. Fue tan buena tenista que llegó al ranking 18 nacional de juniors en los Estados Unidos y recibió ofertas para torneos profesionales. Pero eligió la ciencia: se licenció en física y literatura inglesa en la Universidad de Stanford, hizo un máster en física, y estaba completando su **doctorado en astrofísica** en Stanford en 1977 cuando vio un anuncio en el periódico estudiantil: la NASA buscaba candidatos para astronauta, y por primera vez en la historia, aceptaba **mujeres**.',
    'El anuncio de 1977 de la NASA fue revolucionario. Decía explícitamente: "La NASA busca candidatos de ambos sexos de todas las razas." Era la primera convocatoria en la historia del programa espacial americano que no excluía a las mujeres. Se presentaron **8,079 candidatos**, de los cuales 1,544 eran mujeres. Ride fue seleccionada como parte de la clase de astronautas de 1978, junto con otras 5 mujeres: Judith Resnik (que murió en el Challenger), Anna Fisher, Shannon Lucid, Kathryn Sullivan y Margaret Rhea Seddon. Estos 35 nuevos astronautas, conocidos como el "Grupo 8" o los "35 nuevos astronautas", marcaron el inicio de la era moderna del programa espacial americano, con diversidad de género, raza y formación académica.',
    'El entrenamiento de Ride como astronauta duró 2 años (1978-1979). Aprendió a pilotar aviones a reacción T-38 Talon, a operar el **brazo robótico canadiense** (el SRMS, Shuttle Remote Manipulator System, también llamado "Canadarm"), a caminar en el espacio en simulaciones subacuáticas, a sobrevivir en el océano después de un amerizaje de emergencia, y a operar todos los sistemas del transbordador. Ride se especializó en el Canadarm, el brazo articulado de 15 metros que los astronautas usan para desplegar, capturar y reparar satélites desde la bahía de carga del transbordador. Esta habilidad sería central en sus misiones.',
    'El **18 de junio de 1983**, a las 7:33 AM, el transbordador **Challenger** despegó del Centro Espacial Kennedy con la misión **STS-7**. A bordo estaba Sally Ride, de 32 años. Se convirtió en la primera mujer estadounidense y la tercera mujer en el mundo (después de Tereshkova y Savitskaya) en llegar al espacio. El vuelo duró **6 días, 2 horas y 23 minutos**. Durante la misión, Ride desplegó dos satélites de comunicaciones (Anik C2 de Canadá y Palapa B1 de Indonesia) usando el Canadarm, y participó en experimentos científicos que incluían pruebas de un radar de imágenes y experimentos médicos sobre el sistema vestibular en microgravedad.',
    'La **recepción mediática** del vuelo de Ride fue inmensa pero también, en muchos aspectos, incómoda para ella. Los reporteros le preguntaban si lloraba cuando salían mal las cosas, si llevaba maquillaje al espacio, si el vuelo afectaría su capacidad de tener hijos. Ride respondía con paciencia pero con firmeza, negándose a que la redujeran a un símbolo de género. "Soy una astronauta que también es mujer", decía. Curiosamente, las preguntas más técnicas y específicas sobre la misión venían de las niñas en los eventos escolares. Ride se convirtió en un ícono para toda una generación de jóvenes, especialmente niñas, que vieron por primera vez que una mujer podía ser astronauta.',
  ]},
  { id: 'sally_s2', title: 'La Científica y Educadora', image: '/assets/pioneros/sally.png', text: [
    'Sally Ride realizó una **segunda misión** al espacio a bordo del Challenger en octubre de 1984 (STS-41-G), volando junto con Kathryn Sullivan (la primera americana en hacer una EVA). Estaba entrenándose para una **tercera misión** en 1986 cuando el Challenger explotó el 28 de enero de ese año, matando a los 7 tripulantes, incluyendo a su compañera de clase Judith Resnik. El desastre cambió el curso de la NASA y de la carrera de Ride. Fue convocada por el presidente Reagan para formar parte de la **Comisión Rogers**, la comisión independiente encargada de investigar las causas del accidente. Sus análisis técnicos fueron fundamentales para identificar la falla de las juntas tóricas del cohete acelerador sólido en temperaturas frías.',
    'Después del accidente del Challenger, Ride trabajó dos años en la NASA como directora de planificación estratégica, período en el que redactó el influyente informe **"Leadership and America\'s Future in Space"** (conocido como "el Informe Ride"). Este documento, publicado en 1987, propuso una visión a largo plazo para el programa espacial americano que incluía cuatro iniciativas: exploración de la Luna y Marte, estaciones en el espacio, un programa de ciencias de la Tierra desde el espacio, y exploración robótica del sistema solar. Muchas de estas recomendaciones influyeron en los programas que la NASA ejecuta hoy, incluyendo el programa de observación de la Tierra que monitorea el cambio climático.',
    'Ride dejó la NASA en 1987 para regresar a la academia como **profesora de física en Stanford** y luego en la **Universidad de California, San Diego (UCSD)**. Fue directora del Centro de Física de la Educación en UCSD y dedicó gran parte de su energía a un problema que le apasionaba: por qué las niñas pierden el interés en las ciencias y las matemáticas durante la adolescencia. Sus estudios mostraron que las niñas en edad escolar tienen la misma o mayor aptitud para las matemáticas que los niños, pero que factores sociales y culturales (expectativas de los padres, representación en los medios, estereotipos de género) reducen su interés y confianza a partir de los 11-12 años.',
    'En 2001, Ride fundó **Sally Ride Science**, una empresa educativa no lucrativa enfocada en despertar el interés de las niñas en ciencias, tecnología, ingeniería y matemáticas (STEM). La empresa creó programas de campamento de verano, publicaciones científicas para niñas, y eventos escolares. Uno de sus programas más innovadores fue **EarthKAM** (Earth Knowledge Acquired by Middle school students), en el que estudiantes de secundaria controlan una cámara instalada en la ISS y fotografían regiones de la Tierra que ellos eligen. Más de 100,000 estudiantes de todo el mundo han participado en EarthKAM desde su creación, generando más de 100,000 fotografías de la Tierra desde el espacio. Es uno de los programas de ciencias ciudadanas más exitosos en educación espacial.',
    'Sally Ride murió el **23 de julio de 2012** de **cáncer de páncreas**, solo 17 meses después del diagnóstico, a los 61 años. En su obituario, su familia reveló que su compañera de vida durante 27 años había sido **Tam O\'Shaughnessy**, una científica y autora. Ride se convirtió póstumamente en la primera astronauta conocida públicamente homosexual, y su historia añadió una nueva dimensión a su legado como pionera de la igualdad. El presidente Obama le otorgó póstumamente la **Medalla Presidencial de la Libertad** en 2013, la máxima distinción civil de los Estados Unidos. Su nombre vive en el asteroide **4763 Ride**, en el buque oceanográfico de investigación **RV Sally Ride** de la US Navy, y en la **Escuela Sally Ride STEM** en Chicago.',
  ]},
  { id: 'sally_s3', title: 'El Impacto en la Educación Científica', image: '/assets/pioneros/sally.png', text: [
    'El legado educativo de Sally Ride es, según muchos educadores, **más importante que su legado como astronauta**. Como astronauta, fue pionera durante 6 días en el espacio. Como educadora, transformó la vida de decenas de miles de jóvenes durante 25 años. Su investigación sobre la participación de niñas en STEM mostró que la brecha no era de aptitud sino de **percepción y ambiente**: las niñas eran igualmente capaces, pero el ambiente social les decía sistemáticamente que las ciencias "no eran para ellas". La solución de Ride fue crear ambientes donde las niñas pudieran ver a otras mujeres en ciencias, donde fueran elogiadas por hacer buenas preguntas, y donde la ciencia se conectara con cosas que les importaban.',
    'El programa **EarthKAM** que Ride diseñó es un ejemplo perfecto de su filosofía educativa. En lugar de enseñar ciencias de forma abstracta, conectaba a los estudiantes con algo real y emocionante: controlar una cámara en el espacio. Los estudiantes elegían qué fotografiar (su ciudad, un volcán, un río que habían estudiado), calculaban cuándo la ISS pasaría sobre esa región, enviaban los comandos de control de la cámara a la NASA, y recibían sus propias fotografías del espacio días después. Este proceso enseñaba astronomía (órbitas de la ISS), geografía (coordenadas geográficas), física (óptica y exposición fotográfica), e informática (protocolos de comunicación), todo integrado en una experiencia emocionante y significativa.',
    'Uno de los libros más influyentes que escribió Sally Ride fue **"To Space and Back"** (1986), coescrito con Susan Okie. Fue el primer libro sobre viajes espaciales escrito para niños por alguien que realmente había estado en el espacio. En él, Ride describe con detalle y humor cómo es vivir en el espacio: cómo te lavas los dientes cuando el agua flota, cómo comes cuando la cuchara no cae, cómo duermes cuando tu cuerpo no tiene peso. La primera edición vendió más de 500,000 copias. Ride también coescribió otros libros de ciencias para niños: **"Voyager: An Adventure to the Edge of the Solar System"**, **"The Third Planet"** (sobre la Tierra), y **"Mission: Planet Earth"** (sobre cambio climático), todos caracterizados por la precisión científica y la accesibilidad para lectores jóvenes.',
    'La **Medalla Presidencial de la Libertad** que Obama le otorgó a Ride en 2013 reconoció no solo su carrera astronáutica sino su "trabajo incansable para inspirar a las generaciones jóvenes de científicos e ingenieros." La cita del presidente en la ceremonia fue: "Sally fue una pionera en los dos sentidos más importantes de la palabra: fue a donde ninguna mujer había ido antes, y luego dedicó su vida a asegurarse de que no fuera la última." Esta distinción, junto con el asteroide, el barco y las escuelas que llevan su nombre, representa el reconocimiento de una vida dedicada no solo a explorar el espacio sino a **democratizar el acceso al conocimiento científico**.',
    'Hoy, el trabajo de Sally Ride continúa a través de la organización **Sally Ride Science** (ahora fusionada con la Universidad de California San Diego), el programa **EarthKAM** (que opera continuamente en la ISS), y los miles de científicas e ingenieras que fueron inspiradas por ella. En una encuesta de 2018 a mujeres que trabajan en NASA, el 43% mencionó el vuelo de Ride en 1983 como un momento que influyó en su decisión de estudiar ciencias. Ese es el verdadero cálculo del legado de Sally Ride: no los 6 días que pasó en el espacio en 1983, sino los millones de días de trabajo científico que sus sucesoras han dedicado y seguirán dedicando a entender el universo.',
  ]},
],

};

for (const [moduleId, sections] of Object.entries(CONTENT)) {
  replaceModule(moduleId, sections);
}
console.log('\nAll pioneros2 modules rebuilt!');
