const fs = require('fs');
const path = require('path');
const COURSE_DATA_PATH = path.join(__dirname, '../lib/courseData.js');

function findSectionsRange(text, moduleId) {
  const s1 = '"id": "' + moduleId + '"';
  const s2 = '"id":"' + moduleId + '"';
  let idIdx = text.indexOf(s1);
  if (idIdx < 0) idIdx = text.indexOf(s2);
  if (idIdx < 0) return null;
  const ceIdx = text.indexOf('"contentEs"', idIdx);
  if (ceIdx < 0 || ceIdx - idIdx > 5000) return null;
  const sectIdx = text.indexOf('"sections"', ceIdx);
  if (sectIdx < 0) return null;
  const arrStart = text.indexOf('[', sectIdx);
  if (arrStart < 0) return null;
  let depth = 0, arrEnd = arrStart;
  for (let i = arrStart; i < text.length; i++) {
    if (text[i] === '[') depth++;
    else if (text[i] === ']') { depth--; if (depth === 0) { arrEnd = i; break; } }
  }
  return { arrStart, arrEnd };
}

function replaceModule(moduleId, newSections) {
  let text = fs.readFileSync(COURSE_DATA_PATH, 'utf8');
  const range = findSectionsRange(text, moduleId);
  if (!range) { console.error('NOT FOUND: ' + moduleId); return; }
  const { arrStart, arrEnd } = range;
  const newArr = JSON.stringify(newSections, null, 6);
  text = text.substring(0, arrStart) + newArr + text.substring(arrEnd + 1);
  fs.writeFileSync(COURSE_DATA_PATH, text, 'utf8');
  console.log('OK: ' + moduleId + ' (' + newSections.reduce((s,x)=>s+x.text.length,0) + ' paras)');
}

const CONTENT = {

animales_intro: [
  { id: 'animales_intro_s1', title: 'Animales en el Espacio: El Inicio de una Era', image: '/assets/animales/animales_intro.png', text: [
    'Antes de que cualquier ser humano viajara al espacio, los científicos necesitaban saber si era posible sobrevivir fuera de la Tierra. La pregunta era enorme: ¿podría un ser vivo resistir el lanzamiento violento, la ingravidez, la radiación cósmica y el regreso a la atmósfera? Para responderla, enviaron animales. Estos valientes exploradores sin saberlo abrieron el camino para toda la exploración espacial humana. Sus viajes fueron cruciales para la ciencia, aunque también fueron polémicos éticamente.',
    'El primer animal enviado al espacio fue la **mosca de la fruta (Drosophila melanogaster)** en 1947, a bordo de un cohete V-2 capturado de Alemania por los Estados Unidos. Las moscas fueron elegidas porque su genética es muy similar a la humana en un 60%, y los científicos querían estudiar los efectos de la radiación cósmica en el ADN. El cohete alcanzó 109 kilómetros de altitud, cruzando la línea de Kármán (100 km), el límite oficial del espacio. Las moscas sobrevivieron y fueron recuperadas en paracaídas. Este experimento demostró que los organismos vivos podían sobrevivir brevemente en el espacio.',
    'En 1948 y 1949, los Estados Unidos lanzaron monos rhesus llamados **Albert I y Albert II** en cohetes V-2. Albert I murió por asfixia antes de llegar al espacio. Albert II llegó a 134 km de altitud en junio de 1949, convirtiéndose en el primer primate en el espacio, pero murió al impactar contra el suelo cuando falló el sistema de recuperación. Los científicos aprendieron muchísimo de estos trágicos experimentos: cómo el cuerpo reacciona a la aceleración extrema (hasta 9G durante el lanzamiento), cómo la presión afecta los pulmones, y cómo los sistemas de soporte vital deben funcionar perfectamente.',
    'La **Unión Soviética** entró en la carrera espacial animal con gran éxito. En 1957, lanzaron a la famosa **Laika**, una perra mestiza recogida de las calles de Moscú, a bordo del Sputnik 2. Laika se convirtió en el primer ser vivo en orbitar la Tierra. La misión fue una hazaña técnica asombrosa para la época: el Sputnik 2 pesaba 508 kg y llevaba un sistema de soporte vital que monitorizaba la temperatura, presión y ritmo cardíaco de Laika. Desafortunadamente, la misión no tenía plan de regreso: Laika murió en órbita pocas horas después del lanzamiento por sobrecalentamiento.',
    'Los primeros animales en regresar vivos del espacio fueron las perras soviéticas **Belka y Strelka** en agosto de 1960, a bordo del Sputnik 5. Pasaron 25 horas en órbita, completando 17 vueltas alrededor de la Tierra, y aterrizaron sanos y salvos junto con otros pasajeros: 40 ratones, 2 ratas, moscas, plantas, hongos y muestras de semillas. Strelka tuvo cachorros después de la misión, y uno de ellos, llamado **Pushinka**, fue regalado por Nikita Khrushchev al presidente John F. Kennedy. Este hecho humanizó la rivalidad de la Guerra Fría de forma inesperada.',
  ]},
  { id: 'animales_intro_s2', title: 'Lo Que los Animales Enseñaron a la Ciencia', image: '/assets/animales/animales_intro.png', text: [
    'Cada animal enviado al espacio generó datos científicos invaluables. Los médicos y físicos estudiaron cómo el **sistema cardiovascular** se adapta a la microgravedad: el corazón late más despacio porque no necesita bombear sangre contra la gravedad hacia el cerebro. Los fluidos corporales se redistribuyen hacia la cabeza, lo que da a los astronautas el aspecto hinchado en la cara que vemos en las fotografías. Los huesos y músculos se debilitan rápidamente sin la carga gravitacional. Todo esto fue descubierto primero observando animales en el espacio.',
    'Los **chimpancés** fueron fundamentales para preparar los primeros vuelos humanos. **Ham**, un chimpancé entrenado durante 18 meses por la NASA, voló en enero de 1961 en el cohete Mercury-Redstone 2. Ham fue entrenado para jalar palancas en respuesta a luces: si jalaba la palanca correcta al ver una luz azul, recibía un bocado de plátano; si no la jalaba, recibía una leve descarga eléctrica en la planta del pie. Durante el vuelo, Ham siguió respondiendo correctamente a las señales, demostrando que un ser vivo podía realizar tareas complejas en el espacio. Este experimento validó el concepto de que los astronautas humanos podrían operar controles en condiciones de microgravedad.',
    'La **biología espacial** como disciplina científica nació directamente de estos experimentos con animales. Los científicos descubrieron el fenómeno de la **desorientación espacial**: en ausencia de gravedad, el sistema vestibular del oído interno (que nos ayuda a mantener el equilibrio en la Tierra) envía señales confusas al cerebro. Esto causa mareos, náuseas y desorientación. En los primeros días de los vuelos espaciales, casi todos los astronautas experimentaban estos síntomas. Los médicos desarrollaron medicamentos y técnicas de entrenamiento para reducirlos, basándose en lo que habían observado en animales.',
    'En los años 1960 y 1970, tanto la NASA como la agencia espacial soviética (ahora **Roscosmos**) realizaron experimentos con ranas, tortugas, peces y hasta percebes en el espacio. Las **ranas de cola** (Xenopus laevis) fueron especialmente importantes: en microgravedad, las células de los embriones de rana no se dividen correctamente, lo que sugiere que la gravedad juega un papel en el desarrollo embrionario de todos los vertebrados. Este hallazgo tiene implicaciones directas para entender si los seres humanos podrían reproducirse en el espacio durante viajes interestelares largos.',
    'En el siglo XXI, los experimentos con animales en el espacio continúan, pero con fines muy diferentes. La **Estación Espacial Internacional (ISS)** alberga regularmente experimentos con ratones, peces cebra (Danio rerio), gusanos C. elegans y cucarachas. El gusano C. elegans es un organismo modelo perfecto: tiene exactamente **959 células somáticas**, su genoma completo está secuenciado, y el 40% de sus genes tienen equivalentes en humanos. Estudiar cómo este gusano envejece, se mueve y se reproduce en microgravedad ayuda a los científicos a entender el envejecimiento humano y a desarrollar medicamentos contra la osteoporosis y la atrofia muscular, enfermedades muy comunes en los astronautas de larga duración.',
  ]},
  { id: 'animales_intro_s3', title: 'El Legado Ético y Científico', image: '/assets/animales/animales_intro.png', text: [
    'El uso de animales en la exploración espacial siempre ha generado debate ético. En la actualidad, los experimentos con animales en el espacio están **estrictamente regulados** por comités internacionales de ética científica. Todos los protocolos deben ser aprobados por comités independientes que evalúan si el conocimiento que se obtendrá justifica el estrés infligido al animal, si se han agotado todas las alternativas posibles (modelos computacionales, cultivos celulares), y si el diseño experimental minimiza el sufrimiento al máximo. Esta evolución ética es un logro colectivo de la humanidad científica.',
    'Los organismos más pequeños han resultado ser los más valiosos para la ciencia espacial moderna. Las **tardigradas** (también llamados "osos de agua") son microanimales de 0.5mm que pueden sobrevivir en el vacío del espacio, temperaturas de -273°C hasta +150°C, y dosis de radiación 1000 veces letales para los humanos. En 2019, miles de tardigradas deshidratadas sobrevivieron a un accidente durante la misión lunar israelí Beresheet. En el espacio, entran en un estado de **criptobiosis**: detienen todo metabolismo, sustituyen el agua en sus células por una proteína llamada Dsup, y esperan condiciones favorables. Entender este mecanismo podría permitir en el futuro "congelar" astronautas para viajes interestelares.',
    'Los **peces cebra** (Danio rerio) se han convertido en los animales espaciales del siglo XXI. Son transparentes en estadio larvario, lo que permite observar sus órganos internos con microscopio sin cirugía. Su **genoma** es 70% similar al humano. Se reproducen en 3 meses y sus embriones se desarrollan en 24 horas, lo que permite estudiar múltiples generaciones en una sola misión espacial. En la ISS, los científicos han observado que los peces cebra en microgravedad nadan en círculos (desorientación vestibular) durante los primeros días, pero se adaptan en 72 horas. Este patrón de adaptación es casi idéntico al que ocurre en astronautas humanos.',
    'El programa de **bioastronautica** ha generado más de 1,200 publicaciones científicas peer-reviewed en los últimos 20 años. Descubrimientos clave incluyen: que la microgravedad activa el gen **CDKN1A** (regulador del ciclo celular) en mamíferos, lo que explica parte del envejecimiento acelerado que sufren los astronautas; que la radiación cósmica causa daño en el **ADN mitocondrial** de manera diferente a la radiación terrestre; y que el intestino humano (y de otros mamíferos) en el espacio sufre cambios en su **microbioma** similares a los que ocurren en personas con síndrome de intestino irritable. Todos estos hallazgos tienen aplicaciones médicas directas en la Tierra.',
    'El futuro de los animales en el espacio es fascinante. Los planes de la NASA para colonizar Marte incluyen llevar **ecosistemas completos**: gusanos para enriquecer el suelo marciano, bacterias fijadoras de nitrógeno, insectos polinizadores y peces para producir proteínas. Los científicos del proyecto **BioSphere 2** (un experimento de ecosistema cerrado en Arizona en 1991) ya demostraron que es posible crear sistemas ecológicos autosuficientes, aunque con grandes dificultades. La lección más importante que nos dieron todos los animales espaciales es que la vida en el cosmos es frágil, compleja e interdependiente: exactamente igual que en la Tierra.',
  ]},
],

animales_albert_ham: [
  { id: 'albert_ham_s1', title: 'Los Primates Pioneros del Espacio', image: '/assets/animales/albert_ham.png', text: [
    'En la historia de la exploración espacial, los monos y chimpancés jugaron un papel fundamental que muchas veces queda en la sombra de los grandes astronautas humanos. Antes de que Yuri Gagarin orbitara la Tierra en 1961, la NASA y la Fuerza Aérea de Estados Unidos enviaron al menos **29 primates al espacio** en diferentes misiones entre 1948 y 1985. Estos animales no eran simples cobayas pasivas: fueron entrenados meticulosamente para realizar tareas específicas que demostrarían la capacidad de un ser vivo para funcionar bajo condiciones de estrés extremo, microgravedad y radiación cósmica.',
    'El primero fue **Albert I**, un mono rhesus enviado en junio de 1948 a bordo de un cohete V-2 capturado de la Alemania nazi. Albert I nunca llegó realmente al espacio: murió asfixiado durante el vuelo, posiblemente por un fallo en el sistema de soporte de vida. Su sucesor, **Albert II**, fue más exitoso: en junio de 1949 alcanzó una altitud de 134 kilómetros, cruzando con claridad la línea de Kármán (100 km), el límite oficial del espacio según la **Federación Aeronáutica Internacional (FAI)**. Albert II se convirtió así en el primer primate en el espacio. Desgraciadamente, murió al impactar contra el suelo cuando el paracaídas no se desplegó.',
    'Los experimentos con los **Albert III, IV y V** continuaron hasta 1951, mejorando gradualmente los sistemas de recuperación y soporte vital. Albert V fue el primero en sobrevivir al vuelo completo, aunque murió días después por causas no relacionadas directamente con el viaje espacial. Estos experimentos tempranos enseñaron a los ingenieros dos lecciones críticas: primero, que los **sistemas de recuperación** (paracaídas, señales de radio) son tan importantes como el cohete mismo; segundo, que la cabina presurizada debe mantener exactamente la mezcla correcta de oxígeno y nitrógeno para que un mamífero respire normalmente en el vacío del espacio.',
    'En **1959**, la NASA seleccionó a 40 chimpancés para el programa Mercury y comenzó un entrenamiento intensivo. Los chimpancés fueron elegidos sobre otros primates por varias razones científicas: su **genoma** comparte el 98.7% del ADN humano, su sistema cardiovascular es casi idéntico al nuestro, sus manos son capaces de operar palancas y controles simples, y su inteligencia les permite aprender tareas condicionadas complejas. Durante 18 meses, los entrenadores usaron el método de **condicionamiento operante** de B.F. Skinner: recompensas (plátanos) por respuestas correctas y leves estímulos negativos por errores.',
    'El candidato que destacó por encima de todos fue **Ham** (nombre dado después del vuelo; antes se le llamaba simplemente "N. 65"). Ham era una especie de chimpancé llamada **Pan troglodytes**, capturado en Camerún a los dos años de edad. Llegó a Holloman Air Force Base en Nuevo México en 1959 y demostró ser excepcionalmente inteligente y tranquilo bajo presión. Sus entrenadores, el Mayor John Glenn y Wanda Kay Merryman, describieron a Ham como "el más apto psicológicamente" de todos los candidatos: no mostraba pánico ante los simulacros de lanzamiento ni ante las cámaras de presión.',
  ]},
  { id: 'albert_ham_s2', title: 'El Vuelo de Ham: 31 de Enero de 1961', image: '/assets/animales/albert_ham.png', text: [
    'El 31 de enero de 1961, exactamente **16 minutos y 39 segundos** duró el vuelo histórico de Ham. A bordo de la cápsula Mercury-Redstone 2, Ham fue catapultado desde Cabo Cañaveral a una velocidad máxima de 9.285 km/h (Mach 7.7) y alcanzó una altitud de 253 kilómetros, mucho más alta de lo planeado (se esperaba 185 km) debido a un fallo en la válvula de combustible que hizo que el cohete quemara más rápido de lo calculado. Ham soportó fuerzas G de hasta **14.7G** durante el reingreso a la atmósfera, más del doble de lo previsto.',
    'Durante todo el vuelo, Ham realizó su tarea de manera **casi perfecta**: jalaba la palanca correcta al ver la luz azul para evitar el estímulo eléctrico en sus pies. Los registros muestran que cometió un solo error durante todo el vuelo, y ese error ocurrió durante la fase de mayor estrés del reingreso atmosférico. La interpretación científica fue clara: si un chimpancé entrenado podía operar controles bajo condiciones de 14G de aceleración, microgravedad y estrés extremo, un astronauta humano altamente entrenado también podría hacerlo. Esto dio luz verde al programa Mercury.',
    'Después del amerizaje en el Atlántico, Ham tuvo que esperar **3 horas y 15 minutos** dentro de la cápsula semisumergida antes de ser rescatado. La cápsula tomó agua y él pasó tiempo en condiciones difíciles. Cuando finalmente lo sacaron, los médicos encontraron que estaba levemente deshidratado y tenía una pequeña erosión en la nariz (por el traje de vuelo), pero por lo demás estaba en perfecto estado. Ham rechazó comer el manzana que le ofrecieron inicialmente, pero sí aceptó una naranja. Los reportes fotográficos de Ham después del rescate muestran claramente su satisfacción: científicos que lo conocían dijeron que "claramente estaba de buen humor".',
    'Los datos biomédicos recolectados durante el vuelo de Ham fueron revolucionarios. Los sensores registraron su **frecuencia cardíaca** (que aumentó de 90 lpm en reposo a 155 lpm durante el lanzamiento), **temperatura corporal**, **presión sanguínea** y movimientos. Los médicos descubrieron que durante la fase de microgravedad (que duró apenas 6 minutos y 34 segundos), la frecuencia cardíaca de Ham bajó a niveles más tranquilos que durante el vuelo, sugiriendo que la ingravidez en sí misma no es estresante para el sistema cardiovascular. Fue la primera evidencia directa de que los mamíferos toleran bien la microgravedad a corto plazo.',
    'Alan Shepard se convirtió en el primer estadounidense en el espacio apenas **3 meses y 5 días** después del vuelo de Ham, el 5 de mayo de 1961. Sin el vuelo de Ham, Shepard probablemente no habría podido ir. La NASA necesitaba esa demostración de que un ser vivo podía operar bajo condiciones espaciales antes de arriesgarse con una vida humana. El propio Alan Shepard reconoció públicamente esta deuda: "Somos astronautas porque Ham demostró que era posible." Ham vivió hasta los 26 años en el Zoológico Nacional de Washington y más tarde en el Zoológico de Carolina del Norte, donde murió en 1983 como el héroe silencioso de la era espacial.',
  ]},
  { id: 'albert_ham_s3', title: 'La Ciencia Detrás del Entrenamiento Animal', image: '/assets/animales/albert_ham.png', text: [
    'El entrenamiento de Ham y otros chimpancés para misiones espaciales fue una demostración magistral de **psicología conductista** aplicada a la ciencia espacial. Los entrenadores usaban el método de **shaping** (modelado por aproximaciones sucesivas): primero enseñaban al chimpancé a sentarse quieto, luego a prestar atención a una luz, luego a tocar un panel, luego a jalar una palanca específica dentro de 5 segundos. Cada etapa era reforzada con recompensas de comida. Este proceso tomaba meses de sesiones diarias de 30-60 minutos. Los chimpancés más inteligentes aprendían secuencias de hasta **8 acciones encadenadas** en respuesta a señales visuales diferentes.',
    'El **sistema vestibular** de los chimpancés, que controla el equilibrio, fue estudiado exhaustivamente antes y después de los vuelos. Los investigadores de la NASA descubrieron que después de apenas 6 minutos en microgravedad, los chimpancés mostraban una **adaptación neurológica** notable: el cerebro comenzaba a ignorar las señales incorrectas del oído interno y a depender más de señales visuales para orientarse. Este mismo proceso ocurre en astronautas humanos, pero tarda 2-3 días en completarse. La diferencia de tiempo se debe a que el cerebro humano es más dependiente del sistema vestibular y más resistente al cambio.',
    'Uno de los hallazgos más sorprendentes de los experimentos con primates fue sobre la **percepción del tiempo** en el espacio. Los chimpancés entrenados para realizar tareas en intervalos de tiempo fijos (cada 20 segundos, por ejemplo) mostraron que su sentido del tiempo se volvía inexacto en microgravedad durante los primeros minutos. Los científicos interpretaron esto como evidencia de que el **ritmo circadiano** y la percepción temporal están parcialmente regulados por señales gravitacionales. Este hallazgo fue confirmado décadas después en estudios con astronautas humanos en la ISS, donde el sueño irregular es uno de los problemas más reportados.',
    'Después de Ham, el programa de primates de la NASA continuó con **Enos**, el primer chimpancé en orbitar la Tierra, en noviembre de 1961. A diferencia del vuelo suborbital de Ham, Enos completó 2 órbitas completas alrededor de la Tierra en 3 horas y 20 minutos, demostrando que un primate podía funcionar durante un vuelo orbital completo. Los datos de Enos fueron directamente responsables de que John Glenn pudiera orbitar la Tierra apenas 3 meses después, en febrero de 1962. Enos también demostró algo inesperado: durante el vuelo, el sistema de recompensa/castigo falló y Enos recibía estímulos negativos independientemente de si hacía lo correcto. A pesar de esto, continuó realizando la tarea correctamente: evidencia de que los chimpancés pueden mantener el comportamiento aprendido incluso bajo condiciones adversas.',
    'El legado científico de todos estos animales pioneros va mucho más allá de la historia espacial. Los estudios biomédicos realizados con Ham, Enos y los Alberts ayudaron a fundar la **medicina aeroespacial** como especialidad médica reconocida. Las técnicas de monitorización no invasiva de constantes vitales (frecuencia cardíaca, presión arterial, temperatura) que hoy se usan en todas las UCI del mundo fueron desarrolladas originalmente para monitorizar a animales en vuelos espaciales. Los **trajes de presión** usados por pilotos de aviones militares y astronautas derivan directamente de los trajes diseñados para Ham. Y la **psicología del estrés** en situaciones extremas, aplicada hoy a bomberos, militares y cirujanos, tomó muchas de sus bases teóricas de los estudios con primates espaciales.',
  ]},
],

animales_laika: [
  { id: 'laika_s1', title: 'Laika: La Cosmonauta de Cuatro Patas', image: '/assets/animales/animales_laika.png', text: [
    '**Laika** (que significa "ladradora" en ruso) fue una perra mestiza de unos 3 años, pequeña y tranquila, recogida de las calles de Moscú en 1957. Los científicos soviéticos preferían usar perros callejeros para sus experimentos espaciales porque estos animales ya estaban acostumbrados a condiciones adversas: fríos extremos, hambre ocasional y situaciones impredecibles. Los perros de raza, más mimados, tendían a estresarse más en situaciones nuevas. Laika fue seleccionada entre más de 10 candidatos finales por ser la más calmada y bien proporcionada físicamente para el espacio reducido de la cápsula espacial.',
    'El **Sputnik 2** fue diseñado y construido en apenas **4 semanas**, una hazaña de ingeniería impulsada por la orden directa de Nikita Khrushchev de lanzar una misión espectacular para celebrar el 40 aniversario de la Revolución Bolchevique (7 de noviembre de 1957). El cohete pesaba 508.3 kilogramos, casi seis veces más que el Sputnik 1 (83.6 kg), y llevaba un sistema de soporte vital que incluía suministro de oxígeno para 7 días, absorbedores de CO₂, comida en forma de gelatina, agua, y sensores para medir temperatura, presión, pulso cardíaco y respiración de Laika. También llevaba instrumentos científicos para medir radiación cósmica y temperatura en el espacio.',
    'El **3 de noviembre de 1957**, el Sputnik 2 fue lanzado desde el Cosmódromo de Baikonur (en Kazajistán, entonces parte de la URSS) a las 5:30 hora de Moscú. Laika fue colocada en la cápsula 3 días antes del lanzamiento para acostumbrarse al espacio reducido. Los sensores mostraron que su frecuencia cardíaca se triplicó durante el lanzamiento (de 103 a 315 latidos por minuto) y que su ritmo respiratorio también aumentó dramáticamente. Alcanzó una órbita de entre 212 km (perigeo) y 1627 km (apogeo) alrededor de la Tierra. En cada órbita, que duraba 103.7 minutos, Laika daba la vuelta completa al planeta.',
    'Por décadas, el gobierno soviético afirmó que Laika había vivido entre 4 y 7 días en el espacio y que había muerto pacíficamente cuando se agotó el oxígeno. La verdad no se supo hasta el año **2002**, cuando el científico ruso **Dmitri Malashenkov** reveló en una conferencia de la Sociedad de Cosmonáutica que Laika había muerto entre 5 y 7 horas después del lanzamiento por el calor. Un fallo en el sistema de control térmico hizo que la temperatura dentro de la cápsula subiera a 40°C. Laika murió de estrés y sobrecalentamiento, no de forma pacífica como se había dicho. Esta revelación generó una ola internacional de debate ético sobre el uso de animales en la investigación científica.',
    'El Sputnik 2 orbitó la Tierra **2570 veces** durante 162 días antes de reentrar en la atmósfera el 14 de abril de 1958 y desintegrarse. Como la misión no tenía sistema de reentrada ni paracaídas (era imposible técnicamente en ese momento), nunca hubo posibilidad de recuperar a Laika. Los datos que envió el Sputnik 2 durante las pocas horas que los sistemas funcionaron correctamente fueron invaluables: demostraron por primera vez que un mamífero podía sobrevivir al lanzamiento y a las condiciones de órbita, aunque fuera por pocas horas. Esta información fue esencial para planificar los primeros vuelos humanos.',
  ]},
  { id: 'laika_s2', title: 'Lo Que Laika Enseñó a la Ciencia', image: '/assets/animales/animales_laika.png', text: [
    'Los datos científicos recolectados durante el vuelo de Laika revolucionaron nuestra comprensión de la **fisiología en el espacio**. Los sensores mostraron que durante los primeros 3 orbitas, la frecuencia cardíaca de Laika fue 3 veces su nivel normal en reposo, y su respiración era errática. Sin embargo, hacia la 4ª órbita, ambos parámetros comenzaban a normalizarse ligeramente antes de que el calor la matara. Este patrón de "estrés seguido de adaptación" fue el primer indicio de que el sistema nervioso autónomo de los mamíferos puede adaptarse a las condiciones espaciales. El mismo patrón fue confirmado en todos los vuelos espaciales humanos subsiguientes.',
    'Los datos de **radiación cósmica** medidos a bordo del Sputnik 2 fueron especialmente importantes. En 1957, los científicos sabían que existía radiación cósmica (descubierta por Victor Hess en 1911), pero no tenían certeza de cuánta había en órbita terrestre baja o qué efecto tendría sobre organismos vivos. Los instrumentos del Sputnik 2 confirmaron que la radiación en órbita era significativamente mayor que en la superficie terrestre, pero dentro de los límites que un organismo podría tolerar durante periodos relativamente cortos. Esta medición fue la base para diseñar el blindaje de radiación de las cápsulas Mercury, Vostok y Voskhod.',
    'El vuelo de Laika también generó el primer estudio serio sobre los **efectos psicológicos del confinamiento extremo** en mamíferos. Antes del lanzamiento, los investigadores observaron el comportamiento de Laika en simuladores de la cápsula durante semanas. Notaron que al principio mostraba signos de estrés (gruñidos, intentos de escapar), pero después de 15-20 días se adaptaba y dormía tranquilamente incluso en el espacio reducido. Este proceso de **habituación al estrés del confinamiento** se convirtió en la base del entrenamiento psicológico de los cosmonautas soviéticos, que incluía períodos obligatorios en cámaras de aislamiento.',
    'La misión de Laika fue también una demostración de que era posible **monitorizar remotamente** las funciones vitales de un ser vivo en el espacio. Los ingenieros soviéticos desarrollaron sensores biomédicos en miniatura que pesaban apenas gramos y podían transmitir datos vía radio. Esta tecnología fue el precursor directo de todos los sistemas de **telemedicina** modernos: los aparatos que hoy miden el ritmo cardíaco, la saturación de oxígeno y la presión arterial de pacientes en hospitales usan principios desarrollados en los años 1950 para monitorizar animales en el espacio.',
    'A nivel cultural y político, Laika tuvo un impacto enorme. El lanzamiento del Sputnik 2 apenas un mes después del Sputnik 1 (octubre de 1957) demostró que la URSS tenía una capacidad tecnológica muy superior a lo que Occidente había estimado. El presidente Eisenhower creó la **NASA** en respuesta directa (fue establecida en julio de 1958). El "Shock del Sputnik" provocó una reforma total del sistema educativo estadounidense, con énfasis en ciencias y matemáticas (la ley NDEA de 1958 invirtió miles de millones en educación científica). Paradójicamente, una perra callejera de Moscú transformó la educación científica de toda una generación de estadounidenses.',
  ]},
  { id: 'laika_s3', title: 'El Legado de Laika y la Ética Animal', image: '/assets/animales/animales_laika.png', text: [
    'Laika se convirtió en uno de los íconos culturales más reconocibles del siglo XX. Su imagen aparece en sellos postales de más de **40 países** diferentes. En Moscú, existe un monumento en su honor en el Instituto de Medicina Militar, cerca del lugar donde fue entrenada. En 2008, se instaló una placa conmemorativa. El escritor francés Jean-Marc Reiser publicó en 1977 una conmovedora historia corta imaginando los últimos momentos de Laika. La película cubana "Laika" (2017) y numerosas canciones, novelas y obras de arte han sido inspiradas por su historia. Laika se convirtió en símbolo no solo del avance científico sino de la soledad y el sacrificio en la exploración del cosmos.',
    'El debate ético generado por la muerte de Laika aceleró el desarrollo de **regulaciones internacionales** para la investigación con animales. En 1959, los científicos William Russell y Rex Burch publicaron "The Principles of Humane Experimental Technique", que introdujo el principio de las **3 Rs**: Reemplazar animales con métodos alternativos cuando sea posible, Reducir el número de animales al mínimo necesario, y Refinar los procedimientos para minimizar el sufrimiento. Estas 3 Rs son hoy la base de toda la legislación de bienestar animal en investigación científica en la Unión Europea, Estados Unidos y más de 50 países.',
    'En la Unión Soviética, la misión de Laika fue presentada como un triunfo patriótico sin cuestionamiento ético. Sin embargo, algunos de los científicos que trabajaron con ella expresaron privadamente su remordimiento. **Oleg Gazenko**, uno de los principales científicos del programa, dijo en 1998: "Cuanto más pasa el tiempo, más me pesa. No deberíamos haberlo hecho. No aprendimos suficiente de esa misión para justificar la muerte de Laika." Esta declaración, hecha 41 años después del vuelo, fue un gesto de honestidad científica poco común y muy valorado por la comunidad internacional.',
    'Las perras soviéticas que siguieron a Laika, especialmente **Belka y Strelka** (que regresaron vivas del espacio en 1960), demostraron que los avances técnicos permiten hacer ciencia sin sacrificar vidas animales innecesariamente. Hoy en día, los experimentos con animales en la ISS usan técnicas mínimamente invasivas. Los ratones que viven a bordo de la estación tienen acceso a ruedas de ejercicio, comida variada, agua fresca y espacio suficiente para moverse. Al regresar a la Tierra, son sometidos a análisis biológicos exhaustivos y luego viven el resto de su vida natural en instalaciones de investigación certificadas.',
    'El nombre "Laika" en ruso significa "ladradora", y también es el nombre de una raza de perros siberianos de trineo. Pero en el mundo entero, "Laika" significa hoy mucho más: representa el primer ser vivo consciente que contempló la Tierra desde el espacio. Aunque no sobrevivió para contarlo, los datos que generó con su cuerpo permitieron que otros sí pudieran hacerlo. Yuri Gagarin, el primer humano en el espacio, dijo en 1961: "Laika preparó el camino para mí." Sin Laika, sin Ham, sin Belka y Strelka, sin los Albert I al V, la carrera espacial humana habría comenzado con muchas más tragedias. Estos animales pagaron el precio del conocimiento que nosotros ahora damos por sentado.',
  ]},
],

animales_gatos: [
  { id: 'gatos_s1', title: 'Félicette: La Gata Astronauta', image: '/assets/animales/animales_gatos.png', text: [
    '**Félicette** fue la primera gata (y única gata) en volar al espacio. Era una pequeña gata blanca y negra que fue lanzada desde el **Centro de Pruebas de Hammaguir** en el desierto de Argelia (entonces territorio francés) el **18 de octubre de 1963**. Francia se convirtió así en el tercer país en enviar un ser vivo al espacio, después de la URSS y Estados Unidos. Félicette viajó en una cápsula del cohete Véronique AG1 y alcanzó una altitud de **157 kilómetros**, pasando la línea de Kármán (100 km) durante aproximadamente 13 minutos, con 5 minutos de experiencia de microgravedad real.',
    'El **Centre National d\'Études Spatiales (CNES)** de Francia seleccionó a Félicette entre 14 candidatas felinas después de meses de pruebas. Irónicamente, el programa francés comenzó entrenando a un gato llamado **Félix**, pero escapó poco antes del lanzamiento, lo que obligó a sustituirlo rápidamente por Félicette. Los gatos fueron elegidos porque su sistema nervioso autónomo y sus respuestas al estrés son bien conocidos por la neurociencia, y porque son fáciles de trabajar con ellos en laboratorio. Félicette tenía implantados electrodos en su cerebro que transmitían señales de actividad neuronal durante el vuelo, una información científica de enorme valor.',
    'Los datos cerebrales de Félicette fueron los primeros obtenidos de un animal en el espacio. Los **electrodos** en su corteza cerebral transmitían electroencefalogramas en tiempo real durante toda la misión. Los científicos monitorizaron su actividad neurológica durante el lanzamiento (señal de alta actividad por el estrés), durante la microgravedad (actividad cerebral sorprendentemente similar al estado de vigilia tranquila en Tierra) y durante el reingreso. El hallazgo más importante fue que las neuronas de Félicette seguían disparando patrones coherentes en microgravedad, lo que significaba que el cerebro de un mamífero puede funcionar normalmente sin la influencia constante de la gravedad.',
    'La cápsula de Félicette aterrizó con paracaídas en el desierto argelino **15 minutos** después del lanzamiento. Félicette fue recuperada viva y en aparente buen estado. Los médicos veterinarios realizaron exámenes completos durante varios días: su peso, temperatura, reflejos, comportamiento, niveles hormonales y función neurológica eran todos normales. Vivió durante **2 meses** después del vuelo antes de que los científicos, lamentablemente, la sacrificaran para analizar su cerebro en busca de cambios causados por la exposición a la radiación cósmica y la microgravedad. Este procedimiento era estándar en la medicina experimental de los años 1960.',
    'Por décadas, Félicette fue olvidada por la historia. A diferencia de Laika, Ham o los perros soviéticos, ningún monumento le fue erigido hasta **2019**, cuando una campaña de crowdfunding internacional recaudó más de 57,000 dólares para crear una estatua de bronce de Félicette que fue instalada en la **International Space University** en Estrasburgo, Francia. La campaña fue impulsada por el periodista espacial Matthew Serrano, quien señaló la injusticia histórica de que durante décadas se le había atribuido el vuelo a un gato inexistente llamado "Félix". La estatua muestra a Félicette sobre un globo terráqueo, mirando hacia las estrellas.',
  ]},
  { id: 'gatos_s2', title: 'Otros Animales Franceses en el Espacio', image: '/assets/animales/animales_gatos.png', text: [
    'Francia no se limitó a los gatos en su programa espacial. En febrero de 1961, dos años antes que Félicette, Francia lanzó **ratas** (llamadas Hector, Castor y Pollux) en cohetes de sondeo. Estas ratas llevaban también electrodos cerebrales y demostraron que el sistema nervioso de los roedores funciona de manera similar en el espacio que en la Tierra. Hector fue el primero en volar (22 de febrero de 1961) y también fue recuperado vivo. Estos experimentos fueron parte del programa que eventualmente llevaría a los vuelos humanos europeos en la era de la **Agencia Espacial Europea (ESA)**.',
    'El programa de animales en el espacio no fue solo soviético y estadounidense. El **Reino Unido** lanzó varias ranas y gusanos en cohetes. **China** comenzó su propio programa en 1964 con perros y ratas. **Argentina** lanzó una rata llamada Belisario en 1967. **Yugoslavia** envió una perra llamada Pepa en 1963. Estos programas nacionales, aunque menos conocidos que los de las superpotencias, contribuyeron datos sobre **biología en diferentes zonas geográficas**: la altitud del sitio de lanzamiento, la latitud y la proximidad a las bandas de radiación de Van Allen afectan la exposición a la radiación, y estos programas ayudaron a mapear esos efectos con mayor precisión.',
    'Los **insectos** también han sido pasajeros frecuentes en misiones espaciales. Las abejas fueron enviadas al espacio en el transbordador Challenger en 1984, en una misión llamada "Colony in Space" dirigida por estudiantes de secundaria. Las abejas en microgravedad tardaron **varios días** en adaptarse para construir su panal: al principio construían celdas deformes y asimétricas, pero gradualmente aprendieron a compensar la falta de gravedad. Este experimento fue el primero en demostrar que los insectos sociales pueden reorganizar su comportamiento para adaptarse a condiciones espaciales, lo que tiene implicaciones para el diseño de sistemas de polinización en futuras bases lunares o marcianas.',
    'Las **arañas** han sido objeto de múltiples estudios espaciales. En 1973, dos arañas llamadas Arabella y Anita viajaron a bordo del **Skylab 3**. En microgravedad, Arabella inicialmente construía telarañas caóticas e irregulares. Sin embargo, después de varios días, sus telarañas se volvieron cada vez más simétricas y regulares, aunque nunca idénticas a las terrestres: eran más finas en el centro y más gruesas en los bordes, probablemente porque la araña usaba señales visuales (la luz) para orientarse en lugar de la gravedad. Este experimento, diseñado originalmente por una estudiante de secundaria de Massachusetts llamada **Judy Miles**, demostró la plasticidad conductual de los arácnidos.',
    'El futuro de los animales en el espacio incluye experimentos con **especies migratorias**. Los científicos quieren entender cómo las aves migratorias, que usan el campo magnético terrestre para orientarse, se comportarían en el espacio donde el campo magnético varía significativamente. También hay planes para estudiar **peces eléctricos** (como los peces torpedo) en microgravedad, ya que su sistema de electrorrecepción podría proporcionar información sobre cómo diseñar sensores artificiales para naves espaciales. La lista de animales que han estado en el espacio incluye hoy más de 50 especies diferentes, desde bacterias hasta primates, y cada una ha contribuido a hacer el espacio un poco más comprensible y accesible para los humanos.',
  ]},
  { id: 'gatos_s3', title: 'La Neurociencia Espacial Animal', image: '/assets/animales/animales_gatos.png', text: [
    'Los experimentos neurológicos con Félicette abrieron un campo completamente nuevo: la **neurociencia espacial**. Los científicos querían saber si el cerebro de un mamífero funcionaba de manera diferente en ausencia de gravedad. La gravedad es una constante que ha estado presente durante toda la evolución de los vertebrados: todos nuestros sentidos, nuestro sentido del equilibrio, nuestra percepción de "arriba" y "abajo", están profundamente influenciados por la gravedad. ¿Qué le pasa al cerebro cuando esa constante desaparece?',
    'Los datos de Félicette mostraron que la actividad en la **corteza cerebral** durante la microgravedad era sorprendentemente normal, pero que el **cerebelo** (la región que coordina el equilibrio y el movimiento) mostraba patrones de actividad inusuales durante los primeros minutos de ingravidez. Esto confirmó lo que los médicos habían sospechado: la desorientación inicial que los astronautas reportan en el espacio no es un problema de la mente consciente, sino del cerebelo tratando de reconciliar señales contradictorias entre los ojos (que ven un entorno normal) y el sistema vestibular del oído interno (que ya no detecta "abajo").',
    'En la ISS moderna, los **neurocientíficos** estudian el cerebro humano en el espacio usando tecnologías que Félicette nunca podría haber imaginado. El experimento **NeuroMapping** usa resonancia magnética portátil para medir cambios en el volumen del cerebro durante misiones de larga duración. Los resultados son sorprendentes: los astronautas que pasan más de 6 meses en el espacio muestran un aumento en el volumen de **líquido cefalorraquídeo** en el cráneo, compresión de la glándula pituitaria, y cambios en la sustancia blanca del cerebro similares a los observados en algunos pacientes con hipertensión intracraneal. Estos cambios se reducen pero no desaparecen completamente en los meses después del regreso a la Tierra.',
    'Los estudios de comportamiento animal en el espacio han revelado algo fascinante: las **jerarquías sociales** entre animales también cambian en microgravedad. Grupos de ratones enviados a la ISS muestran inicialmente comportamientos de estrés y agresión (similar a lo que ocurre cuando se los pone en un espacio nuevo). Pero después de 2-3 semanas, desarrollan un comportamiento completamente nuevo y nunca observado en la Tierra: comienzan a correr en grupos circulares alrededor de las paredes de su habitáculo, todos en la misma dirección, durante horas. Los científicos aún no entienden completamente este comportamiento, pero podría estar relacionado con la necesidad de estimulación vestibular que la microgravedad no proporciona.',
    'El legado de Félicette, los Alberts, Laika, Ham y todos los demás animales espaciales es inmenso y a menudo invisible. Las **UCI neonatales** modernas, donde bebés prematuros lucha por sobrevivir, usan sistemas de monitorización de constantes vitales derivados directamente de los desarrollados para animales en el espacio. Las **cámaras hiperbáricas** usadas para tratar la enfermedad de descompresión en buzos usan principios aprendidos al estudiar cómo la presión atmosférica afecta a los animales en vuelos espaciales. Los **sensores de CO₂** usados en submarinos y minas fueron perfeccionados usando datos de los sistemas de soporte vital de cápsulas espaciales. La exploración espacial animal nos dio, sin quererlo, herramientas médicas que salvan miles de vidas humanas cada año en la Tierra.',
  ]},
],

};

// Process all modules
for (const [moduleId, sections] of Object.entries(CONTENT)) {
  replaceModule(moduleId, sections);
}
console.log('\nAll animales modules rebuilt!');
