const fs = require('fs');
const path = require('path');
const COURSE_DATA_PATH = path.join(__dirname, '../lib/courseData.js');

function findSectionsRange(text, moduleId) {
  const s1 = '"id": "' + moduleId + '"';
  const s2 = '"id":"' + moduleId + '"';
  let idIdx = text.indexOf(s1);
  if (idIdx < 0) idIdx = text.indexOf(s2);
  if (idIdx < 0) return null;
  const ceIdx = text.indexOf('"contentEs"', idIdx);
  if (ceIdx < 0 || ceIdx - idIdx > 5000) return null;
  const sectIdx = text.indexOf('"sections"', ceIdx);
  if (sectIdx < 0) return null;
  const arrStart = text.indexOf('[', sectIdx);
  if (arrStart < 0) return null;
  let depth = 0, arrEnd = arrStart;
  for (let i = arrStart; i < text.length; i++) {
    if (text[i] === '[') depth++;
    else if (text[i] === ']') { depth--; if (depth === 0) { arrEnd = i; break; } }
  }
  return { arrStart, arrEnd };
}

function replaceModule(moduleId, newSections) {
  let text = fs.readFileSync(COURSE_DATA_PATH, 'utf8');
  const range = findSectionsRange(text, moduleId);
  if (!range) { console.error('NOT FOUND: ' + moduleId); return; }
  const { arrStart, arrEnd } = range;
  const newArr = JSON.stringify(newSections, null, 6);
  text = text.substring(0, arrStart) + newArr + text.substring(arrEnd + 1);
  fs.writeFileSync(COURSE_DATA_PATH, text, 'utf8');
  console.log('OK: ' + moduleId + ' (' + newSections.reduce((s,x)=>s+x.text.length,0) + ' paras)');
}

const CONTENT = {

pioneros_alan: [
  { id: 'pioneros_alan_s1', title: 'Alan Shepard: El Primer Estadounidense en el Espacio', image: '/assets/pioneros/alan.png', text: [
    '**Alan Bartlett Shepard Jr.** nació el 18 de noviembre de 1923 en East Derry, New Hampshire, en una familia de tradición militar. Desde pequeño mostró una fascinación por la aviación y los aviones. Estudió en la Academia Naval de los Estados Unidos y se graduó en 1944, justo a tiempo para servir en la Segunda Guerra Mundial como oficial de destructor. Después de la guerra se convirtió en piloto de pruebas de la Marina, volando más de 40 tipos diferentes de aeronaves y acumulando más de 8000 horas de vuelo. Era conocido por su frialdad bajo presión, su perfeccionismo técnico y un sentido del humor sarcástico que sus compañeros apodaban "El Amigo Frío".',
    'En 1959, la NASA seleccionó a los **7 astronautas Mercury originales** de entre 508 candidatos: John Glenn, Gus Grissom, Scott Carpenter, Gordon Cooper, Wally Schirra, Deke Slayton y Alan Shepard. Todos eran pilotos de prueba militares con al menos 1500 horas de vuelo en aviones de alto rendimiento y títulos universitarios en ciencias o ingeniería. Shepard fue seleccionado por ser, según los evaluadores médicos y psicológicos, el candidato con las mejores respuestas fisiológicas al estrés y la mejor capacidad de tomar decisiones bajo condiciones extremas. Sin embargo, Deke Slayton fue retirado de los vuelos por una arritmia cardíaca y Glenn fue el más mediático. Shepard trabajó en silencio.',
    'El **5 de mayo de 1961**, a las 9:34 AM hora del Este, Alan Shepard se convirtió en el primer estadounidense en el espacio. A bordo de la cápsula **Freedom 7** (también llamado Mercury-Redstone 3), fue lanzado desde Cabo Cañaveral. El vuelo duró **15 minutos y 22 segundos**: subió a 187 km de altitud, experimentó 5 minutos de ingravidez, y aterrizó en el Océano Atlántico a 486 km del punto de lanzamiento. Fue recuperado por el helicóptero USS Lake Champlain. Aunque fue un vuelo suborbital (no dio la vuelta completa a la Tierra como Yuri Gagarin 23 días antes), demostró que Estados Unidos podía enviar un humano al espacio y traerlo de vuelta sano y salvo.',
    'Durante el vuelo, Shepard experimentó fuerzas G de hasta **6.3G** durante el lanzamiento y **11.6G** durante el reingreso, sentadas opresoras que comprimían su cuerpo contra el asiento. Sin embargo, mantuvo la calma y siguió el protocolo. Realizó pruebas de control manual de la cápsula (inclinando la Freedom 7 usando pequeños propulsores de actitud) y reportó visibilidad perfecta de la Tierra desde la ventana. Sus palabras más famosas durante el vuelo fueron pronunciadas antes del lanzamiento, cuando hubo un retraso de horas por problemas técnicos y alguien le preguntó cómo estaba: "Por favor, resuelvan sus problemas y enciendan esa vela." La frase, llena de impaciencia y determinación, se volvió legendaria.',
    'Shepard recibió una recepción de héroe: el presidente Kennedy le recibió en la Casa Blanca, fue aclamado con desfiles en varias ciudades, y se convirtió en el símbolo viviente del espíritu americano de aventura. Pero su historia no terminó ahí. En 1963 fue diagnosticado con **enfermedad de Ménière**, un trastorno del oído interno que causa vértigo severo e imposibilitó que volara durante 6 años. En ese tiempo pasó de ser astronauta activo a administrador del programa de astronautas de la NASA. Una cirugía experimental en 1968 corrigió su problema, y Shepard regresó a la lista activa de vuelo con 47 años, convirtiéndose en el astronauta de mayor edad en volar hasta ese momento.',
  ]},
  { id: 'pioneros_alan_s2', title: 'Apollo 14: Shepard en la Luna', image: '/assets/pioneros/alan.png', text: [
    'El momento más memorable de la carrera de Alan Shepard llegó en **febrero de 1971**: fue el comandante del **Apollo 14**, la tercera misión en alunizar. Shepard y el piloto del módulo lunar **Edgar Mitchell** pasaron 33 horas y 30 minutos en la superficie lunar, realizando dos caminatas lunares que totalizaron 9 horas y 23 minutos. Aterrizaron en la región de **Fra Mauro**, una zona geológicamente importante donde esperaban encontrar rocas del Imbrian Temprano, el período en que un asteroide masivo creó la cuenca del Mar de las Lluvias hace 3.85 mil millones de años.',
    'Shepard y Mitchell caminaron hasta el cráter **Cone**, de 305 metros de diámetro, para recolectar rocas del borde que los geólogos creían que habrían sido excavadas del subsuelo lunar, dando información sobre capas más profundas de la corteza lunar. El ascenso fue físicamente agotador: en trajes de 84 kg caminando en un terreno irregular. Llegaron a unos 20 metros del borde antes de tener que regresar por falta de tiempo y oxígeno. Aun así, recolectaron **42.28 kg de rocas lunares**, incluyendo muestras de **basalto anortosítico** que tenían más de 4,000 millones de años, entre las rocas más antiguas que los humanos han tocado.',
    'Alan Shepard es famoso mundialmente por un gesto aparentemente frívolo pero científicamente interesante: en la Luna, sacó una cabeza de palo de golf de **6 hierro** y golpeó dos pelotas de golf. Dijo que la segunda pelota voló "millas y millas" en el vacío lunar. La estimación real es que voló unos **200-400 metros**, porque en la Luna la gravedad es solo 1/6 de la terrestre y no hay atmósfera que frene la pelota. Este momento fue transmitido en vivo por televisión y fue el primer "deporte" jugado en otro mundo. El palo y las dos pelotas están ahora expuestos en el **Museo Nacional del Aire y el Espacio** en Washington D.C.',
    'La misión Apollo 14 estuvo a punto de ser cancelada. Durante el viaje a la Luna, el módulo lunar **Antares** sufrió un fallo en el sistema de radar de aborto: el radar enviaba señales que habrían disparado automáticamente el motor de ascenso durante el descenso, abortando la misión. Los ingenieros del **MIT** y de la NASA trabajaron durante horas para escribir un parche de software que fuera cargado al ordenador de a bordo mediante el teclado manual (52 teclas de entrada de datos). El parche fue enviado con apenas 7 minutos de margen antes del inicio del descenso. Fue uno de los primeros ejemplos de **debugging de software en tiempo real** en el espacio, y sentó las bases para los procedimientos modernos de mantenimiento de software en misiones espaciales.',
    'Alan Shepard se retiró de la NASA en 1974 y se dedicó a los negocios, amasando una considerable fortuna como inversor en bienes raíces y cervecerías. También fue cofundador de la **Mercury Seven Foundation** (hoy llamada Astronaut Scholarship Foundation), que otorga becas anuales a estudiantes de ciencia e ingeniería. Murió de **leucemia** el 21 de julio de 1998, a los 74 años, en Pebble Beach, California. Su esposa Louise murió 5 semanas después, según sus familiares de pena. Alan Shepard fue la encarnación del coraje científico: el hombre que pasó de ser el primero en ver la Tierra desde el espacio a ser uno de los pocos humanos que han caminado en otro mundo.',
  ]},
  { id: 'pioneros_alan_s3', title: 'El Legado Científico de Freedom 7', image: '/assets/pioneros/alan.png', text: [
    'El vuelo de Alan Shepard el 5 de mayo de 1961 fue mucho más que un logro político para Estados Unidos. Generó datos científicos fundamentales. La **Freedom 7** llevaba instrumentos para medir la radiación cósmica en el espacio suborbital, registros de las fuerzas G experimentadas por el cuerpo humano durante el lanzamiento y reingreso, y datos detallados sobre el rendimiento cognitivo de Shepard bajo estrés extremo. Los ingenieros de la NASA analizaron cada segundo de telemetría para refinar los sistemas de soporte vital, los trajes espaciales y los sistemas de control de las futuras misiones Mercury, Gemini y Apollo.',
    'Shepard demostró que un humano podía **operar controles manualmente en el espacio**. Antes de su vuelo, algunos científicos temían que la ingravidez pudiera causar confusión mental, pérdida de control motor fino o incapacidad de tomar decisiones. Shepard inclinó la cápsula manualmente en tres ejes diferentes durante los 5 minutos de microgravedad, siguiendo un protocolo predefinido. Sus respuestas fueron perfectas. Este resultado fundamental fue lo que convenció al presidente Kennedy de que podría anunciarse el objetivo de llegar a la Luna: si un astronauta podía controlar una cápsula en el espacio, eventualmente podría controlar un módulo lunar durante un alunizaje.',
    'El presidente Kennedy hizo su famoso discurso ante el Congreso solo **20 días** después del vuelo de Shepard: "Creo que esta nación debe comprometerse a alcanzar el objetivo, antes de que termine esta década, de poner a un hombre en la Luna y traerlo de regreso a la Tierra sano y salvo." Sin el éxito de Freedom 7, este anuncio no habría sido políticamente posible. El vuelo de Shepard dio a Kennedy la credibilidad necesaria para hacer una promesa que muchos científicos y políticos consideraban audaz hasta el extremo. El camino de Shepard a la Luna (que ocurrió 10 años después) comenzó ese martes de mayo de 1961.',
    'La **cápsula Freedom 7** sobrevivió al vuelo y hoy es una de las piezas más valiosas del patrimonio de la historia espacial. Fue recuperada del Atlántico, restaurada, y está expuesta en el **Centro Espacial Kennedy** en Florida. Los visitantes pueden ver las marcas de calor en el escudo térmico, las pequeñas ventanas por las que Shepard vio la curvatura de la Tierra por primera vez, y el interior de 1.7 metros de diámetro donde un hombre cruzó la frontera del espacio. También se conservan sus registros de biometría del vuelo, que muestran la frecuencia cardíaca de Shepard (de 80 lpm en reposo a 138 lpm durante el lanzamiento y de regreso a 92 lpm en microgravedad).',
    'El legado más duradero de Alan Shepard no es haber sido el primero en el espacio ni haber jugado golf en la Luna. Es haber demostrado que la **voluntad humana** puede superar obstáculos que parecen imposibles. Fue el primero, luego fue descalificado por enfermedad, y aun así regresó a los 47 años para caminar en la Luna. Enseñó a una generación que los fracasos temporales no definen una carrera ni una vida. La **Astronaut Scholarship Foundation** que cofundó ha otorgado más de 4,000 becas por valor de más de 4 millones de dólares a jóvenes estudiantes de ciencias. El legado de Shepard vive en cada científico e ingeniero que esas becas han ayudado a formar.',
  ]},
],

pioneros_valentina: [
  { id: 'valentina_s1', title: 'Valentina Tereshkova: La Primera Mujer en el Espacio', image: '/assets/pioneros/valentina.png', text: [
    '**Valentina Vladimirovna Tereshkova** nació el 6 de marzo de 1937 en Maslennikovo, una pequeña aldea a orillas del río Volga en Rusia. Su padre Ivan murió en la Segunda Guerra Mundial cuando ella tenía apenas 2 años, y su madre fue agricultora colectiva. A los 18 años comenzó a trabajar en una fábrica textil para ayudar a su familia. Su vida cambió cuando descubrió el paracaidismo: a los 22 años hizo su primer salto, y en los años siguientes realizó más de **163 saltos** con el Club de Paracaidismo de Yaroslavl. Esta habilidad, insólita para una joven obrera, llamó la atención del programa espacial soviético.',
    'Después del vuelo de Yuri Gagarin en 1961, el liderazgo soviético quería demostrar otra "primera" al mundo: enviar a una mujer al espacio antes que los Estados Unidos. **Nikita Khrushchev** ordenó personalmente que se buscara a candidatas entre las paracaidistas civiles. Tereshkova fue una de las cinco finalistas seleccionadas de entre más de 400 candidatas. Las otras cuatro eran Tatiana Kuznetsova, Irina Solovyova, Valentina Ponomareva y Zhanna Yorkina. Ninguna de ellas tenía experiencia como piloto o ingeniera, pero todas tenían experiencia en paracaidismo (fundamental para el sistema de eyección del Vostok) y buena salud física y mental.',
    'Tereshkova fue seleccionada como candidata principal principalmente por razones políticas además de técnicas: era la hija de un héroe de guerra, obrera de fábrica (imagen perfecta de la clase trabajadora soviética), miembro del Komsomol (organización juvenil comunista), y tenía una personalidad carismática y extrovertida ideal para representar a la URSS en el escenario mundial. En 19 meses de entrenamiento intensivo, aprendió a pilotar aviones a reacción, resistió pruebas de aislamiento de 10 días, centrifugadoras a 8G, vuelos en parábola para simular ingravidez, y estudió ingeniería espacial básica. Según sus instructores, fue una estudiante aplicada aunque técnicamente no era tan brillante como las otras candidatas.',
    'El **16 de junio de 1963**, Valentina Tereshkova fue lanzada a bordo del **Vostok 6** desde el Cosmódromo de Baikonur. Tenía 26 años. Usó el nombre en clave **"Chaika"** (Gaviota) durante las comunicaciones de radio. Su misión duró **2 días, 22 horas y 50 minutos**, durante los cuales completó **48 órbitas** alrededor de la Tierra. El Vostok 5, pilotado por Valery Bykovsky, estaba en órbita al mismo tiempo, y los dos cosmonautas se comunicaron por radio. Esta fue la primera vez que dos naves espaciales estuvieron en órbita simultáneamente con comunicación directa entre ellas.',
    'Las condiciones del vuelo fueron duras. Tereshkova desarrolló **náuseas severas** desde las primeras horas (el "mal de espacio" afecta a cerca del 50% de los astronautas). También hubo un problema técnico no anunciado públicamente hasta 30 años después: un error en el programa de vuelo automático hacía que la cápsula subiera en lugar de bajar la órbita cuando se activaba el piloto automático. Si Tereshkova no hubiera detectado el error y reportado a tierra para que los ingenieros corrigieran el software manualmente, la cápsula habría subido a una órbita cada vez más alta y nunca habría regresado. Su observación calmada y precisa bajo presión salvó la misión y probablemente su vida.',
  ]},
  { id: 'valentina_s2', title: 'El Vuelo y sus Datos Científicos', image: '/assets/pioneros/valentina.png', text: [
    'Los experimentos científicos del Vostok 6 incluyeron fotografía de la atmósfera terrestre y de la Tierra desde el espacio, medición de la radiación cósmica, y el primer estudio detallado de los efectos de la microgravedad en el cuerpo de una mujer. Los médicos querían saber si existían diferencias fisiológicas significativas entre hombres y mujeres en el espacio. Los resultados mostraron que el cuerpo de Tereshkova respondió de manera muy similar al de los cosmonautas masculinos: mismos patrones de frecuencia cardíaca, misma distribución de fluidos hacia la cabeza, mismo estrés en el sistema vestibular. Esta equivalencia fue científicamente importante: demostró que el sexo biológico no es un factor limitante para la exploración espacial.',
    'Tereshkova realizó observaciones visuales sistemáticas del horizonte terrestre desde su ventana. Sus descripciones detalladas de las capas de la atmósfera, especialmente la **capa de ozono** vista como una delgada banda azul brillante, se convirtieron en datos de referencia para los meteorólogos y climatólogos de la época. También fotografió nubes, océanos y zonas costeras con una cámara Konvas, generando imágenes que fueron las primeras fotografías de alta calidad de la superficie terrestre tomadas por un ser humano desde el espacio (las anteriores eran de cámaras automáticas sin observador humano).',
    'Uno de los momentos más emotivos del vuelo ocurrió cuando Tereshkova cruzó sobre la aldea de su madre en el Volga. Sabiendo que su familia no conocía el verdadero propósito de su "entrenamiento de paracaidismo", ella les había dicho que estaría en un campamento de entrenamiento durante semanas. Su madre solo supo que su hija había estado en el espacio cuando lo escuchó en la radio durante el vuelo. La imagen de la madre mirando al cielo mientras su hija orbitaba la Tierra a 200 km de altura a 28,000 km/h fue reproducida en medios de todo el mundo.',
    'El reingreso del Vostok 6 fue técnicamente exitoso pero físicamente brutal. A 7 km de altitud, Tereshkova **se eyectó** de la cápsula (el sistema Vostok no tenía aterrizaje dentro de la nave; los cosmonautas usaban paracaídas personales, igual que los primeros astronautas americanos). Aterrizó en una zona agrícola de la región de Karaganda en Kazajistán. Los campesinos locales que la encontraron dijeron que les pidió comida con urgencia (llevaba más de 70 horas con la comida de tubo de la NASA). Les regaló su ración espacial como recuerdo y comió pan y papas del campo. Fue recogida por el equipo de recuperación horas después.',
    'Después del vuelo, Tereshkova recibió la medalla **"Héroe de la Unión Soviética"**, el máximo honor civil soviético. Khrushchev la presentó al mundo como la imagen perfecta del socialismo: una obrera que había llegado al espacio. Se casó con el cosmonauta Andrian Nikolayev en una boda televisada en noviembre de 1963, y en 1964 tuvieron una hija llamada **Yelena**. Yelena fue el primer bebé en la historia cuya madre había estado en el espacio, y los médicos la vigilaron de cerca para ver si la exposición a la radiación cósmica de su madre antes del embarazo había causado algún efecto genético. No se observó ninguno.',
  ]},
  { id: 'valentina_s3', title: 'El Largo Camino Hacia la Igualdad en el Espacio', image: '/assets/pioneros/valentina.png', text: [
    'Después del vuelo de Tereshkova en 1963, pasaron **19 años** antes de que otra mujer fuera al espacio: **Svetlana Savitskaya** en 1982. La razón de esta brecha es compleja: la URSS usó el vuelo de Tereshkova principalmente como propaganda política, no como el inicio de un programa sistemático de cosmonautas femeninas. Las otras cuatro candidatas que habían entrenado con Tereshkova fueron descartadas sin volar. Khrushchev consideró que ya habían demostrado el punto y no había necesidad de enviar más mujeres al espacio en el corto plazo. Esta decisión política retrasó décadas la participación femenina en la exploración espacial.',
    'En Estados Unidos, el camino fue igualmente complicado. En 1960-1961, el programa **Mercury 13** reclutó a 13 mujeres pilotas de prueba (llamadas popularmente "las Mercury 13") que pasaron todas las pruebas médicas y psicológicas de la NASA con resultados iguales o mejores que los astronautas masculinos. Sin embargo, la NASA y el Congreso las rechazaron argumentando que los astronautas debían ser pilotos militares de prueba, carrera a la que las mujeres no tenían acceso en esa época. No fue hasta **1978** que la NASA aceptó astronautas femeninas en el programa. **Sally Ride** se convirtió en la primera astronauta estadounidense en el espacio en 1983.',
    'La razón fisiológica por la que las mujeres son **igual de aptas** para el espacio que los hombres es respaldada hoy por décadas de datos. En algunos aspectos, las mujeres presentan ventajas: en promedio tienen menor masa corporal (reduciendo el costo de lanzamiento), sus corazones son proporcionales a su cuerpo (lo que equivale a una mejor eficiencia cardiovascular en microgravedad), y estudios recientes del proyecto **Twins Study** de la NASA (que comparó al astronauta Scott Kelly con su gemelo Mark después de un año en el espacio) sugieren que el genoma femenino podría ser ligeramente más resistente al estrés de la radiación cósmica, aunque se necesitan más datos para confirmar esto.',
    'Valentina Tereshkova se convirtió en una figura política prominente después de su carrera como cosmonauta. Fue diputada del Soviet Supremo durante décadas, presidenta del Soviet de Mujeres Soviéticas, y representante de la URSS en la ONU. En 2011, con 74 años, declaró públicamente que estaría dispuesta a ir a Marte en un viaje sin retorno. En 2014 participó en la ceremonia de apertura de los **Juegos Olímpicos de Sochi**, llevando la bandera olímpica. Y en 2021, el Parlamento de Rusia (Duma) aprobó una ley que propuso ella misma para borrar los registros de ciertos crímenes menores, una acción de clemencia social en línea con su imagen pública de humanismo.',
    'El mensaje científico más importante de la misión de Tereshkova no fue un dato técnico sino una demostración sociológica: que el acceso al espacio no debería estar limitado por el género, la clase social ni el origen. Hoy, la **ISS** ha sido visitada por más de 70 mujeres de docenas de países. En 2024, más del 30% de los astronautas en activo de la NASA son mujeres. El programa **Artemis** planea poner a la primera mujer en la Luna. El camino que Tereshkova abrió en 1963, aunque ancho y difícil, lleva hoy a la Luna y más allá. Cada cosmonauta y astronauta femenina que sube a una nave espacial es el resultado de una joven obrera de Yaroslavl que saltó desde aviones en 1959 soñando con las estrellas.',
  ]},
],

pioneros_leonov: [
  { id: 'leonov_s1', title: 'Alexei Leonov: El Primer Humano en el Espacio Exterior', image: '/assets/pioneros/leonov.png', text: [
    '**Alexei Arkhipovich Leonov** nació el 30 de mayo de 1934 en Listvyanka, una pequeña aldea de Siberia. Era el octavo hijo de una familia numerosa. Estudió en la Escuela de Aviación Militar y luego en la Academia de las Fuerzas Aéreas Soviéticas, graduándose como piloto de caza. También era un artista talentoso: dibujaba y pintaba paisajes desde niño, habilidad que más tarde usaría para crear bocetos de la Tierra y del espacio desde su propia perspectiva como cosmonauta. Sus pinturas de la Tierra desde el espacio se exhiben en museos rusos y son consideradas documentos históricos únicos por combinar precisión científica con perspectiva artística personal.',
    'El **18 de marzo de 1965**, Leonov se convirtió en el primer ser humano en salir de una nave espacial y flotar en el espacio abierto: realizó la primera **EVA (Actividad Extra-Vehicular)** de la historia. A bordo de la Voskhod 2 junto con el comandante Pavel Belyayev, Leonov abrió una esclusa de aire inflable especialmente diseñada (llamada Volga) y salió al espacio durante **12 minutos y 9 segundos**. Flotó hasta alejarse unos 5 metros de la nave, conectado solo por un cordón umbilical de 5.35 metros que suministraba oxígeno y comunicaciones. Era la primera vez que un ser humano flotaba libre en el vacío del cosmos.',
    'La descripción de Leonov de ese momento es una de las más poéticas de la historia espacial: "Flotaba sobre nuestro planeta azul, que era tan hermoso y tan vulnerable. Sentí que era una gota de agua flotando en un océano cósmico." Sus sensores de traje registraron que su frecuencia cardíaca subió a **164 latidos por minuto** durante los primeros segundos fuera de la nave, pero se estabilizó rápidamente. La temperatura dentro del traje llegó a 35.5°C por el esfuerzo físico. Veía la Tierra rotar lentamente bajo sus pies, con Europa, el Mediterráneo y África pasando en silencio. El Sol, sin la atmósfera que lo filtra, brillaba con una intensidad cegadora.',
    'Entonces ocurrió una crisis casi fatal. El **traje espacial de Leonov se infló** por la diferencia de presión entre el interior del traje y el vacío exterior. Sus manos se salieron de los guantes, sus pies se salieron de las botas, y el traje rígido e hinchado se volvió prácticamente imposible de mover. Los brazos se alejaron del cuerpo. Las piernas no podían doblarse. Leonov no podía entrar de nuevo en la esclusa de aire: la abertura era demasiado estrecha para el traje inflado. Si no lograba entrar, moriría en el espacio en pocos minutos cuando se agotara el oxígeno.',
    'Leonov tomó la decisión más importante de su vida: en contra del protocolo, abrió la válvula de su traje y redujo la presión interna de **0.4 a 0.27 atmósferas** (el límite mínimo seguro antes del riesgo de embolia gaseosa, similar a la enfermedad de descompresión de los buzos). Con el traje parcialmente desinflado, pudo doblar los brazos y entrar en la esclusa de aire con la cabeza primero (el protocolo decía que debía entrar con los pies). El proceso le tomó **12 minutos**, durante los cuales el nivel de CO₂ en su traje subió a niveles peligrosos y su temperatura corporal aumentó 2°C. Entró exhausto, empapado en sudor, con el corazón latiendo a 190 bpm. Esta experiencia fue mantenida en secreto por la URSS durante décadas.',
  ]},
  { id: 'leonov_s2', title: 'El Regreso y el Programa Espacial Soviético', image: '/assets/pioneros/leonov.png', text: [
    'Los problemas del Voskhod 2 no terminaron con el reingreso de Leonov a la nave. El **sistema de orientación automática** falló durante la maniobra de reentrada, obligando a Belyayev a controlar manualmente el cohete de retrorretroalimentación con una palanca que nunca había usado en simulaciones para esta maniobra específica. Como resultado, la cápsula aterrizó **386 kilómetros más lejos** de lo planeado, en medio de la taiga siberiana densa y nevada a -30°C. Las temperaturas eran mortales para cualquier persona sin equipo de supervivencia adecuado.',
    'Los equipos de rescate no podían llegar a la zona de aterrizaje por helicóptero (los árboles eran demasiado densos) ni por tierra (no había caminos). Belyayev y Leonov pasaron **la noche entera** en la cápsula, sin calefacción funcional, mientras las autoridades decidían cómo rescatarlos. Al día siguiente, equipos de esquiadores y madereros llegaron a pie por el bosque y construyeron un refugio de troncos. Los cosmonautas pasaron una segunda noche en el bosque antes de que un helicóptero pudiera aterrizar en un claro preparado a 9 km de distancia. Caminaron hasta él con esquíes improvisados. Llegaron a Moscú al tercer día, cuando ya se les daba por muertos en algunos medios de comunicación occidentales.',
    'La misión Voskhod 2 cambió completamente el diseño de los **trajes espaciales** para EVA. Los ingenieros soviéticos y americanos (que en ese momento no sabían de la crisis del traje de Leonov, mantenida en secreto hasta 1990) rediseñaron independientemente los trajes para incluir sistemas de presurización más sofisticados, mayor flexibilidad en las articulaciones, y sistemas de emergencia de reducción de presión controlada. Los trajes **Berkut** usados en el Voskhod 2 fueron reemplazados por los **Yastreb** y luego los **Orlan**, que hoy usan los cosmonautas en la ISS. Los trajes americanos **EMU** (Extra-vehicular Mobility Unit) también incorporaron las lecciones de Leonov.',
    'Leonov fue el primer cosmonauta en dibujar lo que veía desde el espacio. Durante el vuelo, cuando no estaba realizando tareas técnicas, hacía bocetos a lápiz en una pequeña libreta. Sus dibujos del sol sobre la Tierra, de las estrellas sin atmósfera que las distorsione, y de la Tierra curvada en el horizonte fueron publicados en libros y se convirtieron en referencias visuales históricas. Más tarde, ya retirado, Leonov pintó **cuadros al óleo** grandes de sus experiencias espaciales. Algunos científicos usan estas pinturas como referencia para calibrar qué tan bien representan las fotografías digitales modernas los colores reales del espacio tal como los ven los humanos.',
    'En 1975, Leonov fue el comandante de la parte soviética de la histórica **misión Apollo-Soyuz**, el primer vuelo espacial conjunto entre Estados Unidos y la URSS durante la Guerra Fría. Las dos naves acoplaron en el espacio, y los astronautas americanos Tom Stafford y Deke Slayton se estrecharon la mano con Leonov y Valery Kubasov en el espacio, 140 km sobre Europa. Leonov servía de intérprete entre las dos tripulaciones (hablaba inglés). Esta misión, llamada "el apretón de manos en el espacio", fue un símbolo de distensión diplomática y demostró que la exploración espacial podía ser un proyecto de cooperación global en lugar de una carrera armamentística.',
  ]},
  { id: 'leonov_s3', title: 'El Arte y la Ciencia de Ver el Espacio', image: '/assets/pioneros/leonov.png', text: [
    'La combinación única de Leonov de habilidades artísticas y técnicas hizo de él un observador del espacio diferente a cualquier otro astronauta o cosmonauta. Sus descripciones de colores en el espacio son científicamente precisas y poéticamente ricas. Describió el **negro del espacio** como "un negro denso, no el negro de la noche en la Tierra, sino un negro que tiene profundidad, que parece sólido". Describió el **Sol sin atmósfera** como "un disco perfectamente definido, sin aureola, sin rayos, como un ojo que te mira directamente". Estas descripciones han ayudado a los científicos a entender cómo la ausencia de atmósfera afecta la percepción visual humana de la luz.',
    'Los **colores de la Tierra** desde el espacio también fueron documentados con precisión por Leonov. Describió el Mediterráneo como "turquesa intenso", los desiertos del Sahara como "ocre rojizo con reflejos de plata donde había arena fina", los océanos del Pacífico como "azul índigo que se acerca al negro en las zonas más profundas". Los climatólogos y oceanólogos han verificado que estas observaciones visuales corresponden con datos de reflectividad espectral medidos por satélites: el color que describía Leonov en el Mediterráneo efectivamente corresponde a las longitudes de onda características de las algas y la salinidad de ese mar.',
    'La experiencia de Leonov en el espacio exterior (la primera EVA) estableció protocolos de seguridad que protegen a todos los astronautas modernos. La regla de **doble tether** (dos cuerdas de seguridad independientes siempre conectadas a la nave durante una EVA) surgió directamente del casi accidente de Leonov. La regla de que los trajes de EVA siempre deben incluir un sistema de control de presión manual accesible por el propio astronauta también viene de esta misión. Y la práctica de realizar simulaciones de EVA en **piscinas de flotación neutra** (donde la flotación en el agua simula la microgravedad) fue desarrollada después de la misión de Leonov para preparar mejor a los astronautas para trabajar en el espacio exterior.',
    'Leonov se retiró del programa espacial en 1991 y se dedicó a la pintura, la escritura y las conferencias. Publicó varios libros de memorias y compilaciones de sus pinturas espaciales. En 1995 creó la fundación **"Leonov Art"** para promover el arte inspirado en la exploración espacial. Recibió el título de **Héroe de la URSS** dos veces (una por el Voskhod 2 y otra por Apollo-Soyuz), fue Doctor Honoris Causa de varias universidades, y recibió el Premio de la Academia de Artes de Rusia. Murió el **11 de octubre de 2019** a los 85 años, en Moscú, siendo el último superviviente de los cosmonautas del programa Voskhod.',
    'El legado de Alexei Leonov trasciende el récord histórico. Fue el primer humano en experimentar el espacio no desde dentro de una máquina sino directamente, cara a cara con el cosmos. Esa experiencia cambió profundamente su filosofía: "Cuando estás en el espacio, no piensas en tu país ni en tu partido político. Piensas en la Tierra, que es pequeña, azul y hermosa, y en que todos los seres humanos que has amado están ahí. Y te das cuenta de que tenemos que cuidarla." Esta perspectiva, que los psicólogos llaman el **Efecto Overview** (la transformación cognitiva que experimentan los astronautas al ver la Tierra desde el espacio), fue documentada por primera vez en las memorias de Leonov y hoy es un campo serio de investigación en psicología espacial.',
  ]},
],

};

for (const [moduleId, sections] of Object.entries(CONTENT)) {
  replaceModule(moduleId, sections);
}
console.log('\nAll pioneros modules rebuilt!');
